- src/app/pages/shell/shell.component.html
- src/app/pages/shell/shell.component.ts
- src/app/services/shell.service.ts
despite the ping message, it works
> Feature webshell

- .angular-cli.json
- src/app/components/common/topbar/topbar.component.ts
- src/app/components/common/topbar/topbar.template.html
- src/app/pages/common/entity/entity-form/entity-form.component.scss
- src/app/services/theme/theme.service.ts
- src/app/views/sessions/signin/signin.component.html
- src/assets/styles/themes/egret-blue.scss
- src/assets/styles/themes/egret-dark-pink.scss
- src/assets/styles/themes/egret-dark-purple.scss
- src/assets/styles/themes/egret-indigo.scss
- src/assets/styles/themes/freenas-sharks.scss
- src/assets/styles/themes/freenas-warriors.scss
- src/index.html
Forgot I was still using my personal repo, please accept this gift of awesome themes
> Theme updates

- .angular-cli.json
- src/app/components/common/lineChart/lineChart.component.ts
- src/app/components/common/lineChart/lineChart.scss
- src/app/pages/common/entity/fab-speed-dial/fab-speed-dial.scss
- src/assets/styles/egret_overrides.css
- src/assets/styles/themes/egret-dark-pink.scss
- src/assets/styles/themes/egret-dark-purple.scss
- src/assets/styles/themes/freenas-sharks.scss
- src/assets/styles/themes/freenas-warriors.scss
Summary: Made the tab groups, breadcrumbs and topbar fixed to top of screen. Also made cosmetic upgrades to line charts
https://github.com/freenas/webui/compare/linecharts-facelift1?expand=1#diff-c78e1fddb79799856010780b5453a800
https://github.com/freenas/webui/compare/linecharts-facelift1?expand=1#diff-30b85064daf79995d242c84ab5d268b
https://github.com/freenas/webui/compare/linecharts-facelift1?diff=unified&expand=1&name=linecharts-facelift1#diff-05907bc024245051669d758debc57335
https://github.com/freenas/webui/compare/linecharts-facelift1?diff=unified&expand=1&name=linecharts-facelift1#diff-eaf05700b7d0cdda38b49ab734a28a2
https://github.com/freenas/webui/compare/linecharts-facelift1?diff=unified&expand=1&name=linecharts-facelift1#diff-bbf3ab04f22ee9d591166802989c827 …
> Linecharts facelift1

- src/app/components/common/notifications/notifications.component.html
- src/app/components/common/notifications/notifications.component.ts
- src/app/components/common/topbar/topbar.component.ts
- src/app/services/notifications.service.ts
Fixed the notifications.  Nice little cache NotificationService that does all the polling and just divies out the cache to the toptoolbar.component.ts and the notification.component.ts.
This make a MUCH smooter use of the UI.. WAY less rest calls...  !!!  And seems to not overload teh API anymore.  Cool.
Reivew..
Main code all in NotificationService, toptoolbar.component, and notification.component.
Happy Weekend.
> Master notification fix

- src/app/pages/common/entity/entity-form/components/dynamic-field/dynamic-field.css
- src/app/pages/common/entity/entity-form/components/form-textarea/form-textarea.component.html
- src/app/pages/system/advanced/advanced.component.ts
I fixed https://bugs.freenas.org/issues/26117
Please review. Thanks
> Adding ascii art font on System -> advanced page(issue #26117)

- src/app/pages/sharing/iscsi/extent/extent-form/extent-form.component.ts
fixed the build for now, but still need to check out it
> Fixed broke build by pete, vb & lola

- src/app/services/app-loader/app-loader.component.html
- src/app/services/app-loader/app-loader.component.ts
- src/app/services/app-loader/app-loader.module.ts
- src/app/services/app-loader/app-loader.service.ts
Fixes: https://bugs.freenas.org/issues/25825
> Ticket 25825

- src/app/services/app-loader/app-loader.component.html
- src/app/services/app-loader/app-loader.component.ts
- src/app/services/app-loader/app-loader.module.ts
- src/app/services/app-loader/app-loader.service.ts
You have circular dependency error. 
```WARNING in Circular dependency detected:
src/app/services/app-loader/app-loader.component.ts -> src/app/services/app-loader/app-loader.service.ts -> src/app/services/app-loader/app-loader.component.ts```
Please check out the app-loader.component and app-loader.service. There is circular dependency over there.
> Revert "Ticket 25825"

- src/app/views/sessions/signin/signin.component.html
- src/app/views/sessions/signin/signin.component.ts
Bug Description: New/Beta UI - login screen does not behave properly when entering the wrong password
Fixes: https://bugs.freenas.org/issues/26372
> Ticket: 26372

- src/app/components/common/navigation/navigation.template.html
please review my change, do not delete this PR after merge as this is ongoing work towards QA automation.
> adding id's to sidenav

- src/app/components/common/lineChart/lineChart.component.ts
- src/app/components/common/lineChart/lineChart.service.ts
- src/app/pages/dashboard/dashboard.component.ts
I completed https://bugs.freenas.org/issues/25954
> Chentao fix 25954

- src/app/pages/common/entity/entity-delete/entity-delete.component.html
- src/app/pages/common/entity/entity-delete/entity-delete.component.ts
- src/app/pages/storage/volumes/datasets/dataset-delete/dataset-delete.component.ts
- src/app/pages/storage/volumes/zvol/zvol-delete/zvol-delete.component.ts
An extra checkbox added
ticket: #26378
> Remove the Periodic Snapshot Task of the Dataset is being deleted (like the snapshots are removed)

- src/app/components/common/consolepanel/consolepanel-dialog.component.ts
- src/app/components/common/layouts/admin-layout/admin-layout.component.ts
- src/app/pages/common/entity/entity-form/entity-form.component.ts
- src/app/services/ws.service.ts
- src/assets/styles/egret_overrides.css
I completed https://bugs.freenas.org/issues/26459
> Daisuke webui fix 26459

- src/app/pages/common/entity/entity-table/entity-table.component.html
Sorry for the odd branch name....  TYPE 0
Super Super easy one line change.  table.component.html
<div style="overflow: hidden; height: 20px;" title="{{row[col.prop]}}">
Where I added  title="{{row[col.prop]}}"
> Fix  26262

- src/app/components/common/topbar/topbar.component.ts
Done: "Reboot" and "Shutdown" fixed
Ticket: #26478
> Subject: "Reboot" and "Shutdown" buttons do not work in new Gui

- src/app/pages/dashboard/dashboard.component.ts
- src/app/pages/reportsdashboard/reportsdashboard.component.ts
I finished ticket #13005(https://bugs.freenas.org/issues/13005).
Please review...
> Chentao fix #13005

- src/app/components/common/about/about-dialog.component.html
- src/app/views/sessions/signin/signin.component.html
Done: Link added
Ticket: #26435
> Subject: Link to the old UI in login page

- src/app/pages/common/entity/entity-table/entity-table.component.css
- src/app/pages/common/entity/entity-table/entity-table.component.html
- src/app/pages/common/entity/entity-table/entity-table.component.scss
- src/app/pages/common/entity/entity-table/entity-table.component.ts
- src/app/pages/task-calendar/replication/replication-add/replication-add.component.html
- src/app/pages/task-calendar/replication/replication-add/replication-add.component.ts
- src/app/pages/task-calendar/replication/replication-edit/replication-edit.component.ts
Fixed protected field that needed to be public.
> Entity table fixes

- package.json
- src/app/app.module.ts
- src/app/pages/system/system.module.ts
- src/app/pages/system/update/update.component.html
- src/app/pages/system/update/update.component.ts
Done: changelog with markdown syntax support
Ticket: #23672
> ChangeLog on Update Page

- .angular-cli.json
- src/app/pages/common/entity/entity-table/entity-table.component.html
- src/app/pages/common/entity/entity-table/entity-table.component.ts
Got the pagination control working in unison with external pagination.
Gives you.. Pagination at top... (and item range selector)    <<  >>
At bottom... Second pagination option by page.
Still will fix the  artifact behind actions pop on chrome.. But this change is separate from that.
> Entity pagination demo

- src/app/app.component.ts
- src/assets/styles/styles.css
Ticket #26653 was resolved. https://redmine.ixsystems.com/issues/26653
> Changed "embedded" string misspelled in URL, #26653 (Chentao-fix)

- src/app/services/ws.service.ts
Added console.log to ws.services to diagonsis ticket #26683
https://redmine.ixsystems.com/issues/26683
> Added console.log to ws.services to diagonsis ticket #26683

- src/app/services/ws.service.ts
Reverts freenas/webui#108, remove console.log
> Revert "Added console.log to ws.services to diagonsis ticket #26683"

- src/app/pages/common/entity/entity-table/entity-table-actions.component.html
- src/app/pages/common/entity/entity-table/entity-table-actions.component.scss
- src/app/pages/common/entity/entity-table/entity-table.component.html
- src/app/pages/common/entity/entity-table/entity-table.component.ts
Fixed the artifacdt that you saw in chrome behind the menu..... AND kept it fixed in the firefox case.
> Entity action fixes 2

- src/app/pages/common/entity/entity-form/components/form-checkbox/form-checkbox.component.html
- src/app/pages/common/entity/entity-form/components/form-explorer/form-explorer.component.html
- src/app/pages/common/entity/entity-form/components/form-input/form-input.component.html
- src/app/pages/common/entity/entity-form/components/form-permissions/form-permissions.component.html
- src/app/pages/common/entity/entity-form/components/form-readfile/form-readfile.component.html
- src/app/pages/common/entity/entity-form/components/form-select/form-select.component.html
- src/app/pages/common/entity/entity-form/components/form-textarea-button/form-textarea-button.component.html
- src/app/pages/common/entity/entity-form/components/form-textarea/form-textarea.component.html
- src/app/pages/common/entity/entity-form/components/form-upload/form-upload.component.html
- src/app/pages/common/entity/entity-form/components/tooltip/tooltip.component.css
- src/app/pages/common/entity/entity-form/components/tooltip/tooltip.component.html
- src/app/pages/common/entity/entity-form/components/tooltip/tooltip.component.ts
- src/assets/styles/styles.css
https://redmine.ixsystems.com/issues/26723
Adjusted tooltip icon size and placement, added an animation, fixed mobile responsive of Tooltip alert.
> Adjust tooltip icon size and placement (Chentao fix #26723)

- src/app/components/common/topbar/topbar.component.ts
Done: no more tours showing after first time.
Ticket: #26567
> Subject: Fix the annoying tour shows every time

- src/app/components/common/lineChart/lineChart.component.ts
Fixes: https://redmine.ixsystems.com/issues/26538
Desc: Add zooming to graphs 
Zooming is achieved through two ways..
1. In the mini-map under the actual graph you can select the portion (which was present in the system)
2. Mouse scrolling in the graphs would enable the same functionality; upto the extent the graph can be zoomable (added in this PR).
> Ticket:26538

- src/app/components/common/topbar/topbar.component.ts
> Clarify and simplify logout/shutdown/reboot messages

- src/app/pages/account/groups/group-form/group-form.component.ts
- src/assets/styles/styles.css
https://redmine.ixsystems.com/issues/26718
Implemented some CSS Styles like underline and text color In <a> link of tooltips.
Please review and let me know.
Thanks
> Style enhancements: Tooltips (Chentao fix #26718)

- src/app/views/sessions/signin/signin.component.html
> Adjust URL of the Legacy UI

- src/app/pages/system/advanced/advanced.component.css
- src/app/pages/system/advanced/advanced.component.html
- src/app/pages/system/advanced/advanced.component.ts
Fixes: https://redmine.ixsystems.com/issues/26481
Desc: Saving System-Advanced settings shouldn't validate serial choice if not enabled
> Ticket: 26481

- src/app/pages/system/update/update.component.html
> Fix spelling and capitalization of "No updates available".

- src/app/pages/system/dataset/dataset.component.ts
- src/app/pages/system/dataset/index.ts
- src/app/pages/system/system.module.ts
- src/app/pages/system/system.routing.ts
- src/app/services/navigation/navigation.service.ts
> system dataset component

- src/app/pages/common/entity/entity-form/components/form-explorer/form-explorer.component.html
- src/app/pages/common/entity/entity-form/components/form-explorer/form-explorer.component.ts
- src/app/pages/common/entity/entity-form/models/field-config.interface.ts
- src/app/pages/common/entity/entity-form/services/entity-form.service.ts
- src/app/pages/storage/VMware-snapshot/VMware-snapshot/VMware-snapshot-form.component.ts
https://redmine.ixsystems.com/issues/27060?issue_count=21&issue_position=1&next_issue_id=26960
Done.
--------------------------------------------------------
In file explorer,
A new property, "explorerType" was added. "explorerType" property has three values, "zvol", "directory", "file".
The default value is "file".
Please take the code as an example.
{
type: 'explorer', 
name: 'filesystem', 
placeholder: 'ZFS Filesystem',
explorerType: "zvol",
initial: '/mnt'
}
> Chentao fix #27060

- src/app/pages/system/tunable/tunable-form/tunable-form.component.ts
Done: enable enabled
Ticket: #27067
> Subject: Enable should be on by default while creating a Tunable

- src/app/pages/storage/storage.routing.ts
- src/app/pages/storage/volumes/manager/manager.component.css
- src/app/pages/storage/volumes/manager/manager.component.html
- src/app/pages/storage/volumes/manager/manager.component.ts
- src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
> Add ability to extend existing volumes and some touchups to volume manager

- src/app/pages/common/entity/entity-table/entity-table.component.ts
- src/app/pages/system/bootenv/bootenv-status/bootenv-status.component.ts
https://redmine.ixsystems.com/issues/25608
Done
> Detach option for mirrored boot device(Chentao fix 25608)

- src/app/pages/storage/disks/disks-list/disks-list.component.html
- src/app/pages/storage/disks/disks-list/disks-list.component.ts
Quick improvement for bug I saw in tabs.. Table would randomly degrade the rows.. Under extreme tab swithcing... Had same issue once upon a time in the Reportdashboard... Works nice now.  :) "Well behaved"
> Diskpage visual improvement

- src/app/components/common/topbar/topbar.component.ts
- src/app/pages/common/confirm-dialog/confirm-dialog.component.html
- src/app/pages/common/confirm-dialog/confirm-dialog.component.ts
- src/app/services/dialog.service.ts
https://redmine.ixsystems.com/issues/27446
Done
> New GUI log out operation shouldn't have confirmation checkbox in it(Chentao fix 27446)

- src/app/views/sessions/signin/signin.component.html
- src/app/views/sessions/signin/signin.component.ts
> Change requirement for login button so it doesn't get arbitrarily disabled by tin foil hat browsers.

- src/app/pages/system/alertservice/alertservice-add-hipchat/alertservice-add-hipchat.component.ts
- src/app/pages/system/alertservice/alertservice-add-influxdb/alertservice-add-influxdb.component.ts
- src/app/pages/system/alertservice/alertservice-add-mattermost/alertservice-add-mattermost.component.ts
This also included adding missing commas in value and placeholder sections.
> Added the tooltips for HipChat, InfluxDB, and Mattermost Alert Services.

- src/app/pages/system/advanced/advanced.component.html
- src/app/pages/system/advanced/advanced.component.ts
> Save Debug in System-Advanced Page

- src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
Had a working download encrypt key thing going wanted in.
> The tree is back

- src/app/pages/sharing/iscsi/globalconfiguration/globalconfiguration.component.ts
- src/app/pages/sharing/smb/smb-form/smb-form.component.ts
- src/app/pages/sharing/webdav/webdav-form/webdav-form.component.ts
1. Added 14 tool tips to smb-form.
2. Added 5 tool tips to web-dav form
3. Added 3 tool tips to ../iscsi/globalconfiguration
> Tooltips: Added tooltips to 3 pages.

- src/app/pages/directoryservice/kerberosrealms/kerberosrealms-form/kerberosrealms-form.component.ts
- src/app/pages/directoryservice/ldap/ldap.component.ts
- src/app/pages/directoryservice/nis/nis.component.ts
- src/app/pages/network/interfaces/interfaces-form/interfaces-form.component.ts
- src/app/pages/network/staticroutes/staticroute-form/staticroute-form.component.ts
- src/app/pages/network/vlans/vlan-form/vlan-form.component.ts
- src/app/pages/sharing/afp/afp-form/afp-form.component.ts
- src/app/pages/sharing/nfs/nfs-form/nfs-form.component.ts
- src/app/pages/storage/VMware-snapshot/VMware-snapshot/VMware-snapshot-form.component.ts
- src/app/pages/storage/snapshots/snapshot-list/snapshot-list.component.ts
- src/app/pages/task-calendar/cron/cron-form/cron-form.component.ts
- src/app/pages/task-calendar/rsync/rsync-form/rsync-form.component.ts
Added tool tips for various pages
> Added tool tips

- src/app/pages/storage/snapshots/snapshot-add/snapshot-add.component.ts
- src/app/pages/storage/snapshots/snapshot-clone/snapshot-clone.component.ts
There is one additional to add in the 'clone' file.
Build test: no issues locally.
> Tooltips: add 3 / 3 messages to the Storage -> Snapshots -> Add page

- src/app/pages/network/ipmi/ipmi.component.ts
Add all needed tooltips to the Network -> IPMI page.
NPM build test compiled successfully, but the page isn't visible on my testing hardware (no BMC?).
Fix spelling error in placeholder.
> Tooltips: Add Network -> IPMI tooltips (7/7)

- src/app/pages/system/alertservice/alertservice-add-opsgenie/alertservice-add-opsgenie.component.ts
- src/app/pages/system/alertservice/alertservice-add-pagerduty/alertservice-add-pagerduty.component.ts
- src/app/pages/system/alertservice/alertservice-edit-aws/alertservice-edit-aws.component.ts
- src/app/pages/system/alertservice/alertservice-edit-hipchat/alertservice-edit-hipchat.component.ts
- src/app/pages/system/alertservice/alertservice-edit-influxdb/alertservice-edit-influxdb.component.ts
- src/app/pages/system/alertservice/alertservice-edit-mattermost/alertservice-edit-mattermost.component.ts
- src/app/pages/system/alertservice/alertservice-edit-opsgenie/alertservice-edit-opsgenie.component.ts
- src/app/pages/system/alertservice/alertservice-edit-pagerduty/alertservice-edit-pagerduty.component.ts
- src/app/pages/system/alertservice/alertservice-edit-slack/alertservice-edit-slack.component.ts
- src/app/pages/system/alertservice/alertservice-edit-victorops/alertservice-edit-victorops.component.ts
Also added the tooltips for all the edit Alert Services pages.
> Added the tooltips for the Add OpsGenie and Add PagerDuty Alert Services pages. 

- src/app/pages/network/configuration/configuration.component.ts
Add remaining tooltips to the Global Configuration page.
Build tested locally - no render issues.
> Tooltips: finish Network -> Global Configuration page

- src/app/pages/common/entity/entity-form/components/form-select/form-select.component.html
- src/app/pages/common/entity/entity-form/components/form-select/form-select.component.ts
- src/app/pages/common/entity/entity-form/entity-form.component.ts
- src/app/pages/common/entity/entity-form/models/field-config.interface.ts
- src/app/pages/task-calendar/rsync/rsync-form/rsync-form.component.ts
https://redmine.ixsystems.com/issues/27538
Done
> Missing item on Tasks/Rsync(Chentao fix 27538)

- src/app/pages/common/entity/entity-form/components/form-explorer/form-explorer.component.html
- src/app/pages/common/entity/entity-form/components/tooltip/tooltip.component.css
- src/app/pages/task-calendar/initshutdown/initshutdown-form/initshutdown-form.component.ts
- src/assets/styles/styles.css
https://redmine.ixsystems.com/issues/27495
Done
> Changed Init/Shutdown script field(chentao-fix-27495)

- src/app/pages/system/general/general.component.ts
> ADDED: a indicator shows when certificate value is empty

- src/app/pages/common/entity/entity-form/entity-form.component.ts
removed console.log() in entity-form
> Remove console.log in entity-form

- .angular-cli.json
- src/app/pages/common/entity/entity-form/components/form-explorer/form-explorer.component.ts
https://redmine.ixsystems.com/issues/27464
Done
> File browser is not a tree view(Chentao fix 27464)

- src/app/pages/shell/shell.component.html
- src/app/pages/shell/shell.component.ts
> a hint for copy/paste on shell page

- src/app/pages/system/ca/ca-intermediate/ca-intermediate.component.ts
- src/app/pages/system/certificates/certificate-internal/certificate-internal.component.ts
- src/app/pages/system/dataset/dataset.component.ts
- src/app/pages/system/general/general.component.ts
> ADDED: --- as an empty value for select components

- src/app/pages/storage/volumes/manager/manager.component.ts
> Only show the encryption checkbox when checking it, not when unchecking

- src/app/pages/account/users/user-form/user-form.component.ts
> using `user.get_next_uid` to get next available userid for new user.

- src/app/pages/shell/shell.component.css
- src/app/pages/shell/shell.component.html
> Tooltips on the Shell page

- src/app/pages/network/vlans/vlan-form/vlan-form.component.ts
> Fix the field for vlan parent interface in edit mode and add priority code point

- src/app/pages/sharing/smb/smb-form/smb-form.component.ts
> Add missing homes share checkbox and fix vfs defaults to match current samba settings

- src/app/pages/system/ca/ca-intermediate/ca-intermediate.component.ts
- src/app/pages/system/ca/ca-internal/ca-internal.component.ts
- src/app/pages/system/certificates/certificate-csr/certificate-csr.component.ts
- src/app/pages/system/certificates/certificate-internal/certificate-internal.component.ts
> country list in CA and certificate pages

- src/app/pages/directoryservice/activedirectory/activedirectory.component.ts
- src/app/pages/network/laggs/lagg-form/lagg-form.component.ts
- src/app/pages/services/components/service-lldp/service-lldp.component.ts
- src/app/pages/services/components/service-rsync/service-rsync.component.ts
- src/app/pages/system/CloudCredentials/CloudCredentials-amazon/CloudCredentials-amazon.component.ts
- src/app/pages/system/email/email.component.ts
1. Email page
2. Amazon cloud credentials page
3. Lagg form page.
> Tooltips: Added tool tips to 3 pages.

- src/app/pages/shell/shell.component.ts
> quick fix for tooltip icon not showing correctly on shell page

- src/app/pages/sharing/afp/afp-form/afp-form.component.ts
> Add Time Machine Quota

- src/app/components/common/layouts/admin-layout/admin-layout.component.ts
- src/app/components/common/topbar/topbar.component.ts
- src/app/services/ws.service.ts
https://redmine.ixsystems.com/issues/27543
Done
> Getting logged out while the console log popup is up blocks the login form(Chentao fix 27543)

- src/app/pages/system/ca/ca-intermediate/ca-intermediate.component.ts
- src/app/pages/system/ca/ca-internal/ca-internal.component.ts
- src/app/pages/system/certificates/certificate-csr/certificate-csr.component.ts
- src/app/pages/system/certificates/certificate-internal/certificate-internal.component.ts
> ADDED: cert_san field for alternate names field

- src/app/pages/system/CloudCredentials/CloudCredentials-B2/CloudCredentials-B2.component.ts
- src/app/pages/system/CloudCredentials/CloudCredentials-amazon/CloudCredentials-amazon.component.ts
- src/app/pages/system/CloudCredentials/CloudCredentials-azure/CloudCredentials-azure.component.ts
- src/app/pages/system/CloudCredentials/CloudCredentials-gcs/CloudCredentials-gcs.component.ts
- src/app/pages/system/alertservice/alertservice-add-victorops/alertservice-add-victorops.component.ts
- src/app/pages/system/dataset/dataset.component.ts
- src/app/pages/vm/devices/device-cdrom-add/device-cdrom-add.component.ts
- src/app/pages/vm/devices/device-nic-add/device-nic-add.component.ts
1. Improved tool tips for AWS Credentials page
2. Added 3/3 tool tips for Azure Credentials page
3. Fixed output display error for tool tip on alertservice/add victorops page.
4. Added 3/3 tool tips for BACKBLAZE Credentials page
5. Added 2/2 tool tips for GCS creds page.
> Tool tips:

- src/app/pages/common/entity/entity-form/components/form-array/form-array.component.html
- src/app/pages/common/entity/entity-form/components/form-checkbox/form-checkbox.component.html
- src/app/pages/common/entity/entity-form/components/form-datepicker/form-datepicker.component.html
- src/app/pages/common/entity/entity-form/components/form-explorer/form-explorer.component.html
- src/app/pages/common/entity/entity-form/components/form-input/form-input.component.html
- src/app/pages/common/entity/entity-form/components/form-permissions/form-permissions.component.html
- src/app/pages/common/entity/entity-form/components/form-radio/form-radio.component.html
- src/app/pages/common/entity/entity-form/components/form-readfile/form-readfile.component.html
- src/app/pages/common/entity/entity-form/components/form-select/form-select.component.html
- src/app/pages/common/entity/entity-form/components/form-slider/form-slider.component.html
- src/app/pages/common/entity/entity-form/components/form-task/form-task.component.html
- src/app/pages/common/entity/entity-form/components/form-textarea-button/form-textarea-button.component.html
- src/app/pages/common/entity/entity-form/components/form-textarea/form-textarea.component.html
- src/app/pages/common/entity/entity-form/components/form-toggle-button/form-toggle-button.component.html
- src/app/pages/common/entity/entity-form/components/form-upload/form-upload.component.html
- src/app/pages/common/entity/entity-form/entity-form.component.html
- src/app/pages/common/entity/utils.ts
> Various fixes to error visibility

- src/app/pages/sharing/smb/smb-form/smb-form.component.ts
> Make smb default permissions non-default and pop up a scary message when checked

- src/app/app.module.ts
- src/app/pages/common/entity/entity-form/entity-form-embedded.component.html
- src/app/pages/common/entity/entity-form/entity-form.component.html
- src/app/pages/common/entity/entity-table/entity-table-actions.component.html
- src/app/pages/common/entity/entity-table/entity-table-add-actions.component.ts
- src/app/pages/common/entity/entity-table/entity-table.component.html
- src/app/pages/common/entity/entity-table/entity-table.component.ts
- src/app/pages/dashboard/dashboard.component.ts
- src/app/pages/reportsdashboard/reportsdashboard.component.ts
- src/app/pages/storage/disks/disks-list/disks-list.component.ts
- src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
- src/app/services/erd.service.ts
Added IDs.
Form buttons.  And some extra IDs in entity-form and entity-embeded-form
Table Rows.
Fix for erd.listenTo on dashboard, reportdashboard and entity-table into consolidated ErdService where I far more tightly check for the existence of IDs and the ERD api before beginning.
> Added id for qa

- src/app/pages/services/components/service-afp/service-afp.component.ts
Fixed a typo where "Guest account" was named as the checkbox when it should have been the select type.
> Fixed out of order names.

- src/app/pages/services/components/service-tftp/service-tftp.component.ts
- src/app/pages/services/components/service-ups/service-ups.component.ts
- src/app/pages/services/components/service-webdav/service-webdav.component.ts
Add tooltips to three pages:
- 6 / 6 for Service Webdav.
- 18 / 18 for Service UPS.
- 6 / 6 for Services TFTP.
- Build test locally: no compile or render errors.
> Adding more tooltips:

- src/app/pages/system/general/config-save/config-save.component.html
> Fixed miss spelling when you download the config file

- src/app/app.component.ts
- src/app/pages/common/entity/entity-form/components/form-upload/form-upload.component.ts
- src/app/pages/system/general/config-upload/config-upload.component.ts
- src/app/services/rest.service.ts
- src/app/services/ws.service.ts
- src/app/views/sessions/signin/signin.component.ts
> Use a 1-minute ttl token with keepalive instead of storing username/password for authentication

- src/app/pages/system/ca/ca-intermediate/ca-intermediate.component.ts
- src/app/pages/system/ca/ca-internal/ca-internal.component.ts
See commit messages for more details.
> Redmine bug #24593: ensure CA/Certificate form `Common Name` field tooltips match.

- src/app/pages/common/entity/entity-job/entity-job.component.html
- src/app/pages/common/entity/entity-job/entity-job.component.ts
> Subject: limit decimals

- package.json
- src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
- src/main.ts
FIX FINALLY for material 5...!!!!
Really.. Total team effort here.... Enjoy!!  Finaly figured out.. we also needed to update @angular/compiler-cli  !!!
"@angular/cli": "^1.6.6",
"@angular/compiler-cli": "^5.2.2",
> Master compiler cli fix

- src/app/pages/system/advanced/advanced.component.ts
> Removed legacy URL for save debug

- src/app/components/common/breadcrumb/breadcrumb.component.css
- src/app/components/common/breadcrumb/breadcrumb.component.html
- src/app/components/common/dialog/about/about-dialog.component.html
- src/app/views/others/reboot/reboot.component.css
- src/app/views/others/reboot/reboot.component.html
- src/app/views/others/reboot/reboot.component.ts
- src/app/views/others/shutdown/shutdown.component.css
- src/app/views/others/shutdown/shutdown.component.html
- src/app/views/others/shutdown/shutdown.component.ts
- src/app/views/sessions/signin/signin.component.css
- src/app/views/sessions/signin/signin.component.html
> Add copyright throughout the UI

- src/app/app.component.ts
- src/app/pages/common/entity/entity-form/components/form-upload/form-upload.component.ts
- src/app/pages/system/general/config-upload/config-upload.component.ts
- src/app/services/rest.service.ts
- src/app/services/ws.service.ts
- src/app/views/sessions/signin/signin.component.ts
Revert "Temporarily reverting so rest calls can work again, will revert the revert once they are fixed"
This reverts commit 18ab3af9482f06b48ad3ccd6e09b66ccd2115c03.
> Yo dawg I heard you like reverting, so I reverted your revert so you can login with yo token

- package.json
- src/app/components/common/customizer/customizer.component.css
- src/app/components/common/customizer/customizer.component.ts
- src/app/components/common/topbar/topbar.component.ts
- src/app/components/common/topbar/topbar.template.html
- src/app/services/navigation/navigation.service.ts
Simple change.. getting it checked in so I have a PR for the ticket.  https://redmine.ixsystems.com/issues/27840
> Missing volume actions 2

- src/app/pages/services/components/service-dc/service-dc.component.ts
as following bug was completed, https://redmine.ixsystems.com/issues/26606 I had to bring changes to latest UI as well.
> added domain/forest functional levels 2012, 2012_R2.

- src/app/pages/common/entity/entity-form/components/tooltip/tooltip.component.css
- src/app/pages/storage/volumes/manager/manager.component.css
- src/app/pages/storage/volumes/manager/manager.component.html
- src/app/pages/storage/volumes/manager/manager.component.ts
- src/app/pages/storage/volumes/manager/vdev/vdev.component.ts
(some things appear to have changed with the table and other things)
Ticket: #23140
> Fix layout and refreshing issues with the volume manager

- src/app/pages/systemprocesses/system-processes.component.ts
Done: Fixed with removed dependencies from component to angular-cli
Ticket: #28191
> Subject: System process not working in prod build

- src/app/pages/system/advanced/advanced.component.css
- src/app/pages/system/advanced/advanced.component.html
- src/app/pages/system/advanced/advanced.component.ts
I leave actual tooltips blank for doc team.
now should display tooltips.
ticket: #27502
> Tooltip placeholders for System Advanced page

- package.json
- src/app/core/components/corecomponents.module.ts
- src/app/core/components/viewchart/viewchart.component.ts
- src/app/core/components/viewchartdonut/viewchartdonut.component.ts
- src/app/core/components/viewchartline/viewchartline.component.ts
- src/app/core/components/viewchartpie/viewchartpie.component.ts
- src/app/core/components/widgets/widget/widget.component.html
- src/app/core/components/widgets/widget/widget.component.ts
- src/app/core/directives/animation.directive.ts
- src/app/pages/common/entity/entity-card/entity-card.component.css
- src/app/pages/vm/vm-cards/vm-cards.component.css
- src/app/pages/vm/vm-cards/vm-summary.component.ts
- src/app/services/theme/theme.service.ts
- src/assets/styles/charts.css
This PR adds a new animations directive, charts enhancements, an example widget class and a bug ticket fix for the theme service.
> Widgets ng5

- src/app/pages/storage/storage.module.ts
- src/app/pages/storage/storage.routing.ts
- src/app/pages/storage/volumes/volume-delete/volume-delete.component.ts
- src/app/pages/storage/volumes/volumeaddkey-form/index.ts
- src/app/pages/storage/volumes/volumeaddkey-form/volumeaddkey-form.component.ts
- src/app/pages/storage/volumes/volumerekey-form/index.ts
- src/app/pages/storage/volumes/volumerekey-form/volumerekey-form.component.ts
- src/app/pages/storage/volumes/volumes-list/volumes-list.component.html
- src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
- src/app/pages/storage/volumes/volumeunlock-form/index.ts
- src/app/pages/storage/volumes/volumeunlock-form/volumeunlock-form.component.ts
Whom ever...
Put in missing actions for encryption.
Also.. Put in ID's for volumes table.  This is a micro release.. Had more to do.. But this stuff works.. And adds the ID's on the volumes page Rish needs to test it.!  :)
> Missing volume actions 3

- src/app/pages/directoryservice/activedirectory/activedirectory.component.ts
- src/app/pages/services/components/service-dc/service-dc.component.ts
- Add new 2012 and 2012_R2 options to the tooltip.
- Build test: no issues.
> Redmine issue #26606 and #25358

- src/app/pages/account/users/user-form/user-form.component.ts
- src/app/pages/services/components/service-afp/service-afp.component.ts
- src/app/pages/services/components/service-ftp/service-ftp.component.ts
- src/app/pages/services/components/service-s3/service-s3.component.ts
- src/app/pages/services/components/service-tftp/service-tftp.component.ts
- src/app/pages/sharing/afp/afp-form/afp-form.component.ts
- src/app/pages/sharing/nfs/nfs-form/nfs-form.component.ts
- src/app/pages/sharing/smb/smb-form/smb-form.component.ts
- src/app/pages/sharing/webdav/webdav-form/webdav-form.component.ts
- src/app/pages/task-calendar/rsync/rsync-form/rsync-form.component.ts
(one shouldn't select a file for a share or a home directory)
> Specify file explorer types for various forms

- package.json
(hopefully this should get rid of those pesky flag css errors we see alot in dev mode)
> Bumping flag css version back down

- tests/acc_edit.py
- tests/runtest.py
- tests/serv_webdav.py
- tests/sys_email.py
- tests/sys_update.py
- tests/theme.py
check update test disabled due to the connection issue
http://10.20.20.72:8180/jenkins/job/FreeNAS%20-%20Master%20-%20WebUI%20Tests%20-%20Without%20Install%20on%20ESXI%20VM/114/console
> tests tuned and jenkin passing all tests

- package.json
- src/app/components/common/topbar/topbar.component.css
- src/app/components/common/topbar/topbar.component.ts
These commits bump angular-cli to the latest rc version and comment out the flag stuff that neither works in dev or production mode properly now (it's just a flag icon, maybe they'll fix it later)
> Bump angular cli

- src/app/components/common/topbar/topbar.template.html
> UPDATED: replaced inappropriate icon

- package.json
This command will clear your modules and do a fresh install of them
> Add npm run reinstall command to package.json

- src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
Found and fixex bug for how I was calling (from the per dataset treetable).. Not passing id to download ecnryption dialog.
Simple fix.
> Found an error how I was calling dialog. I wasn't setting the Volume ID

- src/app/components/common/layouts/admin-layout/admin-layout.component.ts
> Fix the list of supported languages so that browser language auto-detection will work properly.

- src/app/pages/shell/shell.component.ts
> Fixed tab width in shell should be 8 spaces, not 4

- src/app/pages/common/entity/entity-form/entity-form-embedded.component.html
- src/app/pages/vm/vm-cards/vm-cards.component.ts
Finally was able to reproduce the problem. This problem only seems to happen when you are running FreeNAS as a VM, in which case none of these would work anyway. The fix was to not mutate data but replace it. In other words, clear the array completely before pushing API response data to it. Also fixed a stray < in entity-form-embedded template
> Fixed repeating card issue (see ticket #28227). 

- src/app/core/services/api.service.ts
- src/app/pages/vm/vm-cards/vm-cards.component.html
- src/app/pages/vm/vm-cards/vm-cards.component.ts
VNC button is now disabled if there is no web vnc device and if the vm is not running. In the process of doing this, I also switched the last of the API calls on this page to use web socket API v2.0
> Fixed VNC button issue

- package.json
The usual suspects ;)   People who most commonly deal with build yuck...
> added @angular-devkit/build-optimizer

- src/app/pages/directoryservice/idmap/idmap.component.ts
- src/app/pages/network/interfaces/interfaces-form/interfaces-form.component.ts
- src/app/pages/network/laggs/lagg-form/lagg-form.component.ts
- src/app/pages/services/components/service-dynamicdns/service-dynamicdns.component.ts
- src/app/pages/services/components/service-ftp/service-ftp.component.ts
- src/app/pages/services/components/service-s3/service-s3.component.ts
- src/app/pages/services/components/service-smb/service-smb.component.ts
- src/app/pages/services/components/service-snmp/service-snmp.component.ts
- src/app/pages/sharing/nfs/nfs-form/nfs-form.component.ts
Chart each screen of the new UI and track down missing tooltips.
Add many different tooltips.
Clean up many existing tooltips for proper links, grammar, spelling, etc.
Clean up extra whitespace in many of the reviewed files.
Build tested continuously - no issues for now.
> Initial Tooltip review:

- src/app/pages/account/users/user-form/user-form.component.ts
- src/app/pages/storage/volumes/manager/manager.component.ts
- src/app/pages/storage/volumes/manager/vdev/vdev.component.ts
- src/app/pages/storage/volumes/zvol/zvol-add/zvol-add.component.ts
- src/app/pages/system/general/general.component.ts
This includes the "Create ZFS Pool" page and the "Add Zvol" page.
Also cleaned up some extra whitespace in the files.
Build tested locally, no issues.
> Add remaining Storage/Volumes tooltips + Commits for other missing tooltips.

- src/app/app.routes.ts
- src/app/pages/common/entity/entity-form/components/form-checkbox/form-checkbox.component.html
- src/app/pages/common/entity/entity-form/components/form-checkbox/form-checkbox.component.scss
- src/app/pages/common/entity/entity-form/components/form-explorer/form-explorer.component.html
- src/app/pages/common/entity/entity-form/components/form-explorer/form-explorer.component.scss
- src/app/pages/common/entity/entity-form/components/form-permissions/form-permissions.component.html
- src/app/pages/common/entity/entity-form/components/form-permissions/form-permissions.component.ts
- src/app/pages/common/entity/entity-form/components/form-permissions/form-permissions.css
- src/app/pages/common/entity/entity-form/components/form-radio/form-radio.component.html
- src/app/pages/common/entity/entity-form/components/form-radio/form-radio.component.scss
- src/app/pages/common/entity/entity-form/components/form-upload/form-upload.component.css
- src/app/pages/common/entity/entity-form/components/form-upload/form-upload.component.html
- src/app/pages/common/entity/entity-form/components/form-upload/form-upload.component.ts
- src/app/pages/common/entity/entity-form/entity-form.component.html
- src/app/pages/common/entity/entity-form/entity-form.component.scss
- src/app/pages/task-calendar/cron/cron-form/cron-form.component.css
- src/app/pages/task-calendar/cron/cron-form/cron-form.component.html
- src/app/pages/task-calendar/cron/cron-form/cron-form.component.ts
> First pass at polishing up the CSS for various form components

- src/app/pages/system/general/general.component.ts
> DELETED: test upload component shouldn't exist

- src/app/pages/common/entity/entity-form/components/form-select/form-select.component.html
> Apparently trying to translate the options was a bit too ambitious

- src/app/pages/jails/jail-list/jail-list.component.html
- src/app/pages/jails/jail-list/jail-list.component.ts
this is the for the init install with no jails pool activated, should prompt a config setup
ticket: #28864
> activate pool page for Jails

- src/app/pages/storage/snapshots/snapshot-list/snapshot-list.component.ts
> Fix paths for snapshot clone and revert

- src/app/pages/system/update/update.component.html
- src/app/pages/system/update/update.component.ts
> Warning when switch Update train

- src/app/pages/jails/jail-wizard/jail-wizard.component.ts
- src/app/pages/plugins/plugin-add/plugin-add.component.ts
- src/app/pages/services/components/service-s3/service-s3.component.ts
- src/app/pages/storage/volumes/zvol/zvol-edit/zvol-edit.component.ts
- src/app/pages/system/alertservice/alertservice-add-aws/alertservice-add-aws.component.ts
- src/app/pages/system/alertservice/alertservice-add-mattermost/alertservice-add-mattermost.component.ts
- src/app/pages/system/alertservice/alertservice-add-opsgenie/alertservice-add-opsgenie.component.ts
- src/app/pages/system/alertservice/alertservice-add-pagerduty/alertservice-add-pagerduty.component.ts
- src/app/pages/system/alertservice/alertservice-add-slack/alertservice-add-slack.component.ts
- src/app/pages/system/alertservice/alertservice-add-victorops/alertservice-add-victorops.component.ts
- src/app/pages/system/alertservice/alertservice-edit-aws/alertservice-edit-aws.component.ts
- src/app/pages/system/alertservice/alertservice-edit-mattermost/alertservice-edit-mattermost.component.ts
- src/app/pages/system/alertservice/alertservice-edit-opsgenie/alertservice-edit-opsgenie.component.ts
- src/app/pages/system/alertservice/alertservice-edit-pagerduty/alertservice-edit-pagerduty.component.ts
- src/app/pages/system/alertservice/alertservice-edit-slack/alertservice-edit-slack.component.ts
- src/app/pages/system/alertservice/alertservice-edit-victorops/alertservice-edit-victorops.component.ts
- src/app/pages/system/ca/ca-form/ca-form.component.ts
- Review tooltips in the System/AlertServices pages.
- Clean up whitespace and line length issues.
- Add tooltips and fix spelling in the Jail wizard.
- Find and add more missing tooltips.
> Ongoing Tooltip review:

- src/app/pages/vm/vm-cards/vm-cards.component.css
- src/app/services/app-loader/app-loader.component.css
- src/app/services/theme/theme.service.ts
Fixed issue with scrollbar showing up on spinners. Fixed issue with background images not showing on vm cards. Added default accent colors to theme.service to avoid animation glitches with dashboard sysinfo widget.
> Fixed a few cosmetic issues

- src/app/pages/sharing/iscsi/target/target-add/target-add.component.css
- src/app/pages/sharing/iscsi/target/target-add/target-add.component.html
- src/app/pages/sharing/iscsi/target/target-add/target-add.component.ts
- src/app/pages/sharing/iscsi/target/target-edit/target-edit.component.css
- src/app/pages/sharing/iscsi/target/target-edit/target-edit.component.html
- src/app/pages/sharing/iscsi/target/target-edit/target-edit.component.ts
> CSS align the buttons in iscsi targets

- src/app/app.component.ts
- src/app/components/common/layouts/admin-layout/admin-layout.component.ts
- src/app/components/common/layouts/admin-layout/admin-layout.template.html
- src/app/core/components/viewchart/viewchart.component.ts
- src/app/core/components/widgets/widgetpool/widgetpool.component.css
- src/app/core/components/widgets/widgetpool/widgetpool.component.html
- src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.css
- src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.html
- src/app/core/services/core.service.ts
- src/app/pages/dashboard/dashboard.html
- src/assets/styles/egret_overrides.css
Breakpoints implemented on dashboard via flexlayout directives. Individual widgets may need fine tuning but this is mostly there. Will come back to further refine this later when time permits.
> Dashboard Responsive Layout

- src/app/pages/shell/shell.component.ts
> FIXED: turn off BLINK cursor to BLINK

- src/app/pages/jails/configuration/configuration.component.ts
- src/app/pages/jails/jail-add/jail-add.component.ts
- src/app/pages/jails/jail-edit/jail-edit.component.ts
Also, RCTL property tooltips are added, although that feature has not been implemented yet - do we need to comment that section out for now?
> Add tooltips to Jail Add, Edit, and Configure pages.

- src/app/pages/jails/jail-list/jail-list.component.html
I've altered the form **label**, **placeholder**, and added a **title** (hoverable tooltip) which should better explain how to activate the iocage jail manager and what activating the manager does.
> Rework "Select a Pool" (iocage activate) screen to have more info

- src/app/pages/common/confirm-dialog/confirm-dialog.component.html
- src/app/pages/storage/storage.module.ts
- src/app/pages/storage/volumes/manager/manager.component.html
- src/app/pages/storage/volumes/manager/manager.component.ts
- src/app/pages/storage/volumes/manager/vdev/vdev.component.html
- src/app/pages/storage/volumes/manager/vdev/vdev.component.ts
- src/assets/i18n/en.po
- src/assets/i18n/es.po
- src/assets/i18n/strings.po
- src/assets/i18n/zh-hans.po
>  Add translation markers and extend warning to volume manager 

- src/app/pages/account/users/user-form/user-form.component.ts
made some edits suggested by VS CODE.
> user form now creates a `username` directory.

- src/app/pages/vm/vm-cards/vm-cards.component.html
- src/app/pages/vm/vm-wizard/vm-wizard.component.ts
this PR is was a result of my commit to the master directly and then reverting the said commit to master. this would have been avoided I has created FIX-29817 after I reverted my commit to the master or if I would have created FIX-29817 right on `13eeb99cc8fefcc88fea6ee65cf7d5a54cc436ef`. but anyhow things are in order and please review this change,
> this is a commit brings in changes for VM pages

- src/app/pages/storage/volumes/datasets/dataset-permissions/dataset-permissions.component.ts
- src/assets/i18n/en.po
- src/assets/i18n/es.po
- src/assets/i18n/strings.po
- src/assets/i18n/zh-hans.po
> Add mac mode, translation markers and proper acl handling to dataset permissions

- src/app/pages/task-calendar/cloudsync/cloudsync-delete/cloudsync-delete.component.ts
- src/app/pages/task-calendar/cloudsync/cloudsync-delete/index.ts
- src/app/pages/task-calendar/cloudsync/cloudsync-form/cloudsync-form.component.css
- src/app/pages/task-calendar/cloudsync/cloudsync-form/cloudsync-form.component.html
- src/app/pages/task-calendar/cloudsync/cloudsync-form/cloudsync-form.component.ts
- src/app/pages/task-calendar/cloudsync/cloudsync-form/index.ts
- src/app/pages/task-calendar/cloudsync/cloudsync-list/cloudsync-list.component.ts
- src/app/pages/task-calendar/cloudsync/cloudsync-list/index.ts
- src/app/pages/task-calendar/task-calendar.module.ts
- src/app/pages/task-calendar/task-calendar.routing.ts
- src/app/services/navigation/navigation.service.ts
> Feature: Task - Cloud Sync

- src/app/pages/system/CloudCredentials/CloudCredentials-B2/CloudCredentials-B2.component.ts
- src/app/pages/system/CloudCredentials/CloudCredentials-amazon/CloudCredentials-amazon.component.ts
- src/app/pages/system/CloudCredentials/CloudCredentials-azure/CloudCredentials-azure.component.ts
- src/app/pages/system/CloudCredentials/CloudCredentials-gcs/CloudCredentials-gcs.component.ts
- src/app/pages/system/advanced/advanced.component.ts
- src/app/pages/system/bootenv/bootenv-attach/bootenv-attach-form.component.ts
- src/app/pages/system/bootenv/bootenv-clone/bootenv-clone.component.ts
- src/app/pages/system/bootenv/bootenv-create/bootenv-create.component.ts
- src/app/pages/system/bootenv/bootenv-rename/bootenv-rename.component.ts
- src/app/pages/system/bootenv/bootenv-replace/bootenv-replace-form.component.ts
- src/app/pages/system/ca/ca-form/ca-form.component.ts
- src/app/pages/system/ca/ca-import/ca-import.component.ts
- src/app/pages/system/ca/ca-intermediate/ca-intermediate.component.ts
- src/app/pages/system/ca/ca-internal/ca-internal.component.ts
- src/app/pages/system/certificates/certificate-csr/certificate-csr.component.ts
- src/app/pages/system/certificates/certificate-edit/certificate-edit.component.ts
- src/app/pages/system/certificates/certificate-import/certificate-import.component.ts
- src/app/pages/system/certificates/certificate-internal/certificate-internal.component.ts
- src/app/pages/system/email/email.component.ts
- src/app/pages/system/general/general.component.ts
- src/app/pages/system/ntpservers/ntpserver-add/ntpserver-add.component.ts
- src/app/pages/system/ntpservers/ntpserver-edit/ntpserver-edit.component.ts
- src/app/pages/system/support/support.component.html
- src/app/pages/system/support/support.component.ts
- src/app/pages/system/tunable/tunable-form/tunable-form.component.ts
- src/app/pages/system/update/update.component.ts
> Translation for System section

- src/app/pages/common/entity/entity-form/components/tooltip/tooltip.component.css
> Left align, resize and add a white border to make tooltips more visible

- src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
- src/app/pages/task-calendar/replication/replication-form/replication-form.component.ts
Was getting the wrong key.. Assumed it was the same as on the button "Recover Key" on the front page. ... Whos dialog makes a key.. that'd make sense.. So. I put that same key sacn on the RSH Key Scan button for creating a replication task.  Also fixed the error case.
> Fixed rsh key scan button

- src/app/pages/system/tunable/tunable-form/tunable-form.component.ts
> (System-Tunable)UPDATED: set loader as default value for tunable type

- src/app/pages/shell/shell.component.html
- src/app/pages/shell/shell.component.ts
- src/app/pages/shell/shell.module.ts
> Shell page translation

- src/app/pages/services/components/service-afp/service-afp.component.ts
- src/app/pages/services/components/service-cifs/service-cifs.component.ts
- src/app/pages/services/components/service-dc/service-dc.component.ts
- src/app/pages/services/components/service-dynamicdns/service-dynamicdns.component.ts
- src/app/pages/services/components/service-ftp/service-ftp.component.ts
- src/app/pages/services/components/service-lldp/service-lldp.component.ts
- src/app/pages/services/components/service-nfs/service-nfs.component.ts
- src/app/pages/services/components/service-rsync/rsyncconfiguration/configure_rsync/configure_rsync.component.ts
- src/app/pages/services/components/service-s3/service-s3.component.ts
- src/app/pages/services/components/service-smart/service-smart.component.ts
- src/app/pages/services/components/service-smb/service-smb.component.ts
- src/app/pages/services/components/service-snmp/service-snmp.component.ts
- src/app/pages/services/components/service-ssh/service-ssh.component.ts
- src/app/pages/services/components/service-tftp/service-tftp.component.ts
- src/app/pages/services/components/service-ups/service-ups.component.ts
- src/app/pages/services/components/service-webdav/service-webdav.component.ts
- src/app/pages/services/services.module.ts
> Translation markers for Service components

- src/app/pages/storage/volumes/datasets/dataset-permissions/dataset-permissions.component.ts
> Add warning message to apply permissions recursively

- src/app/pages/common/entity/entity-table/entity-table.component.html
- src/app/pages/sharing/afp/afp-form/afp-form.component.ts
- src/app/pages/sharing/afp/afp-list/afp-list.component.ts
- src/app/pages/sharing/nfs/nfs-form/nfs-form.component.ts
- src/app/pages/sharing/nfs/nfs-list/nfs-list.component.ts
- src/app/pages/sharing/smb/smb-form/smb-form.component.ts
- src/app/pages/sharing/smb/smb-list/smb-list.component.ts
- src/app/pages/sharing/webdav/webdav-form/webdav-form.component.ts
- src/app/pages/sharing/webdav/webdav-list/webdav-list.component.ts
>  Add translation markers to the sharing section

- src/app/pages/shell/shell.component.html
- src/app/pages/shell/shell.component.ts
> Shell: auto resize

- src/app/pages/services/components/service-ftp/service-ftp.component.ts
> ftp service check if no certificate installed

- src/app/pages/common/entity/entity-form/entity-form.component.ts
This fixes System General and possibly others with single select dropdowns
Ticket: #30261
> Values should only be array type if setting a multiple select

- src/app/services/notifications.service.ts
forEach is dangerous
Ticket: #30261
> Fix a traceback that happened to me with notifications that caused some pages to not load

- src/app/pages/common/entity/entity-form/entity-form.component.ts
- src/app/pages/sharing/smb/smb-form/smb-form.component.ts
> Fix SMB Edit

- src/app/services/tour.service.ts
> Tour service: translation marker to tour titles and contents

- src/app/pages/system/support/support.component.html
- src/app/pages/system/support/support.component.ts
also made registration link more apparent. :D
> added field validation for required fields.

- src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.css
- src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.html
- src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.ts
- src/app/pages/dashboard/dashboard.html
Added conditionals in widgetsysinfo html and ts files to detect ixsystems as manufacturer. Should now show serial for any hardware with ixsystems in the manufacturer attribute. Also fixed a few flex-layout issues in the dashboard and removed debug messages from widget
> Fixed ticket #30321

- src/app/pages/jails/jail-add/jail-add.component.ts
- src/app/pages/jails/jail-edit/jail-edit.component.ts
- src/app/pages/plugins/plugin-add/plugin-add.component.ts
- src/app/services/ws.service.ts
Removed dialogService on ws.services component
> Fix ws error dialog

- src/app/pages/storage/snapshots/snapshot-clone/snapshot-clone.component.ts
- src/app/pages/storage/storage.routing.ts
- src/app/pages/storage/volumes/datasets/dataset-delete/dataset-delete.component.ts
- src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
- src/app/pages/storage/volumes/datasets/dataset-permissions/dataset-permissions.component.ts
- src/app/pages/storage/volumes/manager/manager.component.html
- src/app/pages/storage/volumes/manager/manager.component.ts
- src/app/pages/storage/volumes/status/status.component.html
- src/app/pages/storage/volumes/status/status.component.ts
- src/app/pages/storage/volumes/volume-delete/volume-delete.component.ts
- src/app/pages/storage/volumes/volume-import/volume-import.component.ts
- src/app/pages/storage/volumes/volume-unencryptimports/volume-unencryptimport.component.ts
- src/app/pages/storage/volumes/volumeaddkey-form/volumeaddkey-form.component.ts
- src/app/pages/storage/volumes/volumecreatekey-form/volumecreatekey-form.component.ts
- src/app/pages/storage/volumes/volumerekey-form/volumerekey-form.component.ts
- src/app/pages/storage/volumes/volumes-list/volumes-list.component.html
- src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
- src/app/pages/storage/volumes/volumeunlock-form/volumeunlock-form.component.ts
- src/app/pages/storage/volumes/zvol/zvol-add/zvol-add.component.ts
- src/app/pages/storage/volumes/zvol/zvol-delete/zvol-delete.component.ts
- src/app/pages/storage/volumes/zvol/zvol-edit/zvol-edit.component.ts
- src/app/services/navigation/navigation.service.ts
- src/app/services/tour.service.ts
> Initial attempt to rename volume pool throughout all the UI

- src/app/core/services/api.service.ts
- src/app/pages/vm/vm-cards/vm-card-edit.component.ts
- src/app/pages/vm/vm-cards/vm-cards.component.ts
Fixed the clone button on vm cards and added transitional states and message bus integration.
> Vb clone fix

- src/app/pages/vm/vm-cards/vm-cards.component.ts
> fix power button, removed console.log, fixed some vscode suggested 

- src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
> Add exec field to dataset options

- src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
> Use websocket call for dataset promotion

- src/app/pages/account/groups/group-form/group-form.component.ts
- src/app/pages/account/users/user-form/user-form.component.ts
> Add required markers to users and groups

- src/app/pages/system/CloudCredentials/CloudCredentials-B2/CloudCredentials-B2.component.ts
- src/app/pages/system/CloudCredentials/CloudCredentials-amazon/CloudCredentials-amazon.component.ts
- src/app/pages/system/CloudCredentials/CloudCredentials-azure/CloudCredentials-azure.component.ts
- src/app/pages/system/CloudCredentials/CloudCredentials-gcs/CloudCredentials-gcs.component.ts
- src/app/pages/system/ca/ca-import/ca-import.component.ts
- src/app/pages/system/ca/ca-intermediate/ca-intermediate.component.ts
- src/app/pages/system/ca/ca-internal/ca-internal.component.ts
- src/app/pages/system/certificates/certificate-csr/certificate-csr.component.ts
- src/app/pages/system/certificates/certificate-edit/certificate-edit.component.ts
- src/app/pages/system/certificates/certificate-import/certificate-import.component.ts
- src/app/pages/system/certificates/certificate-internal/certificate-internal.component.ts
> Mandatory field validators for system section

- src/app/pages/services/components/service-dc/service-dc.component.ts
- src/app/pages/services/components/service-ftp/service-ftp.component.ts
- src/app/pages/services/components/service-nfs/service-nfs.component.ts
- src/app/pages/services/components/service-smart/service-smart.component.ts
- src/app/pages/services/components/service-smb/service-smb.component.ts
- src/app/pages/services/components/service-ups/service-ups.component.ts
- src/app/pages/sharing/iscsi/associated-target/associated-target-form/associated-target-form.component.ts
- src/app/pages/sharing/iscsi/authorizedaccess/authorizedaccess-form/authorizedaccess-form.component.ts
- src/app/pages/sharing/iscsi/extent/extent-form/extent-form.component.ts
- src/app/pages/sharing/iscsi/globalconfiguration/globalconfiguration.component.ts
- src/app/pages/task-calendar/rsync/rsync-form/rsync-form.component.ts
> Mandatory field validators for Service section

- src/app/pages/common/entity/entity-form/components/form-explorer/form-explorer.component.html
- src/app/pages/sharing/afp/afp-form/afp-form.component.ts
- src/app/pages/sharing/nfs/nfs-form/nfs-form.component.ts
- src/app/pages/sharing/smb/smb-form/smb-form.component.ts
- src/app/pages/sharing/webdav/webdav-form/webdav-form.component.ts
> Add required validators to the sharing section

- src/app/pages/network/interfaces/interfaces-form/interfaces-form.component.ts
- src/app/pages/network/laggs/lagg-form/lagg-form.component.ts
- src/app/pages/network/staticroutes/staticroute-form/staticroute-form.component.ts
- src/app/pages/network/vlans/vlan-form/vlan-form.component.ts
> Add required validators to the networking section

- src/app/pages/common/entity/entity-form/entity-form.component.html
- src/app/pages/common/entity/entity-form/entity-form.component.scss
- src/app/pages/system/general/general.component.html
> Fix tooltips getting cut off in entity-form

- src/app/pages/account/groups/group-list/group-list.component.ts
> Make the group name show up first in the list

- src/app/app.routes.ts
- src/app/pages/network/laggs/lagg-list/lagg-list.component.ts
- src/app/pages/network/network.routing.ts
- src/app/pages/network/vlans/vlan-list/vlan-list.component.ts
- src/app/pages/preferences/preferences.routing.ts
- src/app/pages/services/services.routing.ts
- src/app/pages/storage/VMware-snapshot/VMware-snapshot-list/VMware-snapshot-list.component.ts
- src/app/pages/storage/disks/disks-list/disks-list.component.ts
- src/app/pages/storage/storage.routing.ts
- src/app/pages/system/alertservice/alertservice-list/alertservice-list.component.ts
- src/app/pages/system/system.routing.ts
- src/app/pages/task-calendar/task-calendar.routing.ts
- src/app/pages/vm/vm.routing.ts
> Attempt to make the titles and breadcrumbs consistent

- src/app/pages/task-calendar/cloudsync/cloudsync-form/cloudsync-form.component.html
- src/app/pages/task-calendar/cloudsync/cloudsync-form/cloudsync-form.component.ts
> Cloudsync: check if commit fails with error dialog

- src/app/pages/storage/volumes/manager/disk/disk.component.css
- src/app/pages/storage/volumes/manager/manager.component.html
- src/app/pages/storage/volumes/manager/vdev/vdev.component.css
- src/app/pages/storage/volumes/manager/vdev/vdev.component.html
confusing and screwy with multiple vdevs, minor css tweaks and require a
name
Ticket: #31206
> Tweaks to volume manager, hiding checkbox for vdevs since it is

- src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
> Prevent editing permissions of iocage dataset

- src/app/pages/network/interfaces/interfaces-form/interfaces-form.component.ts
> Hide the appropriate fields in network interfaces when dhcp or ipv6auto is checked

- src/app/pages/common/entity/entity-form/components/tooltip/tooltip.component.css
- src/app/pages/common/entity/entity-form/components/tooltip/tooltip.component.html
- src/app/pages/common/entity/entity-form/components/tooltip/tooltip.component.ts
> Dynamc tooltips

- src/app/pages/storage/snapshots/snapshot-clone/snapshot-clone.component.ts
- src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
> Only allow promoting of clone datasets

- src/app/components/common/topbar/topbar.template.html
(as we discussed in our meeting it gets in the way and the traditional
way of changing languages has always been to go to system general)
> Remove language menu from the topbar

- src/app/components/common/topbar/topbar.template.html
> Add missing settings tooltip to gear

- src/app/pages/system/general/general.component.html
- src/app/pages/system/general/general.component.ts
> Replaced FAB buttons on system general page

- src/app/pages/system/tunable/tunable-form/tunable-form.component.ts
> Tunable: validators for tunable, disabled save button when invalid

- src/app/components/common/topbar/topbar.component.ts
> Tour: save show/hide tour to user preference

- src/app/pages/system/general/config-reset/config-reset.component.html
- src/app/pages/system/general/config-reset/config-reset.component.ts
- src/app/pages/system/general/config-save/config-save.component.html
- src/app/pages/system/general/config-save/config-save.component.ts
- src/app/pages/system/general/config-upload/config-upload.component.html
- src/app/pages/system/general/config-upload/config-upload.component.ts
> Cancel button on config save/update/reset page

- src/app/pages/common/error-dialog/error-dialog.component.html
- src/app/pages/common/info-dialog/info-dialog.component.html
Ticket: #31704
Info and error dialog boxes were editable.
> Change textarea on info and error dialogs to readonly

- src/app/pages/common/entity/entity-table/entity-table.component.html
Ticket: #31803 
A simple fix; mostly I'm experimenting in writing a ticket. ;)
> Fix spacing issue on jails page

- src/app/pages/network/configuration/configuration.component.ts
> Add additional domains field to network configuration

- src/app/pages/common/entity/entity-table/entity-table.component.html
- src/assets/styles/fn-styles.css
Fixed with a universal selector (a blunt instrument) but seems to work without problems
> Col overflow ellipsis

- src/app/pages/services/components/service-smb/service-smb.component.ts
(I thought I could be cleaver with these things but turns out it don't work)
Ticket: #31923
> Change unix permissions components for smb form to validated inputs

- src/app/pages/storage/VMware-snapshot/VMware-snapshot/VMware-snapshot-form.component.ts
- src/app/pages/storage/import-disk/import-disk.component.ts
- src/app/pages/storage/snapshots/snapshot-add/snapshot-add.component.ts
- src/app/pages/storage/volumes/volume-delete/volume-delete.component.ts
- src/app/pages/storage/volumes/volume-import/volume-import.component.ts
- src/app/pages/storage/volumes/volume-unencryptimports/volume-unencryptimport.component.ts
- src/app/pages/storage/volumes/volumeaddkey-form/volumeaddkey-form.component.ts
- src/app/pages/storage/volumes/volumecreatekey-form/volumecreatekey-form.component.ts
- src/app/pages/storage/volumes/volumerekey-form/volumerekey-form.component.ts
- src/app/pages/storage/volumes/volumeunlock-form/volumeunlock-form.component.ts
- src/app/pages/storage/volumes/zvol/zvol-add/zvol-add.component.ts
Finished adding
,
validation: [Validators.required],
required: true
To all the forms in storage.  
Also to Detach Volume added a confirmation.  In addition to the "Delete All Contents" thing..  Now you have to confirm before button allows pushng.  Did that for all things.  Don't let form poppy if there's no default parameter(s) values required.
Easy enough to do this.. but testing requires trucking around the Storage Section and trying all forms.  Ive done this.. But should be verified by another.
> Feature 31158

- src/app/pages/services/components/service-nfs/service-nfs.component.ts
Ticket: #31899
Remove unneeded colons
> Correct errant commit from earlier

- src/app/pages/common/entity/entity-form/entity-form.component.ts
- src/app/pages/network/interfaces/interfaces-form/interfaces-form.component.ts
- src/app/pages/network/network.module.ts
- src/app/services/network.service.ts
> Add aliases support to network interfaces

- src/app/pages/common/entity/entity-form/entity-form.component.ts
- src/app/pages/common/entity/entity-table/entity-table.component.ts
- src/app/pages/network/interfaces/interfaces-form/interfaces-form.component.ts
- src/app/pages/network/interfaces/interfaces-list/interfaces-list.component.ts
- src/app/pages/network/laggs/lagg-list/lagg-list.component.ts
- src/app/pages/network/vlans/vlan-form/vlan-form.component.ts
- src/app/pages/network/vlans/vlan-list/vlan-list.component.ts
> Add warnings about loss of network connectivity throughout the network section

- src/app/pages/system/advanced/advanced.component.ts
> Add a spinner to save debug

- src/app/components/common/notifications/notifications.component.html
Ticket: #30486
Relabels 'notifications' to actions w/o messing with file structure (which is all named 'notifications'). Not sure I understand the scope of this project; can't seem to generate notifications on my VM. DKM
> Change notifications to alerts

- src/app/pages/services/components/service-dc/service-dc.component.ts
I messed up the commit on this yesterday. In the meantime, the ticket may have been pulled. Was #32244. Sorry.
> Fix typos on Services-DC Controller (updating an errant commit)

- src/app/pages/services/components/service-webdav/service-webdav.component.ts
>  Add missing option to webdav authentication, also hide fields per setting like old ui

- src/app/pages/network/laggs/lagg-list/lagg-list.component.ts
- src/app/pages/network/laggs/members/members-form/index.ts
- src/app/pages/network/laggs/members/members-form/members-form.component.ts
- src/app/pages/network/laggs/members/members-list/index.ts
- src/app/pages/network/laggs/members/members-list/members-list.component.ts
- src/app/pages/network/network.module.ts
- src/app/pages/network/network.routing.ts
> Add lagg members button/crud

- src/app/core/services/api.service.ts
- src/app/pages/vm/vm-cards/vm-cards.component.css
- src/app/pages/vm/vm-cards/vm-cards.component.html
- src/app/pages/vm/vm-cards/vm-cards.component.ts
This removes delete button and replaces it with an options icon/popup menu with more start options and a delete option. For quick toggling of basic power states the old power button is left where it was.
> Tkt #27457: 

- src/app/pages/task-calendar/replication/replication-form/replication-form.component.ts
- Local build testing: no issues.
> Remove redundant word from replication tooltip.

- src/app/components/common/topbar/topbar.template.html
> Change notification tooltip to alert

- src/app/pages/services/components/service-ups/service-ups.component.ts
> Add missing options to UPS service

- src/app/pages/vm/dockervm-wizard/dockervm-wizard.component.ts
Added missing tooltips.
Reviewed and shortened existing tooltips.
Adjusted placeholder values in a few spots for clarity.
Local build testing: no issues.
> Update Docker VM Wizard field names and tooltips.

- src/app/pages/account/users/user-form/user-form.component.ts
- src/app/pages/common/entity/entity-form/entity-form.component.html
- src/app/pages/common/entity/entity-form/entity-form.component.scss
- src/app/pages/common/entity/entity-form/entity-form.component.ts
- src/app/pages/common/entity/entity-form/models/fieldset.interface.ts
- src/app/pages/vm/devices/device-edit/device-edit.component.ts
- src/assets/styles/themes/ix-blue.scss
Implemented fieldsets into entity-form. Also made css adjustments to font sizes and checkbox sizes
> Reduce entities

- src/app/components/common/topbar/topbar.template.html
- src/assets/styles/egret_overrides.css
- src/assets/styles/themes/ix-blue.scss
Removes redundant path to system/general and some smaller global css fixes
> Tkt #31692

- src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
> Add missing dataset option 'share_type' to dataset-form

- src/app/views/sessions/signin/signin.component.ts
> Do not prefill root into the login box

- src/app/pages/services/components/service-tftp/service-tftp.component.ts
> Fix TFTP permissions

- src/app/pages/storage/volumes/volume-delete/volume-delete.component.ts
- src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
> Rename volume detach/delete to delete

- src/app/pages/common/entity/entity-form/entity-form.component.ts
- src/app/pages/system/advanced/advanced.component.ts
> Update system advanced to use websocket calls

- src/app/pages/storage/import-disk/import-disk.component.ts
> Add msdosfs locale to disk import and fix the ui so it works with the new api

- src/app/components/common/topbar/topbar.component.ts
- src/app/components/common/topbar/topbar.template.html
- src/app/views/others/reboot/reboot.component.html
> Change restart to reboot in settings

- src/assets/styles/fn-styles.css
- src/assets/styles/themes/ix-blue.scss
> Make checkboxes and ellipsis work together

- src/app/pages/services/components/service-dynamicdns/service-dynamicdns.component.ts
- Adjust field names slightly to match the old UI.
- Port over tooltip messages from the FreeNAS guide for the new fields.
- NPM local build testing: no issues.
> Update field names and add missing tooltips for Services/DynamicDNS:

- src/app/pages/system/update/update.component.ts
> Close update check after error

- src/app/pages/systemprocesses/system-processes.component.ts
> Use a promise to make sure xterm is initialized before calling top

- src/app/views/sessions/signin/signin.component.ts
(this helps with the issue of getting logged out prematurely)
Ticket: #31425
> Increase token timeout from 1 minute to 5 minutes

- src/app/pages/sharing/smb/smb-form/smb-form.component.ts
> Have default permissions checked when creating an smb share as per discussion

- src/app/pages/system/ca/ca-form/ca-form.component.ts
- src/app/pages/system/ca/ca-import/ca-import.component.ts
- src/app/pages/system/ca/ca-intermediate/ca-intermediate.component.ts
- src/app/pages/system/ca/ca-internal/ca-internal.component.ts
- src/app/pages/system/certificates/certificate-csr/certificate-csr.component.ts
- src/app/pages/system/certificates/certificate-edit/certificate-edit.component.ts
- src/app/pages/system/certificates/certificate-import/certificate-import.component.ts
- src/app/pages/system/certificates/certificate-internal/certificate-internal.component.ts
- src/app/pages/system/tunable/tunable-form/tunable-form.component.ts
Review and reduce tooltip length for all tooltips in the above mentioned files.
Local build testing with NPM: no issues.
> Review tooltips for System/CAs, Certificates, and Tunables:

- src/app/pages/network/configuration/configuration.component.ts
- src/app/pages/network/interfaces/interfaces-form/interfaces-form.component.ts
- src/app/pages/network/ipmi/ipmi.component.ts
- src/app/pages/network/laggs/lagg-form/lagg-form.component.ts
- src/app/pages/network/staticroutes/staticroute-form/staticroute-form.component.ts
- src/app/pages/network/vlans/vlan-form/vlan-form.component.ts
- Review, reduce, fix all tooltips in the Network category.
- Fix a few whitespace errors.
> Review all Network tooltips:

- src/app/pages/sharing/afp/afp-form/afp-form.component.ts
-Update volume to pool references.
-Review for errors. 
-Tighten up sentences.
> Reviewed Sharing -> AFP tooltips:

- src/app/pages/sharing/webdav/webdav-form/webdav-form.component.ts
-Changed volume to pool
-Made minor wording changes.
-Tested the build.
> Reviewed Sharing -> WebDAV tooltips:

- src/app/pages/sharing/nfs/nfs-form/nfs-form.component.ts
-Replaced "volume" references with "pool."
-Replaced "checked"  references with "set"
-Cleaned up the formatting so all the tooltip lines are aligned with the first line. 
- Tested the build.
> Reviwed Sharing -> NFS tooltips:

- src/app/pages/common/entity/entity-table/entity-table.component.html
- src/app/pages/common/entity/entity-table/entity-table.component.scss
- src/app/pages/storage/volumes/manager/manager.component.html
- src/app/pages/storage/volumes/manager/vdev/vdev.component.html
- src/assets/styles/themes/ix-blue.scss
> Fix mat-checkbox alignment on Mozilla

- src/app/pages/vm/dockervm-wizard/dockervm-wizard.component.ts
- src/app/pages/vm/vm-cards/vm-card-edit.component.ts
- src/app/pages/vm/vm-cards/vm-table.component.ts
- src/app/pages/vm/vm-wizard/vm-wizard.component.ts
- Rewrite/reduce/fix VMs related tooltips.
- Whitespace fixes.
- Adjust field titles to ensure consistency.
- Local testing with npm: no issues.
> Review VMs tooltips:

- src/app/pages/jails/jail-add/jail-add.component.ts
- src/app/pages/jails/jail-wizard/jail-wizard.component.ts
Also added the import for the regexValidator
> Add jail jail name validation

- src/app/pages/jails/storages/storage-form/storage-form.component.ts
- Quick rework of mountpoint tooltips.
- Local testing with NPM: no issues.
> Review Jail mountpoints tooltips:

- src/app/pages/system/alertservice/alert-service/alert-service.component.ts
- Rewrite/fix/shorten all tooltips in the Alert Services area.
- Add external links to outside alert service documentation.
- Local testing with npm: no issues.
> Review System/Alert Services tooltips:

- src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
> reflect parent dataset values

- src/app/pages/sharing/iscsi/globalconfiguration/globalconfiguration.component.ts
-Reviewed and reword text to improve readability.
-Fix formatting issues.
-Tested the build with npm.
> Sharing -> ISCSI -> Global Configuration tooltip review:

- src/app/pages/services/components/service-lldp/service-lldp.component.ts
- src/app/pages/services/components/service-nfs/service-nfs.component.ts
- src/app/pages/services/components/service-rsync/rsyncconfiguration/configure_rsync/configure_rsync.component.ts
- src/app/pages/services/components/service-rsync/rsyncconfiguration/rsyncmodule/rsyncconfiguration-form.component.ts
- src/app/pages/services/components/service-s3/service-s3.component.ts
- src/app/pages/services/components/service-smart/service-smart.component.ts
- src/app/pages/services/components/service-snmp/service-snmp.component.ts
- src/app/pages/services/components/service-ssh/service-ssh.component.ts
- src/app/pages/services/components/service-tftp/service-tftp.component.ts
- src/app/pages/services/components/service-ups/service-ups.component.ts
- src/app/pages/services/components/service-webdav/service-webdav.component.ts
- Reviewed tooltips for the LLDP, NFS, rsync, rsync module, S3, S.M.A.R.T., SNMP, SSH, TFTP, UPS, and WebDAV services.
- Added some default values in fields.
- Cleaned up placeholder text in a few areas.
- Whitespace cleanup.
- Local testing with NPM: no issues.
> Review some Services tooltips:

- src/app/pages/storage/storage.routing.ts
- src/app/pages/storage/volumes/volumeaddkey-form/volumeaddkey-form.component.ts
- src/app/pages/storage/volumes/volumecreatekey-form/volumecreatekey-form.component.ts
- src/app/pages/storage/volumes/volumerekey-form/volumerekey-form.component.ts
- src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
- src/app/services/storage.service.ts
> Fixes for add recovery key and rekey and unlock

- src/app/pages/task-calendar/replication/replication-list/replication-list.component.ts
- src/app/pages/task-calendar/scrub/scrub-list/scrub-list.component.ts
- src/app/pages/task-calendar/snapshot/snapshot-list/snapshot-list.component.ts
Also clean up some whitespace.
Local testing with NPM: no issues.
> Rename Volumes to Pools for table views on three Tasks pages:

- src/app/pages/sharing/iscsi/extent/extent-form/extent-form.component.ts
-Reviewed for errors.
-Adjusted formatting to our style.
-Replaced "volume" with "pool" and "checked" with "set".
-Passed NPM build test.
> Reviewed sharing -> iscsi -> extent -> add tooltips:

- src/app/pages/services/components/service-smb/service-smb.component.ts
-Shorten text to improve readability.
- Convert Volume to Pool
-Passed npm build test.
> Reviewed Services -> SMB tooltips:

- src/app/pages/services/components/service-afp/service-afp.component.ts
-Reviewed tooltips for errors and tightened up sentences for improved readability. 
-Replaced "checked" with "set" and "volume" with "pool". 
-Adjust formatting.
-Passed NPM test.
> Reviewed services -> afp tooltips:

- src/app/pages/sharing/iscsi/target/target-add/target-add.component.ts
-Made minor edits and fixed formatting issues.
-Passed npm build test.
> Reviewed iSCSI -> Target -> Add tooltips:

- src/app/pages/sharing/iscsi/initiator/initiator-form/initiator-form.component.ts
-Review and fix formatting issues.
-No build errors.
> Review iscsi -> initiator tooltips:

- src/app/views/sessions/signin/signin.component.html
- src/app/views/sessions/signin/signin.component.ts
> Fixes to login screen to make the behavior more similar to old UI

- src/app/pages/services/components/service-ftp/service-ftp.component.ts
-Updated checked to set.
-Reviewed for errors.
-Passed npm build.
> Reviewed service -> ftp tooltips:

- src/app/pages/services/components/service-dc/service-dc.component.ts
- src/app/pages/services/components/service-dynamicdns/service-dynamicdns.component.ts
-Review and improve tooltips.
-Passed npm build test with no errors.
> Reviewed the domain controller and dynamic dns tooltips:

- src/app/pages/network/interfaces/interfaces-list/interfaces-list.component.ts
> Add ipv6 configure and options to network interfaces list

- src/app/components/common/topbar/topbar.component.ts
- src/app/views/sessions/signin/signin.component.ts
> Update message that appears when switching from Angular UI to Legacy UI:

- src/app/pages/account/users/user-form/user-form.component.ts
> Made minor text fixes.

- src/app/pages/vm/devices/device-add/device-add.component.ts
- src/app/pages/vm/devices/device-cdrom-add/device-cdrom-add.component.ts
- src/app/pages/vm/devices/device-disk-add/device-disk-add.component.ts
- src/app/pages/vm/devices/device-edit/device-edit.component.ts
- src/app/pages/vm/devices/device-nic-add/device-nic-add.component.ts
- src/app/pages/vm/devices/device-rawfile-add/device-rawfile-add.component.ts
- src/app/pages/vm/devices/device-vnc-add/device-vnc-add.component.ts
Found these tooltips untracked in my document and did a quick review.
Also cleaned up extra whitespace in the files.
Renamed a few placeholder values to be cleaner/less confusing.
NPM testing: no issues.
> Rewrite VMs/Device/Add * tooltips, also VMs/Device/Edit tooltips:

- src/app/pages/system/advanced/advanced.component.ts
> added "ATA Security User" and "SED password".

- src/app/pages/jails/jail-edit/jail-edit.component.ts
Updated the tooltips to current formatting practices
Updated tooltips for grammar and to reflect actaul usage
> Jail Edit tooltip review

- src/app/pages/jails/jail-add/jail-add.component.ts
All Jail Add tooltips have been formatted to current standards.
Updated tooltips to reflect the current state of the gui and iocage.
> Update Jail Add tooltips formatting, grammar, and accuracy

- src/app/pages/storage/snapshots/snapshot-add/snapshot-add.component.ts
> Update field from Volume -> Pool

- src/app/pages/shell/shell.component.ts
> Fix small text formatting error in Shell tooltip.

- src/app/pages/storage/volumes/manager/manager.component.html
- src/app/pages/storage/volumes/manager/vdev/vdev.component.html
> Remove comments, restore a missing var

- src/app/pages/storage/snapshots/snapshot-clone/snapshot-clone.component.ts
> Make snapshot clone work for the root dataset like it does in the old UI

- package.json
- src/app/pages/common/entity/entity-form/components/dynamic-field/dynamic-field.directive.ts
- src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.css
- src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.html
- src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.ts
- src/app/pages/common/entity/entity.module.ts
- src/app/pages/preferences/page/forms/customtheme/customtheme.component.ts
- src/assets/styles/themes/ix-blue.scss
- src/styles.css
Creates a advanced scheduler featuring a select list and optional popup scheduler with preview. Can be easily added to any entity-form component
> FormScheduler Ticket 33327

- src/app/pages/storage/volumes/volumes-list/volumes-list.component.html
- src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
> Add compressratio data to pool list

- src/app/pages/task-calendar/snapshot/snapshot-form/snapshot-form.component.ts
> Update text in form from Volume -> Pool.

- src/app/pages/system/bootenv/bootenv-list/bootenv-list.component.html
- src/app/pages/system/bootenv/bootenv-list/bootenv-list.component.ts
> Remove fab button from boot environments by moving the extra actions into buttons

- src/app/components/common/layouts/admin-layout/admin-layout.component.css
- src/app/components/common/layouts/admin-layout/admin-layout.template.html
> Link to dash 34318

- src/assets/styles/themes/ix-blue.scss
> Reposition oddly placed tooltip

- src/app/components/common/topbar/topbar.template.html
> Break power-related settings out into a new menu

- src/app/pages/system/update/update.component.css
- src/app/pages/system/update/update.component.html
> style buttons and selector on update page

- src/app/pages/common/entity/entity-table/entity-table.component.html
- src/app/pages/common/entity/entity-table/entity-table.component.ts
- src/app/pages/task-calendar/replication/replication-list/replication-list.component.ts
> Move replication actions from fab icon into table header

- src/app/pages/system/general/general.component.ts
> Hide certificate and https redirect fields depending on the protocol setting in System General and move certificate to the top.

- src/app/views/sessions/signin/signin.component.html
> Add legacy ui option and copyright back but only show when the websocket is available.

- src/app/pages/jails/jail-add/jail-add.component.ts
- src/app/pages/jails/jail-edit/jail-edit.component.ts
- src/app/pages/jails/jail-wizard/jail-wizard.component.ts
Everything is documented in https://redmine.ixsystems.com/issues/34669
> Jails vnet fix

- src/app/pages/task-calendar/replication/replication-form/replication-form.component.ts
> Replication bandwidth uses kilobits not kilobytes

- src/app/pages/common/entity/entity-form/components/form-permissions/form-permissions.component.html
- src/app/pages/common/entity/entity-form/models/field-config.interface.ts
- src/app/pages/services/components/service-tftp/service-tftp.component.ts
- src/app/pages/services/services.module.ts
> Fix issues in TFTP with non-usable exec permissions and no users in dropdown

- src/app/pages/system/update/update.component.ts
Smooth out the update text strings.
> Update component text a little.

- src/app/pages/task-calendar/cloudsync/cloudsync-form/cloudsync-form.component.ts
https://redmine.ixsystems.com/issues/26924
> Update Cloud Sync tooltips

- src/assets/styles/themes/ix-blue.scss
> Change text overflow setting to remove scrollbar

- src/app/components/common/dialog/about/about-dialog.component.css
- src/app/components/common/dialog/about/about-dialog.component.html
> Fix alignment on About Dialog

- src/app/pages/system/certificates/certificate-edit/certificate-edit.component.ts
> Fix edit mode for certificates/csr and fix the tooltips

- src/assets/styles/themes/ix-blue.scss
> Fix issue where datatable rows get stuck at original window size

- src/app/views/sessions/signin/signin.component.ts
> Dismiss snackbar upon successful login

- src/app/pages/common/entity/entity-wizard/entity-wizard.component.css
- src/app/pages/common/entity/entity-wizard/entity-wizard.component.html
Ticket: #34110
Adds a Cancel button throughout entity wizards. Tested it for function and spacing on Jails, Pools and VM wizards
> Add cancel buttons to entity wizard

- src/app/pages/account/users/change-password/change-password.component.ts
> Do not log user out after password change

- src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
> Fix issues with unlock and detatch pool

- src/app/pages/sharing/smb/smb-form/smb-form.component.ts
> Add Periodic Snapshot Task setting to SMB Add

- src/app/pages/network/interfaces/interfaces-form/interfaces-form.component.ts
> How did aliases ever work???

- src/app/pages/common/entity/entity-form/components/form-input/form-input.component.html
> Add dummy input fields to prevent the browser from auto-filling passwords

- src/app/pages/services/components/service-smart/service-smart.component.ts
> Replace commas with spaces so that emails are formatted properly for SMART service

- src/app/pages/services/components/service-ups/service-ups.component.ts
> Use ups.port_choices and ups.driver_choices to get ports and drivers for UPS

- src/app/pages/network/interfaces/interfaces-form/interfaces-form.component.ts
> Add warning to let the user know they should configure the webui interface first

- src/app/pages/services/components/service-s3/service-s3.component.ts
> Warn users when they try to pick a root dataset for S3 minio

- README.md
I've personally ran into these issues
The solutions provided fixed everything for me.
> Update to address a few common issues

- src/app/pages/reportsdashboard/reportsdashboard.html
- src/assets/styles/charts.css
Ticket #35817 
On the reports page the chart tooltips (on hover) don't have a background color assigned making them unreadable. This branch fixes that issue.
> Reports css

- src/app/pages/system/certificates/certificate-edit/certificate-edit.component.ts
- src/app/pages/system/certificates/certificate-list/certificate-list.component.ts
- src/app/pages/system/system.routing.ts
> Rename certificate edit to view and remove tooltips from readonly fields

- src/app/pages/system/ca/ca-edit/ca-edit.component.ts
- src/app/pages/system/ca/ca-edit/index.ts
- src/app/pages/system/ca/ca-list/ca-list.component.ts
- src/app/pages/system/system.module.ts
- src/app/pages/system/system.routing.ts
> Add page for editing/viewing CAs

- src/app/pages/system/CloudCredentials/cloudcredentials-form/cloudcredentials-form.component.ts
https://redmine.ixsystems.com/issues/36458
> This corrects the erroneous Endpoint URL tooltip.

- src/app/pages/account/groups/members/members.component.html
> Don't show "Members of groupname group" until groupname is populated

- src/app/pages/system/advanced/advanced.component.ts
> s/Enable Console Menu/Show Text Console without Password Prompt/

- src/app/pages/services/components/service-s3/service-s3.component.ts
> Populate secret_key fields with secret_key data in s3

- src/app/pages/storage/volumes/zvol/zvol-form/zvol-form.component.ts
Local build testing: no issues.
> Update erroneous tooltip in Add zvol page.

- src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
> Do not show snapshot create for non-dataset/zvol

- src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
> Add option to unlock pool using recovery key and hide actions that cannot be accessed when pool is locked

- src/app/pages/common/error-dialog/error-dialog.component.html
- src/app/pages/storage/volumes/manager/manager.component.html
- src/app/pages/storage/volumes/manager/manager.component.ts
- src/app/services/dialog.service.ts
>  Add validation for pool name against existing pools and fix redundant error message

- src/app/pages/services/components/service-s3/service-s3.component.ts
> Fix warning for first time setup of minio dataset

- src/app/pages/services/components/service-smb/service-smb.component.ts
https://github.com/freenas/freenas/pull/1343
https://redmine.ixsystems.com/issues/36103
https://github.com/freenas/freenas/pull/1452
> Fix lack of clarity in NTLMv1

- src/app/pages/task-calendar/rsync/rsync-form/rsync-form.component.ts
> Fix rsync task "extra options"

- src/app/pages/system/general/general.component.ts
> Fix possible race condition that causes a traceback on system general

- src/app/app.component.ts
- src/index.html
Ticket: #37268
Shortens page title from pathname to 'FreeNAS - <hostname>'
> Shorten page titles displayed in tabs

- src/app/pages/task-calendar/rsync/rsync-list/rsync-list.component.ts
> Add run now to rsync tasks

- src/app/pages/system/advanced/advanced.component.ts
Ticket: #37423
Removes screen saver option from System > Advanced
> Remove screen saver choice from sys-advanced

- src/app/pages/system/update/update.component.ts
adding @william-gr as well as he maybe able to point out some of wrong workflow as Legacy UI train switch logic was implemented here as  well.
> implemented legecy UI updater train switch logic.

- jenkins-yarn
First try of a webui-yarn build
> - Yarn build

- src/app/pages/system/advanced/advanced.component.ts
Ticket: #37846
Adds a label of sorts over the swap size input box on System > Advanced
> Put a label over the swap size field on system > advanced

- src/app/core/components/widgets/widgetnetinfo/widgetnetinfo.component.html
- src/app/core/components/widgets/widgetnetinfo/widgetnetinfo.component.ts
Fixed widgetnetinfo html template so it only shows information for the Primary NIC (the interface the UI is connected to.)
> Fixed widgetnetinfo html template

- src/app/views/others/reboot/reboot.component.css
- src/app/views/others/reboot/reboot.component.html
- src/app/views/others/reboot/reboot.component.ts
- src/app/views/others/shutdown/shutdown.component.css
- src/app/views/others/shutdown/shutdown.component.html
- src/app/views/others/shutdown/shutdown.component.ts
Ticket: #39228
Adds style and branding to the shutdown screen
Gives ability to shutdown and restart screens to switch to TrueNAS logo and text when appropriate
> Restart shutdown redesign

- src/app/core/services/api.service.ts
- src/app/pages/vm/vm-cards/vm-cards.component.ts
added `responseFailedEvent` to the ApiCall to handle error.
> Raise descriptive error when VM fails to start

- src/app/views/others/shutdown/shutdown.component.html
Ticket: #38993
A PR from this ticket was merged already, but this is a small change - remove sign-in link
> Remove sign in link from shutdown screen

- src/app/pages/common/entity/entity-table/entity-table.component.html
- src/app/pages/common/entity/entity-table/entity-table.component.ts
> Convert row data on display only, not on row

- src/app/views/others/reboot/reboot.component.ts
> Have browser reload login page when leaving reboot screen

- src/app/pages/system/ca/ca-sign/ca-sign.component.ts
Added tooltips for the CSRs dropdown and the Identifier field
> Add missing sign CA tooltips

- src/app/pages/system/bootenv/bootenv-clone/bootenv-clone.component.ts
- src/app/pages/system/bootenv/bootenv-create/bootenv-create.component.ts
- src/app/pages/system/bootenv/bootenv-rename/bootenv-rename.component.ts
- src/app/services/bootenv.service.ts
- src/app/services/index.ts
> added regex validation for boot environments Name fields

- src/app/pages/services/components/service-s3/service-s3.component.ts
> Fix S3 port validation (hopefully for good this time)

- src/app/components/common/layouts/admin-layout/admin-layout.component.ts
Ticket: #37188
Fix an issue with the scroll bar not showing up at first by slightly delaying the initialization
> add a short delay to scroll bar initializing

- src/app/pages/account/users/change-password/change-password.component.ts
- src/app/pages/account/users/user-form/user-form.component.ts
- src/app/pages/common/entity/entity-form/entity-form.component.html
- src/app/pages/common/entity/entity-form/entity-form.component.scss
- src/app/pages/common/entity/entity-form/entity-form.component.ts
- src/app/pages/directoryservice/ldap/ldap.component.ts
- src/app/pages/sharing/iscsi/authorizedaccess/authorizedaccess-form/authorizedaccess-form.component.ts
- src/app/pages/storage/VMware-snapshot/VMware-snapshot/VMware-snapshot-form.component.ts
- src/app/pages/storage/disks/disk-form/disk-form.component.ts
- src/app/pages/system/advanced/advanced.component.ts
- src/app/pages/system/ca/ca-add/ca-add.component.ts
- src/app/pages/system/certificates/certificate-add/certificate-add.component.ts
- src/app/pages/system/email/email.component.ts
- src/app/pages/system/support/support.component.ts
- src/assets/styles/themes/ix-blue.scss
Ticket: #33648
Adds a 'hide/show password" button on entity forms with a pw field
> Show pw button 33648

- src/app/pages/task-calendar/snapshot/snapshot-form/snapshot-form.component.ts
> Move tooltip for snapshot lifetime to the right place

- src/app/pages/system/dataset/dataset.component.ts
Tooltips updated:
System Dataset Pool
Syslog
Reporting Database
webui built with no errors
https://redmine.ixsystems.com/issues/37606
See also https://redmine.ixsystems.com/issues/29106
for discussion about the System Dataset Pool drop-down/tooltip
> Update System:SystemDataset tooltips

- src/app/pages/network/vlans/vlan-form/vlan-form.component.ts
> Add validation to vlan tag

- src/app/pages/task-calendar/smart/smart-form/smart-form.component.ts
> Fix label for smart test schedule

- src/app/pages/services/components/service-ftp/service-ftp.component.ts
> Add validation and linting fixes for FTP service

- src/assets/styles/themes/ix-blue.scss
> Fix tooltips in dialog

- src/app/pages/system/advanced/advanced.component.ts
Fields with updated tooltips:
Show Text Console without Password Prompt
Swap Size in GiB
Enable autotune
Enable Debug Kernel
Show advanced fields by default
MOTD Banner
Periodic Notification User
Use FQDN for logging
Report CPU usage in percentage
ATA Security User
SED Password
Added text "SED (Self-Encrypting-Drive) Options" above the SED options
This is to help clarify what a SED is.
webui built with no errors
Redmine: https://redmine.ixsystems.com/issues/37606
> Update System:Advanced tooltips and fields

- src/app/pages/system/system.routing.ts
Ticket for change:
https://redmine.ixsystems.com/issues/40656
> Correct System System Dataset and Tunables breadcrumbs

- src/app/pages/account/groups/group-form/group-form.component.ts
> Add validators to group add/edit, use built in error handling

- src/app/services/network.service.ts
> Update vlan pint choices to use the right params

- src/app/pages/services/services.routing.ts
> Make SMARTD breadcrumb say S.M.A.R.T.

- src/app/pages/common/entity/entity-form/components/form-select/form-select.component.html
- src/app/pages/network/interfaces/interfaces-form/interfaces-form.component.ts
>  Move interface warning to interface field and pre-populate interface with the "default" one.

- src/app/pages/system/ca/ca-add/ca-add.component.ts
- src/app/pages/system/certificates/certificate-add/certificate-add.component.ts
(CAs and Certificates use the same tooltips)
Tooltips Updated
Signing Certificate Authority
Key Length
Digest Algorithm
Lifetime
Country
Locality
Common Name
Subject Alternate Names
Certificate
Private Key
webui builds without issue
https://redmine.ixsystems.com/issues/37606
> System CAs and Certificate tooltip updates

- src/app/pages/storage/disks/disk-wipe/disk-wipe.component.ts
> Handle disk wipe percentages correctly

- src/app/pages/services/components/service-snmp/service-snmp.component.ts
Ticket: #40146
#40151
#40156
#40131
> Add validators and missing labels to SNMP, hide v3 fields when v3 is not checked

- src/app/pages/task-calendar/initshutdown/initshutdown-form/initshutdown-form.component.ts
> Fix disable/hide on init/shutdown scripts

- src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
Made edits where appropriate. Some included:
Updating "volume" to "pool".
Replace "pool:" with just the pool name. Example on line 120.
Adding full stops to end of sentences.
Formatting tooltips with the correct spacing. 
Passed build test with no errors.
> Reviewed the dialogue messages based on standards created by Tim. 

- src/app/pages/network/network.routing.ts
webui builds clean
https://redmine.ixsystems.com/issues/41160
> Update Network:Global Configuration breadcrumb

- src/app/pages/storage/import-disk/import-disk.component.ts
- src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
- src/app/pages/storage/volumes/zvol/zvol-form/zvol-form.component.ts
> Apply handleWSError to the websocket using forms of the storage section

- src/app/pages/services/components/service-smb/service-smb.component.ts
> Add length validators for netbios name and netbios alias

- src/app/pages/common/entity/entity-table/entity-table.component.ts
- src/app/pages/dashboard/dashboard.component.ts
- src/app/pages/dashboard/dashboard.html
- src/app/pages/dashboard/dashboard.scss
- src/app/pages/reportsdashboard/reportsdashboard.component.ts
- src/app/pages/reportsdashboard/reportsdashboard.html
- src/app/pages/reportsdashboard/reportsdashboard.scss
- src/app/pages/services/services.component.css
- src/app/pages/services/services.component.html
- src/app/pages/services/services.component.ts
- src/assets/styles/themes/ix-blue.scss
Ticket: #39702
Adds a delay indicator to entity tables, service table, dashboard and reports page
> Ui loading messages 39702

- src/app/components/common/topbar/topbar.component.ts
Ticket: #39087
removes the 'are you sure?' dialog when logging out
> remove confirm dialog when logging out

- src/app/pages/network/configuration/configuration.component.ts
> Hide netwait ip when netwait enabled is not checked

- src/app/pages/storage/volumes/volumes-list/volumes-list.component.css
- src/app/pages/storage/volumes/volumes-list/volumes-list.component.html
- src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
> add spinner to pools list

- src/app/pages/system/tunable/tunable-form/tunable-form.component.ts
Tooltips updated:
Variable
Value
Type drop-down
Comment field
Enabled checkbox
webui built with no errors
https://redmine.ixsystems.com/issues/37606
> System -> Tunable tooltips

- src/app/pages/task-calendar/snapshot/snapshot-form/snapshot-form.component.ts
> Sort datsets and pools in periodic snapshot form

- src/app/components/common/layouts/admin-layout/admin-layout.component.ts
- src/app/pages/system/advanced/advanced.component.ts
Ticket: #37398
Removes telemetry reporting option from Systems > Advanced
Removes console log enjoining the user to get some
> remove telemetry reporting from sys> advanced #37398

- src/app/pages/common/entity/entity-dialog/entity-dialog.component.html
> Adding id's to entity-dialog pages so they can be QA'd

- src/app/pages/task-calendar/cloudsync/cloudsync-form/cloudsync-form.component.ts
- src/app/pages/task-calendar/cron/cron-form/cron-form.component.ts
- src/app/pages/task-calendar/initshutdown/initshutdown-form/initshutdown-form.component.ts
- src/app/pages/task-calendar/replication/replication-form/replication-form.component.ts
- src/app/pages/task-calendar/resilver/resilver.component.ts
- src/app/pages/task-calendar/rsync/rsync-form/rsync-form.component.ts
- src/app/pages/task-calendar/smart/smart-form/smart-form.component.ts
Tooltips updated
Tasks:Cron Jobs
Description
Run As User
Schedule a Cron Job
Redirect Standard Output
Redirect Errors
Tasks:Init/Shutdown Scripts
Enabled
Tasks:Rsync
User
Rsync Mode
Short Description
Schedule the Rsync Task
Recursive
Archive
Delete
Preserve extended attributes
Extra Options
Enabled
webui builds without error
https://redmine.ixsystems.com/issues/37606
> Tasks tooltips update

- src/app/pages/services/services-table.component.html
- src/app/pages/services/services.component.css
- src/app/pages/services/services.component.html
- src/app/pages/services/services.component.ts
ticket: 37662
ticket: 38560
ticket: 38570
> Fix services ui

- src/app/pages/common/entity/entity-form/components/form-explorer/form-explorer.component.ts
> Change enter behavior for file explorer to select the current node

- src/app/pages/services/components/service-webdav/service-webdav.component.ts
> Convert webdav to use websocket call to fix issues

- src/app/pages/vm/vm-wizard/vm-wizard.component.ts
please create a new vm requesting to create a disk as this case was missed in previous fix,
> remove `/mnt/` when new disk is created.

- src/app/pages/storage/volumes/volumes-list/volumes-list.component.css
- src/app/pages/storage/volumes/volumes-list/volumes-list.component.html
- src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
> Hide actions that cannot be used when pool is locked and convert lock menu to unlock button when pool is locked

- src/app/pages/network/configuration/configuration.component.ts
- src/app/pages/network/interfaces/interfaces-form/interfaces-form.component.ts
- src/app/pages/network/ipmi/ipmi.component.ts
- src/app/pages/network/laggs/lagg-form/lagg-form.component.ts
- src/app/pages/network/staticroutes/staticroute-form/staticroute-form.component.ts
- src/app/pages/network/vlans/vlan-form/vlan-form.component.ts
This is all of the Network section tooltips.
> Network tooltips

- src/app/core/components/widgets/widgetcputemps/widgetcputemps.component.ts
- src/app/core/components/widgets/widgetmemoryhistory/widgetmemoryhistory.component.ts
- src/app/core/components/widgets/widgetpool/widgetpool.component.html
- src/app/core/components/widgets/widgetstorage/widgetstorage.component.ts
- src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.ts
- src/app/pages/services/components/service-ftp/service-ftp.component.ts
- src/app/pages/vm/vm-cards/vm-summary.component.ts
> Review and fix remaining instances of inconsistent GB, MB, or KB usage.

- src/app/pages/preferences/page/forms/customtheme/customtheme.component.css
> reduce z-index of card on custom theme page to put tooltips on top

- src/app/views/sessions/signin/signin.component.ts
> Add ability to log directly in with a token

- .angular-cli.json
- src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.html
An inline css background image rule was causing it. Added a ternary operator so if the the property is not set it would default to 'none'
> Fixed issue with 404 error in browser console being thrown immediately after login.

- src/app/pages/plugins/plugin-add/plugin-add.component.ts
fixed ticket: #39682, #41324, #40848
> Fix plugin fail installed issues

- src/app/components/common/topbar/topbar.component.ts
Ticket: #39383
Samantha Bonham requested a wording change.
> wording change

- src/assets/styles/themes/ix-blue.scss
Ticket: #41328
Style check boxes, various arrows and other design elements to respond to light or dark background
> Fix dark themes 41328

- src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
> Add missing option to pool detach to allow user to keep their shares

- src/app/components/common/topbar/topbar.template.html
capitalization as per Warren's request.
> Changed the Exit/Restart tooltip to Power and fixed sub button 

- src/assets/styles/themes/ix-blue.scss
Ticket: 41328
This update catches up with the new variables and theme rules
> update checkbox settings to work with new theme rules

- src/app/app.routes.ts
- src/app/components/common/topbar/topbar.template.html
- src/app/pages/preferences/preferences.routing.ts
- src/app/views/sessions/signin/signin.component.html
> editing to Ui references

- src/app/core/components/widgets/widgetpool/widgetpool.component.html
- src/app/core/components/widgets/widgetpool/widgetpool.component.ts
> Do not run filesize on values if the value is not a number (i.e. if pool is locked)

- src/app/core/components/widgets/widgetcputemps/widgetcputemps.component.css
- src/app/core/components/widgets/widgetcputemps/widgetcputemps.component.html
- src/app/core/components/widgets/widgetcputemps/widgetcputemps.component.ts
- src/app/core/components/widgets/widgetnetinfo/widgetnetinfo.component.ts
Fine tuned widgetnetinfo component to handle null values being returned from middleware for bandwidth stat. Also did a similar workaround for widgetcputemp. Also added an error message that will show up when invalid data is detected. This prevents errors from flooding the browser JS console.
> Error handling needed to deal with bad data being returned from middleware

- src/assets/styles/themes/ix-blue.scss
> fix pseudo checkbox theme

- src/app/components/common/topbar/topbar.component.ts
- Removed the redundant text and simplified the dialog.
- NPM build test: no issues.
> Update text again based on discussion with Warren:

- src/app/pages/sharing/iscsi/initiator/initiator-form/initiator-form.component.ts
- Add link to explain CIDR notation.
- Update to reflect multiple addresses can be listed.
- Update example to reflect multiple addresses.
- NPM build test: no issues.
- Redmine issue [41355](https://redmine.ixsystems.com/issues/41355)
> Update Sharing/iSCSI/Initiators/Add Authorized Network help text:

- src/app/pages/jails/jail-add/jail-add.component.ts
> Fix creating jails with no ip address

- src/app/pages/common/entity/entity-form/validators/range-validation.ts
- src/app/pages/services/components/service-ftp/service-ftp.component.ts
Fix validation on service ftp to prevent things like following 0's in numbers
Ticket: #39962
> Fix 39962 2

- src/app/pages/jails/jail-add/jail-add.component.ts
- src/app/pages/jails/jail-wizard/jail-wizard.component.ts
> Jail.create now returns percentages so handle job with entityJob

- src/app/pages/common/entity/utils.ts
- src/app/pages/jails/jail-add/jail-add.component.ts
- src/app/pages/jails/jail-edit/jail-edit.component.ts
- src/app/pages/jails/jail-wizard/jail-wizard.component.ts
- src/app/pages/jails/storages/storage-form/storage-form.component.ts
> apply handleWSError to the jails section

- src/app/pages/system/CloudCredentials/cloudcredentials-form/cloudcredentials-form.component.ts
Review/expansion of these will likely be necessary before merging
> Begin adding missing Cloud Service Credential tooltips

- src/app/pages/common/entity/entity-table/entity-table.component.ts
fixed missing = in the condition check :D
> fix entity-table where last page was repeat of first page.

- src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
> Add multi-select dropdown for restarting services upon pool unlock

- src/app/pages/services/components/service-smb/service-smb.component.ts
> Use websocket calls for DOS/UNIX charset choices

- src/app/pages/storage/volumes/manager/manager.component.ts
> Fix logic for validating disks added to vdevs for extend pool

- src/app/pages/common/entity/entity-form/services/entity-form.service.ts
> Sort folders on the file explorer alphabetically

- src/app/services/iscsi.service.ts
> Allow SMB (and iSCSI portals) to select IPv6 addresses for binding

- src/assets/styles/themes/ix-blue.scss
> recolor empty rows on data tables

- src/app/pages/common/entity/entity-table/entity-table.component.html
> fix T/F tooltips by changing how titles are set

- src/app/views/sessions/signin/signin.component.css
- src/app/views/sessions/signin/signin.component.html
Ticket: #43035
Modifies the buttons on the log-in dialog
> Log in 43035

- src/app/views/sessions/signin/signin.component.ts
> match sign-in dialog to topbar

- src/app/pages/vm/devices/device-edit/device-edit.component.ts
Also add basic help text for the new Device Order field for each VM Device.
NPM testing: no issues.
> Update VM Disk Device help text:

- src/app/components/common/dialog/downloadkey/downloadkey-dialog.component.html
- src/app/components/common/dialog/downloadkey/downloadkey-dialog.component.scss
- src/app/pages/common/entity/entity-table/entity-table.component.html
- src/app/pages/common/entity/entity-table/entity-table.component.scss
- src/app/pages/storage/volumes/manager/manager.component.html
- src/app/pages/storage/volumes/manager/vdev/vdev.component.html
- src/assets/styles/themes/ix-blue.scss
Ticket: #44009
Add theme colors to ripples and hover effects
> Theme colors for component effects 44009

- src/app/components/common/dialog/downloadkey/downloadkey-dialog.component.html
- src/app/components/common/topbar/topbar.component.ts
- src/app/pages/common/entity/entity-card/entity-card.component.ts
- src/app/pages/common/entity/entity-form/components/form-upload/form-upload.component.ts
- src/app/pages/common/entity/entity-form/components/tooltip/tooltip.component.css
- src/app/pages/common/entity/entity-form/entity-form-embedded.component.html
- src/app/pages/common/entity/entity-table/entity-table.component.ts
- src/app/pages/common/entity/entity-wizard/entity-wizard.component.ts
- src/app/pages/preferences/page/forms/general-preferences-form.component.ts
- src/app/pages/preferences/page/preferences.component.ts
- src/app/pages/storage/snapshots/snapshot-rollback/snapshot-rollback.component.html
- src/app/pages/system/general/config-reset/config-reset.component.html
- src/app/pages/system/update/manualupdate/manualupdate.component.ts
- src/app/pages/system/update/update.component.ts
Clean up a couple field names and tooltips in the Manual Update page.
Local NPM test: no issues.
> Review more UI messages and general whitespace cleanup.

- src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
> Add helptext for new field Restart Services:

- src/app/pages/jails/jail-add/jail-add.component.ts
- src/app/pages/jails/jail-edit/jail-edit.component.ts
- src/app/pages/jails/jail-wizard/jail-wizard.component.ts
> Fix jail ip issues

- src/app/pages/system/CloudCredentials/cloudcredentials-form/cloudcredentials-form.component.ts
> Add helptext to new Google Team Drive ID field.

- src/app/core/components/widgets/widgetnetinfo/widgetnetinfo.component.html
> Changed WidgetNetInfo widget bandwidth units to MBps

- src/app/helptext/cloudsync/cloudsync-form.ts
- src/app/helptext/task-calendar/cloudsync/cloudsync-form.ts
- src/app/helptext/task-calendar/cron/cron-form.ts
- src/app/helptext/task-calendar/initshutdown/initshutdown.ts
- src/app/helptext/task-calendar/replication-form/replication-form.ts
- src/app/helptext/task-calendar/resilver/resilver.ts
- src/app/helptext/task-calendar/resync/resync-form.ts
- src/app/helptext/task-calendar/scrub/scrub-form.ts
- src/app/helptext/task-calendar/smart/smart-form.ts
- src/app/helptext/task-calendar/snapshot/snapshot-form.ts
- src/app/pages/task-calendar/cloudsync/cloudsync-form/cloudsync-form.component.ts
- src/app/pages/task-calendar/cron/cron-form/cron-form.component.ts
- src/app/pages/task-calendar/initshutdown/initshutdown-form/initshutdown-form.component.ts
- src/app/pages/task-calendar/replication/replication-form/replication-form.component.ts
- src/app/pages/task-calendar/resilver/resilver.component.ts
- src/app/pages/task-calendar/rsync/rsync-form/rsync-form.component.ts
- src/app/pages/task-calendar/scrub/scrub-form/scrub-form.component.ts
- src/app/pages/task-calendar/smart/smart-form/smart-form.component.ts
- src/app/pages/task-calendar/snapshot/snapshot-form/snapshot-form.component.ts
Ticket: #45145
Moves tooltips, placeholders and validators from pages under the Tasks heading into the new helptext area
> Feat task tooltips 45145

- src/app/pages/vm/dockervm-wizard/dockervm-wizard.component.ts
when starting docker container.
remove redundant code.
display correct summary item for raw file.
> remove double error notification

- src/app/pages/common/entity/entity-wizard/entity-wizard.component.html
> get rid of duplicate IDs in entity wizard

- src/app/pages/vm/vm-cards/vm-card-edit.component.ts
- src/app/pages/vm/vm-cards/vm-cards.component.css
- src/app/pages/vm/vm-cards/vm-cards.component.html
Ticket: #48523
Limit size of description on VM cards, and limit display size too.
> constrain description size and width of display

- src/app/pages/system/certificates/certificate-add/certificate-add.component.ts
Ticket: #49282
This is the same issue as the fix for the CA page.
> add real-time validation to certificate-add identifier

- src/app/pages/jails/jail-add/jail-add.component.ts
> Updated vnetX_mac tooltips in advanced jail-add.

- src/app/pages/jails/jail-add/jail-add.component.ts
> Updated vnetX_mac tooltips in advanced jail-add (11.2-stable).

- src/app/pages/system/bootenv/bootenv-list/bootenv-list.component.ts
- src/app/services/storage.service.ts
Ticket: #49084
Adds sort by date function that works with dates on BootEnv
> Fix sort by date 49084

- src/app/pages/vm/vm-cards/vm-table.component.html
- src/app/pages/vm/vm-cards/vm-table.component.ts
add listener to get vm status every 5 seconds.
> bring start/stop button to table view

- src/app/pages/common/entity/entity-table/entity-table-add-actions.component.ts
- src/app/pages/common/entity/fab-speed-dial/fab-speed-dial.scss
fixed broken fab button on jail mount point UI
> FIX 47756-2

- src/app/pages/common/entity/entity-table/entity-table-add-actions.component.ts
- src/app/pages/common/entity/fab-speed-dial/fab-speed-dial.scss
fixed broken fab button on jail mount point UI
> FIX 47756-2-stable

- src/app/pages/jails/jail-add/jail-add.component.ts
- src/app/pages/jails/jail-edit/jail-edit.component.ts
- src/app/pages/jails/jail-wizard/jail-wizard.component.ts
> add tool tip to explain the auto configure ipv6 checkbox (11.2-stable)

- src/app/pages/jails/jail-add/jail-add.component.ts
- src/app/pages/jails/jail-edit/jail-edit.component.ts
- src/app/pages/jails/jail-wizard/jail-wizard.component.ts
> Updated tool tip to explain the auto configure ipv6 checkbox.

- src/app/pages/reportsdashboard/components/report/report.component.css
- src/app/pages/reportsdashboard/components/report/report.component.html
- src/assets/styles/themes/ix-blue.scss
Ticket: #41176
Some layout and cosmetic changes for reports
> branch to merge with 11.2

- src/app/pages/services/services-table.component.html
> ids for testing

- src/app/pages/jails/jail-add/jail-add.component.ts
- src/app/pages/jails/jail-edit/jail-edit.component.ts
> Add help text for vnet_default_interface field in Jails Add/Edit:

- src/app/pages/jails/jail-add/jail-add.component.ts
- src/app/pages/jails/jail-edit/jail-edit.component.ts
> Add help text for new vnet_default_interface field in Jails Add/Edit:

- src/app/pages/vm/vm-wizard/vm-wizard.component.ts
(cherry picked from commit 98e0c2341072b5ede5664309dc2061b2e43b367b)
> VM Wizard now allows selection of achi or virtio for disks.

- src/app/pages/common/entity/entity-table/entity-table.component.ts
- src/app/pages/jails/jail-list/jail-list.component.ts
- src/app/services/storage.service.ts
> Fix load jails in order 49783

- src/app/pages/jails/jail-list/jail-list.component.ts
- src/app/services/storage.service.ts
> sorting for stable branch

- src/app/services/storage.service.ts
Ticket: 50431
Branch for merge with 11.2 stable
> second branch

- src/app/pages/guide/guide.component.ts
Ticket: 46641
https://github.com/freenas/webui/pull/1393
is matching PR for master
> guide fix for stable

- src/app/views/others/reboot/reboot.component.ts
- src/app/views/sessions/signin/signin.component.ts
Ticket: #52434
https://github.com/freenas/webui/pull/1390
is matching PR for master
> for stable

- src/app/pages/common/entity/entity-table/entity-table.component.html
- src/app/pages/common/entity/entity-table/entity-table.component.scss
- src/app/pages/common/entity/entity-table/entity-table.component.ts
- src/app/pages/jails/jail-list/jail-list.component.html
- src/app/pages/jails/jail-list/jail-list.component.ts
- src/app/pages/plugins/plugins-installed/plugins-installed.component.html
- src/app/pages/plugins/plugins-installed/plugins-installed.component.ts
> Add warning and link to Legacy UI to jails and installed plugins

- src/app/components/common/lineChart/lineChart.service.ts
- src/app/pages/reportsdashboard/reportsdashboard.component.ts
(cherry picked from commit 4dc172c7b6fe076c7ff0137a677fe4107e7f65da)
> ctl-tpc report label changed to match old UI. SCSI Target Port (tpc)

- src/app/pages/common/entity/entity-form/components/form-textarea/form-textarea.component.html
- src/app/pages/common/entity/entity-form/components/form-textarea/form-textarea.component.ts
- src/app/pages/sharing/nfs/nfs-form/nfs-form.component.ts
(cherry picked from commit 02e05256ae2ef5c77bce93a91c059fad6e514b09)
> Add validation for NFS network/hosts fields.

- src/app/pages/services/components/service-ftp/service-ftp.component.ts
(file doesn't use exec permission so it is hidden)
Ticket: #52425
> Fix FTP permissions so that they work the same as the old UI

- src/app/pages/services/components/service-ups/service-ups.component.ts
removed unused imports and over indentation.
> fix UPS service when freenas is configured as Secondary.

- src/app/pages/sharing/smb/smb-form/smb-form.component.ts
This is the stable version of https://github.com/freenas/webui/pull/1392/commits.
> Sam ticket 453987 stable

- src/app/pages/common/entity/entity-table/entity-table.component.html
- src/app/pages/common/entity/entity-table/entity-table.component.ts
Ticket #53577 and 52351
Adds a slight delay before loading entity table actions to enable accurate info in that column
> Add slight delay in loading entity actions 53577

- src/app/pages/common/entity/entity-table/entity-table.component.html
- src/app/pages/common/entity/entity-table/entity-table.component.ts
Ticket #53577 and 52351
Adds a slight delay before loading entity table actions to enable accurate info in that column
> Add delay for entity actions stable branch 53577

- src/app/components/common/lineChart/lineChart.component.ts
- src/app/components/common/lineChart/lineChart.service.ts
- src/app/pages/common/entity/entity-form/entity-form-embedded.component.html
- src/app/pages/common/entity/entity-form/entity-form-embedded.component.ts
- src/app/pages/reportsdashboard/components/report/report.component.css
- src/app/pages/reportsdashboard/components/report/report.component.html
- src/app/pages/reportsdashboard/reportsdashboard.component.ts
- src/app/pages/reportsdashboard/reportsdashboard.html
- src/app/pages/reportsdashboard/reportsdashboard.module.ts
- src/app/pages/reportsdashboard/reportsdashboard.scss
- src/assets/styles/charts.css
- src/assets/styles/themes/ix-blue.scss
> Fix 28870 stable

- src/app/pages/system/advanced/advanced.component.ts
(making similar filename and download behaviour)
(cherry picked from commit f0fa32f18ee203e46f3ab3df70b647a1d51090d7)
> impement similar behaviour (legacy UI) for save debug operation.

- src/app/pages/account/users/user-form/user-form.component.ts
> Ported text changes to 11.2 

- src/app/pages/system/CloudCredentials/cloudcredentials-form/cloudcredentials-form.component.ts
> 52360: Update System/Cloud Credentials/Add/Account ID field help text:

- src/app/pages/sharing/iscsi/associated-target/associated-target-form/associated-target-form.component.ts
> Port help text change to 11.2-stable branch:

- src/app/pages/system/update/update.component.ts
- src/assets/styles/themes/ix-blue.scss
Ticket: #40940 
For stable branch. Addresses issues that failed testing
> fix train issues in stable

- src/app/pages/vm/dockervm-wizard/dockervm-wizard.component.ts
- src/app/pages/vm/vm-wizard/vm-wizard.component.ts
(cherry picked from commit d7f57b14e79d3fb43000a6b0631f9ae49f596eef)
> do not call filesystem.statfs when gui value undefined or empty

- src/app/pages/vm/vm-cards/vm-cards.component.css
- src/app/pages/vm/vm-cards/vm-cards.component.html
> Use the same working button for cards and slim, this fixes button in slim mode (stable)

- src/app/core/services/preferences.service.ts
- src/app/pages/preferences/page/forms/general-preferences-form.component.ts
- src/app/pages/system/update/update.component.ts
config file download,
vscode suggested linting fixes,
> fix tracebacks in prefrences page,

- src/app/pages/vm/vm-cards/vm-cards.component.css
- src/app/pages/vm/vm-cards/vm-cards.component.html
> Use the same working button for cards and slim, this fixes button in slim mode

- src/app/pages/services/components/service-ups/service-ups.component.ts
> Port changes from PR 1456 to freenas/11.2-stable branch:

- src/app/pages/system/update/update.component.css
- src/app/pages/system/update/update.component.html
- src/assets/styles/themes/ix-blue.scss
Ticket: #40940
Seems like many recent changes got left out in previous commits to stable branch. This commit brings it up to date with master
> update page - catch up stable to master

- src/app/pages/services/components/service-ups/service-ups.component.ts
Add a default value for the Remote Port field.
NPM testing: no issues.
> 44350: Add help text to new Services/UPS/Remote Host and Remote Port fields:

- src/app/pages/services/components/service-ups/service-ups.component.ts
(cherry picked from commit 6db0fda039bd4c7ecde16a9d5151c71616c2bfae)
> make save button work in master setting.

- src/app/pages/sharing/nfs/nfs-form/nfs-form.component.ts
Ported changes from master PR: https://github.com/freenas/webui/commit/7af04ebc9a5ee6c1f2317656179737ad085d3536
> Ported changes from master. 

- src/app/core/components/widgets/widgetnetinfo/widgetnetinfo.component.ts
- src/app/core/services/preferences.service.ts
- src/app/pages/preferences/page/forms/general-preferences-form.component.ts
> Fix 54420 stable

- src/app/pages/common/entity/entity-dialog/dialog-form-configuration.interface.ts
- src/app/pages/common/entity/entity-dialog/entity-dialog.component.html
- src/app/pages/common/entity/entity-dialog/entity-dialog.component.ts
- src/app/pages/preferences/page/forms/general-preferences-form.component.ts
- src/app/pages/system/update/manualupdate/manualupdate.component.ts
- src/app/pages/system/update/update.component.ts
> Port changes from PR 1474 to freenas/11.2-stable branch:

- src/app/core/services/preferences.service.ts
- src/app/pages/system/update/update.component.ts
On initial first time load, If preferences does exist return
after saving Preferences so that UI can retry.
remove redundant Download Sucessful.
(cherry picked from commit 83c31ec507f9c58368bf815677d54ca098e01099)
> fixed firefox UI websocket disconnet.

- src/app/pages/reportsdashboard/reportsdashboard.component.ts
- src/app/pages/reportsdashboard/reportsdashboard.html
Brought back paging to disks tab
> Fix 54459 stable

- src/app/pages/services/services.component.ts
> Adjust netdata url to go to the base page instead of swap

- src/app/pages/account/users/user-form/user-form.component.ts
Passed build test. 
Changes were ported from: https://github.com/freenas/webui/pull/1495
> Ported changes from master.

- src/app/pages/account/users/user-form/user-form.component.ts
characters list and the A before the $ symbol.
Sent these text changes to Jeff E and he approved them. 
Passed build test.
> Clarified the docs by removing the fullstop at the end of the 

- src/app/helptext/jails/jail-wizard.ts
- src/app/helptext/jails/jails-add.ts
- src/app/helptext/jails/jails-edit.ts
> Correct IPv6 autoconfig help text

- src/app/pages/system/update/manualupdate/manualupdate.component.ts
- src/app/pages/system/update/update.component.ts
show Save Config dailoge when user clicks  INSTALL MANUAL UDPATE FILE
> Remove redundant "SAVE CONFIG" button in System/Update/Manual Update

- src/app/pages/system/advanced/advanced.component.ts
(cherry picked from commit 0d67dc8b180ba29cbc37a3a656085eb8770ea47f)
> fixed FF disconnet issue spotted by bonnie in system/Advanced

- src/app/pages/reportsdashboard/components/report/report.component.html
Moved click() event handler in report component html template from icon element to the button element.
> Fixed regression with Firefox. 

- src/app/pages/system/CloudCredentials/cloudcredentials-form/cloudcredentials-form.component.ts
Cloud Credentials.
Passed build test with no issues.
Related to https://redmine.ixsystems.com/issues/56412#change-386844
> Added the tooltips for the new fields added to the OneDrive option in 

- src/app/pages/system/general/general.component.ts
> stable: Remove reference to Weblate

- src/app/pages/system/general/general.component.ts
> Remove reference to Weblate

- src/app/components/common/navigation/navigation.component.ts
- src/app/services/docs.service.ts
- src/app/services/navigation/navigation.service.ts
> Move logic for getting docstring version to navigation component and add webversion to guide url

- src/app/pages/common/entity/entity-form/components/form-select/form-select.component.html
- src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
- src/app/pages/storage/volumes/zvol/zvol-form/zvol-form.component.ts
removed options for zvol volblocksize  < 4K
show recordsize < 4K in dropdown, but do not allow user to select.
(cherry picked from commit 51d77fde38a0475dd3727d73148d3807b0d22994)
> add warning if users are trying to setup dataset recordsize.

- src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.ts
> use inbuilt validator cron-parser for validating cronjob.

- src/app/core/components/widgets/widgetnetinfo/widgetnetinfo.component.html
Ticket: 58434
(cherry picked from commit 3c4a082877cf2d2df354fd3cd2295d806e08d681)
> We using MBps

- src/app/helptext/task-calendar/resync/resync-form.ts
- src/app/pages/directoryservice/activedirectory/activedirectory.component.ts
- src/app/pages/directoryservice/ldap/ldap.component.ts
- src/app/pages/network/laggs/lagg-form/lagg-form.component.ts
- src/app/pages/services/components/service-dc/service-dc.component.ts
- src/app/pages/services/components/service-ftp/service-ftp.component.ts
- src/app/pages/services/components/service-lldp/service-lldp.component.ts
- src/app/pages/services/components/service-s3/service-s3.component.ts
- src/app/pages/services/components/service-smart/service-smart.component.ts
- src/app/pages/services/components/service-smb/service-smb.component.ts
- src/app/pages/services/components/service-snmp/service-snmp.component.ts
- src/app/pages/services/components/service-ssh/service-ssh.component.ts
- src/app/pages/services/components/service-webdav/service-webdav.component.ts
- src/app/pages/sharing/iscsi/extent/extent-form/extent-form.component.ts
- src/app/pages/sharing/iscsi/globalconfiguration/globalconfiguration.component.ts
- src/app/pages/sharing/iscsi/portal/portal-form/portal-form.component.ts
- src/app/pages/sharing/smb/smb-form/smb-form.component.ts
- src/app/pages/storage/disks/disk-bulk-edit/disk-bulk-edit.component.ts
- src/app/pages/storage/disks/disk-form/disk-form.component.ts
- src/app/pages/storage/import-disk/import-disk.component.ts
- src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
- src/app/pages/storage/volumes/manager/manager.component.ts
- src/app/pages/storage/volumes/manager/vdev/vdev.component.ts
- src/app/pages/storage/volumes/zvol/zvol-form/zvol-form.component.ts
- src/app/pages/system/advanced/advanced.component.ts
- src/app/pages/system/ca/ca-add/ca-add.component.ts
- src/app/pages/system/certificates/certificate-add/certificate-add.component.ts
- src/app/pages/system/general/general.component.ts
- src/app/pages/vm/devices/device-add2/device-add.component.ts
- src/app/pages/vm/devices/device-edit/device-edit.component.ts
https://redmine.ixsystems.com/issues/57825
> Put anchors last in generated URLs

- src/app/core/services/preferences.service.ts
- src/app/pages/preferences/page/forms/general-preferences-form.component.ts
- src/app/pages/system/update/update.component.ts
- src/app/services/theme/theme.service.ts
- src/assets/styles/themes/ix-blue.scss
(cherry picked from commit 460ed75c0715ba49a33809dab7a9c069c40e70a0)
> Reverse behavior of "Hide warning config prompt on upgrade" checkbox.

- src/app/pages/account/users/user-form/user-form.component.ts
(cherry picked from commit 3d029ad2713ac4db6cd950d5bd9a7c6cc25db0a0)
> changing UID now sticks

- src/app/pages/account/users/user-form/user-form.component.ts
(cherry picked from commit 26310b66836ed3b99e89d8cc63197d49baa04431)
> Prevent changing an existing user's UID in new UI

- src/app/pages/common/entity/entity-toolbar/components/toolbar-multimenu/toolbar-multimenu.component.ts
- src/app/pages/common/entity/entity-toolbar/entity-toolbar.component.ts
- src/app/pages/reportsdashboard/reportsdashboard.component.ts
- src/app/pages/reportsdashboard/reportsdashboard.html
Replaced tab navigation and reports controls with entity-toolbar
> Entity toolbar reports

- src/app/pages/sharing/nfs/nfs-form/nfs-form.component.ts
> Initialize security for nfs v4 shares

- src/app/pages/common/entity/entity-toolbar/components/toolbar-multimenu/toolbar-multimenu.component.ts
- src/app/pages/common/entity/entity-toolbar/entity-toolbar.component.ts
- src/app/pages/reportsdashboard/reportsdashboard.component.ts
- src/app/pages/reportsdashboard/reportsdashboard.html
> Revert "Entity toolbar reports"

- .angular-cli.json
- src/app/components/common/topbar/topbar.template.html
- src/app/core/components/widgets/widgetcpuhistory/widgetcpuhistory.component.css
- src/app/core/components/widgets/widgetcpuhistory/widgetcpuhistory.component.html
- src/app/core/components/widgets/widgetcpuhistory/widgetcpuhistory.component.ts
- src/app/core/components/widgets/widgetcputemps/widgetcputemps.component.css
- src/app/core/components/widgets/widgetcputemps/widgetcputemps.component.html
- src/app/core/components/widgets/widgetcputemps/widgetcputemps.component.ts
- src/app/core/components/widgets/widgetload/widgetload.component.css
- src/app/core/components/widgets/widgetload/widgetload.component.html
- src/app/core/components/widgets/widgetload/widgetload.component.ts
- src/app/core/components/widgets/widgetmemoryhistory/widgetmemoryhistory.component.css
- src/app/core/components/widgets/widgetmemoryhistory/widgetmemoryhistory.component.html
- src/app/core/components/widgets/widgetmemoryhistory/widgetmemoryhistory.component.ts
- src/app/core/components/widgets/widgetnetinfo/widgetnetinfo.component.html
- src/app/core/components/widgets/widgetnetinfo/widgetnetinfo.component.ts
- src/app/core/components/widgets/widgetpool/widgetpool.component.css
- src/app/core/components/widgets/widgetpool/widgetpool.component.html
- src/app/core/components/widgets/widgetpool/widgetpool.component.ts
- src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.css
- src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.html
- src/app/services/stats.service.ts
- src/app/services/theme/theme.service.ts
- src/assets/styles/material-reduction.css
- src/assets/styles/themes/ix-blue.scss
Pulled in all dashboard widgets and stats service from new-default-theme branch. Put back MBps label change. Also pulled in ix-blue.scss file and made sure the hideWarning variables were renamed to enableWarning.
> Dszidi redo dashboard

- src/app/components/common/layouts/auth-layout/auth-layout.component.ts
- src/app/views/sessions/sessions.module.ts
- src/app/views/sessions/signin/signin.component.css
- src/app/views/sessions/signin/signin.component.html
- src/assets/styles/styles.css
- src/index.html
Restyled login form, preload screen and connection error screens. made sure legacy web interface text stayed the same.
> Login page and preload pages now styled with ix-dark theme's palette

- src/app/pages/common/entity/entity-form/components/form-select/form-select.component.html
- src/app/pages/common/entity/entity-form/components/form-select/form-select.component.scss
- src/app/pages/common/entity/entity-form/components/form-select/form-select.component.ts
- src/app/pages/network/ipmi/ipmi.component.ts
Restyled form-select. Fixed IPMI page channel selector width
> Dszidi redo misc

- src/app/pages/common/entity/entity-form/components/form-select/form-select.component.html
- src/app/pages/common/entity/entity-form/components/form-select/form-select.component.ts
Fixed form-select. Component now properly shows initial form control values
> Form select fix

- src/app/pages/system/update/update.component.ts
(cherry picked from commit ec3499961ddab7774f4fd4093e068e77cad3d3c1)
> suppress warning for 11.2-stable release.

- jenkins-yarn
> - as per discussion drop archive function..

- src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
- src/app/pages/storage/volumes/zvol/zvol-form/zvol-form.component.ts
(cherry picked from commit 1c24911642099fb36e04207ef751ae0de9f3bbf2)
> added Tib size options to zvol/datasets

- src/app/pages/common/entity/entity-job/entity-job.component.ts
- src/app/pages/system/support/support.component.ts
(cherry picked from commit 1087dde57e5bdf906da74654e2644d417627373f)
> disable dialoge box close on clicking outside.

- src/app/pages/storage/import-disk/import-disk.component.ts
Ticket: #53629
(cherry picked from commit 1a37fbece215fbf483a34396c63b3fa004f16f6d)
> Fix import disk percent status

- src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
Ticket: #61107
(cherry picked from commit 28e61bf91c72292d0ea61d5ef22ace9607d56fe9)
> Allow promotion of both datasets and zvols not just datasets

- src/app/pages/common/entity/entity-dialog/entity-dialog.component.html
- src/app/pages/common/entity/entity-form/components/form-input/form-input.component.html
Ticket #56994
Reverses the show/hide password icon and modifies the tooltip
> Reverse show hide pw

- src/app/pages/common/entity/entity-dialog/entity-dialog.component.html
- src/app/pages/common/entity/entity-form/components/form-input/form-input.component.html
> for stable branch

- src/app/pages/directoryservice/activedirectory/activedirectory.component.ts
- src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
> Replace old links to internal User Guide

- src/app/pages/system/bootenv/bootenv-attach/bootenv-attach-form.component.ts
(cherry picked from commit 5e07d393ce771379cc4cee4cc83138d2cd22f4c6)
> display disk size in bootenv-attach-form.

- src/app/pages/system/general/general.component.ts
- src/app/pages/system/update/update.component.ts
Cherry picked the commit from PR1570 to port to 11.2-stable branch.
Could not get local NPM or Yarn builds to function, there is some kind of error with the 'node-sass' module that won't allow either to build. This is not related to my changes.
> Update "Save Config" dialog and add it to the button in System/General

- src/app/pages/system/general/general.component.ts
- src/app/pages/system/update/update.component.ts
> #59706: Update "Save Config" dialog and add it to the button in System/General

- src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.ts
> Fix issue with saved value not being populated in cron permissions component, fix tracebacks and remove console.logs

- src/app/helptext/network/configuration/configuration.ts
- src/app/helptext/network/interfaces/interfaces-form.ts
- src/app/helptext/network/ipmi/ipmi.ts
- src/app/helptext/network/laggs/lagg.ts
- src/app/helptext/network/staticroutes/staticroutes.ts
- src/app/helptext/network/vlans/vlans.ts
- src/app/pages/network/configuration/configuration.component.ts
- src/app/pages/network/interfaces/interfaces-form/interfaces-form.component.ts
- src/app/pages/network/ipmi/ipmi.component.ts
- src/app/pages/network/laggs/lagg-form/lagg-form.component.ts
- src/app/pages/network/laggs/members/members-form/members-form.component.ts
- src/app/pages/network/staticroutes/staticroute-form/staticroute-form.component.ts
- src/app/pages/network/vlans/vlan-form/vlan-form.component.ts
> 45156 for 11.2 stable

- src/app/pages/common/entity/entity-form/components/form-select/form-select.component.html
- src/app/pages/common/entity/entity-form/components/form-select/form-select.component.ts
- src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
- src/app/pages/storage/volumes/zvol/zvol-form/zvol-form.component.ts
* hide low recordsize values
* if default recordsize is low in recordsize, display
* corresponding lowrecord size along with warning.
fix warning message,
> * set correct values for quotas dataset in edit mode.

- src/app/core/components/widgets/widgetpool/widgetpool.component.css
- src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.css
- src/assets/styles/themes/ix-blue.scss
Ticket: #65130
Fixes a few misc layout issues I suspect may have been caused by new version of material components? BTW these don't appear in 11.2. Fixed layouts and colors appear below, broken ones in the ticket - https://redmine.ixsystems.com/issues/65130.
> Fix layout issues

- src/app/helptext/services/components/service-ups.ts
- src/app/pages/services/components/service-ups/service-ups.component.ts
Ticket: #1380 
Remoteport and host were missing from ups service component and helptext
> Add remotehost and port to ups service and helptext

- src/assets/i18n/zh-hant.po
Translating FreeNAS WebUI Chinese Traditional. All complete
> zh-hant.po all translated

- src/app/pages/vm/devices/device-add2/device-add.component.ts
- src/app/pages/vm/devices/device-edit/device-edit.component.html
- src/app/pages/vm/devices/device-edit/device-edit.component.ts
(cherry picked from commit b9a26e844e5f18ecab31f647aaf68a77f894295f)
> post submit, display an middleawre error msg based on user action.

- src/app/pages/storage/snapshots/snapshot-list/snapshot-list.component.ts
Ticket: #65247
(cherry picked from commit aa225d87ae0b0a130874f5eeeb58c6096466adee)
> Snapshot list now uses websocket call and displays creation timestamp

- src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.css
- src/assets/styles/themes/ix-blue.scss
Ticket: # 68155 - Fixes a color issue on cron fields like Cron Jobs > Add > Custom
> 68115 cron field color fix

- src/app/pages/sharing/nfs/nfs-form/nfs-form.component.ts
> Adjust nfs shares to use all users/groups (instead of just local) and switch the fields to comboboxes

- src/app/pages/storage/volumes/manager/manager.component.ts
Ticket: #68716
(cherry picked from commit 064800378424c109320877ef0e0df9348001e9d8)
> Adjust ids to the new ids so that the pool manager filters will work again

- src/app/helptext/services/components/service-smb.ts
- src/app/pages/services/components/service-smb/service-smb.component.ts
> Add checkbox for enable SMB1 support

- src/app/components/common/breadcrumb/breadcrumb.component.ts
- src/app/components/common/lineChart/lineChart.component.ts
- src/app/pages/common/entity/entity-form/components/form-select/form-select.component.html
- src/app/pages/common/entity/entity-form/components/form-select/form-select.component.scss
- src/app/pages/common/entity/entity-form/components/form-select/form-select.component.ts
- src/app/pages/common/entity/entity-toolbar/components/toolbar-button/toolbar-button.component.ts
- src/app/pages/common/entity/entity-toolbar/components/toolbar-menu/toolbar-menu.component.html
- src/app/pages/common/entity/entity-toolbar/components/toolbar-menu/toolbar-menu.component.scss
- src/app/pages/common/entity/entity-toolbar/components/toolbar-menu/toolbar-menu.component.ts
- src/app/pages/common/entity/entity-toolbar/components/toolbar-multimenu/toolbar-multimenu.component.html
- src/app/pages/common/entity/entity-toolbar/components/toolbar-multimenu/toolbar-multimenu.component.scss
- src/app/pages/common/entity/entity-toolbar/components/toolbar-multimenu/toolbar-multimenu.component.ts
- src/app/pages/common/entity/entity-toolbar/entity-toolbar.component.css
- src/app/pages/common/entity/entity-toolbar/entity-toolbar.component.html
- src/app/pages/common/entity/entity-toolbar/entity-toolbar.component.ts
- src/app/pages/common/entity/entity-toolbar/models/control-config.interface.ts
- src/app/pages/common/entity/entity-toolbar/models/control.interface.ts
- src/app/pages/common/entity/entity.module.ts
- src/app/pages/network/ipmi/ipmi.component.css
- src/app/pages/network/ipmi/ipmi.component.ts
- src/app/pages/reportsdashboard/components/report/report.component.html
- src/app/pages/reportsdashboard/components/report/report.component.ts
- src/app/pages/reportsdashboard/reportsdashboard.component.ts
- src/app/pages/reportsdashboard/reportsdashboard.html
- src/app/pages/reportsdashboard/reportsdashboard.scss
- src/assets/styles/themes/ix-blue.scss
Pulls in changes from reportsdashboard, form-select and a minor css fix for ipmi page.
> Reports catchup

- src/app/pages/system/update/update.component.ts
> 63360 for 11.2 stable

- src/app/pages/system/update/update.component.ts
> 63360 make use of new middleware reporting of train descriptions

- src/app/pages/vm/devices/device-edit/device-edit.component.ts
(cherry picked from commit e48068dfcff9cca36b7046fd9c4b960b1e668dfb)
> view Devices when VM is running

- src/app/core/services/api.service.ts
- src/app/pages/vm/devices/device-edit/device-edit.component.ts
- src/app/pages/vm/vm-cards/vm-cards.component.ts
(cherry picked from commit 14763cf17537e5da0d94ac0e755cfe326a9a5780)
> implemented vm clone feature

- src/app/pages/dashboard/dashboard.component.ts
> Use root level dataset available size value instead of raw size for pool widget

- src/app/pages/task-calendar/replication/replication-form/replication-form.component.html
- src/app/pages/task-calendar/replication/replication-form/replication-form.component.ts
Ticket: #67879
(cherry picked from commit 239160f00f7e16a8cdf556c4372222ac7598ab0f)
> Use websocket call instead of rest to get > 20 snapshot task entries and perform minor cleanup to replication form

- src/app/pages/system/bootenv/bootenv-attach/bootenv-attach-form.component.ts
(cherry picked from commit 3a95beb876f00152264af148155a9a9f42fb1af5)
> fix broken boot disk attach form.

- src/app/core/services/preferences.service.ts
- src/app/pages/system/update/manualupdate/manualupdate.component.ts
(cherry picked from commit a62e855440d6451f8f26c6d42156aa8e87cd9a94)
> Add reboot option to Manual Update screen.

- src/app/core/components/widgets/widgetpool/widgetpool.component.css
- src/app/core/components/widgets/widgetpool/widgetpool.component.html
- src/app/core/components/widgets/widgetpool/widgetpool.component.ts
- src/app/pages/dashboard/dashboard.component.ts
Documented in the comments what status strings we can expect for volume.status. The widgetpool component now changes color based on severity (safe,warn,error).
> Sets Pool Widget bg color based on status (stable)

- src/app/pages/storage/volumes/zvol/zvol-form/zvol-form.component.ts
> Preserve original values so that zvol size remains consistent if the user does not try to change it.

- src/app/core/components/widgets/widgetpool/widgetpool.component.css
- src/app/core/components/widgets/widgetpool/widgetpool.component.html
- src/app/core/components/widgets/widgetpool/widgetpool.component.ts
- src/app/pages/dashboard/dashboard.component.ts
Documented in the comments what status strings we can expect for volume.status. The widgetpool component now changes color based on severity (safe,warn,error).
> Sets Pool Widget bg color based on status 

- src/app/pages/jails/jail-edit/jail-edit.component.html
- src/app/pages/jails/jail-edit/jail-edit.component.ts
Fixes jail-edit expansion panels on iOS. Tested on iOS12 iPhone 6S Plus
> jail-edit on iOS Fix (stable)

- src/app/pages/common/entity/entity-table/entity-table.component.ts
Ticket: #69814
Delays getData() till the end of the ngInit queue to make sure col info is complete;
> 69814-master

- src/app/pages/common/entity/entity-table/entity-table.component.ts
Ticket: #69814
Fixes condition where column headers fail to load on page refresh of entity tables
> 69814-for-11.2-stable

- src/app/pages/common/entity/entity-table/entity-table-actions.component.ts
- src/app/pages/vm/vm-cards/vm-cards.component.ts
source: https://stackoverflow.com/questions/37074485/angular2-rxjs-missing-observable-interval-method
> interval behaviour changed for rxjs > v6.2.1,

- src/app/core/services/api.service.ts
- src/app/pages/vm/vm-cards/vm-cards.component.ts
- src/app/pages/vm/vm-form/vm-form.component.ts
(cherry picked from commit b9c3db38f2a80a1e5c14f1c5cd93a7f61d6e8dcf)
> Handle VM errors gracefully.

- src/app/pages/storage/volumes/zvol/zvol-form/zvol-form.component.ts
> Use a split instead of a regex to find the poolname for zvol blocksize

- src/app/pages/system/general/general.component.ts
(cherry picked from commit 3a33932b865461901e94518e40539157207c0f31)
> FireFox specific fix.

- src/app/pages/vm/vm-cards/vm-cards.component.ts
(cherry picked from commit c366ec46ca56e5dfc4f8cf60930eacbd6052240b)
> add missing Com port text.

- src/app/pages/storage/snapshots/snapshot-list/snapshot-list.component.ts
Ticket: #70606
(cherry picked from commit f06ef0f66f87b822cd1cbf19bb8c22d0b463a641)
> Add filter for system dataset to snasphots

- src/app/components/common/breadcrumb/breadcrumb.component.html
- src/app/components/common/dialog/about/about-dialog.component.html
- src/app/views/others/reboot/reboot.component.html
- src/app/views/others/shutdown/shutdown.component.html
- src/app/views/sessions/signin/signin.component.html
Ticket: #72777
(cherry picked from commit 48e94a20de131aeb5e44e7e714bda29eb38f64ca)
> Bump up copyright year to 2019

- src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
> Fix saving dataset with reservations and quotas with decimals

- src/app/helptext/jails/jails-add.ts
- src/app/helptext/jails/jails-edit.ts
(cherry picked from commit 0006d6fb0ce445429e6dba4753641bf5fb743a73)
> Updated vnet_default_interface helptext (11.2-stable).

- src/app/pages/system/update/manualupdate/manualupdate.component.ts
Ticket: #59973
(cherry picked from commit 179cb14dd4e9688a6c992d214bde4dad93535bea)
> Have the reboot dialog actually send you to reboot

- src/app/helptext/storage/volumes/datasets/dataset-form.ts
- src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
> Bring back warning about dataset recordsize > min recommended size

- src/app/components/common/breadcrumb/breadcrumb.component.html
- src/app/components/common/breadcrumb/breadcrumb.component.ts
- src/app/components/common/dialog/about/about-dialog.component.html
- src/app/components/common/dialog/about/about-dialog.component.ts
- src/app/helptext/global-helptext.ts
- src/app/views/others/reboot/reboot.component.html
- src/app/views/others/reboot/reboot.component.ts
- src/app/views/others/shutdown/shutdown.component.html
- src/app/views/others/shutdown/shutdown.component.ts
- src/app/views/sessions/signin/signin.component.html
- src/app/views/sessions/signin/signin.component.ts
Ticket: #73200
Store copyright year in a global helptext file, plus added one var (dockerhost) that the docs team will use
> FIX-73200-master

- src/app/components/common/breadcrumb/breadcrumb.component.html
- src/app/components/common/breadcrumb/breadcrumb.component.ts
- src/app/components/common/dialog/about/about-dialog.component.html
- src/app/components/common/dialog/about/about-dialog.component.ts
- src/app/helptext/global-helptext.ts
- src/app/views/others/reboot/reboot.component.html
- src/app/views/others/reboot/reboot.component.ts
- src/app/views/others/shutdown/shutdown.component.html
- src/app/views/others/shutdown/shutdown.component.ts
- src/app/views/sessions/signin/signin.component.html
- src/app/views/sessions/signin/signin.component.ts
Ticket: #73200
Store copyright year in a global helptext file
Helptext file also contains a var, dockerhost, to be used in 4-5 places
> FIX-73200-stable

- src/app/helptext/vm/docker-vm-wizard/docker-vm-wizard.ts
- src/app/pages/common/entity/entity-table/entity-table.component.ts
- src/app/pages/vm/dockervm-wizard/dockervm-wizard.component.ts
- src/app/pages/vm/vm-cards/vm-cards.component.ts
Search through webui files and replace references to Container VM, Docker VM, Docker Container, etc with "Docker Host".
Small cleanup of related messages.
Whitespace cleanup in edited files too.
> 72755 (11.2-U3): Unify term "Docker Host" (11.2-stable backport)

- src/app/pages/directoryservice/idmap/idmap.component.html
- src/assets/styles/themes/ix-blue.scss
Ticket 75415 for stable
Styles, positions err msg, keeps it from pushing form out of the way.
> FIX-75415-stable

- src/app/pages/storage/volumes/volumes-list/volumes-list.component.css
- src/app/pages/storage/volumes/volumes-list/volumes-list.component.html
Ticket: #61992
Align icons horizontally on pool accordion menu
> Fix 61992 master

- src/app/pages/storage/volumes/volumes-list/volumes-list.component.css
- src/app/pages/storage/volumes/volumes-list/volumes-list.component.html
> Fix 61992 align pool icons STABLE

- src/app/helptext/account/group-list.ts
- src/app/helptext/account/members.ts
- src/app/helptext/account/user-change-pw.ts
- src/app/helptext/account/user-form.ts
- src/app/helptext/account/user-list.ts
- src/app/pages/account/groups/group-list/group-list.component.ts
- src/app/pages/account/groups/members/members.component.ts
- src/app/pages/account/users/change-password/change-password.component.ts
- src/app/pages/account/users/user-form/user-form.component.ts
- src/app/pages/account/users/user-list/user-list.component.ts
> Fix 45123 master

- src/app/helptext/account/group-list.ts
- src/app/helptext/account/members.ts
- src/app/helptext/account/user-change-pw.ts
- src/app/helptext/account/user-form.ts
- src/app/helptext/account/user-list.ts
- src/app/pages/account/groups/group-list/group-list.component.ts
- src/app/pages/account/groups/members/members.component.ts
- src/app/pages/account/users/change-password/change-password.component.ts
- src/app/pages/account/users/user-form/user-form.component.ts
- src/app/pages/account/users/user-list/user-list.component.ts
> Fix 45123 account helptext stable

- src/app/pages/common/entity/entity-table/entity-table.component.html
Ticket: #73351
(cherry picked from commit a2886e419533b99fd3168fb6016976607406d59a)
> Hide footer text if there are no rows

- src/app/helptext/vm/docker-vm-wizard/docker-vm-wizard.ts
- src/app/pages/vm/dockervm-wizard/dockervm-wizard.component.ts
- src/app/pages/vm/vm-cards/vm-cards.component.ts
> Revert "72755 (11.2-U3): Unify term "Docker Host" (11.2-stable backport)"

- src/assets/i18n/zh-hans.po
It is a 20% complete Simplified Chinese translation. A more complete version is on its way.
IT HAS NOT BEEN TESTED ON MY COMPUTER! My FreeBSD keeps throwing errors yesterday and I'm a noob to BSD......
a good place to submit issues directly to me: https://github.com/dingyifei/freenas-webui-zh_cn-translation
lol
> A 20% Simplified Chinese Translation

- src/app/views/others/reboot/reboot.component.html
- src/app/views/others/shutdown/shutdown.component.html
> FIX-73702-stable

- src/app/core/components/corecomponents.module.ts
- src/app/core/components/widgets/widgetpool/widgetpool.component.ts
Ticket: #73371
(cherry picked from commit d8904f4c0eef727282ddc60f087a4e49109d712b)
> Apply storage sort to disks for dashboard widget

- src/app/pages/sharing/smb/smb-form/smb-form.component.ts
> Sort the vfs_objects options

- src/app/pages/vm/vm-cards/vm-cards.component.ts
> Remove redundant add option from vm list (wizard should let user pick what type they want)

- src/app/helptext/account/groups.ts
> Adjust group name regex to allow dashes and periods

- src/app/helptext/sharing/iscsi/iscsi.ts
> update iscsi tooltips

- src/app/pages/common/entity/entity-table/entity-table-actions.component.ts
- src/app/pages/common/entity/entity-table/entity-table.component.ts
- src/app/pages/vm/vm-cards/vm-cards.component.ts
> add key_props info for VM table

- src/app/pages/common/entity/entity-table/entity-table-actions.component.ts
- src/app/pages/common/entity/entity-table/entity-table.component.ts
- src/app/pages/vm/vm-cards/vm-cards.component.ts
> label key_props for vm table

- src/app/pages/vm/vm-wizard/vm-wizard.component.ts
> Correct error message about VM zvols on umounted mount points

- src/assets/styles/reset.css
> Add css styling to make <b> and <i> tags in tooltips work again

- src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
Ticket: #67710
Takes advantage of new middleware feature to enter a passphrase when locking a pool. This is for 11.3 only, I believe?
> 67710 passphrase 2 lock pool

- src/app/helptext/vm/vm-wizard/vm-wizard.ts
This was per [Warrens Comment](https://github.com/freenas/freenas-docs/pull/616#pullrequestreview-195066552).
> Make Hard Disks VM labels more concise (master).

- src/app/pages/task-calendar/replication/replication-form/replication-form.component.ts
Ticket: #65904
(cherry picked from commit c37fc1388685b6ef2f68aaa40ea0830c4b975545)
> Only populate dataset/snapshot task list for replication with unique values

- src/app/helptext/vm/docker-vm-wizard/docker-vm-wizard.ts
- src/app/helptext/vm/vm-wizard/vm-wizard.ts
- src/app/pages/vm/dockervm-wizard/dockervm-wizard.component.ts
- src/app/pages/vm/vm-wizard/vm-wizard.component.ts
(cherry picked from commit 4e682e5412747897dbe2bb0e0d33e16d157e6d9d)
> Allow CDROM step to be skipped in VM wizard.

- src/app/pages/common/entity/entity-table/entity-table.component.ts
Ticket: #70426
Redo calc of table height in light of recent design changes
> Fix-70426-for-11.3

- src/app/pages/common/entity/entity-table/entity-table.component.ts
Ticket: #70426
Fixes table height calculation in cases where the recent UI improvements created more vertical space
> Fix-70426-for-11.2-stable

- src/app/pages/system/support/support.component.ts
(cherry picked from commit e9c6ada60b285d853094c7d84667215afcd00e26)
> Add link to ticket when submitting.

- src/app/pages/storage/volumes/manager/manager.component.ts
Ticket: #69663
(cherry picked from commit 7438efd7b47e7b2c8dfe2c27ef1f9dd2015a9b1a)
> Pool manager dialog button should say "extend pool" when extending and "create pool" when creating.

- src/app/helptext/sharing/iscsi/iscsi.ts
- src/app/pages/sharing/iscsi/associated-target/associated-target-form/associated-target-form.component.ts
11.2 use rest call which doesn't support auto-assign lunid
> FIX 69186 stable

- src/app/core/components/widgets/widgetcputemps/widgetcputemps.component.ts
- src/app/pages/dashboard/dashboard.component.ts
- src/app/services/stats.service.ts
> Dashboard/stats.service fixes from stats-jobs branch.

- src/app/pages/system/update/update.component.css
- src/app/pages/system/update/update.component.html
Ticket 65214
Adds a refresh button to the update page
> 65214-MASTER

- src/app/pages/system/update/update.component.css
- src/app/pages/system/update/update.component.html
Ticket 65214
Adds a refresh button to the update page
> 65214 stable

- src/app/pages/common/entity/entity-form/components/form-upload/form-upload.component.html
Ticket 72313
Style button on pool decrypt page
> 72313-stable

- src/app/pages/common/entity/entity-form/components/form-upload/form-upload.component.html
Ticket 72313
Style button on pool decrypt page
> 72313-master

- src/app/pages/account/users/user-list/user-list.component.ts
- src/app/pages/common/entity/entity-table/entity-table.component.html
- src/app/pages/jails/jail-list/jail-list.component.ts
- src/app/pages/plugins/plugins-available/plugins-available-list.component.ts
- src/app/pages/storage/snapshots/snapshot-list/snapshot-list.component.ts
- src/app/pages/system/ntpservers/ntpserver-list/ntpserver-list.component.ts
- src/assets/styles/themes/ix-blue.scss
Ticket 48295
This is the companion to https://github.com/freenas/webui/pull/1795
Don't know why I didn't submit it earlier. :)
> 48295 stable

- src/app/helptext/services/components/service-tftp.ts
- src/app/pages/services/components/service-tftp/service-tftp.component.ts
> Add tftp_host to tftp service

- src/app/pages/vm/vm-wizard/vm-wizard.component.ts
> Adjust vm wizard name regex to not allow spaces

- src/app/pages/storage/volumes/manager/vdev/vdev.component.html
Ticket: #75046
(cherry picked from commit bea0f12f4f28b297a3eff378dd4847bf2cdf71e4)
> Make vdev checkall boxes have unique ids so they don't confuse each other

- src/app/pages/sharing/webdav/webdav-form/webdav-form.component.ts
Ticket: #75766
(cherry picked from commit a10cd9a273ce3ec0f021c2a8c8abd1563697064c)
> Change user & group ownership should be enabled by default

- src/app/pages/system/general/general.component.ts
> Add rule to restart web service when certificate for UI is changed in system general

- src/assets/styles/themes/ix-blue.scss
> FIX-74298-master

- src/assets/styles/themes/ix-blue.scss
> Fix 74298 hi contrast STABLE

- src/app/components/common/lineChart/lineChart.component.ts
- src/app/components/common/lineChart/lineChart.service.ts
- src/app/pages/reportsdashboard/components/report/report.component.css
- src/app/pages/reportsdashboard/components/report/report.component.html
- src/app/pages/reportsdashboard/reportsdashboard.component.ts
Added CPU temperature charts to reports
> CPU Temperature Reports

- src/app/pages/common/entity/entity-table/entity-table-actions.component.ts
Ticket: #76674
Menus don't show in pool list, which uses entity table actions, but doesn't have filterColumns.
> FIX-76674-MASTER

- src/app/pages/common/entity/entity-table/entity-table-actions.component.ts
- src/assets/styles/themes/ix-blue.scss
Ticket: #76674
Menus don't show in pool list, which uses entity table actions, but doesn't have filterColumns.
The CSS change bumps over the header checkboxes in datatables, needed in 11.2 only
> FIX-76674-stable

- src/app/pages/common/entity/entity-table/entity-table.component.html
- src/app/pages/common/entity/entity-table/entity-table.component.scss
- src/app/pages/common/entity/entity-table/entity-table.component.ts
- src/app/pages/vm/vm-cards/vm-cards.component.ts
- src/app/pages/vm/vm-form/vm-form.component.ts
Ticket 59649
Add checkbox to turn on/off autostart, add slider to start/stop VM
> 59649 master

- src/app/pages/common/entity/entity-table/entity-table.component.html
- src/app/pages/common/entity/entity-table/entity-table.component.scss
- src/app/pages/common/entity/entity-table/entity-table.component.ts
- src/app/pages/vm/vm-cards/vm-cards.component.ts
- src/app/pages/vm/vm-form/vm-form.component.ts
Ticket 59649
Add checkbox to turn on/off autostart, add slider to start/stop VM
> 59649 stable

- src/app/pages/services/components/service-ups/service-ups.component.ts
> Combine hostname and port into a single combobox

- src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
Ticket: #76243
(cherry picked from commit b455069682974acdf128520bd34f928dd6303da0)
> Need to convert 1M to 1024K for middleware

- src/assets/i18n/zh-hans.po
This time it should just work
this is the second attempt xD
> Simplified Chinese 25% translation

- src/app/pages/system/bootenv/bootenv-list/bootenv-list.component.ts
(cherry picked from commit fdb06914bfb29368684e47205ee63b923f60082a)
> allow boot_scrub interval to be modified from GUI.

- src/app/pages/storage/volumes/volumes-list/volumes-list.component.html
Ticket: #72553
(cherry picked from commit 6d32526d30ea665ec96a41bdbdce286fb110f13b)
> Adjust lock icon to reflect the lock state of the pool

- src/app/helptext/vm/devices/device-add-edit.ts
- src/app/pages/vm/devices/device-add2/device-add.component.ts
- src/app/pages/vm/devices/device-edit/device-edit.component.ts
(cherry picked from commit c34821120f8e0c77625148acbbf7de24786a6df8)
> use async/await to fix hiesenbug where VNC option does not show.

- src/app/pages/vm/vm-cards/vm-cards.component.ts
I have some some sort of build error unrelated to this work, so I can't test locally yet.
> 74686: Reword "Container Provider" in the Virtual Machines list.

- src/app/pages/vm/vm-cards/vm-cards.component.ts
Local yarn build testing: no issues.
> 74686: Transform "Container Provider" text in VMs page

- src/app/pages/account/users/user-form/user-form.component.ts
- src/app/pages/common/entity/entity-form/entity-form.component.html
- src/app/pages/common/entity/entity-form/entity-form.component.scss
- src/app/pages/common/entity/entity-form/entity-form.component.ts
- src/app/services/app-loader/app-loader.service.ts
Ticket 71169
Puts a simple progress spinner on user form until group ws call comes back (which consistently takes the longest). The UI seems to display the credentials immediately once the ws call gets a response. The spinner doesn't interfere with using the form.
> 71169 loader user page STABLE

- src/app/pages/account/users/user-form/user-form.component.ts
- src/app/pages/common/entity/entity-form/entity-form.component.html
- src/app/pages/common/entity/entity-form/entity-form.component.scss
- src/app/pages/common/entity/entity-form/entity-form.component.ts
- src/app/services/app-loader/app-loader.service.ts
Ticket 71169
Puts a simple progress spinner on user form until group ws call comes back (which consistently takes the longest). The UI seems to display the credentials immediately once the ws call gets a response. The spinner doesn't interfere with using the form.
> 71169 master

- src/app/pages/system/ca/ca-add/ca-add.component.ts
- src/app/pages/system/certificates/certificate-add/certificate-add.component.ts
> Split on all space types for SAN in certificates and CAs

- src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
> Fix volume free percentage

- src/app/pages/common/entity/entity-form/entity-form.component.scss
Ticket: #52450
Force entity forms to load at full-width of their containing card
> Fix 52450 STABLE

- src/app/pages/common/entity/entity-form/entity-form.component.scss
Ticket: #52450
Force entity forms to load at full-width of their containing card
> FIX-52450-MASTER

- src/app/components/common/navigation/navigation.template.html
- src/assets/styles/fn-styles.css
- src/assets/styles/styles.css
Ticket: #76918
Removes scrollbars from all sidenav (collapsed) dropdowns except System, which is pretty large.
> Fix 76918 stable

- src/assets/styles/fn-styles.css
- src/assets/styles/styles.css
Ticket: #76918
Removes scrollbars from all sidenav (collapsed) dropdowns except System, which is pretty large.
> FIX-76918-MASTER

- src/app/helptext/storage/volumes/manager/manager.ts
Ticket: #77602
(cherry picked from commit 284b37e880974fe41836790718f288c3c89512b6)
> Use the new suggested warning message for extending pools

- src/app/pages/vm/vm-cards/vm-cards.component.ts
> Add VM restart option back

- src/app/helptext/services/components/service-dc.ts
- src/app/pages/services/components/service-dc/service-dc.component.ts
> Pop up warning dialog for DC when AD monitoring is enabled

- src/app/helptext/task-calendar/initshutdown/initshutdown.ts
(cherry-pick from PR 2000)
Sync help text for "Command", "Script", and "When" fields with updated docs.
PEP8 cleanup.
> 69625 (11.2-stable): Update Init/Shutdown Scripts > Add help text:

- src/app/helptext/task-calendar/initshutdown/initshutdown.ts
Sync help text for "Command", "Script", and "When" fields with updated docs.
Minor PEP8 cleanup.
> 69625: Update Init/Shutdown Scripts > Add help text:

- src/app/helptext/system/email.ts
- src/app/pages/system/email/email.component.ts
(cherry picked from commit d3c242d8c326070f379226f348dfe650e76938db)
> Update labels and help text for 'Security' field in system>email (11.2)

- src/assets/styles/themes/ix-blue.scss
Ticket 77709
Fixes color problems on dark themes with disabled checkboxes, dropdowns
> Fix 77709 stable

- src/assets/styles/themes/ix-blue.scss
Ticket 77709
Fixes color problems on dark themes with disabled checkboxes, dropdowns
> Fix 77709 master

- ports/freenas/freenas-webui/Makefile
> Buildtime file needs to go into assets for us to be able to grab it

- src/app/pages/vm/vm-cards/vm-cards.component.ts
> Fix logic for getting serial port for VMs

- src/app/pages/system/general/general.component.ts
> Use new websocket call for getting certificates for system general

- src/app/helptext/account/groups.ts
> Allow underscores in group names similar to how we allow them in user names

- src/app/views/others/reboot/reboot.component.ts
> Add random seed to signin URL before going from reboot to signin page to force browser reload

- src/app/app.component.ts
- src/app/components/common/lineChart/lineChart.component.ts
- src/app/core/classes/ix-abstractobject.ts
- src/app/core/classes/thread.ts
- src/app/core/services/chart-data-utils.service.ts
- src/app/pages/reportsdashboard/components/report/report.component.html
- src/app/pages/reportsdashboard/reportsdashboard.component.ts
- src/assets/scripts/lib/data_utils.js
Added the ability to offload number crunching to threads/workers. Reporting now makes use of this.
Also added bytesToGigabytes conversion to memory and iscsi related reports
> Threads and Conversions

- src/assets/scripts/lib/data_utils.js
Added conversion to swap report
> Fix swap values (master)

- src/assets/scripts/lib/data_utils.js
Added conversion to swap report
> Fix swap values

- src/assets/i18n/fr.po
> Revert "Update fr.po"

- src/app/components/common/lineChart/lineChart.component.ts
- src/app/pages/reportsdashboard/components/report/report.component.html
- src/assets/scripts/lib/data_utils.js
Added analytics properties to linechartData.meta in web worker. Total value no longer shows up in memory charts in reports section
> No more totals on Memory Reports (Stable)
