truenas/webui

src/app/components/common/lineChart/lineChart.component.ts
src/app/pages/reportsdashboard/components/report/report.component.html
src/assets/scripts/lib/data_utils.js

Added analytics properties to linechartData.meta in web worker. Total value no longer shows up in memory charts in reports section

No more totals on Memory Reports

---

src/assets/styles/egret_overrides.css

Ticket: #59688
Removes some animations to get footer console to place itself properly

Fix-59688b for stable:remove some animations

---

src/assets/styles/egret_overrides.css

Ticket: #59688
Removes some animations to get footer console to place itself properly

59688b turn off some animations

---

src/app/core/components/widgets/widgetpool/widgetpool.component.ts
src/app/services/storage.service.ts

Ticket: #73371
(cherry picked from commit b3ddf8a75458a4ac67e72feed4892480a75e27a0)

Add a disk name sort method for just sorting disk names

---

src/app/pages/storage/volumes/volumes-list/volumes-list.component.html
src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts

pool row ids for icons

---

src/app/core/components/widgets/widgetpool/widgetpool.component.ts

Ticket: #73371
(cherry picked from commit 4a5ef65f495f0774c7dd35e1aaa525ba08e02631)

Move sort to a place where it won't get fuddled by race conditions

---

src/app/pages/storage/volumes/volumes-list/volumes-list.component.html
src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts

FIX 81201-master

---

src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts

Cascade needs to be passed in regardless of deletion status

---

src/app/helptext/services/components/service-smb.ts
src/app/pages/services/components/service-smb/service-smb.component.ts

Ticket: #72387
Remove DOS Charset as an option in SMB for

FIX-72387-master

---

src/app/helptext/sharing/smb/smb.ts
src/app/pages/common/entity/entity-form/components/form-input/form-input.component.html
src/app/pages/sharing/smb/smb-form/smb-form.component.ts

Ticket: #59112
Makes a custom validator to prevent 'global' from being used as a SMB share name

FIX-59112-master

---

src/app/pages/storage/volumes/manager/manager.component.html
src/app/pages/storage/volumes/manager/vdev/vdev.component.html

Ticket: #79212
Gives the disk col more space in pool manager

Give the disk col more space in pool manager

---

src/app/pages/storage/volumes/manager/manager.component.html
src/app/pages/storage/volumes/manager/vdev/vdev.component.html

Ticket: #79212
Gives the disk col more space in pool manager

FIX-79212-stable

---

src/app/helptext/account/user-form.ts

https://redmine.ixsystems.com/issues/79149

#79149 - Fixed cosmetic bug and changed bold to italics in User/Edit

---

src/app/pages/services/services-table.component.html
src/assets/styles/themes/ix-blue.scss

Ticket: #79356
Fixes layout problem when dragging datatable columns, adds needed labels to Services table, cleans up datatable CSS a bit.

FIX-79356a_master

---

src/app/pages/system/update/update.component.css
src/app/pages/system/update/update.component.html

Ticket: #78960
Formats a button and sets two scrolls to auto on Update page

Fix 78960 stable

---

src/assets/styles/themes/ix-blue.scss

FIX 83476 stable: Form field color fix

---

src/app/pages/system/bootenv/bootenv-list/bootenv-list.component.html
src/assets/styles/themes/ix-blue.scss

FIX 83476 fix input ripples, cursor color, focused labels

---

src/app/pages/services/services-table.component.html
src/assets/styles/themes/ix-blue.scss

Ticket: #79356
Fixes layout problem when dragging datatable columns, adds needed labels to Services table, cleans up datatable CSS a bit.

FIX-79356-stable

---

src/app/pages/sharing/smb/smb-list/smb-list.component.ts

Fix placement of name and path header labels in smb

---

src/app/helptext/vm/vm-wizard/vm-wizard.ts

(cherry picked from commit e93be5e7f2d93d2702719b6d7af4c48d0decb107)

80004:Updated the 'Bind' helptext in VM wizard(11.2)

---

src/app/pages/task-calendar/snapshot/snapshot-list/snapshot-list.component.ts

Sunday is the 7th day, not the 0th day

---

src/app/pages/common/entity/entity-tree-table/entity-tree-table.component.html

Use iec for filesize pipe on entity-tree-table

---

src/app/pages/system/update/update.component.css
src/app/pages/system/update/update.component.html

Ticket: #78960
Formats a button and sets two scrolls to auto on Update page

Fix 78960 master

---

src/app/pages/system/advanced/advanced.component.ts

Ticket: #76225
Adds progress bar, etc. to System/Advanced/Save Debug

Feat 76225 master

---

src/app/pages/system/certificates/certificate-edit/certificate-edit.component.ts

Ticket: #74892
Changes submit method for Cert Edit to match changes in MW, allows editing of CSR names (identifiers)

Feat 74892 master

---

src/app/pages/vm/dockervm-wizard/dockervm-wizard.component.ts

Use the proper quotes so globalHelptext variables will work in docker wizard

---

src/app/helptext/directoryservice/activedirectory.ts
src/app/pages/directoryservice/activedirectory/activedirectory.component.ts

Ticket: #37518
Adds required and length validation to AD netbiosname_a field, fixes helptext labeling

Fix 37518 stable

---

src/app/helptext/system/ca.ts
src/app/helptext/system/certificates.ts
src/app/pages/common/entity/entity-form/entity-form.component.ts
src/app/pages/system/ca/ca-add/ca-add.component.ts
src/app/pages/system/certificates/certificate-add/certificate-add.component.ts

Tickets 59085, 72347, and 73783
For CA Add and Certificate Add:
- Adds Organizational Unit field 
- Adds option to choose between RSA and EC key types
- Makes the form disable/enable fields based on key type selection
- Hides fields not needed for chosen cert or CA type

Feat 59085 master

---

src/app/pages/common/entity/entity-form/entity-form.component.html
src/app/pages/common/entity/entity-form/entity-form.component.ts
src/app/pages/dashboard/dashboard.component.ts
src/app/pages/dashboard/dashboard.html
src/app/pages/reportsdashboard/reportsdashboard.component.ts
src/app/pages/reportsdashboard/reportsdashboard.html
src/app/pages/storage/volumes/manager/manager.component.html
src/app/pages/storage/volumes/manager/manager.component.ts
src/app/pages/system/alert/alert.component.html
src/app/pages/system/alert/alert.component.ts
src/app/pages/system/update/update.component.html
src/app/pages/system/update/update.component.ts

Ticket: #78600
Adds extra space at the bottom of a few pages. when the footer console is on, to prevent console from covering content.

Fix 78600 master

---

src/app/pages/common/entity/entity-form/entity-form.component.html
src/app/pages/common/entity/entity-form/entity-form.component.ts
src/app/pages/dashboard/dashboard.component.ts
src/app/pages/dashboard/dashboard.html
src/app/pages/reportsdashboard/reportsdashboard.component.ts
src/app/pages/reportsdashboard/reportsdashboard.html
src/app/pages/storage/volumes/manager/manager.component.html
src/app/pages/storage/volumes/manager/manager.component.ts
src/app/pages/system/alert/alert.component.html
src/app/pages/system/alert/alert.component.ts
src/app/pages/system/update/update.component.html
src/app/pages/system/update/update.component.ts

Ticket: #78600
Adds extra space at the bottom of a few pages. when the footer console is on, to prevent console from covering content.

Fix 78600 stable

---

src/app/pages/common/entity/entity-table/entity-table.component.ts

Ticket: #78582
Makes adjustable the VM table and tables with headers that resize, all to avoid double scroll ba

Fix 78582 stable

---

src/app/pages/common/entity/entity-table/entity-table.component.ts

Ticket: #78582
Makes adjustable the VM table and tables with headers that resize, all to avoid double scroll bars

Fix 78582 master

---

src/app/pages/storage/disks/disk-list/disk-list.component.ts

Override existing logic for getting unused disks to make wipe work again

---

src/app/pages/common/error-dialog/error-dialog.component.html
src/app/pages/common/error-dialog/error-dialog.component.ts

Ticket: #83387
Prevents error dialog from expanding a text area behind it

Fix 83387 master

---

src/app/helptext/account/user-form.ts

https://redmine.ixsystems.com/issues/79149

For #79149,  Changed bold to italics and fixed space error in user-form 

---

src/app/views/sessions/signin/signin.component.html

Ticket: #76576
Explicitly turns off auto complete, caps and correct for sign in userna

FIX-76576-stable

---

src/app/views/sessions/signin/signin.component.html

Ticket: #76576
Explicitly turns off auto complete, caps and correct for sign in username

FIX-76576-master

---

src/app/core/components/widgets/widgetpool/widgetpool.component.html
src/app/core/components/widgets/widgetpool/widgetpool.component.ts

Ticket: #83883
(cherry picked from commit 77d76e721e28c2c19042410af13db147c347055b)

Use name of disk instead of index to search for disk details

---

package.json
src/app/app.component.html
src/app/app.component.ts
src/app/app.module.ts
src/app/helptext/task-calendar/cloudsync/cloudsync-form.ts
src/app/pages/task-calendar/cloudsync/cloudsync-form/cloudsync-form.component.ts
src/app/pages/task-calendar/cloudsync/cloudsync-list/cloudsync-list.component.ts
src/app/services/engineerMode.service.ts
src/app/services/index.ts
src/app/services/ws.service.ts

fixed ticket: #36633 and #35107

Fix 36633 35107

---

src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.css
src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.html
src/assets/styles/themes/ix-blue.scss

Ticket: #79995
Fixes color issues on date picker that were especially bad on the hi-contrast theme. Also improves the calendar's display on Firefox

Fix 79995 calendar stable

---

src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.css
src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.html
src/assets/styles/themes/ix-blue.scss

Ticket: #79995
Fixes color issues on date picker that were especially bad on the hi-contrast theme. Also improves the calendar's display on Firefox.

Fix 79995 master

---

src/app/pages/sharing/smb/smb-form/smb-form.component.ts

Ticket: #84676
Change defaults for VFS Objects on Sharing >SMB> Edit
Periodic Snapshot task was previously changed to checkbox

FEAT-84676-master

---

src/app/helptext/account/user-form.ts

(cherry picked from commit cebda8c9880901deeb4e3658b3dbfe56ba0e74f7)

Fixed user>add 'username' field help text to not contradict.

---

src/app/helptext/directoryservice/activedirectory.ts
src/app/pages/directoryservice/activedirectory/activedirectory.component.ts

Ticket: #84684
Removes fields from Directory Services > AD

FEAT-84684-master

---

src/app/helptext/services/components/service-smb.ts
src/app/pages/services/components/service-smb/service-smb.component.ts

Ticket: #84668
Removes eight fields from Services > SMB > Edit, adds a Admin Group select box, plus adjustments to helptext

FEAT-84668-master

---

src/app/helptext/services/components/service-ups.ts

https://redmine.ixsystems.com/issues/83668
Remove parenthetical aside and update link.

Fix 83668 - incorrect field name

---

src/app/pages/storage/volumes/volumes-list/volumes-list.component.css
src/app/pages/storage/volumes/volumes-list/volumes-list.component.html

NAS-101353
Assigns a color from the theme to each state for pool icons

Fix-NAS-101353-stable

---

src/app/pages/storage/volumes/volumes-list/volumes-list.component.css
src/app/pages/storage/volumes/volumes-list/volumes-list.component.html

NAS-101353
Assigns a color from the theme to each state for pool icons

FIX-NAS-101353-master

---

src/app/pages/storage/volumes/volumes-list/volumes-list.component.html
src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts

Adds dynamic space on pool list page if footer console is open (failed test previously)

NAS-101039 add space for console on pool list

---

src/app/pages/common/entity/entity-form/entity-form.component.ts
src/app/pages/system/ca/ca-add/ca-add.component.ts
src/app/pages/system/certificates/certificate-add/certificate-add.component.ts

Ticket: #80508
Hides fields not in use on CA and Cert add pages

FIX-80508-stable

---

src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts

NAS-100864

---

src/assets/styles/themes/ix-blue.scss

Fix for arrow color on focused select fields

NAS-101199 Fix master

---

src/assets/styles/themes/ix-blue.scss

Fix for arrow color on focused select fields

NAS-101199 fix stable

---

src/app/helptext/system/support.ts
src/app/pages/system/support/support.component.ts

Fix broken link, fix formatting of username field

Fix support text and setting on helptext username

---

src/app/helptext/system/cloudcredentials.ts

(cherry picked from commit f2aca6c5b6c388ca3aada07d223a90f4e87870ec)

Update endpoint URL to be less confusing.

---

src/app/pages/common/entity/entity-form/components/form-select/form-select.component.html

NAS-101477 Add space to multi-selectors throughout the app

---

src/app/pages/common/entity/entity-form/components/form-select/form-select.component.html

Add spaces on multi option select fields

---

src/app/helptext/system/email.ts

(cherry picked from commit e18cf3d05404943d078438ae6f7bc3e104ce217f)

NAS-100955 escaped less than and greater than signs so they appeared.

---

src/assets/i18n/zh-hant.po

Fixed: extra quotation marks leading to "Starting job... "The following words cannot be converted for display

Fixed: enter an extra quotation mark

---

src/app/pages/common/select-dialog/select-dialog.component.html
src/assets/styles/themes/ix-blue.scss

NAS-101489
Updates styling on the Select Dialog, plus fixes color issue on the placeholder (on the select dialog AND in IPMI component dropdown)

NAS-101489-  fixes for Select dialog

---

src/app/pages/common/select-dialog/select-dialog.component.html
src/assets/styles/themes/ix-blue.scss

NAS-101489
Updates styling on the Select Dialog, plus fixes color issue on the placeholder (on the select dialog AND in IPMI component dropdown)

NAS-101489 css issues on the select dialog

---

src/app/pages/storage/volumes/volumes-list/volumes-list.component.html

Redo icon colors for pools

---

src/app/helptext/services/components/service-smb.ts
src/app/pages/services/components/service-smb/service-smb.component.ts

NAS-101078  for stable branch
Adds a pull-down on SMB form that populates with group list

NAS-101078

---

src/app/helptext/system/email.ts

(cherry picked from commit 550d3526ed3b22c85b9cf9a0a2e391db209679fd)

NAS-101092 Sync legacy email SMTP password helptext with newUI helptext.

---

src/app/helptext/system/update.ts
src/app/pages/common/entity/entity-job/entity-job.component.ts
src/app/pages/system/update/manualupdate/manualupdate.component.ts

NAS-101368 Add emitter to entity job to account for failed connection

---

src/app/pages/network/ipmi/ipmi.component.ts

Update ipmi component to be able to configure failover node ipmi

---

src/app/helptext/system/advanced.ts
src/app/pages/system/advanced/advanced.component.ts

Remove "Periodic Notification User"

---

src/app/helptext/system/general.ts
src/app/pages/system/general/general.component.ts

Update system general to use websocket call with new fields and ability to listen on multiple ip addresses

---

src/app/pages/storage/import-disk/import-disk.component.ts

NAS-100609
Uses new ws call to detect file type when importing a disk

NAS-100609 import disk method

---

src/app/pages/common/entity/entity-table/entity-table.component.ts
src/app/pages/storage/snapshots/snapshot-list/snapshot-list.component.ts

NAS-101303
(cherry picked from commit 9b4855f8a5917b7e3e633915c8ad995d992f7e66)

Fix snapshot query

---

src/app/pages/common/entity/entity-form/entity-form.component.ts
src/app/pages/storage/VMware-snapshot/VMware-snapshot/VMware-snapshot-form.component.ts

NAS-101296
Uses a new API method to match datastores with datasets. When a datastore is chosen that is mapped to a dataset, that dataset is automatically selected. If the user tries to save a non-matching set, a dialog is raised.

Nas 101296 master

---

src/app/core/services/api.service.ts
src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
src/app/pages/vm/vm-cards/vm-cards.component.ts

NAS-100967
Allows user to enter a name for a cloned VM

Feat 77107 master

---

src/app/helptext/system/failover.ts
src/app/pages/system/failover/failover.component.ts
src/app/views/others/failover/failover.component.css
src/app/views/others/failover/failover.component.html
src/app/views/others/failover/failover.component.ts
src/app/views/others/others.module.ts
src/app/views/others/others.routing.ts

Add initiate failover button to system > failover

---

src/app/components/common/topbar/topbar.component.ts
src/app/helptext/network/interfaces/interfaces-list.ts
src/app/pages/network/interfaces/interfaces-list/interfaces-list.component.html
src/app/pages/network/interfaces/interfaces-list/interfaces-list.component.ts

Tweak pending/checkin prompting to make checkin show up immediately and use proper helptext

---

src/app/helptext/services/components/service-smb.ts
src/app/pages/directoryservice/idmap/idmap.component.ts
src/app/pages/services/components/service-smb/service-smb.component.ts

NAS-101528
Updates APIs in smb and idmap components

Nas 101528 master

---

src/app/helptext/storage/volumes/volume-key.ts
src/app/pages/storage/volumes/volumechangekey-form/volumechangekey-form.component.ts

NAS-101759
Adds checkbox to remove pool passphrase

NAS-101759 Add checkbox to remove pw from pool

---

src/app/pages/storage/volumes/volumes-list/volumes-list.component.css

NAS-101657
Raises pool icons up to clear hover highlight

NAS-101657 fix layout issue for icons on pools list

---

src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.html

NAS-100583
You mean like this?

NAS-100583 cores to threads

---

src/app/core/components/widgets/widgetpool/widgetpool.component.html
src/app/core/components/widgets/widgetpool/widgetpool.component.ts

NAS-101479
Gives the pool widget the same five possible colors (depending on state) as the icons on Pools/List

NAS-101479 match pool widget color to pool icons

---

src/app/core/components/widgets/widgetcpuhistory/widgetcpuhistory.component.ts
src/app/core/components/widgets/widgetcputemps/widgetcputemps.component.ts
src/app/core/components/widgets/widgetload/widgetload.component.ts
src/app/core/components/widgets/widgetmemoryhistory/widgetmemoryhistory.component.ts
src/assets/styles/egret_overrides.css

In some cases the content was overflowing and the extra height fixes this.
NAS-100568

NAS-100568 - Increased the height of the cards to allow for more information. 

---

src/app/app.module.ts
src/app/components/common/dialog/directory-services-monitor/directory-services-monitor.component.css
src/app/components/common/dialog/directory-services-monitor/directory-services-monitor.component.html
src/app/components/common/dialog/directory-services-monitor/directory-services-monitor.component.ts
src/app/components/common/dialog/task-manager/task-manager.component.ts
src/app/components/common/topbar/topbar.component.ts
src/app/components/common/topbar/topbar.template.html

NAS-100177 - Adds a button and dialog to the topbar that, on opening, checks and displays status of dir services. Colored icons for the five states.

Nas 100177 master

---

src/app/pages/storage/snapshots/snapshot-list/snapshot-list.component.ts

Fix snapshot actions

---

src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.html
src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.ts
src/app/pages/system/support/support.component.ts

Small fixes for Kris' press tour demo.

Demo fixes 1

---

src/app/pages/common/entity/entity-form/components/form-textarea-button/form-textarea-button.component.html
src/app/pages/task-calendar/replication/replication-form/replication-form.component.ts

@lola27 please check if it works properly, I don't have an ability to build it.

Properly fetch remote host key when managing replication task

---

src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts

Fix data loading for atime property

---

src/app/pages/services/components/service-ups/service-ups.component.ts
src/app/pages/storage/volumes/datasets/dataset-acl/dataset-acl.component.ts
src/assets/styles/fn-styles.css
src/assets/styles/themes/ix-blue.scss

NAS-101693
Creates and styles a combobox for UPS services page

Nas 101693 master

---

src/app/helptext/services/components/service-dynamic-dns.ts
src/app/pages/services/components/service-dynamicdns/service-dynamicdns.component.ts

NAS-101736 - Adds 'Custom Provider' option to Dynamic DNS service

NAS-101736 Add custom provider to menu and add CP fields to DynDNS

---

src/app/components/common/topbar/topbar.component.ts
src/app/pages/common/confirm-dialog/confirm-dialog.component.html
src/app/pages/common/confirm-dialog/confirm-dialog.component.ts
src/app/services/dialog.service.ts

Add automatic EULA popup if EULA has not been accepted

---

src/app/pages/storage/volumes/manager/manager.component.html
src/app/pages/storage/volumes/manager/manager.component.ts

NAS-101890
(cherry picked from commit 8166a0a38d896f07497be02a454d7c9ed2491046)

Add reset layout button functionality to volume manager

---

src/app/components/common/topbar/topbar.component.css
src/app/components/common/topbar/topbar.template.html
src/assets/styles/themes/ix-blue.scss

NAS-101953
Fixes 1) text color not changing on hover, making High Contrast unreadable and 2) first regular menu item being forcibly focused by Angular.

Nas 101953 master

---

src/app/pages/common/entity/entity-table/entity-table.component.ts
src/app/pages/plugins/available-plugins/available-plugins.component.css
src/app/pages/plugins/available-plugins/available-plugins.component.html
src/app/pages/plugins/plugin/plugin.component.css
src/app/pages/plugins/plugin/plugin.component.html
src/app/pages/plugins/plugin/plugin.component.ts
src/assets/styles/themes/ix-blue.scss

NAS-101958
Make tables expand when expandable rows expand, plus fix some color issues on the new plugins page, add unique ids to new buttons

Nas 101958 master

---

src/app/pages/services/components/service-ssh/service-ssh.component.ts

NAS-100553 Uses new ws call to populate bind interfaces on SSH setup page

NAS-100553 use ssh.bindiface_choices

---

src/app/components/common/topbar/topbar.component.css
src/app/components/common/topbar/topbar.component.ts
src/app/components/common/topbar/topbar.template.html

NAS-100173
Adds system hostname to topbar

NAS-100173 add hostname to topbar

---

src/app/components/common/notifications/notifications.component.html
src/app/services/notifications.service.ts

NAS-10193
Uses the FN/TN system timezone for the timestamp in notifications (does require a browser refresh after changing time zones)

Nas 101931 master

---

src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.css
src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.html
src/app/pages/task-calendar/snapshot/snapshot-form/snapshot-form.component.ts

NAS-101924
Allow minutes to be edited on periodic snapshot tasks, fits the schedule list to the mat-card; also, I took the liberty of removing seconds from the time display since it is always 00 and never adjustable(?)

NAS-101924 allow minutes to be updated on periodic snapshot tasks

---

src/app/pages/system/advanced/advanced.component.ts

Populate serial port options properly

---

src/app/helptext/system/general.ts
src/app/pages/common/entity/entity-dialog/entity-dialog.component.html
src/app/pages/system/general/general.component.ts

Fix broken config save and add pool_keys boolean to it

---

src/app/pages/storage/volumes/manager/manager.component.ts

Add spinner to pool manager while loading disk data

---

src/app/helptext/services/components/service-rsync.ts
src/app/pages/common/entity/entity-table/entity-table.component.ts
src/app/pages/services/components/service-rsync/rsyncconfiguration/rsyncconfiguration-list/rsyncconfiguration-list.component.ts
src/app/pages/services/components/service-rsync/rsyncconfiguration/rsyncmodule/rsyncconfiguration-form.component.ts

NAS-101170
Adapt the rsync config form to use the ws call with new values for mode
Adapt the entity filter function to recognize arrays of strings/bools/numbers (since rsync form stores some data in arrays.

Nas 101170 master

---

src/app/helptext/task-calendar/resync/resync-form.ts
src/app/pages/task-calendar/rsync/rsync-form/rsync-form.component.ts
src/app/pages/task-calendar/rsync/rsync-list/rsync-list.component.ts

Convert rsync task to use websocket call and use proper description field

---

src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.css
src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.html
src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.ts
src/assets/styles/themes/ix-blue.scss

NAS-101538
Disallows spaces in hours field on form scheduler, adds an instruction
The minutes and days fields SEEM to work okay, so I applied this only to hours

NAS-101538 disallow spaces in hours field of form scheduler

---

src/app/pages/system/ssh-connections/ssh-connections-form/ssh-connections-form.component.ts

I think this will correctly display all errors related to SSH connection submissions.

NAS-102096 -- pass dialog to EntityUtils.handleWSError

---

src/app/core/services/api.service.ts
src/app/pages/jails/jail-add/jail-add.component.ts
src/app/pages/jails/jail-edit/jail-edit.component.ts
src/app/pages/jails/jail-wizard/jail-wizard.component.ts
src/app/pages/plugins/plugin-add/plugin-add.component.ts
src/app/pages/plugins/plugin-advanced-add/plugin-advanced-add.component.ts
src/app/pages/vm/vm-wizard/vm-wizard.component.ts

I couldnt find any routes.* calls

NAS-100545 -- interfaces -> interface

---

src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
src/app/services/storage.service.ts

data from pool.unlock_services_restart_choices

NAS-102123 -- populating pool unlock service list with MW data

---

src/app/helptext/directoryservice/ldap.ts
src/app/pages/directoryservice/ldap/ldap.component.ts

NAS-102112
Adds a checkbox under Advanced Options of Dir Services?LDAP to disable LDAP user/group cache, taking advantage of a new Middleware feature

Nas 102112

---

src/app/pages/plugins/available-plugins/available-plugins.component.html
src/app/pages/plugins/available-plugins/available-plugins.component.ts

time or for truenas under engineer mode

NAS-102114 

---

src/app/pages/storage/volumes/manager/manager.component.css
src/app/pages/storage/volumes/volumes-list/volumes-list.component.css
src/assets/styles/themes/ix-blue.scss

NAS-101934 left justify pool list, fix color issues for disabled buttons on pool manager

NAS-101934 left justify pool list

---

src/app/core/services/preferences.service.ts
src/app/pages/common/entity/entity-table/entity-table.component.html
src/app/pages/common/entity/entity-table/entity-table.component.scss
src/app/pages/common/entity/entity-table/entity-table.component.ts
src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts

NAS-100466
Allows user-selected columns (on entity tables) to persist. Preferred cols are stored in user preferences. The most recent view is always stored. User can revert to the default view.

NAS 100466

---

src/app/core/components/corecomponents.module.ts
src/app/core/components/widgets/widgetmemory/widgetmemory.component.css
src/app/core/components/widgets/widgetmemory/widgetmemory.component.html
src/app/core/components/widgets/widgetmemory/widgetmemory.component.ts
src/app/pages/dashboard/dashboard.component.ts
src/app/pages/dashboard/dashboard.html

New memory widget powered by middleware real time events

Memory widget

---

src/app/pages/network/interfaces/interfaces-form/interfaces-form.component.ts

Sure I could have rolled this in with that other interfaces ticket I'm working on, but I needed the win :)

NAS-102195 hide type field on edit for interfaces

---

src/app/pages/common/entity/entity-form/components/form-checkbox/form-checkbox.component.scss
src/assets/styles/themes/ix-blue.scss

This PR attempts to fix this. Please check it in the build.

Fix form checkboxes margins

---

src/app/helptext/services/components/service-afp.ts
src/app/helptext/services/components/service-snmp.ts
src/app/pages/services/components/service-rsync/rsyncconfiguration/rsyncconfiguration-list/rsyncconfiguration-list.component.ts
src/assets/i18n/ru.po

Plus fix couple typos in original phrases.

Add some more random Russian translations.

---

src/app/pages/directoryservice/idmap/idmap.component.ts

NAS-102236 - makes sure that Active Dir and LDAP use custom methods for IMDAP

NAS-102236 use correct ldap method for idmaps

---

src/app/helptext/system/support.ts
src/app/pages/system/support/support.component.ts

NAS-101948 adds 'update license' method to TN support page

Nas 101948 master

---

src/app/components/common/layouts/admin-layout/admin-layout.component.css
src/app/components/common/layouts/admin-layout/admin-layout.component.ts
src/app/components/common/layouts/admin-layout/admin-layout.template.html
src/app/components/common/topbar/topbar.component.css
src/app/components/common/topbar/topbar.component.ts
src/app/components/common/topbar/topbar.template.html
src/app/pages/preferences/page/forms/general-preferences-form.component.ts

Remove theme switcher from topbar
Move hostname from topbar to sidenav
For theme switcher in General Preferences, make theme change on click
Add snackbar for when changes are submitted

Nas 102277

---

src/app/pages/services/components/service-smb/service-smb.component.ts
src/app/pages/services/components/service-tftp/service-tftp.component.ts
src/app/pages/sharing/nfs/nfs-form/nfs-form.component.ts
src/app/pages/storage/volumes/datasets/dataset-permissions/dataset-permissions.component.ts
src/app/pages/task-calendar/cron/cron-form/cron-form.component.ts
src/app/pages/task-calendar/rsync/rsync-form/rsync-form.component.ts
src/app/services/user.service.ts

Replace getAllUsers and getAllGroups with DS cache queries

---

src/app/helptext/network/interfaces/interfaces-list.ts
src/app/pages/network/interfaces/interfaces-list/interfaces-list.component.ts

Pop up a message to tell the user they cannot edit/delete an interface while HA is enabled

---

src/app/helptext/task-calendar/snapshot/snapshot-form.ts

Switch to a FreeNAS/TrueNAS agnostic phrasing.

Fix brand replacement error in Periodic Snapshots helptext

---

src/app/pages/account/users/user-list/user-list.component.ts
src/app/pages/common/entity/entity-table/entity-table.component.ts

NAS-102329 - Hides cols, adds expandy rows on user table; also, some adjustments to entity table to mkae 'hide columns' work on all tables if no preferences are set.

NAS-102329

---

src/app/helptext/vm/vm-wizard/vm-wizard.ts
src/app/pages/common/entity/entity-form/components/form-upload/form-upload.component.ts
src/app/pages/vm/vm-wizard/vm-wizard.component.ts
src/app/services/ws.service.ts

* Using pool.filesystem_choices "FILESYSTEM" for the zvol portion of the VM wizard
* Removes first step of VM wizard (and shifts all the indexes)
* Happy to remove the websocket debug flag. Find myself logging payloads pretty frequently though.

NAS-102200 / NAS-102313

---

src/app/pages/services/services-table.component.ts

NAS-102336 - Makes services table scale correctly when footer console is open/closed

NAS-102336

---

src/app/helptext/system/email.ts
src/app/pages/common/entity/entity-form/entity-form.component.ts
src/app/pages/system/email/email.component.ts

* using ws calls
* password field no longer required
* this does not strip the password field on load. users are able to configure other fields and save as usual without stripping the password field. let me know if that's not desirable behavior.

NAS-102218 -- email page updates

---

src/app/helptext/task-calendar/replication/replication.ts

NAS-102332

---

src/app/pages/jails/jail-list/components/jail-details.component.ts

https://jira.ixsystems.com/browse/NAS-102247

NAS-102247 -- jail start/restart/stop -> EntityJob

---

src/app/components/common/dialog/downloadkey/downloadkey-dialog.component.ts
src/app/pages/services/services.component.ts

As this involves security, this probably should be merged in 11.2 branch too

Do not use http:// URLs when working via https://

---

src/app/helptext/storage/volumes/volume-key.ts
src/app/pages/storage/volumes/volumeaddkey-form/volumeaddkey-form.component.ts
src/app/pages/storage/volumes/volumechangekey-form/volumechangekey-form.component.ts
src/app/pages/storage/volumes/volumecreatekey-form/volumecreatekey-form.component.ts
src/app/pages/storage/volumes/volumerekey-form/volumerekey-form.component.ts
src/assets/styles/themes/ix-blue.scss

Provides warnings when changing keys/passphrases on pools, and also forces the download-key dialog to open so the user has to download a copy of the new key (requested by docs)

Nas 102362

---

src/app/helptext/account/user-form.ts

Code Freeze has happened, but this is for 11.2-U4. It can wait until next release version if need be.
(cherry picked from commit f26a17d18f424831a9cc94fc1ec05a4e52fa5361)

NAS-100799 Updated the home directory helptext.

---

tests/selenium/test_026_sys_email.py
tests/selenium/test_088_theme.py

Also fix email tests outgoingMail xpath

QE NAS-102497 Update UI theme tests with the latest changes for changing the theme

---

src/app/helptext/directoryservice/activedirectory.ts
src/app/helptext/global-helptext.ts
src/app/helptext/network/configuration/configuration.ts
src/app/helptext/sharing/iscsi/iscsi.ts
src/app/helptext/system/failover.ts
src/app/helptext/topbar.ts
src/app/pages/common/confirm-dialog/confirm-dialog.component.css
src/app/views/sessions/signin/signin.component.ts

Replaces 'storage controllers' with TrueNAS controllers (controllers is capitalized in labels, not capitalized in sentences or otherwise. Thought about making a global var, but not sure if that breaks translation.

Nas 100172

---

src/app/core/components/widgets/widgetpool/widgetpool.component.css
src/app/core/components/widgets/widgetpool/widgetpool.component.html
src/app/core/components/widgets/widgetpool/widgetpool.component.ts
src/app/pages/dashboard/dashboard.component.ts
src/app/pages/dashboard/dashboard.html

Added 'Available Space' info to widget. Also settings icon now links to the pools status page

Pool Widget link to status page

---

src/app/pages/common/entity/entity-form/components/form-explorer/form-explorer.component.html
src/app/pages/common/entity/entity-form/components/form-explorer/form-explorer.component.ts
src/app/pages/common/entity/entity-form/models/field-config.interface.ts
src/app/pages/task-calendar/replication/replication-form/replication-form.component.ts

In form explorer, allows checkboxes to be set to select only the item clicked, not all the children (for a parent) and not the parent if all children are selected

Nas 102374

---

src/app/components/common/layouts/admin-layout/admin-layout.component.ts
src/app/components/common/layouts/admin-layout/admin-layout.template.html
src/app/pages/preferences/page/forms/customtheme/customtheme.component.ts

fixes various display issues when creating custom themes and switching between theme previews

Nas 102491

---

src/app/pages/storage/disks/disk-list/disk-list.component.ts

Adds columns/details to Storage > Disks table:
* Disk type
* Rotation rate
* Enclosure
Hides some additional columns by default.

NAS-102136

---

src/app/pages/network/interfaces/interfaces-list/interfaces-list.component.ts

Simple helptext reference error

NAS-102612 

---

src/app/helptext/system/reporting.ts
src/app/pages/system/reporting/reporting.component.ts

Hides the rrd destroy checkbox except when needed, enforces unchecked state on load, adds validation (numbers only) to two fields

NAS-102298 hide checkbox unless needed

---

src/app/services/dialog.service.ts

Closes open dialogs when websocket connection is dropped.

NAS-102639 

---

src/app/pages/network/interfaces/interfaces-list/interfaces-list.component.ts

NAS-102195 Add type to interfaces table

---

src/app/pages/preferences/page/forms/general-preferences-form.component.ts
src/assets/styles/themes/ix-blue.scss

various layout issues on prefs page, especially locking tooltip icon in place

NAS-102676 put tooltip in place, fix other style issues

---

src/app/pages/system/support/support.component.ts

Should take care of NAS-102641 too. Keeps the entity job dialog from getting stuck at the wrong spot, also clears the form on success response

Nas 102644

---

src/app/components/common/topbar/topbar.component.ts
src/app/components/common/topbar/topbar.template.html
src/app/helptext/global-helptext.ts
src/app/helptext/system/advanced.ts
src/app/helptext/topbar.ts
src/app/pages/system/advanced/advanced.component.ts
src/app/views/sessions/signin/signin.component.html
src/app/views/sessions/signin/signin.component.ts

Hides Ui pointers to legacy UI in Freenas, and shows them in TrueNAS only if user selects this option in System Advanced. This PR contains some dialogs and a tooltip and needs docs input.

Nas 102627

---

src/app/helptext/system/cloudcredentials.ts

 NAS-101652: Synchronize field help text with docs 

---

src/app/helptext/task-calendar/cloudsync/cloudsync-form.ts
src/app/pages/common/entity/entity-form/components/dynamic-field/dynamic-field.css
src/app/pages/common/entity/entity-form/components/form-paragraph/form-paragraph.component.html
src/app/pages/common/entity/entity-form/components/form-paragraph/form-paragraph.component.ts
src/app/pages/common/entity/entity-form/models/field-config.interface.ts
src/app/pages/task-calendar/cloudsync/cloudsync-form/cloudsync-form.component.ts
src/app/pages/task-calendar/cloudsync/cloudsync-list/cloudsync-list.component.ts

* changes cloudsync defaults to PULL/COPY
* adds helptext paragraphs below transfer mode dropdown
* when user interacts with Direction dropdown, change transfer mode to COPY
* adds Transfer Mode column to cloudsync list (hidden by default)

NAS-102257

---

src/app/pages/common/entity/entity-form/components/tooltip/tooltip.component.css
src/app/pages/common/entity/entity-form/components/tooltip/tooltip.component.html
src/app/pages/common/entity/entity-form/components/tooltip/tooltip.component.ts
src/app/pages/common/entity/entity.module.ts

Makes tooltips draggable; also, clicking on the text will lock it in its visible state, and clicking the icon will still toggle visibility

NAS 102847

---

src/app/pages/system/support/support.component.ts

Fixes fields on support page for TN - Additional hardware, features, and customer

NAS-102787

---

src/app/helptext/vm/vm-wizard/vm-wizard.ts
src/app/pages/vm/vm-cards/vm-cards.component.ts
src/app/pages/vm/vm-wizard/vm-wizard.component.ts

Adds description to VM column choices
Also, I took the liberty of adding a description field to the wizard too, if that is good.

NAS-100369

---

src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
src/app/pages/system/update/update.component.html
src/app/pages/system/update/update.component.ts

* Adds ID and name props to all action buttons in volume-list.component
* Quick update to changelog parsing so that newlines work and the response is formatted in a readable way.

NAS-102736

---

src/app/pages/common/entity/entity-form/components/tooltip/tooltip.component.css
src/app/pages/common/entity/entity-form/components/tooltip/tooltip.component.html
src/app/pages/common/entity/entity-form/components/tooltip/tooltip.component.ts

Makes tooltips work on touch screen, and gives user a convenient way to toggle tooltip once it has been dragged to a new location.

NAS-102853 Click icon to toggle tooltip

---

src/app/pages/storage/volumes/datasets/dataset-acl/dataset-acl.component.ts
src/app/services/user.service.ts

* Uses `user/group.get_user/group_obj` call when possible in ACL manager

Nas 102744

---

src/app/helptext/directoryservice/activedirectory.ts
src/app/pages/directoryservice/activedirectory/activedirectory.component.ts

Takes care of NAS-102792 and 102797. Populates Kerberos principal field with new ws call, adds Computer Account OU field, removes null values before submitting data

NAS 102792

---

src/app/helptext/directoryservice/ldap.ts

NAS-100091: Update LDAP Hostname field helptext.

---

src/app/helptext/sharing/iscsi/iscsi.ts

iSCSI field help text. See https://github.com/freenas/freenas-docs/pull/1409

NAS-100481: Synchronize ui help text and docs

---

src/app/core/components/widgets/widgetpool/widgetpool.component.css
src/app/core/components/widgets/widgetpool/widgetpool.component.html
src/app/core/components/widgets/widgetpool/widgetpool.component.ts
src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.css

Handle case when pool is locked or encrypted

Nas 102677

---

src/app/helptext/storage/disks/disk-form.ts

Sync with docs PR https://github.com/freenas/freenas-docs/pull/1411

NAS-100710: Update Disk temp monitoring fields help text

---

src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts

Refactors pool detach code to 'steer around' checks for attachments and running processes if pool is already locked.

NAS-102794

---

src/app/helptext/directoryservice/ldap.ts

With regard to [Warren's comment](https://github.com/freenas/freenas-docs/pull/1359#discussion_r314470081).

Uppercase "Disable LDAP User/Group Cache"

---

src/app/helptext/sharing/iscsi/iscsi.ts

https://github.com/freenas/freenas-docs/pull/1409/files

NAS-100481: sync iscsi field help text with docs fields.

---

src/app/pages/task-calendar/snapshot/snapshot-form/snapshot-form.component.ts

Makes Period SS Tasks recursive by default

NAS-102086 

---

src/app/helptext/storage/volumes/volume-key.ts

- Review all encryption operations and the recovery key download dialog and clean up text
- local build testing with yarn: no issues

NAS-102558: Review UI pool encryption text

---

src/app/helptext/storage/volumes/zvol-form.ts
src/app/pages/common/entity/entity-form/validators/forbidden-values-validation.ts
src/app/pages/common/entity/entity-table/entity-table.component.ts
src/app/pages/storage/volumes/zvol/zvol-form/zvol-form.component.ts

Validate names as they are typed, compare them against an array of names already used on the same node of the tree.

Nas 102896

---

src/app/helptext/services/components/service-netdata.ts

https://github.com/freenas/freenas-docs/pull/1410/files

NAS-100516: Sync netdata field descriptions with docs.

---

src/app/helptext/sharing/smb/smb.ts

Related doc ticket: https://github.com/freenas/freenas-docs/pull/1376

NAS-102104 sync export recycle bin helptext with userguide descrip

---

src/app/pages/vm/vm-wizard/vm-wizard.component.ts

Thanks to Tim Moore for catching this. The new API call to get available IP addresses should be in the wizard too.

NAS-101339 Add new ws call to VM wizard per Tim Moore's review

---

src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts

in dataset creation form, default values for smb share type

NAS-102739 

---

src/app/pages/common/entity/entity-form/components/form-checkbox/form-checkbox.component.html
src/app/pages/common/entity/entity-form/components/form-colorpicker/form-colorpicker.component.html
src/app/pages/common/entity/entity-form/components/form-combobox/form-combobox.component.html
src/app/pages/common/entity/entity-form/components/form-datepicker/form-datepicker.component.html
src/app/pages/common/entity/entity-form/components/form-explorer/form-explorer.component.html
src/app/pages/common/entity/entity-form/components/form-input/form-input.component.html
src/app/pages/common/entity/entity-form/components/form-ipwithnetmask/form-ipwithnetmask.component.html
src/app/pages/common/entity/entity-form/components/form-paragraph/form-paragraph.component.html
src/app/pages/common/entity/entity-form/components/form-permissions/form-permissions.component.html
src/app/pages/common/entity/entity-form/components/form-radio/form-radio.component.html
src/app/pages/common/entity/entity-form/components/form-readfile/form-readfile.component.html
src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.html
src/app/pages/common/entity/entity-form/components/form-select/form-select.component.html
src/app/pages/common/entity/entity-form/components/form-textarea-button/form-textarea-button.component.html
src/app/pages/common/entity/entity-form/components/form-textarea/form-textarea.component.html
src/app/pages/common/entity/entity-form/components/form-upload/form-upload.component.html
src/app/pages/common/entity/entity-form/components/tooltip/tooltip.component.css
src/app/pages/common/entity/entity-form/components/tooltip/tooltip.component.html
src/app/pages/common/entity/entity-form/components/tooltip/tooltip.component.ts
src/app/pages/shell/shell.component.html
src/assets/styles/themes/ix-blue.scss

Adds styling to help text. Also adds header text.

Tooltip styles

---

src/app/services/jail.service.ts

Add boolean to show remote jail releases as well as local ones

---

src/app/core/services/preferences.service.ts
src/app/pages/preferences/page/forms/general-preferences-form.component.ts
src/app/services/theme/theme.service.ts
src/assets/styles/themes/ix-blue.scss

Removed option to hide help text icons

Removed option to hide help text in User Preferences.

---

src/app/helptext/system/cloudcredentials.ts
src/app/pages/system/CloudCredentials/cloudcredentials-form/cloudcredentials-form.component.ts

Remove no longer existing Amazon cloud drive fields, set S3 to new default

---

src/app/pages/common/entity/entity-table/entity-table.component.html
src/app/pages/common/entity/entity-table/entity-table.component.ts
src/app/pages/jails/jail-list/jail-list.component.html
src/app/pages/jails/jail-list/jail-list.component.ts

Remove legacy warning from jails page and entity table

---

src/app/helptext/task-calendar/snapshot/snapshot-form.ts
src/app/pages/task-calendar/snapshot/snapshot-form/snapshot-form.component.ts

Show but disable missing dataset in snapshot task if dataset does not exist

---

src/app/core/components/corecomponents.module.ts
src/app/core/components/widgets/widget/widget.component.ts
src/app/core/components/widgets/widgetcontroller/widgetcontroller.component.css
src/app/core/components/widgets/widgetcontroller/widgetcontroller.component.html
src/app/core/components/widgets/widgetcontroller/widgetcontroller.component.spec.ts
src/app/core/components/widgets/widgetcontroller/widgetcontroller.component.ts
src/app/core/components/widgets/widgetcpu/widgetcpu.component.css
src/app/core/components/widgets/widgetcpu/widgetcpu.component.html
src/app/core/components/widgets/widgetcpu/widgetcpu.component.ts
src/app/core/components/widgets/widgetmemory/widgetmemory.component.css
src/app/core/components/widgets/widgetmemory/widgetmemory.component.html
src/app/core/components/widgets/widgetmemory/widgetmemory.component.ts
src/app/core/components/widgets/widgetnic/widgetnic.component.css
src/app/core/components/widgets/widgetnic/widgetnic.component.html
src/app/core/components/widgets/widgetnic/widgetnic.component.ts
src/app/core/components/widgets/widgetpool/widgetpool.component.css
src/app/core/components/widgets/widgetpool/widgetpool.component.html
src/app/core/components/widgets/widgetpool/widgetpool.component.ts
src/app/core/components/widgets/widgetsysinfo/simple-failover-btn.component.ts
src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.css
src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.html
src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.ts
src/app/pages/dashboard/dashboard.component.ts
src/app/pages/dashboard/dashboard.html
src/app/pages/dashboard/dashboard.scss
src/assets/styles/egret_overrides.css

Scale down all the dashboard things for mobile :)

Mobile dashboard

---

src/app/pages/jails/jail-list/jail-list.component.ts

Add error handling for successfully failed jail start tasks

---

src/app/pages/storage/volumes/datasets/dataset-permissions/dataset-permissions.component.ts

The ticket mentions documenting how we handle this, but after speaking with Andrew, this new behavior in this ticket seems like what the user would expect

NAS-103014 strip out user and group on submit if unchanged

---

src/app/helptext/storage/volumes/datasets/dataset-acl.ts
src/app/pages/common/entity/entity-form/components/form-list/form-list.component.html
src/app/pages/common/entity/entity-form/components/form-list/form-list.component.ts
src/app/pages/common/entity/entity-form/models/field-config.interface.ts
src/app/pages/storage/volumes/datasets/dataset-acl/dataset-acl.component.ts
src/assets/styles/themes/ix-blue.scss

Delete button on all ACL items, Add button re-positioned

NAS-103013

---

src/app/app.component.ts
src/app/components/common/layouts/admin-layout/admin-layout.component.ts
src/app/components/common/navigation/navigation.component.ts
src/app/components/common/topbar/topbar.component.ts
src/app/core/classes/viewcontroller.ts
src/app/core/components/viewcontroller/viewcontroller.component.ts
src/app/core/services/api.service.ts
src/app/core/services/base.service.ts
src/app/core/services/core.service.ts
src/app/core/services/coreservices.module.ts
src/app/core/services/data.service.ts
src/app/core/services/system-profile.service.ts
src/app/pages/dashboard/dashboard.component.ts
src/app/pages/system/update/manualupdate/manualupdate.component.ts
src/app/services/ws.service.ts

Use a new service to cache data from 'system.info' api call.
Avoid the 'Too many concurrent calls' errors from middleware on initial page load.

NAS-103040

---

src/app/helptext/global-helptext.ts
src/app/helptext/vm/vm-wizard/vm-wizard.ts
src/app/pages/task-calendar/replication/replication-form/replication-form.component.ts
src/app/pages/vm/vm-wizard/vm-wizard.component.ts
src/app/services/storage.service.ts

In VM wizard, change Memory field type to text.

NAS-101423

---

src/app/pages/system/general/general.component.ts

Store the ui certificate id as a string so it can be compared properly later when saving

---

src/app/pages/storage/snapshots/snapshot-list/components/snapshot-details.component.ts

(also fix snapshot actions which seem to be missing)
NAS-102697

Convert datetime to use UI time instead of GMT for snapshots

---

src/app/components/common/navigation/navigation.component.ts

Fix system.info gathering logic so the call works properly on FreeNAS and TrueNAS

---

src/app/pages/services/components/service-ssh/service-ssh.component.ts

Fix ssh interface options to give the raw interface name as value

---

src/app/pages/account/users/user-list/user-list.component.ts

Since this ticket was created, we have modified many tables to use expanding panels and selectable columns, reducing many layout problems. This PR addresses some size issues that remain in the user table.

NAS-102214 Set widths for user table

---

src/app/pages/network/interfaces/interfaces-form/interfaces-form.component.ts

Fix nic choices for Lagg, Vlan and Bridge to work properly with named interfaces

---

src/app/core/classes/system-profiler.ts
src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.css
src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.html
src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.ts
src/app/pages/system/viewenclosure/view-enclosure.component.html
src/app/pages/system/viewenclosure/view-enclosure.component.ts

Enclosure UI now includes spare, logs and caches in the drive trays.
Enclosure UI also no longer assumes that the first enclosure is the controller.

NAS-103065

---

src/app/helptext/system/support.ts
src/app/pages/system/support/tn-support/tn-support.component.ts
src/app/pages/system/support/tn-sys-info/tn-sys-info.component.ts

Refreshes page via a dialog when a TN license is accepted; also removes the old License Update button!

Nas 103111

---

src/app/core/components/viewchart/viewchart.component.ts
src/app/core/services/api.service.ts
src/app/pages/vm/vm-cards/vm-cards.component.ts

Overcommit dialog now only shows when middleware returns ENOMEM error

NAS-102700

---

src/app/components/common/layouts/admin-layout/admin-layout.component.ts
src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.html
src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.ts

Enclosure UI chassis now updates scale on window resize instead of on media query breakpoints.
(cherry picked from commit be438c0a2bdcbcb1675f8b94cc2125f7b99a6690)

Enclosure fix layout on window resize

---

src/app/pages/vm/devices/device-add2/device-add.component.html
src/app/pages/vm/devices/device-add2/device-add.component.ts
src/app/pages/vm/devices/device-edit/device-edit.component.html
src/app/pages/vm/devices/device-edit/device-edit.component.ts

Adjust VM device add/edit to use WSError handler

---

src/app/pages/jails/jail-list/jail-list.component.ts

Update jail start/stop/restart actions to be handled as jobs

---

src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts

Fix error handling for lock

---

src/app/pages/directoryservice/ldap/ldap.component.ts

Use certificates instead of CAs for LDAP

---

src/app/core/services/preferences.service.ts
src/app/pages/preferences/page/forms/general-preferences-form.component.ts
src/app/pages/system/update/update.component.ts

Removes 'disable config dialog' from preferences, cleans up lots of unneeded code, especially in upgrade component

NAS-103152

---

src/app/helptext/directoryservice/idmap.ts
src/app/pages/directoryservice/idmap/idmap.component.ts

Removes range validation from UI, allows error messages from MW to display, edits idmap code to match reworked API

NAS-103012

---

src/app/pages/common/error-dialog/error-dialog.component.ts

Addresses an apparent race condition by delaying the setting of textarea height

Nas 103148

---

src/app/pages/reportsdashboard/reportsdashboard.component.ts
src/app/pages/reportsdashboard/reportsdashboard.html

Get a master list of available disks via disk.query so reports shows all disks.

NAS-103163

---

src/app/helptext/system/update.ts
src/app/pages/system/update/manualupdate/manualupdate.component.ts
src/app/pages/system/update/update.component.ts

Fixes a few things to make manual update on HA work like regular update

Nas 103184

---

src/app/pages/system/CloudCredentials/cloudcredentials-form/cloudcredentials-form.component.ts

Use new excerpt from mw for error msg on dialog

Nas 103117

---

src/app/pages/account/users/user-list/user-list.component.ts
src/app/pages/common/entity/entity-table/entity-table.component.ts

Drops maxWidth from first and last displayed cols in User table.
If first and/or last cols have maxWidth set, there is a display glitch (see pic)
This is applied only to user table, b/c this is the only table with maxWidths set

Nas 103190

---

src/app/helptext/task-calendar/scrub/scrub-form.ts

- Yarn testing: all markup for Threshold days and Schedule the Scrub Task converted.

NAS-102931: Convert formatting strings to html

---

src/app/helptext/system/cloudcredentials.ts

NAS-103089: Add help text to new "Region" field

---

src/app/helptext/network/interfaces/interfaces-form.ts

NAS-102623: Synchronize IP and VIP Address field help text with docs

---

src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.html
src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.ts

Fixes calendar navigation in preview section of cron ui.

NAS-103217

---

src/app/helptext/task-calendar/resync/resync-form.ts

This address [dru's comment](https://jira.ixsystems.com/browse/NAS-102955?focusedCommentId=99026&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-99026).

NAS-102955 update 'path' helptext in rsync task form.

---

src/app/helptext/storage/snapshots/snapshots.ts

Clean up a couple line length issues.
Yarn build test: no issues.

NAS-103033: Update help text for 'Name' and 'Naming Schema' fields

---

src/app/helptext/sharing/iscsi/iscsi-wizard.ts
src/app/helptext/sharing/iscsi/iscsi.ts

NAS-103031: Remove HAST references from iSCSI help text

---

src/app/pages/sharing/iscsi/portal/portal-form/portal-form.component.ts

Show --- instead of None for null value on discovery auth group

---

src/app/pages/vm/vm-wizard/vm-wizard.component.ts
src/app/services/storage.service.ts

Adds human-readability to the label for Available memory on VM wizard

Nas 101423a

---

src/app/helptext/directoryservice/activedirectory.ts
src/app/helptext/directoryservice/ldap.ts
src/app/pages/directoryservice/activedirectory/activedirectory.component.ts
src/app/pages/directoryservice/ldap/ldap.component.ts

Remove some AD fields, add cert validation checkbox to AD, LDAP
Definitely needs a check of helptext

NAS-103188

---

src/app/pages/common/entity/entity-form/components/form-explorer/form-explorer.component.html
src/app/pages/common/entity/entity-form/components/form-explorer/form-explorer.component.scss
src/app/pages/common/entity/entity-form/components/form-radio/form-radio.component.html
src/assets/styles/themes/ix-blue.scss

Move tooltips in file explorer form and radio options to allow text copying; plus some css adjustments. Addresses failed test

NAS-102881 

---

src/app/helptext/urls.ts
src/app/services/docs.service.ts

Add docs keyword for truenas/freenas and adjust guide to point to correct location

---

src/app/helptext/vm/vm-wizard/vm-wizard.ts

"Zvol Location" not "Zvol Dataset Location"

---

src/app/pages/system/general/general.component.ts

Convert System General language selection into a combobox with alphabetically sorted options

---

src/app/components/common/dialog/task-manager/task-manager.component.ts
src/app/helptext/global-helptext.ts
src/app/pages/common/entity/entity-job/entity-job.component.html
src/app/pages/common/entity/entity-job/entity-job.component.ts

Tell the user to refer to the task manager when closing a job.

---

src/app/helptext/task-calendar/replication/replication.ts

- Update line break spacing
- Unify the text between UI and guide EDIT: https://github.com/freenas/freenas-docs/pull/1543

NAS-101272: synchronize Advanced Replication Fields with docs

---

src/app/pages/system/bootenv/bootenv-list/bootenv-list.component.ts

Use raw values and do conversion rather than using already parsed values for boot pool sizes

---

src/app/helptext/task-calendar/replication/replication-wizard.ts
src/app/pages/task-calendar/replication/replication-wizard/replication-wizard.component.ts

- Add draft help text to new replication wizard
- Yarn build testing: no issues

NAS-102085: Replication Wizard help text

---

src/app/helptext/system/update.ts
src/app/pages/common/entity/entity-job/entity-job.component.html
src/app/pages/common/entity/entity-job/entity-job.component.ts
src/app/pages/system/update/manualupdate/manualupdate.component.ts

NAS-103240
Adds an indeterminate progress indicator and a 'Uploading file...' message to the first dialog in manual update process

NAS-103240

---

src/app/pages/system/dataset/dataset.component.ts

NAS-101403

---

src/app/core/components/corecomponents.module.ts
src/app/core/components/pipes/convert.pipe.ts
src/app/core/components/widgets/widgetnic/widgetnic.component.css
src/app/core/components/widgets/widgetnic/widgetnic.component.html
src/app/pages/dashboard/dashboard.component.ts

Remove subscription to TC stats. Updated widgetnic to use MW realtime events instead

NAS-103248

---

src/app/pages/jails/jail-add/jail-add.component.ts
src/app/pages/jails/jail-edit/jail-edit.component.ts

NAT forwards should handle the case of a jail port but no host port

---

src/app/pages/common/entity/entity-table/entity-table.component.html
src/app/pages/common/entity/entity-table/entity-table.component.scss
src/app/pages/common/entity/entity-table/entity-table.component.ts

Restyles buttons, adds color acc to state. Also makes 'PENDING' not a button since it doesn't point to a function in replication component. Not sure how this fits with other components that will use this feature

Nas 103235

---

src/app/helptext/network/interfaces/interfaces-form.ts

From releng review.
Yarn build test with TrueNAS HA: no issues.

NAS-103068: Update TrueNAS HA VHID help text:

---

src/app/helptext/system/general.ts
src/app/pages/common/entity/entity-form/components/form-radio/form-radio.component.html
src/app/pages/system/general/general.component.ts
src/assets/styles/themes/ix-blue.scss

Makes language selector sortable by name or code

Language list sort

---

src/app/pages/common/info-dialog/info-dialog.component.html
src/app/pages/common/info-dialog/info-dialog.component.scss

Adds scrollbars when needed to info dialog info-panel without interfering with the info dialog textarea or with other dialogs

NAS-103230

---

src/app/pages/system/support/fn-support/fn-support.component.ts

NAS-103320

---

src/app/helptext/system/general.ts
src/app/pages/common/entity/entity-form/components/tooltip/tooltip.component.ts
src/app/pages/storage/volumes/manager/manager.component.css
src/app/pages/storage/volumes/manager/manager.component.html
src/app/pages/storage/volumes/manager/vdev/vdev.component.css

Aligns and styles pool manager, fixes a bug for tooltips in dialogs

Nas 103304

---

src/app/pages/storage/volumes/manager/manager.component.ts

Speed up the time of loading disks by cutting unnecessary parameter

---

src/app/pages/preferences/page/forms/general-preferences-form.component.ts

Do not load the form until we get our response from preferences service

---

src/app/pages/storage/volumes/manager/manager.component.ts

Fix bug with extending duplicated vdevs

---

src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.ts

Don't make call to failover.licensed unless the box is TrueNAS

---

src/app/pages/storage/volumes/datasets/dataset-acl/dataset-acl.component.ts

Add parent in after ACL is copied for better performance

---

src/app/pages/system/update/update.component.ts

Use "selected" instead of "current" to get the currently selected train

---

src/app/pages/storage/volumes/manager/vdev/vdev.component.html

use ngModelChange instead of change to make estimated capacity work properly

---

src/app/pages/account/users/user-form/user-form.component.ts

NAS-103362
NAS-103361
NAS-103364

fix issues related to users form

---

src/app/helptext/system/general.ts

Adds a warning re keys that aren't backed up from System >
General Save Config

Nas 103386

---

src/app/pages/system/update/update.component.html
src/app/pages/system/update/update.component.ts

Fix issues with updater train selection

---

src/app/helptext/vm/vm-wizard/vm-wizard.ts
src/app/pages/common/entity/entity-table/entity-table.component.ts
src/app/pages/storage/volumes/manager/manager.component.css
src/app/pages/vm/vm-cards/vm-summary.component.css
src/app/pages/vm/vm-cards/vm-summary.component.html
src/app/pages/vm/vm-cards/vm-summary.component.ts
src/app/pages/vm/vm-wizard/vm-wizard.component.ts

Replaces chart on VM page with simple memory calculation and warning, removes memory calc from wizard; also aligns a button on the pool manager

Nas 103375

---

src/app/pages/storage/volumes/manager/manager.component.ts

Add paratext to vdev duplication dialog to explain what it will do

---

src/app/pages/account/users/user-list/user-list.component.ts

Fix expansion panel icon and id for delete action

---

src/app/pages/system/update/update.component.ts

Fix issues with trains not populating

---

src/app/helptext/system/failover.ts
src/app/pages/system/failover/failover.component.ts

Add scary warning for disabling master

---

src/app/helptext/global-helptext.ts
src/app/helptext/vm/vm-wizard/vm-wizard.ts
src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
src/app/pages/storage/volumes/zvol/zvol-form/zvol-form.component.ts
src/app/pages/task-calendar/replication/replication-form/replication-form.component.ts
src/app/pages/vm/vm-cards/vm-cards.component.ts
src/app/pages/vm/vm-form/vm-form.component.ts
src/app/pages/vm/vm-wizard/vm-wizard.component.ts

Adds human readability to VM edit form and table, adds the VM tooltips to the form that are already in use on the wizard, adds real time err check for mem size

Nas 103404

---

src/app/pages/plugins/available-plugins/available-plugins.component.html
src/app/pages/plugins/available-plugins/available-plugins.component.ts
src/app/pages/plugins/plugins.component.ts

Remove revision column, append revision to version with underscore

---

src/app/pages/system/update/update.component.ts

NAS-103048 11-2 fix Turn off spinner on general update error

---

src/app/services/docs.service.ts

Adjust guide link to maybe go to the right place?

---

src/app/pages/network/interfaces/interfaces-form/interfaces-form.component.ts

Properly populate interface edit fields

---

src/app/pages/common/entity/entity-table/entity-table.component.html

Add inline spinners for VM states of deleting and restarting

NAS-103427 

---

src/app/helptext/vm/vm-wizard/vm-wizard.ts
src/app/pages/vm/vm-wizard/vm-wizard.component.ts

Fixes some step errors, etc, to get error messages working on VM wizard

Nas 103431

---

src/app/pages/common/entity/entity-form/components/form-radio/form-radio.component.html

Adds config name to radio button ids. Should make ids unique in a form, which also fixes a problem on pool wizard panel 2

NAS-103444 

---

src/app/pages/services/components/service-smb/service-smb.component.ts
src/app/services/index.ts
src/app/services/services.service.ts

Adjust smb service to use new call for getting bind ips

---

src/app/pages/vm/vm-cards/vm-summary.component.ts

Listens for VM events, and fires off the check available memory api call immediately, then in 5 seconds, then in 10 seconds, and stops.

Nas 103484

---

src/app/pages/common/entity/entity-dialog/entity-dialog.component.html
src/app/pages/common/entity/entity-dialog/entity-dialog.component.ts
src/app/pages/plugins/plugins.component.ts
src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
src/app/services/dialog.service.ts

Adds standard instructions to the doubleConfirm dialog about what to type in, provides a pseudo mask of the name of the dataset, plug-in, etc. to type over.

Nas 103453

---

src/app/helptext/services/components/service-dynamic-dns.ts

For 11.3
Yarn build test: no issues

NAS-103131: Sync DDNS service help text with docs

---

src/app/helptext/system/general.ts
src/app/pages/system/general/general.component.ts

Add validation for system general IP fields

---

src/app/pages/sharing/smb/smb-form/smb-form.component.ts

I think the code is correct, except that the paths are reversed, based on Andrew's description in the ticket.

NAS-103457 Flip logic acc to ticket instructions

---

src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts

Optimize pool data gathering

---

src/app/helptext/storage/volumes/datasets/dataset-acl.ts
src/app/pages/common/entity/entity-form/components/form-combobox/form-combobox.component.html
src/app/pages/storage/volumes/datasets/dataset-acl/dataset-acl.component.ts
src/assets/styles/themes/ix-blue.scss

Populate user and group fields with uid/gid and warn if the name could not be resolved

---

src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts

Combine calls into Observable.zip for faster pool loading time

---

src/app/pages/plugins/available-plugins/available-plugins.component.ts

Fix version/revision scheme for all plugins in selector not just the first selected

---

src/app/pages/storage/disks/disk-list/disk-list.component.ts

Use devname instead of name for wiping disks

---

src/app/pages/common/entity/entity-table/entity-table-add-actions.component.html
src/app/pages/common/entity/entity-table/entity-table.component.ts
src/app/pages/system/bootenv/bootenv-list/bootenv-list.component.ts

Moves top panel info and functions on Boot Env page into a dialog, expands the table

Nas 103462

---

src/app/helptext/sharing/smb/smb.ts
src/app/pages/sharing/smb/smb-form/smb-form.component.ts

Prompts user to restart SMB service if Time Machine has been newly enabled on the form

Nas 103469

---

src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts

Skip service/attachment checks if pool is in unknown state

---

src/app/pages/storage/volumes/manager/manager.component.css
src/app/pages/storage/volumes/manager/manager.component.html
src/app/pages/storage/volumes/manager/vdev/vdev.component.html

Expand disk name row column sizes to fit multipath disk names

---

src/app/helptext/storage/volumes/manager/vdev.ts
src/app/pages/storage/volumes/manager/manager.component.ts
src/app/pages/storage/volumes/manager/vdev/vdev.component.ts

Do not allow saving with vdevs containing disks of mixed sizes

---

src/app/helptext/sharing/iscsi/iscsi-wizard.ts
src/app/pages/sharing/iscsi/iscsi-wizard/iscsi-wizard.component.ts
src/app/services/network.service.ts
src/assets/styles/themes/ix-blue.scss

Validates (on blur) auth networks on ISCSI wizard.
BTW, I made a change in help text. It says to enter ALL in auth_network field, but this doesn't seem to work (even before validation!) and API calls for leaving it empty for all networks

Nas 103483

---

src/app/components/common/navigation/navigation.component.ts
src/app/pages/common/entity/entity-dashboard/entity-dashboard.component.ts

Hide acme dns on TrueNAS

---

src/app/services/notifications.service.ts

Use events to update alerts instead of polling

---

src/app/helptext/system/advanced.ts
src/app/pages/system/advanced/advanced.component.ts

Remove no longer used graphite field from system advanced

---

src/app/pages/dashboard/dashboard.component.ts

Kill all dashboard subscriptions when tab is not in focus

Dashboard Memory Leak part 2

---

src/app/pages/network/interfaces/interfaces-list/interfaces-list.component.ts

Fix error handling for network interface checkin/commit

---

src/app/helptext/system/advanced.ts
src/app/pages/system/advanced/advanced.component.ts
src/app/services/storage.service.ts

Add method for downloading streaming files on the backend to prevent need to open a new tab

---

src/app/components/common/layouts/admin-layout/admin-layout.component.ts

(cherry picked from commit c54e94e31823efebb1bd20bae8a73724dbf4ea7c)

NAS-102028 -- fix buggy comparison in footer console

---

src/app/helptext/system/bootenv.ts

Add information in the tooltip to inform users of valid characters.

NAS-103463: Update create tooltip to include allowable chars

---

src/app/components/common/topbar/topbar.component.ts

Subscribes to core.get_jobs to listen for updates, runs the function for notifying the user only once.

NAS-103559 

---

src/app/views/sessions/signin/signin.component.html
src/app/views/sessions/signin/signin.component.ts

Check the state of the machine before logging in with cached token

---

src/app/pages/storage/volumes/datasets/dataset-acl/dataset-acl.component.ts

Add defaults to ACL setting to show when new ones are added

NAS-103570

---

src/app/pages/system/CloudCredentials/cloudcredentials-form/cloudcredentials-form.component.ts

NAS-103508 

---

src/app/pages/common/entity/utils.ts

Fix off by 1 error that was preventing field error from being displayed

---

src/app/pages/system/acmedns/acmedns-add/acmedns-form.component.ts

Remove Hover from ACME choices, leaves drop down and conditions that allow other providers to be added.

NAS-103571

---

src/app/components/common/topbar/topbar.component.ts
src/app/helptext/network/interfaces/interfaces-form.ts
src/app/helptext/network/interfaces/interfaces-list.ts
src/app/pages/network/interfaces/interfaces-form/interfaces-form.component.ts
src/app/pages/network/interfaces/interfaces-list/interfaces-list.component.html
src/app/pages/network/interfaces/interfaces-list/interfaces-list.component.ts

Make network checkin text more consistent, move helptext to helptext file

---

src/app/core/components/widgets/widgetmemory/widgetmemory.component.css
src/app/core/components/widgets/widgetmemory/widgetmemory.component.html
src/app/pages/common/entity/entity-form/components/form-status/form-status.component.css
src/app/pages/common/entity/entity-form/components/form-status/form-status.component.html
src/app/pages/common/entity/entity-form/components/form-status/form-status.component.spec.ts
src/app/pages/common/entity/entity-form/components/form-status/form-status.component.ts
src/app/pages/common/entity/entity-form/entity-form-embedded.component.html
src/app/pages/common/entity/entity-form/entity-form-embedded.component.ts
src/app/pages/common/entity/entity.module.ts
src/app/pages/preferences/page/forms/general-preferences-form.component.ts

Since the preferences form doesn't take the user back to the home page, I added a confirmation graphic to entity-form-embedded

NAS-100561

---

src/app/helptext/services/components/service-snmp.ts
src/app/pages/services/components/service-snmp/service-snmp.component.ts

SNMP service fields contact and location are not actually required

---

src/app/pages/directoryservice/activedirectory/activedirectory.component.ts
src/app/pages/directoryservice/ldap/ldap.component.ts

Gives a blank option in AD and LDAP forms for kerberos realms and principals so user can de-select previously selected values.

Nas 103414

---

src/app/pages/system/email/email.component.ts

Send TrueNAS test email when box is TrueNAS

---

src/app/helptext/sharing/afp/afp.ts
src/app/helptext/sharing/nfs/nfs.ts
src/app/helptext/sharing/smb/smb.ts
src/app/helptext/sharing/webdav/webdav.ts
src/app/pages/sharing/afp/afp-list/afp-list.component.ts
src/app/pages/sharing/smb/smb-form/smb-form.component.ts
src/app/pages/sharing/smb/smb-list/smb-list.component.ts
src/app/pages/sharing/webdav/webdav-list/webdav-list.component.ts

Add comment field for SMB shares

---

README.md

Add pixabay image license to README

NAS-103795

---

src/app/core/classes/hardware/vdev-labels-svg.ts
src/app/core/classes/system-profiler.ts
src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.html
src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.ts
src/app/pages/system/viewenclosure/view-enclosure.component.html
src/app/pages/system/viewenclosure/view-enclosure.component.ts

Correctly handle scenarios where vdevs span multiple enclosures

NAS-103531

---

src/app/helptext/storage/volumes/volume-list.ts
src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts

Warn user about services that will be disrupted by locking the pool

---

src/app/core/components/pipes/convert.pipe.ts
src/app/core/components/widgets/widgetnic/widgetnic.component.ts
src/app/core/components/widgets/widgetpool/widgetpool.component.ts
src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.ts
src/app/pages/dashboard/dashboard.component.ts

Removed redundant  API calls.
Fix how widgetsysinfo detects the hardware model

Dash Unsubscribe

---

src/app/helptext/storage/volumes/volume-key.ts
src/app/pages/storage/volumes/volumerekey-form/volumerekey-form.component.ts
src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
src/app/services/encryption.service.ts

Remove snackbars from pool list and pool encryption forms

---

src/app/helptext/system/general.ts
src/app/pages/system/general/general.component.ts

Remove snackbar from System General

---

src/app/pages/system/update/update.component.ts

(cherry picked from commit 80fdc45ad200308753574b29501c0615a9b9930d)

Fix reversed logic preventing train from showing

---

src/app/helptext/system/support.ts
src/app/pages/system/support/proactive/proactive.component.ts
src/app/pages/system/support/production-status/production-status.component.ts
src/app/pages/system/support/support.component.ts
src/app/pages/system/support/tn-support/tn-support.component.ts
src/app/pages/system/support/tn-sys-info/tn-sys-info.component.ts

Changes snackbars to dialogs in support

NAS-103767

---

src/app/helptext/system/failover.ts
src/app/pages/system/failover/failover.component.ts

Snackbars removed from failover

NAS-103714

---

src/app/helptext/system/tunable.ts
src/app/pages/system/tunable/tunable-form/tunable-form.component.ts
src/app/pages/system/tunable/tunable-list/tunable-list.component.ts

Changes 'comment' to 'description' for tunables form and table

NAS-103762

---

src/app/services/dialog.service.ts

Fix keep primary group on user deletion

---

src/app/pages/system/CloudCredentials/cloudcredentials-form/cloudcredentials-form.component.ts
src/app/pages/system/alertservice/alert-service/alert-service.component.ts

NAS-103618 

---

src/app/pages/plugins/plugins.component.ts

Show admin portal by default, put ip addresses on panel

NAS-103439

---

src/app/services/notifications.service.ts

Fix inverted logic for clearing alerts

---

tests/selenium/test_086_store_delete.py

Adding code to input the pool name to confirm

QE-243 Update Export/disconnect UI pool test

---

src/app/helptext/system/certificates.ts
src/app/pages/system/certificates/certificate-list/certificate-list.component.ts

Removes snackbars from cert list, changes download method

NAS-103765

---

src/app/pages/network/interfaces/interfaces-list/interfaces-list.component.ts
src/app/pages/network/ipmi/ipmi.component.ts

Remove snackbars from networking

---

src/app/components/common/topbar/topbar.component.ts

Snackbars to menus in topbar - I dropped the response to accepting the EULA - seems unnecessary?

NAS-103823

---

src/app/pages/storage/disks/disk-wipe/disk-wipe.component.ts

Remove snackbar code from disk-wipe (wasn't being called - also, nothing in disks

NAS-103818

---

src/app/pages/task-calendar/cloudsync/cloudsync-form/cloudsync-form.component.ts

NAS-103715-2

---

src/app/core/components/widgets/widgetpool/widgetpool.component.css
src/app/core/components/widgets/widgetpool/widgetpool.component.html

Show partial list of disk names on vdev view in pool widget

NAS-103740

---

src/app/pages/system/reporting/reporting.component.ts

Removes snackbar from sys reporting

NAS-103842

---

src/app/pages/system/update/update.component.ts

NAS-103845 

---

src/app/pages/storage/volumes/manager/manager.component.ts
src/app/pages/storage/volumes/volume-status/volume-status.component.ts

Remove snackbars from pool manager and pool status

---

src/app/helptext/account/user-change-pw.ts
src/app/pages/account/users/change-password/change-password.component.ts

Change password page no longer shows username, and now validates current password

---

src/app/pages/common/entity/entity-wizard/entity-wizard.component.ts

Removes snack bar from entity wizard

NAS-103841

---

src/app/pages/common/error-dialog/error-dialog.component.ts
src/app/services/job.service.ts

NAS-103840 

---

src/app/pages/task-calendar/cron/cron-list/cron-list.component.ts

Convert snackbar to info dialog on cron jobs

---

src/app/components/common/dialog/downloadkey/downloadkey-dialog.component.ts

Download pool key programatically

---

src/app/core/classes/hardware/vdev-labels-svg.ts
src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.css
src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.ts
src/app/views/sessions/signin/signin.component.ts

Signin component needs to properly unregister from core service. Also remove margins from vdev labels

NAS-103852

---

src/app/pages/common/entity/entity-table/entity-row-details.component.html
src/app/pages/common/entity/entity-table/entity-table-add-actions.component.html
src/app/pages/common/entity/entity-table/entity-table-row-details/entity-table-row-details.component.html
src/app/pages/common/entity/entity-table/entity-table.component.html

Adds tags to entity table, actions, expandable rows, etc. which will eventually be rolled into the PO files

NAS-103869 Translate tags for entity table and related components

---

src/app/pages/reportsdashboard/reportsdashboard.component.ts

Don't show a UPS tab in reporting if the report does not exist in middleware response.

NAS-103865

---

src/app/pages/services/components/service-ftp/service-ftp.component.ts

Anonymous path is now hidden unless anon login is allowed, this field is also anonymous required when login is allowed

---

src/app/core/components/widgets/widgetnic/widgetnic.component.html
src/app/core/components/widgets/widgetnic/widgetnic.component.ts

Do unit conversion in component instead of pipe. Optimize for units other than just KiB
This also fixes NAS-103931

NAS-103741

---

src/app/helptext/system/ssh-connections.ts

- Port existing text from the 11.3 guide and remove bits that don't apply to the UI.
- Yarn build testing: no issues.

NAS-103801: Add help text to all fields in System/SSH Connections

---

src/app/helptext/services/components/service-ups.ts
src/app/pages/services/components/service-ups/service-ups.component.ts

Shutdown command shouldn't be required for ups

---

src/app/helptext/storage/snapshots/snapshots.ts
src/app/pages/storage/snapshots/snapshot-clone/snapshot-clone.component.ts

Rename snapshot clone to "clone to new dataset"

---

src/app/pages/vm/vm-list/vm-list.component.ts

Uses VNC bind address as a parameter in api call

NAS-101236

---

src/app/helptext/storage/VMware-snapshot/VMware-snapshot.ts
src/app/pages/storage/VMware-snapshot/VMware-snapshot/VMware-snapshot-form.component.ts

As described in ticket discussion, makes the dialog more friendly, eliminates traceback

NAS-103883 improve dialog for connection error

---

src/app/pages/sharing/webdav/webdav-list/webdav-list.component.ts

Adds wsdelete call to webdav (which I missed earlier)

NAS-103948

---

src/app/helptext/system/reporting.ts

NAS-103528: Sync `Graphite Server` name and help text with Docs PR 1612.

---

src/app/helptext/account/groups.ts
src/app/pages/account/groups/group-form/group-form.component.ts

Hide allow repeated GIDs field when in edit mode and set it to true

---

src/app/pages/network/interfaces/interfaces-form/interfaces-form.component.ts
src/app/services/network.service.ts

Allow invalidating ip addresses in network interfaces

---

src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.ts

Add product image support for E and XL+ on the system information dashboard widget

NAS-103972 

---

src/app/helptext/storage/volumes/volume-list.ts
src/app/pages/common/entity/entity-table/entity-table-actions.component.html
src/app/pages/common/entity/entity-table/entity-table-row-details/entity-table-row-details.component.html
src/app/pages/common/entity/entity-tree-table/entity-tree-table.component.html
src/app/pages/sharing/smb/smb-form/smb-form.component.ts
src/app/pages/sharing/smb/smb-list/smb-list.component.ts
src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts

Disables options (for pool list, SMB shares list, and when creating an SMB share) to edit permissions or ACL. Also provides a mat-tooltip explanation when the button or option is disabled

Nas 103953

---

src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
src/assets/styles/themes/ix-blue.scss

Displays dialog when services must be stopped on pool export; also makes use of self=this.

Nas 103679

---

src/app/helptext/system/general.ts

NAS-101549 Update tooltip for Syslog Server

---

src/app/pages/common/entity/entity-tree-table/entity-tree-table.component.html
src/app/pages/common/entity/entity-tree-table/entity-tree-table.component.ts
src/app/pages/storage/volumes/volumes-list/volumes-list.component.html
src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts

Add some translate pipes to make the pools page more translatable

---

src/app/helptext/storage/volumes/zvol-form.ts

Capitalize Zvol and remove : for consistency

---

src/app/pages/storage/volumes/manager/manager.component.ts
src/app/pages/storage/volumes/manager/vdev/vdev.component.ts

Use value from system advanced for swapsize in vdev estimation

---

src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts

Allow null values for quota/reservation fields

---

src/app/helptext/directoryservice/ldap.ts
src/app/pages/common/entity/entity-form/entity-form.component.ts
src/app/pages/directoryservice/activedirectory/activedirectory.component.ts
src/app/pages/directoryservice/ldap/ldap.component.ts

Update Active Dir and LDAP forms to use new mw calls, make LDAP use ws

Nas 104016

---

src/app/pages/system/general/general.component.ts

Fix possible traceback if certificate is not available on page load

---

src/app/pages/storage/volumes/datasets/dataset-permissions/dataset-permissions.component.ts

Converts pool.dataset.permission to a job

Nas 104025

---

src/app/helptext/services/components/service-ftp.ts
src/app/pages/services/components/service-ftp/service-ftp.component.ts

Add warning for Allow Root Login

---

src/app/pages/sharing/smb/smb-form/smb-form.component.ts
src/app/pages/sharing/smb/smb-list/smb-list.component.ts

…to allow all paths to ACL editor to work

NAS-103973 Simplify method for getting pool name

---

src/app/pages/system/support/support.component.ts
src/app/pages/system/support/tn-sys-info/tn-sys-info.component.html

Fix bug in calculating exp date for license, add translate markers

NAS-104101

---

src/app/helptext/storage/volumes/datasets/dataset-form.ts
src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts

Add 'Inherit' checkboxes for quota critical/warning fields

---

src/app/helptext/sharing/smb/smb.ts

NAS-103892: Port MacOS guest access tip into Sharing/SMB help text

---

src/app/helptext/network/interfaces/interfaces-form.ts
src/app/pages/network/interfaces/interfaces-form/interfaces-form.component.ts

Add Disable Offload Capabilities field

---

src/app/pages/system/bootenv/bootenv-status/bootenv-status.component.ts

Single disks are now 'Attach' and 'Replace' and multiple disks are 'Detach' and 'Replace'
Issue NAS-103462

NAS-103462b Allow single disks to be replaced

---

src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts

Fix issue with inheritence not being checked properly for root dataset

---

src/app/pages/storage/volumes/datasets/dataset-acl/dataset-acl.component.ts

Reset the ACLs before setting new values

---

src/app/helptext/account/groups.ts
src/app/helptext/account/user-form.ts
src/app/pages/account/groups/group-form/group-form.component.ts
src/app/pages/account/groups/group-list/group-list.component.ts
src/app/pages/account/groups/members/members.component.ts
src/app/pages/account/users/user-form/user-form.component.ts
src/app/pages/account/users/user-list/user-list.component.ts

Accounts pages now use web socket API exclusively.

NAS-103684

---

src/app/pages/storage/snapshots/snapshot-clone/snapshot-clone.component.ts

Convert snapshot clone to websocket

---

src/app/pages/storage/volumes/volume-import-wizard/volume-import-wizard.component.ts

Do not pass null for passphrase on pool import

---

src/app/helptext/services/components/service-smart.ts
src/app/pages/services/components/service-smart/service-smart.component.ts

Not sure if were _always_ using fieldsets or not. If so, could use some help on how to lay this form out.

NAS-103696

---

src/app/helptext/system/general.ts
src/app/pages/system/general/general.component.ts

Remove notifier and use hardcoded list for syslog level options

---

src/app/helptext/system/bootenv.ts
src/app/pages/system/bootenv/bootenv-clone/bootenv-clone.component.ts

Convert boot environment clone to websocket call

---

src/app/pages/jails/jail-list/jail-list.component.ts
src/app/pages/plugins/plugins.component.ts

NAS-104117

---

src/app/pages/jails/jail-list/jail-list.component.ts
src/app/pages/plugins/plugins.component.ts

activate pool for jail manager

NAS-104186

---

src/app/pages/task-calendar/rsync/rsync-form/rsync-form.component.ts

Add querykey to rsync task to make it call properly

---

src/app/services/network.service.ts

Remove notifier calls from network service

---

src/app/helptext/sharing/webdav/webdav.ts
src/app/pages/sharing/webdav/webdav-form/webdav-form.component.ts

Convert Webdav shares to websocket

---

src/app/helptext/services/components/service-lldp.ts
src/app/pages/services/components/service-lldp/service-lldp.component.ts
src/assets/styles/themes/ix-blue.scss

Adds validation to lldp form for country field

Nas 104079

---

src/app/pages/common/entity/entity-form/components/form-input/form-input.component.html

Still fits on pool unlock dialog too

NAS-104081 Add some margin on the file uploader

---

src/app/pages/common/entity/entity-form/components/tooltip/tooltip.component.css

NAS-104075 Make long titles on tooltips use ellipsis

---

src/app/helptext/directoryservice/activedirectory.ts
src/app/pages/directoryservice/activedirectory/activedirectory.component.ts

Makes the AD password field optional unless 'Enable' is checked

Nas 104048

---

src/app/helptext/jails/jail-configuration.ts
src/app/pages/jails/jail-add/jail-add.component.ts
src/app/pages/jails/jail-edit/jail-edit.component.ts
src/app/pages/plugins/plugin-advanced-add/plugin-advanced-add.component.ts

NAS-104119 

---

src/app/pages/common/entity/entity-form/entity-form.component.html

Translate fieldset header names

---

src/app/pages/preferences/page/forms/general-preferences-form.component.ts

I will update the docs when this text is approved.

NAS-103998 clarify password toggle setting in preferences

---

src/app/components/common/navigation/navigation.component.ts
src/app/pages/system/support/proactive/proactive.component.ts

This bug shows up on an unlicensed system, but not on localhost (at least not for me). I patched it onto a virtual TN machine to test.

NAS-104131 Fix a bug that trips up support page

---

src/app/helptext/directoryservice/activedirectory.ts
src/app/pages/directoryservice/activedirectory/activedirectory.component.ts

Adds a 'leave domain' button and functionality to AD, dynamically shows/hides button and checks/unchecks box as relevant.

Nas 104037

---

src/app/components/common/dialog/task-manager/task-manager.component.css
src/app/components/common/dialog/task-manager/task-manager.component.html

NAS-104144 Add icon for aborted tasks in TM

---

src/app/helptext/directoryservice/idmap.ts
src/app/pages/directoryservice/idmap/idmap.component.ts

Updates ldap range hi-low helptext, removes repeated code
Ps - helptext comes from Warren, Andrew

Nas 104064

---

src/app/pages/storage/volumes/volume-import-wizard/volume-import-wizard.component.ts

Hide the upload button on import pool

---

src/app/pages/network/interfaces/interfaces-list/interfaces-list.component.ts

Remove pesky comma that was breaking filtering in interfaces

---

src/app/pages/system/ntpservers/ntpserver-add/ntpserver-add.component.ts

This is also covered in PR #3200, but this is for 11.3

NAS-104114 Set iburst to true

---

src/app/components/common/topbar/topbar.template.html

Remove account entry from upper gear icon

---

src/app/components/common/topbar/topbar.component.ts

Re-remove polling checks for network status from UI

---

src/app/helptext/directoryservice/kerberosrealms-form-list.ts
src/app/pages/directoryservice/kerberosrealms/kerberosrealms-form/kerberosrealms-form.component.ts
src/app/pages/directoryservice/kerberosrealms/kerberosrealms-list/kerberosrealms-list.component.ts

Also displays and accepts fields which accept more than one value as space -separated lists, and filters out commas

Nas 103688 k-realms rest to ws

---

src/app/helptext/task-calendar/cron/cron-form.ts
src/app/pages/task-calendar/cron/cron-form/cron-form.component.ts
src/app/pages/task-calendar/cron/cron-list/cron-list.component.ts

Move cron pages to websocket API.

NAS-103725-1

---

src/app/components/common/dialog/task-manager/task-manager.component.ts

Remove exception (traceback) from datasource in task manager to improve filtering

Nas 104227 Filtering for Task Manager

---

src/app/pages/system/dataset/dataset.component.ts

Make sure loader opens and closes at the right time in all conditions

NAS-104076

---

src/app/helptext/network/interfaces/interfaces-form.ts
src/app/pages/network/interfaces/interfaces-form/interfaces-form.component.ts

Replace notifier for vlanpcp in network interfaces

---

src/app/helptext/directoryservice/kerberossettings.ts
src/app/pages/directoryservice/kerberossettings/kerberossettings.component.ts

Also updates broken links in tooltips to https

Nas 103689 WS for Kerberos settings

---

src/app/pages/network/interfaces/interfaces-form/interfaces-form.component.ts

Always show Disable Offload Capabilities field

---

src/app/helptext/storage/volumes/datasets/dataset-form.ts

Will update docs when text is approved.

NAS-104052 Update help text for Inherit checkbox for datasets

---

src/app/helptext/system/cloudcredentials.ts

NAS-103580: unify help text with Guide field description.

---

src/app/helptext/storage/volumes/datasets/dataset-acl.ts

NAS-103519: Sync Default ACL Options help text with guide

---

src/app/pages/common/entity/entity-job/entity-job.component.ts
src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
src/app/services/storage.service.ts

Adjust pool unlock to use websocket call and id for services to restart

---

src/app/pages/storage/volumes/volume-import-wizard/volume-import-wizard.component.ts

Fix logic for hiding/showing decryption options on pool import wizard

---

src/app/helptext/system/reporting.ts
src/app/pages/system/reporting/reporting.component.ts

Refreshes comparison values on save, so that data that is immediately reentered will be checked correctly

NAS-104311 set graph age and points on submit

---

src/app/pages/storage/volumes/manager/manager.component.ts

Update estimated size after repeat

---

src/app/components/common/topbar/topbar.component.ts
src/app/helptext/global-helptext.ts
src/app/views/sessions/signin/signin.component.html
src/app/views/sessions/signin/signin.component.ts

Keep track of ha status to show a different message on login screen during failover

---

src/app/pages/common/entity/entity-form/components/form-explorer/form-explorer.component.html
src/app/pages/common/entity/entity-form/services/entity-form.service.ts

Add ACL tag to name of folder for file explorer view if acl is present

---

src/app/helptext/services/components/service-ups.ts

- Add text for the new auto option
- Yarn test: no issues.

NAS-103592: Update helptext for Services/UPS/Port or Hostname

---

src/app/components/common/topbar/topbar.component.ts

Should stop multiple dialogs from popping up over long waits while updating

NAS-104289 Call dialog only once

---

src/app/helptext/task-calendar/cloudsync/cloudsync-form.ts

NAS-103716: Update Tasks/Cloud Sync Tasks/Direction help text

---

src/app/helptext/jails/jail-configuration.ts
src/app/helptext/jails/jail-wizard.ts
src/app/helptext/jails/jails-add.ts
src/app/helptext/plugins/plugins.ts
src/app/pages/plugins/plugin-add/plugin-add.component.ts

Make jail and plugin name tooltips consistent, add a missing helptext to the plugin screen.

NAS 104009

---

src/app/pages/task-calendar/cloudsync/cloudsync-form/cloudsync-form.component.ts

NAS-104377

---

src/app/helptext/system/dataset.ts
src/app/pages/system/dataset/dataset.component.ts

Converted System Dataset page to websocket calls.
Applied fieldset layout to form.

NAS-103721

---

src/app/services/language.service.ts

Convert language service from rest to websocket

---

src/app/pages/network/interfaces/interfaces-form/interfaces-form.component.ts

Fix display of vlan parent interface in edit mode

---

src/app/pages/common/confirm-dialog/confirm-dialog.component.html

Add translation to confirmation dialog

---

src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.html

Update the words that can be translated but they will have to be injected into the PO file.

Update words that can be translated

---

src/app/helptext/global-helptext.ts
src/app/helptext/sharing/afp/afp.ts
src/app/pages/common/entity/entity-form/classes/field-sets.ts
src/app/pages/common/entity/entity-form/entity-form-embedded.component.ts
src/app/pages/common/entity/entity-form/entity-form.component.ts
src/app/pages/sharing/afp/afp-form/afp-form.component.ts

Also adds a FieldSets class which tries to centralize some of the more common fieldset operations.

NAS-103702 -- afp share config rest -> ws

---

src/app/pages/common/entity/entity-form/components/tooltip/tooltip.component.html

Translate tooltip headers

---

src/app/pages/task-calendar/replication/replication-wizard/replication-wizard.component.ts

Update the words that can be translated but they will have to be injected into the PO file.

Add T markers for translation

---

src/app/pages/storage/disks/disk-list/disk-list.component.ts

Remove enclosure column from disks

---

src/app/pages/system/advanced/advanced.component.ts

Hide tracebacks field that doesn't do anything

---

package.json
src/environments/environment.prod.ts

Removing sentry, it just hasn't been useful since most tracebacks are too cryptic in prod mode

---

src/app/core/components/widgets/widgetnic/widgetnic.component.html
src/app/core/components/widgets/widgetnic/widgetnic.component.ts
src/app/pages/dashboard/dashboard.component.ts

Show INET6 interface type on dashboard interface widget

NAS-104373

---

src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.html

Put 3 letters to the days of the week (instead of 1) to avoid incompatibility of translation in somes languages. Update the words that can be translated but they will have to be injected into the PO file.

Put 3 letters to the days of the week

---

src/assets/styles/themes/ix-blue.scss

Fixes non-responding file uploader in tn-support (maybe chrome only?)

NAS-104415 Constrain width of button actions

---

src/app/pages/reportsdashboard/reportsdashboard.component.ts
src/app/pages/reportsdashboard/reportsdashboard.html

Added T() and translation pipes on UI side.

NAS-104434

---

src/app/helptext/network/interfaces/interfaces-form.ts
src/app/pages/network/interfaces/interfaces-form/interfaces-form.component.ts

Add confirm dialog for disable offload capabilities

---

src/app/helptext/directoryservice/ldap.ts

https://github.com/freenas/freenas-docs/pull/1665/files

NAS-104280: resync docs and help text (Dir. Service/LDAP)

---

src/app/pages/systemprocesses/system-processes.component.ts

System processes now waits until the terminal starts printing before executing a command.

---

src/app/helptext/system/reporting.ts
src/app/pages/system/reporting/reporting.component.ts

Removed inputType=number, added some labels.

NAS-104288 Make changes based on UI meeting

---

src/app/pages/system/system.routing.ts

Add a T marker for breadcrumb translation Alert Service

Add a T marker for translation

---

src/environments/environment.ts.skel

Remove no longer used raven dependency from skeleton file

---

src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts

Kris wrote a new warning for this dialog on the ticket in Jira, and Warren punched it up a little and made the title titlecase. Hope everyone likes it!

NAS-104323 Change dialog text

---

src/app/pages/system/update/update.component.html
src/app/pages/system/update/update.component.ts

Un-hardcode url for release notes

---

src/app/pages/common/entity/entity-form/services/entity-form.service.ts

Hide symlinks in file/directory display

---

src/app/helptext/network/interfaces/interfaces-form.ts

Update field name and help text to sync up with RC2 guide.
Keep synced with freenas-docs PR 1652 https://github.com/freenas/freenas-docs/pull/1652/files

NAS-104139: Update hardware offload field

---

src/app/helptext/system/reporting.ts
src/app/pages/system/reporting/reporting.component.ts

Shows the warning dialog when CPU percent checkbox is checked as well as under two other possible conditions. Warren wrote the warning message and William confirmed the behavior.

NAS-103966

---

src/app/pages/network/interfaces/interfaces-form/interfaces-form.component.ts

Reset MTU to 1500 if MTU is cleared

---

src/app/components/common/topbar/topbar.component.ts
src/app/core/components/widgets/widgetsysinfo/simple-failover-btn.component.ts
src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.css
src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.html
src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.ts

System information widget for standby controller reacts to HA status provided by HA status icon in topbar.

NAS-104224

---

src/app/core/components/widgets/widgetcpu/widgetcpu.component.html
src/app/pages/common/entity/entity-form/entity-form-embedded.component.ts
src/app/pages/common/entity/entity-form/entity-form.component.ts
src/app/pages/jails/jail-wizard/jail-wizard.component.ts
src/app/pages/network/ipmi/ipmi.component.ts
src/app/pages/preferences/page/forms/custom-theme-manager-form.component.ts
src/app/pages/preferences/page/forms/customtheme/customtheme.component.ts
src/app/pages/reportsdashboard/reportsdashboard.component.ts
src/app/pages/services/components/service-ftp/service-ftp.component.ts
src/app/pages/services/components/service-ssh/service-ssh.component.ts
src/app/pages/services/services-table.component.html
src/app/pages/sharing/iscsi/target/target-form/target-form.component.ts
src/app/pages/storage/VMware-snapshot/VMware-snapshot/VMware-snapshot-form.component.ts
src/app/pages/storage/volumes/volumechangekey-form/volumechangekey-form.component.ts
src/app/pages/storage/volumes/volumecreatekey-form/volumecreatekey-form.component.ts
src/app/pages/system/update/manualupdate/manualupdate.component.ts
src/app/pages/system/update/update.component.html
src/app/pages/task-calendar/cron/cron-form/cron-form.component.ts

I've completed Russian translation as of now. Yay!
So everything that still remains in English in UI probably misses respective tags. I've tried to add some in this PR, but don't know whether it is correct, and it is definitely far from all.  At least there are folder headers in iSCSI are not translated.  And I haven't checked, but I guess that enclosure management may be also.

Add some random translation tags.

---

src/app/core/components/widgets/widgetpool/widgetpool.component.ts
src/app/core/services/api.service.ts
src/app/pages/dashboard/dashboard.component.ts

- VolumeDataRequest event now sends websocket call instead of REST.
- Pool Widget on dash needed to adapt to the different data structure returned from middleware.

NAS-104305

---

src/app/core/components/widgets/widgetnic/widgetnic.component.ts

Use new rate property from reporting.realtime
Ticket:
https://jira.ixsystems.com/browse/NAS-104507

NAS-104507 Master

---

src/app/core/components/widgets/widgetnic/widgetnic.component.ts

Use new rate property from reporting.realtime
Ticket:
https://jira.ixsystems.com/browse/NAS-104507

NAS-104507

---

src/app/pages/network/interfaces/interfaces-list/interfaces-list.component.ts

@william-gr do you agree that we should DB VLAN parent interface here? We already show DB bridge members, LAGG ports and protocol. Or if we want to display actual values, I should make a reverse change?

Show DB VLAN parent interface

---

src/app/helptext/storage/disks/disk-form.ts

DOCS-121: Resync Guide and UI help text (Storage/Disks/Edit)

---

src/app/helptext/system/tunable.ts
src/app/pages/system/tunable/tunable-form/tunable-form.component.ts
src/app/pages/system/tunable/tunable-list/tunable-list.component.ts

Convert tunables to web socket api.
Add fieldsets to form

NAS-103723

---

src/app/pages/storage/volumes/datasets/dataset-acl/dataset-acl.component.ts
src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
src/app/pages/storage/volumes/manager/manager.component.ts

Removed references to rest service from pool manager and a couple of other storage related files.

NAS-103718

---

src/app/components/common/notifications/notifications.component.ts

Prevent displaying duplicate notifications

---

src/app/pages/reportsdashboard/reports-utils.worker.ts

Convert cpu temps to array so it gets displayed properly

---

src/app/pages/common/confirm-dialog/confirm-dialog.component.html
src/app/pages/common/entity/entity-form/services/message.service.ts
src/app/pages/sharing/smb/smb-form/smb-form.component.ts
src/app/pages/storage/volumes/datasets/dataset-acl/dataset-acl.component.ts

On creation of new SMB home share, navigates to ACL form and chooses 'HOME' ACL preset

Nas 104575

---

src/assets/i18n/cs.po

[cs.po] Minor Czech update

---

src/app/pages/network/interfaces/interfaces-list/interfaces-list.component.ts

Add MTU to network interface columns

---

src/app/pages/common/entity/entity-form/components/form-select/form-select.component.html
src/app/pages/common/entity/entity-form/components/form-select/form-select.component.scss
src/app/pages/common/entity/entity-form/models/field-config.interface.ts
src/app/pages/system/alert/alert.component.ts

Inline label support for form-select. Alert settings page uses this feature

NAS-104630 / 12.0 / NAS-104630

---

src/app/pages/network/interfaces/interfaces-form/interfaces-form.component.ts
src/app/services/network.service.ts

Use websocket call to get lagg protocols

---

src/app/helptext/system/general.ts

s/WebGUI/Web Interface

---

src/app/pages/network/ipmi/ipmi.component.ts

Add button linking to ipmi management page
Also took the liberty of removing pw confirm field

NAS-103990 / 12.0 / NAS-103990 

---

src/app/pages/account/groups/group-list/group-list.component.ts

NAS-104653 / 12.0 / Convert group-list to websocket

---

src/app/helptext/task-calendar/initshutdown/initshutdown.ts
src/app/pages/task-calendar/initshutdown/initshutdown-form/initshutdown-form.component.ts
src/app/pages/task-calendar/initshutdown/initshutdown-list/initshutdown-list.component.ts

NAS-102175 / 12.0 / Add fieldset, description field and T markers to initshutdown scripts

---

src/app/helptext/services/components/service-s3.ts
src/app/pages/services/components/service-s3/service-s3.component.ts

NAS-104456 / 12.0 / Apply fieldsets to S3 configuration

---

src/app/helptext/services/components/service-snmp.ts
src/app/pages/services/components/service-snmp/service-snmp.component.ts

NAS-104457 / 12.0 / Apply fieldsets to snmp service

---

src/app/helptext/services/components/service-webdav.ts
src/app/pages/services/components/service-webdav/service-webdav.component.ts

NAS-104458 / 12.0 / Add fieldsets to webdav service

---

src/app/helptext/system/failover.ts
src/app/pages/system/failover/failover.component.ts

NAS-104453 / 12.0 / Add fieldsets for system failover

---

src/app/services/navigation/navigation.service.ts

NAS-104003 / 12.0 / Adjust network menu to be more logical

---

src/app/components/common/notifications/notifications.component.html

Adds am/pm to alert times, for now. Hope to revisit this to allow 24 hrs, other styles as local/date choices are completed

NAS-104642 / 11.3 / NAS-104642 Add am/pm to alert times

---

src/app/components/common/notifications/notifications.component.html

Adds am/pm to alert times, for now. Hope to revisit this to allow 24 hrs, other styles as local/date choices are completed

NAS-104642 / 12.0 / NAS-104642 Add am/pm to alert times

---

src/app/services/notifications.service.ts

NAS-104577 / 11.3 / Do not repopulate duplicate notifications

---

src/app/services/notifications.service.ts

NAS-104577 / 12.0 / Do not repopulate duplicate notifications (by erinix)

---

scripts/convert_po2json.js

NAS-104676 / 12.0 / Add a process.exit to the script so it can error out on bad PO files

---

scripts/convert_po2json.js

NAS-104676 / 11.3 / Add a process.exit to the script so it can error out on bad PO files (by erinix)

---

src/app/pages/common/entity/entity-form/components/form-combobox/form-combobox.component.html
src/app/pages/common/entity/entity-form/components/form-combobox/form-combobox.component.ts
src/app/pages/system/general/general.component.ts

Make timezone and language filterable

NAS-103967 / 12.0 / Nas 103967

---

src/app/pages/sharing/webdav/webdav-form/webdav-form.component.ts

NAS-101095 / 12.0 / Have UI check if WebDAV service is enabled when share is created

---

src/app/helptext/network/ipmi/ipmi.ts
src/app/pages/network/ipmi/ipmi.component.ts

NAS-104143 / 12.0 / Split IPMI password into its own fieldset

---

src/app/helptext/sharing/smb/smb.ts

(cherry picked from commit 3dfd7050b6c5c98502699c201c114c0ce24dfb40)

DOCS-102 update help text for "Use as Home Share".

---

src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts

NAS-104693 / 12.0 / Add translate.get for pool upgrade so text can be translated

---

src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts

NAS-104712 / 12.0 / NAS-104712 Fix pool label

---

src/app/pages/common/entity/entity-form/entity-form.component.ts

NAS-104006 / 12.0 / NAS-104006

---

src/app/pages/common/entity/entity-table/entity-table.component.ts

@erinix this is needed for 11.3-RELEASE

Do not display clickable button for LEGACY periodic snapshot tasks

---

src/app/pages/task-calendar/replication/replication-form/replication-form.component.ts
src/app/pages/task-calendar/replication/replication-wizard/replication-wizard.component.ts

Ensures that source data from replication wizard and form gets converted from string to array; also gets rid of user-entered whitespace. Thanks to Vladimir Vinogradenko for the clean lodash solution

NAS-104727 / 11.3 / Nas 104727

---

src/app/helptext/task-calendar/cloudsync/cloudsync-form.ts
src/app/pages/task-calendar/cloudsync/cloudsync-list/cloudsync-list.component.ts

- Add a little more text to the dialog to explain what will happen.

NAS-102288 / None / NAS-102288: move dry run dialog to help text file

---

src/app/components/common/dual-list/dual-list.component.css
src/app/components/common/dual-list/dual-list.component.html
src/app/pages/account/groups/members/members.component.html
src/app/pages/storage/volumes/manager/vdev/vdev.component.css
src/assets/styles/themes/ix-blue.scss

Better style and sizing for Groups > Members

NAS-100793 / 12.0 / Nas 100793

---

src/app/helptext/system/reporting.ts
src/app/pages/system/reporting/reporting.component.ts

NAS-102245 / 12.0 / Add graphite separate instances field to reporting settings

---

src/app/helptext/vm/vm-wizard/vm-wizard.ts
src/app/pages/vm/vm-form/vm-form.component.ts
src/app/pages/vm/vm-list/vm-list.component.ts
src/app/pages/vm/vm-wizard/vm-wizard.component.ts

Adds cores and threads to VM wizard, form and table; validates the three values against each other; changes vm form to ws; updates some values in vm wizard that have changed in mw for v. 12;
To save a new VM, I had to uncheck 'Enable VNC' on the first panel of the wizard; mw team is looking into this.

NAS-104398 / 12.0 / Nas 104398

---

src/app/helptext/vm/vm-wizard/vm-wizard.ts
src/app/pages/vm/vm-form/vm-form.component.ts

The other forms in VM (Add/Edit) devices are non-entity and apply Fieldsets on their own

NAS-100659 / 12.0 / NAS-100659 Fieldsets for VM edit form

---

src/app/pages/common/entity/entity-table/entity-table.component.html
src/app/pages/common/entity/entity-table/entity-table.component.ts
src/app/pages/storage/snapshots/snapshot-list/snapshot-list.component.ts

Also, settimout in entity table gets rid of persistent console error

NAS-103977 / 12.0 / NAS-103977 Default sorted column

---

src/app/pages/common/entity/utils.ts

NAS-104183 / 12.0 / Better handle error messages for array

---

src/app/helptext/network/configuration/configuration.ts
src/app/helptext/services/components/service-smb.ts
src/app/pages/network/configuration/configuration.component.ts
src/app/pages/services/components/service-smb/service-smb.component.ts

NAS-104714 / 12.0 / Remove zeroconf from SMB, add Service Announcement section to Network Configuration

---

src/app/helptext/system/update.ts
src/app/pages/common/entity/entity-table/entity-table.component.ts
src/app/pages/system/general/general.component.ts
src/app/pages/system/update/update.component.html
src/app/pages/system/update/update.component.ts
src/app/services/ws.service.ts

Fixes some tracebacks in update page
Updates logic so errors dowloading config files stop the upgrade process until user chooses to continue
Rearranges update component to put commands together that execute the update
Also fixes a common traceback from entity table and one from ws service

NAS-104758 / 12.0 / Nas 104758

---

src/app/helptext/system/advanced.ts
src/app/pages/system/advanced/advanced.component.ts

NAS-104806 / 12.0 / Remove Legacy UI field from System advanced

---

src/app/helptext/sharing/smb/smb.ts
src/app/pages/sharing/smb/smb-form/smb-form.component.ts

NAS-104816 / 12.0 / Remove VFS objects from SMB share creation

---

src/app/helptext/sharing/iscsi/iscsi.ts

- Fix conflicts in files and complete the cherry-pick
Complete sync with final text from freenas-docs PR 1675

DOCS-116: Update iSCSI/Portals/IP Address help text (master port)

---

src/assets/styles/themes/ix-blue.scss

Right 'margin' for red button on Encrypt key dialog

NAS-104803 / 12.0 / NAS-104803 Space for encrypt button

---

src/assets/styles/themes/ix-blue.scss

Right 'margin' for red button on Encrypt key dialog

NAS-104803 / 11.3 / NAS-104803 Space for encrypt button

---

src/app/pages/services/components/service-smb/service-smb.component.ts
src/app/services/user.service.ts

NAS-104687 / 12.0 / Add filter for builtin groups

---

src/app/pages/system/general/general.component.ts
src/app/services/system-general.service.ts

NAS-104481 / 11.3 / Use new methods for ipv4/ipv6 listening addresses for WebUI

---

src/app/core/services/system-profile.service.ts
src/app/pages/network/configuration/configuration.component.ts
src/app/pages/network/network.module.ts

Cached system.info data needs to be updated when global network settings have been submitted

NAS-104652 / 11.3 / NAS-104652

---

src/app/helptext/directoryservice/activedirectory.ts
src/app/pages/common/entity/entity-form/entity-form.component.ts
src/app/pages/directoryservice/activedirectory/activedirectory.component.ts

When joining a domain, repopulates key menus based on response from submit event

NAS-104489 / 11.3 / Nas 104489

---

src/app/helptext/directoryservice/activedirectory.ts
src/app/pages/common/entity/entity-form/entity-form.component.ts
src/app/pages/directoryservice/activedirectory/activedirectory.component.ts

When joining a domain, repopulates key menus based on response from submit event

NAS-104489 / 12.0 / NAS-104489 for 12

---

src/app/pages/common/entity/entity-form/components/form-explorer/form-explorer.component.html
src/app/pages/common/entity/entity-form/components/form-explorer/form-explorer.component.scss

Use color to set off ACL tag, plus tooltip(?)

NAS-104637 / 12.0 / NAS-104637

---

src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.html

Always use system_serial instead of license.system.serial

NAS-104636 / 11.3 / NAS-104636-stable

---

src/app/pages/network/interfaces/interfaces-list/interfaces-list.component.ts

Refresh the data when changes have been discarded

---

src/app/helptext/services/components/service-rsync.ts

DOCS-124: Update Services/Rsync help text

---

src/app/components/common/topbar/topbar.component.ts
src/app/components/common/topbar/topbar.template.html

NAS-103606 / 12.0 / NAS-103606

---

src/app/pages/system/alert/alert.component.ts

NAS-104702 / 12.0 / Add warning level field to alert settings

---

src/app/helptext/network/interfaces/interfaces-form.ts

NAS-104473: fix MTU help text format bug (master port)

---

src/app/pages/storage/volumes/manager/manager.component.css
src/app/pages/storage/volumes/manager/manager.component.html
src/app/pages/storage/volumes/volumes-list/volumes-list.component.html

Locked pool displays closed by default, hopefully for a better appearance since; also fixes a layout issue on pool manager when extending an encrypted pool

NAS-104811 / 12.0 / Nas 104811 master

---

src/app/pages/storage/volumes/zvol/zvol-form/zvol-form.component.ts

NAS-104838 / 12.0 / Fix logic for zvol resize validation

---

src/app/pages/services/components/service-s3/service-s3.component.ts

NAS-104808 / 11.3 / Adjust logic to match current api

---

src/app/components/common/layouts/admin-layout/admin-layout.component.ts

NAS-103747 / 11.3 / Fix logic for grabbing console messages

---

src/app/pages/storage/volumes/zvol/zvol-form/zvol-form.component.ts

NAS-104838 / 11.3 / Fix logic for zvol resize validation (by erinix)

---

src/app/components/common/layouts/admin-layout/admin-layout.component.ts

NAS-103747 / 12.0 / Fix logic for grabbing console messages (by erinix)

---

src/app/pages/system/advanced/advanced.component.ts

NAS-104806 / 12.0 / Fix traceback on System Advance page

---

src/app/services/docs.service.ts

NAS-104855 / 11.3 / Remove excess \ before # that is added by translate service

---

src/app/services/docs.service.ts

NAS-104855 / 12.0 / Remove excess \ before # that is added by translate service (by erinix)

---

src/app/pages/common/entity/entity-form/components/form-permissions/form-permissions.component.html

NAS-102485 / 12.0 / Adjust orientation of unix permissions component

---

src/app/pages/storage/volumes/manager/manager.component.html
src/app/pages/storage/volumes/manager/manager.component.ts
src/app/pages/storage/volumes/manager/vdev/vdev.component.html
src/app/pages/storage/volumes/manager/vdev/vdev.component.ts

NAS-104809 / 12.0 / Fix creation of pools so that log/cache/spare should work properly now

---

src/app/helptext/system/certificates.ts
src/app/pages/system/certificates/certificate-acme-add/certificate-acme-add.component.ts

Fixes 'Add ACME Certificate' form problem that prevented authenticator from displaying.

NAS-104865 / 11.3 / Nas 104865

---

src/app/pages/network/interfaces/interfaces-form/interfaces-form.component.ts

NAS-104835 / 11.3 / Don't append a controller label if one is not available

---

src/app/pages/network/interfaces/interfaces-form/interfaces-form.component.ts

NAS-104835 / 12.0 / Don't append a controller label if one is not available (by erinix)

---

src/app/pages/sharing/iscsi/target/target-form/target-form.component.ts

git cherry-pick -x b219f123438f09ca61a2e581ff44d013f2c5e3ee

NAS-104954 / 11.3 / NAS-104954 (by lola27)

---

src/app/helptext/storage/volumes/datasets/dataset-form.ts
src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts

NAS-104588 / 12.0 / Validate against quota sizes smaller than 1G

---

src/app/helptext/storage/volumes/datasets/dataset-form.ts
src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts

NAS-104588 / 11.3 / Validate against quota sizes smaller than 1G (by erinix)

---

src/app/pages/common/entity/entity-tree-table/entity-tree-table.component.html
src/app/pages/common/entity/entity-tree-table/entity-tree-table.component.ts
src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts

Calls acl info method on button click rather than on page load

NAS-104987 / 12.0 / Nas 104987

---

src/app/pages/storage/volumes/volumeaddkey-form/volumeaddkey-form.component.ts
src/app/pages/storage/volumes/volumechangekey-form/volumechangekey-form.component.ts
src/app/pages/storage/volumes/volumecreatekey-form/volumecreatekey-form.component.ts
src/app/pages/storage/volumes/volumerekey-form/volumerekey-form.component.ts

NAS-104805 / 12.0 / Add websocket call info to make the geli pool key management forms work properly

---

src/app/pages/storage/volumes/manager/manager.component.ts

NAS-104804 / 12.0 / Fix issues with extending pools

---

src/assets/i18n/fr.po

Hello,
I made some improvements to the french translation. 
If I missed something or what so ever just tell me.
Thanks for your work !

French translation improvements.

---

src/app/pages/system/tunable/tunable-list/tunable-list.component.ts

NAS-100419 / 12.0 / Add multi delete to tunables

---

src/assets/videos/README.md

NAS-101521 / 12.0 / Add directory and readme file for uploading embedded videos to

---

src/app/core/services/preferences.service.ts
src/app/pages/vm/vm-wizard/vm-wizard.component.ts

Saves in preferences the previous values of NIC type and NIC attach (on the VM wizard) and used these as default values if they are available.

NAS-102783 / 12.0 / NAS-102783 Default selections for VM Wiz

---

src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts

NAS-105081 / 12.0 / Simplify name, populate used and available on datasets

---

src/app/helptext/directoryservice/activedirectory.ts
src/app/helptext/directoryservice/kerberosrealms-form-list.ts
src/app/helptext/directoryservice/ldap.ts
src/app/helptext/global-helptext.ts
src/app/helptext/sharing/afp/afp.ts
src/app/helptext/sharing/nfs/nfs.ts
src/app/helptext/sharing/smb/smb.ts
src/app/pages/directoryservice/activedirectory/activedirectory.component.ts
src/app/pages/directoryservice/kerberosrealms/kerberosrealms-form/kerberosrealms-form.component.ts
src/app/pages/directoryservice/ldap/ldap.component.ts
src/app/pages/services/components/service-ftp/service-ftp.component.ts
src/app/pages/services/components/service-smb/service-smb.component.ts
src/app/pages/services/components/service-ssh/service-ssh.component.ts
src/app/pages/sharing/afp/afp-form/afp-form.component.ts
src/app/pages/sharing/nfs/nfs-form/nfs-form.component.ts
src/app/pages/sharing/smb/smb-form/smb-form.component.ts

NAS-104011 / 12.0 / Rename Advanced/Basic "Mode" to "Options", move text to global helptext

---

src/app/components/common/dialog/task-manager/task-manager.component.ts
src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.css
src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.html
src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.ts
src/app/pages/reportsdashboard/components/report/report.component.html
src/app/pages/reportsdashboard/components/report/report.component.ts
src/app/pages/storage/snapshots/snapshot-list/components/snapshot-details.component.ts
src/app/services/locale.service.ts

For TN 12, makes timezone changes propagate (using the locale service) to the task manager, form scheduler, reports, snapshot details

NAS-105133 / 12.0 / Nas 105133

---

.gitignore
package.json

NAS-101669 / 12.0 / Generate licenses json file in build

---

src/app/helptext/vm/vm-wizard/vm-wizard.ts
src/app/pages/vm/vm-form/vm-form.component.ts
src/app/pages/vm/vm-list/vm-list.component.ts
src/app/pages/vm/vm-wizard/vm-wizard.component.ts

Update VM table, form and wizard to use new API methods for stopping and powering off a VM

NAS-105049 / 12.0 / Nas 105049

---

src/app/pages/common/entity/entity-table/entity-table.component.ts
src/app/pages/storage/disks/disk-list/disk-list.component.ts
src/app/pages/storage/import-disk/import-disk.component.ts

Auto-updates disk list and the select field on import-disk form when a disk is attached or removed

NAS-101464 / 12.0 / Nas 101464

---

src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
src/app/pages/storage/volumes/zvol/zvol-form/zvol-form.component.ts

NAS-104011 / 12.0 / Use the global "Advanced/Basic Options" for dataset and zvol forms

---

src/app/helptext/services/components/service-ssh.ts
src/app/pages/services/components/service-ssh/service-ssh.component.ts

NAS-105023 / 12.0 / Add weak-ciphers multiselect to SSH config

---

src/app/views/sessions/signin/signin.component.ts

NAS-102357 / 12.0 / Rename "passive" to "standby" on login page

---

src/app/core/components/widgets/widgetcpu/widgetcpu.component.ts

Update temperatures in cpu widget

NAS-104842 / 11.3 / NAS-104842

---

src/app/core/components/widgets/widgetpool/widgetpool.component.html

Ignore identifier value in pool widget.

NAS-104864 / 11.3 / NAS-104864

---

package.json
src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.html
src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.ts
src/app/pages/reportsdashboard/components/report/report.component.html
src/app/pages/reportsdashboard/components/report/report.component.ts
src/app/pages/storage/snapshots/snapshot-list/components/snapshot-details.component.ts

Fix timezone issues in form scheduler, reports, snapshots. Thanks to Aaron Ervin for extra help

NAS-105008 / 11.3 / Nas 105008

---

src/app/helptext/network/interfaces/interfaces-form.ts
src/app/pages/network/interfaces/interfaces-form/interfaces-form.component.ts

NAS-104995
(cherry picked from commit d5337e79b8e18ee8ec6fe3456d7a4d79d524d762)

NAS-104995 / 12.0 / Remove requirement for name on interface form

---

src/app/helptext/network/interfaces/interfaces-form.ts
src/app/pages/network/interfaces/interfaces-form/interfaces-form.component.ts

NAS-104995 / 11.3 / Remove requirement for name on interface form

---

src/app/pages/storage/volumes/volume-status/volume-status.component.ts

NAS-105061 / 12.0 / Fix name of device when removing disk

---

src/app/helptext/storage/volumes/volume-import-wizard.ts
src/app/pages/storage/volumes/volume-import-wizard/volume-import-wizard.component.ts

NAS-105124 / 12.0 / Fix labels for pool import wizard job dialog

---

src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts

NAS-104696 / 12.0 / Check job description for whether or not the scrub is actually complete

---

src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts

NAS-104696 / 11.3 / Check job description for whether or not the scrub is actually complete (by erinix)

---

src/app/helptext/storage/volumes/volume-import-wizard.ts
src/app/pages/storage/volumes/volume-import-wizard/volume-import-wizard.component.ts

NAS-105124 / 11.3 / Fix labels for pool import wizard job dialog (by erinix)

---

src/app/pages/storage/volumes/volume-status/volume-status.component.ts

NAS-105061 / 11.3 / Fix name of device when removing disk (by erinix)

---

src/app/core/components/widgets/widgetpool/widgetpool.component.html

Ignore identifier value in pool widget.

NAS-104864 / 12.0 / NAS-104864 (by dszidi)

---

src/app/core/components/widgets/widgetcpu/widgetcpu.component.ts

Update temperatures in cpu widget

NAS-104842 / 12.0 / NAS-104842 (by dszidi)

---

package.json

Rollback to known good translate-extract version

---

src/app/helptext/directoryservice/idmap.ts
src/app/pages/directoryservice/idmap/idmap.component.ts

These fields are already present in the new idmap implementation in v 12

NAS-105210 / 11.3 / NAS-105210 Add missing idmap fields

---

src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts

NAS-101266 / 12.0 / Rename "Recovery Key" menu item to "Manage Recovery Key"

---

src/app/pages/storage/snapshots/snapshot-add/snapshot-add.component.ts
src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts

NAS-105215 / 11.3 / Fix hour format for manual snapshot creation

---

src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts

NAS-105215 / 12.0 / Fix hour format for manual snapshot creation (by erinix)

---

src/app/helptext/directoryservice/kerberossettings.ts

NAS-105209 / 11.3 / Use FreeBSD man page link for kerberos settings helptext

---

src/app/helptext/directoryservice/kerberossettings.ts

NAS-105209 / 12.0 / Use FreeBSD man page link for kerberos settings

---

src/app/helptext/system/update.ts
src/app/pages/system/update/update.component.ts

Matches HA update to non-HA in that you can download an update, install it later (this is the solution mentioned in the ticket comments). In testing, need to pay attention to 'Apply Pending Updates' on HA systems to make sure it's doing what I think it is doing.

NAS-103803 / 11.3 / Nas 103803

---

src/app/helptext/task-calendar/snapshot/snapshot-form.ts

- Port text changes as needed to 12.0 branch.

NAS-104998 / 11.3 / NAS-104998: Synchronize UI help text and 11.3 docs

---

src/app/helptext/task-calendar/snapshot/snapshot-form.ts

Cherry-picked #3728 and made one adjustment as needed.

NAS-104998 / 12.0 / NAS-104998: Synchronize UI help text and docs (12.0 port)

---

src/app/pages/system/certificates/certificate-list/certificate-list.component.ts

NAS-105125 / 12.0 / Pass in dialog service to fix error handling for certificate delete

---

src/app/helptext/system/update.ts
src/app/pages/system/update/update.component.ts

For v. 12 - Allow update to be downloaded only on HA, combine functions

NAS-103803 / 12.0 / NAS-103803

---

src/app/pages/system/certificates/certificate-list/certificate-list.component.ts

NAS-105125 / 11.3 / Pass in dialog service to fix error handling for certificate delete (by erinix)

---

src/app/helptext/system/update.ts
src/app/pages/system/update/update.component.ts

Removes train comparison logic. I added this to NAS-103083 (which should be merged first) to avoid merge conflicts

NAS-105195 / 12.0 / Nas 105195 v12

---

src/app/pages/system/update/update.component.ts

Remove comparison logic for trains - Middleware will return only valid choices

NAS-105195 / 11.3 / Nas 105195 v11

---

src/app/helptext/task-calendar/replication/replication-wizard.ts
src/app/helptext/task-calendar/replication/replication.ts

- Re-investigate field behavior and update field names and help text for the Replication Task Wizard and Advanced Replication Creation screens.

NAS-105113 / 12.0 / NAS-105113: Adjust field names and expand help text in Replication Tasks (12 port)

---

src/app/services/app-loader/app-loader.component.html
src/app/services/app-loader/app-loader.component.ts

Fixes a display error in app loader. The observable seemed to not work, starting around the time we switched to ws ???

NAS-105280 / 12.0 / Nas 105280

---

src/app/pages/system/certificates/certificate-list/certificate-list.component.ts

NAS-105125 / 12.0 / Error message can also appear in the progress on a failed state

---

src/app/pages/system/certificates/certificate-list/certificate-list.component.ts

NAS-105125 / 11.3 / Error message can also appear in the progress on a failed state (by erinix)

---

src/app/helptext/services/components/service-s3.ts
src/app/pages/services/components/service-s3/service-s3.component.ts

This reverts commit 4a9be897d357516026205b677410393a5f40ea49.

Revert "Pop up warning message when a user selects any dataset for S3"

---

src/app/pages/storage/volumes/manager/manager.component.ts

(middleware just flattens all stripes anyway it seems)
NAS-105144

NAS-105144 / 12.0 / Do not show the disks error message when extending with stripes

---

src/app/pages/storage/volumes/manager/manager.component.ts

(middleware just flattens all stripes anyway it seems)
NAS-105144

NAS-105144 / 11.3 / Do not show the disks error message when extending with stripes (by erinix)

---

src/app/helptext/services/components/service-s3.ts
src/app/pages/services/components/service-s3/service-s3.component.ts

This reverts commit 1253c1af25cdb017e51550bd3a23b2aa2105dd18.

NAS-101186 / 12.0 / Revert "Revert "Pop up warning message when a user selects any dataset for S3"

---

src/app/helptext/services/components/service-s3.ts
src/app/pages/services/components/service-s3/service-s3.component.ts

NAS-101186 / 11.3 / Pop up warning message when a user selects any dataset for S3

---

src/app/pages/storage/volumes/volume-import-wizard/volume-import-wizard.component.ts

NAS-105199 / 11.3 / Reset the array of importable volumes upon success response to prevent double options

---

src/app/pages/storage/volumes/volume-import-wizard/volume-import-wizard.component.ts

NAS-105199 / 12.0 / Reset the array of importable volumes upon success response to prevent double options (by erinix)

---

src/app/pages/system/bootenv/bootenv-attach/bootenv-attach-form.component.ts

NAS-105302 / 11.3 / Remove nopercent for boot environment attach

---

src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.css
src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.html
src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.ts
src/app/pages/task-calendar/replication/replication-form/replication-form.component.ts
src/app/pages/task-calendar/snapshot/snapshot-form/snapshot-form.component.ts

Adds descriptions for presets on Form Scheduler; hides 'Begin' and 'End' settings on Replication form, Periodic Snapshot Tasks form, unless the chosen setting is Hourly or Custom

NAS-105253 / 11.3 / Nas 105253

---

src/app/pages/system/bootenv/bootenv-attach/bootenv-attach-form.component.ts

NAS-105302 / 12.0 / Remove nopercent for boot environment attach (by erinix)

---

src/app/appMaterial.module.ts
src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.css
src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.html
src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.ts
src/app/pages/task-calendar/replication/replication-form/replication-form.component.ts
src/app/pages/task-calendar/snapshot/snapshot-form/snapshot-form.component.ts

Update form scheduler for v 12

NAS-105523 / 12.0 / NAS-105523

---

src/app/pages/common/entity/entity-job/entity-job.component.ts

Fixes entity job dialog so that it monitors progress again

NAS-105334 / 12.0 / Nas 105334

---

src/app/core/classes/system-profiler.ts
src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.html
src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.ts

Enclosure UI can now handle when vdev child is present but no device is listed (status=REMOVED)
Enclosure UI now informs if the pool is not healthy.

NAS-105143 / 11.3 / NAS-105143

---

src/app/pages/storage/snapshots/snapshot-add/snapshot-add.component.ts
src/app/pages/storage/snapshots/snapshot-list/snapshot-list.component.ts

NAS-105358 / 12.0 / Hide boot pool from snapshots

---

src/app/pages/task-calendar/snapshot/snapshot-form/snapshot-form.component.ts

NAS-105289 / 12.0 / Add required marker and reasonable default to periodic snapshot task

---

src/app/pages/storage/volumes/volume-status/volume-status.component.ts

Fix time display when a pool-scan runs (scrub or resilver)

NAS-104992 / 11.3 / NAS-104992 

---

src/app/components/common/layouts/admin-layout/admin-layout.component.ts
src/app/components/common/topbar/topbar.component.ts

Make sure main content area left margin updates when sidenav is toggled

Sidenav Fix for Master

---

src/app/pages/storage/storage.routing.ts
src/app/pages/storage/volumes/manager/manager.component.html
src/app/pages/storage/volumes/manager/manager.component.ts
src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts

NAS-100331 / 12.0 / Rename extend pool to "add vdevs"

---

src/app/pages/storage/volumes/volume-status/volume-status.component.ts

NAS-104992 / 12.0 / NAS-104992 

---

src/app/app.routes.ts
src/app/pages/common/entity/entity-form/entity-form-embedded.component.html
src/app/pages/preferences/page/forms/customtheme/customtheme.component.css
src/app/pages/preferences/page/forms/customtheme/customtheme.component.html
src/app/pages/preferences/page/forms/customtheme/customtheme.component.ts
src/app/pages/preferences/preferences.module.ts
src/app/pages/preferences/preferences.routing.ts
src/assets/styles/themes/ix-blue.scss

Fixes breadcrumb and button label for custom theme page, per the ticket AND...
adds a bunch of translation tags and pipes, fixes some layout issues too

NAS-104002 / 12.0 / Nas 104002

---

src/app/pages/preferences/page/forms/general-preferences-form.component.ts

The ticket mentions Save vs Submit buttons, already addressed, I think, by https://jira.ixsystems.com/browse/NAS-104006

NAS-103999 / 12.0 / NAS-103999 Settings to preferences

---

src/app/core/components/widgets/widgetmemory/widgetmemory.component.html
src/app/core/components/widgets/widgetmemory/widgetmemory.component.ts
src/app/pages/dashboard/dashboard.html

Inform user if ecc memory is installed

NAS-103202 / 12.0 / NAS-103202
