src/app/pages/vm/vm-cards/vm-cards.component.css
src/app/pages/vm/vm-cards/vm-cards.component.html
src/app/pages/vm/vm-cards/vm-cards.component.ts

Removed background image from vm-cards to avoid copyright issues. We can replace them with suitable images later. Also added label to power button. This is a more effective way to communicate the button's toggle state than the previous color change method..

Usability improvement: Added a label to vm power button

---

src/app/app.module.ts
src/app/pages/common/error-dialog/error-dialog.component.html
src/app/pages/common/error-dialog/error-dialog.component.scss
src/app/pages/common/error-dialog/error-dialog.component.ts
src/app/services/dialog.service.ts
src/assets/styles/styles.css

I completed https://bugs.freenas.org/issues/24180
For example, this error dialog modal can be called by the following code:
this.dialogService.errorReport("title", "description", "traceback -- error").subscribe((res) => { });

Adding an error dialog component, Ticket: #24180

---

src/app/services/theme/theme.service.ts

The way to see if the bug is fixed.. Take a fresh system that has never run the theme changer. (So the variable is never set)... It should pick a default of ix-systemblue.. With the Icon working :)
Also.. Theme changeing should continue to work.. after saved.

Themservice default fix

---

src/app/app.routes.ts
src/app/components/common/topbar/topbar.component.ts
src/app/pages/system/update/update.component.ts
src/app/services/ws.service.ts
src/app/views/others/others.module.ts
src/app/views/others/others.routing.ts
src/app/views/others/shutdown/shutdown.component.html
src/app/views/others/shutdown/shutdown.component.ts
src/app/views/sessions/signin/signin.component.html
src/app/views/sessions/signin/signin.component.ts

Make reboot page show up on reboot events, add shutdown page for
shutting down, hide login page while websockets are not available and
add loader to update pages
Ticket: #27357
#27453
#27068
#27444

Fixes for update/shutdown/reboot/login pages

---

src/app/pages/system/ca/ca-intermediate/ca-intermediate.component.ts
src/app/pages/system/ca/ca-internal/ca-internal.component.ts
src/app/pages/system/certificates/certificate-csr/certificate-csr.component.ts
src/app/pages/system/certificates/certificate-internal/certificate-internal.component.ts

Update `Common Name` tooltip for applicable System/CA and System/Certificates forms.
The tooltip now warns the user to use a unique common name for each "part" of a chain of certificates,
as per engineering feedback.
Build test: no compile errors.

Resolving Redmine issue #24593, Part 2:

---

tests/boot.exp

* After changes "Enter an option from 1-12:" no longer displays in jenkins console.
* Now we have to look for "Enter an option from 1-11:" to exit expect properly.

Fixes boot expect script

---

src/app/pages/vm/vm-cards/vm-cards.component.html
src/app/pages/vm/vm-cards/vm-cards.component.ts

VM card VNC button is now disabled if there is no WEB VNC device found. Unable to add tooltip with warning message due to this issue. https://github.com/angular/material2/issues/7953

VNC disabled when no WEB VNC device found.

---

src/app/pages/vm/vm-cards/vm-cards.component.html

Found a workaround for ticket #28586. Also added tooltips to Devices and Edit buttons on vm cards. Edit button is now disabled if VM is running

FIX #28586

---

src/app/pages/common/entity/entity-table/entity-table-add-actions.component.ts

Reverted template on entity-table-add-actions.component to previous state. Spinner is back for everything

Entity table's spinner for all the things

---

src/app/pages/vm/devices/device-list/device-list.component.ts

https://stackoverflow.com/questions/39787038/how-to-manage-angular2-expression-has-changed-after-it-was-checked-exception-w

fix vm title on device list page. fixed a traceback as well.

---

src/app/pages/storage/disks/disks-list/disks-list.component.html
src/app/pages/storage/disks/disks-list/disks-list.component.ts
src/app/pages/storage/volumes/volume-unencryptimports/volume-unencryptimport.component.ts
src/app/pages/storage/volumes/volumes-list/volumes-list.component.html
src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
src/app/pages/storage/volumes/volumeunlock-form/volumeunlock-form.component.ts

Got the API volume/id/detach    body:  JSON.stringify( {  label:  disk.disk_name } )
This works.  the api retuns and says "Disk successfully detached"
But.. I see no way to then detect this.. The getting disks by pool.. The disk I detached still comes up?
I notice in disks.query There's no status in da1 vs da2 (I detached da2 in my pool).  Same is true of v1.0/storage/disks
So.. How do you detech the status that this api toggled?
OH.. I removed the uneeded Succesfully Un locked volume blah blah.. because you can see the difference in the parent list when itupdates (Not locked)

Faeture 28712 sunday

---

src/app/components/common/dialog/consolepanel/consolepanel-dialog.component.html
src/app/components/common/dialog/consolepanel/consolepanel-dialog.component.scss
src/app/components/common/dialog/consolepanel/consolepanel-dialog.component.ts

Ticket: #31380
Instructions for console are on the tooltip where it is launched, but since the console is active throughout the app, I added dynamic instructions to the console.

Make dynamic instructions for console dialog

---

src/app/pages/jails/storages/storage-form/storage-form.component.ts

- Rewrite message to reflect that a directory named in "Destination" that does
not exist is automatically created.
- Local build testing: no issues.

Update Jail mount point "Destination" tooltip.

---

src/app/pages/common/entity/entity-form/entity-form.component.scss
src/app/pages/common/entity/entity-task/entity-task.component.html
src/assets/styles/themes/ix-blue.scss

Moved entity-forms .mat-card.form-card max-width rule to global css files. Added .form-card class to entity-task's mat-card element so both form types will have the same layout property.

Simple form width adjustment via css

---

src/app/core/components/viewchart/viewchart.component.ts
src/app/core/components/widgets/widget/widget.component.html
src/app/core/components/widgets/widgetcpuhistory/widgetcpuhistory.component.html
src/app/core/components/widgets/widgetloadhistory/widgetloadhistory.component.html
src/app/core/components/widgets/widgetmemoryhistory/widgetmemoryhistory.component.html
src/app/core/components/widgets/widgetpool/widgetpool.component.html
src/app/pages/dashboard/dashboard.html
src/app/services/stats.service.ts
src/assets/styles/egret_overrides.css

Fixed out of bounds problem with widget cards by disabling the back face of the flip card via ngIf. Also added a pipe to legend time to avoid numbers with more than 2 decimal places. Relaxed the frequency at which stats service was polling as it seems to have been a little bit too aggressive and was slowing the page down.

Fixed out of bounds problem with widget cards

---

src/app/components/common/topbar/topbar.component.ts
src/app/components/common/topbar/topbar.template.html
src/app/views/sessions/signin/signin.component.html
src/app/views/sessions/signin/signin.component.ts

Add confirm dialogs to options to switch to legacy UI

---

src/app/pages/task-calendar/cloudsync/cloudsync-form/cloudsync-form.component.ts

- Update the "Home Directory" name and related tooltip to better reflect the field's functionality/role in the task.
- NPM testing: no issues

Update unclear field name and tooltip:

---

src/app/pages/vm/devices/device-edit/device-edit.component.html
src/app/pages/vm/devices/device-edit/device-edit.component.scss
src/app/pages/vm/devices/device-edit/device-edit.component.ts
src/assets/styles/themes/ix-blue.scss

The device-edit component was using only the template from entity-form and nothing else. When fieldsets were added to entity-form, this caused some breakage. Wasn't noticed since technically this component is not using entity-form, only the template. Copied scss and html files from entity-form so device-edit could safely have it's own modifications without causing trouble. Wrapped fieldConfig inside a fieldset so look and feel and features can be consistent with entity-form. At some point this and all other forms should be converted to entity-form.

Fixed breakage with device-edit form

---

src/app/pages/network/configuration/configuration.component.ts

Advise to enter an IPv6 address for the IPv6 Default Gateway

Fix tooltip for the IPv6 Default Gateway

---

src/app/components/common/breadcrumb/breadcrumb.component.css
src/app/components/common/topbar/topbar.template.html
src/app/pages/vm/vm-cards/vm-cards.component.css
src/app/pages/vm/vm-cards/vm-cards.component.html

Ticket: #35281
Fix hamburger menu tooltip from going off screen when sidenav is closed
VM page - fixes broken alignment of fab button on firefox. adjusts on webkit
Makes VM header line up on smaller screens
Shrinks copyright text in breadcrumb area when screen gets small

Fix css in top bar, breadcrumb area, on VM page

---

src/app/pages/common/entity/entity-job/entity-job.component.html
src/app/pages/directoryservice/idmap/idmap.component.html
src/app/pages/task-calendar/cloudsync/cloudsync-form/cloudsync-form.component.html
src/assets/styles/themes/ix-blue.scss

Ticket: #36828
- Buttons on idmap page - aligns and flattens
- Buttons on CloudSync page - flattens
- Button and tooltip on Add Replication form - fixes alignment
- Makes the slider on the Shell pick up theme color
- Replaces the ink-bar (highlight) for the tabs on the Sharing/ISCSI with bottom borders for each tab, since the ink-bar feature won't wrap for two rows of tabs

Css fixes misc

---

src/app/pages/common/entity/entity-table/entity-table.component.ts

Ticket: #33954
I think the filter works great - a few keystrokes usually gets you down to just a result or two. One improvement is that it should be case insensitive. We could easily make the filter ignore booleans, but I think this might cause more headaches than it solves.

Make filter function case insensitive

---

src/app/pages/common/entity/entity-table/entity-table.component.html
src/app/pages/storage/volumes/manager/manager.component.html
src/app/pages/storage/volumes/manager/vdev/vdev.component.html

Ticket: #37690
- I reset the entity table selection method from check box to multi row last week (to make it possible to select by clicking anywhere on the row), but should have known better. It appears to work at first, but doesn't really. This rolls it back.
- This branch also adds the ability to click on the labels of the column-selecting check boxes (on the Users page, for example) to check the box.

Fix entity table checkboxes 37690

---

src/app/pages/common/entity/entity-table/entity-table.component.ts

Ticket: #37710
Fixes the filter on entity tables. The newly added column-select check boxes redefined the data set that the filter was using, so it needed to be restored.

Fix for filter function broken by checkboxes on entity pages

---

package.json
src/assets/styles/fn-styles.css

Ticket: #37666 (also addresses #37453). 
Removes ellipsis on text overflow for data tables.
With horizontal scroll bars on data tables, there are few reasons to keep the ellipsis on text overflow, and the ellipsis is causing a new problem - making data invisible until user scrolls over - on TrueOS, at least). 
Ticket 37453 reports shifting check boxes, which I haven't been able to duplicate but which the ticketer says is solved by removing the ellipsis (which was a known issue with the ellipsis in the past).

Remove ellipsis on overflow to allow data to show

---

src/assets/styles/themes/ix-blue.scss

Ticket: #38605
- Fix another gap in entity table, this one added by the horz scroll bar; fixed by filling in the background color

Fill in gap above scroll bar with background color

---

src/app/components/common/topbar/topbar.component.ts
src/app/components/common/topbar/topbar.template.html

Ticket: #39095
Fix for glitch in sidenav when it goes from collapsed state to full - the bug is that it covers up the main toggle button. This fixes that and also hides the little arrow button when it isn't useful, to keep it from getting the menu out of sync.

Hide collapsed toggle when sidenav is offscreen to keep it from getting out of sync

---

src/assets/styles/themes/ix-blue.scss

Ticket: #40206
Adds a CSS rule to color 'pseudo-checkboxes' which appear without the right theme color in SMART Tests

Add a rule to get checkboxes on SMART tests to pick up theme color

---

src/app/components/common/navigation/navigation.component.ts
src/app/components/common/navigation/navigation.template.html

Ticket: #41760
Causes the scrollbar on sidenav to update on every menu item click. Fixes a problem where, if he scrollbar isn't needed on page load, then it won't automatically appear when the menu expands and it is needed.

force scrollbar to refresh on every menu click

---

src/app/views/others/shutdown/shutdown.component.css
src/app/views/others/shutdown/shutdown.component.html
src/app/views/others/shutdown/shutdown.component.ts

Ticket: #39563
Adds a fade-to-black 60 seconds after the user clicks to shut down the system

add fadeout to shutdown screen

---

src/app/pages/common/info-dialog/info-dialog.component.scss

Ticket: #38600
Add a bit of space on info dialog to allow for the update warning about switching trains, Tested on Ffx and Chromium on Ubuntu and TrueOS

increase height of info panel to make room for train err message

---

src/app/core/components/widgets/widgetnetinfo/widgetnetinfo.component.ts
src/app/core/services/api.service.ts

WidgetNetInfo now gets the UI ip from `interfaces.websocket_interface`. This should avoid problems when ui is accessed via DNS instead of ip address.

Fix for dashboard on FreeNAS systems that are accessed via DNS

---

src/app/pages/services/services.component.ts
src/app/pages/system/alertservice/alert-service/alert-service.component.html
src/app/services/app-confirm/app-confirm.component.ts
src/app/services/app-confirm/app-confirm.service.ts
src/assets/styles/themes/ix-blue.scss

Ticket: #42845
Formats dialog that pops up from service-stop button - conforms it to material standards
Fixes a button on Alert Service page that is way too transparent when disabled
Brings theme colors to progress bars

restyle app-confirm dialog

---

src/app/pages/shell/shell.component.ts

explicitly set cursor focus in shell to true

---

src/app/pages/vm/vm-cards/vm-cards.component.ts

In the VmCardsComponent some extra properties were added to the VmProfile type that were meant for UI use only. These were being sent to middleware and causing errors. There is now a method that strips these properties before sending new VmProfile data to middleware.

Fix Vm Cards Edit and Save

---

src/assets/styles/themes/ix-blue.scss

Ticket: #35272
Uses CSS to remove up/down arrows on number input fields

Removes arrows from number fields for moz and webkit

---

src/app/pages/guide/guide.component.ts

Ticket: #44641
Removes the specific reference to 'http' to perhaps make our url more flexible; This will not, however, let an unencrypted link through a security filter.

adjust safeUrl settings

---

src/app/app.component.ts
src/app/core/components/viewchart/viewchart.component.ts
src/app/core/components/viewchartdonut/viewchartdonut.component.ts
src/app/core/components/viewchartline/viewchartline.component.ts
src/app/pages/vm/vm-cards/vm-summary.component.css
src/app/pages/vm/vm-cards/vm-summary.component.html
src/app/pages/vm/vm-cards/vm-summary.component.ts

Also removed cpu uage and pool usage charts since they were not appropriate and there wasn't enough room to accommodate them anyway. Changed legend location in viewchartdonut. You can now set legendPosition property to place legend to top or to the right.

Fixed labels on virtual memory chart in vm-summary in table view.

---

src/app/pages/account/users/user-form/user-form.component.ts

Updated the username tooltip to include up to 16  characters in response to bug 52116. 

---

src/app/pages/sharing/nfs/nfs-form/nfs-form.component.ts

Passed build test with no issues.
Related to: https://redmine.ixsystems.com/issues/23923#change-362826.
Added a correct example of an IP address/hostname to the Authorized Hosts and IP addresses field in response to a customer adding an incorrect address  (192.168.2.1/24).

Added an example for the authorized hosts and ip addresses field.

---

src/app/pages/common/entity/entity-dialog/dialog-form-configuration.interface.ts
src/app/pages/common/entity/entity-dialog/entity-dialog.component.html
src/app/pages/common/entity/entity-dialog/entity-dialog.component.ts
src/app/pages/preferences/page/forms/general-preferences-form.component.ts
src/app/pages/system/update/manualupdate/manualupdate.component.ts
src/app/pages/system/update/update.component.ts

- Rename the dialog box.
- Add warning.
- Remove unnecessary option.
- Add helptext
- Rename Buttons to conform with naming conventions
- Rename checkbox in Settings/Preferences.
- Add help text to checkbox.
- Alter "Export Password Secret Seed" to read "Include Password Secret Seed".
- Clean up whitespace.
- NPM testing: no issues.

Update text related to "Save System Configuration" dialog:

---

src/app/pages/account/users/user-form/user-form.component.ts

The validator forcing the max password length to <= 9 characters was
removed in 94e555c96f17bcb10f466948f5f1203ebea619ff, but the tooltip
was not. This change adjusts the tooltip accordingly.

Remove tooltip stating password must be <= 9 chars

---

src/app/pages/system/update/manualupdate/manualupdate.component.ts
src/app/pages/system/update/update.component.ts

show Save Config dailoge when user clicks  INSTALL MANUAL UDPATE FILE
(cherry picked from commit 7b2c852a8dbfc8f3f8d83aebde882b01dd197e26)

Remove redundant "SAVE CONFIG" button in System/Update/Manual Update

---

src/app/pages/reportsdashboard/components/report/report.component.html

Moved click() event handler in report component html template from icon element to the button element.
(cherry picked from commit 49e60917efdf5522e1d43d490d6f8639ee50788a)

Fixed regression with Firefox. 

---

src/app/pages/system/update/manualupdate/manualupdate.component.ts

(cherry picked from commit be239bee1a8b25bece99c339e860dd3e4d13f2dd)

fix Misspelled "successful in the Restart dialogue.

---

src/app/components/common/lineChart/lineChart.component.ts
src/app/pages/reportsdashboard/components/report/report.component.html

Reports analytics elements (min,max,avg,total) in elements gracefully degrade when no data is available. Hard to test but I happened to find it when trying to display disk io-time

Found a problem where legend analytics would cause endless loop if no data

---

src/app/pages/common/confirm-dialog/confirm-dialog.component.css

#62790 - Overflow shows up only when twelve or more lines get pushed to the content div on confirm dialog. Otherwise, seems not to bother all our regular confirm dialogs.

Add overflow to content div on confirm dialog

---

src/app/pages/common/entity/entity-tree-table/entity-tree-table.component.html
src/assets/styles/themes/ix-blue.scss

Ticket #61641
Fixes alignment issues on pools data-tree - keeps name col from text-wrapping, but allows comments to wrap. Hopefully the best set of compromises

61641 align pool data tree

---

src/app/pages/common/entity/entity-tree-table/entity-tree-table.component.html
src/assets/styles/themes/ix-blue.scss

Ticket #61641
Fixes alignment issues on pools data-tree - keeps name col from text-wrapping, but allows comments to wrap. Hopefully the best set of compromises

61641 alignment issues on pools tree for 11.2 stable

---

src/app/pages/common/entity/entity-form/components/tooltip/tooltip.component.ts

Ticket: #62550 and duplicates
Positions tooltips and dynamically resizes some of them to keep all of them within the margins of the card where they originate; to fix a bug where tooltips sometimes get cut off at the margin or padding.

position and size tooltips to stay within margins

---

src/app/pages/system/update/update.component.ts

Sets the train of current OS as default, to fix issue where config file from older version causes wrong train options to load
Adds ‘MINOR_UPGRADE’ and ‘MAJOR_UPGRADE’ to the legit upgrade list, which seems consistent with 11.1
Fixes it so if user switches to another train, but then switches back before actually updating, the display resets and then reloads properly
Moves the first check for updates to later in ngOnInit, AFTER the value of this.trains is set; otherwise, the update check runs on a default value which can be wrong, at least when you have loaded a config file from an older version.

63636 update page for 11.3

---

src/assets/styles/themes/ix-blue.scss

#66214 for 11.2 stable
Color bands to visually separate pool tree list

add color bands to pool table

---

src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.css

Ticket: #68115 - Fixes just the cursor on cron fields; the highlight is okay in 11.2 stable

recolor cursor on cron fields

---

src/assets/styles/themes/ix-blue.scss

Ticket #59490
Makes invalid fields more visible (we were accidentally overwriting the red color on the label)
The material spec for helping the visually impaired is to have the red label and underline, and maybe a warning message ('email is required', etc.) We could consider adding messages, as much for catching the eye as for their content.

59490 for 11.3

---

src/assets/styles/themes/ix-blue.scss

Ticket #59490
Makes invalid fields more visible (we were accidentally overwriting the red color on the label)
The material spec for helping the visually impaired is to have the red label and underline, and maybe a warning message ('email is required', etc.) We could consider adding messages, as much for catching the eye as for their content.

edit style for more visible error state

---

src/app/pages/system/ca/ca-add/ca-add.component.ts
src/app/pages/system/certificates/certificate-add/certificate-add.component.ts

Ticket: #66925
Front end is already fixed to work with middleware to display error messages about key strength. This PR proposes only a tooltip modification.

modify cert and ca tooltips for private key

---

src/app/pages/storage/volumes/zvol/zvol-form/zvol-form.component.ts

Ticket: #69168
(cherry picked from commit bf94ac3ad73399151a2c8a7fedc453c97f774b49)

Preserve original values so that zvol size remains consistent if the user does not try to change it.

---

src/assets/styles/themes/ix-blue.scss

Changed mat-option hover style to use --fg2 rules from theme palette

Fixed mat-option hover and focus having same styles (master)

---

src/assets/styles/themes/ix-blue.scss

Changed mat-option hover style to use --fg2 rules from theme palette

Fixed mat-option hover and focus having same styles (stable)

---

src/app/pages/jails/jail-edit/jail-edit.component.html
src/app/pages/jails/jail-edit/jail-edit.component.ts

Added isReady property to jail-edit. This variable makes the expansion panels active and is set during AfterViewInit lifecycle hook. This was causing problems in iOS.

jail-edit on iOS Fix (master)

---

src/app/services/stats.service.ts

Changed how stats service formats the start and end times for API call. Using epoch time previously led to null values and some sort of clock mismatch. Switching to 'now-xxx' syntax and limiting the end param to 20 seconds from present fixes things.

Fixed trailing zeros charts on front page dashboard (master)

---

src/app/services/stats.service.ts

Changed how stats service formats the start and end times for API call. Using epoch time previously led to null values and some sort of clock mismatch. Switching to 'now-xxx' syntax and limiting the end param to 20 seconds from present fixes things.

 Fixed trailing zeros charts on front page dashboard (stable)

---

src/app/pages/system/CloudCredentials/cloudcredentials-form/cloudcredentials-form.component.ts

- Rename fields to Disable Endpoint Region and Use Signature Version 2.
- Add simple help text describing function and usage of these fields.
- Local yarn build test: no issues.

63483: Add help text to new Cloud Credentials/S3 fields (cherry-pick to 11.2-stable):

---

src/app/pages/system/CloudCredentials/cloudcredentials-form/cloudcredentials-form.component.ts

- Rename fields to Disable Enpoint Region and Use Signature Version 2.
- Add simple help text describing function and usage of these fields.
- Local yarn build test: no issues.

63483: Add help text to new Cloud Credentials/S3 fields:

---

src/assets/styles/reset.css

Ticket: #72635
(cherry picked from commit 05ccba54beca4116f15a517cac5b609940b34d10)

Add css styling to make <b> and <i> tags in tooltips work again

---

src/app/helptext/vm/vm-wizard/vm-wizard.ts

(cherry picked from commit 4f4e4ba0ea57dec75f0cb686418ce193cf86172e)
As per [Warrens comment](https://github.com/freenas/freenas-docs/pull/616#pullrequestreview-195066552)

Make Hard Disks VM labels more concise (11.2-stable).

---

src/app/core/components/widgets/widgetcputemps/widgetcputemps.component.ts
src/app/core/services/api.service.ts
src/app/pages/dashboard/dashboard.component.ts
src/app/services/stats.service.ts
src/app/services/ws.service.ts

- Fixes "too many concurrent requests" tracebacks
- Merged cpu temp calls into a single call
- Polling adjusted to happen every 4 seconds (was a minute before due to typo)
- All dashboard widgets now load more quickly and reload more often
- dashboard page  sends StatsKillAll message to ensure stats service stops polling once the user has left the page.

Dashboard performance improvements

---

src/app/components/common/layouts/admin-layout/admin-layout.component.css
src/app/components/common/layouts/admin-layout/admin-layout.template.html

Ticket 59688
Seems like this was partly fixed already, as the footer console appears at the bottom of the viewport, isn't affected by scrolling; The fix I added was to make room for content at the bottom to scroll up into view when the console is on.

Fix 59688 stable

---

src/app/pages/common/entity/entity-job/entity-job.component.html

Ticket 75631
Display update percentage as integer not float. We apparently don't label file size or download rate on the front end, so this PR doesn't relabel MB to MiB, etc. as suggested in the ticket.

FIX-75631-stable

---

src/assets/styles/themes/ix-blue.scss

Ticket: #76765
- Removes the empty vertical scrollbar from the app and from the Shells. The vert scroll bar still displays when needed.
- Also fixes some text that is too dark for dark themes.

FIX-76765-MASTER

---

src/assets/styles/themes/ix-blue.scss

Ticket: #76765
- Removes the empty vertical scrollbar from the app and from the Shells. The vert scroll bar still displays when needed.
- Also fixes some text that is too dark for dark themes.

Set some scrollbars to auto, fix some text

---

ports/freenas/freenas-webui/Makefile

if the version of webui on FreeNAS is different from the version
currently loaded into the web-browser. This can trigger a refresh
if the two timestamps do not match.

Add a 'buildtime' flag which can be parsed by WebUI to determine

---

src/app/pages/common/error-dialog/error-dialog.component.ts

Ticket: 76747
Makes dialog larger when it displays backtrace. Dialog is still a fixed size, and scroll appears when BT is larger than capacity of the box.

FIX-76747-master

---

src/app/pages/common/error-dialog/error-dialog.component.ts

Ticket: 76747
Makes dialog larger when it displays backtrace. Dialog is still a fixed size, and scroll appears when BT is larger than capacity of the box.

FIX: 76747-stable

---

src/app/helptext/system/email.ts
src/app/pages/system/email/email.component.ts
src/assets/styles/themes/ix-blue.scss

Ticket: #67359
This PR replaces #1979
Adds a message to make it clear that password (and matching PW) are always needed to submit the form (if SMTP auth is selected), even when you are just editing.
Incorporates requested change: T('Matching passwords must be entered to submit the form, even when editing settings.')

Email pw warning

---

src/app/components/common/layouts/admin-layout/admin-layout.template.html
src/app/pages/common/entity/entity-form/entity-form.component.html
src/app/pages/common/entity/entity-form/entity-form.component.ts
src/app/pages/common/entity/entity-table/entity-table.component.ts
src/assets/styles/egret_overrides.css

Ticket: #76773
Adjust entity tables to prevent a vert scroll from appearing on the main window. Gets rid of double vert scrollbars, except when tables are compressed to two rows.

Fix 76733 master

---

src/app/components/common/layouts/admin-layout/admin-layout.template.html
src/app/pages/common/entity/entity-form/entity-form.component.html
src/app/pages/common/entity/entity-form/entity-form.component.ts
src/app/pages/common/entity/entity-table/entity-table.component.ts
src/assets/styles/egret_overrides.css

Ticket: #76773
Adjust entity tables to prevent a vert scroll from appearing on the main window. Gets rid of double vert scrollbars, except when tables are compressed to two rows.

Fix 76773 stable

---

src/app/helptext/account/groups.ts

Ticket: #71147
(cherry picked from commit f6bee5c92260a30e0685d8d3f1212a63b03a4d7f)

Allow underscores in group names similar to how we allow them in user names

---

src/app/helptext/directoryservice/activedirectory.ts
src/app/helptext/directoryservice/ldap.ts
src/app/helptext/services/components/service-dc.ts
src/app/helptext/services/components/service-smb.ts
src/app/helptext/services/components/service-ssh.ts

The documentation chapter talking about Directory Services lives in `directoryservices.html` but the GUI references file `directoryservice.html`
This PR is trying to fix the above-described issue, by referencing file existing in the documentation.

Preventing UI from linking to nonexisting URL in documentation.

---

src/app/helptext/sharing/smb/smb.ts
src/app/pages/common/entity/entity-form/components/form-input/form-input.component.html
src/app/pages/sharing/smb/smb-form/smb-form.component.ts

Ticket: #59112
Makes a custom validator to prevent 'global' from being used as a SMB share name

Fix 59112 stable

---

src/app/helptext/directoryservice/activedirectory.ts
src/app/pages/directoryservice/activedirectory/activedirectory.component.ts

Ticket: #37518
Adds required and length validation to AD netbiosname_a field, fixes helptext labeling

Fix 37518 master

---

src/app/pages/storage/volumes/volumes-list/volumes-list.component.html
src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts

Ticket: #78438
Add colored icons for pool status, reformat text. In pic, pools all say 'healthy' but are actually keyed to Healthy (green), degraded (yellow) and other (red)

Fix 78438 stable

---

src/app/pages/storage/volumes/volumes-list/volumes-list.component.html
src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts

Ticket: #78438
Add colored icons for pool status, reformat text. In pic, pools all say 'healthy' but are actually keyed to Healthy (green), degraded (yellow) and other (red)

Feat 78438 master

---

src/app/pages/common/error-dialog/error-dialog.component.html
src/app/pages/common/error-dialog/error-dialog.component.ts

Ticket: #83387
Prevents error dialog from expanding a text area behind it

Fix backtrace textbox issue

---

src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
src/app/services/dialog.service.ts

Ticket: #78978
Adds a wider instance of dialog form; allows pool disconnect dialog to be wider without affecting other dialogs.

FIX-78978-stable-Add wider instance of entity dialog

---

src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
src/app/services/dialog.service.ts

Ticket: #78978
Adds a wider instance of dialog form; allows pool disconnect dialog to be wider without affecting other dialogs.

FIX-78978-master Wider dialog for disconnecting pools

---

src/app/helptext/services/components/service-ups.ts

Cherry-pick from master branch PR
Remove parenthetical aside and update link.

Fix 83668 - incorrect field name

---

src/app/pages/storage/volumes/volumes-list/volumes-list.component.html
src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts

Adds dynamic space on pool list page if footer console is open (failed test previously)

Console fix for pool list

---

src/app/helptext/system/email.ts

(cherry picked from commit 81a34ca1eb66fa151a52048fa356be1ec376e838)

Added info in the helptext about creating a friendly name in the from email field.

---

src/app/helptext/account/user-form.ts

Ticket: NAS-101158: Tone down scare message about usernames longer than 8 character

Clarify warning about username lengths

---

src/app/helptext/system/update.ts
src/app/pages/common/entity/entity-job/entity-job.component.ts
src/app/pages/system/update/manualupdate/manualupdate.component.ts

NAS-101368
Adds new emitter to wspost method in entity-job component to send a custom fail message if the attempt to post is immediately rejected; applied in update component, where there was an issue with manual updates 'hanging'.

Nas 101368 stable

---

src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts

NAS-100807
Re-works the err message on error dialog in Unlock Pool action to make use of MW error message (currently shows Object Object)

NAS-100807 match error format on pool unlcok to msg from MW

---

src/app/pages/common/error-dialog/error-dialog.component.html
src/app/pages/common/error-dialog/error-dialog.component.ts

NAS-101524
Another fix for the resizable error dialog, this time dealing with multiple dialogs being open at once by using ids where possible, and selecting the last one in an array which is hopefully our error dialog.

NAS-101524 Make sure the topmost dialog is selected for resizing

---

src/app/pages/storage/volumes/manager/manager.component.css
src/assets/styles/themes/ix-blue.scss

NAS-101541
Aligns checkboxes with the center of their labels rather than the baseline
Master branch also needed a little more margin on Pools Manager

NAS-101541 fix text-checkbox alignment

---

src/app/pages/system/update/update.component.ts

NAS-101841
Fixes a condition where available updates (sometimes) don't load. Nests the second ws call inside the first to make sure the first is done before check() is called.

NAS-101841 nest ws calls to make sure all data is in

---

src/app/pages/system/update/update.component.ts

NAS-101841
Fixes a condition where available updates (sometimes) don't load. Nests the second ws call inside the first to make sure the first is done before check() is called.

nest ws calls to make sure all data is in

---

src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts

NAS-100807
Re-works the err message on error dialog in Unlock Pool action to make use of MW error message (currently shows Object Object)

NAS-100807 Match err msg from MW on pool unlock to err dialog format

---

src/app/pages/common/error-dialog/error-dialog.component.html
src/app/pages/common/error-dialog/error-dialog.component.ts

NAS-101524
Another fix for the resizable error dialog, this time dealing with multiple dialogs being open at once by using ids where possible, and selecting the last one in an array which is hopefully our error dialog.

NAS-101524 make sure topmost dialog is selected for resizing

---

src/assets/styles/themes/ix-blue.scss

NAS-101541
Aligns checkboxes with the center of their labels rather than the baseline

Nas 101541 stable checkbox align

---

src/assets/styles/themes/ix-blue.scss

reduces div height for each line in xterm. An element with color looks better, works on zoom in and out, but if user adjusts font size, lines without fonts don't look great

NAS-100367 adjust div height in xterm

---

src/app/components/common/layouts/admin-layout/admin-layout.component.ts

Checking that log message is defined and that it's a string

NAS-102028 -- fix buggy comparison in footer console

---

src/app/components/common/layouts/admin-layout/admin-layout.component.css
src/app/components/common/notifications/notifications.component.css
src/app/components/common/notifications/notifications.component.html
src/app/components/common/notifications/notifications.component.ts

NAS-102213
Adds a check-circle icon to closed alerts and makes the alert text and icon a little opaque; makes 'Dismiss' the standard verb, sets width of the alert sidenav to prevent 'blinking' effect on refresh; gets rid of some unused code in notifications component.

NAS-102213 reformat closed alerts, standardize terms, stop blinking

---

src/app/components/common/layouts/admin-layout/admin-layout.component.css
src/app/components/common/layouts/admin-layout/admin-layout.template.html
src/assets/styles/fonts.css

Installed fonts are showing on dev builds but not on real hardware. Alos, fixes the hostname not being hidden when sidenav collapses

NAS-102443 fix font paths and hostname hide/show state

---

src/app/pages/preferences/page/forms/customtheme/customtheme.component.ts

NAS-102339 - removes from Theme creator the fields for label swatch and Add to Favorites; Automatically sets and saves primary color as swatch (for use in the future), removes default check from Enable Dark Logo, removes some used code

NAS-102339 remove old elements from theme page

---

src/app/helptext/system/support.ts
src/app/pages/system/support/support.component.ts
src/assets/styles/themes/ix-blue.scss

Removes DOM Sanitizer bypass from support page and adds underline via CSS.
This bypass, along with recently added (to Paratext) docurl and translate filters, was keeping paratexts from loading on this page. Angular docs say that using the bypass should be rare. I tested this branch on a hotpatch to my mini as well as in VM, and all links continue to work with no errors. This is the only use I found of the bypass in paratext anywhere in the UI.

NAS-102488

---

src/app/helptext/task-calendar/snapshot/snapshot-form.ts

I grepped through the code looking for other occurrences of this and found no likely places. If you happen to know of any, let's fix them.

NAS-102385 fix display of code in naming schema tooltip

---

src/app/views/sessions/signin/signin.component.ts

Keeps sign in page from hanging up in a 'loading' state by explicitly calling redirect

NAS-101932

---

src/app/core/components/viewchartgauge/viewchartgauge.component.ts
src/app/core/components/widgets/widgetcpu/widgetcpu.component.html
src/app/core/components/widgets/widgetpool/widgetpool.component.ts

Dashboard cpu widget now refers to threads instead of cores
Fixed console error on cpu widget where we are trying to access gauge before it is in the DOM
Fixed slight regression with pool widget's title text.

Widget cpu labels

---

src/app/pages/common/entity/entity-table/entity-table.component.html
src/app/pages/common/entity/entity-table/entity-table.component.ts

* removes setTimeout in entity-table which was causing some tables to not render actions
* note that ive moved the three dot and expand panel arrow button into the same fixed-width column. Are there drawbacks to this approach? Seems like a simple fix to the "action column too wide" tickets.

NAS-102640

---

src/app/pages/common/entity/entity-table/entity-table.component.scss
src/assets/styles/themes/ix-blue.scss

Gets tab nav to wrap in iscsi component. This is not an issue in services-rsync component, the only other place where this seems to be used. Also fixes layout issues with the entity table filter and buttons on smaller viewports.

NAS-102600 Make tab nav bar on iSCSI page wrap on narrow windows

---

src/app/pages/task-calendar/cloudsync/cloudsync-form/cloudsync-form.component.ts

* After user selects a "Credential," the destination folder will default to '/'
* Need to be sure this is the default behavior we're looking for.
Difference in default API message to `cloudsync.create`:
```
{
...
attributes: {}
}
```
becomes
```
{
...
attributes: { folder: '/' }
}
```

NAS-102635

---

src/app/pages/sharing/smb/smb-form/smb-form.component.ts

When saving an SMB share form, only prompt to edit the dataset's ACL if it is non-trivial. Otherwise redirect to the SMB share list.

NAS-102632 

---

src/app/helptext/task-calendar/replication/replication.ts
src/app/pages/common/entity/entity-table/entity-table-row-details/entity-table-row-details.component.html
src/app/pages/common/entity/entity-table/entity-table-row-details/entity-table-row-details.component.scss
src/app/pages/common/entity/entity-table/entity-table.component.html
src/app/pages/common/entity/entity-table/entity-table.component.scss
src/app/pages/task-calendar/cloudsync/cloudsync-list/cloudsync-list.component.ts
src/app/pages/task-calendar/replication/replication-list/replication-list.component.ts

* "No snapshots sent yet" if rep task does not have a previous run
* Unfortunately, the column widgets cannot support show/hide on a per-row basis, so future runs cannot be supported at this time. Perhaps we could target for 12?
* Moves task parsing from `dataHandler` to `resourceTransformIncomingRestData` so that the column data updates dynamically as the task runs
QUICK UPDATES:
* Fix for tooltip formatting bug
* Adds support for mdi icons in table widgets
* Make sure that table detail actions are visible at the right times

NAS-102155 

---

src/app/pages/network/interfaces/interfaces-list/interfaces-list.component.css
src/app/pages/network/interfaces/interfaces-list/interfaces-list.component.html
src/app/pages/network/interfaces/interfaces-list/interfaces-list.component.ts
src/assets/styles/themes/ix-blue.scss

I think the main problem addressed in this ticket, the sliding network icon not going away, is b/c you can click on action buttons that throw an error that never displays. Also,it's easy to take the 60 seconds at the top of the interfaces page (when you make a change) for a countdown timer that isn't working. Instead, it is a setting for the user to choose their own time limit for the next step. I have  tried to make that clear in text and styling. And have disabled buttons when HA is avaialble (and changes can't be made)

NAS-102624a No, this is the way

---

src/app/helptext/system/cloudcredentials.ts

- System > Cloud Credentials > Add > Amazon S3 > Endpoint URL.
- Help text now matches docs description.

NAS-101652: Synchronize field help text with docs

---

src/app/helptext/storage/volumes/datasets/dataset-permissions.ts
src/app/pages/storage/volumes/datasets/dataset-permissions/dataset-permissions.component.ts

* Removes deprecated ACL Type radio button from Dataset Permissions form. Default is 'unix' now.
* Adds headings to Dataset Permissions form.
* Update form layout by putting Who and Access Mode sections side-by-side.

Nas 102656

---

src/app/helptext/storage/volumes/datasets/dataset-acl.ts
src/app/pages/common/entity/entity-form/entity-form.component.scss
src/app/pages/storage/volumes/datasets/dataset-acl/dataset-acl.component.ts

* Adds headings to form sections: "File Information," "Access Control List," and "Advanced"
* Moves ACL to the right of the file information, saving a bit of vertical space (at the expense of some horizontal space that appeared unused)
* Renames "Tag" field in ACL to "Who"

NAS-101749 -- general layout updates to ACL manager form

---

src/app/pages/common/entity/entity-form/components/form-select/form-select.component.html
src/app/pages/common/entity/entity-form/models/field-config.interface.ts
src/app/pages/directoryservice/ldap/ldap.component.ts

Entity-form's form-select component now shows zero state message in disabled state if there are no options. Entity-form's field-config interface augmented with zeroStateMessage property,

Avoid empty list for form-select

---

src/app/helptext/services/components/service-ftp.ts
src/app/pages/services/components/service-ftp/service-ftp.component.ts

NAS-102869
(cherry picked from commit 3cd051cac105da753d4bf66004899c99dbc858ab)

Move certificate options out of helptext so they don't get doubled every time the page loads

---

src/app/pages/sharing/afp/afp-list/afp-list.component.ts
src/app/pages/sharing/nfs/nfs-list/nfs-list.component.ts
src/app/pages/sharing/smb/smb-list/smb-list.component.ts
src/app/pages/sharing/webdav/webdav-list/webdav-list.component.ts

Change from rest to ws calls on some sharing lists.
The ticket cited a problem with the associated target list, which has already been updated in 11.3 but not yet in 11.2.
In testing with QE, we saw the 1000 record barrier on the nfs list when using the rest call, and switching to WS fixed this. The PR changes the remaining rest calls in Sharing to ws.

NAS-102015

---

src/app/pages/common/entity/entity-table/entity-table.component.ts

You can duplicate the problem in the ticket by zooming the browser to 175% and resizing a table so that the last row is on a 'page' by itself. 174% and 176% don't show the same problem. There might be other bad breakpoints others will discover. This branch sets row height to 49px (rather than 50) when zoom is 175%. Otherwise, nothing changes.

Nas 102141

---

src/app/pages/system/support/support.component.html

Adds fxLayout=column to main container
The layout problem this PR addresses can be reliably recreated by going to pools list, then to the support page

NAS-103130 Define support page as fxflex column

---

src/app/pages/system/support/support.component.html
src/app/pages/system/support/tn-sys-info/tn-sys-info.component.html
src/assets/styles/themes/ix-blue.scss

Makes both FN and TN support pages display well down to 375px width (iPhone 6) and fairly well down to 325px, the width of the iPhone 5

Responsive support page

---

src/app/pages/common/entity/entity-form/entity-form.component.scss

Fixes condition where tooltips on entity form 'slide under' the border after visiting a page with expansion headers

NAS-102853

---

src/app/pages/system/bootenv/bootenv-list/bootenv-list.component.ts

If boot env 'Active' is 'Now/Reboot' or 'Reboot', the menu item to Activate disappears

NAS-103466 Make Activate conditional

---

src/app/helptext/system/bootenv.ts

Add information in the tooltip to inform users of valid characters.

NAS-103464: Update clone tooltip to include allowable chars

---

src/app/helptext/system/bootenv.ts

Add information in the tooltip to inform users of valid characters.

NAS-103465: Update rename tooltip to include allowable chars

---

src/app/helptext/system/email.ts
src/app/pages/system/email/email.component.ts

Adds validation and required status to the two fields required for saving the email profile, closes loader when an err returns from mw (Middleware accepts an integer of 0+, and provides some basic email validation)

NAS-103584

---

src/app/pages/common/entity/entity-form/components/form-input/form-input.component.html
src/app/pages/common/entity/entity-form/models/field-config.interface.ts
src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
src/app/services/dialog.service.ts
src/assets/styles/themes/ix-blue.scss

Adds a double-confirm input to Pool Export dialog and makes it possible to use form-input as a 'masked'  double-confirm input with just two config properties. Also sets disableclose to true on the wide dialog form!!!

Nas 103604

---

src/app/pages/common/entity/entity-form/components/dynamic-field/dynamic-field.css
src/app/pages/common/entity/entity-form/components/form-checkbox/form-checkbox.component.html
src/app/pages/common/entity/entity-form/components/form-combobox/form-combobox.component.html
src/app/pages/common/entity/entity-form/components/form-explorer/form-explorer.component.html
src/app/pages/common/entity/entity-form/components/form-input/form-input.component.html
src/app/pages/common/entity/entity-form/components/form-ipwithnetmask/form-ipwithnetmask.component.html
src/app/pages/common/entity/entity-form/components/form-list/form-list.component.ts
src/app/pages/common/entity/entity-form/components/form-radio/form-radio.component.html
src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.html
src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.ts
src/app/pages/common/entity/entity-form/components/form-select/form-select.component.html
src/app/pages/common/entity/entity-form/components/form-textarea-button/form-textarea-button.component.html
src/app/pages/common/entity/entity-form/components/form-textarea/form-textarea.component.html
src/app/pages/common/entity/entity-form/components/form-upload/form-upload.component.html
src/assets/styles/themes/ix-blue.scss

I built this on Erin's earlier PR #2968 hoping to minimize merge conflicts later.
Uses css to position error messages on inputs, selects, and a few other fields.

Nas 103629

---

src/app/pages/directoryservice/activedirectory/activedirectory.component.ts

shows netbiosname_b only if ha_mode is LEGACY

NAS-103671

---

src/app/pages/common/entity/entity-table/entity-table.component.ts

Prevents 'show default columns' function from running when the default view is all of the columns and they are already showing anyway. This is the condition that causes the display to temporarily forget the 'permanent' columns. Also, fixes a console.error with the dropMaxWidth function

NAS-103834

---

src/app/helptext/jails/jail-configuration.ts
src/app/pages/jails/jail-add/jail-add.component.ts

- Add draft help text (needs review/refinement).
- Rename fields to match title case standard.

NAS-103124: Add help text and rename NAT port forwarding fields.

---

src/app/helptext/account/user-change-pw.ts
src/app/helptext/system/advanced.ts
src/app/pages/account/users/change-password/change-password.component.ts
src/app/pages/common/entity/entity-form/entity-form.component.html
src/app/pages/common/entity/entity-form/entity-form.component.ts
src/app/pages/system/advanced/advanced.component.ts
src/app/pages/system/dataset/dataset.component.ts
src/app/pages/system/email/email.component.ts
src/app/pages/system/general/general.component.ts
src/app/pages/system/reporting/reporting.component.ts
src/assets/styles/themes/ix-blue.scss

Removes snackbar from entity form. Any forms that submit thru entity form AND that don't have a success route should show 'Settings saved' under the save button until the form is edited. Likewise with entity forms that use a custom submit, though I had to look for these, and might possibly have missed some?

NAS-103712 Remove entity form snackbar etc

---

src/app/core/services/preferences.service.ts
src/app/services/theme/theme.service.ts
src/app/services/ws.service.ts

Only send Authentication event when user logs in. Not during reauthentication via token. Theme service no longer listens for Authentication event directly. Removed some comments from preferences service

NAS-104093

---

src/app/helptext/system/alert-service.ts

For some reason the original links would not work unless you were already on the sight. Changed broken links to wiki links.

NAS-102713 fix broken links in SNMP alert service.

---

src/app/pages/system/bootenv/bootenv-status/bootenv-status.component.ts

For Boot Pool status page, offers 'attach' as an option only on the one disk of s single-disk pool, and offers 'Detach' and 'Replace' on disks of multi-disk pools. This PR goes with NAS-103462, which already has a PR merged

NAS-103462 Change availability of boot pool options

---

src/app/pages/common/entity/entity-form/components/form-explorer/form-explorer.component.html
src/app/pages/common/entity/entity-form/components/form-explorer/form-explorer.component.ts

Gives the top-level icon in form explorer a new icon, opens the tree one level by default

NAS-104062

---

src/app/helptext/system/alert-service.ts

- Includes Mattermost: `Icon URL` field and SNMP Trap: `Hostname` and `Port` fields.
- Jira issue Fix Version is `11.3-RC2`
- TODO: Port final text into the FreeNAS guide

NAS-104058: Add help text to fields added in System/Alert Services

---

src/app/pages/vm/vm-wizard/vm-wizard.component.ts

If the memory input contains only numbers (after spaces are stripped out), form displays a human readable equivalent to bytes
Ticket also mentions zvols, but we already turn any zvol number w/o a label into MiB

NAS-104074 Convert num to human readable if no unit is specified

---

src/app/pages/common/entity/entity-form/validators/compare-validation.ts

inputs (even when inputType = number) send strings to greaterThan validator when we edit values, so the validator tries to compare them alphabetically; This changes them to numbers before they are compared. Only the NTP servers forms and the SMB service form use this validator right now, and this seems to work on all of those cases.

NAS-104115 Change string to number in validator

---

src/app/pages/directoryservice/ldap/ldap.component.ts

Delays setting value of hostname. Also fixes a submit issue to make sure a blank hostname can be submitted if 'enable' is not selected

NAS-104237 Hostname not appearing on LDAP form

---

src/app/pages/system/update/update.component.ts

Removes 'train' as an arg for update call. I tested this on nightlies, nightly sdk and on RC1 (updating to RC2).

NAS-104271 Update train issue

---

src/app/helptext/storage/snapshots/snapshots.ts
src/app/pages/storage/snapshots/snapshot-list/snapshot-list.component.ts

- Conduct behavior testing for the rollback action and review the zfs.py middleware code.
- Rewrite the rollback dialog to reflect the behavior.
- Expand the warning about what is deleted by the action.
- Clean up some extra whitespace and errors.
- Yarn build testing: no issues.
Example of the new dialog:

NAS-100815: Rewrite Rollback Dialog

---

src/app/helptext/system/advanced.ts
src/app/pages/common/entity/entity-form/components/form-errors/form-errors.component.html
src/app/pages/system/advanced/advanced.component.ts
src/app/services/index.ts
src/app/services/validation.service.ts

Keeps the pw-matching validator working on Sys Adv form
Custom validators seem to quit listening to value changes (sometimes after save, almost always when user navigates away and then comes back), until page is refreshed. Custom validators in the component and in a service don't seem to do this. This PR puts the match password validator into a new service. Also makes a slight adjustment to the form-errors component so that errors show immediately on mismatch, a style consideration that I think might be less confusing for the user.

Nas 104085

---

src/app/helptext/system/general.ts

Correction typo in Save Configuration from "Export Pool Ecryption Keys" to "Export Pool Encryption Keys".

Correct spelling mistake in System/General

---

src/app/helptext/system/alert-service.ts

- Update text to include statement about configuring Mattermost.
- Add link to Mattermost configuration documentation.

NAS-104275: Update System/Alert Services/Mattermost/Icon URL help text

---

src/app/pages/common/entity/entity-form/entity-form.component.html
src/app/pages/common/entity/entity-form/entity-form.component.scss

Makes success msg in entity form a block-level element within action button row, with a div that is always present. Hopefully this fixes an intermittent problem of buttons overlapping the success message

Nas 104293

---

src/app/helptext/system/cloudcredentials.ts
src/app/pages/system/CloudCredentials/cloudcredentials-form/cloudcredentials-form.component.ts

- Fix an error where the Provider help text was not showing.
- Update the help text for each OneDrive field to match the updated authentication behavior.
- Yarn test: no issues.

NAS-103535: Update System/Cloud Credentials/OneDrive help text.

---

src/app/pages/system/bootenv/bootenv-list/bootenv-list.component.ts

Activate and Keep/Unkeep don't navigate to another page, so this PR empties the 'selected' list when these single actions are taken.

NAS-104314 Clear selected items when single actions are taken

---

src/app/helptext/system/failover.ts

Port text from TrueNAS Guide.
Yarn build testing: no issues.
Sync up with freenas-docs PR 1639 (https://github.com/freenas/freenas-docs/pull/1639)

NAS-103141: add helptext to TrueNAS System/Failover fields.

---

src/app/helptext/system/ntpservers.ts

The common \<sup> tag would not work. When used with integers it returned the calculation of the numbers used (which was an incorrect exponent calculation). When used with a string the tag did nothing.

NAS-104040 Clarify min and max poll helptext for NTP servers.

---

src/app/pages/services/components/service-rsync/service-rsync.component.html
src/app/pages/services/components/service-rsync/service-rsync.component.ts
src/app/pages/services/services.routing.ts
src/app/services/route-parts/route-parts.service.ts

Follows the pattern of Sharing/ISCSI to lay out rsync modules in routing; rsync add/edit forms now display as standalone (like other forms in the UI), rather than on a tab; breadcrumbs no longer provide broken links

Nas 104124a

---

src/app/helptext/sharing/iscsi/iscsi-wizard.ts
src/app/helptext/sharing/iscsi/iscsi.ts

- Update identical string in both help text files.
- Yarn testing: no issues.

NAS-103854: Update Sharing/iSCSI/Discovery Auth Group help text:

---

src/app/pages/system/CloudCredentials/cloudcredentials-form/cloudcredentials-form.component.ts

When verifying or saving cloud credentials, SFTP needs to make a key and store it first. This PR routes verifying and saving for SFTP through that process, and hopefully leaves other cloud providers alone. I tested this with ssh connection to a vm, and also with my S3 and Google Drive accounts

Nas 104291a

---

src/app/helptext/global-helptext.ts

Copyright appears on log in / out pages, in breadcrumb, about dialog. Also appears in Shell, w/c isn't updated by this global var

NAS-104561 Change global var for copyright year

---

src/app/helptext/directoryservice/kerberossettings.ts
src/app/helptext/storage/volumes/manager/manager.ts

The two links with local page anchor refs (#) break in production build (A '/' gets inserted into the path), though not necessarily on dev build or localhost. Had to hotpatch to test.

NAS-104495 / 11.3 / NAS-104495b

---

src/app/pages/task-calendar/rsync/rsync-form/rsync-form.component.ts

Allows user to enter one or more 'extras' to the rsync form. Extras cannot contain spaces, since mw apparently splits on space. In ui, extras can be split by space or comma or both

NAS-104762 / 12.0 / NAS-104762 Convert extras to list and back

---

src/app/pages/task-calendar/rsync/rsync-form/rsync-form.component.ts

Allows user to enter one or more 'extras' to the rsync form. Extras cannot contain spaces, since mw apparently splits on space. In ui, extras can be split by space or comma or both

NAS-104762 / 11.3 / NAS-104762 Convert rsync extra from string to list and back

---

src/app/helptext/services/components/service-lldp.ts
src/app/pages/services/components/service-lldp/service-lldp.component.ts
src/app/services/services.service.ts

… combobox to search…thru list
MW no longer accepts null or '' or lower-case letters. Country codes AND names are dsiplayed in the scrollbox and for filtering/searching; Only the two letter code is displayed when the choice is made since the user can type in their code rather than select it

NAS-104215 / 12.0 / NAS-104215 Use API call to get lldp country codes

---

src/assets/styles/themes/ix-blue.scss

Makes selects (drop-downs) show more content if there is a lot of content, doesn't affect smaller ones. Look at the user form (the groups select menu) and VM wizard zvol location. I tried out many sizes - much larger than this creates problem of hidden options. Also, combobox (and filtering) isn't a great option (for groups) since we need multiselect

NAS-100792 / 12.0 / NAS-100792a

---

src/app/pages/common/error-dialog/error-dialog.component.ts
src/app/pages/system/update/manualupdate/manualupdate.component.ts

Thanks to Aaron Ervin for rxjs help
Makes the resizing selectors for error dialog more specific so it can handle more than one error dialog at a time; also prevents the observable in manual update component from firing twice;

NAS-104801 / 11.3 / NAS-104801 

---

src/app/pages/common/error-dialog/error-dialog.component.ts
src/app/pages/system/update/manualupdate/manualupdate.component.ts

Thanks to Aaron Ervin for rxjs help
Makes the resizing selectors for error dialog more specific so it can handle more than one error dialog at a time; also prevents the observable in manual update component from firing twice;

NAS-104801 / 12.0 / NAS-104801

---

src/app/pages/reportsdashboard/components/report/report.component.ts

Reports should use server time when calculating API call time frames

NAS-104584

---

src/app/pages/reportsdashboard/components/report/report.component.ts

Reports should use server time when calculating API call time frames
(cherry picked from commit 765a25a4b6f64e092da33f748fc35ae56be22ed4)

NAS-104584 MASTER

---

src/app/helptext/directoryservice/kerberossettings.ts
src/app/helptext/storage/volumes/manager/manager.ts

The two links with local page anchor refs (#) break in production build (A '/' gets inserted into the path), though not necessarily on dev build or localhost. Had to hotpatch to test.

NAS-104495 / 12.0 / NAS-104495 Put broken links on single line

---

src/app/helptext/sharing/iscsi/iscsi-wizard.ts
src/app/helptext/sharing/iscsi/iscsi.ts
src/app/pages/sharing/iscsi/portal/portal-form/portal-form.component.ts

- Update to include text about IPv6 wildcard.
- Fix bug that was preventing help text from displaying in Sharing/iSCSI/Portals/Add
- Yarn testing: no issues.

DOCS-116: Update iSCSI/Portals/IP Address help text

---

src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.html

Always use system_serial instead of license.system.serial
(cherry picked from commit 4a225842dbf0130da88acd497d38f3f1360b6749)

NAS-104636 / 12.0 / NAS-104636

---

src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.html

Always use system_serial instead of license.system.serial

NAS-104636 / 12.0 / NAS-104636-stable (by dszidi)

---

src/app/pages/services/services.component.html
src/app/pages/services/services.component.ts

Fixes filter on services page for SMB (which has a different name from its label), also ignores spaces (for two-word Services) and periods (for 'smart' or S.M.A.R.T.)

NAS-104598 Filter by label, ignore space and period

---

src/app/pages/common/entity/entity-form/services/entity-form.service.ts

Prevents slowdown by filtering results on ws call when explorerType is 'directory'; also limits results to 1000 at Andrew's suggestion

NAS-104535

---

src/app/helptext/account/user-form.ts
src/app/helptext/network/ipmi/ipmi.ts
src/app/helptext/services/components/service-dynamic-dns.ts
src/app/helptext/services/components/service-snmp.ts
src/app/helptext/services/components/service-webdav.ts
src/app/pages/account/users/user-form/user-form.component.ts
src/app/pages/network/ipmi/ipmi.component.ts
src/app/pages/services/components/service-dynamicdns/service-dynamicdns.component.ts
src/app/pages/services/components/service-snmp/service-snmp.component.ts
src/app/pages/services/components/service-webdav/service-webdav.component.ts

Moves password comparison validation to the Validation service for user form and four other components. We weren't able to confirm that this fixes the problem in the ticket, but it does fix the issue of the validators that stop listening when the user navigates away from the page, then comes back.
Also please check: It seemed like a mistake that the password for dynamic DNS had a minLength validator of 8, since it's the pw for any number of outside services

NAS-104796 / 11.3 / Nas 104796

---

src/app/helptext/account/user-form.ts
src/app/helptext/network/ipmi/ipmi.ts
src/app/helptext/services/components/service-dynamic-dns.ts
src/app/helptext/services/components/service-snmp.ts
src/app/helptext/services/components/service-webdav.ts
src/app/pages/account/users/user-form/user-form.component.ts
src/app/pages/network/ipmi/ipmi.component.ts
src/app/pages/services/components/service-dynamicdns/service-dynamicdns.component.ts
src/app/pages/services/components/service-webdav/service-webdav.component.ts

Moves password comparison validation to the Validation service for user form and four other components. We weren't able to confirm that this fixes the problem in the ticket, but it does fix the issue of the validators that stop listening when the user navigates away from the page, then comes back.
Also please check: It seemed like a mistake that the password for dynamic DNS had a minLength validator of 8, since it's the pw for any number of outside services

NAS-104796 / 12.0 / Nas 104796 master

---

src/app/helptext/storage/volumes/volume-list.ts
src/app/pages/common/entity/entity-dialog/entity-dialog.component.ts
src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts

This solution makes it where the passphrase or key is field is hidden and disabled when either of the others is used for unlocking to prevent the user from attempting to use both.

NAS-104874 / 11.3 / Nas 104874

---

src/app/components/common/dialog/task-manager/task-manager.component.css
src/app/components/common/dialog/task-manager/task-manager.component.html
src/app/components/common/dialog/task-manager/task-manager.component.ts

Makes time in task manager respond to timezone changes. Note that there is a related middleware ticket, NAS-10455, that this one needs to get the time right. PS - Fixing for 12 may require a different approach, since 12 will have the local service and choice of formats

NAS-104541 / 11.3 / NAS-104541 Make task manager responsive to time zone change

---

src/assets/styles/themes/ix-blue.scss

Keeps tooltips from getting pushed into bottom margin on wizards, also limits explorer to a reasonable height throughout the app.

NAS-104740 / 12.0 / NAS-104740 Limit height of form explorer, thanks to Damian S

---

src/assets/styles/themes/ix-blue.scss

Keeps tooltips from getting pushed into bottom margin on wizards, also limits explorer to a reasonable height throughout the app.

NAS-104740 / 11.3 / Nas 104740 stable imit height of form explorer, thanks to Damian S

---

src/app/helptext/storage/volumes/volume-list.ts
src/app/pages/common/entity/entity-dialog/entity-dialog.component.ts
src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts

git cherry-pick -x 5df80e9767dfa09554754ec075299703ddb29ed1
git cherry-pick -x dbd5d682f2d2db13bc474b06d1b662a37601c1a7
This solution makes it where the passphrase or key is field is hidden and disabled when either of the others is used for unlocking to prevent the user from attempting to use both.

NAS-104874 / 12.0 / Nas 104874 (by erinix)

---

src/app/helptext/sharing/iscsi/iscsi.ts

I heard that code was frozen. If that's the case, no big deal. This can be pushed to next version release cycle.

DOCS-291 helptext for "enable" in iSCSI extents

---

src/app/helptext/system/certificates.ts

Similar to #3430 - slashes seem to get inserted sometimes on multiline links; tested this with a hot-patched 11.3 release system

NAS-105070 / 11.3 / NAS-105070 put link on one line to avoid slash being inserted

---

src/app/pages/system/support/fn-support/fn-support.component.ts
src/app/pages/system/support/tn-support/tn-support.component.ts

Clears out Support form values (inc debug and attachments) on submit by:
- Using a local var for payload that is new for each submit
- clearing out 'subs' which stores the attachment list 
Debug and attachments were hanging around and being resubmitted if the page wasn't refreshed

NAS-105040 / 11.3 / NAS-105040 Clear support payload on form submit for FN, TN

---

src/app/pages/system/support/fn-support/fn-support.component.ts
src/app/pages/system/support/tn-support/tn-support.component.ts

Clears out Support form values (inc debug and attachments) on submit by:
- Using a local var for payload that is new for each submit
- clearing out 'subs' which stores the attachment list 
Debug and attachments were hanging around and being resubmitted if the page wasn't refreshed

NAS-105040 / 12.0 / NAS-105040 Clear support payload on form submit for FN, TN

---

src/app/pages/services/components/service-ups/service-ups.component.ts

Hides (and disables) 'driver' field on UPS service form when 'slave' mode is chosen

NAS-105247 / 11.3 / NAS-105247 Make UPS Service fields show and hide correctly

---

src/app/pages/services/components/service-ups/service-ups.component.ts

Hides (and disables) 'driver' field on UPS service form when 'slave' mode is chosen, fixes beforeSubmit() for v. 12 labeling

NAS-105247 / 12.0 / Nas 105247 for v12

---

src/app/helptext/task-calendar/replication/replication-wizard.ts
src/app/helptext/task-calendar/replication/replication.ts

- Reinvestigate field behavior and update field names and help text for the Replication Task Wizard and Advanced Replication Creation screens.
- Yarn testing: no issues.
Final text changes to be ported to the 12 branch as needed and used as a basis to rewrite or expand text in the 11.3-U2 guide.

NAS-105113 / 11.3 / NAS-105113: Adjust field names and expand help text in Replication Tasks

---

src/app/core/classes/system-profiler.ts
src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.html
src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.ts

Enclosure UI can now handle when vdev child is present but no device is listed (status=REMOVED)
Enclosure UI now informs if the pool is not healthy.

NAS-105143 / 12.0 / NAS-105143 (by dszidi)

---

src/app/pages/common/entity/entity-table/entity-table.component.html
src/app/pages/common/entity/entity-table/entity-table.component.scss
src/app/pages/common/entity/entity-table/entity-table.component.ts
src/app/pages/plugins/available-plugins/available-plugins.component.css

Make entity-table able to do:
1. if the table container has no more space (which means the table has more than one page), table height will not be updated when expanding/collapsing rows.
2. if the table container has more space (like the situation described in the ticket 105400), table height will be recalculated when expanding/collapsing rows. if table height (include the expanded detail rows) + cardHeaderContainer (the dynamic cardheader component) > TableContainerHeight (window.innerHeight - 233), then the table height will be set fixed which equal to TableContainerHeight.

NAS-105400 / 12.0 / Nas 105400

---

src/app/pages/reportsdashboard/components/report/report.component.ts
src/app/pages/reportsdashboard/reportsdashboard.component.ts

Update linechart when report changes. Previously the components weren't expected to have the assigned reports change, only the data. However due to how the virtual scrolling recycles on screen components, reports need to update their linecharts when the reports change.

NAS-105514 / 12.0 / NAS-105514

---

src/app/components/common/topbar/topbar.component.ts
src/app/pages/system/support/fn-sys-info/fn-sys-info.component.ts

TN Core returns true for 'is_eula_accepted' so this PR forces the eula to be presented when a new license is entered in core. PS - truenas.get_eula is returning null right now on 12

NAS-105566 / 12.0 / NAS-105566 Force topbar to present eula on license enter

---

src/app/pages/directoryservice/kerberossettings/kerberossettings.component.ts

I removed this 'isEntity' when switching to ws, but put it back in too. But it doesn't belong. It blocks existing data from loading

NAS-105610 / 12.0 / NAS-105610 remove isEntity from Kerb settings form

---

src/app/pages/system/two-factor/two-factor.component.ts

The important changes are on lines 280 and 281, to make sure the secret and the URI get updated immediately when secret is refreshed. This also causes the 'Show QR' button to be enabled when it should be.

NAS-105626 / 12.0 / NAS-105626 Update secret and qr string on secret renewal

---

src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.html
src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.ts

Make form scheduler use the preferred time format AND the preferred timezone. 
The timezone issue is already fixed in 11.3 stable; format issue doesn't apply to 11.3

NAS-105647 / 12.0 / NAS-105647

---

src/app/pages/sharing/smb/smb-form/smb-form.component.ts

Makes SMB Share form show advanced fields if advanced is checked in sys > advanced. This call (system.advanced.config) is already made in entity form, but this particular form gets it too late. Doesn't seem to be a problem in 11.3

NAS-105738 / 12.0 / NAS-105738 Check advanced.config in component

---

src/app/helptext/services/components/service-smb.ts
src/app/pages/services/components/service-smb/service-smb.component.ts

Adds custom validation for a list of strings for netbios aliases. the REST call submits and receives a space-separated string rather than an array, so the other changes in the PR for v 12 aren't needed here.

NAS-105395 / 11.3 / NAS-105395 Fix validation for netbios aliases on 11

---

src/app/helptext/services/components/service-afp.ts
src/app/pages/services/components/service-afp/service-afp.component.ts

The mw call is in the stable / master repositories but not yet in a build
New line in helptext is from api doc

NAS-105296 / 12.0 / NAS-105296 Use new mw method to fetch bindips

---

src/app/helptext/system/email.ts
src/app/pages/system/email/email.component.ts

Validates for ASCII characters from 32 to 126 (which includes SPACE, which mw also allows)

NAS-105539 / 11.3 / NAS-105539 Match mw validation for email password

---

src/app/helptext/directoryservice/activedirectory.ts
src/app/helptext/directoryservice/ldap.ts
src/app/helptext/network/interfaces/interfaces-form.ts
src/app/helptext/network/laggs/lagg.ts
src/app/helptext/services/components/service-dc.ts
src/app/helptext/services/components/service-ftp.ts
src/app/helptext/services/components/service-s3.ts
src/app/helptext/services/components/service-smb.ts
src/app/helptext/services/components/service-snmp.ts
src/app/helptext/services/components/service-ssh.ts
src/app/helptext/services/components/service-webdav.ts
src/app/helptext/sharing/iscsi/iscsi.ts
src/app/helptext/shell/shell.ts
src/app/helptext/storage/import-disk/import-disk.ts
src/app/helptext/storage/snapshots/snapshots.ts
src/app/helptext/storage/volumes/datasets/dataset-acl.ts
src/app/helptext/storage/volumes/datasets/dataset-form.ts
src/app/helptext/storage/volumes/manager/vdev.ts
src/app/helptext/storage/volumes/zvol-form.ts
src/app/helptext/system/advanced.ts
src/app/helptext/system/ca.ts
src/app/helptext/system/certificates.ts
src/app/helptext/system/general.ts
src/app/helptext/task-calendar/replication/replication.ts
src/app/helptext/task-calendar/resync/resync-form.ts
src/app/helptext/vm/devices/device-add-edit.ts
src/app/helptext/vm/vm-cards/vm-cards.ts

- Attempt to directly inject more informative text into many help text strings
- Remove fragile documentation links that break with each release
- Cherry-picked commit from 11.3-U3 branch and reworked to apply changes to 12

NAS-105927 / 12.0 / NAS-105927: Replace all guide links with detailed text.

---

src/app/helptext/task-calendar/replication/replication.ts

Also an incidental fix to yarn error complaining about a missing help text field in system/advanced.
cherry-pick from PR #3983

NAS-105870 / 12.0 / NAS-105870: Rework restrict_schedule field name and help text

---

src/app/helptext/system/advanced.ts
src/app/helptext/task-calendar/replication/replication.ts

Also an incidental fix to yarn error complaining about a missing help text field in system/advanced.

NAS-105870 / 11.3 / NAS-105870: Rework restrict_schedule field name and help text. (11.3-U3)

---

src/app/pages/preferences/page/forms/custom-theme-manager-form.component.ts

I think this fix will resolve the issue below. Indeed with the French translation the buttons below are no longer aligned. With the correction there are.
**Before fix**
**After fix**

Fix display buttons in french translation

---

src/app/core/components/widgets/widgetmemory/widgetmemory.component.html

ecc presents as "ECC" or "non-ECC", but actually
the system actually only knows "ECC" or "IDK, prolly not but maybe".
dmidecode does not seem a reliable source for this information.
It has been shown that ECC can be installed, configured, and enabled,
and yet dmidecode can say that it is not.
This change should only show the "(ECC)" in the panel when it knows
there is ECC, and nothing when it isn't sure, instead of "(non-ECC)".
See:
* https://www.ixsystems.com/community/threads/truenas-web-ui-shows-non-ecc-but-ecc-is-used.84492/
* https://jira.ixsystems.com/projects/NAS/issues/NAS-105991

dashboard memory panel: show ECC status only when known

---

src/app/helptext/sharing/smb/smb.ts
src/app/pages/sharing/smb/smb-form/smb-form.component.ts
src/app/pages/sharing/smb/smb-list/smb-list.component.ts

The [ENOENT] error in the smb table and form, below, was just added to the middleware today, and isn't in the build yet.

NAS-105950 / 12.0 / NAS-105950 Use new api calls to detect if pools or datasets are locked

---

src/app/helptext/sharing/afp/afp.ts
src/app/helptext/sharing/smb/smb.ts

Updated AFP and SMB hosts allow/deny helptext. Also, I removed some erroneous code for a placeholder no longer being used.

NAS-106099 / 12.0 / update hosts allow/deny helptext.

---

src/app/pages/storage/volumes/volume-status/volume-status.component.css
src/app/pages/storage/volumes/volume-status/volume-status.component.html
src/app/pages/storage/volumes/volume-status/volume-status.component.ts

Show pool scrub in seconds, minutes, hours, and days with min, hr, day added only as needed; Distinguish between singular and plural; adjust some styling, fix some translations, also added percentage complete to status page
NOTE that zfs.pool.scan seems to be returning 0 seconds right now

NAS-106230 / 12.0 / NAS-106230

---

src/app/helptext/services/components/service-afp.ts
src/app/helptext/services/components/service-smb.ts
src/app/pages/services/components/service-afp/service-afp.component.ts

The update to mw doesn't appear to be in the build yet.
The tooltip is the same as for log level in Services > SMB. It probably should be checked in both places to make sure it is up-to-date and provides help.

NAS-106204 / 12.0 / NAS-106204 Expose loglevel for AFP

---

src/app/services/user.service.ts

Regex allows username to begin with number, letter or underscore(_); name can contain these plus period (.) and dash(-), and can use $ but only in the last position. Username must be 16 characters or less, and a warning about legacy systems is shown when length exceeds eight characters. Group names use the same regex without the length restrictions.

NAS-106274 / 12.0 / Nas 106274

---

src/app/services/user.service.ts

Regex allows username to begin with number, letter or underscore(_); name can contain these plus period (.) and dash(-), and can use $ but only in the last position. Username must be 16 characters or less, and a warning about legacy systems is shown when length exceeds eight characters. Group names use the same regex without the length restrictions.

NAS-106274 / 11.3 / NAS-106274 Allow user/group names to begin with a number

---

src/app/helptext/task-calendar/snapshot/snapshot-form.ts

Removing extra spaces reinstated translations for the five checked tooltips (pic). Three tooltips on this page have changed in content and need an updated translation to match the new string. For one (at the bottom), seems to be new.

NAS-106055 / 11.3 / NAS-106055 Remove some spaces that broke some translations

---

src/app/helptext/storage/volumes/volume-list.ts
src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
src/app/services/dialog.service.ts

Uses translate.get to translate string fragments in pool export dialog; also moves lots of text strings into helptext (PS - no changes to any helptext, so no disturbing translation)
In 11.3, many of the 'conditional strings" that appear in the dialog window did not have T tags and therefore aren't yet in the .po files

NAS-106464 / 11.3 / Nas 106464 stable

---

src/assets/i18n/README.md
src/assets/i18n/ja.po

[ja.po]
Add a few translations
[README.md]
Update last update and fix typo (jp.po -> ja.po)
---
1. Is `jp.po` in [README.md](https://github.com/freenas/webui/tree/master/src/assets/i18n#readme) a typo for `ja.po` ? Please check if it's correct.
2. I'd like to work on translating the untranslated parts into Japanese, but I don't know how to incorporate and test (preview) those changes.
I checked the [README.md in the repository](https://github.com/freenas/webui#readme).
```$ ./setup_env.js -i <ip address or FQDN of the server where FreeNAS is running>```
I entered the IP address of a running FreeNAS and started it with `yarn start`.
But the web server started with the default `http://localhost:4200` and I can't test (preview) it the way I intended.
To be honest, my English is not very …

Update ja.po, README.md

---

src/app/pages/storage/volumes/datasets/dataset-unlock/dataset-unlock.component.ts

Remove option to restart jails/vms on dataset unlock, this should just always happen

---

src/app/pages/common/entity/entity-form/components/form-checkbox/form-checkbox.component.html

I checked non-standard (ie non-entity) checkboxes too; didn't find any to fix, although some non-standard forms lack ix-auto

NAS-106737 / 12.0 / Nas 106737 (by dkmullen)

---

src/app/helptext/system/support.ts

Right now the UI still states
`Search the FreeNAS issue tracker to ensure the issue has not already been reported before filing a bug report or feature request.`
I changed that to say TrueNAS.

change FreeNAS to TrueNAS on System Support Page

---

src/app/helptext/sharing/smb/smb.ts
src/app/pages/sharing/smb/smb-form/smb-form.component.ts
src/app/pages/sharing/smb/smb-list/smb-list.component.ts

Uses a new (private?) method for determining locked status, adds translate.get to dialog (which fixes translation), updates helptext to hopefully make it more specific (which breaks translation until new strings are translated).

NAS-106870 / 12.1 / Nas 106870

---

src/app/pages/vm/vm-form/vm-form.component.ts

Fixes list of bootloader options on VM edit form. The VNC button issue mentioned in the ticket was addressed in https://github.com/freenas/webui/pull/4427

NAS-106904 / 12.1 / NAS-106904 Update listing of boot options in VM edit form

---

src/app/helptext/sharing/afp/afp.ts
src/app/helptext/sharing/smb/smb.ts
src/app/pages/common/entity/entity-dialog/dialog-form-configuration.interface.ts
src/app/pages/common/entity/entity-dialog/entity-dialog.component.html
src/app/pages/sharing/afp/afp-form/afp-form.component.ts
src/app/pages/sharing/smb/smb-form/smb-form.component.ts
src/assets/styles/themes/ix-blue.scss

Displays BOTH a dialog AND paragraph warning when user wants to create a NEW AFP share (but not when editing an existing one). We probably want one or the other - need guidance on which; dialog offers an easy way (via a button) to redirect to the SMB share creation form. Also need guidance on the message

NAS-106920 / 12.1 / Nas 106920

---

src/app/helptext/storage/volumes/datasets/dataset-acl.ts
src/app/helptext/storage/volumes/datasets/dataset-permissions.ts
src/app/pages/storage/volumes/datasets/dataset-acl/dataset-acl.component.ts
src/app/pages/storage/volumes/datasets/dataset-permissions/dataset-permissions.component.ts
src/app/pages/storage/volumes/datasets/dataset-posix-acl/dataset-posix-acl.component.ts
src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts

Uses only one menu item, 'Edit Permissions' which takes the user to Permissions editor if ACL is trivial, and to the ACL editor if not. Adds a button for switching from Permissions Editor to ACL and (if ACL is trivial) back again. Makes 'Strip ACL a button with its own submission method

NAS-106868 / 12.1 / Nas 106868 

---

src/app/pages/system/advanced/advanced.component.ts

MIddleware accepts an integer of GiBs, so UI validation should match

NAS-107072 / 12.1 / NAS-107072 Refine validation to allow only gigs and integers

---

src/app/pages/network/ipmi/ipmi.component.ts

git cherry-pick -x d96ca69e27a323e8404d67db9979cb93f919bb2d
PS Ip fields/values aren't submitted at all if dhcp is checked

NAS-106842 / 11.3 / NAS-106842 disable ip addresses when dhcp is selected (by dkmullen)

---

src/assets/styles/styles.css

The shark icon is too big, and right up against the border when collapsed (labels not showing mode). I made it smaller by 5px and it looks so much better.

Make shark icon smaller

---

src/app/pages/vm/vm-wizard/vm-wizard.component.ts

Hides bind on VM wizard when VNC option isn't applicable (12.0 - this is covered already in 12.1 +

NAS-106888 / 12.0 / NAS-106888 Hid Bind when VNC is not available

---

src/app/pages/system/advanced/advanced.component.ts

MIddleware accepts an integer of GiBs, so UI validation should match

NAS-107072 / 12.0 / NAS-107072 Refine validation to allow only gigs and integers (by dkmullen)

---

src/app/components/common/dialog/about/about-dialog.component.html

Although the websites are (currently the same), TrueNAS help should preferably (for consistancy) point to the TrueNAS website.
This sets the Documentation link in the about dialog screen to:
https://www.truenas.com/docs/
Instead of:
https://docs.ixsystems.com/
Notes:
- Needs backport to 12.0
Signed-off-by: Kjeld Schouten-Lebbing <kjeld@schouten-lebbing.nl>

NAS-107326 / 12.1 / Change Documentation link

---

src/app/components/common/dialog/about/about-dialog.component.html

Although the websites are (currently the same), TrueNAS help should preferably (for consistancy) point to the TrueNAS website.
This sets the Documentation link in the about dialog screen to:
https://www.truenas.com/docs/
Instead of:
https://docs.ixsystems.com/
Notes:
- Needs backport to 12.0
Signed-off-by: Kjeld Schouten-Lebbing <kjeld@schouten-lebbing.nl>
Original PR: https://github.com/freenas/webui/pull/4571

NAS-107326 / 12.0 / Change Documentation link (by Ornias1993)

---

src/app/pages/services/components/service-ups/service-ups.component.ts

Checking value changes too soon seems to consistently cause the error in the ticket
Original PR: https://github.com/freenas/webui/pull/4575

NAS-107316 / 12.0 / NAS-107316 Delay first check of drivers (by dkmullen)

---

src/app/components/common/dialog/about/about-dialog.component.html

Here is a fix for https://jira.ixsystems.com/browse/NAS-107326 
Documentation link in About panel should point to https://www.truenas.com/docs/ same as the Guide link in the menu does.

NAS-107326 Pointing docs link to truenas.com/docs

---

src/app/helptext/shell/shell.ts
src/app/helptext/vm/vm-cards/vm-cards.ts

There seems to be a typo in in which arcstat is named arcsat.
This PRfixes said typo
Notes:
- Might want to backport this to 12 and 
- Possibly needs backporting to 11 as well
Signed-off-by: Kjeld Schouten-Lebbing <kjeld@schouten-lebbing.nl>

NAS-107330 / 12.1 / Rename arcsat to arcstat

---

src/app/helptext/storage/volumes/volume-list.ts
src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts

Fix spacing and wording on pool export window for 11.3
Only processes:
Services and processes:
Original PR: https://github.com/freenas/webui/pull/4604

NAS-107177 / 20.10 / NAS-107177 (by dkmullen)

---

src/app/pages/common/entity/entity-table/entity-table.component.ts

The issue in the ticket was caused by removal from UI of pools column from disk table. This PR adds a check for missing columns and removes them from display

NAS-107442 / 12.0 / NAS-107442 Remove non-existing cols from preferred list

---

src/app/pages/common/entity/entity-table/entity-table.component.ts

The issue in the ticket was caused by removal from UI of pools column from disk table. This PR adds a check for missing columns and removes them from display
Original PR: https://github.com/freenas/webui/pull/4618

NAS-107442 / 11.3 / NAS-107442 Remove non-existing cols from preferred list (by dkmullen)

---

src/app/pages/common/entity/entity-table/entity-table.component.ts

The issue in the ticket was caused by removal from UI of pools column from disk table. This PR adds a check for missing columns and removes them from display
Original PR: https://github.com/freenas/webui/pull/4618

NAS-107442 / 20.10 / NAS-107442 Remove non-existing cols from preferred list (by dkmullen)

---

src/app/helptext/directoryservice/activedirectory.ts

Rework AD Timeout help text to point to Task Manager instead of waiting for timeout.

NAS-107439 / 12.0 / NAS-107439

---

src/app/helptext/storage/volumes/volume-list.ts
src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts

Fix spacing and wording on pool export window for 11.3
Only processes:
Services and processes:
Original PR: https://github.com/freenas/webui/pull/4604

NAS-107177 / 12.0 / NAS-107177 (by dkmullen)

---

src/app/helptext/directoryservice/activedirectory.ts

Rework AD Timeout help text to point to Task Manager instead of waiting for timeout.
Original PR: https://github.com/freenas/webui/pull/4627

NAS-107439 / 20.10 / NAS-107439 (by Mrt134)

---

src/app/core/components/widgets/widgetcpu/widgetcpu.component.html
src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.ts

CPU widget should degrade to Unknown if model is null. WidgetSysInfo now has a case for Scale systems in product detection

NAS-107655 / 20.10 / NAS-107655

---

src/app/components/common/topbar/topbar.component.ts
src/app/pages/system/update/update.component.ts

Uses update api info to communicate whether the system will restart. Keeps 'update.download' as the method if the user doesn't want to reboot, but uses the reboot: true property otherwise; redirectes to reboot page upon success

NAS-107584 / 12.0 / Nas 107584

---

src/app/helptext/sharing/smb/smb.ts

"AFP" -> "SMB" in SMB helptext

---

src/app/components/common/navigation/navigation.component.ts
src/assets/styles/fn-styles.css

Allows room for all 22 possible menu items under System, although 21 is probably the max need under current restrictions. Seems to have no ill effect on shorter lists. Should not be an issue with the new menu on SCALE
ALSO: Removes 2FA from the menu if the product type is enterprise

NAS-107951 / 12.0 / NAS-107951 Make room for all menu items

---

src/app/components/common/topbar/topbar.component.ts
src/app/pages/system/update/update.component.ts

Uses update api info to communicate whether the system will restart. Keeps 'update.download' as the method if the user doesn't want to reboot, but uses the reboot: true property otherwise; redirectes to reboot page upon success
Original PR: https://github.com/freenas/webui/pull/4702

NAS-107584 / 20.10 / Nas 107584 (by dkmullen)

---

src/app/helptext/network/interfaces/interfaces-list.ts

Update delete_dialog_text to reflect disruptive changes must be tested before saving. Ticket is currently not assigned a Fix Version so let me know if this needs to be back-ported to 12.0.

NAS-107884 / 20.10 / NAS-107884

---

src/app/pages/system/general-settings/support/proactive/proactive.component.ts
src/app/pages/system/general-settings/support/support-licensed/support-form-licensed.component.ts
src/app/pages/system/general-settings/support/support-unlicensed/support-form-unlicensed.component.ts
src/app/pages/system/general-settings/support/support.component.html
src/assets/styles/fn-styles.css

Sets unlicensed support to one column
Fixes alignment on two-column licensed-support form
Fixes alignment on Proactive support form by moving instructions from header to tooltip
Fixes display problem with three buttons on Support card and vertical image by using dropdown action button
Also undoes min-width setting which attempted to fix width for UPS service driver choices - making a new ticket for displaying those.
(Varying field lengths, misalligned password 'eye' icon are being fixed in another branch)
Still three buttons on licensed rack-mounted server, which is most common case

NAS-107808 / 20.10 / Nas 107808

---

src/app/helptext/account/user-list.ts
src/app/pages/account/users/user-list/user-list.component.ts

Resets user/group lists when when the slide-in menu closes and refreshes the table. This isn't an issue for previous versions because the form navigated to the table causing a complete page reload.

NAS-107988 / 20.10 / NAS-107988 reset users/groups when table refreshes

---

src/app/components/common/breadcrumb/breadcrumb.component.css
src/app/components/common/breadcrumb/breadcrumb.component.html
src/app/components/common/breadcrumb/breadcrumb.component.ts

Fixes issue (as in datasets permissions, edit, acls and also zvol edit) where coded urls cause problems. A similar change was implemented recently in 11.3 (below) and this seems to work better
https://github.com/freenas/webui/commit/5f1e0413f4cc01a73cb2ba3fc5971f665f787be5#diff-122221e4e53fbcd8526591888e67e068

NAS-107896 / 12.0 / NAS-107896 Use click instead of routerlink for breadcrumbs

---

src/app/helptext/system/support.ts

Liscensing -> Licensing on settings-support overview
Signed-off-by: Kjeld Schouten-Lebbing <kjeld@schouten-lebbing.nl>

Fix support typo in settings

---

src/app/pages/storage/volumes/volumes-list/volumes-list.component.html

When geli-locked pool fails to decrypt, the lock turns red and a message appears.
Create a test case with:
midclt call datastore.update storage.volume 5 '{"vol_encrypt": 1}'
(5 being the vol number)
The yellow lock is for a pw-protected pool. The red lock is a geli-encrypted pool that failed to decrypt.

NAS-107876 / 12.0 / Nas 107876 12

---

src/app/helptext/services/components/service-snmp.ts
src/app/pages/services/components/service-snmp/service-snmp.component.ts

Depends on mw pr: https://github.com/freenas/freenas/pull/5904
git cherry-pick -x e19f4c4d144b85f881e5233b49412c64bd3a70c8
git cherry-pick -x 33eb7a7a3416e23b7f1dfccacef4c83ce51a98b1
git cherry-pick -x e8958b85ec409cd7b0882c2796364bf3a09a1cbb
git cherry-pick -x 63a4e0ec0d7eee54ea43657325eaef1f64b90c68
Add iftop option to SNMP service
Original PR: https://github.com/freenas/webui/pull/4792

NAS-108068 / 12.0 / Nas 108068 (by dkmullen)

---

src/app/core/components/widgets/widgetcpu/widgetcpu.component.ts

Use the more flexible convertToRGB method. It checks the input value type and will not throw an error when given rgba values.

NAS-108212 / 12.0 / NAS-108212

---

src/app/core/classes/hardware/m50.ts
src/app/core/classes/system-profiler.ts
src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks-mini.component.ts
src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.ts

Fixes too many concurrent calls error on enclosure UI. This was caused by the DiskTemperatures subscription living in the base class. This is a feature only on the MINI line but the service was being activated on the rack mount models too.
The rear drive bays on the M50 were referencing the drives that belong to the front. Rear drive bay detection has been reworked and rear drives now correctly reference the disks that belong to that chassis.

NAS-108211 / 12.0 / NAS-108211

---

src/app/pages/common/entity/entity-table/entity-table.component.ts
src/app/pages/storage/snapshots/snapshot-list/snapshot-list.component.ts
src/app/pages/storage/volumes/datasets/dataset-quotas/dataset-quotas-grouplist/dataset-quotas-grouplist.component.ts
src/app/pages/storage/volumes/datasets/dataset-quotas/dataset-quotas-userlist/dataset-quotas-userlist.component.ts

git cherry-pick -x 1046d367c0514c5791fe7792e50f995b4443d8ba
git cherry-pick -x 8663bf715c7beef15afe53cc0aee64a18b7027ab
Prevent row resize and auto sort for entity table when handleData is called outside of page load
Original PR: https://github.com/freenas/webui/pull/4767

NAS-107889 / 20.12 / Nas 107889 (by dkmullen)

---

src/app/helptext/storage/volumes/volume-list.ts
src/app/pages/storage/volumes/volumes-list/volumes-list.component.html
src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts

git cherry-pick -x 0238cacdacb24f913ebfd96b81709d915f8ef720
git cherry-pick -x 5f878be37f4946db6f1bd227e9c2ed7bc9a73b87
git cherry-pick -x 8a1cb62d9bf8daa410db86ed367388f8699e7850
git cherry-pick -x 4c961589ad89ac98c9c66de2bf85971baec9cb64
Could use more from docs team on a specific warning of any dangers of detaching the sys dataset pool. 
Original PR: https://github.com/freenas/webui/pull/4805

NAS-107948 / 12.0 / NAS-107948 Add sys dataset warnings (by dkmullen)

---

src/app/pages/system/CloudCredentials/cloudcredentials-form/cloudcredentials-form.component.ts

pCloud hostname is not sent when verifying credentials

NAS-108500 / 12.0 / fix pCloud hostname is not sent when verifying credentials

---

src/app/pages/task-calendar/cron/cron-list/cron-list.component.ts

Remove the piece of code that replaces "no" to "false" in the CRON table component

NAS-108628 / 12.0 / Keep yes/no enabled column for consistency

---

src/app/pages/credentials/backup-credentials/forms/cloud-credentials-form.component.ts

pCloud hostname is not sent when verifying credentials
Original PR: https://github.com/freenas/webui/pull/4934

NAS-108500 / 21.02 / fix pCloud hostname is not sent when verifying credentials (by AlexKarpov98)

---

src/app/pages/task-calendar/cron/cron-list/cron-list.component.ts

Remove the piece of code that replaces "no" to "false" in the CRON table component
Original PR: https://github.com/freenas/webui/pull/4963

NAS-108628 / 21.02 / Keep yes/no enabled column for consistency (by denysbutenko)

---

src/app/core/components/widgets/widgetcpu/widgetcpu.component.css
src/app/core/components/widgets/widgetcpu/widgetcpu.component.html

The issue with stacking text due to `-webkit-transform-style: preserve-3d;` on https://github.com/freenas/webui/blob/f475e51734c9b79eb49649218510b226b0d02769/src%2Fassets%2Fstyles%2Fegret_overrides.css#L197

NAS-108464 / 12.0 / Fix issue with text in Safari

---

src/app/pages/common/entity/entity-form/services/field-relation.service.ts

Add back checking for `null` since `typeof null == 'object'`

NAS-109275 / 21.02 / Fix object detection in getDataType

---

src/app/pages/credentials/certificates-dash/certificates-dash.component.ts

This PR renames `ACME DNS Authenticators` to `ACME DNS-Authenticators`.
To put more emphasis on the fact it's a list of "DNS-Authenticators", not "ACMEdns Authenticators" (which is also commonly writhen as "ACME-DNS authenticators")

NAS-109667 / 21.04 / Rename "ACME DNS Authenticators"

---

src/app/pages/credentials/certificates-dash/forms/certificate-acme-add.component.ts

Currently the ACME creation modal looks like this:
This is obviously not acceptable.
This PR changes it to look like this instead:
It's a relatively simple fix with no expected side effects.

NAS-109975 / 21.04 / Cleanup the Domain_list when doing ACME creation

---

src/app/pages/applications/forms/chart-release-add.component.ts

externalInterfaces can now be left out of the form when adding (i.e. no empty external interface needs to be given when it is not needed).

NAS-109847 / 21.04 / Cannot create docker containers without some fields / NAS-109847

---

src/app/pages/storage/volumes/volumes-list/volumes-list-controls.component.html

The "Create" button might not be clear enough on what people are actually creating.
As it's on the big "Storage" overview, it's not 100% clear it means "Create a Pool" unless people take the time to view the tooltip or read the manual.
In other windows, the "Big Blue Button", is expected to be read as an addition to the page title.
For example:
Sharing AFP - Add
But for storage this causes confusion because it's read like:
Storage - Create
But you're not "Creating" storage, but creating a new pool.
An example of such a confused user can be found here:
https://www.truenas.com/community/threads/can%E2%80%99t-add-l2arc-or-slog-in-anglefish.92968/#post-643677
(and to be honest: I understand why he is confused looking at the screenshot)

rename "Create" in storage overview to "Create Pool"

---

src/app/interfaces/dialog.interface.ts
src/app/pages/account/users/user-list/user-list.component.ts
src/app/services/dialog.service.ts

To test:
* Find any old confirm modal (for example top bar -> reboot)
* Test new confirm modal (User list -> Toggle built in users with gear icon)

NAS-110328 / 21.06 / NAS-110328: Refactoring confirm action in DialogService to simplify it

---

src/app/components/common/topbar/topbar.component.ts
src/app/interfaces/dialog.interface.ts
src/app/services/dialog.service.ts

git cherry-pick -x e35c079f5525a65dc52b1bc472febdf88631ce8d
To test:
* Find any old confirm modal (for example top bar -> reboot)
* Test new confirm modal (User list -> Toggle built in users with gear icon)
Original PR: https://github.com/truenas/webui/pull/5405
Jira URL: https://jira.ixsystems.com/browse/NAS-110328

NAS-110328 / 12.0 / NAS-110328: Refactoring confirm action in DialogService to simplify it (by undsoft)

---

src/app/pages/applications/forms/catalog-add-form.component.ts

"main" is the current default for github, as people make more community catalogs, it's likely most are made on github.
Note:
Someone confirmed thats also the default for gitlab.

[Apps] Change default catalog branch to main

---

src/app/pages/system/advanced/advanced.component.ts

Pass 4th argument {{true}} to {{core.download}} when requesting debug. Display debug generation progress as usual, but only start downloading when job is finished.

NAS-109976 / 12.0 / Changes in debug generation process:

---

src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.html
src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.ts
src/app/pages/system/viewenclosure/view-enclosure.component.html
src/app/pages/system/viewenclosure/view-enclosure.component.ts

- Use enclosure.query's has_slot_status to determine if rear bays are identifiable.
- Enclosure Selector UI should only be visible if there are actually multiple enclosures. I noticed it was showing on M Series due to M series reporting rear bays as a separate chassis. This is now fixed

NAS-110603 / 12.0 / Fix identify button and enclosure selector issues

---

src/app/enums/dns-authenticator-type.enum.ts
src/app/enums/schema.enum.ts
src/app/interfaces/api-directory.interface.ts
src/app/interfaces/dns-authenticator.interface.ts
src/app/interfaces/schema.interface.ts
src/app/pages/credentials/certificates-dash/certificates-dash.component.ts
src/app/pages/credentials/certificates-dash/forms/acmedns-form.component.ts
src/app/pages/credentials/certificates-dash/forms/certificate-acme-add.component.ts

How to test:
Credentials -> Certificates -> ACME DNS-Authenticators
When cloudflare is selected, either 'email' + 'API key' or 'API token' need to be added, but not both.
There was a bug when user touched email field, but then cleaned it, and actually filled in API token.
Plus, would be good to do general regression testing on the form.

NAS-110459 / 21.06 / NAS-110459: Fixing DNS Authenticator form in some scenarios

---

src/app/core/components/widgets/widgetcpu/widgetcpu.component.ts

A new temperature_celsius stat was added to reporting.realtime and it was breaking the cpu widget.
To test this PR, please make sure the cpu widget on dashboard does not throw console errors in the following scenarios.
- CPUs with hyperthreading
- CPUs without hyperthreading
- Machines that don't report CPU temperatures (VMs)

NAS-110860 / 12.0 / Tweak settings for new temperature_celsius stat

---

src/app/pages/common/entity/entity-form/components/form-select/form-select.component.ts

Fix for `[object Object]` in form-select component.
How to test it?
- Go to Credentials -> Local Users -> Edit user and check "Disable Password" menu items.
- Go to Data Protection -> Add Replication Task  -> Check "Load Previous Replication Task" menu items

NAS-110917 / None / Fix [object Object] in dropdown menu

---

src/app/pages/common/entity/entity-form/components/form-select/form-select.component.ts
src/app/pages/vm/vm-wizard/vm-wizard.component.ts

Testing:
- Make sure that when creating a VM there is no "[Object object]" in CPU Model dropdown.
- Make sure that CPU Model is only shown when CPU Mode = Custom.

NAS-110960 / None / NAS-110960 - Fixing CPU Model dropdown

---

src/app/pages/common/entity/entity-form/entity-form.component.scss

[Original PR](https://github.com/truenas/webui/pull/5557) was based on `release/21.06-BETA.1` branch. This one is on top of `master` branch.
> The problem is entity-form adds global styles when opening a wizard. It affects .mat-content class in the volume list so that styles should be isolated into components.
> 
> How to test?
> * Open the Storage page, click the Import button, and then check the volume header it shouldn't be sticky to the top.
> * Please check the video in JIRA ticket

NAS-110981 / 21.08 / Fix text alignment on volume list

---

src/app/pages/common/entity/entity-form/entity-form.component.ts
src/app/pages/storage/volumes/datasets/dataset-acl/dataset-acl.component.ts
src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
src/app/pages/storage/volumes/datasets/dataset-permissions/dataset-permissions.component.ts
src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
src/app/pages/storage/volumes/zvol/zvol-form/zvol-form.component.ts

NAS-105663
How/What to test:
- Create nested datasets in a pool
- Go to any level of choice in datasets and open 'Edit Options' or 'Edit Permission' or 'Acl Manager' pages on that dataset
- When you come back after cancelling or successfully saving the settings, the exact same dataset should be expanded automatically
e.g.,
If you have the following datasets in your pool
`pool`
- `ds` -> `ds-ds` -> `ds-ds-ds`
- `dss` -> `dss2`
Currently, when you go to `Edit Options` or `Edit Permissions` or `Acl Manager` page for dataset `ds-ds` and come back by cancelling or saving your changes, all the datasets are automatically collapsed.
With these changes, when you go to edit any aforementioned settings on `ds-ds` dataset and come back to the pools page by cancelling or saving those settings, the …

NAS-105663 / 12.0 / The dataset will be expanded after coming back from 'Edit Options' or 'Edit Permission' pages

---

src/app/pages/common/entity/entity-table/entity-table.component.html
src/app/pages/common/entity/entity-table/entity-table.component.ts
src/app/pages/storage/snapshots/snapshot-list/snapshot-list.component.ts

NAS-110760
What to test
- Selecting values on the table should trigger `indeterminate` state on the multi-select checkbox in the table header
- Selecting all values one by one or clicking the multi-select checkbox should select all the rows currently visible on the screen and only those rows. i.e., rows from other pages or filtered out rows shouldn't be selected
- De-selecting one row should put the multi-select checkbox back into `indeterminate` state
- Check if changing the `rowIdentifier` for `SnapshotsListComponent` has had any effect on that page
- Multi-select now depends on the `rowIdentifier` or `'name'` field in either/or relationship. If `rowIdentifier` is not set `'name'` field will be used
- Other components that use multi-select should have the unique `rowIdentifier` too …

NAS-110760 / 21.08 / Making multiselect respect pagination and filter

---

src/app/pages/system/CloudCredentials/cloudcredentials-form/cloudcredentials-form.component.ts

**Setup:**
1. `docker pull openstackswift/saio`
2. `docker run -d -p 8080:8080 openstackswift/saio`
2. If you are using local middleware, you can skip this test. Otherwise you need to expose local openstackswift to the world. You can do this by setting up a tunnel with https://ngrok.com. Something like `ngrok tcp 8080`
3. Go to System -> Cloud Credentials -> Add.
4. Add a new OpenStack Swift credential, where 
UserName: `test:tester`
Password: `testing`
Auth URL: If local: `http://127.0.0.1/auth/v1.0`, otherwise `http://ngrokurlandport/auth/v1.0`, something similar to `http://8.tcp.ngrok.io:16358/auth/v1.0`
Auth Version: `v1`
Tenant Name: `test`
5. Verify Credentials.
**To test:**
- That Advanced options change when Auth Version is changed.
- That when form is saved and then edited, Auth …

NAS-110665 / 12.0 / NAS-110665 - Fixing cloudcredential form + OpenStack Swift

---

src/app/pages/system/general-settings/gui-form/gui-form.component.ts

NAS-111460
To Test
1. Open the GUI Settings form in the System -> General Settings page
2. On the form, previous data should load Ok and you shouldn't see empty fields

NAS-111460 / 21.08 / Fixed bug with wrong reassignment of variable

---

src/app/pages/common/entity/entity-form/components/form-radio/form-radio.component.html
src/app/pages/common/entity/entity-form/components/form-radio/form-radio.component.ts
src/app/pages/common/entity/entity-form/models/field-config.interface.ts
src/app/pages/storage/volumes/permissions/components/edit-nfs-ace/edit-nfs-ace-field-set.ts

Testing:
- ACL editor should have inline radio buttons for the "ACL Type", "Permissions Type" and "Flags Type" fields.
- Make sure other forms with radios keep column layout by default. (Import disk form is a good one to test)
- When browser window gets too narrow, inline radio buttons should revert to column layout

NAS-111469 / 21.08 / Add inline options for form-radio.

---

src/app/pages/common/entity/entity-form/components/form-radio/form-radio.component.html

Testing: When present, tooltip component (?) icon should be inline with radio buttons. eg. `system/email` form

NAS-111617 / 21.08 / Apply flex layout to radio button and tooltip

---

src/app/core/components/widgets/widget-cpu/widget-cpu.component.ts

To test:
- use tn33 for backend and hover over bar chart in cpu widget.
- Make sure the legend items stay in one line (no line breaks) and bar chart is never cut off

NAS-111165 / 21.08 / Keep cpu widget stats to whole numbers

---

src/app/interfaces/api-directory.interface.ts
src/app/interfaces/pool-remove.interface.ts
src/app/pages/storage/volumes/volume-status/volume-status.component.ts

How to test:
- Go to the Storage page
- Create a new pool with 2 disks and pick `STRIPE`
- Click on pool options and choose `Status`
- Click the three dots menu on disk and choose `Remove`
You'll see something like:

NAS-111414 / 21.08 / Treat removing vdev in the UI as a job

---

src/app/enums/acl-type.enum.ts
src/app/pages/storage/volumes/permissions/containers/dataset-trivial-permissions/dataset-trivial-permissions.component.ts
src/app/pages/storage/volumes/permissions/containers/permissions-sidebar/permissions-sidebar.component.html
src/app/pages/storage/volumes/permissions/containers/permissions-sidebar/permissions-sidebar.component.ts

Two things to test:
1. Root dataset in every pool should not have pencil edit icon in view permissions sidebar.
2. If you create dataset with acltype = OFF, and then go to edit permissions, you should not see Set ACL button. You should still see this button on datasets with other acltype.

NAS-111284 / 21.08 / NAS-111284 - Do not allow root dataset to be edited

---

src/app/components/common/topbar/topbar.component.ts
src/app/core/services/disk-state.service.ts
src/app/pages/system/viewenclosure/view-enclosure.component.ts

Testing:
- Remove a disk from a pool that has a spare
- Put the disk back
- Make sure the resilver icon shows up on the topbar
- The disk should reappear and should be presented as part of the pool again AFTER the resilver process completes

NAS-111431 / 12.0 / Enclosures should listen for global resilver events

---

src/app/core/components/widgets/widget-network/widget-network.component.html
src/app/core/components/widgets/widget-network/widget-network.component.scss
src/app/core/components/widgets/widget-network/widget-network.component.ts

Changes:
- fix empty IP addresses
- replace `IP Addresses: 0` with `IP Addresses: –` when no data is available
- alignment for interface name and report icon
- added icon for IP addresses when nics > 1 
- display `(+1)` if there are >= 2 IP addresses is available 
- align entity-empty on center
Preview:

NAS-111749 / 21.08 / Fix empty IP addresses on network widget

---

src/app/services/ws.service.ts

Steps to reproduce.
1) Create VM with two pools
2) SSH into server and `cd /var/db/system/samba4`
3) Move system dataset to a different pool via System/Advanced page
4) Form should show dialog with traceback message (as opposed to silently failing like it does currently)

NAS-111755 / 21.08 / Job should call error method when job is FAILED

---

src/app/enums/acl-type.enum.ts
src/app/interfaces/api-directory.interface.ts
src/app/pages/sharing/smb/smb-form/smb-form.component.ts
src/app/pages/storage/volumes/permissions/components/select-preset-modal/select-preset-modal.component.ts
src/app/pages/storage/volumes/permissions/containers/dataset-acl-editor/dataset-acl-editor.component.ts
src/app/pages/storage/volumes/permissions/interfaces/select-preset-modal-config.interface.ts

1. Use cloud vm for testing. I've hot-pached middleware there with latest changes.
2. Create datasets with POSIX and NFS acl type.
3. Create SMB share in Sharing dashboard pointing at NFS dataset. Use Purpose that will allow you to enable Home Share in advanced settings.
4. You should get redirected to an acl editor with some aces already preset.
5. Delete share and create new pointing to POSIX dataset.
6. Check that Use Preset button acl editor works.

NAS-111465 / 21.08 / NAS-111465 - Redirect to an ACL Editor after home share is created

---

src/app/pages/credentials/backup-credentials/forms/cloud-credentials-form.component.ts

This hides all keys and tokens that are visible in the Backup Credentials panels to avoid inadvertently exposing them.

NAS-0: Hide Backup Credential tokens & keys

---

src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts

This PR hides the encryption password and salt on Cloud Sync pages, in the same way as all other secret fields elsewhere in the UI.

NAS-0: Hide Cloud Sync encryption key & salt

---

src/app/pages/common/entity/entity-form/entity-form.component.ts

Basically in every place where we have tabs and navigate away from entity-form to something else the loader would not close.
Multiple places to check:
1. Services -> Rsync -> Rsync Modules
2. Sharing -> iSCSI Configure -> Targets

NAS-111877 / 21.10 / NAS-111877: Closing loader after navigating to Rsync Module form.

---

src/app/pages/common/entity/entity-form/entity-form.component.ts

Basically in every place where we have tabs and navigate away from entity-form to something else the loader would not close.
Multiple places to check:
1. Services -> Rsync -> Rsync Modules
2. Sharing -> iSCSI Configure -> Targets
Original PR: https://github.com/truenas/webui/pull/5805
Jira URL: https://jira.ixsystems.com/browse/NAS-111877

NAS-111877 / 21.08-BETA.1 / NAS-111877: Closing loader after navigating to Rsync Module form. (by undsoft)

---

src/app/core/classes/system-profiler.ts

PR testing needs iX rackmount hardware with enclosure support and a pool with spares. (tn27 should be preconfigured)
To test, simply make sure the spares are being presented as members of the pool.

NAS-111931 / 21.10 / NAS-111931: Adapt disk name retrieval to Linux naming conventions

---

src/app/helptext/apps/apps.ts
src/app/pages/applications/catalog/catalog.component.ts
src/app/pages/applications/forms/chart-form.component.ts
src/app/pages/applications/forms/chart-wizard.component.ts

The dialog has the following changes:
- On `Available Apps` or `Manage Catalog` when `Refresh All` is clicked: `Installing` -> `Refreshing`
- Chart Form that uses `editCall` endpoint: `Installing` -> `Updating`

NAS-111627 / 21.10 / APPS: Update text on dialog title

---

src/app/core/services/api.service.ts

git cherry-pick -x 908c9dc6e63b5c07ea18ed7b0a6df38bc34bfc79
And this is why, kids, you don't mutate variables.
Original PR: https://github.com/truenas/webui/pull/5870
Jira URL: https://jira.ixsystems.com/browse/NAS-112160

NAS-112160 / 21.10 / NAS-112160: Fixing enclosure page after using dashboard widget (by undsoft)

---

src/app/pages/sharing/iscsi/target/target-form/target-form.component.ts
src/assets/styles/other/_material-reduction.scss

NAS-112015
To test
Check out the ISCSI targets form on the Shares Dashboard. The list items should be well spaced out and one per line so they're easily usable.

NAS-112015 / 21.10 / NAS-112015: Fixed width on list items to create more space for elements

---

src/app/pages/applications/dialogs/chart-upgrade/chart-upgrade-dialog.component.scss

This changes the size of the changelog displayed from a fixed 150px to 40vh.
It's tested by making the screen smaller and bigger and on smaller screens (up to about 500 height) it responds about the same as 150px fixed, but on bigger screens it gives significantly more reading-room.
In the future this can be increased even further, but currently that is not possible due to NAS-112313, as setting the height to 50-60vh increases the display size at which the overlapping buttons from NAS-112313 appear.
**Why turn the colors around?**
Having the right-side text portion (label) white, turned out to extremely highlight the fact it was below the App name. Turning the colors around removed that annoying effect.
It also fitted within the theme of this section, where previously the important things …

NAS-112312 / 21.10 / determine changelog size dynamically

---

src/app/pages/common/entity/entity-table/entity-table.component.scss
src/app/pages/common/entity/table/table.component.scss
src/app/pages/system/advanced/advanced-settings.component.html
src/assets/styles/index.scss
src/assets/styles/other/_helpers.scss

How to test?
1. Go to `System Settings -> Advanced`
2. Update `MOTD Banner` using the example below
```
████████ ██████  ██    ██ ███████ ███    ██  █████  ███████ 
██    ██   ██ ██    ██ ██      ████   ██ ██   ██ ██      
██    ██████  ██    ██ █████   ██ ██  ██ ███████ ███████ 
██    ██   ██ ██    ██ ██      ██  ██ ██ ██   ██      ██ 
██    ██   ██  ██████  ███████ ██   ████ ██   ██ ███████                                                 
```

NAS-112283 / 21.10 / NAS-112283: Fix text overflow for motd banner

---

src/app/pages/reportsdashboard/components/report/report.component.css
src/app/pages/reportsdashboard/components/report/report.component.html
src/app/pages/reportsdashboard/components/report/report.component.ts
src/app/pages/reportsdashboard/reports-utils.worker.ts
src/app/pages/reportsdashboard/reports.service.ts

Manual port of #5885
Preview:
How to test?
- Go to `Shell`
- Update system time to future, type `date 2110011307` for example
- Clear reporting database `midclt call reporting.clear`
- Go to Reporting, wait a couple of minutes to collect some data
- Reboot the system, type `reboot`
- Wait until the system is loaded
- Go to Reporting
- Fix reporting database
FreeBSD behaves differently from Debian, you may notice a warning in shell:
```
Warning: settings changed through the CLI are not written to the configuration database and will be reset on reboot.
```
It means if you change the date and make a reboot it will revert date changes.
So, the idea is to set the future time, then reset reporting database, collect some data, and then make a reboot. The date will be reverted and you'll get …

NAS-112109 / 12.0 / Handling broken reporting database

---

src/app/pages/applications/chart-releases/chart-releases.component.ts
src/app/pages/applications/dialogs/chart-events/chart-events-dialog.component.scss

With this PR the width of the Chart-Status and Upgrade modals are made more dynamic.
The minimum width is set to the current fixed-width, while the maximum is set a few hunderd pixels higher.
In between the size will be based on 50vh.
This also ports the recent patch that shows more of the Release notes, to the chart summary, primarily the app eventlog.
It basically solves the remaining issues regarding sizing of those modals as stated in NAS-112068
**Example showing the combined effect of these measures on a 4K display:**

NAS-112068 / 21.10 / Dynamic width of chart update/status and eventlog.

---

src/app/pages/storage/volumes/permissions/containers/dataset-acl-editor/dataset-acl-editor.component.ts

NAS-112158
Test "Apply Permissions Recursively" and "Apply permissions to child datasets" fields in ACL Editor by setting them to different pairs of values.

NAS-112158 / 21.10 / NAS-112158: Fetched latest values from FormControl instead of config

---

src/app/views/others/reboot/reboot.component.html
src/app/views/others/reboot/reboot.component.ts
src/app/views/others/shutdown/shutdown.component.html
src/app/views/others/shutdown/shutdown.component.ts

Testing:
1. Reboot the system via topbar menu.
2. Observe that you see a blue reboot screen as opposed to being redirected to a disconnected page right away.
3. Observe that URL is changed to signin, so that if user reloads, he will not trigger reboot again.

NAS-112298 / 21.10 / NAS-112298: Make reboot page more reliable

---

src/app/pages/common/entity/entity-form/components/form-input/form-input.component.ts
src/assets/styles/other/_material-reduction.scss
src/assets/styles/other/_tn-styles.scss

Hide reset button and update cursor and opacity for disabled inputs
Testing: Go to Storage and choose Edit Options of some dataset, it is a good example

NAS-112033 / 21.10 / NAS-112033: Hide reset button on disabled inputs

---

src/app/pages/network/forms/interfaces-form.component.ts

Use a form in Network -> Interfaces and check that correct `type` is now sent to middleware for every IP Address (alias).

NAS-112363 / 21.10 / NAS-112363: Sending IP type when editing an interface

---

src/app/pages/applications/applications.component.html
src/app/pages/applications/applications.component.ts
src/app/pages/applications/catalog/catalog.component.ts
src/app/pages/applications/chart-releases/chart-releases.component.ts

This changes the default tab for the Applications interface when clicking "Apps" from the Menu to "Installed Applications".
**Confirmed working when used with pre-configured pool:**
- Clicking "Apps in the Nav menu" -> lands on "Installed Applications"
- Switching between all possible tab combinations
- Using the bulk tools in  "Installed Applications"
- Referesh button on "Available Applications" 
- setup modal
- poolselector pop-up
Might need (considerable?) extra work for the pool selection popup on new systems though, which isn't my strongsuit, Feel free to fork and finish if so :)

NAS-112057 / 21.10 / Apps: Make "Installed Applications" the default tab

---

src/app/pages/applications/applications.component.scss
src/app/pages/applications/catalog/catalog.component.html
src/app/pages/applications/chart-releases/chart-releases.component.html

As explained in NAS-112059 people are too easily confused between official and community Apps at the moment.
This PR gives two color options:
- Official in a combination of iX Blue and Dark blue
- Community in Yellow and the original disgusting dark yellow.
For Bluefin this, most likely, would need to be redesigned to deal with more than just two color options, but for Anglefish this solves the problem without too much code redundency imho.
**Before:**
**After:**

NAS-112059 / 21.10 / Use iX Blue + Dark Blue for official Apps

---

src/assets/styles/other/_tn-styles.scss

style improvements for trackback area
before:
after:

NAS-112560 / 21.10 / NAS-112560: Preserve whitespace and use monospace font

---

src/app/pages/common/entity/entity-table/entity-table-add-actions/entity-table-add-actions.component.html
src/app/pages/common/entity/entity-table/entity-table-add-actions/entity-table-add-actions.component.ts
src/app/pages/storage/volumes/volume-list-controls/volumes-list-controls.component.html
src/app/pages/storage/volumes/volume-list-controls/volumes-list-controls.component.scss
src/assets/styles/other/_tn-styles.scss

Changes:
- Added missing clear button for the entity-table-actions component
- Added missing spinner for volume-list-actions component (the only one loading indicator on that page)
- Moved spinner to the end on the actions toolbar
- Sync styles
To test:
- Check the search field on the Storage and Snapshots (or another entity table) pages
- Check spinner on the actions toolbar (Storage/Snapshots)

NAS-112588 / 21.10 / Add missing clear button on the search field

---

src/app/pages/common/entity/entity-table/entity-table.component.html
src/app/pages/common/entity/entity-table/entity-table.component.ts
src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts

To test:
- create 500+ snapshots.
- go to storage/snapshots
- make sure the table loads in a reasonable amount of time. 
For context, my machine was originally loading 595 snapshots in 5+ seconds and now it is down to 1 second or less)

NAS-112166 / 21.10 / NAS-112166: Replace setTimeouts w/Observable stream and use OnPush strategy

---

src/app/pages/data-protection/replication/replication-wizard/replication-wizard.component.ts

To test:
- Pull up the Replication Wizard from the Data Protection page
- Set your source or destination to "On aDifferent System"
- Set the "SSH Connection" field to "Create New"
- This will generate a dialog that contains a form with a "Private Key"  select field. Make sure that field's first option is "Generate New" and select it.
- Submit the form and the next time you try to go through the wizard, the SSH Connection you just created should be available in the form

NAS-112820 / 22.02-RC.2 / NAS-112820: Concat instead of map to retain Generate New option

---

src/app/pages/storage/volumes/volume-status/volume-status.component.ts

Smallest PR ever.
To test: create a pool with a spare, on dashboard in Storage widget click on drive icon to get to pool status page. Observe that it's not broken.

NAS-112801 / 22.02-RC.1 / NAS-112801: Fixing pool status page when pool has spares

---

src/app/pages/dashboard/components/widget-network/widget-network.component.ts
src/app/pages/reports-dashboard/components/report/report.component.ts

Changes:
- Do not show `reporting database is broken` message for InvalidExport error
Testing:
On the Reporting or Network widget on the main dashboard, make sure that `The reporting database is broken` message with action to fix database is appeared only when middleware returns error with code 206 (EINVALIDRRDTIMESTAMP)

NAS-112920 / 22.02-RC.2 / NAS-112920: Fix reporting database message

---

src/app/pages/dashboard/components/widget-network/widget-network.component.ts
src/app/pages/reports-dashboard/components/report/report.component.ts

Changes:
- Do not show `reporting database is broken` message for InvalidExport error
Testing:
On the Reporting or Network widget on the main dashboard, make sure that `The reporting database is broken` message with action to fix database is appeared only when middleware returns error with code 206 (EINVALIDRRDTIMESTAMP)
Original PR: https://github.com/truenas/webui/pull/6036
Jira URL: https://jira.ixsystems.com/browse/NAS-112920

NAS-112920 / 22.02-RC.1 / NAS-112920: Fix reporting database message (by denysbutenko)

---

src/app/pages/directoryservice/idmap-form/idmap-form.component.ts

To test, on TrueNAS Core, go to `Directory Services` -> `Active Directory` -> `Advanced Options` -> `Edit Idmap` -> `Add`
Next, on the field named `Idmap Backend` select the option `RCF2307`. Check that the relevant fields have correct types. Also check form submission.

NAS-113000 / 12.0 / Fixed idmap form

---

src/app/pages/applications/kubernetes-settings/kubernetes-settings.component.html
src/app/pages/applications/kubernetes-settings/kubernetes-settings.component.spec.ts
src/app/pages/applications/kubernetes-settings/kubernetes-settings.component.ts

This is the UI portion of the changes proposed here:
https://github.com/truenas/middleware/pull/7834
Submitted as draft, till above PR is merged...
Once https://github.com/truenas/middleware/pull/7834 is merged, this can be used for users to easily disable the default integrated loadbalancer without issue to run their own prefered loadbalancer.
It's important to note why the text refers to "Integrated Loadbalancer", which might seem vague.
However: It is refered to either "ServiceLB" and "Klipper" all-over-the-place and neither name is very descriptive, so just calling it the "integrated loadbalancer" might be the most descriptive option. The target users (who want to run their own Loadbalancer) most likely already knows what this refers to anyway.
**Screenshot of the proposed change:**

NAS-111019 / 22.02-RC.2 / Allow Kubernetes ServiceLB to be turned off

---

src/app/core/classes/hardware/r50b.ts

To test, go to tn30 and check the rear view of the R50B enclosure.
There should only be 2 drive slots in there.

NAS-113386 / 12.0 / R50B only has 2 rear slots

---

src/app/pages/storage/volumes/permissions/components/view-trivial-permissions/trivial-permissions.component.ts
src/app/pages/storage/volumes/permissions/containers/permissions-sidebar/permissions-sidebar.component.ts

The ticket has a description of the issue. Check if the 'User ID: 111' seems like a good idea for trivial permissions in the sidebar when the user/group has been deleted. Or should it just be '111'

NAS-112427 / 22.02-RC.2 / NAS-112427: Fixed ACL group name when group is deleted

---

src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts

To test check that
For Cloud Sync direction `PULL`
1. When one directory is selected, the full path of that directory is set to `payload.attributes.folder`
2. When more than one directories are selected the parent directory's path is set to `payload.attributes.folder` and the children directories are set to `payload.include` array. E.g., for selected directories
- `/parent/child-1`
- `/parent/child-2`
`payload.attributes.folder` should hold `'/parent'` and `payload.include` should hold `[ '/child-1/**', '/child-2/**' ]`
3. `payload.path` should hold the destination directory
For Cloud Sync direction `PUSH`
1. When one directory is selected, the full path of that directory is set to `payload.path`
2. When more than one directories are selected the parent directory's path is set to …

NAS-113589 / 22.02-RC.2 / NAS-113589: Fixed payload for api call

---

src/app/components/common/layouts/admin-layout/admin-layout.component.ts
src/app/components/common/navigation/navigation.component.html
src/app/components/common/topbar/topbar.component.ts
src/app/core/services/preferences.service.ts
src/app/interfaces/events/sidenav-status-event.interface.ts
src/app/interfaces/preferences.interface.ts
src/assets/styles/other/_fn-styles.scss
src/assets/styles/other/_tn-styles.scss

Changes:
- Save the sidenav state when clicking on the hamburger icon to user preferences and restore it on each page reload
- Fix 6px pixels on left when hovering on menu items when `collapsed: false`
- Fix 6px pixels on right  when `collapsed: true`
- Fix tooltip position for some items when `collapsed: true`
Known issues:
- Sometimes, you may see slide-out animation on page reload when the sidenav collapsed
Testing:
- Make sure these changes do not introduce new bugs
- Try to switch between Mobile / Desktop and check how it is going

NAS-113604 / 22.02-RC.2 / Keep sidenav state in user preferences

---

src/app/pages/common/entity/table/table.component.html
src/app/pages/common/entity/table/table.component.scss
src/app/pages/data-protection/components/data-protection-dashboard/data-protection-dashboard.component.ts

Changes:
- Remove `this.parent` references
- Style improvements for loading and empty states (added some space)
Testing:
- Make sure that the dashboard can load each card successfully.
- Extra check for the Cloud Sync Tasks when some task is disabled

NAS-113607 / 22.02-RC.2 / NAS-113607: Fix data protection dashboard

---

src/app/components/common/layouts/admin-layout/admin-layout.component.ts
src/app/enums/api-event-message.enum.ts
src/app/pages/applications/pod-logs/pod-logs.component.ts
src/app/pages/common/entity/entity-form/entity-form.component.ts
src/app/pages/common/entity/entity-job/entity-job.component.ts
src/app/services/app-loader/app-loader.component.html
src/app/services/app-loader/app-loader.component.ts
src/app/services/ws.service.ts

To test,
1. Go to `System Settings` -> `General` -> `GUI Settings` and make sure `Show Console Messages` checkbox is checked before saving.
2. Go to `Shares` -> `Block (iSCSI) Shares Targets` Configure and on the next page, `Total Global Configuration` tab selected, just tap on `Save` button. The loader should open. Here I've added a delay of 10 seconds so testing this PR is easier. (Will remove the delay before merging). The loader should be showing the `Console` button underneath the spinner. Click on that button.
3. Previously, opening the console dialog like this would cause the UI to completely crash and reload. It shouldn't happen now.
Let me know if there are any questions.

NAS-110535 / 22.02 / NAS-110535: Custom subscription to console messages

---

src/app/interfaces/api-directory.interface.ts
src/app/pages/services/components/service-tftp/service-tftp.component.ts

For testing, go to Settings -> Services -> TFTP (click edit) -> Host
Note: I tested it against the cloud VM that patched manually to add a new endpoint.
Related MW PR: https://github.com/truenas/middleware/pull/7951

NAS-113716 / 22.02 / NAS-113716: Host needs to be a dropdown in TFTP service configuration form

---

src/app/pages/storage/volumes/datasets/dataset-unlock/unlock-dialog/unlock-dialog.component.ts

To test,
1. Create encrypted datasets on a pool
2. Export dataset keys from the pool `cog` icon drop down. (Not dataset three dot menu)
3. Export/Disconnect the pool
4. Import the same pool again
5. You should see a prompt that asks if you want to unlock your locked datasets
6. Click on `Continue`
7. Provide the dataset keys json file you downloaded in step 2
8. Click on save and follow the process.
9. On the last `Close` button when you're done unlocking datasets, you should be navigated to the `Storage` page again automatically

NAS-113598 / 22.02-RC.2 / NAS-113598: Added navigation on cancel click

---

src/app/pages/storage/volumes/datasets/dataset-unlock/unlock-dialog/unlock-dialog.component.ts

To test,
1. Create encrypted datasets on a pool
2. Export dataset keys from the pool `cog` icon drop down. (Not dataset three dot menu)
3. Export/Disconnect the pool
4. Import the same pool again
5. You should see a prompt that asks if you want to unlock your locked datasets
6. Click on `Continue`
7. Provide the dataset keys json file you downloaded in step 2
8. Click on save and follow the process.
9. On the last `Close` button when you're done unlocking datasets, you should be navigated to the `Storage` page again automatically
Original PR: https://github.com/truenas/webui/pull/6189
Jira URL: https://jira.ixsystems.com/browse/NAS-113598

NAS-113598 / 22.02 / NAS-113598: Added navigation on cancel click (by RehanY147)

---

src/app/pages/common/entity/entity-form/components/dynamic-field/dynamic-field.scss
src/app/pages/system/email/email.component.ts

Test that both Gmail and ordinary email forms can be saved in Alerts -> Email.
Requires fresh middleware.

NAS-113701 / 22.02-RC.2 / Alerts email form

---

src/app/pages/common/entity/entity-form/components/dynamic-field/dynamic-field.scss
src/app/pages/system/email/email.component.ts

Test that both Gmail and ordinary email forms can be saved in Alerts -> Email.
Requires fresh middleware.
Original PR: https://github.com/truenas/webui/pull/6196
Jira URL: https://jira.ixsystems.com/browse/NAS-113701

NAS-113701 / 22.02 / Alerts email form (by undsoft)

---

src/app/pages/jails/jail-form/jail-form.component.ts
src/app/pages/jails/jail-wizard/jail-wizard.component.ts

To test,
- Go to the jails page and click on the `Add` button to create a new jail
- Click on the `Advanced Jail Creation` button
- Select an `IPv4 Interface` and type in an IP that's already in use by the system. (It can be the ip that your NAS system points to. E.g, 192.168.18.21).
- Add a name for the jail and select any release version
- Click on save and you should see the validation error returned by middleware in red under the relevant form field.
- Do the same for the Jail creation wizard by clicking `Next` on step 2
Previously the error failed to appear under the form field. The flashing dialog is intentional. This is what was meant to happen.

NAS-110348 / 13.0 / Fixed property name returned from middleware on error to remove dots

---

src/app/pages/system/view-enclosure/enclosure-disks/enclosure-disks.component.ts
src/app/pages/system/view-enclosure/view-enclosure.component.scss
src/app/pages/system/view-enclosure/view-enclosure.component.ts

There was a typo in the code due to two different variables with similar names. Correct variable is now being referenced with a more distinct and obvious name to avoid future issues. Also some error handling was added to deal with scenarios where middleware doesn't return data with enclosure.query
To test:
- try tn30 and make sure that the visualization comes up in both the main view and the enclosure selector on the right
- try tn40. Assuming the middleware issue is still present on that machine, it should show an error message about enclosure data missing.

NAS-113739 / 22.02 / Fix enclosure selector for R Series

---

src/app/pages/system/view-enclosure/enclosure-disks/enclosure-disks.component.ts
src/app/pages/system/view-enclosure/view-enclosure.component.scss
src/app/pages/system/view-enclosure/view-enclosure.component.ts

There was a typo in the code due to two different variables with similar names. Correct variable is now being referenced with a more distinct and obvious name to avoid future issues. Also some error handling was added to deal with scenarios where middleware doesn't return data with enclosure.query
To test:
- try tn30 and make sure that the visualization comes up in both the main view and the enclosure selector on the right
- try tn40. Assuming the middleware issue is still present on that machine, it should show an error message about enclosure data missing.
Original PR: https://github.com/truenas/webui/pull/6205
Jira URL: https://jira.ixsystems.com/browse/NAS-113739

NAS-113739 / 22.02-RC.2 / Fix enclosure selector for R Series (by dszidi)

---

src/app/pages/network/network.component.ts

To test, go to an HA Scale System. On the dashboard, initiate failover for node A or node B hostname. Whichever node is "active" (not on stand by) should be shown as `Hostname` in the `Global Configuration` card on the `Network` page.

NAS-113586 / 22.02 / NAS-113586: Correct hostname used for global config

---

src/app/core/testing/classes/mock-websocket.service.ts

Several tests were crashing when `environment.remote` was reachable via network
For example at localization-form.component.spec.ts

NAS-113867 / 22.02 / NAS-113867: Unit tests should not be making real network requests

---

src/app/views/others/config-reset/config-reset.component.ts
src/app/views/others/failover/failover.component.ts
src/app/views/others/reboot/reboot.component.ts
src/app/views/others/shutdown/shutdown.component.ts

git cherry-pick -x 487138d6f0ac61c00bca7db5a14777f3471dc351
Basically in some scenarios the url for reboot/shutdown and some other pages got saved, which led to infinite reboot cycle.
More detailed steps are in ticket description.
Original PR: https://github.com/truenas/webui/pull/6218
Jira URL: https://jira.ixsystems.com/browse/NAS-113453

NAS-113453 / 22.02 / NAS-113453: Prevent recursive shutdowns and reboots (by undsoft)

---

src/app/pages/common/entity/entity-job/entity-job.component.html

There are 2 different buttons displayed depending on the job's status.
For failed jobs there's a new "X" button. It's always displayed for failed jobs.
For all other jobs we have the "minimize" button as before. It's displayed 
Testing: clicking Send Test Email with incorrect parameters in Alerts -> Email.

NAS-113817 / 22.02 / NAS-113817: Errors in EntityJobComponent cannot be closed

---

src/app/pages/common/entity/entity-form/components/form-select/form-select.component.html
src/app/pages/common/entity/entity-form/components/form-select/form-select.component.scss
src/assets/styles/other/_tn-styles.scss

Testing: 
1. Credentials -> Certificates
- add certificate authority
- add 10 certificates (Internal Certificate) -or- temporary adjust src\app\pages\common\entity\utils.ts:347
2. Apps -> Available -> Minio -> Install
3. On step 3, keep resizing your browser, until you reach height ~900px
- and "Certificate" dropdown box should be exactly in the middle (vertically)
- and List of certificates should be dropped  _down_ (not up)
4. Scroll the list all the way down - you should be able to reach the last list item. No list item should fall off the screen. 
This PR is re-work of previous PRs:
https://github.com/truenas/webui/pull/3558
https://github.com/truenas/webui/pull/4561
https://github.com/truenas/webui/pull/4564

NAS-112189 / 22.02 / NAS-112189: No Scrollbar For Selecting SSL Certs For K8S Ingress

---

src/app/services/network.service.ts

Testing: 
1. Apps -> Launch Docker Image. Networking -> Add external interface -> IPAM Type Static. 
2. Choose "add route" 
- enter "route destination IP / subnet":  0.0.0.0 / 0
- you'll need to enter "gateway IP", for example 192.168.1.1
3. Submit docker image
4. Navigate to installed apps, locate your docker image, and open "edit" - and assert that "route destination IP  / subnet" equal to 0.0.0.0 / 0

NAS-112334 / 22.02 / NAS-112334: Applications add route - default route - truenas scale

---

src/app/services/storage.service.ts

To reproduce this bug, create two smb shares at least and name the first one any letter out of `KMGTB` like `B` or `G`. If that doesn't work rename the other one to this.

NAS-113646 / 13.0 / Added fix for length check

---

src/app/pages/credentials/certificates-dash/certificates-dash.component.ts

What caused the issue:
https://jira.ixsystems.com/browse/NAS-113490?focusedCommentId=144630&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-144630
Testing:  
a. download dump from the ticket, find "CSR" and "cert_type_CSR", hard-code faulty values into WS response for `certificate.query`
b. alternatively, there's a possibility to test end-to-end: create authenticator (you'll need a domain name and it's Cloudflare or AWS Route53 credentials), then create CSR, then click CSR and choose your authenticator, and then download the resulting certificate
- AR: .crt file with size equal to 0 bytes, and error message in task manager
- ER: .csr file with size matching the size from `ls -l` command in shell

NAS-113490 / 22.02 / NAS-113490: Dinstinguish csr from cert + Fix file extension when downloading csr

---

src/app/enums/report-tab.enum.ts
src/app/pages/reports-dashboard/components/reports-global-controls/reports-global-controls.component.html
src/app/pages/reports-dashboard/components/reports-global-controls/reports-global-controls.component.ts
src/app/pages/reports-dashboard/reports-dashboard.component.ts

Testing: switch between different reports and keep an eye on URL - the URL should not contain any invalid routes, such as "процессор" or "Datenträger"

NAS-113953 / 22.02 / NAS-113953: When locale is not "English (en)", reports other than CPU cannot be accessed, as they redirect to the dashboard

---

src/app/pages/credentials/certificates-dash/forms/certificate-add.component.ts

The error was from `AuthorityKeyIdentifier.enabled`. 
Kept to use `AuthorityKeyIdentifier.authority_cert_issuer` and `AuthorityKeyIdentifier.extension_critical`.

NAS-113860 / 22.02 / Remove Authority Key Identifier option from CSR form

---

src/app/pages/applications/chart-releases/chart-releases.component.ts

This moves the default container shell from /bin/bash to /bin/sh.
Generally speaking all containers have sh, but lightweight containers do not always contain bash.
This has lead to multiple instances of people getting confused and filing bugreports on either the forum, discord or TrueCharts-support

NAS-114222 / 22.02 / default to sh for container shell

---

src/app/services/ws.service.ts

This is a preventative measure for getting `Not Authenticated` errors. Not sure how to reproduce the scenario where this code would be reached but as described by the ticket description, this case is reached somehow. Another ticket will be created to refactor the authentication process. That's expected to improve the process overall.

NAS-113560 / 22.02 / NAS-113560: Added check for a not auth message

---

src/app/pages/common/entity/entity-table/entity-table-row-details/entity-table-row-details.component.html
src/app/pages/common/entity/entity-table/entity-table-row-details/entity-table-row-details.component.ts
src/app/pages/data-protection/components/task-schedule-list/task-schedule-list.component.ts

Made a lot of attempts to replicate issue which user was facing, and finally discovered the following bug:
Parse logic was based on a hard-coded string "Disabled" and thus was tightly coupled with English localization
Testing:
1. Switch language to non English (German, Russian)
2. Credentials -> Cloud Storage -> Dropbox (fill in your dropbox creds, or any other cloud creds you have)
3. Go to Data Protection -> Add Cloud Sync task -> Create 2 tasks
4. Edit both tasks marking each as "Disabled"
5. Go to Data Protection -> click "Flyout" icon next to Cloud Sync Tasks 
Expected result:

NAS-114088 / 22.02 / NAS-114088: Cloud Sync Tasks - prevent page from crashing (fix job schedule parsing)

---

src/app/pages/vm/devices/device-add/device-add.component.html
src/app/pages/vm/devices/device-add/device-add.component.ts

After check the video attachment, I made a suggestion that `vm.device.passthrough_device_choices` has slow response. Assuming it may take ~15 seconds to retrieve such a long device list, it's possible to see the behavior depicted on the video.
The spinner I've added should help the user to know that he needs to wait until PCI devices will be loaded.
Testing: create a VM, and go to Devices -> Add. As a shortcut, I've adjusted response of `vm.device.passthrough_device_choices` query by hard-coding the JSON from the debugging logs which the user has uploaded.

NAS-114045 / 22.02 / NAS-114045: Fix Truenas Scale PCIe Passthru issue - Raid card not visible

---

src/app/pages/dashboard/components/widget-network/widget-network.component.ts
src/app/pages/reports-dashboard/components/report/report.component.ts
src/app/pages/reports-dashboard/reports.service.ts

Replacement for `getServerTime`.
Old `getServerTime` implementation was relying on XMLHttpRequest and thus was sensitive to how the user opens the WebUI - through a proxy or not, through https or http, and so on.
New implementation relies on existing WS which is more stable. I've used existing message `systeminfo`, which provides exact same value.
Testing: make sure charts work. I wasn't able to replicate the behavior which user were observing. I believe user had some networking issue, which should be worked around by getting rid of XMLHttpRequest.

NAS-112307 / 22.02 / NAS-112307: Fix CPU Reports in Dashboard broken, when using a proxy host

---

src/app/pages/common/entity/entity-toolbar/components/toolbar-multiselect/toolbar-multiselect.component.ts

Testing: 
1. create a pool
2. go to dashboard, show "pool" widget 
3. click "disk reports" icon in the top right corner

NAS-114215 / 22.02 / NAS-114215: Fix Disk Report not showing the correct drives in a pool

---

src/app/modules/entity/entity-table/entity-table.component.html
src/app/modules/entity/entity-table/entity-table.component.scss
src/app/pages/directory-service/directory-services.component.html
src/app/pages/directory-service/directory-services.component.scss

Same as https://github.com/truenas/webui/pull/6248
To test:
Go to a page that uses entity-table and doesn't have content.
Make sure entity-empty is centered

NAS-114032 / None / NAS-114032: backport changes to bluefin

---

src/app/pages/common/ix-forms/components/ix-errors/ix-errors.component.html
src/app/pages/system/advanced/isolated-gpu-pcis/isolated-gpu-pcis-form.component.ts
src/app/pages/vm/vm-form/vm-form.component.ts
src/app/pages/vm/vm-wizard/vm-wizard.component.ts

Testing in 3 places:
1. Settings -> Advanced -> Isolated GPUs: logic of validation
2. Virtualization -> Create new VM: translation of error message
3. Edit VM: translation of error message
I've tested 2 GPU setup by mocking the response of `'device.get_info', [DeviceType.Gpu]` . Also need to mockup response of `system.advanced.config  -> isolated_gpu_pci_ids` to emulate GPUs which are already chosen to isolate.

NAS-114338 / 22.02 / NAS-114338: Warning not showing up for isolating Passthrough devices

---

src/app/pages/account/users/user-form/user-form.component.ts

To test:
Go to Credentials -> Users
Hidden `Primary Group` select when `New Primary Group` checked.

NAS-110571 / None / Confusing order of group fields when creating a user

---

src/app/pages/data-protection/replication/replication-form/replication-form.component.ts

**Testing:**
1. Data Protection -> Replication Tasks -> Add one (use Wizard for simplicity)
2. Click on your replication task to Edit
3. Uncheck **Include Dataset Properties** and click **Save**
**Summary:**
When saving changes with **Include Dataset Properties** unticked, payload for `replication.update` was:
BEFORE:
```
"name":"My Pool/My Dataset - My Pool/My Dataset 2",
"properties":false,      <--- FALSE reflects unchecked state of "Include Dataset Properties"
"properties_override":null, <--- NULL causes "null not allowed"
"properties_exclude":[],
```
AFTER:
```
"name":"My Pool/My Dataset - My Pool/My Dataset 2",
"properties":false,
"properties_override":{}, <--- dummy object
"properties_exclude":[],
```

NAS-114428 / 22.02 / NAS-114428: Validation Error Traceback from unsetting Include Dataset Properties

---

src/app/enums/disk-bus.enum.ts
src/app/pages/storage/volumes/manager/manager.component.css
src/app/pages/storage/volumes/manager/manager.component.html
src/app/pages/storage/volumes/manager/manager.component.ts
src/app/pages/storage/volumes/volume-status/volume-status.component.ts

git cherry-pick -x 16ee21b00d1f90db64054c8c03996ee4b80d279e
git cherry-pick -x 6ae1887ccd4c93ee1bf8e4da38c03e32c533bfe5
git cherry-pick -x a4cc4d428e08443f30d87c9d4f5c8246ee132ad6
git cherry-pick -x 388d4d45b1dcb16970e647f96affe67d8ee7206c
git cherry-pick -x 11ff5b744e4b7b3779117151ccc051d464ba9fbd
git cherry-pick -x f5cbe527ad2e50967cde5fe1125bed0b292fefb3
git cherry-pick -x d0a6c043b524bb43ae0b275fb030de86ebd2b44d
git cherry-pick -x 8a49236f5e0eb34f5d93de3acb235e09d41172dd
Display warning if available disks have items in `duplicate_serial`
Testing:
- Use the latest nightly on a VM
- Mock response or create new disks
- Go to `Storage - Create Pool`
- Check the warning message
- Toggle Show/Hide all …

NAS-114146 / 13.0 / Add support for "duplicate_serial" field (by denysbutenko)

---

src/app/components/common/modal/modal.component.ts
src/app/interfaces/api-directory.interface.ts
src/app/pages/system/general-settings/gui-form/gui-form.component.spec.ts
src/app/pages/system/general-settings/gui-form/gui-form.component.ts
src/app/services/ws.service.ts

Go to the GUI settings under System -> General. Change the certificate and save. You should be prompted to restart the service. If you restart the service, the websocket will disconnect and connect again. Make sure that login on reconnect is working and you are still able to use the UI or redirected to the signin page if sign in is not possible.
Save anything other setting other than certificate (like one of the ports) and check that service restart happens (`service.restart` http is called) without calling `system.general.ui_restart` being called. And again that upon reconnection, login works and UI is usable.
You can test this on the Scale VM available to the team.

NAS-114394 / 22.02 / NAS-114394: Making sure the service restarts

---

src/app/services/ws.service.ts

The ticket has a gif attached of the issue
On master, if you stay on the dashboard and refresh the page a few times. The UI will break eventually. This PR fixes that.
We're reverting the re-connection logic to how it was before. The login addition was an attempt at improving the connection/disconnection of websocket but that can be addressed in a separate ticket.
Refreshing the UI on dashboard on this PR shouldn't cause the UI to break as many times as needed.
Note: This doesn't fix the issue of misplaced UI dashboard widgets. That is addressed by a different ticket.

NAS-114563 / 22.02 / NAS-114563: Reverting reconnection logic change

---

src/app/pages/applications/catalog/catalog.component.ts

Go to the apps page and go to the `Available Applications` tab. You shouldn't see the `ix-chart` app as mentioned in the ticket.

NAS-114530 / 22.02 / NAS-114530: Added filter for ix-chart

---

src/app/pages/credentials/certificates-dash/forms/ca-add.component.ts

Go to the certificates page and create a CA. In the form, on the first step, change the type to `Intermediate CA`. Now on the third step `Subject`, all of the fields should be showing up. Previously, this step would be just empty.

NAS-114620 / 22.02.1 / NAS-114620: Fixed field hide order

---

src/app/pages/dashboard/components/widget-pool/widget-pool.component.scss

Check widgets. The scrollbar should only appear if the content block is overflow.

NAS-114141 / None / NAS-114141: fixed scrollbar display in pool widget

---

src/app/pages/credentials/certificates-dash/certificates-dash.component.ts

On /credentials/certificates UI route, we had a bug - dropdown menu in Authorities block does not refresh it's list of options, when a new option gets added.
Testing: see https://jira.ixsystems.com/browse/NAS-114639

NAS-114639 / None / NAS-114639: CSR cannot be signed immediately after it has been added

---

src/app/pages/services/components/service-ups/service-ups.component.html
src/app/pages/services/components/service-ups/service-ups.component.ts

Testing:
System Settings -> Services -> UPS
If UPS mode is Master, Port or Hostname field is required
else Slave, Port or Hostname field is optional

NAS-113904 / None / WebUI - Services / UPS / Settings: Save button remains disabled after setting changes

---

src/app/pages/system/viewenclosure/view-enclosure.component.ts

Summary: adapted response of `EnclosureData` to existing UI logic.
Testing:
To see **System -> View Enclosures**:
1. edit src/app/services/navigation/navigation.service.ts
2. edit src/app/pages/system/viewenclosure/view-enclosure.component.ts:
3. remove condition at src\\app\\pages\\system\\viewenclosure\\view-enclosure.component.html:2
To see contents of **View Enclosures**:
1. Download new JSON response for  `EnclosureData` query from attachments of the ticket https://jira.ixsystems.com/browse/NAS-114383
2. Extract responses  `PoolData`, `SensorData` and `DisksData` queres from the machine mentioned in the ticket https://jira.ixsystems.com/browse/NAS-114383
3. Paste JSON to src/app/pages/system/viewenclosure/view-enclosure.component.ts

NAS-114383 / 13.0 / NAS-114383: enclosure plugin rewritten on 13 needs webUI changes

---

src/app/pages/storage/volumes/volume-status/volume-status.component.ts

To see **Pool Status** page,
1. Storage -> Pools
2. Click ![image](https://user-images.githubusercontent.com/20611516/154975443-28293f5c-353c-45fc-b62f-f3398ddf636e.png) next to the pool's name, and choose **Status** from the menu
3. When **(Context menu next to one of the disks) -> Edit** is clicked,
**Expected result**: editing form is opened.
**Actual result**: error in console. form won't open,
```
[Error] ERROR
TypeError: undefined is not an object (evaluating 'e[0].identifier')
```
Error was caused by incorrect query sent over WS, which resulted in an empty result:
```
"disk.query"
[
"devname",
"=",
"sdc2"    <--- incorrect. should be "sdc"
]
```
After looking into the code, I've found out that in 13 data bindings for device names were incorrectly calculated on UI side.
I've …

NAS-114718 / 13.0 / NAS-114718: Fix for Pool Status -> Edit

---

src/app/modules/tooltip/tooltip.module.ts

The close icon on tooltips wasn't showing due to the missing module. That should be fixed now.

NAS-115186 / 22.12 / NAS-115186: Added missing module

---

src/app/pages/dashboard/components/dashboard/dashboard.component.html

The help widget is draggable all the time. Even when the dashboard is not being re-ordered. You can click on it and drag it around. This PR fixes that.

NAS-115224 / 22.12 / NAS-115224: Fixed drag

---

src/app/modules/entity/utils.ts

If `res.extra` is not array, this error would be handled without any error report dialog.
(tested with mock data)
Added the case for the exception, opened a report dialog.

NAS-113755 / 22.12 / Fix handleWsError

---

src/app/modules/entity/entity-table/entity-table-row-details/entity-table-row-details.component.html
src/app/modules/entity/entity-table/entity-table-row-details/entity-table-row-details.component.scss
src/app/modules/entity/entity-table/entity-table.component.html
src/app/modules/entity/entity-table/entity-table.component.scss
src/app/pages/vm/vm-list/vm-list.component.ts

The virtualization table had issues of overlap columns by first and last columns due to them being `sticky`. Check responsive of the table with different column configurations and responsiveness on different screen sizes. Also, the border on the left column for scroll shouldn't touch the next column (usually the toggle) as complained about in the ticket comments.

NAS-114089 / 22.12 / NAS-114089: Fixed overlap and scroll issue

---

src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts

Go to the Add new cloud sync task form and after entering the values (Google Photos preferably), do a dry run. You should see the abort button and after abort, the dialog should be closable.

NAS-115077 / 22.02.1 / NAS-115077: Show close button after abort

---

src/app/interfaces/virtual-machine.interface.ts
src/app/pages/vm/vm-list/vm-list.component.ts

Summary: 
Adapted to back-end changes made to WS call **web_uri** [here](https://github.com/truenas/middleware/pull/8528)
- new parameter `protocol`, example: `protocol: 'https'`
- parameter `host` now accepts host & port. example: `host: 'localhost:4200'`
Testing: 
1. (Optional) Download middleware update from latest night build ("-manual-update-unsigned.tar" file should work)
2. Virtualization -> (Expand "vm" row) -> "Display" button (you may mock the data to actually make it visible)
3. WS call **web_uri** should be made with correct parameters, taken from your browser's address bar.
Example:
- User visits Angular app via **http**://localhost:4200 -> **Display** button opens **http**://localhost:5800/vnc.html?autoconnect=1 **CORRECT**
- User visits Angular app via …

NAS-115254 / 22.12 / NAS-115254: In UI preserve protocol/port when opening up display of vm devices

---

src/app/modules/entity/entity-form/components/form-select/form-select.component.html
src/app/modules/entity/entity-form/components/form-select/form-select.component.scss
src/app/modules/entity/entity-form/components/form-select/form-select.component.ts
src/app/modules/entity/entity-form/models/field-config.interface.ts
src/app/modules/ix-forms/components/ix-input/ix-input.component.html
src/app/modules/ix-forms/components/ix-input/ix-input.component.scss
src/app/modules/ix-forms/components/ix-input/ix-input.component.ts
src/app/modules/ix-forms/components/ix-select/ix-select.component.html
src/app/modules/ix-forms/components/ix-select/ix-select.component.scss
src/app/modules/ix-forms/components/ix-select/ix-select.component.ts
src/app/pages/directory-service/components/idmap/idmap-form.component.ts
src/app/pages/directory-service/components/ldap/ldap.component.ts
src/app/pages/directory-service/directory-services.component.ts
src/app/pages/network/components/download-client-config-modal/download-client-config-modal.component.html
src/app/pages/network/components/download-client-config-modal/download-client-config-modal.component.ts
src/app/pages/network/components/forms/service-openvpn-client.component.ts
src/app/pages/network/components/open-vpn-server-config/open-vpn-server-config.component.html
src/app/pages/network/components/open-vpn-server-config/open-vpn-server-config.component.ts
src/app/pages/services/components/service-ftp/service-ftp.component.ts
src/app/pages/services/components/service-s3/service-s3.component.html
src/app/pages/services/components/service-s3/service-s3.component.ts
src/app/pages/services/components/service-webdav/service-webdav.component.html
src/app/pages/services/components/service-webdav/service-webdav.component.ts
src/app/pages/system/general-settings/gui-form/gui-form.component.html
src/app/pages/system/general-settings/gui-form/gui-form.component.ts
src/app/pages/system/kmip/kmip.component.ts
src/app/services/ix-slide-in.service.ts

To test,
check that inputs for certificates or certificate authorities have links under them. Also check that on the directory services page, when you come back from a form, the tables update. The changes to the modal close methods are to ensure that tables are refreshed only when we want them to and not when modal is closed for any reason at all.
Let me know if further clarification is needed.

NAS-115262 / 22.12 / Added certificates links under certificate inputs

---

src/app/interfaces/api-directory.interface.ts
src/app/pages/services/components/service-webdav/service-webdav.component.ts

Replaced 'certificate.query' API endpoint with "webdav.cert_choices" in Services -> WebDAV form
Getting, updating and saving of certificates in the form.

NAS-115137 / 22.12 / New method "webdav.cert_choices". Get valid certs for webdav service

---

src/app/pages/storage/volumes/volumes-list/volumes-list.component.html

Removed class 'hidden' which had no effect.
Check rendering and efficiency "pool operations" button

NAS-114069 / 22.12 / NAS-114069: "hidden" class removed

---

src/app/pages/dashboard/components/dashboard/dashboard.component.ts

Summary: `setInterval` was not cleared after changing tab in sidebar
Testing: see steps in the ticket

NAS-115271 / 22.12 / NAS-115271: Dashboard buttons may appear on other pages

---

src/app/pages/services/components/service-dynamic-dns/service-dynamic-dns.component.ts

Just fix the text used for tooltips, now is showing the same text as in `server`

Fix the tooltip text for path field configuring a ddns service

---

src/app/pages/storage/snapshots/snapshot-list/snapshot-list.component.ts

There was already the feature of clearing selection after closed dialog.
Disabled close dialog by clicking backdrop.

NAS-115466 / 22.12 / "Select All" checkbox stays checked after completing operation

---

src/app/interfaces/dataset-quotas.interface.ts
src/app/pages/common/entity/entity-table/entity-table-add-actions.component.ts
src/app/pages/common/entity/entity-table/entity-table.service.ts
src/app/pages/common/entity/entity.module.ts
src/app/pages/storage/volumes/datasets/dataset-quotas/dataset-quotas-grouplist/dataset-quotas-grouplist.component.ts
src/app/pages/storage/volumes/datasets/dataset-quotas/dataset-quotas-userlist/dataset-quotas-userlist.component.ts

To test,
1. Create a two new users `user1` and `user2`
2. Set `User Quotas` for a dataset using the `Bulk` option
3. Remove the users from the system
4. Go back to the `User Quotas` page and you should see errors for quotas
5. Check the `Actions` button and click on the `Remove quotas for invalid users` button and follow through. It should remove the erroneous quota entries.
Test the same thing with `Group Quotas`

NAS-115110 / 13.0 / Added option to remove invalid user quotas

---

src/app/core/classes/system-profiler.ts
src/app/core/services/api.service.ts
src/app/pages/system/viewenclosure/enclosure-disks/components/tab-content/tab-content.component.html
src/app/pages/system/viewenclosure/enclosure-disks/components/tab-content/tab-content.component.ts
src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.html
src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.ts
src/app/pages/system/viewenclosure/view-enclosure.component.html
src/app/pages/system/viewenclosure/view-enclosure.component.ts

Summary:
- adapted the UI code to a new response of `enclosure.query` (use new parameters `{ extra: { pools: true } }`)
- changed order so that controller module are always displayed at the top 
Testing:
1. connect your setup to testing machine `m60-100.dc1.ixsystems.net` 
2. System -> View Enclosure
https://user-images.githubusercontent.com/20611516/156405176-31fad5e9-987e-4df6-891e-77b3a18c1344.mp4
- "m60" module should be on the top
- check that disks are displayed at proper slots in each enclosure (
- first ~24 front
- others ~100 disks each
- check that table rows contain proper sensor data on each tab for each enclosure
https://user-images.githubusercontent.com/20611516/156405198-115d0653-34fa-4239-be93-1c72306ca405.mp4
- check Front - should contain ~23 disks
- check Rear - should …

NAS-114383 / 13.0 / NAS-114383: Fixing logic of joining disks and enclosures

---

src/app/helptext/system/tunable.ts

Remove text about rc.conf and loader variables as these no longer apply in SCALE.

NAS-116082 / 22.02.2 / NAS-116082: Update Tunable/Sysctl Variable tooltips for SCALE

---

src/app/pages/applications/kubernetes-settings/kubernetes-settings.component.ts
src/app/pages/common/ix-forms/services/form-error-handler.service.ts
src/app/pages/system/advanced/syslog-form/syslog-form.component.ts
src/app/pages/system/advanced/system-dataset-pool/system-dataset-pool.component.spec.ts
src/app/pages/system/advanced/system-dataset-pool/system-dataset-pool.component.ts

Fixed error that goes to next even if the state of the job is not successful when using `switchMap` with `ws.job` in `SyslogFormComponent`, `KubernetesSettingsComponent`, `SystemDatasetPoolComponent`.

NAS-116092 / 22.02.2 / System dataset update validation errors are not displayed

---

src/app/pages/dashboard/components/dashboard/dashboard.component.ts

Added extra check to ignore unexist network widgets
Testing:
- Open Network page and create a new interface with type bridge
- Go to Dashboard and enable widget for newly created interface
- Go to Network and remove the bridge
- Go to Dashboard and check if its not broken

NAS-115787 / 22.02.2 / NAS-115787: Keep dashboard safe

---

src/app/pages/common/error-dialog/error-dialog.component.scss

The `!important` is required because the style that overrides it already has important in it.
To test, go to any component and type the following code in `ngOnInit` and load the component in the browser to see the problematic dialog
```
let myWarning = '';
for(let i = 0; i < 50000; i++) {
if(i % 250 === 0) {
myWarning += '<br/>';
}
myWarning += i;
}
this.dialog.errorReport(this.translate.instant('Warning'), `<pre>${myWarning}</pre>`);
```

NAS-116300 / 22.02.2 / NAS-116300: Fixed overflow-y

---

src/app/pages/sharing/iscsi/iscsi-wizard/iscsi-wizard.component.ts

Testing: Shares -> iSCSI -> Configure -> Wizard -> submit wizard in a way that would trigger middleware errors.
Previously form would break - you'd see an infinite spinner and won't be able to continue.
You're likely to hit some validation errors even if you just submit form as is.

NAS-116140 / 22.02.2 / NAS-116140: iSCSI wizard breaks down when middleware returns errors

---

src/app/pages/common/entity/entity-table/entity-table.component.ts

Testing: see video in ticket.
Previous issue happened when user would enter a filter value that doesn't exist in the table.

NAS-113262 / 13.0 / NAS-113262: Enable to edit Snapshot to Clone when Filtering

---

src/app/interfaces/alert.interface.ts
src/app/pages/common/entity/entity-form/components/form-checkbox/form-checkbox.component.html
src/app/pages/common/entity/entity-form/components/form-checkbox/form-checkbox.component.scss
src/app/pages/common/entity/entity-form/entity-form.component.scss
src/app/pages/common/entity/entity-form/models/field-config.interface.ts
src/app/pages/system/alert/alert-defaults.interface.ts
src/app/pages/system/alert/alert.component.html
src/app/pages/system/alert/alert.component.ts

To test, open the `Alerts` drop down and go to the `Alerts Settings` by clicking the cog icon. On the next page, on the top right from the select, click on `Storage`. Now on the list of new inputs, you should see `Proactive Support` as a checkbox for some inputs. (Examples are described in the ticket). Values should be persistent once saved. Default value should be `true` if you've never touched it.
Also, these checkboxes aren't supposed to show for non-enterprise products so find a way around that. Either disable the enterprise check in the new code for testing or edit the enterprise string in `localStorage` or buy a license.

NAS-116447 / 22.02.2 / NAS-116447: Added new checkbox

---

src/app/pages/applications/catalog/catalog.component.html

Summary: `textLimiter` was instantiated too many times, and it was consuming resources. I've changed the code so it won't rely on `textLimiter` at all.
**Testing:**
Enter **Apps** page, and make sure you don't see lagging, which was depicted on the video **2022-04-16 11-57-46.mkv** inside the ticket.

NAS-115796 / 22.12 / NAS-115796: Deleting 'textLimiter' attribute

---

src/app/pages/applications/catalog/catalog.component.html

Summary: `textLimiter` was instantiated too many times, and it was consuming resources. I've changed the code so it won't rely on `textLimiter` at all.
**Testing:**
Enter **Apps** page, and make sure you don't see lagging, which was depicted on the video **2022-04-16 11-57-46.mkv** inside the ticket.
Original PR: https://github.com/truenas/webui/pull/6753
Jira URL: https://jira.ixsystems.com/browse/NAS-115796

NAS-115796 / 22.02.2 / NAS-115796: Deleting 'textLimiter' attribute (by bvasilenko)

---

src/app/pages/dashboard/components/dashboard/dashboard.component.ts

This addresses the Storage widget not showing up. But pool specific widgets simply don't show up because you have to enable them on the dashboard via the config button at the top right. But this fixes the issue with the storage widget. Normally, if you navigate away to a different page and then come back to the dashboard without refreshing the page, the storage page wouldn't show up 99% of the time. This fixes the issue with that.

NAS-115675 / 22.02.2 / NAS-115675: Fixed race condition

---

src/app/pages/system/view-enclosure/enclosure-disks/enclosure-disks-mini.component.ts

This causes webUI to display the following error on SCALE MINI XL+
Since we have rebranded to TrueNAS, most of the systems we ship out the door are flashed with the `TRUENAS-` prefix in SMBIOS. I know basically 0 about typescript but I think this will fix it?

NAS-116609 / 22.02.2 / add proper strings so enclosure mapping works

---

src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts

Testing:
1. On **Storage > VMWare-Snapshots**, when click **Create Snapshot**
2. Do some hard-coding, in order to populate `vmware_res_status` with `true`
3. The "VMWare Sync" option should become visible in the UI

NAS-113539 / 13.0 / NAS-113539: Fixing visibility of checkbox query

---

src/app/pages/common/entity/entity-form/components/form-input/form-input.component.ts
src/app/pages/services/components/service-ups/service-ups.component.ts

Testing:
Services -> UPS -> Unset `No Communication Warning Time`
Changes:
Set null if the value of type `number` input is empty string

NAS-116461 / 13.0 / Unsetting "UPS - No Communication Warning Time" gives error

---

debian/control
debian/rules

This commit adds changes to install yarn package as that will effectively bring in latest nodejs and install npm as well. No need to define it separately. Also we are moving away from debian yarnpkg as it brings legacy nodejs dependencies which we have no use of as we have moved on to newer nodejs version.

NAS-116727 / 22.12 / Remove unnecessary dependencies

---

src/app/helptext/system/update.ts
src/app/pages/common/entity/entity-form/components/form-input/form-input.component.ts
src/app/pages/services/components/service-ups/service-ups.component.ts
src/app/pages/system/update/manualupdate/manualupdate.component.ts
src/app/pages/system/update/update.component.ts

Two things to test:
1. When you go to Manual update and select a scale update file, you should see a warning.
2. When you select a scale update train on main Update screen, you should see a warning.
Additional text if this is an HA system.
The only way to see more trains is to mock response in:
src/app/pages/system/update/update.component.ts:142
```
res = {
"trains": {
"TrueNAS-13.0-STABLE": {
"description": "Community Release Only - Not Enterprise Supported [nightly]",
"sequence": "75b35b700a587c9aad032005a55834d8"
},
"TrueNAS-SCALE-Angelfish": {
"description": "TrueNAS SCALE Angelfish"
}
},
"current": "TrueNAS-13.0-STABLE",
"selected": "TrueNAS-SCALE-Angelfish"
};
```

NAS-116648 / 13.0 / NAS-116648: Warning messages when upgrading to Scale

---

src/app/pages/datasets/components/dataset-node/dataset-node.component.spec.ts
src/app/pages/datasets/components/dataset-node/dataset-node.component.ts

Testing:
Datasets -> Select a Dataset (password protected) -> ZFS Encryption Card -> Click `Lock/Unlock` button
Check if refresh a tree by locking the dataset.

NAS-116937 / 22.12 / Locking a dataset doesn't refresh a tree

---

src/app/pages/storage/volumes/volumes-list/volumes-list-table-config.ts
src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts

Testing:
`zpool create -o compatibility=legacy tank /dev/sdx`
where sdx is one of the unused disks.
`zpool export tank`
Import pool via UI, go to cog icon on a pool and select Upgrade pool.
Original PR: https://github.com/truenas/webui/pull/6851
Jira URL: https://ixsystems.atlassian.net/browse/NAS-117038

NAS-117038 / 22.02.2.1 / NAS-117038: Fixing Upgrade Pool menu item (by undsoft)

---

src/app/enums/failover-disabled-reason.enum.ts
src/app/helptext/topbar.ts

Changes were made to fix a problem with HA systems here: https://github.com/truenas/middleware/pull/9439. I added a new `NO_FENCED` value to be returned so I'm adding it here on front-end.

NAS-117269 / 22.02.3 / add NO_FENCED to disabled reason enum

---

src/app/enums/failover-disabled-reason.enum.ts
src/app/helptext/topbar.ts

Changes were made to fix a problem with HA systems here: https://github.com/truenas/middleware/pull/9439. I added a new `NO_FENCED` value to be returned so I'm adding it here on front-end.
Original PR: https://github.com/truenas/webui/pull/6885
Jira URL: https://ixsystems.atlassian.net/browse/NAS-117269

NAS-117269 / 22.12 / add NO_FENCED to disabled reason enum (by yocalebo)

---

src/app/interfaces/chart-release-event.interface.ts
src/app/pages/applications/dialogs/chart-events/chart-events-dialog.component.html
src/app/pages/applications/dialogs/chart-events/chart-events-dialog.component.ts

Apps -> Installed Applications 
Check sorting of Application Events
_metadata.creation_timestamp?.$date_ was used instead of _first_timestamp?.$date_

NAS-116894 / 22.12 / NAS-116894: Application Events is not sorted

---

codecov.yml

This _should_ disable the status check that complains that not enough % was covered in the diff.

NAS-117366 / 22.12 / NAS-117366: Make `patch` status check optional on codecov

---

src/app/pages/storage2/components/pools-dashboard/pool-usage-card/gauge-chart/gauge-chart.component.scss
src/app/pages/storage2/components/pools-dashboard/pool-usage-card/pool-usage-card.component.html
src/app/pages/storage2/components/pools-dashboard/pool-usage-card/pool-usage-card.component.spec.ts

**Testing**
Go to **Storage** page. On the **Usage** card gauge chart should have:
- same share of red color as in other places
- same font as the number of "Unassigned disks"

NAS-117509 / 22.12 / NAS-117509: Sync colors and fonts

---

src/app/pages/datasets/components/dataset-capacity-management-card/dataset-capacity-management-card.component.html
src/app/pages/datasets/components/dataset-capacity-management-card/dataset-capacity-management-card.component.spec.ts
src/app/pages/datasets/components/dataset-capacity-management-card/dataset-capacity-management-card.component.ts

**Testing:**
Datasets => Dataset Space Management card
- If `Quota for this dataset and all children` field is changed as not 0:
- If `Quota for this dataset and all children` field is changed as 0 and `Quota for this dataset` field is changed as not 0:

NAS-117628 / 22.12 / NAS-117628: Dataset quota is not shown

---

src/app/pages/dashboard/components/dashboard/dashboard.component.ts

**Testing:**
Dashboard => change Configure
After changing the Configure, the widget cards changed should not be reset or reverted without login again or refresh.

NAS-117700 / 22.12 / NAS-117700: Dashboard Config settings revert after save

---

src/app/modules/common/search-input/search-input.component.ts
src/app/modules/entity/entity-table/entity-table-add-actions/entity-table-add-actions-config.interface.ts
src/app/modules/entity/entity-table/entity-table-add-actions/entity-table-add-actions.component.html
src/app/modules/entity/entity-table/entity-table-add-actions/entity-table-add-actions.component.ts
src/app/modules/entity/entity-table/entity-table.interface.ts
src/app/pages/data-protection/cloudsync/cloudsync-list/cloudsync-list.component.ts
src/app/pages/data-protection/replication/replication-list/replication-list.component.ts
src/app/pages/data-protection/rsync-task/rsync-task-list/rsync-task-list.component.ts
src/app/pages/data-protection/snapshot/snapshot-list/snapshot-list.component.ts
src/app/pages/datasets/modules/snapshots/snapshot-list/snapshot-list.component.html
src/app/pages/datasets/modules/snapshots/snapshot-list/snapshot-list.component.ts

**Testing:**
Datasets => Data Protection Card
- Manage Snapshots
- Manage Snapshot Tasks
- Manage Replication Tasks
- Manage Cloud Sync Tasks
- Manage Rsync Tasks
Check for those 5 links.
_Result:_
- The search box should be filled as a chosen dataset string and an icon to clear the filter should exist there.
- The list on the routed page should expose the result for the chosen dataset on the first loading.

NAS-117573 / 22.12 / NAS-117573: Update search box

---

src/app/pages/system/failover-settings/failover-settings.component.spec.ts
src/app/pages/system/failover-settings/failover-settings.component.ts

Some conditions were previously incorrectly ported. You can compare with the old, now deleted `failover.component.ts`:
https://github.com/truenas/webui/pull/6604/files#diff-a8f298f0b8de3eceda6579ed4a16184ff720f82dfa5ef8ad74856b71040321f0
I will also DM you with a machine that can be used for testing.

NAS-117720 / 22.12 / NAS-117720: Bluefin HA testing: UI logout when saving failover settings

---

src/app/pages/services/components/service-ftp/service-ftp.component.html
src/app/pages/services/components/service-ftp/service-ftp.component.spec.ts

**Testing:**
System Settings → Services → FTP
The `Certificate` dropdown should be under `Enable TLS` checkbox in the `Advanced settings`.

NAS-117714 / 22.12 / FTP "Certificate" dropdown should be under "Enable TLS" checkbox

---

.github/workflows/docker_internal.yml
.github/workflows/docker_latest.yml
.github/workflows/main.yml

Changes made in the main.yml file. Added path-ignore.
github actions should not be executed if changes are made only in the "/tests" directory

NAS-117719 / 22.12 / Nas-117719 Do not run CI checks when only RE tests were changed

---

src/app/pages/vm/vm-list/vm-list.component.ts

Testing: start a VM, click Download logs.
Original PR: https://github.com/truenas/webui/pull/7014
Jira URL: https://ixsystems.atlassian.net/browse/NAS-117755

NAS-117755 / 22.02.4 / NAS-117755: Fix downloading VM logs (by undsoft)

---

src/app/pages/applications/forms/chart-form/chart-form.component.spec.ts
src/app/services/app-schema.service.ts

1. Pick any app, for example **jackett**
1. Go to **Services**
1. Change **Service Type** to **LoadBalancer**
- Expected Result: It should show LoadBalancer IP, External IP’s, IP Family Policy and IP Families

NAS-117902 / 22.12 / NAS-117902: Fix form when show_if is '!='

---

src/app/interfaces/api-directory.interface.ts
src/app/pages/system/advanced/isolated-gpu-pcis/isolated-gpu-pcis-form.component.spec.ts
src/app/pages/system/advanced/isolated-gpu-pcis/isolated-gpu-pcis-form.component.ts

**Testing**
On the **System settings > Advanced** page, at the **Isolated GPU Device(s)** section, after clicking **Settings** button, slide-in form **Isolated GPU PCI Id's** appears.
When saving changes, it should call `system.advanced.update_gpu_pci_ids` method, instead of `system.advanced.update`.

NAS-117836 / 22.12 / NAS-117836: Use new method for updating Isolated GPUs

---

src/app/core/components/copy-btn/copy-btn.component.html
src/app/core/components/copy-btn/copy-btn.component.scss
src/app/core/components/copy-btn/copy-btn.component.ts
src/app/interfaces/dataset.interface.ts
src/app/pages/credentials/certificates-dash/view-certificate-dialog/view-certificate-dialog.component.html
src/app/pages/datasets/components/dataset-details-card/dataset-details-card.component.html
src/app/pages/datasets/components/dataset-details-card/dataset-details-card.component.scss
src/app/pages/datasets/components/dataset-details-card/dataset-details-card.component.spec.ts
src/app/pages/datasets/components/dataset-details-card/dataset-details-card.component.ts
src/app/pages/storage2/components/pools-dashboard/pools-dashboard.component.ts
src/app/pages/storage2/components/pools-dashboard/topology-card/topology-card.component.html
src/app/pages/storage2/components/pools-dashboard/topology-card/topology-card.component.scss
src/app/pages/storage2/components/pools-dashboard/topology-card/topology-card.component.spec.ts
src/app/pages/storage2/modules/devices/components/devices/devices.component.scss
src/app/pages/storage2/modules/devices/components/disk-info-card/disk-info-card.component.html
src/app/pages/storage2/modules/devices/components/disk-info-card/disk-info-card.component.scss
src/app/pages/storage2/modules/devices/components/topology-item-node/topology-item-node.component.html
src/app/pages/storage2/modules/devices/components/topology-item-node/topology-item-node.component.scss
src/app/pages/storage2/modules/devices/components/topology-item-node/topology-item-node.component.spec.ts
src/app/pages/storage2/modules/devices/components/topology-item-node/topology-item-node.component.ts
src/app/pages/system/bootenv/bootenv-status/bootenv-node-item/bootenv-node-item.component.ts
src/assets/styles/other/_tn-styles.scss

Changes:
- Add copy button for `Disk Serial` and `Dataset Path`
- Use snack bar service for copy button user feedback
- Update warning color on Pools Dashboard (triangles)
- Update offline color for the status column on the Devices page
- Fix text alignment on the Error dialog – `+ More info`
- Fix issue when closing `Import Pool` form triggered dashboard reloading
For testing, please check the original ticket

NAS-117812 / 22.12 / Minor updates to storage pages

---

src/app/pages/datasets/components/dataset-form/dataset-form.component.ts

To test
1. Create an encrypted pool
2. Try to create a dataset on that pool and disable encryption
Current Behavior: If you disable the `Inherit (encrypted)` field, the `Encryption` checkbox doesn't show up. So, you can only change how the dataset is encrypted. You can't disable the encryption altogether.
Expected Behavior: If you disable the `Inhert (encrypted)` field, the `Encryption` field should also show up with the rest of the fields. Disabling that field should help disable encryption on the newly created dataset. You should also see a warning when you disable encryption for the first time.

NAS-110795 / 22.12 / NAS-110795: Showing encryption checkbox in basic form

---

src/app/enums/network-interface.enum.ts
src/app/pages/dashboard/components/widget-network/widget-network.component.ts

For unknown reasons given network interface has `"link_state": "LINK_STATE_UNKNOWN"`
Before:
After:

NAS-117464 / 22.12 / Fix `No active network interfaces` on network widget

---

src/app/modules/ix-forms/components/ix-chips/ix-chips.component.scss
src/app/modules/ix-forms/components/ix-combobox/ix-combobox.component.scss
src/app/modules/ix-forms/components/ix-input/ix-input.component.scss
src/app/modules/ix-forms/components/ix-select/ix-select.component.scss
src/app/pages/api-keys/components/api-key-list/api-key-list.component.scss
src/app/pages/datasets/components/dataset-details-panel/dataset-details-panel.component.html
src/app/pages/datasets/modules/permissions/containers/permissions-card/permissions-card.component.html

Before:
When you focus on `ix-input` it jumps due to border-width changes. (normal - 1.5px, focus - 1px).
After:
`ix-input` and other controls will inherit the border width on focusing

NAS-117996 / 22.12 / Inherit border width for inputs on focus

---

src/app/interfaces/api-directory.interface.ts
src/app/pages/network/network.component.ts

1. Enter **Network** page, open settings of your network adapter, make a change
After you save your changes, you will see **unapplied changes** ui block with the **Test Changes** button and the input box to specify how long (in seconds) changes will be kept:
2. Click **Test changes** button
After you click it, you’ll see **temporarily applied changes** ui block, counting down the amount of seconds. 
- Normally, to apply your changes, you need to click the **Save Changes** button before this countdown reaches “0”, and if you do so, your changes will be persisted. If you won’t be quick enough, your changes will be unapplied, and you will be taken back to **unapplied changes** ui block.
- To replicate the previously buggy scenario, ignore the normal scenario described above, and instead go …

NAS-113691 / 22.12 / NAS-113691: invalidate committed network changes, after user visits network settings

---

src/app/modules/common/topbar/topbar.component.html
src/app/modules/common/topbar/topbar.component.scss

NAS-117983 / 22.12 / Clickable logo on mobile screens

---

src/app/modules/ix-icon/ix-icon.component.scss
src/app/modules/ix-icon/ix-icon.component.ts

Check for proper handling `@Input` 'name' in the ix-icon.
Icons should be correctly drawn when dynamically changing the input name.
For ligature icon different use cases
`<ix-icon>arrow_circle_right</ix-icon>
<ix-icon [name]="arrow_circle_right"></ix-icon>`
Don't mix these two options
https://user-images.githubusercontent.com/22006748/187682970-12466cbc-f1d0-4bc3-b3d2-e186ca3fe410.mp4

NAS-117870 / 22.12 / NAS-117870: Properly handle change of an icon name at `ix-icon`

---

src/app/services/ix-slide-in.service.ts
src/app/services/modal.service.ts

1. Go to **Sharing**
2. Go to **Data Protection** and click **Add** button to open slide-in panel
3. Click browser's **Back** button
Expected Result: Slide in is closed and user goes back.

NAS-117943 / 22.12 / NAS-117943: Close slide-in while navigating in browser

---

src/assets/styles/other/_tn-styles.scss

Manual cherry-pick a fix from https://github.com/truenas/webui/pull/7035
Preview:

NAS-118258 / 22.12 / Fix icon color in sidebar

---

src/app/pages/storage/modules/devices/components/zfs-info-card/zfs-info-card.component.html
src/app/pages/storage/modules/devices/components/zfs-info-card/zfs-info-card.component.ts

**Testing**
You should have a single disk pool, and an available disk
1. On **Storage > (Choose a single-disk pool) > Manage Devices** , select the single disk of the pool
2. Test the **Extend** button and the **Extend Dialog**

NAS-118065 / 22.12 / NAS-118065: Add Extend button inside ZFS Info block

---

src/app/pages/datasets/components/dataset-form/dataset-form.component.ts

**Summary**
Removed **ACL Type** and **Mode**,  if dataset is a **_root dataset_** , as suggested by the ticket's description

NAS-113216 / 22.12 / NAS-113216: Hide 'acltype' and 'aclmode' when creating or editing first level dataset

---

src/app/pages/reports-dashboard/components/report/report.component.ts

**Testing**
On the **Reporting page**, click the **Zoom out** button for the CPU usage graph. Check that chart's labels and values aren't shuffled.

NAS-117903 / 22.12 / NAS-117903: Set correct key sequence

---

src/app/modules/common/layouts/admin-layout/admin-layout.component.scss

Made sure that bottom info is always visible, if menu items overflow - scroll added.

NAS-117859 / 22.12 / Fixed sidenav bottom details

---

src/app/enums/failover-disabled-reason.enum.ts
src/app/helptext/topbar.ts

Added 3 new reasons in PR: https://github.com/truenas/middleware/pull/9904 so adding them here.

NAS-118303 / 22.12 / New reasons in `failover.disabled.reasons`

---

src/app/modules/alerts/components/alert/alert.component.scss
src/app/modules/alerts/components/alert/alert.component.spec.ts
src/app/modules/alerts/components/alert/alert.component.ts
src/app/modules/alerts/components/alerts-panel/alerts-panel.component.html
src/app/modules/jobs/components/job-item/job-item.component.html
src/app/modules/jobs/components/jobs-panel/jobs-panel.component.html
src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.html
src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.scss
src/app/pages/storage/components/dashboard-pool/pool-usage-card/pool-usage-card.component.html
src/app/pages/storage/components/dashboard-pool/pool-usage-card/pool-usage-card.component.spec.ts
src/app/pages/storage/components/dashboard-pool/topology-card/topology-card.component.html
src/app/pages/storage/components/dashboard-pool/topology-card/topology-card.component.spec.ts
src/assets/styles/other/_fn-styles.scss

Using one style icons (Jobs short list & tasks full list)
___
Alerts - improved UI understandability (red, orange, blue [all-rounded])
___
Storage (one icons style [rounded])

NAS-118333 / 22.12 / Icons update (rounded)

---

src/app/modules/entity/entity-job/entity-job.component.scss
src/app/pages/storage/components/pools-dashboard/pools-dashboard.component.html

NAS-118412 / 22.12 / Pool processing modal width jumping fix

---

src/app/enums/failover-disabled-reason.enum.ts
src/app/helptext/topbar.ts

Added this on backend here: https://github.com/truenas/middleware/pull/9937

NAS-118446 / 22.12 / add MISMATCH_VERSIONS to failover topbar

---

src/app/modules/common/dialog/error-dialog/error-dialog.component.html
src/assets/styles/other/_tn-styles.scss

NAS-118414 / 22.12 / Warning modal icon

---

src/app/services/app-schema.service.spec.ts
src/app/services/app-schema.service.ts

**Testing**
At **Apps** 
1. Pick an app which has a property with `type: int, min: ..., max: ...`  in the schema of it's configuration object. Most of such properties are port numbers.  For example, app **storj** property **Owner User ID**
2. Test validation for this property on the form for adding/editing the app

NAS-112088 / 22.12 / Apps > Don't do validation on empty textboxes if they are not set required: true.

---

src/app/pages/applications/docker-images/docker-images-list/docker-images-list.component.ts
src/app/pages/applications/docker-images/docker-images.store.ts

**Testing**
On the **Apps** page double check that contents of **Docker Images** tab gets refreshed when user switches to other tag, and then switches back to **Docker Images** tab.

NAS-118359 / 22.12 / Update entities in docker-images store

---

src/app/pages/datasets/components/dataset-form/dataset-form.component.ts

Test how `Metadata (Special) Small Block Size` gets saved on the dataset form when dataset is edited or added.
Previous error occurred when dataset was added in Basic mode.

NAS-118464 / 22.12 / Fixes saving Small Block Size on basic edit

---

src/app/pages/storage/modules/devices/components/devices/devices.component.ts

**Testing**
You should have a pool with 2 or more drives. Remove one drive from a pool in order to simulate replacement of the drive. 
Now, **Storage > tank > Topology > Manage Devices** should display the remaining drives correctly.

NAS-118443 / 22.12 / Filter disks when 'disk' or 'device' is null

---

src/app/pages/storage/modules/devices/components/devices/devices.component.ts

**Testing**
You should have a pool with 2 or more drives. Remove one drive from a pool in order to simulate replacement of the drive. 
Now, **Storage > tank > Topology > Manage Devices** should display the remaining drives correctly.
Original PR: https://github.com/truenas/webui/pull/7172
Jira URL: https://ixsystems.atlassian.net/browse/NAS-118443

NAS-118443 / 22.12-BETA.2 / Filter disks when 'disk' or 'device' is null (by bvasilenko)

---

src/app/pages/datasets/datasets.module.ts
src/app/pages/datasets/store/dataset-store.service.ts
src/app/pages/storage/components/dashboard-pool/export-disconnect-modal/export-disconnect-modal.component.ts

To share service in 2 different module, we can make service global as I did via **providedIn: 'root',**
or create a separate Shared Module which we will use in 2 components.
And I had 2 solutions 
--- 
1. Inside of the dataset-details-panel.component are some components which take dataset ID and make request
Since after deletion we still have datasets in store, it tries to take the ID and load some data, but this dataset is no longer existing so that’s why we see error modals.
So I put skeleton to wait for datasets to be loaded, so we know if selected dataset exists
2. After pool deletion, we can clear DATAsets store (but need to plug datasets store module to Storage)
**Selected approach number #2.**

NAS-117941 / 22.12-RC.1 / Error when going to datasets after removing all pools

---

src/app/pages/storage/modules/devices/components/devices/devices.component.html
src/app/pages/storage/modules/devices/components/devices/devices.component.ts
src/app/pages/storage/modules/devices/components/topology-item-node/topology-item-node.component.html
src/app/pages/storage/modules/devices/components/topology-item-node/topology-item-node.component.scss
src/app/pages/storage/modules/devices/components/topology-item-node/topology-item-node.component.spec.ts
src/app/pages/storage/modules/devices/components/topology-item-node/topology-item-node.component.ts
src/app/pages/storage/modules/devices/devices.module.ts

**Testing**
1. Have a Mirrored pool of 2 drives
1. Remove a drive from that pool. And by remove, I mean physically pull the drive. Pool does show degraded.
1. Then attempt to replace the drive by going to **Storage > Pool > Topology > Manage Devices**.
Original PR: https://github.com/truenas/webui/pull/7216
Jira URL: https://ixsystems.atlassian.net/browse/NAS-118443

NAS-118443 / 22.12-BETA.2 / display removed disks in Storage Devices; restore 'Replace' menu item for every disk shown (by bvasilenko)

---

src/app/modules/entity/entity-job/entity-job.component.scss
src/app/modules/jobs/components/jobs-panel/jobs-panel.component.ts

Problem was with jobs-panel.component manual **400px** width passed as props.

NAS-118541 / 22.12-RC.1 / Progress bar overflows jobs dialog

---

src/app/pages/data-protection/replication/replication-form/replication-form.component.ts
src/app/pages/data-protection/replication/replication-wizard/replication-wizard.component.ts

Go to http://localhost:4200/data-protection
Replications Tasks -> ADD 
And try the described case for Wizard and Advanced Form
When creating a replication task (both using wizard and advanced form) we need to forbid using CUSTOM retention policy if Naming regex is used

NAS-118557 / 22.12-RC.1 / Replication: Only Same as Source and None retention policies can be used with Naming regex

---

src/app/pages/datasets/components/dataset-capacity-management-card/dataset-capacity-management-card.component.scss
src/app/pages/datasets/components/dataset-capacity-management-card/space-management-chart/space-management-chart.component.html
src/app/pages/datasets/components/dataset-capacity-management-card/space-management-chart/space-management-chart.component.scss
src/app/pages/datasets/modules/permissions/containers/permissions-card/permissions-card.component.scss
src/assets/styles/components/_charts.scss
src/assets/styles/mixins/cards.scss

So, in result the chart & card are more tight and smaller now.
Before:
After:

NAS-118545 / 22.12-RC.1 / Make Dataset Space Management chart smaller

---

src/app/pages/system/general-settings/general-settings.component.ts

**Testing**
Tweak your box config (or hard-code json response) for **system.general.config** so it returns property `kbdmap` with a value `"us.unix"` set to it, to replicate user's box settings, which he got stuck at after the upgrade.
Go to **Settings > General** and make sure that UI is not broken, and you're able to set keyboard mapping to some other value via the UI.

NAS-118520 / 22.12 / Fix 'Keyboard map' label bug

---

src/assets/styles/other/_fn-styles.scss
src/assets/styles/other/_tn-styles.scss
src/assets/styles/scss-imports/splitview.scss

Go to System Settings -> Services  and run this command in below in the dev console 
`window.document.evaluate('//tr[contains(.,"WebDAV")]', document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue.scrollIntoView(true)`
Expected: toolbar should not disappear or change its position

NAS-113762 / 22.12 / Fixed missing toolbar in Mozilla

---

src/app/pages/credentials/backup-credentials/cloud-credentials-form/cloud-credentials-form.component.html
src/app/pages/credentials/backup-credentials/cloud-credentials-form/cloud-credentials-form.component.spec.ts
src/app/pages/credentials/backup-credentials/cloud-credentials-form/cloud-credentials-form.component.ts

Go to Credentials -> Backup credentials. 
When adding a new cloud credential the order of fields is different and name will default to provider name until user interacts with Name control.

NAS-118777 / 22.12 / Default cloudsync credential name to provider name

---

src/app/pages/system/file-ticket/file-ticket-form/file-ticket-form.component.ts
src/app/pages/system/file-ticket/file-ticket-licensed-form/file-ticket-licensed-form.component.ts

On **Settings > General** page,
**Note:** the issue happens only on licensed servers. If your truenas box does not support this, so you will need to manually adjust the code to see the **Open Ticket** button
1. Click **File Ticket** button and fill in the form (you won't be able to see this on your truenas box, so you can adjust the code to skip this step)
Here's the example of JSON response from `support.new_ticket`:
```
{
"id": "91ae1fad-7f03-f03b-dd84-a1de3cd2660c",
"msg": "result",
"result": [
{
"id": 7907,
"method": "support.new_ticket",
"arguments": [
{
"name": "developer test",
"email": "bvasilenko@ixsystems.com",
"cc": [],
"phone": "+905427783228",
"category": "BUG",
"environment": "testing",
"criticality": "inquiry",
"title": "test 2",
"body": "test 2",
"attach_debug": true
}
], …
```

NAS-118882 / 22.12 / Fix sidebar closing bug

---

src/app/pages/storage/components/dashboard-pool/disk-health-card/disk-health-card.component.html
src/app/pages/storage/components/dashboard-pool/pool-usage-card/pool-usage-card.component.html
src/app/pages/storage/components/dashboard-pool/pool-usage-card/pool-usage-card.component.spec.ts
src/app/pages/storage/components/dashboard-pool/zfs-health-card/zfs-health-card.component.html

made warning icons one style
Prev:
and  removed Used by snapshots  block, check comments: https://ixsystems.atlassian.net/browse/NAS-118891

NAS-118891 / 22.12 / Used snapshot size not showed on the storage page

---

src/app/modules/alerts/components/alert/alert.component.scss
src/app/modules/alerts/components/alerts-panel/alerts-panel.component.scss

PREV: (less line height and white icons on top)
NOW: (more line height and grayish icons on top)

NAS-118946 / 22.12 / Update styles on the Alert Panel

---

src/app/modules/entity/entity-table/entity-table-actions/entity-table-actions.component.html
src/app/pages/system/view-enclosure/classes/system-profiler.ts
src/app/pages/system/view-enclosure/components/enclosure-disks-mini/enclosure-disks-mini.component.html
src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.html

Vdev now has a **name** property and we display it.
On MINI | M40 | other systems

NAS-113218 / 22.12 / Enclosure UI stage left Vdev should show name not type

---

src/app/interfaces/certificate.interface.ts
src/app/pages/credentials/certificates-dash/forms/certificate-add.component.ts

**Summary**
1st part of this ticket is a problem on middleware side.
2nd part is removing `any` casts, and it's done here:

NAS-119051 / 22.12 / Fix `as any` casts

---

src/app/pages/datasets/modules/permissions/containers/dataset-acl-editor/dataset-acl-editor.component.ts
src/app/pages/datasets/modules/permissions/stores/dataset-acl-editor.store.ts

Fixes:
* Stripping ACL would not redirect user back to datasets.
* ACL editor would remember last opened ACL and therefore Select Preset ACL prompt was shown inconsistently.

NAS-119042 / 22.12 / Fixing various inconsistencies with ACL editor

---

src/app/pages/services/components/service-ftp/service-ftp.component.ts

**Testing**
1. Go to **System Settings > Services**
2. Click **Configure** button next to **FTP** service, then click **Advanced settings**
4. Tick **Enable TLS**, choose a certificate and click **Save**
5. Return to advanced settings, and untick the **Enable TLS** and click **Save**
- Expected result:  selected certificate submitted as `null` to middleware, erasing previously selected certificate

NAS-119096 / 22.12 / Set `Certificate` to null when `Enable TLS` is false

---

src/app/pages/network/ipmi/ipmi.component.ts

**Testing**
You should test with an M60 box, for example m60-100.dc1.ixsystems.net
On **Network** page, at **IPMI** block:
1. Click an item from IPMI block to open it for editing
1. Set **VLAN ID** to any integer
1. Save configuration
1. Erase **VLAN ID** integer
1. Save configuration
- Expected result:  VLAN ID should be erased without an error "Is not integer value" mentioned in the ticket

NAS-118439 / 13.0 / Cast `vlan` value ti integer or null

---

src/app/pages/sharing/smb/smb-form/smb-form.component.ts

**Testing**
1. Click **Sharing > Windows Shares (SMB) > ADD**
1. Click on any folder. Note that the ‘Name’ field is updated to match the name of the folder you clicked on.
1. Now click on another folder.
Expected result: The ‘Name’ field is updated to match the selected folder.

NAS-118870 / 13.0 / Update `Name` field after first folder click

---

src/app/pages/sharing/smb/smb-form/smb-form.component.ts

**Testing**
1. Create SMB share on some other machine and add it to your SCALE box using the following command:
For example, you've created an SMB share on your other machine:
`\\192.168.1.111\tst_smb`
In the **Shell** of your SCALE box, run the command:
```
call sharing.smb.create '{"path": "EXTERNAL:<PUT PATH HERE>", "name": "TST_SMB"}'
```
2. View the details of newly created external share in the WebUI on your box:
- **Expected result:** no error message should be displayed. For other errors, however, the error message should still appear.

NAS-119125 / 23.10 / Add support for external share paths

---

src/app/pages/sharing/smb/smb-form/smb-form.component.ts

**Testing**
1. Create SMB share on some other machine and add it to your SCALE box using the following command:
For example, you've created an SMB share on your other machine:
`\\192.168.1.111\tst_smb`
In the **Shell** of your SCALE box, run the command:
```
call sharing.smb.create '{"path": "EXTERNAL:<PUT PATH HERE>", "name": "TST_SMB"}'
```
2. View the details of newly created external share in the WebUI on your box:
- **Expected result:** no error message should be displayed. For other errors, however, the error message should still appear. 
Original PR: https://github.com/truenas/webui/pull/7397
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119125

NAS-119125 / 22.12.1 / Add support for external share paths (by bvasilenko)

---

src/app/views/sessions/signin/signin.component.html
src/app/views/sessions/signin/signin.component.ts

See ticket description.
Basically replaces "Checking HA status" with a loading indicator.

NAS-119212 / 23.10 / Do not show "Checking HA status" on single node systems

---

src/app/views/sessions/signin/signin.component.html
src/app/views/sessions/signin/signin.component.ts

See ticket description.
Basically replaces "Checking HA status" with a loading indicator.
Original PR: https://github.com/truenas/webui/pull/7421
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119212

NAS-119212 / 22.12 / Do not show "Checking HA status" on single node systems (by undsoft)

---

src/app/pages/datasets/components/dataset-details-panel/dataset-details-panel.component.ts
src/app/pages/datasets/components/zvol-form/zvol-form.component.ts

For testing, you can go to the datasets page and click on the `Add Zvol (new)` button, and just close it. The `datasetUpdated` action should be ignored if the form wasn't submitted.

NAS-119264 / 23.10 / Refresh dataset tree when zvol form is submitted

---

src/app/modules/ix-forms/components/ix-select/ix-select.component.html
src/app/modules/ix-forms/components/ix-select/ix-select.component.spec.ts
src/app/modules/ix-forms/components/ix-select/ix-select.component.ts

Go to Credentials -> Local User -> root -> Edit
The field Auxiliary Groups should display labels not values.
Check out ix-select on other forms.
Original PR: https://github.com/truenas/webui/pull/7422
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119172

NAS-119172 / 23.10 / fixed ix-select displays ids instead of labels (by Raz-Dva)

---

src/app/pages/datasets/modules/permissions/components/acl-editor-list/acl-editor-list.component.ts
src/app/pages/datasets/modules/permissions/components/edit-nfs-ace/edit-nfs-ace.component.ts
src/app/pages/datasets/modules/permissions/components/edit-posix-ace/edit-posix-ace.component.ts

Testing: 
1. See bug [video]: 
https://user-images.githubusercontent.com/22980553/207462681-6b41692b-4ab9-4316-b823-26418dfd9f52.mp4
**2. Go to edit ACL page and check fix.**

NAS-119301 / 23.10 / NAS-119370: Edit permissions - long dataset name problem

---

src/app/modules/ix-forms/services/form-error-handler.service.ts
src/app/pages/data-protection/rsync-task/rsync-task-form/rsync-task-form.component.ts

I believe user has an issue where there was a validation error on one of the fields, but it was not visible because this field was behind an ngIf.
1. In Credentials -> Backup Credentials add an incorrect SSH connection.
2. In Data Protection -> Rsync try to create a task using Mode = SSH, Connect using = connection from keychain and select incorrect connection.
It's also possible that there is some other scenario for this.

NAS-119438 / 22.12.1 / Showing errors in rsync form

---

src/app/services/ws.service.ts

… `errno.EACCES` as it is a legitimate error code for many methods
Original PR: https://github.com/truenas/webui/pull/7474
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119437

NAS-119437 / 22.12.1 / Use `ErrnoMixin.ENOTAUTHENTICATED` to redirect to the login page, not… (by themylogin)

---

src/app/modules/ix-forms/services/form-error-handler.service.ts
src/app/pages/data-protection/rsync-task/rsync-task-form/rsync-task-form.component.ts

I believe user has an issue where there was a validation error on one of the fields, but it was not visible because this field was behind an ngIf.
1. In Credentials -> Backup Credentials add an incorrect SSH connection.
2. In Data Protection -> Rsync try to create a task using Mode = SSH, Connect using = connection from keychain and select incorrect connection.
It's also possible that there is some other scenario for this.
Original PR: https://github.com/truenas/webui/pull/7475
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119438

NAS-119438 / 23.10 / Showing errors in rsync form (by undsoft)

---

src/app/pages/dashboard/components/widget-pool/widget-pool.component.html
src/app/pages/dashboard/components/widget-storage/widget-storage.component.html

The Pool Status page does not exist anymore. However, some of that information is available on Pool Dashboard.

NAS-119394 / 23.10 / Fix broken link on widgets

---

src/app/pages/dashboard/components/widget-pool/widget-pool.component.html
src/app/pages/dashboard/components/widget-storage/widget-storage.component.html

The Pool Status page does not exist anymore. However, some of that information is available on Pool Dashboard.
Original PR: https://github.com/truenas/webui/pull/7484
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119394

NAS-119394 / 22.12.1 / Fix broken link on widgets (by denysbutenko)

---

src/app/helptext/sharing/smb/smb.ts

Simple removal of erroneous AFP reference.

PD-18: (CORE 13.0) Fix typo in SMB Hosts Allow and Hosts Deny helptext

---

src/app/modules/common/dialog/show-logs-dialog/show-logs-dialog.component.scss

Now it scrolls by the max-height of `300px`:

NAS-119604 / 23.10 / Design flaw: If the error log is too large, it will be displayed beyond the log window

---

src/app/pages/system/general-settings/support/support.component.ts

How it works now:
https://user-images.githubusercontent.com/22980553/211558909-6489a766-6de9-4d87-8014-634d13ec0d77.mov
Previously if we cancelled, checkbox was marked as checked and didn't get back to default state (unchecked)
Like that:
https://user-images.githubusercontent.com/22980553/211559206-f94aeb14-8137-4067-b302-5b1b1189b61d.mov

NAS-119743 / 23.10 / System -> General -> Support -> Production system checkbox and modal bug

---

src/app/pages/apps-old/forms/chart-form/chart-form.component.ts
src/app/pages/apps/components/chart-form/chart-form.component.ts

`
if (this.isNew || !_.get(this.config, keys)) {
_.unset(data, keys);
}
`
it was unnecessary check because all we needed to do -> just remove field and not check if it has value, if it came inside this method:
`
deleteField$.pipe(untilDestroyed(this)).subscribe({
next: (fieldToBeDeleted) => {
`
that means it should be deleted anyways! 😄

NAS-119716 / 23.10 / Switching a drop down selection, does not "drop" values that are now hidden

---

src/app/interfaces/chart-release.interface.ts
src/app/interfaces/dynamic-form-schema.interface.ts
src/app/modules/ix-forms/components/ix-dynamic-form/ix-dynamic-form-item/ix-dynamic-form-item.component.html
src/app/modules/ix-forms/components/ix-dynamic-form/ix-dynamic-form-item/ix-dynamic-form-item.component.ts
src/app/modules/ix-forms/components/ix-dynamic-form/ix-dynamic-form.component.html
src/app/modules/ix-forms/components/ix-dynamic-form/ix-dynamic-form.component.ts
src/app/modules/ix-forms/components/ix-list/ix-list.component.html
src/app/modules/ix-forms/components/ix-list/ix-list.component.ts
src/app/pages/apps-old/forms/chart-form/chart-form.component.html
src/app/services/schema/app-schema.service.spec.ts
src/app/services/schema/app-shema.transformer.ts

Go to apps:
try to install `docspell`, there you should see pre-created array item:
`default: ["127.0.0.1"]`
This  block `label: IPs` has one element inside of a card.
So when middleware wants to pre-create element, it set's it as as `string[]` 
`default: ["127.0.0.1", "1.1.1.1"]` -> will result in 2 pre-created cards
There might be multiple elements inside of a card.
In this case middleware sets it as `object[]`
example:
```
[
{
name: 'preselected name 1',
value: 'preselected value 1,
},
{
name: 'preselected name 2',
value: 'preselected value 2,
}
]
```
In this case 2 cards will be created.

NAS-119591 / 23.10 / [SCALE/Apps]: `default` does not work in `list` types

---

src/app/interfaces/chart-release.interface.ts
src/app/interfaces/dynamic-form-schema.interface.ts
src/app/modules/ix-forms/components/ix-dynamic-form/ix-dynamic-form-item/ix-dynamic-form-item.component.html
src/app/modules/ix-forms/components/ix-dynamic-form/ix-dynamic-form-item/ix-dynamic-form-item.component.ts
src/app/modules/ix-forms/components/ix-dynamic-form/ix-dynamic-form.component.html
src/app/modules/ix-forms/components/ix-dynamic-form/ix-dynamic-form.component.ts
src/app/modules/ix-forms/components/ix-list/ix-list.component.ts
src/app/pages/applications/forms/chart-form/chart-form.component.html
src/app/services/app-schema.service.spec.ts
src/app/services/app-schema.service.ts

git cherry-pick -x e6383470550f86527268e9202624181ba874e697
git cherry-pick -x 62b7b46070e9ae7369667354f25ddbe613d099f4
git cherry-pick -x 1a362a87bef43095043b7826694d18472510099e
git cherry-pick -x acb81c0d5fcbc44f5c69659837f37888aaa40865
git cherry-pick -x 976096ba85f1fa1b60fd54754c5646ce9bee1dc8
Go to apps:
try to install `docspell`, there you should see pre-created array item:
`default: ["127.0.0.1"]`
This  block `label: IPs` has one element inside of a card.
So when middleware wants to pre-create element, it set's it as as `string[]` 
`default: ["127.0.0.1", "1.1.1.1"]` -> will result in 2 pre-created cards
There might be multiple elements inside of a card.
In this case middleware sets it as …

NAS-119591 / 22.12.1 / [SCALE/Apps]: `default` does not work in `list` types (by AlexKarpov98)

---

src/app/pages/applications/forms/chart-form/chart-form.component.ts

git cherry-pick -x 093ca458af7a90ab9b01af9b0a7d9130f672cc0f
`
if (this.isNew || !_.get(this.config, keys)) {
_.unset(data, keys);
}
`
it was unnecessary check because all we needed to do -> just remove field and not check if it has value, if it came inside this method:
`
deleteField$.pipe(untilDestroyed(this)).subscribe({
next: (fieldToBeDeleted) => {
`
that means it should be deleted anyways! 😄
Original PR: https://github.com/truenas/webui/pull/7567
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119716

NAS-119716 / 22.12.1 / Switching a drop down selection, does not "drop" values that are now hidden (by AlexKarpov98)

---

src/app/core/testing/utils/mock-storage-generator.utils.ts
src/app/enums/v-dev-type.enum.ts
src/app/pages/storage/components/dashboard-pool/topology-card/topology-card.component.html
src/app/pages/storage/components/dashboard-pool/topology-card/topology-card.component.spec.ts
src/app/pages/storage/components/dashboard-pool/topology-card/topology-card.component.ts
src/app/services/storage.service.spec.ts
src/app/services/storage.service.ts

To test:
Create each configuration and check the reported width in the Storage Dashboard topology card.
- Two raidz1 vdevs with 5 disks in each vdev. Topology card should say "5 wide"
- Two mirror vdevs with 2 disks in each vdev. Topology card should say "2 wide"
- Two mirrors. One made with two disks and another with 3 disks. Topology card should say "Mixed Width VDEVs"

NAS-119668: Correctly report vdev width

---

src/app/pages/storage/modules/disks/components/disk-form/disk-form.component.ts

git cherry-pick -x 7dc806bb42ffa4169886fff25d4b49bc556127e0
git cherry-pick -x 3a0b871f97d95386a568705085cac2ee26f9295d
main was merged here:
https://github.com/truenas/webui/pull/7591
now it's a cleanup PR
Original PR: https://github.com/truenas/webui/pull/7583
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119844

NAS-119844 / 22.12.1 / NVMe drives show "Enable S.M.A.R.T." checkbox unchecked even if `togglesmart` API field is true (by AlexKarpov98)

---

src/app/modules/common/dialog/error-dialog/error-dialog.component.scss

NAS-119950 / 23.10 / No scroll-bar on traceback screens in webUI

---

src/app/modules/ix-icon/ix-icon.component.ts
src/app/pages/datasets/components/dataset-details-panel/dataset-details-panel.component.scss
src/app/pages/storage/modules/devices/components/devices/devices.component.html
src/app/pages/storage/modules/devices/components/disk-details-panel/disk-details-panel.component.scss

Testing:
- Switch to mobile view
- Open dataset
- If icon is there, go to Storage and then go back.
- Open same dataset 
-- 
As well test devices for the same logic

NAS-119980 / 23.10 / Missing icon in dataset details header

---

src/app/modules/ix-icon/ix-icon.component.ts
src/app/pages/datasets/components/dataset-details-panel/dataset-details-panel.component.scss
src/app/pages/storage/modules/devices/components/devices/devices.component.html
src/app/pages/storage/modules/devices/components/disk-details-panel/disk-details-panel.component.scss

Testing:
- Switch to mobile view
- Open dataset
- If icon is there, go to Storage and then go back.
- Open same dataset 
-- 
As well test devices for the same logic
Original PR: https://github.com/truenas/webui/pull/7625
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119980

NAS-119980 / 22.12.2 / Missing icon in dataset details header (by AlexKarpov98)

---

src/app/modules/layout/components/topbar/topbar.component.ts
src/app/services/auth/auth.service.ts
src/app/services/system-general.service.ts
src/app/services/websocket-connection.service.ts
src/app/services/ws2.service.ts
src/app/views/sessions/signin/store/signin.store.spec.ts
src/app/views/sessions/signin/store/signin.store.ts

The new `WebsocketConnectionService` wasn't throwing errors properly. It should do that now.
Also, the new method called in the constructor of `SystemGeneralService` is there because not putting it there is causing a race condition of some sort where the signin page keeps loading indefinitely and you can't login. Refreshing the signin page a few times should reproduce that bug.

NAS-120182 / 23.10 / Fixed error throwing my new ws2

---

src/app/services/app-schema.service.ts

git cherry-pick -x d0bfa2e4f7b3b0a8c5fc8286cb32290185592dcc
There was a problem where for some reason **checkIsValidSchedule** received `undefined` or so and caused error.
Original PR: https://github.com/truenas/webui/pull/7683
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120076

NAS-120076 / 22.12.1 / Unable to edit an App (by AlexKarpov98)

---

src/app/pages/storage/components/manager/manager.component.html
src/app/pages/storage/components/manager/manager.component.ts
src/app/pages/storage/components/manager/vdev/vdev.component.ts

Testing: in create pool click Suggest Layout.
If you don't see Suggest Layout, you may need to remove:
```
*ngIf="suggestableDisks.length <= 8"
```
Original PR: https://github.com/truenas/webui/pull/7701
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119941

NAS-119941 / 22.12.2 / Drives disappear when "Suggest Layout" is used in Create … (by undsoft)

---

src/app/pages/storage/components/manager/manager.component.html
src/app/pages/storage/components/manager/manager.component.ts
src/app/pages/storage/components/manager/vdev/vdev.component.ts

Testing: in create pool click Suggest Layout.
If you don't see Suggest Layout, you may need to remove:
```
*ngIf="suggestableDisks.length <= 8"
```
Original PR: https://github.com/truenas/webui/pull/7701
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119941

NAS-119941 / 23.10 / Drives disappear when "Suggest Layout" is used in Create … (by undsoft)

---

src/app/services/app-shema.transformer.ts

The issue was caused because the logic in the addressed method skipped the item and went directly to its attributes and treated them as a direct child of the grand parent. Removing that special treatment fixes this error.
Click `Launch Docker Image` on the apps page. Enter `nginx` in the `Image Repository` field and add a couple of options `'/abc'`, `'/def'` in the `Memory Backed Volumes` field. When you submit, the data sent with the request payload should have the `emptyDirVolumes` field the following formatting `{ ..., emptyDirVolumes: [{ mouthPath: '/abc' }, { mountPath: '/def' }], ... }` instead of `{ ..., emptyDirVolumes: [ '/abc', '/def' ], ... }`
Also, check for regressions by trying to install some other apps.

NAS-119431 / 22.12.2 / No special treatment for dictionary list items

---

src/app/services/schema/app-shema.transformer.ts

The issue was caused because the logic in the addressed method skipped the item and went directly to its attributes and treated them as a direct child of the grand parent. Removing that special treatment fixes this error.
Click `Launch Docker Image` on the apps page. Enter `nginx` in the `Image Repository` field and add a couple of options `'/abc'`, `'/def'` in the `Memory Backed Volumes` field. When you submit, the data sent with the request payload should have the `emptyDirVolumes` field the following formatting `{ ..., emptyDirVolumes: [{ mouthPath: '/abc' }, { mountPath: '/def' }], ... }` instead of `{ ..., emptyDirVolumes: [ '/abc', '/def' ], ... }`
Also, check for regressions by trying to install some other apps.
Original PR: https://github.com/truenas/webui/pull/7717
Jira URL: …

NAS-119431 / 23.10 / No special treatment for dictionary list items (by RehanY147)

---

src/app/interfaces/subs.interface.ts
src/app/modules/entity/entity-form/components/form-upload/form-upload.component.ts
src/app/pages/datasets/modules/encryption/components/dataset-unlock/dataset-unlock.component.ts
src/app/pages/system/file-ticket/file-ticket-form/file-ticket-form.component.spec.ts
src/app/pages/system/file-ticket/file-ticket-form/file-ticket-form.component.ts
src/app/pages/system/file-ticket/file-ticket-licensed-form/file-ticket-licensed-form.component.spec.ts
src/app/pages/system/file-ticket/file-ticket-licensed-form/file-ticket-licensed-form.component.ts
src/app/pages/system/general-settings/upload-config-dialog/upload-config-dialog.component.spec.ts
src/app/pages/system/general-settings/upload-config-dialog/upload-config-dialog.component.ts
src/app/pages/system/update/manual-update-form/manual-update-form.component.ts
src/app/services/ix-file-upload.service.ts

The ticket bug was caused by the fact that the token generated by the call `auth.generate_token` expires after 300 seconds. So, at the time of using that token, if it has expired, middleware will give a 403 error.
This PR aims to call `auth.generate_token` to generate a fresh token every time it is used in such a way.

NAS-120083 / 22.12.2 / Fixed calls wherever token is used

---

src/app/interfaces/chart-release.interface.ts
src/app/pages/apps-old/forms/chart-form/chart-form.component.ts
src/app/pages/apps/components/chart-form/chart-form.component.ts
src/app/services/schema/app-schema.service.spec.ts
src/app/services/schema/app-schema.service.ts

Write to @stavros-k  to set up app according to this comment:
https://ixsystems.atlassian.net/browse/NAS-117906?focusedCommentId=179172 
Check app new fields
AND in the end check `onSubmit(): void {` method in **chart-form.component.ts**
**const data = this.appSchemaService.serializeFormValue(this.form.getRawValue(), this.chartSchema) as ChartFormValues;**
fill all the required fields, then submit and:
console.log(data) and see that field where:
-- **NULL_FALSE is not in the object**
-- **NULL_TRUE is in the object as null**

NAS-117906 / 23.10 / Cannot clear optional integer value - nodePort

---

tests/bdd/ha-bhyve02/test_NAS_T0951.py
tests/bdd/ha-bhyve02/test_NAS_T0961.py
tests/bdd/ha-bhyve02/test_NAS_T0962.py
tests/bdd/ha-bhyve02/test_NAS_T0964.py
tests/bdd/ha-bhyve02/test_NAS_T1657_NFSv3_failover.py
tests/bdd/ha-bhyve02/test_NAS_T1658_alert_on_failover.py
tests/bdd/ha-bhyve02/test_NAS_T1659_middleware_log_on_failover.py
tests/bdd/ha-bhyve02/test_NAS_T1660_smb_permision_on_failover.py
tests/bdd/reusableSeleniumCode.py
tests/bdd/scale/test_NAS_T1223.py
tests/bdd/xpaths.py

* Adding test cases to test Alert and failover with a degraded pool.
* Adding HA_Login_Status_Enable and Trigger_Failover in HA test
* Adding Test Case to verify middleware logs is available after failover
* Fixed missing notifications and added more time to wait for HA status
* Adding test cases to test SMB permission is kept after failover
* Adding sleep before failover in our SMB test cases.
* Fixed mat-select with games in T951
* restore old step in T951

TE-117 / 23.10 / backport "Adding test cases to verify Alert, middleware logs and SMB permission on failover" from  (#7754)

---

src/app/interfaces/chart-release.interface.ts
src/app/pages/applications/forms/chart-form/chart-form.component.ts
src/app/services/app-schema.service.spec.ts
src/app/services/app-schema.service.ts

git cherry-pick -x ce073ffe75ac07b902df2b8c46d6f7ba02a2ba04
git cherry-pick -x fbb8a59fb529ac1128d3714845b9a49e0b33257c
git cherry-pick -x 1eb09346d524cc71cfb221a454ecc97bb10ec2ef
Write to @stavros-k  to set up app according to this comment:
https://ixsystems.atlassian.net/browse/NAS-117906?focusedCommentId=179172 
Check app new fields
AND in the end check `onSubmit(): void {` method in **chart-form.component.ts**
**const data = this.appSchemaService.serializeFormValue(this.form.getRawValue(), this.chartSchema) as ChartFormValues;**
fill all the required fields, then submit and: …

NAS-117906 / 22.12.2 / Cannot clear optional integer value - nodePort (by AlexKarpov98)

---

src/app/pages/vm/vm-list/stop-vm-dialog/stop-vm-dialog.component.html
src/app/pages/vm/vm-list/stop-vm-dialog/stop-vm-dialog.component.spec.ts
src/app/pages/vm/vm-list/stop-vm-dialog/stop-vm-dialog.component.ts
src/app/pages/vm/vm-list/vm-list.component.ts

The issue was that we open `StopVmDialogComponent` with `MatDialog` and when the call is made to middleware, all of the subscriptions are set to be destroyed when `StopVmDialogComponent` is destroyed which happens immediately because we are done with that dialog and now we only need the job dialog. So, updated the code to keep the subscriptions alive until the parent component is destroyed.

NAS-120266 / 23.10 / Dont unsub when dialog is destroyed

---

src/app/interfaces/job.interface.ts
src/app/modules/jobs/store/job.selectors.ts
src/app/pages/jobs/job-logs-row/job-logs-row.component.spec.ts

New **Boolean** field was added to the API.
Check this:
https://github.com/truenas/middleware/pull/10714/files

NAS-120387 / 23.10 / When loading currently running jobs for task manager, exclude the ones that have `transient: true`

---

src/app/pages/task-calendar/replication/replication-form/replication-form.component.ts

Create a replication task. 
Set the state to true for the Schedule checkbox.
Edit the task and change the Schedule state to false. 
There should be no errors after saving.

NAS-119783 / 13.0 / NAS-119783 - Fixed error "[schedule] A dict was expected" for create a replication task

---

src/app/services/auth/auth.service.spec.ts
src/app/services/auth/auth.service.ts
src/app/views/sessions/signin/store/signin.store.spec.ts

The tests check for all scenarios when you login via either username/password or with a token. Also checks scenarios for logout.
This PR also fixes the race condition potential in AuthService that was fixed in WebsocketService by https://github.com/truenas/webui/pull/7829

NAS-120307 / 23.10 / Added tests for `AuthService`

---

src/app/modules/common/search-input/search-input.component.scss
src/app/modules/common/search-input/search-input.component.ts

For testing, please check `ix-input-search` when it is disabled, e.g., while loading.

NAS-120466 / 23.10 / Better disabled state for search input

---

src/app/pages/system/view-enclosure/classes/chassis-view.ts

Testing requires physical access to hardware
- Enclosure UI visualization should update when disk is added or removed (could take up to 10 seconds or so)
- Verify that the color coding on drivetrays is correct and matches physical location of disk
Do this on both MINI products as well as Enterprise models

NAS-120381 / 22.12.2 / Calculate slot when no disk is present

---

src/app/pages/services/components/service-rsync/rsyncconfiguration/rsyncmodule/rsyncconfiguration-form.component.ts

Testing: see ticket. Original issue didn't happen every time, you had to open rsync module several times.
Note to self: do not merge before u4 release.

NAS-120250 / 13.0 / Fixing incorrect rsync module being edited

---

src/app/pages/system/view-enclosure/classes/chassis-view.ts

Testing requires physical access to hardware
- Enclosure UI visualization should update when disk is added or removed (could take up to 10 seconds or so)
- Verify that the color coding on drivetrays is correct and matches physical location of disk
Do this on both MINI products as well as Enterprise models
Original PR: https://github.com/truenas/webui/pull/7839
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120381

NAS-120381 / 23.10 / Calculate slot when no disk is present (by dszidi)

---

src/app/services/schema/app-schema.service.ts

For testing you can use machine from ticket.
Go to apps -> Available Apps -> search for **minio**
click **Install** 
Under **Minio Configuration** configuration there is:
Test Certificate. 
Once you select a certificate, there should appear `Test cert` string field.
And if you select `No certificate` then `Test cert` string input field should disappear.
Or contact @stavros-k (he knows how to setup on any machine)

NAS-120492 / 23.10 / [SCALE/Apps]: Initial value of a dropdown is null, but after picking something and reverting to empty is no longer null

---

src/app/pages/storage/components/dashboard-pool/pool-usage-card/pool-usage-card.component.html
src/app/pages/storage/components/dashboard-pool/pool-usage-card/pool-usage-card.component.spec.ts

Clicking on the "View Disk Space Reports" button on the pool's dashboard usage card should take you to the Partition/Space reports.

NAS-119689 / 22.12.2 / Update pool-usage-card.component.html

---

src/app/pages/storage/components/dashboard-pool/pool-usage-card/pool-usage-card.component.html
src/app/pages/storage/components/dashboard-pool/pool-usage-card/pool-usage-card.component.spec.ts

git cherry-pick -x 9e1603f28dc324a889e33b7d9fefc1ea053bce2e
git cherry-pick -x d76353c31156aa0bf4465512d141e7af5bbded03
git cherry-pick -x da66080489d2c0b26a6466531dccbaa128301f3a
Clicking on the "View Disk Space Reports" button on the pool's dashboard usage card should take you to the Partition/Space reports.
Original PR: https://github.com/truenas/webui/pull/7874
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119689

NAS-119689 / 23.10 / Update pool-usage-card.component.html (by RehanY147)

---

src/app/modules/common/dialog/show-logs-dialog/show-logs-dialog.component.html
src/app/modules/common/dialog/show-logs-dialog/show-logs-dialog.component.scss
src/app/pages/data-protection/components/data-protection-dashboard/data-protection-dashboard.component.ts

git cherry-pick -x b7d22d1d19e29ce9972074c168340e12ff2a142e
git cherry-pick -x 57aa02f37dc340b69012a97e3ab2b0f4ddb2dfc7
git cherry-pick -x 2ff5ef3c87a1fa4d21af5c8bad7a2fdab17b6449
Original PR: https://github.com/truenas/webui/pull/7886
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120621

NAS-120621 / 22.12.2 / Leading whitespaces lost when displaying logs (by AlexKarpov98)

---

src/app/enums/failover-disabled-reason.enum.ts
src/app/helptext/topbar.ts

See https://github.com/truenas/middleware/pull/10877 for details. This should, hopefully, ease confusion when end-user initiates a manual failover and is presented the login page. Instead of showing all reasons why HA is unhealthy (which is expected since user initiated the failover process), it'll give a more concise message to the end-user.

NAS-121066 / 23.10 / add to LOC_FAILOVER_ONGOING HA disabled reasons

---

src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.ts

To test go to enclosure UI and click on a disk. Underneath the drive icon there should not be an "Identify Drive" button under the disk icon. Look in the ticket comments for a test machine url

NAS-121054 / 22.12.2 / Hide identify button for R30

---

src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.ts

To test go to enclosure UI and click on a disk. Underneath the drive icon there should not be an "Identify Drive" button under the disk icon. Look in the ticket comments for a test machine url
Original PR: https://github.com/truenas/webui/pull/7934
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121054

NAS-121054 / 22.12.3 / Hide identify button for R30 (by dszidi)

---

src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.ts

To test go to enclosure UI and click on a disk. Underneath the drive icon there should not be an "Identify Drive" button under the disk icon. Look in the ticket comments for a test machine url
Original PR: https://github.com/truenas/webui/pull/7934
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121054

NAS-121054 / 23.10 / Hide identify button for R30 (by dszidi)

---

src/app/pages/account/users/user-form/user-form.component.ts

Testing:
Credentials -> Local Users:
Try to update user 
IF Home Directory is `/nonexistent` we don't need to show warning modal and simply update user. 
Once we changed it (Home Directory) -> Modal should warn us.

NAS-121043 / 23.10 / webUI is showing incorrect warning

---

src/app/pages/account/users/user-form/user-form.component.ts

Testing:
Credentials -> Local Users:
Try to update user 
IF Home Directory is `/nonexistent` we don't need to show warning modal and simply update user. 
Once we changed it (Home Directory) -> Modal should warn us.
Original PR: https://github.com/truenas/webui/pull/7917
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121043

NAS-121043 / 22.12.3 / webUI is showing incorrect warning (by AlexKarpov98)

---

src/app/pages/account/users/user-form/user-form.component.ts

Testing:
Credentials -> Local Users:
Try to update user 
IF Home Directory is `/nonexistent` we don't need to show warning modal and simply update user. 
Once we changed it (Home Directory) -> Modal should warn us.
Original PR: https://github.com/truenas/webui/pull/7917
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121043
Original PR: https://github.com/truenas/webui/pull/7941
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121043

NAS-121043 / 22.12.2 / webUI is showing incorrect warning (by AlexKarpov98) (by bugclerk)

---

src/app/pages/dashboard/components/widget-cpu/widget-cpu.component.html

Some people complained about it and to be fair high CPU usage is not an error.

NAS-121107 / 23.10 / Remove high CPU usage indicator

---

src/app/pages/storage/modules/disks/components/disk-list/disk-list.component.ts
src/app/pages/storage/modules/disks/components/disk-wipe-dialog/disk-wipe-dialog.component.html
src/app/pages/storage/modules/disks/components/disk-wipe-dialog/disk-wipe-dialog.component.scss

git cherry-pick -x 0f3b666a3441b67b9ab061aeaa68a66a2560850a
git cherry-pick -x 36a1a26267adab95566889ead6f4dfd73c8c2c81
Go Storage -> Disks 
Execute wipe a disk that is part of an exported zpool.
The disk status should be updated in the Pool column after the wipe
Original PR: https://github.com/truenas/webui/pull/7974
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121035

NAS-121035 / 22.12.3 / Fixed updating status of unused disks (by Raz-Dva)

---

src/app/pages/datasets/components/dataset-details-card/dataset-details-card.component.html
src/app/pages/datasets/components/dataset-details-card/dataset-details-card.component.spec.ts

From the original ticket:
> Since Enable Atime does not really apply to Zvol datasets, that line should be removed from the "Zvol Details" section of the following TrueNAS SCALE page
For testing, go to the datasets page and check if it does meet requirements

NAS-121183 / 23.10 / Hide `Enable Atime` for Zvol

---

src/app/pages/datasets/components/dataset-details-card/dataset-details-card.component.html

git cherry-pick -x 63687a26ba54879463daf7eb1290bd239ae1fc09
git cherry-pick -x 1806a3b62357bc0e6e769407ef78dd7b004d1040
From the original ticket:
> Since Enable Atime does not really apply to Zvol datasets, that line should be removed from the "Zvol Details" section of the following TrueNAS SCALE page
For testing, go to the datasets page and check if it does meet requirements
Original PR: https://github.com/truenas/webui/pull/7999
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121183

NAS-121183 / 22.12.3 / Hide `Enable Atime` for Zvol (by denysbutenko)

---

src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.scss
src/app/views/sessions/signin/signin-form/signin-form.component.html
src/app/views/sessions/signin/signin-form/signin-form.component.scss

problem was that `.cdk-overlay-pane` was taking place over input with z-index: 1000

NAS-121060 / 23.10 / Difficult to click on the username field of the login page

---

src/app/modules/entity/entity-table/entity-table.component.ts
src/app/modules/entity/entity-table/entity-table.interface.ts
src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts
src/app/pages/data-protection/cloudsync/cloudsync-list/cloudsync-list.component.ts
src/app/pages/data-protection/replication/replication-list/replication-list.component.ts
src/app/pages/data-protection/rsync-task/rsync-task-form/rsync-task-form.component.ts
src/app/pages/data-protection/rsync-task/rsync-task-list/rsync-task-list.component.ts
src/app/pages/data-protection/snapshot/snapshot-list/snapshot-list.component.ts
src/app/pages/data-protection/snapshot/snapshot-task/snapshot-task.component.ts

**Description**
> Adding many cloud sync tasks causes the UI to become slower and slower. Eventually every click takes 30 seconds for the UI to recover. System is not under any load or shows any spike in CPU during this event.
**The Root Cause**
The Cloud Sync page uses the deprecated `ix-entity-table` component with the rare `asyncView` param. When a user interacts with the cloud sync form and when the form is closed, new data is fetched, creating an interval that invokes fetching data every 10 seconds. One form close - one new interval. After data fetching, it gathers transforming, which is a heavy operation if you have more than 15 entries. That causes the main thread to be locked, and UI is unresponsive until the page gets refreshed.
**How to reproduce the issue?**
1. Go to the full …

NAS-121215 / 22.12.3 / Reduce memory leak in `ix-entity-table` component

---

src/app/modules/entity/entity-table/entity-table.component.ts
src/app/modules/entity/entity-table/entity-table.interface.ts
src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts
src/app/pages/data-protection/cloudsync/cloudsync-list/cloudsync-list.component.ts
src/app/pages/data-protection/replication/replication-list/replication-list.component.ts
src/app/pages/data-protection/rsync-task/rsync-task-form/rsync-task-form.component.ts
src/app/pages/data-protection/rsync-task/rsync-task-list/rsync-task-list.component.ts
src/app/pages/data-protection/snapshot/snapshot-list/snapshot-list.component.ts
src/app/pages/data-protection/snapshot/snapshot-task/snapshot-task.component.ts

**Description**
> Adding many cloud sync tasks causes the UI to become slower and slower. Eventually every click takes 30 seconds for the UI to recover. System is not under any load or shows any spike in CPU during this event.
**The Root Cause**
The Cloud Sync page uses the deprecated `ix-entity-table` component with the rare `asyncView` param. When a user interacts with the cloud sync form and when the form is closed, new data is fetched, creating an interval that invokes fetching data every 10 seconds. One form close - one new interval. After data fetching, it gathers transforming, which is a heavy operation if you have more than 15 entries. That causes the main thread to be locked, and UI is unresponsive until the page gets refreshed.
**How to reproduce the issue?**
1. Go to the full …

NAS-121215 / 23.10 / Reduce memory leak in `ix-entity-table` component (by denysbutenko)

---

src/app/core/pipes/format-datetime.pipe.spec.ts
src/app/core/pipes/format-datetime.pipe.ts

`timeFormat` in local storage may have an old-style format escape `A` that needs to be converted to `aa`. If not converted, the UI does not work reliably, creating hundreds of RangeError messages in the console and potentially freezing the screen.

NAS-121308: Resolve issues with old-style timeFormat

---

src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.ts

Test against an M Series machine with the following conditions:
- Rear drives are NVME
- Rear drives are not assigned to a pool
- no console errors when switching to rear view
Check ticket description for an M Series url

NAS-121342 / 22.12.3 / Fix rear NVME drives on M Series

---

src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.ts

Test against an M Series machine with the following conditions:
- Rear drives are NVME
- Rear drives are not assigned to a pool
- no console errors when switching to rear view
Check ticket description for an M Series url
Original PR: https://github.com/truenas/webui/pull/8034
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121342

NAS-121342 / 22.12.2 / Fix rear NVME drives on M Series (by dszidi)

---

src/app/interfaces/api-directory.interface.ts
src/app/pages/account/users/user-form/user-form.component.html
src/app/pages/account/users/user-form/user-form.component.ts

At the **Credentials > Users > Add User** and **Edit User**, 
On the **Add/Edit user** form, 
When value of **Primary Groups** or **Auxiliary Groups** is changed
In the **Shell** dropdown input box, the list of options is should be refreshed from the API call `user.shell_choices`

NAS-121222 / 23.10 / Update `shell` field

---

src/app/interfaces/api-directory.interface.ts
src/app/pages/account/users/user-form/user-form.component.html
src/app/pages/account/users/user-form/user-form.component.ts

At the **Credentials > Users > Add User** and **Edit User**, 
On the **Add/Edit user** form, 
When value of **Primary Groups** or **Auxiliary Groups** is changed
In the **Shell** dropdown input box, the list of options is should be refreshed from the API call `user.shell_choices`
Original PR: https://github.com/truenas/webui/pull/8023
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121222

NAS-121222 / 22.12.3 / Update `shell` field (by bvasilenko)

---

src/app/interfaces/api-directory.interface.ts
src/app/interfaces/chart-release-event.interface.ts
src/app/pages/apps/apps.module.ts
src/app/pages/apps/components/installed-apps/app-row/app-row.component.html
src/app/pages/apps/components/installed-apps/app-row/app-row.component.scss
src/app/pages/apps/components/installed-apps/app-row/app-row.component.spec.ts
src/app/pages/apps/components/installed-apps/app-row/app-row.component.ts
src/app/pages/apps/components/installed-apps/app-status-cell/app-status-cell.component.html
src/app/pages/apps/components/installed-apps/app-status-cell/app-status-cell.component.scss
src/app/pages/apps/components/installed-apps/app-status-cell/app-status-cell.component.spec.ts
src/app/pages/apps/components/installed-apps/app-status-cell/app-status-cell.component.ts
src/app/pages/apps/components/installed-apps/installed-apps.component.html
src/app/pages/apps/components/installed-apps/installed-apps.component.scss
src/app/pages/apps/components/installed-apps/installed-apps.component.ts
src/app/pages/apps/enum/app-status.enum.ts
src/app/pages/apps/services/applications.service.ts

**Description**
> On the installed apps page, when you click to start a stopped app, the starting process is shown as a progress in a dialog. Instead use the state tiles in the row to show that the app is starting. Clicking on that tile can bring up this dialog that’s showing now.
**Testing**
- Open the Installed Apps page
- Make a test of the app status

NAS-121296 / 23.10 / Implement better app status

---

src/app/modules/jobs/components/jobs-panel/jobs-panel.component.spec.ts
src/app/modules/jobs/components/jobs-panel/jobs-panel.component.ts
src/app/modules/jobs/store/job.selectors.ts

Goal is to filter out `transient: true` jobs.

NAS-121445 / 23.10 / Trivial: Waiting to renew Kerberos ticket. Current ticketexpires

---

src/app/pages/services/components/service-dynamic-dns/service-dynamic-dns.component.html
src/app/pages/services/components/service-dynamic-dns/service-dynamic-dns.component.spec.ts
src/app/pages/services/components/service-dynamic-dns/service-dynamic-dns.component.ts
src/app/pages/services/components/service-lldp/service-lldp.component.html
src/app/pages/services/components/service-lldp/service-lldp.component.ts
src/app/pages/services/components/service-nfs/service-nfs.component.html
src/app/pages/services/components/service-nfs/service-nfs.component.spec.ts
src/app/pages/services/components/service-nfs/service-nfs.component.ts
src/app/pages/services/components/service-rsync/rsync-configure/rsync-configure.component.html
src/app/pages/services/components/service-rsync/rsync-configure/rsync-configure.component.ts
src/app/pages/services/components/service-s3/service-s3.component.html
src/app/pages/services/components/service-s3/service-s3.component.spec.ts
src/app/pages/services/components/service-s3/service-s3.component.ts
src/app/pages/services/components/service-smb/service-smb.component.html
src/app/pages/services/components/service-smb/service-smb.component.spec.ts
src/app/pages/services/components/service-smb/service-smb.component.ts
src/app/pages/services/components/service-snmp/service-snmp.component.html
src/app/pages/services/components/service-ssh/service-ssh.component.html
src/app/pages/services/components/service-ssh/service-ssh.component.spec.ts
src/app/pages/services/components/service-ssh/service-ssh.component.ts
src/app/pages/services/components/service-ups/service-ups.component.html
src/app/pages/services/components/service-ups/service-ups.component.spec.ts
src/app/pages/services/components/service-ups/service-ups.component.ts
src/app/pages/services/components/service-webdav/service-webdav.component.html
src/app/pages/services/components/service-webdav/service-webdav.component.ts

**Description**
> When identifying the SNMP service edit page cancel button, the data-test tag is defined differently than other service cancel buttons.  This should be consistent.
For testing, the cancel button on the `Services -> SNMP` page should have `data-test="button-cancel"` value.

NAS-121440 / 23.10 / Sync cancel buttons in services

---

src/app/services/auth/auth.service.spec.ts
src/app/services/auth/auth.service.ts
src/app/services/dialog.service.ts
src/app/services/error-handler.service.ts

See ticket for testing instructions.
The problem was that when we ran that command or generally on reload, the `ReplaySubject` `lastGeneratedAuthToken$` would remember the last token value, which was invalid at this point. When we went back to the shell, it loaded the wrong token the first couple of times and shell failed to authenticate so it loaded a couple of empty pages before actually loading the right one.
This problem was also partially caused by the missing `take(1)` in the generated auth token repeated action pipe. We only wanted that sequence to execute once every time the timer ticks. But because of that missing `take(1)` pipe, every time the `isAuthenticated$` observable emitted a value, the sequence ran again which caused token to reload without need.
Just test that …

NAS-121124 / 23.10 / Fixed the resizing on reload shell

---

.github/actions/prepare/action.yml
Dockerfile

Reverts truenas/webui#8054
Due to test failures:
```
TypeError: Cannot redefine property: window
> 1 | import 'jest-canvas-mock';
```
The tests are passed in `18.15.x` and failed in `18.16.x`:
https://github.com/nodejs/node/issues/47563
https://github.com/nodejs/node/pull/46615

Revert "NAS-121402 / 23.10 / Upgrade node to hydrogen (18 LTS)"

---

src/app/helptext/sharing/iscsi/iscsi.ts
src/app/pages/sharing/iscsi/iscsi-wizard/iscsi-wizard.component.ts

When creating a new iSCSI target the name field has some rules that aren't reflected until you reach the end of the wizard at which point you may find that the name was invalid. While these rules are probably known by someone familiar with iSCSI, it's not necessarily user-friendly as-is.
I was trying to find a way to show a more helpful validation error when the validation rule was violated, but gave up and instead added the specificity to the tooltip. Also, happy to port this to the latest!

Validate iSCSI Target Name field

---

src/app/pages/sharing/components/shares-dashboard/shares-dashboard.component.ts

NAS-121681 / 23.10 / Shares cards (2 per row) bad visualization

---

src/app/pages/apps/components/installed-apps/installed-apps.component.ts

Add the `Choose Pool` button on the Installed Apps table on first use.
For testing, use a fresh system or `unset pool` to see the needed state.
After the pool is selected, you'll see the next state:

NAS-121679 / 23.10 / Update FirstUse state on Installed Apps

---

src/app/services/ws.service.ts

Currently on master, UI just forgets about the subscriptions when the websocket closes for whatever reason. However, this still leaves a possibility that somewhere we are still subscribed to that event. This is preventive measure to make sure that before forgetting about it, we complete the observable.

NAS-121703 / 23.10 / Closing subscriptions when websocket closes

---

src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts

**Testing**
On the **Create/Edit Dataset** form,
1. Create a pool `tank1` with the default options and a child dataset `tank1/test1` also with the default options. When creating the `tank1/test1` dataset, make sure that the GUI indicated "Checksum: inherit (on)" 
2. Go back to the “Edit Options” for the `tank1/test1` 
The value displayed in the WebUI should match the value returned by the call 
```
zfs get checksum tank1/test1
```
For more details please see ticket.

NAS-120203 / 13.0 / Create/Edit Dataset > Fix Discrepancies between GUI and command line output of dataset checksum

---

src/app/modules/ix-forms/services/ix-formatter.service.ts

**Testing**
At the **Capacity Settings** block,
Test using a decimal in the **Quota** and **Reserved** fields
Original PR: https://github.com/truenas/webui/pull/7643
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119945

NAS-119945 / 22.12.3 / Save input decimals (by bvasilenko)

---

src/app/modules/scheduler/components/scheduler/scheduler.component.scss

Scheduler width & content is fixed like that:

NAS-121738 / 23.10 / Snapshot Lifetime Unit Would Be Hidden If Custom ScheduleIs Too Long

---

src/app/pages/storage/modules/pool-manager/components/inventory/inventory.component.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/create-data-wizard-step/create-data-wizard-step.component.ts
src/app/pages/storage/modules/pool-manager/store/manual-disk-selection-store.service.ts
src/app/pages/storage/modules/pool-manager/store/pools-manager-store.service.ts

Reverts truenas/webui#8141
The original PR leaves a couple of bugs that need to be addressed. Even if I do nothing and have a couple of disks in the inventory, they don't show up in the drop downs on the second step. Also, if I go back to the first step and mark some checkboxes, the second step options don't update.
Furthermore, the `take(1)` for `usableUnusedDisks$` from the store needs to be removed so when disks update the options can update. But removing that causes infinite emits from the selector because in that subscription we are updating form values which triggers state update which triggers `usableUnusedDisks$` update in an infinite loop.

Revert "NAS-121686 / 23.10 / Add usableUnusedDisks stream"

---

src/app/core/testing/utils/mock-enclosure.utils.ts
src/app/services/ws.service.ts
src/environments/environment.prod.ts

Removed a condition that broke UI if `mock-pool` was disabled
Try enabling/disabling `mock-enclosure` and `mock-disks` with and without `mock-pools` enabled
There should not be any combination that results in browser console error that breaks the UI

NAS-121844 / 23.10 / Make sure mock utility doesn't break UI

---

src/app/components/common/topbar/topbar.component.ts
src/app/pages/system/general/general.component.ts
src/app/pages/system/update/manualupdate/manualupdate.component.ts
src/app/pages/system/update/update.component.ts

To reproduce previous issue.
1. In `reboot.component.ts` replace add:
```
console.log('rebooted');
return;
```
before
```
this.ws.call('system.reboot', {})
```
2. Remove `{ skipLocationChange: true }` in `topbar.component.ts`.
3. Press reboot in UI.
4. Change address in browser to `http://localhost` and press Enter.
Observe that you are at reboot page again.

NAS-120602 / 13.0 / Uncommanded reboot from logging into the web interface

---

src/app/modules/ix-forms/services/ix-formatter.service.ts
src/app/modules/scheduler/components/scheduler/scheduler.component.scss

git cherry-pick -x 440027a2993263003b6f584c8db9cde4ce5c2d40
git cherry-pick -x 63c1fe7adfa52ceff3f8f6e99399f0cd6bbaf2da
Scheduler width & content is fixed like that:
Original PR: https://github.com/truenas/webui/pull/8154
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121738

NAS-121738 / 22.12.3 / Snapshot Lifetime Unit Would Be Hidden If Custom ScheduleIs Too Long (by AlexKarpov98)

---

src/app/pages/storage/modules/devices/components/topology-item-node/topology-item-node.component.spec.ts
src/app/pages/storage/modules/devices/components/topology-item-node/topology-item-node.component.ts

Remove the capacity value from VDEV items on the Manage Devices page.
An example

NAS-121773 / 23.10 / Show capacity for disks only on manage devices

---

tests/boot.exp

This will fix the boot issue for 13.1. It should now affect the 13.0 boot since it is how it is set up for the 13.0 and 13.1 HA boot.

NAS-121914 / 13.0 / Fixed Expect Enter an option instead of https:// in boot.exp

---

src/app/modules/layout/components/topbar/jobs-indicator/jobs-indicator.component.html
src/app/modules/layout/components/topbar/jobs-indicator/jobs-indicator.component.spec.ts
src/app/modules/layout/components/topbar/topbar.component.html
src/app/modules/layout/components/topbar/topbar.component.scss
src/app/modules/truecommand/truecommand-button.component.html
src/app/modules/truecommand/truecommand-button.component.scss

A simple fix that moves badges to the upper level due to a bug in `ix-icon`. The issue with ix-icon will be resolved in another ticket - https://ixsystems.atlassian.net/browse/NAS-121890
For testing, check badges appear on the topbar (tc, jobs, alerts).

NAS-121848 / 23.10 / Fix missing mat-badges on topbar

---

src/app/pages/account/users/user-form/user-form.component.spec.ts
src/app/pages/account/users/user-form/user-form.component.ts

**Summary**
Middleware does not support updating `home_create` simultaneously with any other property.
Make a separate `user.update` request for `home_create`.

NAS-121675 / 23.10 / Adding User Auth key doesn't re-evaluate after home directory error - blanks Key on save, and doesn't close right panel

---

src/app/pages/system/view-enclosure/components/view-enclosure/view-enclosure.component.ts

To Test this requires an enterprise server with an expansion shelf.
Try adding or removing a disk. In either case the visualizations in both the main  content card and the enclosure selector card on the right should reflect the changed state

NAS-120108 / 22.12.3 / Extract enclosure visualizations on new disk info

---

src/app/pages/storage/modules/pool-manager/components/manual-disk-selection/components/manual-selection-disks/manual-selection-disks.component.html
src/app/pages/storage/modules/pool-manager/components/manual-disk-selection/components/manual-selection-disks/manual-selection-disks.component.ts
src/app/pages/storage/modules/pool-manager/components/manual-disk-selection/components/manual-selection-vdev/manual-selection-vdev.component.html
src/app/pages/storage/modules/pool-manager/components/manual-disk-selection/components/manual-selection-vdev/manual-selection-vdev.component.ts
src/app/pages/storage/modules/pool-manager/components/manual-disk-selection/interfaces/manual-disk-selection.interface.ts
src/app/pages/storage/modules/pool-manager/components/manual-disk-selection/manual-disk-selection.component.ts
src/app/pages/storage/modules/pool-manager/components/manual-disk-selection/store/manual-disk-drag-toggle.store.ts
src/app/pages/storage/modules/pool-manager/components/manual-disk-selection/store/manual-disk-selection.store.ts
src/app/pages/storage/modules/pool-manager/components/manual-disk-selection/utils/vdevs-to-manual-selection-vdevs.utils.ts
src/app/pages/storage/modules/pool-manager/pool-manager.module.ts

See ticket for details
ManualDiskSelectionDragToggleStore exists because if it is part of the old store, when updating the toggle boolean, as we update the state (because of the immutable patterns, we can't just update one boolean. The whole state has to be a new object), the vdevs gets cloned, which means they are considered updated and get re-rendered on the dom and the dragging can't work because the view we were trying to drag got destroyed in the process. So, drag toggle has to exist in a separate store.
Will add tests in a separate PR.

NAS-122002 / 23.10 / ManualDiskSelectionStore cleanup

---

src/app/pages/reports-dashboard/components/reports-global-controls/reports-global-controls.component.html
src/app/pages/reports-dashboard/components/reports-global-controls/reports-global-controls.component.ts
src/app/pages/reports-dashboard/reports-dashboard.component.ts
src/app/pages/reports-dashboard/reports.service.ts

The issue is missing menu items in the dropdown menu, such as UPS and Target, when reports are available.
For testing, find a system with UPS or mock it in the `reports.service.ts`.
```
this.ws.call('reporting.graphs').subscribe((reportingGraphs) => {
reportingGraphs.push({
name: 'ups',
title: 'UPS',
vertical_label: 'Requests',
identifiers: [
'demand_data',
'demand_metadata',
'prefetch_data',
'prefetch_metadata',
],
stacked: true,
stacked_show_total: true,
});
reportingGraphs.push({
name: 'ctl',
title: 'Target',
vertical_label: 'Requests',
identifiers: [
'demand_data',
'demand_metadata',
'prefetch_data',
'prefetch_metadata',
],
stacked: true,
stacked_show_total: true,
});
this.hasUps$.next(reportingGraphs.some((graph) => graph.name === ReportingGraphName.Ups)); …
```

NAS-122137 / 23.10 / Fix reporting dropdown menu
