truenas/webui

src/app/helptext/directoryservice/activedirectory.ts, src/app/pages/directoryservice/activedirectory/activedirectory.component.ts
Add checkbox for PAM restriction on AD form, move checkboxes into two cols
=> NAS-105365 / 12.0 / NAS-105365

src/app/pages/reportsdashboard/components/report/report.component.css, src/app/pages/reportsdashboard/components/report/report.component.html, src/app/pages/reportsdashboard/components/report/report.component.ts, src/app/pages/reportsdashboard/reportsdashboard.component.ts, src/app/pages/reportsdashboard/reportsdashboard.html, src/app/pages/reportsdashboard/reportsdashboard.scss
Extra Cosmetic fixes for Reports
=> NAS-104445 / 12.0 / NAS-104445-ff 

src/app/core/components/widgets/widgetpool/widgetpool.component.html, src/app/core/components/widgets/widgetpool/widgetpool.component.ts, src/app/pages/dashboard/dashboard.component.ts
Fix used percentage value for widget pool.
Percentage was being calculated but needed to be converted from decimal to integer for the UI
=> NAS-105513 / 12.0 / NAS-105513

src/app/core/components/widgets/widgetmemory/widgetmemory.component.html
Improved caption text for memory widget
=> NAS-105512 / 12.0 / NAS-105512

src/app/helptext/services/components/service-smb.ts, src/app/pages/services/components/service-smb/service-smb.component.ts
Restore filemask, dirmask to smb - 11.3
=> NAS-105403 / 11.3 / NAS-105403 

src/app/helptext/services/components/service-smb.ts, src/app/pages/services/components/service-smb/service-smb.component.ts
Restore dirmask, filemask fields to smb form, for v 12
=> NAS-105403 / 12.0 / NAS-105403

src/app/helptext/task-calendar/snapshot/snapshot-form.ts
Ported from https://github.com/freenas/freenas-docs/pull/1732/files
=> NAS-105366 / 12.0 / NAS-105366: Update help text for Allow Taking Empty Snapshots

src/app/helptext/task-calendar/snapshot/snapshot-form.ts
=> NAS-105366 / 11.3 / NAS-105366: Update help text for Allow Taking Empty Snapshots

src/app/pages/storage/volumes/manager/manager.component.html
=> NAS-105221 / 12.0 / Allow rendering of html for pool list vdev types

src/app/helptext/directoryservice/nis.ts, src/app/helptext/network/configuration/configuration.ts, src/app/helptext/services/components/service-afp.ts, src/app/helptext/services/components/service-dynamic-dns.ts, src/app/helptext/services/components/service-ftp.ts, src/app/helptext/services/components/service-rsync.ts, src/app/helptext/services/components/service-ssh.ts, src/app/helptext/services/components/service-tftp.ts, src/app/helptext/sharing/afp/afp.ts, src/app/helptext/sharing/iscsi/iscsi.ts, src/app/helptext/sharing/webdav/webdav.ts, src/app/helptext/system/advanced.ts, src/app/helptext/system/ca.ts, src/app/helptext/system/certificates.ts, src/app/helptext/system/email.ts, src/app/helptext/task-calendar/cloudsync/cloudsync-form.ts, src/app/helptext/task-calendar/cron/cron-form.ts, src/app/helptext/task-calendar/replication/replication-wizard.ts, src/app/helptext/task-calendar/resilver/resilver.ts, src/app/helptext/task-calendar/resync/resync-form.ts, src/app/helptext/task-calendar/scrub/scrub-form.ts, src/app/helptext/task-calendar/smart/smart.ts, src/app/helptext/task-calendar/snapshot/snapshot-form.ts, src/app/helptext/vm/vm-wizard/vm-wizard.ts, src/app/pages/system/alertservice/alert-service/alert-service.component.ts, src/app/pages/system/system.routing.ts
Reviewed list of inconsistencies and unified terminology and style across the UI.
Added some missing help text and updated others.
=> NAS-104078 / 12.0 / NAS-104078: Clean up UI text and make more consistent

src/app/helptext/storage/volumes/volume-list.ts
=> NAS-105531 / 12.0 / Rename FreeNAS to TrueNAS in Pool Upgrade message

src/app/pages/vm/devices/device-add2/device-add.component.ts, src/app/pages/vm/vm-wizard/vm-wizard.component.ts
Set 0.0.0.0 as default - for v 12
=> NAS-105579 / 12.0 / NAS-105579

src/app/pages/task-calendar/scrub/scrub-form/scrub-form.component.ts
Adapts pool list on Scrub Tasks form to receive ws call format rather than REST
=> NAS-105581 / 12.0 / NAS-105581

src/app/views/sessions/signin/signin.component.ts
Allows log in fields to appear on scale
=> NAS-105565 / 12.0 / NAS-105565 Add refs to SCALE to login logic

src/app/helptext/storage/volumes/volume-list.ts, src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
=> NAS-105531 / 11.3 / Show "TrueNAS" in the warning message for pool upgrade when on a TrueNAS system

src/app/pages/vm/devices/device-add2/device-add.component.ts, src/app/pages/vm/vm-wizard/vm-wizard.component.ts
Sorry about this extension that removes whitespace. Trying to disable it!
=> NAS-105579 / 11.3 / NAS-105579

src/app/helptext/services/components/service-smb.ts, src/app/helptext/sharing/smb/smb.ts
Expand/clarify/make consistent.
Yarn testing: no issues
=> NAS-104793 / 12.0 / NAS-104793: SMB help text cleanups.

src/app/helptext/system/advanced.ts, src/app/pages/system/advanced/advanced.component.ts
Add OP setting to sys advanced form, a bit of rearranging
=> NAS-102348 / 12.0 / NAS-102348

src/app/helptext/storage/disks/disks.ts, src/app/pages/storage/disks/disk-form/disk-form.component.ts, src/assets/styles/themes/ix-blue.scss
Add checkbox to force HDD standby
=> NAS-105589 / 12.0 / NAS-105589

src/app/helptext/network/configuration/configuration.ts
Minor synchronizations with the guide.
=> NAS-104715 / 12.0 / NAS-104715: Help text cleanup for Network / Global Configuration.

src/app/pages/system/general/general.component.ts, src/app/services/locale.service.ts
Updates the date and time example formats in sys general to match the selected timezone
V. 12 only - 11.3 doesn't have this feature
=> NAS-105597 / 12.0 / NAS-105597

src/app/pages/vm/vm-list/vm-list.component.ts
Listen for VM events to change the state of the row and its slider - avoided using getData() so rows would stay open on changes
=> NAS-105622 / 12.0 / Nas 105622

src/app/pages/common/entity/entity-tree-table/entity-tree-table.component.css, src/app/pages/common/entity/entity-tree-table/entity-tree-table.component.html
mat-menu menu group header CSS tweak
=> NAS-105459 / 12.0 / NAS-105459-CSS

src/app/pages/vm/devices/device-edit/device-edit.component.html, src/app/pages/vm/devices/device-list/device-list.component.ts
Add device-specific labels for VM device actions (edit, delete, change order and details)
=> NAS-100871 / 12.0 / NAS-100871

src/app/components/common/layouts/auth-layout/auth-layout.component.ts, src/app/services/theme/theme.service.ts, src/app/views/sessions/signin/signin.component.html, src/app/views/sessions/signin/signin.component.scss
Make the login page use the default theme.
=> NAS-105673 / 12.0 / NAS-105673

src/app/helptext/system/general.ts, src/app/pages/common/entity/entity-job/entity-job.component.ts, src/app/pages/system/general/general.component.ts
Adds required validator to config upload dialog form, updates process for displaying errors in wspost method of job and in the error dialog for save config
=> NAS-105674 / 12.0 / Nas 105674

src/app/pages/system/advanced/advanced.component.ts, src/app/services/storage.service.ts
Adjustments in storage service are to make sure that 1024 MiB becomes 1 GiB
Also adds some conditions where the value of 'humanReadable' is cleared to keep form from filling in unexpectedly
=> NAS-105667 / 12.0 / NAS-105667 Adjust human readables to avoid form errors

src/app/pages/system/support/support.component.ts
New FN systems and images added to support component
=> NAS-105734 / 12.0 / NAS-105734

src/app/pages/common/entity/utils.ts
=> NAS-105765 / 12.0 / Allow for job validation output to be displayed on forms

src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts, src/app/pages/storage/volumes/datasets/dataset-unlock/dataset-unlock.component.ts, src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
=> NAS-105759 / 12.0 / Add eye-toggle to passphrase fields

src/app/helptext/storage/volumes/volume-list.ts, src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
=> NAS-105760 / 12.0 / Add confirm checkbox to encryption options dialog

src/app/pages/storage/volumes/datasets/dataset-unlock/dataset-unlock.component.ts
=> NAS-105761 / 12.0 / Only show unlock with keyfile options if datasets have keys

src/app/components/common/dialog/about/about-dialog.component.html, src/app/components/common/topbar/topbar.component.ts, src/app/helptext/about.ts
Update interaction with pref service to fix bug in showing / hiding splash screen, customize about dialog for other TN products
=> NAS-105744 / 12.0 / NAS-105744 

src/app/helptext/storage/volumes/datasets/dataset-unlock.ts, src/app/pages/storage/volumes/datasets/dataset-unlock/dataset-unlock.component.ts, src/app/pages/storage/volumes/datasets/dataset-unlock/unlock-dialog/unlock-dialog.component.css, src/app/pages/storage/volumes/datasets/dataset-unlock/unlock-dialog/unlock-dialog.component.html, src/app/pages/storage/volumes/datasets/dataset-unlock/unlock-dialog/unlock-dialog.component.ts
=> NAS-105762 / 12.0 / Add final results dialog to show after datasets have been unlocked

src/app/core/services/api.service.ts, src/app/pages/dashboard/dashboard.component.ts, src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
Trust middleware for used_pct from root dataset
=> NAS-105513 / 11.3 / NAS-105513-stable

src/app/helptext/system/general.ts, src/app/pages/system/general/general.component.ts
Adds the 'required' validator for Upload Config dialog form
=> NAS-105674 / 11.3 / Nas 105674 stable

src/app/components/common/dialog/task-manager/task-manager.component.html, src/app/components/common/dialog/task-manager/task-manager.component.ts
view logs button only showing up if there is valid logs
=> NAS-105657 / 11.3 / NAS-105657

src/app/helptext/sharing/smb/smb.ts
(cherry picked from commit 7c7702f7068deced45a07cba6eb9192ffe1baf57)
=> DOCS-383 11.3 / improve host allow SMB field helptext.

src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
=> NAS-105859 / 12.0 / Disable encryption options for root datasets

src/app/helptext/storage/volumes/datasets/dataset-acl.ts
=> NAS-105846 / 11.3 / NAS-105846 remove WRITE from basic permissions

proxy.config.json.skel, src/app/pages/system/advanced/advanced.component.ts
=> NAS-105858 / 11.3 / Use .tar for ha debugs

src/app/helptext/services/components/service-afp.ts, src/app/pages/services/components/service-afp/service-afp.component.ts
The mw call is in the stable / master repositories but not yet in a build
New line in helptext is from api doc
=> NAS-105296 / 11.3 / Nas 105296

src/app/helptext/storage/volumes/volume-import-wizard.ts
Updating Pool import text regarding encryption
=> NAS-105755

src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
Fix lableing and logic issue on dataset form
=> NAS-105803 / 12.0 / NAS-105803

src/app/helptext/system/kmip.ts
Local build testing: no issues
=> NAS-105775 / 12.0 / NAS-105775 (12.0 BETA1): Add more KMIP field helptext.

src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
=> NAS-105867 / 12.0 / Do not show unlock action for datasets with a locked parent

src/app/components/common/topbar/topbar.component.ts, src/app/core/services/preferences.service.ts, src/app/pages/common/entity/entity-form/entity-form-embedded.component.html, src/app/pages/common/entity/entity-table/entity-table.component.ts, src/app/services/theme/theme.service.ts
Various fixes to how preferences handled through the UI
=> NAS-105737 / 12.0 / NAS-105737

src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
=> NAS-105797 / 12.0 / Hide passphrase options if dataset has key encrypted child

src/app/pages/common/entity/entity-tree-table/entity-tree-table.component.html, src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
=> NAS-105798 / 12.0 / Show anti-lock on root datasets that are not encrypted but have encrypted children

src/app/pages/dashboard/dashboard.component.ts
Don't look for available space in first child.
=> NAS-105799 / 12.0 / NAS-105799

src/app/pages/system/advanced/advanced.component.ts
=> NAS-105858 / 12.0 / Use .tar for ha debugs

src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.ts, src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts, src/app/pages/task-calendar/replication/replication-form/replication-form.component.ts, src/app/pages/task-calendar/snapshot/snapshot-form/snapshot-form.component.ts
git cherry-pick -x 6ae1ef59a2a183dc6a99a0e9b049c41a1a381986
git cherry-pick -x 20927e2455192518cd681131d369b9794afa3130
git cherry-pick -x a3fc4ef4322c8938d2f0181180d44ac2b24d697a
=> NAS-105678 / 12.0 / Nas 105678 (by lola27)

src/app/helptext/storage/volumes/datasets/dataset-acl.ts
=> NAS-105846 / 12.0 / NAS-105846 remove WRITE from basic permissions

src/app/core/components/widgets/widgetcpu/widgetcpu.component.html, src/app/core/components/widgets/widgetmemory/widgetmemory.component.html, src/app/core/components/widgets/widgetpool/widgetpool.component.css, src/app/core/components/widgets/widgetpool/widgetpool.component.html, src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.css, src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.html, src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.ts, src/app/pages/dashboard/dashboard.html, src/assets/styles/egret_overrides.css
Scale down dashboard widget widths from 600 to 540 px. 
Make adjustments to labels and mobile layout css.
=> NAS-105852 / 12.0 / NAS-105852

src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.html
Fix product image region conditionals for widgetsysinfo on HA systems
=> NAS-105855 / 12.0 / NAS-105855

src/app/helptext/system/email.ts, src/app/pages/system/email/email.component.ts
Validates for ASCII characters from 32 to 126 (which includes SPACE, which mw also allows)
=> NAS-105539 / 12.0 / NAS-105539 Match middleware validation for email pw

src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
=> NAS-105862 / 11.3 / Prevent double displaying pools after unlock with key

src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
=> NAS-105862 / 12.0 / Prevent double displaying pools after unlock with key (by erinix)

src/app/helptext/storage/volumes/manager/manager.ts
Rewrite help text to point to ZFS Encryption docs instead of GELI.
Local test: no issues
=> NAS-105904 / 12.0 / NAS-105904: Rework Pool Manager "Encryption" help text

src/app/helptext/storage/volumes/manager/manager.ts
- For 11.3, update GELI link and User Guide link to be more resilient for software version changes.
- Add spacing to file to make it easier to read.
- Slight rework to text.
- Local build test: both links work correctly.
=> NAS-105904 / 11.3 / (11.3-U3) NAS-105904: Rewrite Pool Manager "Encryption" checkbox help text

src/app/helptext/services/components/service-s3.ts
(cherry picked from commit bbc4938dfa45128ae0081cc8ea4e676a01390642)
=> NAS-100620 / 11.3-stable / Improve S3 helptext.

src/app/components/common/dialog/about/about-dialog.component.html, src/app/components/common/dialog/about/about-dialog.component.ts
=> NAS-105934 / 12.0 / Remove the view licenses dialog until we have proper middleware

src/app/pages/services/components/service-ftp/service-ftp.component.ts, src/app/services/storage.service.ts
=> Allow custom units for convertBytestoHumanReadable

src/app/helptext/sharing/smb/smb.ts, src/app/pages/sharing/smb/smb-form/smb-form.component.ts, src/app/pages/sharing/smb/smb-list/smb-list.component.ts
Uses pool.dataset.query from smb form and list to check if dataset can be located (ie, if pool is online) before navigating to ACL edit
=> NAS-105687 / 11.3 / Nas 105687

src/app/core/services/preferences.service.ts, src/app/helptext/account/group-list.ts, src/app/helptext/account/user-list.ts, src/app/pages/account/groups/group-list/group-list.component.ts, src/app/pages/account/users/user-list/user-list.component.ts, src/app/pages/common/entity/entity-table/entity-table.component.ts
Adds a one-time dialog to users/groups lists explaining that builtins are hidden; adds mat-tooltip to gear icon; fixes some old references to bsd_user, etc.; removes redundant user and group queries in user-list component. Didn't change 'builtins' to 'system', didn't use filtered query due to a delay in receiving user preferences.
=> NAS-105922 / 12.0 / Nas 105922

src/app/pages/account/users/user-form/user-form.component.ts
=> NAS-105952 / 12.0 / Only prevent builtin users usernames from getting changed

src/app/pages/account/users/user-form/user-form.component.ts
NAS-105952
(cherry picked from commit 1b4c62641293036284f032716efc32a7face6c43)
=> NAS-105952 / 11.3 / Only prevent builtin users usernames from getting changed

src/app/pages/common/entity/entity-table/entity-table.component.ts, src/app/pages/network/interfaces/interfaces-list/interfaces-list.component.ts
NAS-105959
(cherry picked from commit c69f62cc5b610be887ff2f0af668db6fd895ca42)
=> NAS-105959 / 11.3 / Have network interfaces prompt to commit changes after deleting an interface

src/app/pages/common/entity/entity-table/entity-table.component.ts, src/app/pages/network/interfaces/interfaces-list/interfaces-list.component.ts
=> NAS-105959 / 12.0 / Have network interfaces prompt to commit changes after deleting an interface

src/app/helptext/topbar.ts
(cherry picked from commit 05c7ff78b8fe366215825b466089c107d5dc77be)
=> NAS-105969 added helptext for ha_disabled_reasons

src/app/components/common/topbar/topbar.component.ts, src/app/pages/network/interfaces/interfaces-list/interfaces-list.component.ts
=> NAS-105963 / 11.3 / Have the application refresh if user does not commit network changes

src/app/components/common/layouts/admin-layout/admin-layout.component.css, src/app/pages/common/entity/entity-table/entity-table.component.ts, src/app/pages/preferences/page/forms/customtheme/customtheme.component.css, src/assets/styles/egret_overrides.css
Adjustments to keep main scroll bar from going under topbar / breadcrumb bar
=> NAS-105909 / 11.3 / NAS-105909-stable

src/app/components/common/layouts/admin-layout/admin-layout.component.css, src/app/pages/common/entity/entity-table/entity-table.component.ts, src/app/pages/preferences/page/forms/customtheme/customtheme.component.css, src/assets/styles/egret_overrides.css
Adjustments to keep main scroll bar from going under topbar / breadcrumb bar
=> NAS-105909 / 12.0 / Nas 105909

src/app/pages/system/viewenclosure/view-enclosure.component.css
Top is now 0 since position is absolute and not fixed
=> Enclosure UI CSS fix

src/app/helptext/network/interfaces/interfaces-list.ts
- Attempt to rework dialogs to establish a clear flow of testing interface changes before saving them.
=> NAS-105960 / 11.3 / NAS-105960: Rework Network Interface changes dialogs

src/app/components/common/layouts/admin-layout/admin-layout.component.ts, src/app/pages/dashboard/dashboard.component.ts
Modifies mobile screen detection to get around display trouble on Ffx
=> NAS-105901 / 11.3 / NAS-105901 Work around screen resize trouble on Ffx

src/app/components/common/layouts/admin-layout/admin-layout.component.ts, src/app/pages/dashboard/dashboard.component.ts
Modifies mobile screen detection to get around display trouble on Ffx
=> NAS-105901 / 12.0 / Nas 105901

src/app/helptext/network/interfaces/interfaces-list.ts
- Attempt to rework dialogs to establish a clear flow of testing interface changes before saving them.
See Jira ticket for rough screen grab showing the changes.
=> NAS-105960 / 12.0 / NAS-105960: Rework Network Interface changes dialogs (12.0)

src/app/components/common/topbar/topbar.template.html, src/app/helptext/topbar.ts, src/app/pages/common/entity/entity-dialog/entity-dialog.component.html, src/app/pages/common/entity/entity-form/components/form-upload/form-upload.component.html
Translation fixes for general form > entity dialogs and topbar matTooltips (plus form upload input)
=> NAS-105973 / 12.0 / Nas 105973

src/app/helptext/storage/volumes/manager/manager.ts, src/app/pages/storage/volumes/manager/manager.component.html, src/app/pages/storage/volumes/manager/manager.component.ts, src/app/pages/storage/volumes/manager/vdev/vdev.component.ts
=> NAS-106000 / 12.0 / Prevent adding special vdevs that are not of same type as data

src/app/helptext/directoryservice/ldap.ts
=> NAS-106012 / 12.0 / NAS-106012: update LDAP auxiliary parameters file and link

src/app/helptext/system/dataset.ts, src/app/pages/system/dataset/dataset.component.ts
=> NAS-106018 / 11.3 / Add warning message when changing value of syslog

src/app/helptext/system/dataset.ts, src/app/pages/system/dataset/dataset.component.ts
=> NAS-106018 / 12.0 / Add warning message when changing value of syslog

src/app/helptext/storage/volumes/datasets/dataset-acl.ts, src/app/pages/storage/volumes/datasets/dataset-acl/dataset-acl.component.ts
The problem described in the ticket seems to be the result of misconfigured permissions on the dataset @anodos325  has already validated against one known cause for this error in 11.3-U3+ so this ticket handles the error if it crops up  Thanks to @anodos325 for big help diagnosing this one.
=> NAS-105698 / 12.0 / NAS-105698

src/app/core/classes/system-profiler.ts
Don't always assume topology.data
=> NAS-106045 / 12.0 / NAS-106045

src/app/core/classes/system-profiler.ts
Don't always assume topology.data
=> NAS-106045 / 11.3 / NAS-106045 (by dszidi)

src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
Shows aclmode as an advanced field in CORE and ENTERPRISE, hides and disables it in scale
=> NAS-106060 / 12.0 / NAS-106060 Hide ACL Mode on form for SCALE

src/app/pages/sharing/iscsi/target/target-list/target-list.component.ts
=> NAS-106077 / 12.0 / NAS-106077

src/app/components/common/topbar/topbar.component.ts, src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.ts, src/app/core/services/core.service.ts, src/app/core/services/system-profile.service.ts
SystemProfileService is now responsible for dealing with HA status. WidgetSysInfo and Topbar components now relies on this service for HA status
=> NAS-105933 / 12.0 / NAS-105933

src/app/pages/sharing/iscsi/target/target-form/target-form.component.ts
authGroup query info for target form
=> NAS-106076 / 12.0 / NAS-106076

src/app/pages/sharing/iscsi/authorizedaccess/authorizedaccess-form/authorizedaccess-form.component.ts
Checks the non active field in a custom compare validator to make sure errors get turned off as needed
=> NAS-106079 / 12.0 / Nas 106079

src/app/pages/storage/volumes/datasets/dataset-quotas/dataset-quotas-grouplist/dataset-quotas-grouplist.component.ts, src/app/pages/storage/volumes/datasets/dataset-quotas/dataset-quotas-grouplist/group-quota-form/group-quota-form.component.ts, src/app/pages/storage/volumes/datasets/dataset-quotas/dataset-quotas-userlist/dataset-quotas-userlist.component.ts, src/app/pages/storage/volumes/datasets/dataset-quotas/dataset-quotas-userlist/user-quota-form/user-quota-form.component.ts, src/app/services/storage.service.ts
Clean up some display errors, add loaders for opening edit dialogs
=> NAS-106098 / 12.0 / NAS-106098

src/app/helptext/vm/devices/device-add-edit.ts, src/app/pages/vm/devices/device-add2/device-add.component.html, src/app/pages/vm/devices/device-add2/device-add.component.ts, src/app/pages/vm/devices/device-edit/device-edit.component.html, src/app/pages/vm/devices/device-edit/device-edit.component.ts
webui support for PCI-E passthru in vm plugin
DEPENDS: https://github.com/stattin42/freenas/tree/NAS-100045-12.0
ok to test
=> NAS-100045 / 12.0 / NAS-100045 PCI-E passthru support (webui part)

src/app/core/services/preferences.service.ts, src/app/pages/preferences/page/forms/general-preferences-form.component.ts, src/app/services/locale.service.ts
Preferences service should assume there could be both deprecated and new properties to handle.
=> NAS-106124 / 12.0 / NAS-106124

src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.ts
=> Build error fix

src/app/pages/reportsdashboard/components/report/report.component.html, src/app/pages/reportsdashboard/components/report/report.component.ts, src/app/pages/reportsdashboard/reportsdashboard.component.ts, src/app/pages/reportsdashboard/reportsdashboard.html
Filter out passive multipath disks from reporting > disk > devices list.
=> NAS-106090 / 12.0 / NAS-106090

src/app/core/services/system-profile.service.ts
=> NAS-106160 / 12.0 / Fix HA product detection

src/app/components/common/layouts/admin-layout/admin-layout.component.css, src/app/components/common/layouts/admin-layout/admin-layout.component.ts
Only on a Windows system, checks if per-page scrolling is enabled, makes an adjustment in the sidenav
=> NAS-105824 / 12.0 / Nas 105824

src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.ts
Dont check for updates if auto update check is set to false
=> NAS-106168 / 12.0 / NAS-106168

src/app/pages/storage/volumes/manager/manager.component.html, src/app/pages/storage/volumes/manager/manager.component.ts
Do not allow adding data vdevs if there is an empty one
Additionally grey out add vdev if there are no disks.
NAS-106117
=> NAS-106117 / 12.0 / Add some safety belts to pool manager vdev add:

src/app/pages/account/users/user-form/user-form.component.ts
11.3 version sometimes tried to validate before list was loaded; Haven't see the problem on 12, but this might make it more bulletproof.
=> NAS-106175 / 12.0 / Nas 106175 master

src/app/pages/storage/volumes/volumes-list/volumes-list.component.html, src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
=> NAS-106208 / 12.0 / Move the ': ' to html and have it dependant upon the size values being present

src/app/pages/storage/volumes/manager/manager.component.ts
=> NAS-106210 / 12.0 / Grey out add data when there aren't enough disks for the type required

src/app/app.component.ts, src/app/core/components/widgets/widgetpool/widgetpool.component.css, src/app/core/components/widgets/widgetpool/widgetpool.component.html, src/app/pages/common/entity/entity-toolbar/components/toolbar-multimenu/toolbar-multimenu.component.html, src/app/pages/common/entity/entity-toolbar/components/toolbar-multimenu/toolbar-multimenu.component.scss, src/app/pages/common/entity/entity-toolbar/models/control-config.interface.ts, src/app/pages/reportsdashboard/components/report/report.component.css, src/app/pages/reportsdashboard/components/report/report.component.html, src/app/pages/reportsdashboard/components/report/report.component.ts, src/app/pages/reportsdashboard/reportsdashboard.component.ts, src/assets/customicons/multipath.svg
=> NAS-106207 / 12.0 / NAS-106207

src/app/helptext/system/failover.ts
Resolves: https://jira.ixsystems.com/browse/NAS-104582
=> Ui text nas 10458

src/app/core/components/widgets/widgetpool/widgetpool.component.html
Only show lock icon if status is locked. Otherwise show alert icon
=> NAS-106253 / 12.0 / NAS-106253

src/app/pages/task-calendar/snapshot/snapshot-list/snapshot-list.component.ts
This requires middleware fix https://jira.ixsystems.com/browse/NAS-106289 to work. I updated my mw after the fix was merged and successfully tested this PR
=> NAS-106276 / 12.0 / NAS-106276 Select by checkbox for snapshot tasks

src/app/pages/storage/volumes/zvol/zvol-form/zvol-form.component.ts
=> NAS-106281 / 12.0 / Remove volsize from payload if value dosen't change

src/app/core/components/widgets/widgetpool/widgetpool.component.css, src/app/core/components/widgets/widgetpool/widgetpool.component.html, src/app/core/components/widgets/widgetpool/widgetpool.component.ts, src/app/pages/storage/volumes/volumes-list/volumes-list.component.html
Make pool.healthy and pool.status separate elements
=> NAS-106206 / 12.0 / NAS-106206

src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.ts
Dash widgetsysinfo M60 support
=> NAS-104606 / 12.0 / NAS-104606

src/app/pages/reportsdashboard/components/report/report.component.html, src/app/pages/reportsdashboard/components/report/report.component.ts
Make datetime format in reporting consistent.
=> NAS-106283 / 12.0 / NAS-106283

src/app/core/components/widgets/widgetpool/widgetpool.component.html, src/app/pages/reportsdashboard/components/report/report.component.html, src/app/pages/reportsdashboard/components/report/report.component.ts, src/app/pages/storage/volumes/volumes-list/volumes-list.component.html
Fix bug in report component template.
Fine tune pool health in dashboard and storage > pools based on team feedback
=> Post demo tweaks

src/app/pages/services/components/service-nfs/service-nfs.component.ts
=> NAS-106348 / 12.0 / NAS-106348

src/app/components/common/notifications/notifications.component.ts, src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.ts, src/app/pages/system/general/general.component.ts, src/app/services/locale.service.ts
Draws date and time format from pref service using proper method, stores them in local storage for immediate checking, updates as needed when pref service responds; updates notifications of format changes via observable so that no page refresh is needed; removes most timeouts that were waiting on data
=> NAS-106357 / 12.0 / Nas 106357

src/app/core/classes/ix-interfaces.ts, src/app/core/classes/system-profiler.ts, src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks-mini.component.html, src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks-mini.component.ts, src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.html, src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.ts, src/app/pages/system/viewenclosure/view-enclosure.component.css, src/app/pages/system/viewenclosure/view-enclosure.component.html, src/app/pages/system/viewenclosure/view-enclosure.component.ts
Enclosure UI graceful degradation
=> NAS-106364 / 12.0 / NAS-106364-master

src/app/pages/services/components/service-nfs/service-nfs.component.ts, src/app/pages/services/services.component.ts, src/app/pages/sharing/nfs/nfs-form/nfs-form.component.ts
NFS and WebDav are hidden in the SCALE nav menu, and this branch hides their settings in Services; to test this PR, edit line 87 in services component and comment out line 54 in navigation.component
=> NAS-106353 / 12.0 / NAS-106353 Remove nfs items on SCALE

src/app/pages/dashboard/dashboard.component.ts, src/app/pages/dashboard/dashboard.html, src/app/pages/dashboard/dashboard.module.ts, src/app/pages/dashboard/dashboard.scss
Add loader that displays percentage
=> NAS-106374 / 12.0 / NAS-106374

src/app/core/components/widgets/widgetpool/widgetpool.component.html
Don't assume multipath on MIRROR or RAIDZ
=> NAS-106378 / 12.0 / NAS-106378

src/app/helptext/urls.ts
=> NAS-106393 / 12.0 / Use new truenas docs url

src/app/components/common/layouts/admin-layout/admin-layout.template.html, src/app/pages/common/entity/entity-form/entity-form.component.html, src/app/pages/common/entity/entity-form/entity-form.component.ts, src/app/pages/common/entity/entity-table/entity-table.component.ts, src/app/pages/dashboard/dashboard.component.ts, src/app/pages/dashboard/dashboard.html, src/app/pages/storage/volumes/manager/manager.component.html, src/app/pages/storage/volumes/manager/manager.component.ts, src/app/pages/storage/volumes/volumes-list/volumes-list.component.html, src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts, src/app/pages/system/alert/alert.component.html, src/app/pages/system/alert/alert.component.ts, src/app/pages/system/support/eula/eula.component.html, src/app/pages/system/support/eula/eula.component.ts, src/app/pages/system/support/support.component.html, src/app/pages/system/support/support.component.ts, src/app/pages/system/update/update.component.html, src/app/pages/system/update/update.component.ts, src/assets/styles/egret_overrides.css, src/assets/styles/themes/ix-blue.scss
Makes sure content displays all the way to the bottom whether or not footer console is open, makes right-side scroll bar stop at bottom. Many files changed only because I removed the old way of adding a spacer
=> NAS-106365 / 12.0 / Nas 106365

src/app/pages/network/networksummary/networksummary.component.css, src/app/pages/network/networksummary/networksummary.component.html
Network Summary page CSS tweaks
=> NAS-106352 / 12.0 / NAS-106352

src/app/pages/system/certificates/certificate-list/certificate-list.component.ts
=> NAS-106400 / 12.0 / Show N/A when from and until are not available (on CSR)

src/app/core/components/widgets/widgetcpu/widgetcpu.component.html, src/app/core/components/widgets/widgetcpu/widgetcpu.component.ts, src/app/core/services/system-profile.service.ts
Handle case where temperature object is not available.
=> NAS-106406 / 12.0 / NAS-106406

src/app/pages/dashboard/dashboard.component.ts, src/app/pages/dashboard/dashboard.html, src/app/pages/dashboard/dashboard.module.ts, src/app/pages/dashboard/dashboard.scss
=> Revert "NAS-106374 / 12.0 / NAS-106374"

src/app/helptext/sharing/smb/smb.ts
(cherry picked from commit e6ec4ab1d1fb7b586f46e395a5e05e15f7462a16)
=> NAS-106317 clear up SMB recycle bin helpext

src/app/pages/common/entity/entity-form/entity-form.component.html, src/app/pages/common/entity/entity-form/entity-form.component.ts, src/app/pages/common/entity/entity-table/entity-table.component.ts, src/app/pages/dashboard/dashboard.component.ts, src/app/pages/dashboard/dashboard.html, src/app/pages/storage/volumes/manager/manager.component.html, src/app/pages/storage/volumes/manager/manager.component.ts, src/app/pages/storage/volumes/volumes-list/volumes-list.component.html, src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts, src/app/pages/system/alert/alert.component.html, src/app/pages/system/alert/alert.component.ts, src/app/pages/system/support/eula/eula.component.html, src/app/pages/system/support/eula/eula.component.ts, src/app/pages/system/support/support.component.html, src/app/pages/system/support/support.component.ts, src/app/pages/system/update/update.component.html, src/app/pages/system/update/update.component.ts, src/assets/styles/egret_overrides.css, src/assets/styles/themes/ix-blue.scss
Makes sure content displays all the way to the bottom whether or not footer console is open, makes right-side scroll bar stop at bottom. Many files changed only because I removed the old way of adding a spacer
=> NAS-106402 / 11.3 / NAS-106402 Console/scrollbar fix for stable

src/app/core/classes/ix-interfaces.ts, src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.ts, src/app/pages/system/viewenclosure/view-enclosure.component.css, src/app/pages/system/viewenclosure/view-enclosure.component.html, src/app/pages/system/viewenclosure/view-enclosure.component.ts
Enclosure UI graceful degradation
=> NAS-106364 / 11.3 / NAS-106364

src/app/core/components/widgets/widgetpool/widgetpool.component.html
Don't try to show used_pct if data not provided
=> NAS-106214 / 11.3 / NAS-106214

src/app/core/components/widgets/widgetpool/widgetpool.component.ts, src/app/pages/dashboard/dashboard.component.ts
Fix dashboard REST error with volumes encrypted with GELI
=> NAS-106196 / 11.3 / NAS-106196

src/app/core/services/preferences.service.ts, src/app/pages/plugins/available-plugins/available-plugins.component.css, src/app/pages/plugins/available-plugins/available-plugins.component.html, src/app/pages/plugins/available-plugins/available-plugins.component.ts
git cherry-pick -x 1dee129325dd71b64816f7461cf1840010dda1b0
git cherry-pick -x 48fb39cfc888e648f5f36ab7a015ad945d15b328
git cherry-pick -x 9c8b39a81cd75c6a8316d1ec8c7a6081f6210353
git cherry-pick -x f8492fd6f3c0c052ccdcc022893cb9253458bada
git cherry-pick -x 66b85503abdb95ac59a56a77b4f0beb4f5ae35d8
=> NAS-106156 / 11.3 / NAS-106156 (by lola27)

src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.ts
Dont check for updates if auto update check is set to false
=> NAS-106168 / 11.3 / NAS-106168-stable

src/app/pages/sharing/iscsi/authorizedaccess/authorizedaccess-form/authorizedaccess-form.component.ts
Checks the non active field in a custom compare validator to make sure errors get turned off as needed
=> NAS-106079 / 11.3 / NAS-106079 Update error status of non-active field

src/app/helptext/storage/volumes/datasets/dataset-acl.ts, src/app/pages/storage/volumes/datasets/dataset-acl/dataset-acl.component.ts
The problem described in the ticket seems to be the result of misconfigured permissions on the dataset @anodos325  has already validated against one known cause for this error in 11.3-U3+ so this ticket handles the error if it crops up  Thanks to @anodos325 for big help diagnosing this one.
=> NAS-105698 / 11.3 / NAS-105698 Handle err due to misconfigured permissions

src/app/components/common/topbar/topbar.template.html, src/app/helptext/topbar.ts, src/app/pages/common/entity/entity-dialog/entity-dialog.component.html, src/app/pages/common/entity/entity-form/components/form-upload/form-upload.component.html
Translation fixes for general form > entity dialogs and topbar matTooltips (plus form upload input)
=> NAS-105973 / 11.3 / Nas 105973 stable

src/app/pages/storage/volumes/zvol/zvol-form/zvol-form.component.ts
=> NAS-106281 / 11.3 / Remove volsize from payload if value dosen't change (by erinix)

src/app/core/components/widgets/widgetpool/widgetpool.component.html, src/app/core/components/widgets/widgetpool/widgetpool.component.ts, src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.ts, src/app/core/services/api.service.ts, src/app/pages/dashboard/dashboard.component.ts
=> NAS-106232 / 11.3 / NAS-106232

src/app/pages/common/entity/entity-form/entity-form-embedded.component.html
Add translate fieldSet.name in template
=> NAS-106439 / 12.0 / NAS-106439

src/app/components/common/topbar/topbar.component.ts, src/app/helptext/topbar.ts, src/app/pages/system/update/manualupdate/manualupdate.component.ts, src/app/pages/system/update/update.component.html, src/app/pages/system/update/update.component.ts, src/app/services/system-general.service.ts
On failover.upgrade success, sends 'finished' signal to topbar via Subject to disable warning dialog and icon. Also, drops line from HA warning message that system will restart
=> NAS-106401 / 11.3 / Nas 106401 stable

src/app/components/common/topbar/topbar.component.ts, src/app/helptext/topbar.ts, src/app/pages/system/update/manualupdate/manualupdate.component.ts, src/app/pages/system/update/update.component.html, src/app/pages/system/update/update.component.ts, src/app/services/system-general.service.ts
On failover.upgrade success, sends 'finished' signal to topbar via Subject to disable warning dialog and icon. Also, drops line from HA warning message that system will restart
=> NAS-106401 / 12.0 / NAS-106401 Change update warnings and timing for HA in master

src/app/helptext/storage/volumes/volume-list.ts, src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts, src/app/services/dialog.service.ts
Uses translate.get to translate string fragments in pool export dialog; also moves lots of text strings into helptext (PS - no changes to any helptext, so no disturbing translation)
=> NAS-106464 / 12.0 / NAS-106464 

src/app/pages/storage/volumes/volume-import-wizard/volume-import-wizard.component.ts
=> NAS-106457 / 12.0 / Remove disk decryption step from import wizard on SCALE

src/app/core/classes/system-profiler.ts, src/app/core/services/api.service.ts, src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks-mini.component.ts, src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.css, src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.html, src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.ts, src/app/pages/system/viewenclosure/view-enclosure.component.html, src/app/pages/system/viewenclosure/view-enclosure.component.ts
Let users update enclosure label value
=> NAS-106466 / 12.0 / NAS-106466

src/app/pages/sharing/iscsi/extent/extent-form/extent-form.component.ts
=> NAS-106341 / 12.0 / Set enabled box on by default, sort the zvol device list

src/app/pages/sharing/iscsi/extent/extent-form/extent-form.component.ts
git cherry-pick -x b27860f317b942705f3747d95356057e3a395780
NAS-106341
=> NAS-106341 / 11.3 / Set enabled box on by default, sort the zvol device list (by erinix)

src/app/core/services/api.service.ts, src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.css, src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.html, src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.ts, src/app/pages/system/viewenclosure/view-enclosure.component.html, src/app/pages/system/viewenclosure/view-enclosure.component.ts
Backport NAS-106466.
Allows users to change enclosure labels.
=> NAS-106466 / 11.3 / NAS-106466-Stable

src/app/pages/common/entity/entity-table/entity-table.component.html, src/app/pages/common/entity/entity-table/entity-table.component.ts
=> NAS-106469 / 11.3 / NAS-106469

src/app/app.routes.ts, src/app/components/common/navigation/navigation.component.ts, src/app/pages/clustering/clustering-comingsoon/clustering-comingsoon.component.ts, src/app/pages/clustering/clustering.module.ts, src/app/pages/clustering/clustering.routing.ts, src/app/pages/common/entity/entity-comingsoon/entity-comingsoon.component.css, src/app/pages/common/entity/entity-comingsoon/entity-comingsoon.component.html, src/app/pages/common/entity/entity-comingsoon/entity-comingsoon.component.ts, src/app/pages/common/entity/entity-comingsoon/index.ts, src/app/pages/common/entity/entity.module.ts, src/app/pages/containers/containers-comingsoon/containers-comingsoon.component.ts, src/app/pages/containers/containers.module.ts, src/app/pages/containers/containers.routing.ts, src/app/pages/vm/vm-comingsoon/vm-comingsoon.component.ts, src/app/pages/vm/vm.module.ts, src/app/pages/vm/vm.routing.ts, src/app/services/navigation/navigation.service.ts
=> NAS-106489 / 12.0 / Add dummy pages for clustering, vms, containers for SCALE

src/app/helptext/storage/volumes/volume-list.ts, src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
Many translate fixes in pool list actions
=> NAS-106510 / 12.0 / NAS-106510 

src/app/pages/storage/volumes/volume-status/volume-status.component.ts
git cherry-pick -x f5ba526c35ea201e393f4be5c6b13845db061cfb
=> NAS-106518 / 12.0 / NAS-106518 (by lola27)

src/app/components/common/dialog/downloadkey/downloadkey-dialog.component.html, src/app/pages/storage/volumes/manager/manager.component.html, src/app/pages/storage/volumes/manager/vdev/vdev.component.html
A few translation fixes for pool manager / vdev and encrypt dialog
=> NAS-106515 / 12.0 / NAS-106515 

src/app/pages/system/advanced/advanced.component.ts
=> NAS-106531 / 12.1 / Hide swapsize field on TrueNAS Enterprise

src/app/pages/system/tunable/tunable-form/tunable-form.component.ts
=> NAS-106479 / 12.0 / Get tunable choices from middleware, set default for SCALE

src/app/pages/system/advanced/advanced.component.ts
=> NAS-106531 / 11.3 / Hide swapondrive for TrueNAS

src/app/helptext/vm/vm-wizard/vm-wizard.ts, src/app/pages/common/entity/entity-form/components/form-select/form-select.component.html, src/app/pages/common/entity/entity-table/entity-table.component.html, src/app/pages/common/entity/entity-wizard/entity-wizard.component.html, src/app/pages/vm/devices/device-add2/device-add.component.ts, src/app/pages/vm/devices/device-edit/device-edit.component.ts, src/app/pages/vm/devices/device-list/device-list.component.ts, src/app/pages/vm/vm-wizard/vm-wizard.component.ts
Fixes translations on Vm table (and entity table), wizard, forms, dialogs
=> NAS-106572 / 12.1 / Nas 106572

src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
=> NAS-106282 / 12.1 / Do not try to set a dataset to inherit encryption when it is aleady inheriting.

src/app/pages/system/support/fn-support/fn-support.component.ts, src/app/pages/system/support/support.component.html, src/assets/styles/themes/ix-blue.scss
Was not able to recreate the problem (though I have seen it before) but I think this will fix it. Keeps the button inside its containing div, a better layout practice.
=> NAS-106509 / 12.1 / NAS-106509 Layout improvements for support page

src/app/pages/services/components/service-rsync/rsyncconfiguration/rsyncmodule/rsyncconfiguration-form.component.ts
=> NAS-106473 / 12.1 / Convert Rsync module user/group fields into comboboxen with ds cache query

src/app/pages/services/components/service-rsync/rsyncconfiguration/rsyncmodule/rsyncconfiguration-form.component.ts
=> NAS-106473 / 11.3 / Convert Rsync module user/group fields into comboboxen with ds cache query

src/assets/i18n/de.po
=> NAS-106273 / 11.3 / Port over translations from master into stable to fix broken german

src/app/helptext/urls.ts
- Update to final correct URL
- Needs to be merged for BETA1
=> Update Documentation URL

src/app/pages/common/entity/entity-form/components/form-ipwithnetmask/form-ipwithnetmask.component.ts
=> NAS-106625 / 12.1 / Do not return anything from component if IP is blank

src/app/pages/common/entity/entity-form/components/form-ipwithnetmask/form-ipwithnetmask.component.ts
=> NAS-106625 / 12.0 / Do not return anything from component if IP is blank (by erinix)

src/app/helptext/directoryservice/activedirectory.ts, src/app/pages/directoryservice/activedirectory/activedirectory.component.ts
=> Revert "NAS-106580 / 12.1 / NAS-106580 "

src/app/pages/common/entity/entity-comingsoon/entity-comingsoon.component.ts
=> Adjust URL for coming soon pages

src/app/helptext/storage/volumes/volume-list.ts, src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
Many translate fixes in pool list actions
=> NAS-106510 / 12.0 / NAS-106510  (by dkmullen)

src/app/pages/storage/volumes/volume-status/volume-status.component.ts
git cherry-pick -x f5ba526c35ea201e393f4be5c6b13845db061cfb
=> NAS-106518 / 12.0 / NAS-106518 (by lola27) (by bugclerk)

src/app/components/common/dialog/downloadkey/downloadkey-dialog.component.html, src/app/pages/storage/volumes/manager/manager.component.html, src/app/pages/storage/volumes/manager/vdev/vdev.component.html
A few translation fixes for pool manager / vdev and encrypt dialog
=> NAS-106515 / 12.0 / NAS-106515  (by dkmullen)

src/app/pages/system/advanced/advanced.component.ts
=> NAS-106531 / 12.0 / Hide swapsize field on TrueNAS Enterprise (by erinix)

src/app/helptext/vm/devices/device-add-edit.ts, src/app/helptext/vm/vm-wizard/vm-wizard.ts, src/app/pages/common/entity/entity-form/components/form-select/form-select.component.html, src/app/pages/common/entity/entity-table/entity-table.component.html, src/app/pages/common/entity/entity-wizard/entity-wizard.component.html, src/app/pages/vm/devices/device-add2/device-add.component.ts, src/app/pages/vm/devices/device-edit/device-edit.component.ts, src/app/pages/vm/devices/device-list/device-list.component.ts, src/app/pages/vm/vm-wizard/vm-wizard.component.ts
Fixes translations on Vm table (and entity table), wizard, forms, dialogs
=> NAS-106572 / 12.0 / Nas 106572 (by dkmullen)

src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
=> NAS-106282 / 12.0 / Do not try to set a dataset to inherit encryption when it is aleady inheriting. (by erinix)

src/app/pages/system/support/fn-support/fn-support.component.ts, src/app/pages/system/support/support.component.html, src/assets/styles/themes/ix-blue.scss
Was not able to recreate the problem (though I have seen it before) but I think this will fix it. Keeps the button inside its containing div, a better layout practice.
=> NAS-106509 / 12.0 / NAS-106509 Layout improvements for support page (by dkmullen)

src/app/pages/services/components/service-rsync/rsyncconfiguration/rsyncmodule/rsyncconfiguration-form.component.ts
=> NAS-106473 / 12.0 / Convert Rsync module user/group fields into comboboxen with ds cache query (by erinix)

src/app/helptext/storage/volumes/datasets/dataset-acl.ts, src/app/pages/common/entity/entity-form/components/form-list/form-list.component.html, src/app/pages/storage/storage.module.ts, src/app/pages/storage/storage.routing.ts, src/app/pages/storage/volumes/datasets/dataset-posix-acl/dataset-posix-acl.component.ts, src/app/pages/storage/volumes/datasets/dataset-posix-acl/index.ts, src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts, src/assets/styles/themes/ix-blue.scss
Adds Posix.1e acl manager to SCALE
=> NAS-106350 / 12.1 / Nas 106350a

src/app/core/components/widgets/widgetnic/widgetnic.component.html, src/app/core/components/widgets/widgetpool/widgetpool.component.html
Adds missing translation in WidgetNicComponent
=> NAS-106483 / 12.0 / NAS-106483 (by dszidi)

src/app/services/theme/theme.service.ts
Removed ix-official theme. 
Default theme is ix-dark. 
Theme ix-dark topbar color is now #111
=> NAS-106669 / 12.1 / NAS-106669

src/app/core/components/widgets/widgetpool/widgetpool.component.ts
Don't assume name is always defined
=> NAS-106624 / 11.3 / NAS-106624

src/app/pages/vm/vm-serial-shell/vmserial-shell.component.ts, src/app/services/shell.service.ts
VM console needs a small mw fix, merged today: https://github.com/freenas/freenas/pull/5111
=> NAS-106641 / 12.1 / NAS-106641 Update connection methods for VM and jail consoles

src/app/pages/vm/vm-serial-shell/vmserial-shell.component.ts, src/app/services/shell.service.ts
VM console needs a small mw fix, merged today: https://github.com/freenas/freenas/pull/5111
=> NAS-106641 / 12.0 / NAS-106641 Update connection methods for VM and jail consoles (by dkmullen)

src/app/pages/storage/volumes/datasets/dataset-unlock/dataset-unlock.component.ts
NAS-106667
(cherry picked from commit f0a312c175161b2f5226bd882cd79e32c67ed937)
=> NAS-106667 / 12.0 / Remove option to restart jails/vms on dataset unlock, this should just always happen

src/app/helptext/storage/volumes/volume-list.ts, src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
=> NAS-106666 / 12.1 / Convert dataset lock into a job

src/app/helptext/storage/volumes/volume-list.ts, src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
=> NAS-106666 / 12.0 / Convert dataset lock into a job (by erinix)

src/app/helptext/storage/volumes/datasets/dataset-quotas.ts, src/app/pages/common/entity/entity-table/entity-table.component.html, src/app/pages/common/entity/entity-table/entity-table.component.ts, src/app/pages/storage/volumes/datasets/dataset-quotas/dataset-quotas-grouplist/dataset-quotas-grouplist.component.ts, src/app/pages/storage/volumes/datasets/dataset-quotas/dataset-quotas-userlist/dataset-quotas-userlist.component.ts, src/assets/styles/themes/ix-blue.scss
=> NAS-106621 / 12.1 / Nas 106621

src/app/pages/plugins/plugins.component.ts
=> NAS-106637 / 12.1 / NAS-106637 

src/app/pages/plugins/plugins.component.ts
=> NAS-106637 / 12.0 / NAS-106637  (by lola27)

src/app/helptext/storage/volumes/datasets/dataset-quotas.ts, src/app/pages/common/entity/entity-table/entity-table.component.html, src/app/pages/common/entity/entity-table/entity-table.component.ts, src/app/pages/storage/volumes/datasets/dataset-quotas/dataset-quotas-grouplist/dataset-quotas-grouplist.component.ts, src/app/pages/storage/volumes/datasets/dataset-quotas/dataset-quotas-userlist/dataset-quotas-userlist.component.ts, src/assets/styles/themes/ix-blue.scss
=> NAS-106621 / 12.0 / Nas 106621 (by dkmullen)

src/app/views/sessions/signin/signin.component.ts
=> NAS-106665 / 12.1 / Add salt to buildtime url to prevent caching of buildtime file

src/app/views/sessions/signin/signin.component.ts
=> NAS-106665 / 12.0 / Add salt to buildtime url to prevent caching of buildtime file (by erinix)

src/app/views/sessions/signin/signin.component.ts
=> NAS-106665 / 12.1 / Skip buildtime check while in devmode

src/app/views/sessions/signin/signin.component.ts
=> NAS-106665 / 12.0 / Skip buildtime check while in devmode (by erinix)

src/app/pages/common/entity/entity-table/entity-table.component.ts
Uses string conductor to check for error tag (update to merged PR, fixes problem on VM devices lists)
=> NAS-106621 / 12.1 / NAS-106621 Specify string value for error condition

src/app/pages/common/entity/entity-table/entity-table.component.ts
Uses string conductor to check for error tag (update to merged PR, fixes problem on VM devices lists)
=> NAS-106621 / 12.0 / NAS-106621 Specify string value for error condition (by dkmullen)

src/app/core/components/widgets/widgetpool/widgetpool.component.html, src/app/core/components/widgets/widgetpool/widgetpool.component.ts, src/app/pages/dashboard/dashboard.component.ts
Handle missing volume data  
Show error icon with UNHEALTHY status message
=> NAS-106671 / 12.1 / NAS-106671-master

src/app/core/components/widgets/widgetpool/widgetpool.component.html, src/app/core/components/widgets/widgetpool/widgetpool.component.ts, src/app/pages/dashboard/dashboard.component.ts
Handle missing volume data  
Show error icon with UNHEALTHY status message
=> NAS-106671 / 12.0 / NAS-106671-master (by dszidi)

src/app/helptext/directoryservice/activedirectory.ts, src/app/pages/directoryservice/activedirectory/activedirectory.component.ts
=> Revert "Revert "NAS-106580 / 12.1 / NAS-106580 ""

src/app/core/classes/hardware/chassis-view.ts, src/app/core/classes/hardware/es60.ts, src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.ts
Fix hardware detection
Fix drivetray and chassis layout on ES60
=> NAS-106560 / 12.0 / NAS-106560 (by dszidi)

src/app/views/sessions/signin/signin.component.html, src/app/views/sessions/signin/signin.component.ts
=> NAS-106782 / 12.1 / Improve verbiage for HA disabled reasons

src/app/views/sessions/signin/signin.component.html, src/app/views/sessions/signin/signin.component.ts
=> NAS-106782 / 12.0 / Improve verbiage for HA disabled reasons (by erinix)

src/app/views/sessions/signin/signin.component.ts
=> NAS-106793 / 12.0 / Ensure intervals are cleared before logging in to prevent memory leak

src/app/views/sessions/signin/signin.component.ts
=> NAS-106793 / 12.1 / Ensure intervals are cleared before logging in to prevent memory leak (by erinix)

src/app/views/sessions/signin/signin.component.ts
=> NAS-106793 / 11.3 / Ensure intervals are cleared before logging in to prevent memory leak

src/app/pages/network/ipmi/ipmi.component.ts
PS Ip fields/values aren't submitted at all if dhcp is checked
=> NAS-106842 / 12.1 / NAS-106842 disable ip addresses when dhcp is selected

src/app/pages/vm/vm-wizard/vm-wizard.component.ts
On SCALE:
- Enables VNC Settings for either bootloader options but...
- Removes Delay VM Boot Until VNC Connects
- Doesn't offer Grub as an option
On Core, Enterprise
- hides VNC options for Grub and Legacy
On all:
- Exposes verbose bootloader descriptions to the user
=> NAS-106859 / 12.1 / Nas 106859

src/app/services/storage.service.ts
=> NAS-106837 / 12.1 / Fix file download issue by doing map the new rxjs way

src/app/pages/vm/vm-list/vm-list.component.ts
=> NAS-106859 / 12.1 / NAS-106859 Fix vnc buttons and port data on VM table

src/app/helptext/sharing/smb/smb.ts, src/app/pages/sharing/smb/smb-form/smb-form.component.ts, src/app/pages/sharing/smb/smb-list/smb-list.component.ts
Here's the middleware PR for both 12.1 and 12
https://github.com/freenas/freenas/pull/5161
=> NAS-106870 / 12.0 / NAS-106870 Backport for 12

src/app/views/sessions/signin/signin.component.ts
Correction to login component for non-enterprise SCALE
=> NAS-106894 / 12.1 / NAS-106894 Allow non enterprise SCALE to check status on login

src/app/components/common/breadcrumb/breadcrumb.component.html, src/app/components/common/layouts/admin-layout/admin-layout.component.css, src/app/components/common/layouts/admin-layout/admin-layout.component.ts, src/app/components/common/layouts/admin-layout/admin-layout.template.html, src/app/pages/common/entity/entity-table/entity-table.component.scss, src/app/pages/common/entity/entity-table/entity-table.component.ts, src/assets/styles/egret_overrides.css, src/assets/styles/fn-styles.css
Removes breadcrumb bar, moves copyright to bottom of side nav, makes adjustments for extra room
=> NAS-106873 / 12.1 / Nas 106873

src/app/helptext/storage/volumes/datasets/dataset-form.ts, src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts, src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
=> NAS-106836 / 12.1 / Add confirm passphrase field for dataset encryption

src/app/pages/system/advanced/advanced.component.ts
=> NAS-106919 / 12.1 / Use generic error handler for save debug errors

src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
=> NAS-106824 / 12.1 / Only allow exporting dataset keys if a pool has a key encrypted dataset

src/app/components/common/topbar/topbar.component.ts, src/app/helptext/topbar.ts
=> NAS-106841 / 12.1 / NAS-106841

src/app/pages/services/components/service-openvpn/service-openvpn-client/service-openvpn-client.component.ts, src/app/pages/services/components/service-openvpn/service-openvpn-server/service-openvpn-server.component.ts, src/assets/styles/themes/ix-blue.scss
inputs to txtarea, rearrange forms for OpenVPN forms
=> NAS-107007 / 12.1 / NAS-107007

src/app/core/services/preferences.service.ts, src/app/pages/vm/vm-wizard/vm-wizard.component.ts
Store zvol location in prefs, rework other VM stored values
=> NAS-102782 / 12.1 / NAS-102782

src/app/pages/system/general/general.component.ts
=> NAS-107016 / 12.1 / Sort the timezones alphabetically in System General

src/app/pages/common/entity/entity-form/components/form-combobox/form-combobox.component.html
=> NAS-107029 / 12.1 / Apply css class to make errors on comboboxes look better

src/app/pages/common/entity/entity-form/components/tooltip/tooltip.component.html, src/app/pages/common/entity/entity-form/components/tooltip/tooltip.component.ts
Shows one tooltip at a time, auto-closes the previous one when user opens a new one
=> NAS-106964 / 12.1 / Nas 106964

src/app/pages/system/advanced/advanced.component.ts
=> NAS-106919 / 11.3 / Use generic error handler for save debug errors (by erinix)

src/app/pages/common/entity/entity-form/components/form-combobox/form-combobox.component.html
=> NAS-107029 / 11.3 / Apply css class to make errors on comboboxes look better (by erinix)

src/app/pages/sharing/iscsi/associated-target/associated-target-list/associated-target-list.component.ts, src/app/pages/sharing/iscsi/authorizedaccess/authorizedaccess-list/authorizedaccess-list.component.ts, src/app/pages/sharing/iscsi/extent/extent-list/extent-list.component.ts, src/app/pages/sharing/iscsi/initiator/initiator-list/initiator-list.component.ts, src/app/pages/sharing/iscsi/portal/portal-list/portal-list.component.ts, src/app/pages/sharing/iscsi/target/target-list/target-list.component.ts
git cherry-pick -x bc1d7a89a1bde2296ffff11b96cdaffd70932c30
=> NAS-106787 / 11.3 / NAS-106787 (by lola27)

src/app/pages/storage/disks/disk-list/disk-list.component.ts
git cherry-pick -x add9ab78f1036a1d12f72e416dbb0491a2b515cb
git cherry-pick -x 980b866e10b0cd7bf9862f1f7087a685048b9904
=> NAS-106583 / 11.3 / Nas 106583 (by lola27)

src/app/pages/common/entity/entity-table/entity-table.component.ts, src/app/pages/network/interfaces/interfaces-list/interfaces-list.component.ts
=> NAS-107046 / 12.1 / Correct verbiage on physical network interface delete

src/app/pages/system/ca/ca-add/ca-add.component.ts, src/app/pages/system/certificates/certificate-add/certificate-add.component.ts
=> NAS-107079 / 12.1 / NAS-107079 

src/app/app.component.ts, src/app/views/sessions/signin/signin.component.ts
=> NAS-107093 / 12.1 / Fix relogin after refresh on cached section detection, use window reload

debian/rules
=> NAS-107093 / 12.1 / Add buildtime command to dpkg building rules

src/app/pages/system/ca/ca-add/ca-add.component.ts, src/app/pages/system/certificates/certificate-add/certificate-add.component.ts
=> NAS-107079 / 12.0 / NAS-107079  (by lola27)

src/app/app.component.ts, src/app/views/sessions/signin/signin.component.ts
=> NAS-107093 / 12.0 / Fix relogin after refresh on cached section detection, use window reload (by erinix)

src/app/core/services/system-profile.service.ts
Check system_serial_ha to detect HA feature
=> NAS-107118 / 12.1 / NAS-107118

src/app/pages/common/entity/entity-table/entity-table.component.ts
=> NAS-107098 / 12.1 / Listen to navigation events for cleanup to prevent memory leaks

src/app/core/services/system-profile.service.ts
Check system_serial_ha to detect HA feature
=> NAS-107118 / 12.0 / NAS-107118 (by dszidi)

src/app/core/services/system-profile.service.ts
=> NAS-107118 / 12.1 / Check for license before checking license has ha

src/app/core/services/system-profile.service.ts
=> NAS-107118 / 12.0 / Check for license before checking license has ha (by erinix)

src/app/pages/common/entity/entity-form/validators/ip-validation.ts, src/app/pages/sharing/iscsi/initiator/initiator-form/initiator-form.component.ts
=> NAS-107081 / 12.1 / NAS-107081 Validate for optional CIDR

src/app/helptext/task-calendar/snapshot/snapshot-form.ts
git cherry-pick -x bbed56d423202891e8783260188e880c53f5567c
git cherry-pick -x aafc00b7148effec74110ad367bd5766e0164a46
=> NAS-105099 / 11.3 / Improve naming schema tooltip (by themylogin)

src/app/pages/network/ipmi/ipmi.component.ts
PS Ip fields/values aren't submitted at all if dhcp is checked
=> NAS-106842 / 12.0 / NAS-106842 disable ip addresses when dhcp is selected (by dkmullen)

src/app/helptext/system/2FA.ts, src/app/pages/common/entity/entity-form/components/form-input/form-input.component.html, src/app/pages/common/entity/entity-form/models/field-config.interface.ts, src/app/pages/system/two-factor/qr-dialog.html, src/app/pages/system/two-factor/two-factor.component.ts, src/assets/styles/themes/ix-blue.scss
Adds conditional warning dialog and hint to 2FA component
=> NAS-106949 / 12.0 / Nas 106949 (by dkmullen)

src/app/helptext/storage/volumes/datasets/dataset-form.ts, src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts, src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
=> NAS-106836 / 12.0 / Add confirm passphrase field for dataset encryption (by erinix)

src/app/pages/system/advanced/advanced.component.ts
=> NAS-106919 / 12.0 / Use generic error handler for save debug errors (by erinix)

src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
=> NAS-106824 / 12.0 / Only allow exporting dataset keys if a pool has a key encrypted dataset (by erinix)

src/app/components/common/topbar/topbar.component.ts, src/app/helptext/topbar.ts
=> NAS-106841 / 12.0 / NAS-106841 (by lola27)

src/app/pages/system/general/general.component.ts
=> NAS-107016 / 12.0 / Sort the timezones alphabetically in System General (by erinix)

src/app/pages/common/entity/entity-form/components/form-combobox/form-combobox.component.html
=> NAS-107029 / 12.0 / Apply css class to make errors on comboboxes look better (by erinix)

src/assets/styles/styles.css
Here's the PR on the stable branch @erinix
=> Make shark icon smaller

src/app/pages/common/entity/entity-table/entity-table.component.ts, src/app/pages/network/interfaces/interfaces-list/interfaces-list.component.ts
=> NAS-107046 / 12.0 / Correct verbiage on physical network interface delete (by erinix)

src/app/pages/common/entity/entity-form/components/tooltip/tooltip.component.html, src/app/pages/common/entity/entity-form/components/tooltip/tooltip.component.ts
Shows one tooltip at a time, auto-closes the previous one when user opens a new one
=> NAS-106964 / 12.0 / Nas 106964 (by dkmullen)

src/app/pages/common/entity/entity-table/entity-table.component.ts
=> NAS-107098 / 12.0 / Listen to navigation events for cleanup to prevent memory leaks (by erinix)

src/app/pages/common/entity/entity-form/validators/ip-validation.ts, src/app/pages/sharing/iscsi/initiator/initiator-form/initiator-form.component.ts
=> NAS-107081 / 12.0 / NAS-107081 Validate for optional CIDR (by dkmullen)

src/app/pages/network/interfaces/interfaces-form/interfaces-form.component.ts
=> NAS-107120 / 12.0 / change failover_vhid to select type instead of input type (by yocalebo)

src/app/pages/system/ca/ca-add/ca-add.component.ts, src/app/pages/system/certificates/certificate-add/certificate-add.component.ts
=> NAS-107079 / 11.3 / NAS-107079 use ws call to get ec_curves options for ca and

src/app/helptext/storage/volumes/datasets/dataset-form.ts, src/app/pages/storage/volumes/datasets/dataset-acl/dataset-acl.component.ts, src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
git cherry-pick -x e8121a5558d2251e7480dfdde68f6256c9b68104
git cherry-pick -x 35dd8873de134569ab9ea9064ccb751df654b6bf
git cherry-pick -x cc4df00ac7962015cbec21c7b5f9c55ab7831fb4
git cherry-pick -x d9f173a0dbfc45868a6bfa605032a9dfe23e7cca
Original PR: https://github.com/freenas/webui/pull/4504
=> NAS-106814 / 12.0 / Nas 106814 (by dkmullen)

src/app/pages/services/components/service-openvpn/service-openvpn-client/service-openvpn-client.component.ts, src/app/pages/services/components/service-openvpn/service-openvpn-server/service-openvpn-server.component.ts, src/assets/styles/themes/ix-blue.scss
inputs to txtarea, rearrange forms for OpenVPN forms
=> NAS-107007 / 12.0 / NAS-107007 (by dkmullen)

src/app/helptext/sharing/smb/smb.ts, src/app/pages/sharing/smb/smb-form/smb-form.component.ts
git cherry-pick -x d421e3d29196cbf3ea2b86dc744fe18ff2edb1df
git cherry-pick -x 8fc329112ad705f8aef6efc368fce5d11120a492
Original PR: https://github.com/freenas/webui/pull/4509
=> NAS-107103 / 12.0 / NAS-107103 Add warning about acl mismatch (by dkmullen)

src/app/core/classes/theme-utils.ts, src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.ts
(cherry picked from commit 02f9c02e8f0aaba99ccabc70a215307c7caebe0b)
=> NAS-106738 / 12.1 / Remove console logs

src/app/helptext/services/components/service-openvpn.ts
Depends on mw change in https://github.com/freenas/freenas/pull/5337
=> NAS-107178 / 12.0 / NAS-107178 Update protocols

src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.html, src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.ts, src/app/services/locale.service.ts
Examples showing 24 hour time format
=> NAS-106995 / 12.0 / NAS-106995 Show user-preferred time format in uptime

src/app/helptext/sharing/smb/smb.ts
Rework slightly to clarify linking to the manual page.
=> NAS-107162: Update helptext about smb.conf

src/app/pages/storage/volumes/manager/vdev/vdev.component.ts
=> NAS-107159 / 12.0 / Fix issues with size estimate when repeating in extend mode

src/app/app.module.ts, src/app/components/common/dialog/resilver-progress/resilver-progress.component.css, src/app/components/common/dialog/resilver-progress/resilver-progress.component.html, src/app/components/common/dialog/resilver-progress/resilver-progress.component.ts, src/app/components/common/topbar/topbar.component.ts
=> NAS-107101 / 12.0 / Create better progress dialog for resilvering status

src/app/app.module.ts, src/app/components/common/dialog/resilver-progress/resilver-progress.component.css, src/app/components/common/dialog/resilver-progress/resilver-progress.component.html, src/app/components/common/dialog/resilver-progress/resilver-progress.component.ts, src/app/components/common/topbar/topbar.component.ts
NAS-107101
Original PR: https://github.com/freenas/webui/pull/4532
=> NAS-107101 / 12.1 / Create better progress dialog for resilvering status (by erinix)

src/app/pages/storage/volumes/manager/vdev/vdev.component.ts
NAS-107159
Original PR: https://github.com/freenas/webui/pull/4531
=> NAS-107159 / 12.1 / Fix issues with size estimate when repeating in extend mode (by erinix)

src/app/pages/storage/volumes/manager/vdev/vdev.component.ts
NAS-107159
Original PR: https://github.com/freenas/webui/pull/4531
=> NAS-107159 / 11.3 / Fix issues with size estimate when repeating in extend mode (by erinix)

src/app/core/services/coreservices.module.ts, src/app/core/services/data.service.ts, src/app/core/services/stats.service.ts, src/app/pages/dashboard/dashboard.component.ts
Improve real time stats behavior on dashboard
=> NAS-107073 / 12.0 / NAS-107073-stable

src/app/app.routes.ts, src/app/components/common/navigation/navigation.component.ts, src/app/pages/credentials/credentials.component.html, src/app/services/navigation/navigation.service.ts
Restores the virtualization menu for SCALE. I didn't see the navigation problem mentioned in this ticket.
=> NAS-107229 / 12.1 / Nas 107229

src/app/pages/storage/volumes/manager/manager.component.ts
=> NAS-107128 / 11.3 / Add setTimeout to add/remove Vdev to avoid race conditions

src/app/helptext/storage/volumes/datasets/dataset-acl.ts, src/app/pages/storage/volumes/datasets/dataset-acl/dataset-acl.component.ts, src/assets/styles/themes/ix-blue.scss
Changes the way ACL presets are presented
=> NAS-106981 / 12.1 / Nas 106981

src/app/core/services/coreservices.module.ts, src/app/core/services/data.service.ts, src/app/core/services/stats.service.ts, src/app/pages/dashboard/dashboard.component.ts
Improve real time stats behavior on dashboard
Original PR: https://github.com/freenas/webui/pull/4528
=> NAS-107073 / 12.1 / NAS-107073-stable (by dszidi)

src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.html, src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.ts, src/app/services/locale.service.ts
Examples showing 24 hour time format
Original PR: https://github.com/freenas/webui/pull/4513
=> NAS-106995 / 12.1 / NAS-106995 Show user-preferred time format in uptime (by dkmullen)

src/app/helptext/services/components/service-openvpn.ts
Neglected to put a 12.1 label on this one when I submitted it for 12.0 a few days ago
=> NAS-107178 / 12.1 / NAS-107178 for 12.1

src/app/helptext/storage/volumes/datasets/dataset-acl.ts, src/app/pages/common/entity/entity-form/components/form-list/form-list.component.html, src/app/pages/storage/volumes/datasets/dataset-acl/dataset-acl.component.ts, src/assets/styles/themes/ix-blue.scss
git cherry-pick -x 6b0a037b3969ccfd8d48014303c42d81005fe8ec
git cherry-pick -x 268bd74a7fd71c2888c3b951134ee103849d204f
git cherry-pick -x 103f4ce57f01729bbb220dfee506daedd5e8ab9a
Changes the way ACL presets are presented
Original PR: https://github.com/freenas/webui/pull/4542
=> NAS-106981 / 12.0 / Nas 106981 (by dkmullen)

src/app/core/components/widgets/widgetpool/widgetpool.component.html, src/app/core/components/widgets/widgetpool/widgetpool.component.ts
Dont assume logs spares and caches are always single disks
=> NAS-107053 / 12.1 / NAS-107053

src/app/components/common/layouts/admin-layout/admin-layout.component.css, src/app/components/common/navigation/navigation.component.ts, src/app/pages/common/entity/entity-dashboard/entity-dashboard.component.ts, src/app/pages/credentials/credentials.component.html, src/app/pages/storage/storage.routing.ts, src/app/pages/system/system.routing.ts
Makes Enclousres show up on temporary storage dashboard, moves routing for enclosures from system to storage
=> NAS-107297 / 12.1 / NAS-107297 Make Enclosures show up on storage temp dash on enterprise

src/app/core/components/widgets/widgetpool/widgetpool.component.html, src/app/core/components/widgets/widgetpool/widgetpool.component.ts
Dont assume logs spares and caches are always single disks
Original PR: https://github.com/freenas/webui/pull/4544
=> NAS-107053 / 12.0 / NAS-107053 (by dszidi)

src/app/core/components/widgets/widgetpool/widgetpool.component.html
All topologies go to data slide on pool widget
=> NAS-107053 / 12.1 / NAS-107053 fix

src/app/core/components/widgets/widgetpool/widgetpool.component.html, src/app/core/components/widgets/widgetpool/widgetpool.component.ts
=> NAS-107053 / 11.3 / NAS-107053 freenas

src/app/core/components/widgets/widgetpool/widgetpool.component.html
All topologies go to data slide on pool widget
Original PR: https://github.com/freenas/webui/pull/4556
=> NAS-107053 / 12.0 / NAS-107053 fix (by dszidi)

src/app/pages/services/components/service-ups/service-ups.component.ts
Checking value changes too soon seems to consistently cause the error in the ticket
=> NAS-107316 / 12.1 / NAS-107316 Delay first check of drivers

src/app/pages/reportsdashboard/reportsdashboard.component.ts
=> NAS-107276 / 12.0 / NAS-107276

src/app/pages/common/entity/entity-table/entity-table.component.ts, src/app/pages/system/certificates/certificate-list/certificate-list.component.ts
git cherry-pick -x 51132dab0c0e72628910605d683432fb94aed833
git cherry-pick -x 5304a3b5219734418bf829789f0f4ab393eaa909
Original PR: https://github.com/freenas/webui/pull/4577
=> NAS-107292 / 11.3 / Nas 107292 (by lola27)

src/app/helptext/sharing/smb/smb.ts, src/app/pages/sharing/smb/smb-form/smb-form.component.ts
Opens warning dialog when 'Apple style' is changed for the first time on an existing share
=> NAS-107368 / 20.10 / Nas 107368

src/app/helptext/sharing/smb/smb.ts, src/app/pages/sharing/smb/smb-form/smb-form.component.ts
Opens warning dialog when 'Apple style' is changed for the first time on an existing share
Original PR: https://github.com/freenas/webui/pull/4589
=> NAS-107368 / 12.0 / Nas 107368 (by dkmullen)

src/app/pages/sharing/smb/smb-form/smb-form.component.ts
Fixes issue where SMB form fails to open
=> NAS-107361 / 20.10 / NAS-107631 Add pipe

src/app/pages/sharing/smb/smb-form/smb-form.component.ts
Fixes issue where SMB form fails to open
Original PR: https://github.com/freenas/webui/pull/4586
=> NAS-107361 / 12.0 / NAS-107631 Add pipe (by dkmullen)

src/app/pages/common/entity/entity-toolbar/components/toolbar-menu/toolbar-menu.component.ts, src/app/pages/common/entity/entity-toolbar/components/toolbar-multimenu/toolbar-multimenu.component.ts, src/app/pages/common/entity/entity-toolbar/entity-toolbar.component.ts, src/app/pages/reportsdashboard/components/lineChart/lineChart.component.ts, src/app/pages/reportsdashboard/components/report/report.component.ts
NAS-107275
(cherry picked from commit 8c93f14d2a7c11cd628e886c334c45bc3c469bf0)
=> NAS-107275 / 20.10 / Fix import of Subject

src/app/helptext/storage/volumes/volume-list.ts, src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
Fix spacing and wording on pool export window for 11.3
Only processes:
Services and processes:
=> NAS-107177 / 11.3 / NAS-107177

src/app/helptext/global-helptext.ts, src/app/pages/system/general/general.component.ts, src/app/services/system-general.service.ts
=> NAS-107400 / 11.3 / Add generic methods/calls for root password field, add root password to save config

src/app/helptext/global-helptext.ts, src/app/pages/system/general/general.component.ts, src/app/services/system-general.service.ts
git cherry-pick -x 9ea5830af3dd854ab9fa96efd5e44a025558300c
NAS-107400
Original PR: https://github.com/freenas/webui/pull/4610
=> NAS-107400 / 20.10 / Add generic methods/calls for root password field, add root password to save config (by erinix)

src/app/helptext/global-helptext.ts, src/app/pages/system/general/general.component.ts, src/app/services/system-general.service.ts
=> Revert "NAS-107400 / 11.3 / Add generic methods/calls for root password field, add root password to save config"

src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.ts
=> NAS-107449 / 12.0 / NAS-107449 reset string

src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.ts
Original PR: https://github.com/freenas/webui/pull/4615
=> NAS-107449 / 20.10 / NAS-107449 reset string (by dkmullen)

src/app/core/components/widgets/widgetpool/widgetpool.component.html, src/app/core/components/widgets/widgetpool/widgetpool.component.ts
Pool widget properly handles removed disks
=> NAS-106704 / 11.3 / NAS-106704

src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks-mini.component.ts
Add TrueNAS minis  to enclosure management supported products list
=> NAS-107472

src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.ts
TRUENAS-MINI support for dashboard
=> NAS-107491 / 12.0 / NAS-107491-12.0

src/app/app.module.ts, src/app/helptext/global-helptext.ts, src/app/pages/common/password-dialog/password-dialog.component.css, src/app/pages/common/password-dialog/password-dialog.component.html, src/app/pages/common/password-dialog/password-dialog.component.ts, src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts, src/app/services/dialog.service.ts
=> NAS-107400 / 20.10 / Add generic password confirm dialog for exporting dataset keys

src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.ts
TRUENAS-MINI support for dashboard
Original PR: https://github.com/freenas/webui/pull/4628
=> NAS-107491 / 20.10 / NAS-107491-12.0 (by dszidi)

src/app/helptext/system/advanced.ts
=> NAS-107513 / 12.0 / Clarify overprovision size field name

src/app/helptext/system/advanced.ts
NAS-107513
Original PR: https://github.com/freenas/webui/pull/4630
=> NAS-107513 / 20.10 / Clarify overprovision size field name (by erinix)

src/app/app.component.ts, src/app/components/common/layouts/admin-layout/admin-layout.template.html, src/app/services/theme/theme.service.ts, src/assets/customicons/truenas_core_logomark_rgb.svg, src/assets/customicons/truenas_enterprise_logomark_rgb.svg, src/assets/customicons/truenas_scale_logomark_rgb.svg
Use color logomarks in topbar for default theme
=> NAS-107462 / 20.10 / NAS-107462

src/app/pages/vm/vm-list/vm-list.component.ts
NAS-107320
Original PR: https://github.com/freenas/webui/pull/4568
=> NAS-107320 / 11.3 / Properly pass in bind ip, pass in currently used hostname/ip if wildcard (by erinix)

src/app/helptext/storage/volumes/datasets/dataset-form.ts, src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
=> NAS-107528 / 20.10 / Only show dedup if license is present

src/app/pages/account/users/user-form/user-form.component.ts
Already fixed in 12.0 and 12.1
=> NAS-107558 / 11.3 / NAS-107558 remove get-true from smb query

src/app/helptext/storage/volumes/datasets/dataset-form.ts, src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
git cherry-pick -x c19d9b49b0a1b25af8e09fcf2105882b56dc476c
git cherry-pick -x 8904b58e89eaceb125e26d524b863b752ec833d4
NAS-107528
Original PR: https://github.com/freenas/webui/pull/4637
=> NAS-107528 / 11.3 / Only show dedup if license is present (by erinix)

src/app/pages/services/components/service-s3/service-s3.component.ts
=> NAS-107533 / 11.3 / Add ability to remove cert from s3

src/app/helptext/storage/volumes/datasets/dataset-form.ts, src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
NAS-107528
Original PR: https://github.com/freenas/webui/pull/4637
=> NAS-107528 / 12.0 / Only show dedup if license is present (by erinix)

src/app/core/components/widgets/widgetpool/widgetpool.component.html, src/app/pages/dashboard/dashboard.component.ts
Pool widget should handle scenarios where disk name is not provided
=> NAS-106704 / 12.0 / NAS-106704-rc1

src/app/views/sessions/signin/signin.component.html
git cherry-pick -x adbc259d4c20dee71c4aee5e98c1bf1ffd441c27
Original PR: https://github.com/freenas/webui/pull/4601
=> NAS-107401 / 12.0 / NAS-107401 disable autocomplete for one-time pw (by dkmullen)

src/assets/styles/material-reduction.css
=> NAS-107583 / 20.10 / Use relative paths for fonts

src/app/pages/common/password-dialog/password-dialog.component.ts
=> NAS-107400 / 20.10 / Remove circular dependency, console.log

src/app/app.module.ts, src/app/helptext/global-helptext.ts, src/app/pages/common/password-dialog/password-dialog.component.css, src/app/pages/common/password-dialog/password-dialog.component.html, src/app/pages/common/password-dialog/password-dialog.component.ts, src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts, src/app/pages/system/general/general.component.ts, src/app/services/dialog.service.ts, src/app/services/system-general.service.ts
git cherry-pick -x 1edeb6b1b1fce09d2435a5f361d23cfd2c2357fc
NAS-107400
Original PR: https://github.com/freenas/webui/pull/4655
=> NAS-107400 / 12.0 / Remove circular dependency, console.log (by erinix)

src/app/services/ws.service.ts
=> NAS-107621 / 20.10 / Remove auth.token call from ping

src/app/app.component.ts, src/app/components/common/layouts/admin-layout/admin-layout.component.ts, src/app/components/common/topbar/topbar.component.ts, src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.ts, src/app/pages/common/entity/entity-form/entity-form.component.ts, src/app/pages/reportsdashboard/components/report/report.component.ts, src/app/pages/reportsdashboard/reportsdashboard.component.ts, src/app/pages/services/services-table.component.ts, src/app/pages/sharing/iscsi/globalconfiguration/globalconfiguration.component.ts, src/app/pages/sharing/smb/smb-form/smb-form.component.ts, src/app/pages/storage/snapshots/snapshot-list/components/snapshot-details.component.ts, src/app/pages/storage/volumes/manager/manager.component.ts, src/app/pages/system/advanced/advanced.component.ts, src/app/pages/system/bootenv/bootenv-list/bootenv-list.component.ts, src/app/pages/system/general-settings/general-settings.component.ts, src/app/services/app-loader/app-loader.component.ts, src/app/services/language.service.ts, src/app/services/locale.service.ts, src/app/services/notifications.service.ts, src/app/services/system-general.service.ts, src/app/views/others/config-reset/config-reset.component.ts, src/app/views/others/failover/failover.component.ts, src/app/views/others/reboot/reboot.component.ts, src/app/views/others/shutdown/shutdown.component.ts, src/app/views/sessions/signin/signin.component.ts
Stops three api calls from getting called repeatedly, esp on signing in
Many small, repetitive changes to files to make api calls from System General Service.
Console logs in sys gen service are to make it easiler for reviewer to see if this works.
=> NAS-107624 / 20.10 / Nas 107624

src/app/services/ws.service.ts
NAS-107621
Original PR: https://github.com/freenas/webui/pull/4666
=> NAS-107621 / 12.0 / Remove auth.token call from ping (by erinix)

src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
=> NAS-107529 / 12.0 / Fix snapshot create for zvol, fix traceback on zvol menu click

src/app/pages/storage/volumes/manager/manager.component.css, src/app/pages/storage/volumes/manager/manager.component.html, src/app/pages/storage/volumes/manager/vdev/vdev.component.html, src/assets/styles/material-reduction.css
Fix form styles in pool manager
=> NAS-107217 / 20.10 / NAS-107217

src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
NAS-107529
Original PR: https://github.com/freenas/webui/pull/4668
=> NAS-107529 / 20.10 / Fix snapshot create for zvol, fix traceback on zvol menu click (by erinix)

src/app/core/services/stats.service.ts, src/app/pages/dashboard/dashboard.component.ts, src/app/services/system-general.service.ts
Kill reporting.realtime events when user leaves the dash
=> NAS-107623 / 20.10 / NAS-107623

src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.html, src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.ts, src/app/services/system-general.service.ts
Also removed a few console logs from an earlier ticket
=> NAS-107649 / 20.10 / Nas 107649

src/assets/styles/material-reduction.css
=> NAS-107670 / 20.10 / NAS-107670

src/app/app.routes.ts, src/app/pages/account/account.routing.ts, src/app/pages/credentials/credentials.component.css, src/app/pages/credentials/credentials.component.html, src/app/pages/system/system.routing.ts, src/app/services/navigation/navigation.service.ts
Should take care of ticket NAS-107669 too
=> NAS-107665 / 20.10 / Nas 107665

src/app/components/common/layouts/admin-layout/admin-layout.template.html
=> NAS-107436 / 20.10 / On second thought, lets not have breadcrumbs for scale

src/app/helptext/system/cloudcredentials.ts, src/app/pages/system/CloudCredentials/cloudcredentials-form/cloudcredentials-form.component.ts
git cherry-pick -x 97dd962588e936227ca940291e3e27ae5ca7393a
git cherry-pick -x ed4854e1b095717e26cc75c7e5652686126d486f
git cherry-pick -x 71e7364ee7328a25f9f6ff90cf3a2ee325f21ae6
Original PR: https://github.com/freenas/webui/pull/4680
=> NAS-107611 / 12.0 / NAS-107611 New field for S3 creds (by dkmullen)

src/app/helptext/system/cloudcredentials.ts, src/app/pages/system/CloudCredentials/cloudcredentials-form/cloudcredentials-form.component.ts
git cherry-pick -x 97dd962588e936227ca940291e3e27ae5ca7393a
git cherry-pick -x ed4854e1b095717e26cc75c7e5652686126d486f
git cherry-pick -x 71e7364ee7328a25f9f6ff90cf3a2ee325f21ae6
Original PR: https://github.com/freenas/webui/pull/4680
=> NAS-107611 / 20.10 / NAS-107611 New field for S3 creds (by dkmullen)

src/app/components/common/modal/modal.component.css, src/app/pages/common/entity/entity-form/components/form-ipwithnetmask/form-ipwithnetmask.component.html, src/app/views/sessions/signin/signin.component.html, src/assets/styles/material-reduction.css
Fix ipw/netmask fields
Fix input fields on login form
=> NAS-107657 / 20.10 / NAS-107657

src/app/core/components/copy-btn/copy-btn.component.css, src/app/core/components/copy-btn/copy-btn.component.html, src/app/core/components/copy-btn/copy-btn.component.ts, src/app/core/components/corecomponents.module.ts, src/app/core/components/directives/text-limiter/text-limiter.directive.ts, src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.html
Enable users to copy the exact version number on the dashboard in SCALE
=> NAS-106846 / 20.10 / NAS-106846

src/app/pages/network/forms/interfaces-form.component.ts
=> NAS-107678 / 20.10 / Hide vhid for SCALE

src/app/helptext/services/components/service-smb.ts
Update Service > SMB help text with correct behavior.
=> NAS-107645 / 20.10 / NAS-107645

src/app/helptext/services/components/service-smb.ts
Update Service > SMB help text with correct behavior.
Original PR: https://github.com/freenas/webui/pull/4700
=> NAS-107645 / 12.0 / NAS-107645 (by Mrt134)

src/app/pages/system/alert/alert.component.ts
NAS-107741
Original PR: https://github.com/freenas/webui/pull/4709
=> NAS-107741 / 12.0 / Handle alerts better in alert settings (by erinix)

src/app/pages/sharing/iscsi/iscsi.component.html, src/app/pages/sharing/iscsi/target/target-list/target-list.component.ts
license installed
Original PR: https://github.com/freenas/webui/pull/4711
=> NAS-107498 / 12.0 / NAS-107498 (by lola27)

src/app/pages/system/bootenv/bootenv-list/bootenv-list.component.ts
=> NAS-107797 / 20.10 / Fix error handling for boot env actions and traceback upon leaving pages

src/app/pages/system/bootenv/bootenv-list/bootenv-list.component.ts
git cherry-pick -x dc572e442039d59b78aaae1c0b43219d8f5e477d
NAS-107797
NAS-107798
Original PR: https://github.com/freenas/webui/pull/4722
=> NAS-107797 / 12.0 / Fix error handling for boot env actions and traceback upon leaving pages (by erinix)

src/app/pages/common/entity/entity-table/entity-table-actions.component.ts
11.3 has an interval to handle this issue
=> NAS-107794 / 12.0 / NAS-107794 Update actions on changes to row

src/app/pages/system/support/tn-support/tn-support.component.ts
I was wasn't able to reproduce the error by attaching both a debug and screenshots (this worked for me) but this addresses the error message in the ticket and the submission of a null 'cc' field as reflected in the ticket's debug
=> NAS-107899 / 12.0 / NAS-107899 Prevent null being sent for CC

src/app/pages/sharing/nfs/nfs-form/nfs-form.component.ts
=> NAS-107837 / 12.0 / Fix nfs security options to match middleware expected case

src/app/pages/sharing/nfs/nfs-form/nfs-form.component.ts
NAS-107837
Original PR: https://github.com/freenas/webui/pull/4753
=> NAS-107837 / 20.10 / Fix nfs security options to match middleware expected case (by erinix)

src/app/pages/reportsdashboard/components/lineChart/lineChart.component.ts, src/app/pages/reportsdashboard/components/report/report.component.html, src/app/pages/reportsdashboard/components/report/report.component.ts
Adjusts some time displays on reports for timezone; 12 and 12.1 need a separate PR
=> NAS-107552 / 11.3 / Nas 107552

src/app/pages/sharing/iscsi/initiator/initiator-list/initiator-list.component.ts, src/app/pages/sharing/iscsi/iscsi.component.html, src/app/pages/sharing/iscsi/iscsi.component.ts
git cherry-pick -x f5337f30cd2c7f222631dca4f813239f6b24ea0d
Original PR: https://github.com/freenas/webui/pull/4698
=> NAS-107661 / 11.3 / NAS-107661 (by lola27)

src/app/pages/jails/storages/storage-list/storage-list.component.ts
git cherry-pick -x ede99664473dcf7575277d73e3c82d680eae6a24
Original PR: https://github.com/freenas/webui/pull/4741
=> NAS-107638 / 11.3 / NAS-107638  (by lola27)

package.json, src/app/pages/common/entity/entity-tree-table/entity-tree-table.component.css, src/app/pages/common/entity/entity-tree-table/entity-tree-table.component.html, src/app/pages/common/entity/entity-tree-table/entity-tree-table.component.ts, src/app/pages/common/entity/entity-tree-table/entity-tree-table.model.ts, src/app/pages/common/entity/entity-tree-table/entity-tree-table.service.ts, src/app/pages/common/entity/entity-tree-table/old-template.html, src/app/pages/common/entity/entity.module.ts, src/app/pages/storage/volumes/volume-status/volume-status.component.html, src/app/pages/storage/volumes/volumes-list/volumes-list-controls.component.html, src/app/pages/storage/volumes/volumes-list/volumes-list-controls.component.ts, src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts, src/assets/styles/material-reduction.css
Implement mat-table for entity-tree-table
Other routing and css fixes as I saw them
=> NAS-107706 / None / Nas 107706 cdk tree

src/app/pages/common/entity/entity-table/entity-table.component.html, src/app/pages/services/services-table.component.html, src/app/services/theme/theme.service.ts, src/assets/styles/fn-styles.css, src/assets/styles/themes/ix-blue.scss
Better toggle switch and table row styles
=> NAS-107956 / None / NAS-107956

src/app/helptext/network/interfaces/interfaces-form.ts, src/app/pages/network/forms/interfaces-form.component.ts
=> NAS-107646 / 20.10 / Prevent and warn users from using ipv6 on HA

src/app/pages/system/alert/alert.component.ts
=> NAS-107741 / 20.10 / Handle alerts better in alert settings

src/app/pages/sharing/iscsi/iscsi.component.html, src/app/pages/sharing/iscsi/target/target-list/target-list.component.ts
=> NAS-107498 / 20.10 / NAS-107498

src/app/helptext/network/interfaces/interfaces-form.ts, src/app/pages/network/interfaces/interfaces-form/interfaces-form.component.ts
git cherry-pick -x 0221d2f2a9dea95d3ef45b8eb34a48382fb9c788
git cherry-pick -x 81f4aa16b6bf80cbccd2e17e0ab8914ea582308f
git cherry-pick -x f0322f565154a5214ae3855ad6924aafc8e42554
NAS-107646
Original PR: https://github.com/freenas/webui/pull/4696
=> NAS-107646 / 12.0 / Prevent and warn users from using ipv6 on HA (by erinix)

src/app/pages/storage/volumes/datasets/dataset-acl/dataset-acl.component.ts
Prevent user/group from being reset when switching acl presets
=> NAS-107895 / 12.0 / NAS-107895

src/app/core/classes/theme-utils.ts, src/app/pages/reportsdashboard/components/lineChart/lineChart.component.ts
LineChartComponent should not assume theme colors are always hex
=> NAS-108032 / 12.0 / NAS-108032

src/app/helptext/directoryservice/ldap.ts
=> NAS-108024 / 12.0 / NAS-108024 Add deprecation warning

src/app/helptext/services/components/service-snmp.ts, src/app/pages/services/components/service-snmp/service-snmp.component.ts
Add iftop option to SNMP service
=> NAS-108068 / 20.12 / Nas 108068

package.json
=> NAS-108129 / 20.12 / NAS-108129 Update material version

src/app/components/common/modal/modal.component.ts, src/app/core/components/widgets/widgetcontroller/widgetcontroller.component.ts, src/app/core/components/widgets/widgetmemory/widgetmemory.component.css, src/app/core/components/widgets/widgetmemory/widgetmemory.component.html, src/app/core/services/api.service.ts, src/app/pages/common/entity/entity-form/entity-form-configuration.component.ts, src/app/pages/common/entity/entity-toolbar/components/toolbar-button/toolbar-button.component.ts, src/app/pages/common/entity/entity-toolbar/entity-toolbar.component.html, src/app/pages/common/entity/entity-toolbar/entity-toolbar.component.ts, src/app/pages/common/entity/entity-toolbar/models/control-config.interface.ts, src/app/pages/common/entity/entity.module.ts, src/app/pages/dashboard/dashboard.component.ts, src/app/pages/dashboard/dashboard.html, src/app/pages/reportsdashboard/components/reports-global-controls/reports-global-controls.component.html, src/app/pages/reportsdashboard/reportsdashboard.component.ts, src/assets/styles/egret_overrides.css
Dashboard global configuration (Widget visibility)
=> NAS-105082 / 20.12 / NAS-105082

src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.ts
=> NAS-108107 / 12.0 / NAS-108107-a

package.json, src/app/helptext/system/general.ts, src/app/pages/common/entity/entity-toolbar/components/toolbar-menu/toolbar-menu.component.html, src/app/pages/common/entity/entity-toolbar/components/toolbar-menu/toolbar-menu.component.ts, src/app/pages/system/general-settings/general-settings.component.html, src/app/pages/system/general-settings/general-settings.component.ts
Must be merged after https://github.com/freenas/webui/pull/4795
Moves config actions in General Settings dashboard into the new title area (created in the above PR)
=> NAS-107751 / 20.12 / Nas 107751a

src/app/pages/network/network.component.css, src/app/pages/network/network.component.ts, src/app/pages/network/network.module.ts, src/app/pages/network/network.routing.ts
=> NAS-108155 / 20.12 / NAS-108155

src/app/helptext/storage/volumes/datasets/dataset-acl.ts, src/app/pages/storage/volumes/datasets/dataset-acl/dataset-acl.component.ts
=> NAS-107713 / 12.0 / Nas 107713

src/app/components/common/modal/modal.component.css, src/app/pages/common/entity/entity-form/components/form-list/form-list.component.css, src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.css, src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.html, src/app/pages/common/entity/entity-form/entity-form.component.html, src/app/pages/common/entity/entity-form/entity-form.component.scss, src/assets/styles/fn-styles.css, src/assets/styles/material-reduction.css, src/assets/styles/tn-styles.scss
=> NAS-107933 / 20.12 / NAS-107933

src/app/helptext/storage/volumes/datasets/dataset-acl.ts, src/app/pages/storage/volumes/datasets/dataset-acl/dataset-acl.component.ts
Original PR: https://github.com/freenas/webui/pull/4790
=> NAS-107713 / 20.12 / Nas 107713 (by dkmullen)

src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.html
Layout supports up to 6 SAS expanders
=> NAS-108193 / 12.0 / NAS-108193

src/app/pages/storage/VMware-snapshot/VMware-snapshot-list/VMware-snapshot-list.component.ts
Added wsDelete to Vmwaresnapshot.
=> NAS-108209 / 20.12 / add wsDelete to Vmwaresnapshot

src/app/pages/common/entity/entity-table/entity-table.component.ts, src/app/pages/storage/snapshots/snapshot-list/snapshot-list.component.ts, src/app/pages/storage/volumes/datasets/dataset-quotas/dataset-quotas-grouplist/dataset-quotas-grouplist.component.ts, src/app/pages/storage/volumes/datasets/dataset-quotas/dataset-quotas-userlist/dataset-quotas-userlist.component.ts
Prevent row resize and auto sort for entity table when handleData is called outside of page load
=> NAS-107889 / 12.0 / Nas 107889

src/app/core/components/widgets/widgetcpu/widgetcpu.component.html
=> NAS-108089 / 20.12 / Nas 108089(2)

src/app/helptext/directoryservice/idmap.ts, src/app/pages/directoryservice/idmap-form/idmap-form.component.ts, src/app/pages/directoryservice/idmap-list/idmap-list.component.ts
git cherry-pick -x 7a84c8cee6b72746a08e804eb1d337e771163e9f
git cherry-pick -x 7946149c11669eab6c0f09877196a00c91f7e342
git cherry-pick -x 17c7d091ae217f23d5861c01f06aa1549cc715cb
git cherry-pick -x 67ae7a681e32005e1ea8e1c792b7c99e3aefb57d
git cherry-pick -x f74cd8966111d65aba550610fba472048ec6c4e4
git cherry-pick -x 80224214a4bbf3863bdb1a922be2873ea637735d
git cherry-pick -x 08939ebf6a4a5057ed047f643c934a8667455474
git cherry-pick -x f258840f7ad8fa6f002369412af2a4a102435a6e
git cherry-pick -x db439397e63e41fce7a5420cb9405a319aefc563
Original PR: https://github.com/freenas/webui/pull/4748
=> NAS-107702 / 20.12 / Nas 107702 (by dkmullen)

src/app/helptext/storage/volumes/volume-list.ts, src/app/pages/storage/volumes/volumes-list/volumes-list.component.html, src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
Could use more from docs team on a specific warning of any dangers of detaching the sys dataset pool.
=> NAS-107948 / 20.12 / NAS-107948 Add sys dataset warnings

src/app/core/components/widgets/widgetpool/widgetpool.component.ts
=> NAS-108087 / 12.0 / remove zfs_guid/nas-108087

src/app/core/classes/theme-utils.ts, src/app/core/components/widgets/widgetcpu/widgetcpu.component.html, src/app/core/components/widgets/widgetcpu/widgetcpu.component.ts
fix NAS 108089
Original PR: https://github.com/freenas/webui/pull/4822
=> NAS-108089 / 20.12 / Nas 108089(2) (by AlexKarpov98)

src/app/helptext/services/components/service-snmp.ts
Description in mw ticket: https://jira.ixsystems.com/browse/NAS-107305
=> NAS-108068 / 20.12 / NAS-108068 Re-label itop feature

src/app/core/components/widgets/widgetpool/widgetpool.component.ts
remove zfs_guid / NAS-108087
Original PR: https://github.com/freenas/webui/pull/4829
=> NAS-108087 / 20.12 / remove zfs_guid/nas-108087 (by AlexKarpov98)

src/app/pages/common/entity/entity-form/components/dynamic-field/dynamic-field.css, src/app/pages/common/entity/entity-form/components/form-textarea/form-textarea.component.html, src/app/pages/common/entity/entity-form/components/form-textarea/form-textarea.component.ts, src/app/pages/common/entity/entity-form/models/field-config.interface.ts, src/app/pages/storage/volumes/datasets/dataset-unlock/dataset-unlock.component.ts, src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts, src/assets/styles/themes/ix-blue.scss
Adds ability to use a single-dataset key for unlocking
=> NAS-107419 / 12.0 / Nas 107419

src/app/helptext/services/components/service-snmp.ts
Description in mw ticket: https://jira.ixsystems.com/browse/NAS-107305
Original PR: https://github.com/freenas/webui/pull/4810
=> NAS-108068 / 12.0 / NAS-108068 Re-label itop feature (by dkmullen)

src/app/pages/network/interfaces/interfaces-form/interfaces-form.component.ts
Fix Lagg protocol select issue on edit mode in aggregation setting / NAS-108420
=> NAS-108240 / 20.12 / Nas 108240

src/app/pages/network/forms/interfaces-form.component.ts
Fix Lagg protocol select issue on edit mode in aggregation setting / NAS-108420
Original PR: https://github.com/freenas/webui/pull/4838
=> NAS-108240 / 20.12 / Nas 108240 (by AlexKarpov98)

src/app/pages/jails/jail-wizard/jail-wizard.component.ts
NAS-108138
Added vnet_default_interface field to Jails Add Wizard
=> NAS-108138 / 12.0 / Added vnet_default_interface field to 'Jails / Add / Wizard'

src/app/pages/network/forms/interfaces-form.component.ts
Remove subnet masks from failover and virtual addresses, change validation, fix
=> NAS-108064 / 20.12 / Nas 108064

src/app/helptext/services/components/service-nfs.ts, src/app/pages/services/components/service-nfs/service-nfs.component.ts
git cherry-pick -x 9beab088a1035adfcbd835c903de9ee7d32dd3da
git cherry-pick -x c2af548291fe7de9abd6dd030574d84ada87f391
git cherry-pick -x 5bbc8fdbc9e924a98ae4cf76b9fc3af69d664e30
git cherry-pick -x 56c27ce7577a2bac0bbd7be3854f8e08e102de22
git cherry-pick -x 7d39949b8bed24b8c9046fe07a7cb82eea5abdaf
git cherry-pick -x cd2668134bf3d7a948f61572a8d370f979aed08e
git cherry-pick -x c7bb7fdd964518bd1cd4dccb43b102c3a2a640f6
git cherry-pick -x 7f7f11296a889af7d964d8c4f588fd39b98f6842
Adds new api call to nfs service; testing requires being joined to AD
Original PR: https://github.com/freenas/webui/pull/4781
=> NAS-107507 / 12.0 / Nas 107507 (by dkmullen)

src/app/pages/services/components/service-ups/service-ups.component.ts
=> NAS-108279 / 12.0 / Monitor password is required

src/app/pages/services/components/service-ups/service-ups.component.ts
NAS-108279
Original PR: https://github.com/freenas/webui/pull/4844
=> NAS-108279 / 20.12 / Monitor password is required (by erinix)

package.json
(cherry picked from commit 6902054daec07ed04cbb5e145dac1b6d61f1f75b)
=> Fix the friendly build

src/app/helptext/storage/volumes/volume-status.ts, src/app/pages/storage/volumes/volume-status/volume-status.component.ts
=> NAS-108226 / 12.0 / Adjust error handling for replace and extend actions

src/app/helptext/system/email.ts, src/app/pages/system/email/email.component.ts
Adds gMail oauth as a way to authenticate from the email component. User can switch to smtp and back.
=> NAS-107864 / 12.0 / Nas 107864

src/app/helptext/storage/volumes/volume-status.ts, src/app/pages/storage/volumes/volume-status/volume-status.component.ts
NAS-108226
Original PR: https://github.com/freenas/webui/pull/4843
=> NAS-108226 / 20.12 / Adjust error handling for replace and extend actions (by erinix)

src/app/pages/reportsdashboard/components/report/report.component.ts, src/app/pages/reportsdashboard/reports.service.ts
=> NAS-107928 / 12.0 / NAS-107928

src/app/helptext/system/email.ts, src/app/pages/system/email/email.component.ts
Adds gMail oauth as a way to authenticate from the email component. User can switch to smtp and back.
Original PR: https://github.com/freenas/webui/pull/4788
=> NAS-107864 / 20.12 / Nas 107864 (by dkmullen)

src/app/helptext/vm/vm-wizard/vm-wizard.ts, src/app/pages/vm/vm-form/vm-form.component.ts, src/app/pages/vm/vm-list/vm-list.component.ts, src/app/pages/vm/vm-wizard/vm-wizard.component.ts
Scale only; helptext has previously specified a hard limit which isn't the case for SCALE
=> NAS-108173 / 20.12 / NAS-108173 Use api call to determin vcpu limit

src/app/core/components/widgets/widgetnic/widgetnic.component.ts
Fix network activity display issue / NAS-107832
=> NAS-107832 / 20.12 / Fix network activity display issue / NAS-107832

src/app/core/components/widgets/widgetnic/widgetnic.component.ts
Fix network activity display issue / NAS-107832
Original PR: https://github.com/freenas/webui/pull/4848
=> NAS-107832 / 12.0 / Fix network activity display issue / NAS-107832 (by AlexKarpov98)

src/app/pages/reportsdashboard/components/report/report.component.ts, src/app/pages/reportsdashboard/reports.service.ts
Fix trailing null values 
Original PR: https://github.com/freenas/webui/pull/4860
=> NAS-107928 / 20.12 / NAS-107928 (by dszidi)

src/app/pages/storage/disks/disk-list/disk-list.component.ts
Added 'Pool' column in disks list in 'Storage / Disks' / NAS-108272
=> NAS-108272 / Added 'Pool' column in disks list in 'Storage / Disks'

src/app/pages/storage/disks/disk-list/disk-list.component.ts
Added 'Pool' column in disks list in 'Storage / Disks' / NAS-108272
Original PR: https://github.com/freenas/webui/pull/4845
=> NAS-108272 / 20.12 / Disks' (by ryousaf)

src/app/helptext/network/interfaces/interfaces-form.ts
Initial rewrite is complete but I had to pivot to another task. Please review and give feedback for changes. Thanks!
Final commits need to be ported to 12.0 branch.
=> NAS-108065: Relabel Interface Aliases and rewrite help text

src/app/core/classes/system-profiler.ts, src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks-mini.component.html, src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.html
Add support for Metadata and Dedup vdevs for enclosure UI
=> NAS-108084 / 12.0 / NAS-108084

src/app/helptext/network/interfaces/interfaces-form.ts
cherry-pick commit from master and backport to 12.0 branch
=> NAS-108065 / 12.0 / NAS-108065: Relabel Interface Aliases and rewrite help text (12.0 backport)

src/app/core/components/widgets/widgetpool/widgetpool.component.ts
=> NAS-108085 / 12.0 / fix NAS-108085

src/app/core/components/widgets/widgetpool/widgetpool.component.ts
fix NAS-108085
Original PR: https://github.com/freenas/webui/pull/4825
=> NAS-108085 / 20.12 / fix NAS-108085 (by AlexKarpov98)

src/app/helptext/storage/volumes/volume-list.ts, src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
=> NAS-107694 / 12.0 / Add Pool options dialog with auto-trim option

src/app/helptext/storage/volumes/volume-list.ts, src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
=> NAS-107694 / 12.0 / Add helptext, remove console.log, fix pool name in dialog

src/app/helptext/storage/volumes/volume-list.ts, src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
NAS-107694
Original PR: https://github.com/freenas/webui/pull/4872
=> NAS-107694 / 20.12 / Add Pool options dialog with auto-trim option (by erinix)

src/app/helptext/system/cloudcredentials.ts, src/app/pages/system/CloudCredentials/cloudcredentials-form/cloudcredentials-form.component.ts
Depends on mw PR, merged today: https://github.com/freenas/freenas/pull/6033
=> NAS-108323 / 12.0 / Nas 108323

src/app/pages/common/entity/table/table.component.html, src/app/pages/common/entity/table/table.component.ts, src/app/pages/credentials/backup-credentials/backup-credentials.component.ts, src/app/pages/network/card-widget/card-widget.component.html, src/app/pages/network/card-widget/card-widget.component.ts, src/app/pages/network/network.component.ts, src/app/pages/network/network.module.ts
...adds ix-auto to the action buttons on the tables and cards currently in master that use the new templates
=> NAS-108326 / 20.12 / NAS-108326 Add ix-auto to action buttons

src/app/helptext/system/cloudcredentials.ts, src/app/pages/credentials/backup-credentials/forms/cloud-credentials-form.component.ts
git cherry-pick -x ad0ea11620f2b5c6f538624d6c6cb115399547d5
git cherry-pick -x ad3caa8241a3884206fc1697d7ea7e8e456f14be
git cherry-pick -x 2b90d8c9c4472c5fd000e369bdf59b798b45468f
Depends on mw PR, merged today: https://github.com/freenas/freenas/pull/6033
Original PR: https://github.com/freenas/webui/pull/4870
=> NAS-108323 / 20.12 / Nas 108323 (by dkmullen)

src/app/helptext/system/alert-service.ts, src/app/pages/system/alertservice/alert-service/alert-service.component.ts, src/app/pages/system/alertservice/alertservice-list/alertservice-list.component.ts
Telegram Alert Service referring to UI issue NAS-108271 (tested in local with my other pull request https://github.com/freenas/freenas/pull/5984).
=> NAS-108271 / 20.12 / Telegram Alert Service

src/app/pages/common/entity/entity-form/components/form-combobox/form-combobox.component.html, src/app/pages/common/entity/entity-form/components/form-combobox/form-combobox.component.ts, src/app/pages/common/entity/entity-form/models/field-config.interface.ts, src/app/pages/storage/volumes/datasets/dataset-acl/dataset-acl.component.ts, src/app/pages/storage/volumes/datasets/dataset-permissions/dataset-permissions.component.ts, src/app/pages/storage/volumes/datasets/dataset-posix-acl/dataset-posix-acl.component.ts, src/app/services/user.service.ts
add load more feature on storage permission page / NAS-107786
=> NAS-107786 / 20.12 / add load more feature on storage permission page / NAS-107786

src/app/pages/system/general-settings/support/license/license.component.ts
Offer option to refresh page after submitting license
=> NAS-108352 / 20.12 / Nas 108352

src/app/components/common/pagetitle/pagetitle.component.ts, src/app/core/components/widgets/widgetpool/widgetpool.component.html, src/app/pages/common/entity/entity-toolbar/entity-toolbar.component.ts, src/app/pages/common/entity/entity-tree-table/entity-tree-table.component.html, src/app/pages/storage/disks/disk-form/disk-form.component.ts, src/app/pages/storage/volumes/volume-status/volume-status.component.ts
Implement refresh button on Storage/Status page
=> NAS-108302 / 20.12 / NAS-108302

src/app/pages/system/update/update.component.html
Update release notes links to go to the general release notes section of the TrueNAS Documentation Hub.
=> NAS-108396 / 20.12 / NAS-108396

src/app/pages/system/update/update.component.html
Update release notes links to go to the general release notes section of the TrueNAS Documentation Hub.
Original PR: https://github.com/freenas/webui/pull/4898
=> NAS-108396 / 12.0 / NAS-108396 (by Mrt134)

src/app/pages/common/entity/entity-toolbar/components/toolbar-button/toolbar-button.component.ts, src/app/pages/common/entity/entity-toolbar/components/toolbar-menu/toolbar-menu.component.html, src/app/pages/common/entity/entity-toolbar/components/toolbar-menu/toolbar-menu.component.ts, src/app/pages/common/entity/entity-toolbar/components/toolbar-multimenu/toolbar-multimenu.component.html, src/app/pages/common/entity/entity-toolbar/components/toolbar-multimenu/toolbar-multimenu.component.ts, src/app/pages/common/entity/entity-toolbar/components/toolbar-multiselect/toolbar-multiselect.component.html, src/app/pages/common/entity/entity-toolbar/components/toolbar-multiselect/toolbar-multiselect.component.ts, src/app/pages/storage/volumes/volumes-list/volumes-list-controls.component.html
Tweak ix-auto directives on storage global actions. Remove unused markup from template.
=> NAS-108360 / 20.12 / NAS-108360

src/app/components/common/topbar/topbar.template.html
Hide notification badge when the length is zero / NAS-108380
=> NAS-108380 / 20.12 / Hide badge when the length is zero / NAS-108380

src/app/helptext/system/support.ts, src/app/pages/system/support/production-status/production-status.component.ts
=> NAS-108413 / 12.0 / Convert set production to a job

src/app/helptext/system/cloudcredentials.ts, src/app/pages/credentials/backup-credentials/forms/cloud-credentials-form.component.ts
Add validation for file upload on cloud credentials
Original PR: https://github.com/freenas/webui/pull/4888
=> NAS-108308 / 20.12 / Add validation for file upload on cloud credential (by AlexKarpov98)

src/app/pages/common/entity/entity-form/entity-form.component.ts, src/app/pages/common/entity/entity-form/models/fieldset.interface.ts, src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts, src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts, src/app/pages/storage/volumes/zvol/zvol-form/zvol-form.component.ts
Added slide in forms instead of new routes for create/edit datasets in pools
NAS-108348
=> NAS-108348 / 20.12 / Nas 108348

src/app/core/components/viewchartgauge/viewchartgauge.component.ts
WebUI makes firefox 80.0.1 hang
=> NAS-107697 / 12.0 / WebUI makes firefox 80.0.1 hang

src/app/core/components/viewchartgauge/viewchartgauge.component.ts
WebUI makes firefox 80.0.1 hang
Original PR: https://github.com/freenas/webui/pull/4911
=> NAS-107697 / 20.12 / WebUI makes firefox 80.0.1 hang (by AlexKarpov98)

src/app/pages/storage/volumes/manager/vdev/vdev.component.ts
…re set before capacity estimation is performed
NAS-108353
Original PR: https://github.com/freenas/webui/pull/4913
=> NAS-108353 / 20.12 / Moved estimateSize() method to the end of ngOnInit so proper values a… (by ryousaf)

src/app/helptext/system/support.ts, src/app/pages/system/general-settings/support/support.component.ts
Make truenas.set_production a job
=> NAS-108413 / 20.12 / Make truenas.set_production a job

src/app/core/components/widgets/widgetsysinfo/simple-failover-btn.component.ts, src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.html, src/app/pages/dashboard/dashboard.component.ts
Fix missing standby node on dashboard
Small UX consistency tweaks on WidgetSysInfo template
=> NAS-108388 / 20.12 / NAS-108388

src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.css, src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.html
Removed red border around cron picker.
Added a close button on top left of popup to keep things consistent
=> NAS-108499 / 20.12 / NAS-108499

src/app/components/common/topbar/topbar.component.ts, src/app/components/common/topbar/topbar.template.html, src/app/helptext/topbar.ts, src/app/pages/account/users/change-password/change-password.component.ts
=> NAS-108417 / 20.12 / Added Change Password as a dialog instead of a new page

src/app/core/components/directives/text-limiter/text-limiter.directive.ts
=> NAS-108504 / 20.12 / NAS-108504

src/app/pages/system/support/tn-support/tn-support.component.ts
=> NAS-108513 / 12.0 / Updated User Guide link

src/app/pages/system/general-settings/support/support-licensed/support-form-licensed.component.ts
NAS-108513
Original PR: https://github.com/freenas/webui/pull/4927
=> NAS-108513 / 20.12 / Updated User Guide link (by ryousaf)

src/app/pages/common/entity/entity-table/entity-table.component.html, src/app/pages/common/entity/entity-table/entity-table.component.ts
Value needs to be based on first key value and not row/pager index
=> Better ix-auto-identifier values

src/app/pages/common/entity/entity-table/entity-table.component.html, src/app/pages/common/entity/entity-table/entity-table.component.ts
=> NAS-108515 / 20.12 / NAS-108515

src/app/pages/sharing/iscsi/initiator/initiator-form/dynamic-list/dynamic-list.component.html, src/app/pages/sharing/iscsi/initiator/initiator-form/initiator-form.component.html
(cherry picked from commit 2a037c269cbf2cba7de8327ff1e947bf78466d2f)
=> NAS-108495 / 20.12 / Add ix-auto directives on initiator-form

src/app/components/common/topbar/topbar.component.ts
Handle case where there is no advancedConfig
=> NAS-108517 / 20.12 / NAS-108517

src/app/pages/system/update/update.component.ts
Workaround for when trains are not reported yet for enterprise.
=> NAS-108580 / 12.0 / NAS-108580

src/app/helptext/system/cloudcredentials.ts, src/app/pages/system/CloudCredentials/cloudcredentials-form/cloudcredentials-form.component.ts
Add validation for file upload on cloud credentials
=> NAS-108308 / 12.0 / Add validation for file upload on cloud credential

src/app/core/components/widgets/widgetpool/widgetpool.component.html, src/app/core/components/widgets/widgetpool/widgetpool.component.ts
Change icon color for unavail case on pool card / NAS-108361
=> NAS-108361 / 12.0 / Change icon color for unavail case on pool card / NAS-108361

src/app/pages/storage/volumes/volume-status/volume-status.component.ts
- add remove for a log mirror
- hide remove for a disk within a mirror
=> NAS-108298 / 12.0 / Nas 108298

src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
Fix wrong ordering of datasets by used/available space in the web ui
=> NAS-108312 / 12.0 / Fix wrong ordering of datasets by used/available space in the web ui

src/app/pages/sharing/iscsi/initiator/initiator-form/dynamic-list/dynamic-list.component.html, src/app/pages/sharing/iscsi/initiator/initiator-form/initiator-form.component.html
Add ix-auto directives to initiator-form
=> NAS-108495 / 12.0 / NAS-108495

src/app/pages/common/entity/entity-form/components/form-checkbox/form-checkbox.component.html, src/app/pages/common/entity/entity-form/components/form-chip/form-chip.component.html, src/app/pages/common/entity/entity-form/components/form-colorpicker/form-colorpicker.component.html, src/app/pages/common/entity/entity-form/components/form-combobox/form-combobox.component.html, src/app/pages/common/entity/entity-form/components/form-explorer/form-explorer.component.html, src/app/pages/common/entity/entity-form/components/form-input/form-input.component.html, src/app/pages/common/entity/entity-form/components/form-ipwithnetmask/form-ipwithnetmask.component.html, src/app/pages/common/entity/entity-form/components/form-paragraph/form-paragraph.component.html, src/app/pages/common/entity/entity-form/components/form-permissions/form-permissions.component.html, src/app/pages/common/entity/entity-form/components/form-radio/form-radio.component.html, src/app/pages/common/entity/entity-form/components/form-readfile/form-readfile.component.html, src/app/pages/common/entity/entity-form/components/form-select/form-select.component.html, src/app/pages/common/entity/entity-form/components/form-textarea-button/form-textarea-button.component.html, src/app/pages/common/entity/entity-form/components/form-textarea/form-textarea.component.html, src/app/pages/common/entity/entity-form/components/form-upload/form-upload.component.html, src/app/pages/common/entity/entity-form/models/field-config.interface.ts, src/app/pages/system/support/fn-support/fn-support.component.ts, src/app/pages/system/support/production-status/production-status.component.ts, src/app/pages/system/support/tn-support/tn-support.component.ts
Cherry picked commits from previous PR 4942 to resolve merge conflicts.
=> NAS-108530 / 12.0 / NAS-108530 

src/app/pages/storage/disks/smart-results/smart-results.component.ts
=> NAS-108489 / 12.0 / Nas-108489

src/assets/styles/themes/ix-blue.scss
fix CANCEL/CLOSE Buttons for iX Dark Theme need addressed
=> NAS-108449 / 12.0 / fix CANCEL/CLOSE Buttons for iX Dark Theme need addressed

src/app/pages/storage/volumes/volume-status/volume-status.component.ts
- add remove for a log mirror
- hide remove for a disk within a mirror
Original PR: https://github.com/freenas/webui/pull/4907
=> NAS-108298 / 21.02 / Nas 108298 (by AlexKarpov98)

src/app/helptext/system/ca.ts, src/app/helptext/system/certificates.ts, src/app/pages/credentials/certificates-dash/certificates-dash.component.ts, src/app/pages/credentials/certificates-dash/forms/ca-add.component.ts, src/app/pages/credentials/certificates-dash/forms/certificate-add.component.ts
Convert Certificate and CA forms to wizards
=> NAS-108324 / 21.02 / Convert Certificate and CA forms to wizards

src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
git cherry-pick -x 9d5515e3630257b3a9dd06d11f1a311715fe46cc
git cherry-pick -x dca818270344110b6acd0250a8968c0a26598211
Original PR: https://github.com/freenas/webui/pull/4923
=> NAS-108475 / 12.0 / Nas 108475 (by ryousaf)

src/app/helptext/network/interfaces/interfaces-form.ts
=> NAS-108639 / 12.0 / NAS-108639

src/app/pages/common/entity/entity-table/entity-table.component.html, src/assets/styles/material-reduction.css
=> NAS-108721 / 21.02 / Fixed pointer cursor for different conditions

src/app/helptext/system/general.ts, src/app/pages/system/general-settings/general-settings.component.ts
git cherry-pick -x d9ef2dc9df08cf6b385a3fb52ef48f3bf9edd60a
Original PR: https://github.com/freenas/webui/pull/4994
=> NAS-108640 / 21.02 / Update Save Config modal (by denysbutenko)

src/app/core/services/api.service.ts, src/app/pages/dashboard/dashboard.component.ts
Offload dashboard dataset filtering to backend
=> NAS-108681 / 21.02 / NAS-108681

src/app/core/services/api.service.ts, src/app/pages/dashboard/dashboard.component.ts
=> Revert "NAS-108681 / 21.02 / NAS-108681"

src/app/pages/reportsdashboard/reports-utils.worker.ts
=> NAS-108629 / Added case for nfsstatsbytes in optimizeLegend

src/app/pages/common/entity/entity-table/entity-table.component.html, src/app/pages/common/entity/entity-table/entity-table.component.ts, src/app/pages/common/entity/entity-tree-table/entity-tree-table.component.html, src/app/pages/common/entity/entity-tree-table/entity-tree-table.component.ts, src/assets/styles/material-reduction.css
Fix hover styles on mat-tables
=> NAS-108853 / 21.02 / NAS-108853

src/app/helptext/network/interfaces/interfaces-form.ts
NAS-108639
Original PR: https://github.com/freenas/webui/pull/4967
=> NAS-108639 / 21.02 / NAS-108639 (by ryousaf)

src/app/pages/reportsdashboard/reports-utils.worker.ts
NAS-108629
Original PR: https://github.com/freenas/webui/pull/5003
=> NAS-108629 / 21.02 / NAS-108629 / Added case for nfsstatsbytes in optimizeLegend (by ryousaf)

src/app/pages/reportsdashboard/components/lineChart/lineChart.component.ts, src/app/pages/reportsdashboard/reports-utils.worker.ts
git cherry-pick -x 2200ce8d9c2558651a06871c0f71fbb855ef72d8
git cherry-pick -x 72afb57e878513f22a3476e5614f33735f5b63c1
Original PR: https://github.com/freenas/webui/pull/5017
=> NAS-108786 / 21.02 / Improve consistency for bits (by denysbutenko)

src/app/helptext/system/email.ts, src/app/pages/common/entity/entity-form/components/form-paragraph/form-paragraph.component.html, src/app/pages/common/entity/entity-form/models/field-config.interface.ts, src/app/pages/system/email/email.component.ts
git cherry-pick -x 786be7875efbd6bd1c7494c1bcc8f06dc925c5c8
git cherry-pick -x 4e292d9994b2669627c37702adba4d6471c4f489
git cherry-pick -x aa65612efa067eadef02ceef07b0477edcf5c12d
Original PR: https://github.com/freenas/webui/pull/4978
=> NAS-108665 / 21.02 / Update email settings form (by denysbutenko)

src/app/pages/account/groups/group-list/group-list.component.ts
=> NAS-108835 / 21.02 / Fixed route on button click

src/app/pages/system/certificates/certificate-add/certificate-add.component.ts
=> NAS-108906 / 12.0 / Made private key required

src/app/pages/credentials/certificates-dash/forms/certificate-add.component.ts
git cherry-pick -x ba15e42e63b055228b869a8a1764051e4e1f9d46
NAS-108906
Original PR: https://github.com/freenas/webui/pull/5025
=> NAS-108906 / 21.02 / Made private key required (by ryousaf)

src/app/helptext/storage/volumes/zvol-form.ts, src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts, src/app/pages/storage/volumes/zvol/zvol-form/zvol-form.component.ts
git cherry-pick -x 2d58e810cae950bc0caa415bf984c2035f4f0a5f
git cherry-pick -x 4795994fc23ab4ebd3b2aaa63cb4fef294b00542
git cherry-pick -x 0f3918a3d81e914a5441e7ab4a908512752d3edb
Original PR: https://github.com/freenas/webui/pull/4973
=> NAS-108481 / 21.02 / zvol zfs encryption settings missing from UI (by AlexKarpov98)

src/app/pages/storage/disks/disk-form/disk-form.component.ts
=> NAS-108907 / 21.02 / Fixed customFilter for the disk.query call

src/app/pages/shell/shell.component.ts
This commit will fix both of NAS-108942 and NAS-108943
=> NAS-108942 / 21.02 / SCALE UI pages give 'reconnect' button after using the shell

src/app/pages/common/entity/entity-tree-table/entity-tree-table.component.css, src/app/pages/common/entity/entity-tree-table/entity-tree-table.component.html, src/app/pages/common/entity/entity-tree-table/entity-tree-table.component.ts, src/app/pages/storage/volumes/volumes-list/volumes-list.component.css, src/app/pages/storage/volumes/volumes-list/volumes-list.component.html, src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
=> NAS-108952 / 21.02 / Fixed Pools table default columns, EntityTreeTable sticky columns

README.md
container images
Do not merge yet, testing
=> Add initial information on how to test WebUI using the pre-built

Dockerfile, docker/nginx.conf, docker/start.sh
=> Backport to 12.0-stable the changes to allow building docker images for

src/app/helptext/services/components/service-smb.ts, src/app/pages/common/entity/entity-form/components/form-select/form-select.component.html, src/app/pages/common/entity/entity-form/components/form-select/form-select.component.scss, src/app/pages/common/entity/entity-form/components/form-select/form-select.component.ts, src/app/pages/common/entity/entity-form/models/field-config.interface.ts, src/app/pages/services/components/service-smb/service-smb.component.ts
=> NAS-108894 / 21.02 / Added option to add alert with disable alert capability

src/app/pages/system/general-settings/ntpservers/ntpserver-form/ntpserver-form.component.ts, src/assets/styles/tn-styles.scss
=> NAS-109040 / 21.02 / Fixed width for min and max poll fields

src/app/pages/system/email/email.component.ts
=> NAS-109071 / 12.0 / Fixed mail.send middleware arguments for sending test emails

src/app/pages/system/email/email.component.ts
git cherry-pick -x 91d5b28c2505d01a025f6e84a107c7ec76cc7e8a
NAS-109071
Original PR: https://github.com/freenas/webui/pull/5068
=> NAS-109071 / 21.02 / Fixed mail.send middleware arguments for sending test emails (by ryousaf)

src/app/pages/common/entity/entity-form/components/form-combobox/form-combobox.component.html, src/app/pages/common/entity/entity-form/components/form-input/form-input.component.ts
=> NAS-109093 / 21.02 / Added readonly condition for reset input button

src/app/components/common/pagetitle/pagetitle.component.html, src/app/pages/common/entity/entity-table/entity-table-add-actions.component.html, src/assets/styles/material-reduction.css
=> NAS-108949 / 21.02 / Pushed right hand bulk actions & search field on new line when running out of space for better spacing

src/app/pages/common/entity/entity-tree-table/entity-tree-table.component.html, src/app/pages/common/entity/entity-tree-table/entity-tree-table.component.ts, src/app/pages/storage/volumes/volume-status/volume-status.component.ts
=> NAS-109076 / 21.02 / Repopulating entity-tree-table when config is changed by the containing component

src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.ts, src/app/core/services/system-profile.service.ts
git cherry-pick -x edf46c631e2cc7b0cac7a3993a9a6ab851e7369d
Original PR: https://github.com/freenas/webui/pull/5079
=> NAS-109050 / 12.0 / system.info buildtime is not an array anymore (by themylogin)

src/app/helptext/sharing/smb/smb.ts, src/app/pages/sharing/smb/smb-form/smb-form.component.ts
NAS-108918
Original PR: https://github.com/freenas/webui/pull/5081
=> NAS-108918 / 21.02 / Removed incorrect tooltip from smb-form component (by ryousaf)

src/app/views/sessions/signin/signin.component.html
=> NAS-109160 / 12.0 / Fix password not set form

src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
=> NAS-109135 / 12.0 / Fix export key for encrypted datasets

src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
NAS-109135
Original PR: https://github.com/freenas/webui/pull/5103
=> NAS-109135 / 21.02 / Fix export key for encrypted datasets (by erinix)

src/app/components/common/notifications/notifications.component.html, src/app/components/common/notifications/notifications.component.ts, src/app/pages/credentials/credentials.component.html
=> NAS-109256 / 21.02 / Moved Email link from Misc to Alert panel's settings dropdown

src/app/pages/storage/volumes/volumes-list/volumes-list-controls.component.html
=> NAS-109238 / 21.02 / Fixed font size for mat-icon on filter field in Storage

src/app/components/common/breadcrumb/breadcrumb.component.ts, src/app/components/common/dialog/about/about-dialog.component.ts, src/app/components/common/layouts/admin-layout/admin-layout.component.ts, src/app/components/common/pagetitle/pagetitle.component.ts, src/app/services/locale.service.ts, src/app/views/others/config-reset/config-reset.component.ts, src/app/views/others/failover/failover.component.ts, src/app/views/others/reboot/reboot.component.ts, src/app/views/others/shutdown/shutdown.component.ts, src/app/views/sessions/signin/signin.component.ts
=> NAS-109218 / 21.02 / Fixed copyright_year using buildtime throughout

src/app/views/sessions/signin/signin.component.html
git cherry-pick -x e6c2e9078388f39d03af3ee8d38a326add149f4b
git cherry-pick -x f67025f4479439e8922aa58a7e230b1fce672b84
Original PR: https://github.com/freenas/webui/pull/5097
=> NAS-109215 / 21.02 / Fix hide logic (by dszidi)

src/app/pages/credentials/certificates-dash/forms/certificate-add.component.ts
=> NAS-109262 / 21.02 / Made call to certificate.create a job in CertificateAddComponent

src/app/helptext/apps/apps.ts, src/app/pages/applications/catalog/catalog.component.ts, src/app/pages/applications/forms/chart-form.component.ts, src/app/pages/applications/forms/chart-release-add.component.ts, src/app/pages/applications/forms/chart-release-edit.component.ts, src/app/pages/common/entity/utils.ts
=> Revert "NAS-109029 / 21.04 / Allow user to configure GPU in Launch Docker image wizard in UI / NAS-109029"

src/app/pages/common/entity/entity-job/entity-job.component.ts, src/app/pages/storage/import-disk/import-disk.component.ts
=> NAS-108990 / 12.0 / Handled job response case when state is ABORTED for disk import

src/app/pages/system/support/support.component.ts
Should be merged in sync with https://github.com/freenas/freenas/pull/6364
=> NAS-109078 / 12.0 / Properly display additionally licensed hardware

src/app/pages/common/entity/table/table.service.ts
=> NAS-109268 / 21.02 / Closed loader for all delete call cases in TableService

src/app/pages/common/entity/entity-empty/entity-empty.component.html
=> NAS-109240 / 21.04 / Added spinner for loading case for empty-entity

src/app/pages/common/entity/entity-form/components/form-checkbox/form-checkbox.component.html, src/app/pages/common/entity/entity-form/components/form-checkbox/form-checkbox.component.ts
=> NAS-109232 / 21.04 / Prevent default click behavior on form-checkbox when readonly is true

src/app/pages/common/entity/entity-dialog/entity-dialog.component.css, src/app/pages/common/entity/entity-form/components/form-paragraph/form-paragraph.component.html
=> NAS-109263 / 21.04 / Set overflow-wrap property for title, message in entity-dialog. Fixed width of form-paragraph.

src/app/pages/credentials/certificates-dash/forms/certificate-add.component.ts
=> NAS-109270 / 21.04 / Setting values for optional extensions

src/app/pages/common/entity/entity-table/entity-table-actions.component.html, src/app/pages/common/entity/entity-table/entity-table-actions.component.scss, src/app/pages/common/entity/entity-table/entity-table-actions.component.ts, src/app/pages/storage/volumes/volumes-list/volumes-list.component.css, src/app/pages/storage/volumes/volumes-list/volumes-list.component.html, src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
git cherry-pick -x 0bc364f7ef363d1251167cb829ca60340eedfbf5
git cherry-pick -x cd01ae43f33410260e0fde9d8e3232a8efbaf983
git cherry-pick -x 108cbd2197db1c1786d17dcf20ec0f57de75985a
git cherry-pick -x a8d335bd8be334dd2a1689304c21dee780eef6c4
git cherry-pick -x 4f793c2aa61865a76b9b06c91cf19e918652ea9f
git cherry-pick -x 8bfaca4bf05a6853cef438367f0de0306cb1714a
Fix pool actions when status is OFFLINE
Original PR: https://github.com/freenas/webui/pull/5071
=> NAS-108586 / 12.0 / Fix pool actions when status is OFFLINE (by dszidi)

src/app/pages/vm/devices/device-edit/device-edit.component.ts
=> NAS-109077 / 21.04 / Selected only needed properties for quicker response time

src/app/components/common/breadcrumb/breadcrumb.component.ts, src/app/components/common/dialog/about/about-dialog.component.ts, src/app/services/locale.service.ts, src/app/views/others/config-reset/config-reset.component.ts, src/app/views/others/failover/failover.component.ts, src/app/views/others/reboot/reboot.component.ts, src/app/views/others/shutdown/shutdown.component.ts, src/app/views/sessions/signin/signin.component.ts
=> NAS-109049 / 12.0 / Fixed copyright year throughout using buildtime value from localStorage

src/app/app.component.ts, src/app/core/classes/custom-icons.ts
git cherry-pick -x 2398d94b3c6c256f3e5c6cf8ae82932f9774c963
Original PR: https://github.com/freenas/webui/pull/5067
=> NAS-109043 / 12.0 / Clean up svg imports in app component (by denysbutenko)

src/app/helptext/sharing/smb/smb.ts, src/app/pages/sharing/smb/smb-form/smb-form.component.ts
=> NAS-108918 / 12.0 / Removed incorrect tooltip from smb-form component

src/app/pages/jails/jail-form/jail-form.component.ts
=> NAS-108874 / 12.0 / Added exec_fib input to network config for jail form

src/app/components/common/navigation/navigation.template.html
=> NAS-109027 / 12.0 / Removed anchor link's tab selection for navigation panel to avoid mat-nav-list issues

src/app/pages/system/general-settings/support/support.component.ts
git cherry-pick -x 998a70ba9956a15554005913c24309b366989be4
Should be merged in sync with https://github.com/freenas/freenas/pull/6364
Original PR: https://github.com/truenas/webui/pull/5121
=> NAS-109078 / 21.04 / Properly display additionally licensed hardware (by themylogin)

src/app/helptext/system/support.ts, src/assets/styles/tn-styles.scss
=> NAS-109473 / 21.04 / Highlight JIRA link

src/app/pages/common/entity/table/table.component.html, src/app/pages/common/entity/table/table.component.ts, src/app/pages/common/entity/table/table.service.ts
=> NAS-109479 / 21.04 / Added EntityEmpty to Credentials/Certificates

src/app/pages/task-calendar/cloudsync/cloudsync-form/cloudsync-form.component.ts
=> NAS-109364 / 21.04 / Fixed bucket property hide/show toggle on provider selection

src/assets/i18n/envoyer
=> Update and rename fr.po to envoyer

src/app/helptext/apps/apps.ts, src/app/pages/applications/catalog/catalog.component.ts, src/app/pages/applications/forms/chart-form.component.ts, src/app/pages/applications/forms/chart-release-add.component.ts, src/app/pages/applications/forms/chart-release-edit.component.ts, src/app/pages/common/entity/utils.ts
=> NAS-109029 / 21.04 / Allow user to configure GPU in Launch Docker image wizard in UI

src/app/services/system-general.service.ts
=> NAS-109495 / 21.04 / Fixed race condition where system.config.info request was being sent before auth confirmation

src/app/pages/common/entity/entity-job/entity-job.component.ts, src/app/pages/storage/import-disk/import-disk.component.ts
NAS-108990
Original PR: https://github.com/truenas/webui/pull/5140
=> NAS-108990 / 21.04 / Handled job response case when state is ABORTED for disk import (by ryousaf)

src/app/pages/credentials/certificates-dash/forms/acmedns-form.component.ts
=> NAS-109443 / 21.04 / Dynamically created fields based on schemas returned from middleware for ACME DNS Authenticators

src/app/pages/storage/volumes/zvol/zvol-form/zvol-form.component.ts
=> NAS-108924 / 12.0 / Handled INHERITTED case for compression for zvol

src/app/pages/credentials/certificates-dash/forms/certificate-add.component.ts
=> NAS-109652 / 21.04 / Changed san value back to strings

src/app/pages/storage/volumes/zvol/zvol-form/zvol-form.component.ts
NAS-108924
Original PR: https://github.com/truenas/webui/pull/5159
=> NAS-108924 / 21.04 / Handled INHERITTED case for compression for zvol (by ryousaf)

src/app/pages/common/entity/entity-tree-table/entity-tree-table.component.html, src/app/pages/common/entity/entity-tree-table/entity-tree-table.component.ts
=> NAS-109183 / 12.0 / Added custom sorting for EntityTreeTable

src/app/helptext/task-calendar/replication/replication-wizard.ts, src/app/helptext/task-calendar/replication/replication.ts, src/app/pages/common/entity/entity-form/entity-form.component.html, src/app/pages/task-calendar/replication/replication-form/replication-form.component.ts, src/app/pages/task-calendar/replication/replication-wizard/replication-wizard.component.ts, src/assets/styles/material-reduction.css
=> NAS-109051 - Added warnings for encrypted datasets when creating a replication task through form or wizard

src/app/pages/reportsdashboard/reports-utils.worker.ts
=> NAS-108630 / 12.0 / Fixed legend keys for battery statistics reports

src/app/pages/common/entity/entity-form/components/form-input/form-input.component.html
=> NAS-109714 / 21.04 / Only show tooltip and required asterisk when a placeholder is present

src/app/pages/directoryservice/idmap-list/idmap-list.component.ts
=> NAS-109052 / 12.0 / Fixed case where idmap has a custom name

src/app/pages/system/advanced/advanced.component.ts
=> NAS-109582 / 12.0 / Added case for HttpErrorResponse error handling

src/app/components/common/navigation/navigation.component.ts
=> NAS-109603 / 21.04 / Toggle Failover link visibility based on failover.licensed response

src/app/pages/common/entity/entity-table/entity-table.component.ts, src/app/pages/storage/snapshots/snapshot-list/snapshot-list.component.ts, src/assets/styles/material-reduction.css
Also better formatting for multiple keyprops in entity-table delete message
=> NAS-109739 / 12.0 / Add snapshot name to keyprops. 

src/app/pages/system/advanced/advanced-settings.component.ts
git cherry-pick -x 9ee87fcc8ce3af8840050d2a0af34cbe5070da21
NAS-109582
Original PR: https://github.com/truenas/webui/pull/5223
=> NAS-109582 / 21.04 / Added case for HttpErrorResponse error handling (by ryousaf)

src/app/pages/common/entity/entity-table/entity-table.component.ts, src/app/pages/storage/snapshots/snapshot-list/snapshot-list.component.ts, src/assets/styles/material-reduction.css
git cherry-pick -x 7dfad3e6725251ace2c206311ff389102f73a2fe
Also better formatting for multiple keyprops in entity-table delete message
Original PR: https://github.com/truenas/webui/pull/5230
=> NAS-109739 / 21.04 / Add snapshot name to keyprops.  (by dszidi)

src/app/pages/reportsdashboard/reports-utils.worker.ts
NAS-108630
Original PR: https://github.com/truenas/webui/pull/5212
=> NAS-108630 / 21.04 / Fixed legend keys for battery statistics reports (by ryousaf)

src/app/pages/directoryservice/idmap-list/idmap-list.component.ts
NAS-109052
Original PR: https://github.com/truenas/webui/pull/5221
=> NAS-109052 / 21.04 / Fixed case where idmap has a custom name (by ryousaf)

src/app/pages/credentials/certificates-dash/forms/certificate-acme-add.component.ts
=> NAS-109665 / 21.04 / Fetching ACME servers from middleware

src/app/pages/storage/snapshots/snapshot-list/snapshot-list.component.ts
Unset nopercent progressNumberType
=> NAS-109548 / 12.0 / Fix snapshot multidelete progressbar percent format

src/app/pages/storage/snapshots/snapshot-list/snapshot-list.component.ts
git cherry-pick -x 628785c9d45c63ce98b8da09da85e9b975fa6c32
Unset nopercent progressNumberType
Original PR: https://github.com/truenas/webui/pull/5246
=> NAS-109548 / 21.04 / Fix snapshot multidelete progressbar percent format (by dszidi)

src/app/pages/common/entity/entity-tree-table/entity-tree-table.component.html, src/app/pages/common/entity/entity-tree-table/entity-tree-table.component.ts, src/app/pages/common/entity/entity-tree-table/entity-tree-table.model.ts, src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
=> NAS-109804 / 21.04 / Added column based sorting in EntityTreeTable

src/app/pages/task-calendar/cloudsync/cloudsync-form/cloudsync-form.component.ts
=> NAS-109797 / 21.04 / Added special case for null value to disable bucket fields

src/app/pages/common/entity/entity-form/components/form-chip/form-chip.component.html
=> NAS-108854 / 21.04 / Added asterisk for requried & margin for tooltip for FormChipComponent

src/app/pages/common/entity/entity-form/components/form-permissions/form-permissions.component.html, src/app/pages/common/entity/entity-form/models/field-config.interface.ts, src/app/pages/services/components/service-ftp/service-ftp.component.ts, src/app/pages/services/components/service-tftp/service-tftp.component.ts
=> NAS-109288 / 21.04 / Changed behavior of File Permissions field checkboxes

src/app/pages/vm/vm-list/vm-list.component.ts, src/app/pages/vm/vm-wizard/vm-wizard.component.ts, src/app/services/modal.service.ts
=> NAS-109682 / 21.04 / Refresh page using getData when new vm has been created

src/app/pages/network/network.component.ts, src/app/pages/services/services.component.ts
=> NAS-109893 / 21.04 / Handled configure case for OpenVPN Client and Server services

src/app/pages/applications/applications.component.scss, src/app/pages/applications/catalog/catalog.component.html, src/app/pages/applications/catalog/catalog.component.ts, src/app/pages/applications/chart-releases/chart-releases.component.html, src/app/pages/applications/forms/chart-wizard.component.ts
Made for NAS-109316 by @AlexKarpov98
A new PR as requested by @denysbutenko due to wrong branch name on my side of things
- Fixes custom trains (not called "charts) not working
- Makes info modal availibility more clear on hover (color change and bigger pointer area)
- Gives a little more spaces for App titles (10-> 15 characters), as the "cutoff-dots" (...) also take up 3 characters
- Fixes Install wizard not taking Catalog and Train into account
- Fixes info modal not taking catalog and train into account
Signed-off-by: Kjeld Schouten-Lebbing kjeld@schouten-lebbing.nl
=> NAS-109316 / None / Misc bugfixes for NAS-109316

src/app/pages/system/bootenv/bootenv-status/bootenv-status.component.ts
=> NAS-108975 / 21.04 / Fixed resetting of table config in BootStatusListComponent to populate data when ready

src/app/pages/credentials/backup-credentials/forms/ssh-connections-form.component.ts
=> NAS-109692 / 21.04 / Disabled button when sub-form is not valid

src/app/helptext/vm/vm-wizard/vm-wizard.ts, src/app/pages/vm/vm-wizard/vm-wizard.component.ts
=> NAS-109713 / 21.04 / Creating devices separately with vm.device.create when creating a new VM through VMWizardComponent

src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
=> NAS-109834 / 21.04 / Update dataset form

src/app/pages/credentials/certificates-dash/forms/certificate-edit.component.ts
=> NAS-109428 / 21.04 / Fixed check for CSR when editing certificates/csr

src/app/pages/common/entity/entity-empty/entity-empty.component.scss
Screenshots available on https://jira.ixsystems.com/browse/NAS-109974
=> NAS-109974 / 21.04 / Fix entity-empty text color on light themes

src/app/pages/common/entity/entity-table/entity-table.component.html, src/assets/styles/material-reduction.css, src/assets/styles/tn-styles.scss
https://jira.ixsystems.com/browse/NAS-110103
=> NAS-110103 / 21.04 / Fix checkbox glitches

src/app/components/common/navigation/navigation.component.ts
=> NAS-109842 / 12.0 / Removed two-factor auth disable

README-egret.md, README.md, package.json
git cherry-pick -x 4b9c9b550e0094eace9e6ab609a68bc3e12a5d3b
git cherry-pick -x 8c7decae2cbe0a1863fd2a5fe21a587b2df4d506
git cherry-pick -x 0bf15c34d3305fb28c65bd9c682b2ee18362b509
Original PR: https://github.com/truenas/webui/pull/5237
=> NAS-109677 / 12.0 / Update repo info (by denysbutenko)

src/app/helptext/storage/volumes/datasets/dataset-acl.ts
git cherry-pick -x ad6a436e63b6b9301b44452668e49ecb23f1eb5c
Original PR: https://github.com/truenas/webui/pull/5302
=> NAS-109799 / 21.04 / Allow translate labels for ACL (by denysbutenko)

src/app/pages/common/entity/entity-toolbar/components/toolbar-menu/toolbar-menu.component.html, src/app/pages/common/entity/entity-toolbar/components/toolbar-menu/toolbar-menu.component.scss, src/app/pages/common/entity/entity-toolbar/components/toolbar-menu/toolbar-menu.component.ts, src/app/pages/common/entity/entity-toolbar/components/toolbar-multimenu/toolbar-multimenu.component.html, src/app/pages/common/entity/entity-toolbar/components/toolbar-multimenu/toolbar-multimenu.component.scss, src/app/pages/common/entity/entity-toolbar/components/toolbar-multiselect/toolbar-multiselect.component.html, src/app/pages/common/entity/entity-toolbar/entity-toolbar.component.css, src/app/pages/common/entity/entity-toolbar/entity-toolbar.component.html, src/app/pages/common/entity/entity-toolbar/entity-toolbar.component.scss, src/app/pages/common/entity/entity-toolbar/entity-toolbar.component.ts, src/assets/styles/material-reduction.css
=> NAS-110042 / 21.04 / Fix vertical alignment for toolbar items

src/app/helptext/storage/volumes/manager/manager.ts, src/app/pages/storage/volumes/manager/manager.component.html, src/app/pages/storage/volumes/manager/manager.component.ts
=> NAS-109689 / 12.0 / Add warning message for Log vdev

src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
=> NAS-109876 / 12.0 / Always showing Encryption checkbox, disabling relevant fields properly on value changes

.github/CODEOWNERS, .github/workflows/docker_image.yml
Don't really know what I'm doing, just copying stuff from master.
=> NAS-110198 / 12.0 / NAS-110198 - Make 12.0-stable workflow similar to master

.github/workflows/docker_external.yml, .github/workflows/docker_internal.yml
to check if the origin comes from internal repo or external fork and
use that to determine which to run
=> Split docker builts out into two seperate workflows, add conditional

.github/workflows/docker_external.yml, .github/workflows/docker_internal.yml
=> Backport fixes to run docker image creation for internal users on

src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts, src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
Will stop closing dataset sidebar on validation errors + some cleanup.
=> NAS-110121 / 21.06 / NAS-110121 - Do not close sidebar on WS error

src/app/pages/common/error-dialog/error-dialog.component.html, src/app/pages/data-protection/replication/replication-list/replication-list.component.ts, src/assets/styles/tn-styles.scss
git cherry-pick -x 9094ee5f8e394cf1a134d78f3ccfc736e445efd1
Original PR: https://github.com/truenas/webui/pull/5318
=> NAS-109971 / 21.06 / Fix replication error inconsistent display (by denysbutenko)

src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.html, src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.ts
git cherry-pick -x 2aa1961be61a62cbafbd74a068a27b3732228852
git cherry-pick -x 7087da82ab318e57447e8ddb9a4f7c4b5139e187
git cherry-pick -x eca056ee43609971fa7bf6815e3766f99822e8f3
Original PR: https://github.com/truenas/webui/pull/5305
=> NAS-109672 / 21.06 / Scheduler preview not handling daylight savings time correctly (by denysbutenko)

src/app/pages/common/password-dialog/password-dialog.component.html, src/app/pages/common/password-dialog/password-dialog.component.ts
git cherry-pick -x adc7f3911d0602615cdd250a29523201688b7e31
git cherry-pick -x 39010108cfe1e1a58c34cd3c0bcf1a48c6a09894
Original PR: https://github.com/truenas/webui/pull/5270
=> NAS-109860 / 21.06 / Fix "Continue" button on password dialog (by denysbutenko)

src/app/helptext/storage/volumes/manager/manager.ts, src/app/pages/storage/volumes/manager/manager.component.css, src/app/pages/storage/volumes/manager/manager.component.html, src/app/pages/storage/volumes/manager/manager.component.ts, src/app/pages/storage/volumes/manager/vdev/vdev.component.html
git cherry-pick -x f5bebf0dd0c3af31020bc769bf097ee1c419ec9f
git cherry-pick -x b76a0422ebdbd8d0ce66f1d7afcba7aa73cbc754
Original PR: https://github.com/truenas/webui/pull/5279
=> NAS-109689 / 21.06 / Add warning message for Log vdev (by denysbutenko)

src/app/pages/common/entity/entity-job/entity-job.interface.ts, src/app/pages/data-protection/cloudsync/cloudsync-list/cloudsync-list.component.ts, src/app/pages/data-protection/components/data-protection-dashboard/data-protection-dashboard.component.ts, src/app/pages/data-protection/replication/replication-form/replication-form.component.ts, src/app/pages/data-protection/replication/replication-list/replication-list.component.ts, src/app/pages/data-protection/replication/replication-wizard/replication-wizard.component.ts, src/app/pages/data-protection/replication/replication.interface.ts, src/app/pages/data-protection/rsync/rsync-list/rsync-list.component.ts
extends [PR#5315](https://github.com/truenas/webui/pull/5315), target branch: [NAS-109874](https://github.com/truenas/webui/tree/NAS-109874)
=> NAS-110199 / None / Sync Replication Tasks creation workflow

src/app/components/common/dual-list/dual-list.component.css, src/app/pages/account/groups/members/members.component.css
How it is currently:
How it will be:
=> NAS-109993 / 21.06 / Fix spacing and border color on dark themes

src/app/components/common/dual-list/dual-list.component.css, src/app/pages/account/groups/members/members.component.css
How it is currently:
How it will be:
Original PR: https://github.com/truenas/webui/pull/5285
Jira URL: https://jira.ixsystems.com/browse/NAS-109993
=> NAS-109993 / 12.0 / Fix spacing and border color on dark themes (by denysbutenko)

src/app/pages/storage/volumes/manager/manager.component.css, src/app/pages/storage/volumes/manager/manager.component.ts
git cherry-pick -x f4df66e24e5479ef7785a99a1feff269da927f8b
git cherry-pick -x 7fab48cde138fc9a9cb7e426875bcb5f2e867d27
git cherry-pick -x 16e490abdff0ee77be164f98ae83e51359032998
git cherry-pick -x d2946cffafe62c8182463ee0ff38f0cd59e3ff84
git cherry-pick -x 74dba66aaf212b084672f901a99f8880648f949b
git cherry-pick -x 9ac1aba0672bfb62e37477b348145bc14d08f221
git cherry-pick -x 9829a611ae164c33e348fa5154b050739176d940
Original PR: https://github.com/truenas/webui/pull/5321
Jira URL: https://jira.ixsystems.com/browse/NAS-109689
=> NAS-109689 / 12.0 / Add warning message for Log vdev (by denysbutenko) (by bugclerk)

src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.css, src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.html, src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.ts, src/app/pages/dashboard/dashboard.html, src/app/pages/system/system.routing.ts, src/app/services/navigation/navigation.service.ts
git cherry-pick -x cd177431f1a7314821b5a57b8ae0237f90bcb15f
git cherry-pick -x 6f102e8c8f4aa740c78ffbfec806b797dcb8cbda
git cherry-pick -x 0b216787de8f75f4a71804098872d62b2705ab7c
git cherry-pick -x c7308184dfb54ab492abdaacf8040baa71ae8b48
git cherry-pick -x 6642b30b586320401ad908c729e7d0c3b6d78105
git cherry-pick -x 10b2e202dac89741999a7748d740ef972428456b
git cherry-pick -x 10d24b5793da21fe9495e44929d078f400561489
git cherry-pick -x 97f6714c429c70c1d1ee73d8ef7ce39e4b9e7644
Original PR: https://github.com/truenas/webui/pull/5326
Jira URL: https://jira.ixsystems.com/browse/NAS-110134
=> NAS-110134 / 21.06 / Link to enclosure page from product image on dashboard (by dszidi)

src/app/core/services/disk-temperature.service.ts, src/app/pages/storage/import-disk/import-disk.component.ts
git cherry-pick -x fa7d88abc3628d3103984d1374c50257de43daf9
git cherry-pick -x 73c05ebcaf9a35002a39d7553552c5b6400441e4
git cherry-pick -x 38b433ccaa26fee870048a055404d582d56b9c0e
git cherry-pick -x 0fa932bc29a4f9af9da9793db2dd45c5b1fce133
git cherry-pick -x 7422ca1df4ec14840d87ccdd7435870bdad45e1a
Original PR: https://github.com/truenas/webui/pull/5336
Jira URL: https://jira.ixsystems.com/browse/NAS-109664
=> NAS-109664 / 21.06 / Use global service for disk.query events (by dszidi)

src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.html, src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.ts
git cherry-pick -x c5f551229fdfbac89d9237cf436607c6f87b163b
Original PR: https://github.com/truenas/webui/pull/5258
=> NAS-108293 / 21.06 / Show slot number in disk view. Make sure disk details are cleared (by dszidi)

src/app/helptext/system/general.ts, src/app/pages/system/general-settings/localization-form/localization-form.component.ts
=> NAS-110329 / 21.06 / Remove 'Sort language by' option from localization form

.vscode/settings.json
Backport of [PR#5360](https://github.com/truenas/webui/pull/5360)
=> NAS-110289 / 12.0 / Use absolute path for imports in VSCode (backported manually)

src/app/helptext/services/components/service-smart.ts, src/app/pages/services/components/service-smart/service-smart.component.ts
=> NAS-110247 / 12.0 / Added field removed by PR# 3619

src/app/pages/storage/volumes/zvol/zvol-form/zvol-form.component.ts
=> NAS-110246 / 12.0 / Removed queryCall to avoid race condition. Data fetched in preinit instead

src/app/interfaces/group.ts, src/app/interfaces/preferences.ts, src/app/interfaces/user.ts, src/app/pages/account/groups/group-list/group-list.component.ts
=> NAS-110293 / 21.06 / Fixed user count. Added dialog with user names when checkbox clicked

src/app/core/guards/translations-loaded.guard.ts, src/app/services/language.service.ts
This fixes some of the errors that I've discovered when porting to 12.0
=> NAS-110331 / 21.06 / NAS-110331: Simplifying translation system

src/app/app.routes.ts, src/app/components/common/layouts/admin-layout/admin-layout.component.ts, src/app/components/common/layouts/auth-layout/auth-layout.component.ts, src/app/components/common/topbar/topbar.component.ts, src/app/core/guards/translations-loaded.guard.ts, src/app/pages/system/general/general.component.ts, src/app/services/language.service.ts
Backport of 
https://github.com/truenas/webui/pull/5389
and https://github.com/truenas/webui/pull/5401
=> NAS-110331 / 12.0 / NAS-110331 - Guard to wait for translations to simplify translation code (by undsoft)

.gitignore, tests/bdd/conftest.py, tests/bdd/runtest.py, tests/bdd/scale/function.py
added scale/ for the UI test
added scale/features/.keepme to keep features at commit, and features folder is used to store the feature files during testing
added missing object to avoid committing to GitHub
added screenshot/scale with .keepme
added scale/function.py for all the extra functionality needed for developing scale UI test
improved conftest.py
added missing part in runtest.py for scale and improved it
=> DOCS-2049 added folders and code to start developing scale UI test

src/app/helptext/task-calendar/replication/replication.ts
@Mrt134 fix the wording if necessary please.
@undsoft can you then please make sure that i18n files are updated properly?
Master backport is not needed.
=> NAS-109476 / 12.0 / Fix Full Filesystem Replication tooltip

src/app/pages/storage/volumes/zvol/zvol-form/zvol-form.component.ts
=> NAS-110536 / 12.0 / Made deduplicatoin conditional based on dedup license

src/app/core/components/corecomponents.module.ts, src/app/core/components/widgets/widgetpool/widgetpool.component.html, src/app/core/components/widgets/widgetpool/widgetpool.component.ts, src/app/pages/common/entity/entity-toolbar/components/toolbar-multiselect/toolbar-multiselect.component.ts, src/app/pages/reportsdashboard/reportsdashboard.component.html, src/app/pages/reportsdashboard/reportsdashboard.component.ts
This is basically a manual port of https://github.com/truenas/webui/pull/5421. Cannot approve my own PR.
=> NAS-110503 / 21.06 / NAS-110503: Preselect disks when navigating from dashboard

src/app/core/guards/translations-loaded.guard.ts, src/app/services/language.service.ts
This fixes the issue when translations would take too long to load in some cases.
=> NAS-110048 / 12.0 / NAS-110048 - Fix for translations taking too long to load

src/app/pages/applications/chart-releases/chart-releases.component.ts, src/app/pages/applications/dialogs/chart-events/chart-events-dialog.component.ts, src/app/pages/applications/forms/chart-form.component.ts, src/app/pages/applications/forms/chart-release-add.component.ts, src/app/pages/applications/forms/chart-release-edit.component.ts, src/app/pages/applications/forms/chart-wizard.component.ts, src/app/pages/common/confirm-dialog/confirm-dialog.component.ts, src/app/pages/credentials/backup-credentials/backup-credentials.component.ts, src/app/pages/credentials/backup-credentials/forms/cloud-credentials-form.component.ts, src/app/pages/credentials/certificates-dash/certificates-dash.component.ts, src/app/pages/credentials/certificates-dash/forms/ca-add.component.ts, src/app/pages/credentials/certificates-dash/forms/ca-edit.component.ts, src/app/pages/credentials/certificates-dash/forms/certificate-add.component.ts, src/app/pages/credentials/certificates-dash/forms/certificate-edit.component.ts, src/app/pages/dashboard/dashboard-note-edit.component.ts, src/app/pages/dashboard/dashboard.component.ts, src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts, src/app/pages/data-protection/cloudsync/cloudsync-list/cloudsync-list.component.ts, src/app/pages/network/forms/configuration.component.ts, src/app/pages/plugins/available-plugins/available-plugins.component.ts, src/app/pages/preferences/page/forms/custom-theme-manager-form.component.ts, src/app/pages/storage/volumes/datasets/dataset-permissions/dataset-permissions.component.ts, src/app/pages/storage/volumes/datasets/dataset-posix-acl/dataset-posix-acl.component.ts, src/app/pages/system/advanced/console-form/console-form.component.ts, src/app/pages/system/advanced/cron/cron-form/cron-form.component.ts, src/app/pages/system/advanced/cron/cron-list/cron-list.component.ts, src/app/pages/system/bootenv/bootenv-list/bootenv-list.component.ts, src/app/pages/system/bootenv/bootenv-status/bootenv-status.component.ts, src/app/views/others/config-reset/config-reset.component.ts
No functional changes, testing is not necessary.
=> NAS-110628 / None / NAS-110628: Adding return types 3

src/app/core/components/widgets/widgetcpu/widgetcpu.component.html, src/app/core/components/widgets/widgetcpu/widgetcpu.component.ts, src/app/interfaces/events/cpu-stats-event.interface.ts, src/app/interfaces/events/index.ts, src/app/pages/dashboard/dashboard.component.ts
To test:
- Cpu widget on dahsboard works
- Link to report on cpu widget actually goes to reports.
=> NAS-110355 / 21.06 / NAS-110355: Fixes link on CPU widget in dashboard

src/app/pages/system/advanced/advanced-settings.component.ts
Fix "this.parent.doAdd is undefined"
=> NAS-110735 / 21.06 / Fix advanced settings

src/app/pages/storage/volumes/volumes-list/volumes-list-controls.component.html, src/assets/styles/material-reduction.css
To test: make sure Create Pool button on Storage page works.
=> NAS-110748 / 21.06 / NAS-110748 - Fixes Create Pool button

package.json, src/app/core/classes/xterm-attach-addon.ts, src/app/pages/applications/pod-shell/pod-shell.component.ts, src/app/pages/jails/jail-shell/jail-shell.component.ts, src/app/pages/shell/shell.component.ts, src/app/pages/systemprocesses/system-processes.component.ts, src/app/pages/vm/vm-serial-shell/vmserial-shell.component.ts, yarn.lock
Testing at the moment requires specific backend.
=> NAS-110577 / 21.06 / NAS-110577 - Binary frames for shell

.eslintrc.js, src/app/pages/applications/catalog/catalog.component.ts, src/app/pages/applications/forms/chart-form.component.ts, src/app/pages/applications/forms/chart-release-add.component.ts, src/app/pages/applications/forms/chart-release-edit.component.ts, src/app/pages/applications/forms/chart-wizard.component.ts
Previous issue was reproducible if user had slow internet connection (can be emulated in Chrome Inspector), went to Apps and quickly pressed Launch Docker Image.
=> NAS-110585 / 21.06 / NAS-110585: Race condition when clicking on Launch Docker wizard.

src/app/pages/storage/volumes/datasets/dataset-posix-acl/dataset-posix-acl.component.ts, src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts
To test:
- Make sure that pool.dataset.query is not returning mountpoints as null
- make sure all "Edit Permissions" links work and take the user to the correct form (acl/posix/permissions)
=> NAS-110130 / 21.06 / Fix mountpoint issue on storage page.

tests/bdd/ha-bhyve02/test_NAS_T0905.py, tests/bdd/ha-bhyve02/test_NAS_T1073.py, tests/bdd/pytest.ini
To Verify 2FA Login after Failover
=> DOCS-2193 / Added test_NAS_T1073.py with test case step definition and code

tests/bdd/conftest.py, tests/bdd/scale/function.py, tests/bdd/scale/test_NAS_T1066.py
Updated gherkins steps in test_NAS_T1066.py
Added nas_hostname fixture and hostname step in test_NAS_T1066.py
=> DOCS-2250 / DOCS-2253 / Added inputable option with a sleep of 0.5 second 

src/app/components/common/topbar/topbar.component.html
Not all the topbar icons had the same class attribute value so margins were not consistently applied.
To test simply inspect each icon in the right side of the topbar component and make sure they all have the same margins applied.
=> NAS-109165 / 21.08 / Consistent spacing of topbar icons.

src/app/pages/common/entity/entity.module.ts, src/app/pages/storage/volumes/datasets/dataset-unlock/dataset-unlock.component.ts
There is no way to test this, because I could not reproduce the issue locally. This is a blind fix.
=> NAS-110916 / None / NAS-110916 - Injection error when unlocking dataset

.eslintrc.js, src/app/components/common/dialog/consolepanel/consolepanel-dialog.component.ts, src/app/components/common/dialog/downloadkey/downloadkey-dialog.component.ts, src/app/components/common/dual-list/dual-list.component.ts, src/app/core/components/viewchart/viewchart.component.types.ts, src/app/core/services/core.service.ts, src/app/interfaces/query-api.interface.ts, src/app/interfaces/replication-task.interface.ts, src/app/pages/applications/chart-releases/chart-releases.component.ts, src/app/pages/applications/pod-logs/pod-logs.component.ts, src/app/pages/common/entity/entity-card/entity-card.component.ts, src/app/pages/common/entity/entity-form/components/form-upload/form-upload.component.ts, src/app/pages/common/entity/entity-job/entity-job.component.ts, src/app/pages/common/entity/utils.ts, src/app/pages/common/error-dialog/error-dialog.component.ts, src/app/pages/sharing/smb/smb-form/smb-form.component.ts, src/app/pages/storage/volumes/datasets/dataset-acl/dataset-acl.component.ts, src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts, src/app/pages/storage/volumes/datasets/dataset-posix-acl/dataset-posix-acl.component.ts, src/app/pages/storage/volumes/zvol/zvol-form/zvol-form.component.ts, src/app/pages/storage/volumes/zvol/zvol-wizard/zvol-wizard.component.ts, src/app/pages/system/update/update.component.ts, src/app/views/sessions/signin/signin.component.ts
=> NAS-111067 / 21.08 / NAS-111067 - Enable default ban-types rule

src/app/core/components/widgets/widgetnic/widgetnic.component.html
Steps to reproduce are in the ticket.
=> NAS-111111 / 21.06-BETA.1 / NAS-111111 - Fix dashboard failing on specific machine

src/app/core/components/widgets/widgetnic/widgetnic.component.html, src/app/pages/sharing/smb/smb-form/smb-form.component.ts
Just porting changes from release to master.
=> Merging release branch 2

tests/bdd/pytest.ini, tests/bdd/scale/test_NAS_T1062.py, tests/bdd/scale/test_NAS_T1089.py
dev branch build passed: https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/UI%20Tests%20-%20TrueNAS%20SCALE%20from%20a%20dev%20branch%20(Incremental)/42/
=> T1089 scaleuitest

tests/bdd/pytest.ini, tests/bdd/scale/test_NAS_T1071.py, tests/bdd/scale/test_NAS_T1093.py
https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/UI%20Tests%20-%20TrueNAS%20SCALE%20from%20a%20dev%20branch%20(Incremental)/53/
=> T1093 scaleuitest
