tests/bdd/pytest.ini
tests/bdd/scale/test_NAS_T1095.py

https://jira.ixsystems.com/browse/DOCS-2292
https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/UI%20Tests%20-%20TrueNAS%20SCALE%20from%20a%20dev%20branch%20(Incremental)/58/

DOCS-2292: t1095-scaleuitest

---

tests/bdd/pytest.ini
tests/bdd/scale/test_NAS_T1062.py
tests/bdd/scale/test_NAS_T1096.py

https://jira.ixsystems.com/browse/DOCS-2296
https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/UI%20Tests%20-%20TrueNAS%20SCALE%20from%20a%20dev%20branch%20(Incremental)/64

DOCS-2296: t1096-scaleuitest

---

tests/bdd/pytest.ini
tests/bdd/scale/test_NAS_T1097.py

https://jira.ixsystems.com/browse/DOCS-2297
https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/UI%20Tests%20-%20TrueNAS%20SCALE%20from%20a%20dev%20branch%20(Incremental)/66

DOCS-2297: t1097-scaleuitest

---

tests/bdd/pytest.ini
tests/bdd/scale/test_NAS_T1098.py

https://jira.ixsystems.com/browse/DOCS-2298
https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/UI%20Tests%20-%20TrueNAS%20SCALE%20from%20a%20dev%20branch%20(Incremental)/67

DOCS-2298: t1098-scaleuitest

---

tests/bdd/pytest.ini
tests/bdd/scale/test_NAS_T1099.py

https://jira.ixsystems.com/browse/DOCS-2299
https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/UI%20Tests%20-%20TrueNAS%20SCALE%20from%20a%20dev%20branch%20(Incremental)/68/

DOCS-2299: t1099-scaleuitest

---

tests/bdd/pytest.ini
tests/bdd/scale/test_NAS_T1101.py

https://jira.ixsystems.com/browse/DOCS-2305
https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/UI%20Tests%20-%20TrueNAS%20SCALE%20from%20a%20dev%20branch%20(Incremental)/78/testReport/scale/

DOCS-2305: t1101-scaleuitest

---

tests/bdd/pytest.ini
tests/bdd/scale/test_NAS_T1102.py

https://jira.ixsystems.com/browse/DOCS-2306
https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/UI%20Tests%20-%20TrueNAS%20SCALE%20from%20a%20dev%20branch%20(Incremental)/79/

DOCS-2306: t1102-scaleuitest

---

src/app/core/classes/system-profiler.ts
src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.html

Testing:
- Test against R10 (tn27) for no SAS Expanders case
- Test against any available TrueNAS controller that does have SAS Expanders

NAS-111148 / 12.0 / Enclosure UI should handle case of no sas expanders

---

src/app/core/classes/system-profiler.ts

To test/reproduce:
- Create a pool and add a vdev of type SPARE
- physically remove one of the non SPARE disks
- Make sure Enclosure UI still displays the pools once resilver has started

NAS-111222 / 12.0 / Don't assume REMOVED status will be present

---

src/app/helptext/storage/volumes/manager/manager.ts

NAS-111007 / 12.0 / Fixed link

---

src/app/pages/sharing/nfs/nfs-form/nfs-form.component.ts

**To test**
- Create a new user
- Open Shares dashboard
- Click `Add` NFS share
- Switch to 'Advanced Options'
- Click on [`Maproot User`,`Maproot Group`,`Mapall User`,`Mapall Group`] dropdown button on the right
- Scroll down to find user/group

NAS-111094 / 21.08 / Add load more on scroll for users and groups comboboxes

---

src/app/core/classes/hardware/es102.ts
src/app/core/classes/hardware/r20a.ts
src/app/core/classes/system-profiler.ts
src/app/core/components/widgets/widgetcpu/widgetcpu.component.ts
src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.html

No review is necessary, just moving commits.

12.0 u4.1 candidate

---

src/app/pages/system/bootenv/bootenv-status/bootenv-status.component.ts

To test:
1. System Settings -> Boot
2. Actions -> Boot Pool Status
3. Make sure three dot menu is there and working.

NAS-110391 / 21.08 / NAS-110391 - Fixes action menu on Boot Env

---

src/app/pages/credentials/backup-credentials/forms/cloud-credentials-form.component.ts

See https://github.com/truenas/webui/pull/5647

NAS-110665 / 21.08 / NAS-110665 - Fixing cloudcredential form + OpenStack Swift

---

src/app/core/components/widgets/widgetcpu/widgetcpu.component.css
src/app/core/components/widgets/widgetcpu/widgetcpu.component.html

This is basically a port of: https://github.com/truenas/webui/pull/4943

NAS-106198 / 12.0 / NAS-106198 - Fixing CPU widget in Safari

---

src/app/pages/credentials/backup-credentials/forms/cloud-credentials-form.component.ts

NAS-111015 / 21.08 / Fixed method that takes in fixed constant so it takes the latest value

---

src/app/pages/system/bootenv/bootenv-create/bootenv-create.component.ts

NAS-111286 / 21.08 / Fixed issue with late initialization of fieldConfig

---

src/app/pages/services/components/service-s3/service-s3.component.ts

Open Services  -> S3 and check that View secret key button works on edit.

NAS-111000 / 12.0 / NAS-111000 - Allowing secret_key to be visible on edit

---

src/app/pages/services/components/service-s3/service-s3.component.ts

Open Services  -> S3 and check that View secret key button works on edit.
Original PR: https://github.com/truenas/webui/pull/5659
Jira URL: https://jira.ixsystems.com/browse/NAS-111000

NAS-111000 / 21.08 / NAS-111000 - Allowing secret_key to be visible on edit (by undsoft)

---

src/app/core/classes/hardware/r20a.ts

Slots go left to right and top to bottom

NAS-111396 / 12.0 / Revert r20a slot layout to default

---

src/app/components/common/dialog/jobs-manager/components/job-item/job-item.component.html

Example of job that has description: `midclt call disk.wipe ada0 QUICK`
Preview:

NAS-107006 / 21.08 / Display job description in task manager

---

src/app/pages/sharing/smb/smb-list/smb-list.component.ts

NAS-110444 / 21.08 / Added two ACL options for SMB Shares

---

src/app/core/components/widgets/widgetcpu/widgetcpu.component.html

Cores are physical. Threads are logical.  Since this is regarding about physical temp we are talking about cores not threads.
I'll have another PR for the SCALE UI.

update the term threads to cores for temp values (Core Version)

---

src/app/core/components/widgets/widget-cpu/widget-cpu.component.html

Cores are physical. Threads are logical.  Since this is regarding about physical temp we are talking about cores not threads.
I think master is the scale branch, but if its not, let me know and I'll change the base branch.

update the term threads to cores for temp values (SCALE version)

---

src/app/core/components/widgets/widgetsysinfo/widgetsysinfo.component.ts

To test this, simply make sure that System Information widget for standby controllers consistently populate with content.

NAS-111476 / 12.0 / Passive widgets also need to listen for HA_Status

---

src/app/enums/tunable-type.enum.ts
src/app/interfaces/api-directory.interface.ts
src/app/interfaces/tunable.interface.ts
src/app/pages/system/tunable/tunable-form/tunable-form.component.ts

Testing:
System -> Advanced Settings -> check that you can add things to Sysctl

NAS-111461 / 21.08 / NAS-111461 - Fixing Sysctl form

---

src/app/core/services/core-service/core.service.spec.ts
src/app/directives/common/app-let.directive.ts
src/app/directives/common/common-directives.module.ts
src/app/pages/storage/volumes/volumes-list/volumes-list-table-config.ts
src/app/pages/vm/vm-form/vm-form.component.ts
src/app/pages/vm/vm-wizard/vm-wizard.component.ts
src/app/services/validation.service.ts
tsconfig.json

+ no-impilicit-this for stricter code
+ appLet directive https://medium.com/@AustinMatherne/angular-let-directive-a168d4248138
No testing is necessary.

NAS-111433 / 21.08 / Adding no-implicit this to introduce stricter checks.

---

src/app/pages/task-calendar/replication/replication-list/replication-list.component.ts

Testing instructions are a bit complicated. I suggest just approving based on ticket description and code, it's pretty clear what the intention was.

NAS-111478 / 12.0 / NAS-111478 - Fixing redundant error modal

---

src/app/pages/system/bootenv/bootenv-clone/bootenv-clone.component.ts

NAS-111287
To test
1. Go to System -> Boot page
2. Click on the three dots button for a boot env
3. Click on the clone option
4. The clone form should show up and the `source` field should be filled in

NAS-111287 / 21.08 / Fixed clone config and value set

---

src/app/helptext/data-protection/replication/replication.ts

@Mrt134 we will introduce a new field in another PR https://jira.ixsystems.com/browse/NAS-110543
With this PR I want to change existing field's tooltip to refer to that newly added field. Please review their names and descriptions in the JIRA issue and here.

NAS-109476 / 21.08 / Explain replicate_tooltip to use new name_regex option

---

src/app/interfaces/alert-service.interface.ts
src/app/pages/system/alert-service/alert-service/alert-service.component.ts

NAS-111342
To test, go to Alerts (Top bar) -> Settings (Cog Icon) -> Alert Services
Edit, or Add new alert service and try saving or sending test alerts

NAS-111342 / 21.08 / Fixed request payload

---

src/app/services/storage.service.spec.ts
src/app/services/storage.service.ts

You can test in any component that uses `convertBytestoHumanReadable`, for example in VM Wizard.

NAS-101423 / 21.08 / NAS-101423 - Updating how convertBytestoHumanReadable handles 0

---

src/app/pages/data-protection/components/data-protection-dashboard/data-protection-dashboard.component.ts

Testing: open Data Protection dashboard with a cloud sync task and click on [x] Enabled checkbox.

NAS-111485 / 21.08 / NAS-111485 - Fix enabled checkbox on Cloud Tasks

---

src/app/components/common/notifications/notifications.component.ts

NAS-111560
Ticket description has all the details for testing

NAS-111560 / 21.08 / Added wait until sidenav closed before navigating away

---

src/app/pages/vm/vm-list/vm-list.component.ts

NAS-111565 / 21.08 / Handled new response from vm.query subscription

---

src/app/pages/common/entity/entity-form/components/dynamic-field/dynamic-field.directive.ts
src/app/pages/common/entity/entity-form/components/form-radio/form-radio.component.html
src/app/pages/common/entity/entity-form/components/form-selection-list/form-selection-list.component.html
src/app/pages/common/entity/entity-form/components/form-selection-list/form-selection-list.component.scss
src/app/pages/common/entity/entity-form/components/form-selection-list/form-selection-list.component.ts
src/app/pages/common/entity/entity.module.ts
src/app/pages/storage/volumes/permissions/components/edit-nfs-ace/edit-nfs-ace-field-set.ts
src/app/pages/storage/volumes/permissions/components/edit-posix-ace/edit-posix-ace-field-set.ts
src/assets/styles/other/_material-reduction.scss
src/assets/styles/other/_tn-styles.scss

NAS-111470
To test, go to Storage -> Dataset three dots menu -> View Permission -> Edit Icon -> Set ACL button
Test the Advanced permissions and flags for NFS and Permissions for POSIX forms

NAS-111470 / 21.08 / Added FormSelectionListComponent, checkbox groups for NFS and POSIX ACL Editors

---

src/app/pages/vm/vm-list/vm-list.component.ts

Testing - check that autostart checkbox on list of vms works.

NAS-111376 / 21.08 / NAS-111376 - Autostart vm checkbox

---

src/app/core/components/widgets/widget-network/widget-network.component.scss
src/app/core/components/widgets/widget-storage/widget-storage.component.html
src/app/core/components/widgets/widget-storage/widget-storage.component.scss

Testing:
- Take a look at the Storage widget in different states (2, 4, 6 pools) and see if there is something that looks awkward

NAS-111446 / 21.08 / Layout improvements for Storage widget

---

src/app/components/common/app-common.module.ts
src/app/components/common/layouts/admin-layout/admin-layout.component.html
src/app/components/common/layouts/admin-layout/admin-layout.component.scss
src/app/components/common/layouts/admin-layout/admin-layout.component.ts
src/app/components/common/secondary-menu/secondary-menu.component.html
src/app/components/common/secondary-menu/secondary-menu.component.ts
src/assets/styles/scss-imports/cssvars.scss

Fixes: 
- https://jira.ixsystems.com/browse/NAS-110404
- https://jira.ixsystems.com/browse/NAS-110405
Generally, not very satisfied with these 'fixes', but better refactoring is for another time.

NAS-110405 / 21.08 / NAS-110405 - Main menu issues on mobile

---

src/app/pages/applications/applications.component.scss

Open list of installed apps and see all text.

NAS-111264 / 21.08 / NAS-111264 - Fixing text visibility on some themes

---

src/app/core/components/widgets/widget-storage/widget-storage.component.ts

Free space value is quite different on Dashboard and Storage pages

NAS-111668 / 21.08 / Fix free space on storage widget

---

src/app/pages/applications/chart-releases/chart-releases.component.ts

1. Find an app that has an update.
2. Remember current version.
3. Update, make sure that list is updated.
4. Rollback, make sure that list is updated.

NAS-111227 / 21.08 / NAS-111227 - Refresh app list after app update

---

src/app/pages/sharing/components/shares-dashboard/shares-dashboard.component.scss

NAS-110863 / 21.08 / Adjusted height

---

src/app/helptext/system/certificates.ts

NAS-111743 / 12.0 / Fixed tooltip

---

src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts

NAS-111181 / 12.0 / Added Boolean filter to check if password check was successful

---

src/app/pages/sharing/components/shares-dashboard/shares-dashboard.component.scss

NAS-111727 / 21.08 / Fixed table setting on smaller screens

---

src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts

NAS-110523 / 12.0 / Added warning for checksum

---

src/app/pages/common/entity/utils.ts

NAS-111767
See ticket description for reproduction steps
The error shows up properly now

NAS-111767 / 21.08 / Checked error response for null or undefined values before proceeding

---

src/app/pages/storage/volumes/volumes-list/volumes-list-table-config.ts

Suggest approving based on code alone, it's pretty straightforward.

NAS-111716 / 21.08 / NAS-111716 - Minor text update

---

src/app/core/components/widgets/widget-network/widget-network.component.html
src/app/core/components/widgets/widget-network/widget-network.component.scss
src/app/core/components/widgets/widget-network/widget-network.component.ts

| Before  | After |
| ------------- | ------------- |
| ![image](https://user-images.githubusercontent.com/351613/129228827-992e44f2-9991-4a19-999a-32975a57db70.png)  | ![image](https://user-images.githubusercontent.com/351613/129228846-2259138e-9f91-49bb-888b-b7cdb4d0106d.png)  |

NAS-111828 / 21.08 / Fix regressions on network chart

---

tests/bdd/scale/test_NAS_T1062.py
tests/bdd/scale/test_NAS_T1067.py
tests/bdd/scale/test_NAS_T1068.py
tests/bdd/scale/test_NAS_T1070.py
tests/bdd/scale/test_NAS_T1087.py
tests/bdd/scale/test_NAS_T1089.py
tests/bdd/scale/test_NAS_T1091.py
tests/bdd/scale/test_NAS_T1093.py
tests/bdd/scale/test_NAS_T1094.py
tests/bdd/scale/test_NAS_T1095.py
tests/bdd/scale/test_NAS_T1096.py
tests/bdd/scale/test_NAS_T1097.py
tests/bdd/scale/test_NAS_T1098.py
tests/bdd/scale/test_NAS_T1099.py
tests/bdd/scale/test_NAS_T1100.py
tests/bdd/scale/test_NAS_T1102.py
tests/bdd/scale/test_NAS_T1130.py
tests/bdd/scale/test_NAS_T1138.py

https://jira.ixsystems.com/browse/DOCS-2493

DOCS-2493 21.08 test fixes

---

src/app/core/components/widgets/widget-pool/widget-pool.component.ts
src/app/core/components/widgets/widget-storage/widget-storage.component.html
src/app/core/components/widgets/widget-storage/widget-storage.component.ts
src/app/core/services/api.service.ts
src/app/interfaces/events/volume-data-event.interface.ts
src/app/interfaces/volume-data.interface.ts
src/app/pages/dashboard/dashboard.component.ts
src/app/pages/dashboard/dashboard.html

This PR aims to update pool info especially focused on `Free Space` and `Used Space` on the Storage widget
How to test?
- Open Dashboard
- Remove or Upload something to some pool
- Check if `Free space` and `Used space` was updated (it may take up to 15 seconds)
Preview

NAS-111574 / 21.10 / Update pool info on the Storage widget

---

src/app/pages/common/entity/table/table.component.html
src/app/pages/common/entity/table/table.component.scss

How to test?
- Go to the Network page
- Check if table rows have the same height (48px)
- Go to the Backup Credentials page
- Check if table rows have the same height (48px)

NAS-111924 / 21.10 / Fix table rows height

---

src/app/services/cloudcredential.service.ts

NAS-111310 / 12.0 / Rounding off bandwidth in Bytes to closest integer

---

src/app/pages/storage/volumes/permissions/containers/dataset-trivial-permissions/dataset-trivial-permissions.component.ts

…cked & applied
Original PR: https://github.com/truenas/webui/pull/5800
Jira URL: https://jira.ixsystems.com/browse/NAS-111940

NAS-111940 / 21.10 / NAS-111940: Apply Permissions Recursively checkbox is not getting che… (by undsoft)

---

src/app/pages/common/entity/entity-table/entity-table.interface.ts
src/app/pages/sharing/webdav/webdav-list/webdav-list.component.ts

Go to Sharing -> Webdav full page. 
Make sure page works.

NAS-111939 / 21.08-BETA.1 / NAS-111939 - Fixing Webdav list

---

tests/bdd/pytest.ini
tests/bdd/scale/test_NAS_T1098.py
tests/bdd/scale/test_NAS_T1099.py
tests/bdd/scale/test_NAS_T1119.py

https://jira.ixsystems.com/browse/DOCS-2309
https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/UI%20Tests%20-%20TrueNAS%20SCALE%20from%20a%20dev%20branch%20(Incremental)/129

DOCS-2309 T1119 scaleuitest

---

src/app/pages/reportsdashboard/components/report/report.component.css
src/app/pages/reportsdashboard/components/report/report.component.html
src/app/pages/reportsdashboard/components/report/report.component.ts
src/app/pages/reportsdashboard/reportsdashboard.component.ts

NAS-111378
To test, check Reports -> Disks (graphs)
For disks that don't meet the criteria, an empty graph should show with a message to correctly configure the disk.

NAS-111378 / 12.0 / Added empty graph cards for temp graphs for disks that don't have them

---

src/app/pages/storage/volumes/volume-list-controls/volumes-list-controls.component.html

No testing is necessary, just making code compatible with tests.

NAS-112201 / 21.10 / NAS-112201: Reverting ix-auto changes

---

src/app/interfaces/api-directory.interface.ts
src/app/interfaces/dataset-lock.interface.ts
src/app/pages/storage/volumes/volumes-list/volumes-list-table-config.ts
src/app/services/storage.service.ts

In additions to #5848: Update related interface

NAS-112138 / 21.10 / NAS-112138: Remove services_restart attribute

---

src/app/core/services/api.service.ts

And this is why, kids, you don't mutate variables.

NAS-112160 / 12.0 / NAS-112160: Fixing enclosure page after using dashboard widget

---

src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.ts

Testing: connect to an instance [listed in the ticket](https://jira.ixsystems.com/browse/NAS-112239) and make sure enclosure ui works.

NAS-112239 / 12.0 / NAS-112239: R20B support in enclosure management

---

src/app/pages/system/view-enclosure/enclosure-disks/enclosure-disks.component.ts

git cherry-pick -x 6c4c439e966bee173afe33ee60d242877ad0bf4f
Testing: connect to an instance [listed in the ticket](https://jira.ixsystems.com/browse/NAS-112239) and make sure enclosure ui works.
Original PR: https://github.com/truenas/webui/pull/5884
Jira URL: https://jira.ixsystems.com/browse/NAS-112239

NAS-112239 / 21.10 / NAS-112239: R20B support in enclosure management (by undsoft)

---

src/app/core/services/api.service.ts

NAS-112329 / 21.10 / NAS-112329: Added value assignment for both cases

---

src/app/components/common/dialog/about/about-dialog.component.ts
src/app/components/common/topbar/topbar.component.ts
src/app/pages/preferences/page/forms/general-preferences-form.component.ts

NAS-112340 / 21.10 / NAS-112340: Quick fix for welcome dialog showing up over and over

---

src/app/pages/common/error-dialog/error-dialog.component.html
src/app/pages/common/error-dialog/error-dialog.component.scss
src/app/pages/common/error-dialog/error-dialog.component.ts
src/app/pages/common/info-dialog/info-dialog.component.html
src/assets/styles/other/_tn-styles.scss

To test:
- Create some replication task (ticket says cloud sync but can be any kind really)
- Misconfigure it so it fails
- Click on the "FAILED" in the state table cell
- In the error dialog click on "More info" button to show the error message.
- Make sure the white text-area does not extend so far that the action buttons cover it.

NAS-112435 / 21.10 / NAS-112435: Avoid button overlap

---

src/app/enums/job-state.enum.ts
src/app/pages/common/entity/entity-table/entity-table.component.ts
src/app/pages/common/entity/table/table.component.ts
src/app/pages/data-protection/cloudsync/cloudsync-list/cloudsync-list.component.ts
src/app/pages/data-protection/components/data-protection-dashboard/data-protection-dashboard.component.ts
src/app/pages/data-protection/rsync/rsync-list/rsync-list.component.ts

Locked dataset and shares available on Cloud VM

NAS-111731 / 21.10 / Display LOCKED state on Cloudsync/Rsync tasks

---

src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts

Easiest way to reproduce is to go to our cloudvm and try to edit a cloudsync task called `pizza` :)
Other way to reproduce is to create a cloudsync task without selecting any folders on remote machine and then reopening it for edit.

NAS-112423 / 21.10 / NAS-112423: Fix cloudsync form in some scenarios

---

tests/bdd/core/test_NAS_T1222.py
tests/bdd/pytest.ini

to verify core file alert works
here are the results https://builds.ixsystems.com/job/TrueNAS%2012.0%20Internal%20CORE%20UI%20Tests%20from%20Branch/8/

DOCS-2367 / 12.0 / added core/test_NAS_T1222.py with test case steps and code

---

tests/bdd/pytest.ini
tests/bdd/scale/test_NAS_T1119.py
tests/bdd/scale/test_NAS_T1123.py
tests/bdd/scale/test_NAS_T1124.py

https://jira.ixsystems.com/browse/DOCS-2324
https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/UI%20Tests%20-%20TrueNAS%20SCALE%20from%20a%20dev%20branch%20(Incremental)/179

DOCS-2324 T1124 scaleuitest

---

tests/bdd/scale/test_NAS_T1123.py
tests/bdd/scale/test_NAS_T1124.py

This fixes the import statements for t1123 and t1124

fix import statement

---

src/app/pages/vm/vm-form/vm-form.component.ts
src/app/pages/vm/vm-wizard/vm-wizard.component.ts

I was not able to reproduce the issue as described in the ticket.
This is essentially a blind fix.

NAS-112269 / 21.10 / NAS-112269: Maybe fixing GPU field in VM form

---

src/app/pages/sharing/components/shares-dashboard/shares-dashboard.component.ts

NAS-111884 / 21.10 / NAS-111884: Removing unnecessary tap and delay

---

src/app/pages/storage/volumes/volume-status/volume-status.component.ts

NAS-112289
To test
1. Create a pool
2. Have an extra unassigned disk attached with the VM
3. Go to "Status" page from the dropdown menu from the cog icon on the pool table header
4. Check if the `Extend` option is present on the three dot menu of the pool children

NAS-112289 / 21.10 / NAS-112289: Fixed actions addition to include Extend

---

.eslintrc.js
src/app/core/classes/hardware/es102.ts
src/app/core/classes/hardware/r50.ts
src/app/core/classes/hardware/vdev-labels-svg.ts
src/app/pages/applications/forms/kubernetes-settings.component.ts
src/app/pages/dashboard/components/dashboard/dashboard.component.ts
src/app/pages/dashboard/components/widget-pool/widget-pool.component.ts
src/app/pages/data-protection/scrub/scrub-form/scrub-form.component.ts
src/app/pages/data-protection/snapshot/snapshot-form/snapshot-form.component.ts
src/app/pages/services/components/service-smb/service-smb.component.ts
src/app/pages/system/view-enclosure/enclosure-disks/enclosure-disks.component.ts
src/app/pages/system/view-enclosure/view-enclosure.component.ts
src/app/services/modal.service.ts

This fixes first 3 forms fields not populating correctly in Apps -> Advanced Settings. To check, make sure you can work with these fields.
Also enabled a small linter rule.

NAS-112272 / 21.10 / NAS-112272: definitions/nodeIP not working

---

src/app/pages/applications/applications.component.scss
src/app/pages/applications/catalog/catalog.component.html
src/app/pages/applications/chart-releases/chart-releases.component.html

For testing, go to Applications and check if the badge has correct colors (blue for official charts and yellow for others) on Installed and Available tabs.

NAS-112631 / 21.10 / NAS-112631: Sync badge colors

---

src/app/pages/common/ix/components/ix-modal/ix-modal.component.ts
src/app/views/sessions/signin/signin.component.html
src/app/views/sessions/signin/signin.component.ts

There is no way to test this right now because middleware doesn't work correctly too, but the code is simple enough to just review it.

NAS-112665 / 21.10 / NAS-112665: Various fixes for failover

---

src/app/pages/common/ix/components/ix-combobox/ix-combobox.component.ts
src/app/pages/common/ix/components/ix-select/ix-select.component.ts
src/app/pages/system/general-settings/localization-form2/localization-form2.component.ts

To test: check that localization form doesn't have regressions.

NAS-112555 / 22.02-RC.2 / NAS-112555: Add ChangeDetection.OnPush to remaining new form components

---

tests/bdd/pytest.ini
tests/bdd/scale/test_NAS_T1137.py

https://jira.ixsystems.com/browse/DOCS-2332
https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/UI%20Tests%20-%20TrueNAS%20SCALE%20from%20a%20dev%20branch2%20(Incremental)/69

DOCS-2332 T1137 scaleuitest

---

tests/bdd/pytest.ini
tests/bdd/scale/test_NAS_T1241.py

https://jira.ixsystems.com/browse/DOCS-2751
https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/UI%20Tests%20-%20TrueNAS%20SCALE%20from%20a%20dev%20branch2%20(Incremental)/70/testReport/scale/test_NAS_T1241/

DOCS-2751 t1241-scaleuitest

---

tests/bdd/pytest.ini
tests/bdd/scale/test_NAS_T1242.py

https://jira.ixsystems.com/browse/DOCS-2752
https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/UI%20Tests%20-JT-%20TrueNAS%20SCALE%20from%20a%20dev%20branch%20(Incremental)/71/testReport/scale/test_NAS_T1242/

DOCS-2752 T1242 scaleuitest

---

tests/bdd/pytest.ini
tests/bdd/scale/test_NAS_T1243.py

https://jira.ixsystems.com/browse/DOCS-2754
https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/UI%20Tests%20-JT-%20TrueNAS%20SCALE%20from%20a%20dev%20branch%20(Incremental)/80/

DOCS-2754 T1243 scaleuitest

---

src/app/app.module.ts
src/environments/environment.ts.skel

NAS-113177 / 12.0 / NAS-113177: Fixing env file

---

src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts

Reproduction steps are in the ticket.

NAS-113008 / 22.02-RC.2 / NAS-113008: Fixing missing Promote menu items

---

src/app/pages/sharing/iscsi/iscsi-wizard/iscsi-wizard.component.ts

Test any regressions in IP validation in the relevant form

NAS-112525 / 22.02-RC.2 / NAS-112525: Removed unnecessary validator from iscsi-wizard.component.ts

---

src/app/components/common/dialog/resilver-progress/resilver-progress.component.html
src/app/components/common/dual-list/dual-list.component.html
src/app/components/common/dual-list/dual-list.component.ts
src/app/core/components/directives/text-limiter/text-limiter.directive.ts
src/app/modules/tooltip/tooltip.component.html
src/app/modules/tooltip/tooltip.module.ts
src/app/pages/common/entity/entity-form/components/form-chip/form-chip.component.html
src/app/pages/common/entity/entity-form/components/form-colorpicker/form-colorpicker.component.html
src/app/pages/common/entity/entity-form/components/form-combobox/form-combobox.component.html
src/app/pages/common/entity/entity-wizard/entity-wizard.component.html
src/app/pages/common/ix-forms/components/ix-combobox/ix-combobox.component.html
src/app/pages/common/ix-forms/components/ix-input/ix-input.component.html
src/app/pages/common/ix-forms/components/ix-user-combobox/ix-user-combobox.component.html
src/app/pages/credentials/backup-credentials/ssh-keypair-form/ssh-keypair-form.component.html
src/app/pages/dashboard/components/dashboard/dashboard.component.html
src/app/pages/reports-dashboard/components/report/report.component.html
src/app/pages/storage/volumes/manager/manager.component.html
src/app/pages/storage/volumes/manager/vdev/vdev.component.html
tsconfig.json

For testing maybe check some of the changes that look riskier.

NAS-113319 / None / NAS-113319: Make template checks even more strict

---

src/app/core/services/api.service.ts

This likely won't change much if anything at all, but just to be safer I've ported some changes that we made on `master` branch.
For testing you could try to reproduce the issue in the ticket, or do quick regression testing.

NAS-112744 / 12.0 / NAS-112744: Bringing api.service closer to its Scale conterpart

---

src/app/components/common/modal/modal.component.ts
src/app/pages/common/ix-forms/components/ix-modal/ix-modal.component.ts

Add support to close slide-in panels using the Esc key.
Please let me know if there are other places that need to be supported

NAS-113322 / 22.02-RC.2 / NAS-113322: Close modals on Escape

---

tests/bdd/pytest.ini
tests/bdd/scale/test_NAS_T1102.py
tests/bdd/scale/test_NAS_T1242.py
tests/bdd/scale/test_NAS_T1243.py
tests/bdd/scale/test_NAS_T1247.py

https://jira.ixsystems.com/browse/DOCS-2889
https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/UI%20Tests%20-JT-%20TrueNAS%20SCALE%20from%20a%20dev%20branch%20(Incremental)/123/testReport/scale/test_NAS_T1247/

DOCS-2889 T1247 scaleuitest

---

tests/bdd/pytest.ini
tests/bdd/scale/test_NAS_T1062.py
tests/bdd/scale/test_NAS_T1249.py

https://jira.ixsystems.com/browse/DOCS-2758
https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/UI%20Tests%20-JT-%20TrueNAS%20SCALE%20from%20a%20dev%20branch%20(Incremental)/127/testReport/scale/test_NAS_T1249/

DOCS-2758 T1249 scaleuitest

---

tests/bdd/pytest.ini
tests/bdd/scale/test_NAS_T1062.py
tests/bdd/scale/test_NAS_T1250.py

https://jira.ixsystems.com/browse/DOCS-2765
https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/UI%20Tests%20-JT-%20TrueNAS%20SCALE%20from%20a%20dev%20branch%20(Incremental)/129/testReport/scale/test_NAS_T1250/test_verify_that_you_can_create_a_new_group

DOCS-2765 T1250 scaleuitest

---

tests/bdd/pytest.ini
tests/bdd/scale/test_NAS_T1251.py
tests/bdd/scale/test_NAS_T1252.py

https://jira.ixsystems.com/browse/DOCS-2762
https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/UI%20Tests%20-JT-%20TrueNAS%20SCALE%20from%20a%20dev%20branch%20(Incremental)/135/testReport/scale/test_NAS_T1252/

DOCS-2762 T1252 scaleuitest

---

tests/bdd/pytest.ini
tests/bdd/scale/test_NAS_T1062.py
tests/bdd/scale/test_NAS_T1253.py

https://jira.ixsystems.com/browse/DOCS-2761
Also includes fix for t1062
https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/UI%20Tests%20-JT-%20TrueNAS%20SCALE%20from%20a%20dev%20branch%20(Incremental)/140/testReport/scale/test_NAS_T1253/

DOCS-2761 T1253 scaleuitest

---

src/app/pages/system/update/update.component.ts
src/app/services/dialog.service.ts

NAS-113474 / 22.02-RC.2 / First time update UI doesn't allow apply updates and reboot checkbox

---

src/app/pages/credentials/backup-credentials/forms/cloud-credentials-form.component.ts

Credentials -> Backup credentials
Empty FTP password + regressions.

NAS-113588 / 22.02 / NAS-113588: Allow empty string as an FTP password

---

tests/bdd/scale/test_NAS_T1125.py
tests/bdd/scale/test_NAS_T1133.py
tests/bdd/scale/test_NAS_T1223.py
tests/bdd/scale/test_NAS_T1237.py
tests/bdd/scale/test_NAS_T1243.py
tests/bdd/scale/test_NAS_T1244.py
tests/bdd/scale/test_NAS_T1247.py
tests/bdd/scale/test_NAS_T1257.py

DOCS-2750 is my epic for Q4
https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/UI%20Tests%20-JT-%20TrueNAS%20SCALE%20from%20a%20dev%20branch%20(Incremental)/168/

Fixing UI Automated Tests for SCALE

---

src/app/views/others/config-reset/config-reset.component.html
src/app/views/others/config-reset/config-reset.component.scss
src/app/views/others/reboot/reboot.component.html
src/app/views/others/reboot/reboot.component.scss
src/app/views/others/shutdown/shutdown.component.scss

Updated style for shutdown and config reset pages too.

NAS-113709 / 22.02 / TrueNAS logo do not fit the box on Reboot page

---

src/app/pages/common/entity/entity-form/components/form-upload/form-upload.component.ts

Make sure to actually press Upload after selecting a file.

NAS-113724 / 22.02-RC.2 / NAS-113724: Cannot Restore Config File

---

src/app/pages/common/entity/entity-form/components/form-upload/form-upload.component.ts

Make sure to actually press Upload after selecting a file.
Original PR: https://github.com/truenas/webui/pull/6193
Jira URL: https://jira.ixsystems.com/browse/NAS-113724

NAS-113724 / 22.02 / NAS-113724: Cannot Restore Config File (by undsoft)

---

src/app/components/common/notifications/notifications.component.html
src/app/components/common/notifications/notifications.component.ts
src/app/enums/api-event-message.enum.ts
src/app/interfaces/api-event.interface.ts
src/app/services/notifications.service.ts

Testing:
- Find a system with alerts. There are alerts that get dismissed and can be reopened and alerts that get removed. You need to test both.
- Dismiss/undismiss alerts.
- Open two tabs on the same page. Dismiss/undismiss alerts. Observe that changes propagate to another tab.
- Create alerts manually via shell: `midclt call alert.oneshot_create UnscheduledReboot "Something bad happened"`. Clear the alert. For additional alerts use different error message.

NAS-113738 / 22.02-RC.2 / NAS-113738: Hack-fixes alerts

---

src/app/components/common/notifications/notifications.component.html
src/app/components/common/notifications/notifications.component.ts
src/app/enums/api-event-message.enum.ts
src/app/interfaces/api-event.interface.ts
src/app/services/notifications.service.ts

Testing:
- Find a system with alerts. There are alerts that get dismissed and can be reopened and alerts that get removed. You need to test both.
- Dismiss/undismiss alerts.
- Open two tabs on the same page. Dismiss/undismiss alerts. Observe that changes propagate to another tab.
- Create alerts manually via shell: `midclt call alert.oneshot_create UnscheduledReboot "Something bad happened"`. Clear the alert. For additional alerts use different error message.
Original PR: https://github.com/truenas/webui/pull/6198
Jira URL: https://jira.ixsystems.com/browse/NAS-113738

NAS-113738 / 22.02 / NAS-113738: Hack-fixes alerts (by undsoft)

---

src/app/pages/services/components/service-lldp/service-lldp.component.html
src/app/pages/services/components/service-lldp/service-lldp.component.scss
src/app/pages/services/components/service-lldp/service-lldp.component.spec.ts
src/app/pages/services/components/service-lldp/service-lldp.component.ts
src/app/pages/services/services.module.ts
src/app/pages/services/services.routing.ts
src/app/services/services.service.ts

Testing: System Settings -> Services -> LLDP

NAS-113821 / 22.02 / NAS-113821: Refactor LLDP form to new ix-forms

---

tests/bdd/pytest.ini
tests/bdd/scale/test_NAS_T1258.py
tests/bdd/scale/test_NAS_T1259.py

https://jira.ixsystems.com/browse/DOCS-2766
https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/UI%20Tests%20-JT-%20TrueNAS%20SCALE%20from%20a%20dev%20branch%20(Incremental)/175/testReport/scale/test_NAS_T1258/
https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/UI%20Tests%20-JT-%20TrueNAS%20SCALE%20from%20a%20dev%20branch%20(Incremental)/175/testReport/scale/test_NAS_T1259/

DOCS-2766 T1258 T1259 SCALE UI Tests

---

src/app/views/others/config-reset/config-reset.component.ts
src/app/views/others/failover/failover.component.ts
src/app/views/others/reboot/reboot.component.ts
src/app/views/others/shutdown/shutdown.component.ts

Basically in some scenarios the url for reboot/shutdown and some other pages got saved, which led to infinite reboot cycle.
More detailed steps are in ticket description.

NAS-113453 / 13.0 / NAS-113453: Prevent recursive shutdowns and reboots

---

src/app/pages/reportsdashboard/components/report/report.component.ts
src/app/pages/reportsdashboard/reports.service.ts

Not sure how to test. This was an issue on Chrome only that wasn't reproducible on localhost anyway, so don't know how you would test this. This needs to be tested directly on a VM.

NAS-113814 / 13.0 / Making `getServerTime` async

---

src/app/pages/reportsdashboard/components/report/report.component.ts
src/app/pages/reportsdashboard/reports.service.ts

Not sure how to test. This was an issue on Chrome only that wasn't reproducible on localhost anyway, so don't know how you would test this. This needs to be tested directly on a VM. 
Original PR: https://github.com/truenas/webui/pull/6226
Jira URL: https://jira.ixsystems.com/browse/NAS-113814

NAS-113814 / 12.0 / Making `getServerTime` async (by RehanY147)

---

src/app/pages/account/users/user-list/user-list.component.ts
src/app/pages/common/entity/entity-toolbar/components/toolbar-button/toolbar-button.component.html
src/app/pages/common/entity/entity-toolbar/components/toolbar-button/toolbar-button.component.ts
src/app/pages/common/entity/entity-toolbar/models/control-config.interface.ts

For testing, go to the Users page, and right-click on the "Add" button choose "Inspect" then make sure that 
`ix-auto="button__Users_ADD"`

NAS-113869 / 22.02 / NAS-113869: Users Page Add Button ix-auto value regression

---

tests/bdd/pytest.ini
tests/bdd/scale/test_NAS_T1260.py

https://jira.ixsystems.com/browse/DOCS-2768
https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/UI%20Tests%20-JT-%20TrueNAS%20SCALE%20from%20a%20dev%20branch%20(Incremental)/176/testReport/scale/test_NAS_T1260/

DOCS-2768 T1260 scaleuitest

---

tests/bdd/pytest.ini
tests/bdd/scale/test_NAS_T1261.py

https://jira.ixsystems.com/browse/DOCS-2767
https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/UI%20Tests%20-JT-%20TrueNAS%20SCALE%20from%20a%20dev%20branch%20(Incremental)/177/testReport/scale/test_NAS_T1261/

DOCS-2767 T1261 scaleuitest

---

src/app/pages/applications/application-tab.enum.ts
src/app/pages/applications/application-toolbar-control.enum.ts
src/app/pages/applications/applications.component.html
src/app/pages/applications/applications.component.ts
src/app/pages/applications/catalog/catalog.component.ts
src/app/pages/applications/chart-releases/chart-releases.component.ts
src/app/pages/applications/docker-images/docker-images.component.ts
src/app/pages/applications/manage-catalogs/manage-catalogs.component.ts

Testing: type something in search bar in Apps and switch sections.
Known issue: there may be some UI flickering.
Also includes very minor speed optimizations for Available apps page.

NAS-113850 / 22.02 / NAS-113850: Clearing search bar in apps on tab switches

---

src/app/views/sessions/signin/signin.component.ts

Solved the problem that redirected to dashboard page when reloading the page.
Similar to Scale version [NAS-110533](https://jira.ixsystems.com/browse/NAS-110533)

NAS-114150 / 13.0 / Pressing reload for the license it reload to the Dashboard instead of Support page

---

src/app/pages/dashboard/components/widget-cpu/widget-cpu.component.ts
src/app/pages/dashboard/components/widget-memory/widget-memory.component.ts

Testing: trigger race condition by adding some delay to both of these events: `UserPreferencesChanged` and `UserPreferencesReady`

NAS-108939 / 22.02 / NAS-108939: Dashboard: fix race condition between theme query and chart initialization

---

tests/bdd/ha-bhyve02/test_NAS_T0905.py

Test passed 2 times https://builds.ixsystems.com/job/TrueNAS%2013.0%20nightlies%20HA%20UI%20Tests%20from%20branch/

DOCS-3026 / Improved the HA test for 13.0

---

src/app/pages/storage/volumes/manager/manager.component.ts

Testing: use 2+ disks which have different volume

NAS-114058 / 22.02 / NAS-114058: Fix Duplicate drives in pool creation

---

src/app/pages/common/entity/entity-table/entity-table.component.html

Ticket description has details on the issue. One important detail is that you should have the same name for each table item on the alert services list page.

NAS-114052 / 13.0 / Fixed checkbox clicks by adding unique ids

---

src/app/pages/common/entity/entity-table/entity-table.component.html

Ticket description has details on the issue. One important detail is that you should have the same name for each table item on the alert services list page.
Original PR: https://github.com/truenas/webui/pull/6285
Jira URL: https://jira.ixsystems.com/browse/NAS-114052

NAS-114052 / 12.0 / Fixed checkbox clicks by adding unique ids (by RehanY147)

---

src/app/interfaces/api-directory.interface.ts
src/app/services/vm.service.ts

Unused method removed. No testing is necessary.

NAS-111724 / None / NAS-111724: Remove support for { get: true }

---

src/app/pages/common/entity/entity-table/entity-table.component.html

Will be moved to next release.

Revert "NAS-114052 / 12.0 / Fixed checkbox clicks by adding unique ids (by RehanY147)"

---

src/app/pages/common/entity/entity-table/entity-table-add-actions/entity-table-add-actions.component.html
src/app/pages/storage/volumes/manager/manager.component.ts

Blocked the filter input with a form.

NAS-113708 / 22.02 / Fix autocomplete on search field

---

src/app/helptext/system/update.ts
src/app/pages/system/update/update.component.css
src/app/pages/system/update/update.component.html
src/app/pages/system/update/update.component.ts

Observe new link on System -> Update.

NAS-114297 / 12.0 / NAS-114297: Add link to docs from Update page

---

src/app/pages/applications/applications.component.ts

Check that you can press toolbar button on all tabs in Apps section.

NAS-114224 / 22.02 / NAS-114224: Fixing broken toolbar buttons in Apps

---

src/app/pages/common/entity/table/table.component.html
src/app/pages/common/entity/table/table.component.ts
src/app/pages/common/ix-forms/components/ix-slide-toggle/ix-slide-toggle.component.html
src/app/pages/common/ix-forms/components/ix-slide-toggle/ix-slide-toggle.component.scss
src/app/pages/common/ix-forms/components/ix-slide-toggle/ix-slide-toggle.component.ts
src/app/pages/common/ix-forms/components/ix-slide-toggle/ix-slide-toggle.harness.ts
src/app/pages/common/ix-forms/ix-forms.module.ts
src/app/pages/common/ix-forms/testing/ix-form.harness.ts
src/app/pages/dashboard/components/dashboard-form/dashboard-form.component.html
src/app/pages/sharing/components/shares-dashboard/shares-dashboard.component.ts
src/assets/styles/other/_tn-styles.scss

Created a new `ix-slide-toggle` component

NAS-111872 / 22.02 / Use toggle slider to control share status

---

tests/bdd/pytest.ini
tests/bdd/scale/test_NAS_T1285.py

https://jira.ixsystems.com/browse/DOCS-2771
https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/UI%20Tests%20-JT-%20TrueNAS%20SCALE%20from%20a%20dev%20branch%20(Incremental)/202/testReport/scale/test_NAS_T1285/

DOCS 2771 T1285 scaleuitest

---

tests/bdd/scale/test_NAS_T1286.py

https://jira.ixsystems.com/browse/DOCS-3097
https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/UI%20Tests%20-JT-%20TrueNAS%20SCALE%20from%20a%20dev%20branch%20(Incremental)/203/testReport/scale/test_NAS_T1286/

DOCS-3097 T1286 scaleuitest

---

src/app/pages/vm/vm-list/vm-list.component.ts
src/assets/i18n/fr.po

git cherry-pick -x 35dea451eab378f77eaaa9b42300bcfcf6cd1f24
git cherry-pick -x f76bb3dde899ee2187ce5e6c7670a18b39e743be
Original PR: https://github.com/truenas/webui/pull/6305
Jira URL: https://jira.ixsystems.com/browse/NAS-114171

NAS-114171 / 13.0 / NAS-114171: provide translation id for "serial shell" (by bvasilenko)

---

src/app/pages/common/info-dialog/info-dialog.component.html
src/app/pages/vm/devices/device-edit/device-edit.component.html

For testing, to go Virtualization -> Existing VM -> Devices
1. Add RAW Device (any file with .raw extension will work)
2. Your RAW Device -> "..." menu -> Edit 
3. Any Device -> "..." menu) -> Details (look for modal's heading to not contain HTML tags)

NAS-114087 / 22.02 / NAS-114087: VM - RAW file type broken/unable to run VM

---

src/app/pages/common/entity/entity-table/entity-table.component.ts
src/app/pages/vm/vm-list/vm-list.component.ts

Testing: start/stop existing VM and watch for issues as per description

NAS-114347 / 22.02 / NAS-114347: Virtual Machines list don't update when starting or stopping a VM

---

tests/bdd/pytest.ini
tests/bdd/scale/test_NAS_T1287.py

https://jira.ixsystems.com/browse/DOCS-3098
https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/UI%20Tests%20-JT-%20TrueNAS%20SCALE%20from%20a%20dev%20branch%20(Incremental)/217/testReport/scale/test_NAS_T1287/

DOCS-3098 T1287 scaleuitest

---

tests/bdd/pytest.ini
tests/bdd/scale/test_NAS_T1334.py

https://jira.ixsystems.com/browse/DOCS-3121
https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/UI%20Tests%20-JT-%20TrueNAS%20SCALE%20from%20a%20dev%20branch%20(Incremental)/225/testReport/scale/test_NAS_T1334/

DOCS-312` T1334 scaleuitest

---

tests/bdd/pytest.ini
tests/bdd/scale/test_NAS_T1335.py

https://jira.ixsystems.com/browse/DOCS-3122
https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/UI%20Tests%20-JT-%20TrueNAS%20SCALE%20from%20a%20dev%20branch%20(Incremental)/222/testReport/scale/test_NAS_T1335/

DOCS-3122 T1335 scaleuitest

---

src/app/pages/common/entity/entity-form/components/form-scheduler/form-scheduler.component.scss

Updated `form-scheduler` style

NAS-114410 / 22.02 / Custom cron job modal is cut off on smaller screens

---

src/app/modules/entity/entity-form/components/form-explorer/form-explorer.component.ts
src/app/modules/entity/entity-form/entity-form.component.ts
src/app/modules/entity/entity-form/validators/forbidden-values-validation.ts
src/app/modules/entity/entity-form/validators/ip-validation.ts
src/app/modules/entity/entity-form/validators/regex-validation.ts
src/app/modules/entity/entity-table/entity-table-actions/entity-table-actions.component.ts
src/app/modules/ix-forms/services/ix-validators.service.ts
src/app/pages/reports-dashboard/components/report/report.component.ts
src/app/pages/services/components/service-ftp/service-ftp.component.ts
src/app/pages/sharing/iscsi/iscsi-wizard/iscsi-wizard.component.ts
src/app/pages/sharing/iscsi/portal/portal-form/portal-form.component.ts
src/app/services/theme/theme.service.ts

NAS-114284 / None / NAS-114284: replace simple instances of == with ===

---

tests/bdd/ha-bhyve02/test_NAS_T0905.py
tests/bdd/ha-bhyve02/test_NAS_T0932.py

https://builds.ixsystems.com/job/TrueNAS%2013.0%20nightlies%20HA%20UI%20Tests%20from%20branch/18/

DOCS-3141 Changed Create Pool wait to disappear to 120 second

---

src/app/pages/common/entity/entity-empty/entity-empty.component.scss
src/app/pages/common/entity/table/table.component.html
src/app/pages/dashboard/components/dashboard/dashboard.component.html

Updated the style of `entity-empty` component

NAS-114546 / 22.02 / Some tables in the UI have left aligned empty and loading states

---

tests/bdd/pytest.ini
tests/bdd/scale/test_NAS_T1355.py

https://jira.ixsystems.com/browse/DOCS-3108
https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/UI%20Tests%20-JT-%20TrueNAS%20SCALE%20from%20a%20dev%20branch%20(Incremental)/241/testReport/scale/test_NAS_T1355/

DOCS-3108 T1355 scaleuitest

---

src/app/services/ws.service.ts

Testing:
Confirm multicasting in any component:
```
const request$ = this.ws.call('system.general.language_choices');     
request$.subscribe((config) => console.log('subscription 1', config));
request$.subscribe((config) => console.log('subscription 2', config));
request$.subscribe((config) => console.log('subscription 3', config));
```

NAS-112343 / None / Websocket observables are not properly multicasted

---

src/app/modules/ix-forms/components/ix-input/ix-input.component.html
src/app/modules/ix-forms/components/ix-input/ix-input.component.scss

Check inputs that have a reset button

NAS-114633 / None / NAS-114633: Fixed ix-input value overlap icon

---

src/app/modules/entity/entity-job/entity-job.component.html
src/app/modules/entity/entity-job/entity-job.component.ts
src/app/pages/system/update/manual-update/manual-update.component.ts

Go to the Update page and choose to update a manual file to update TrueNAS. During the upload, you should be able to see the upload progress and afterwards, the update process should go smoothly.

NAS-110284 / None / NAS-110284: Added upload progress

---

src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts

Testing:
Storage -> Create dataset / Edit dataset option
Try to input 0 in the `Metadata (Special) Small Block Size` field.

NAS-114682 / 13.0 / Unable to select 0 in special vdev for metadata size

---

src/app/modules/entity/entity-table/entity-table.component.scss

Check borders for empty tables

NAS-114731 / None / NAS-114731: fixed width for .mat-card-table

---

src/app/pages/storage/volumes/manager/manager.component.html
src/app/pages/storage/volumes/manager/manager.component.scss

Testing:
- Storage->Create Pool-> Available Disks
- You will need 10+ disks. One way to do it is mock data

NAS-114810 / 22.02 / NAS-114810: Create Pool UI Page - No page/scroll option shown for available disks (SCALE)

---

src/app/views/sessions/signin/signin.component.ts

Testing:
System -> 2FA -> Enable Two Factor Authentication
Re-checked Two Factor Status after failing to login in to the sync login page.

NAS-114614 / 13.0 / 2FA field doesn't show after failover until screen is refreshed

---

src/app/pages/common/entity/entity-form/components/form-errors/form-errors.component.html
src/app/pages/services/components/service-ups/service-ups.component.ts

Testing:
System Settings -> Services -> UPS
If UPS mode is `Master`, Port or Hostname field is required
else `Slave`, Port or Hostname field is optional

NAS-113904 / 13.0 / WebUI - Services / UPS / Settings: Save button remains disabled after setting changes

---

src/app/core/components/widgets/widgetpool/widgetpool.component.css
src/app/core/components/widgets/widgetpool/widgetpool.component.html
src/app/core/components/widgets/widgetpool/widgetpool.component.ts

Testing: 
mock properties of the pool object
- `healthy` to `false` 
- `status` to `DEGRADED` (also try `LOCKED` and `FAULTED`)

NAS-113471 / 13.0 / NAS-113471: Dashboard and Storage -> Pools degraded symbology do not match

---

src/app/helptext/task-calendar/replication/replication.ts
src/app/pages/task-calendar/replication/replication-form/replication-form.component.ts

The added warning should show up for edits but not for new replication tasks

NAS-114275 / 13.0 / Added warning

---

src/app/pages/directory-service/components/active-directory/active-directory.component.ts

Re-targeted from https://github.com/truenas/webui/pull/6443

NAS-114769 / 22.02 / Changing Kerberos Principal from nothing to "---" breaks AD form

---

src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts

Re-targeted from https://github.com/truenas/webui/pull/6445

NAS-114751 / 22.02 / TrueNas Scale Cloud Sync Remote folder reset to /

---

src/app/modules/ix-forms/components/ix-radio-group/ix-radio-group.harness.ts
src/app/pages/network/configuration/configuration.component.html
src/app/pages/network/configuration/configuration.component.spec.ts

Tested in [network configuration component](https://github.com/truenas/webui/blob/d780886dc4566f1e3441695e396e94e699f354f3/src/app/pages/network/configuration/configuration.component.spec.ts)

NAS-114799 / 22.12 / Bug in setValue for IxRadioGroup harness

---

package.json
tsconfig.json
yarn.lock

To test simply make sure UI compiles and no new errors are present.

NAS-115136 / 13.0 / Replace deprecated dependency.

---

src/app/pages/services/services.component.ts
src/app/pages/services/services.module.ts

Go to System -> Services and previously the column "Start Automatically" would have issues showing checkboxes. You would get the "No value accessor for control" error. This PR should fix that.

NAS-115181 / 22.12 / NAS-115181: Added missing module

---

src/app/pages/storage/storage.module.ts

The pool create page didn't work correctly and gave errors on the console. This PR should fix that.

NAS-115193 / 22.12 / NAS-115193: Added missing module

---

src/app/pages/common/entity/entity-form/components/form-chip/form-chip.component.html
src/app/pages/common/entity/entity-form/components/form-chip/form-chip.component.ts

Testing:
Nextwork -> Gloabal Configuration -> Host Name Database
Try to paste the following text
192.168.0.220 tn1
192.168.0.228 tn2
192.168.0.225 tn3
Split it to set the chip list value if the paste value includes line break.

NAS-115191 / 22.02.1 / "Network / Global Configuration / Host Name Database" is inconvenient

---

src/app/pages/system/ssh-connections/ssh-connections-form/ssh-connections-form.component.ts

Testing:
SSH Connection -> Add -> Generate SSH Key Pair

NAS-115099 / 13.0 / SSH Keypairs: Creating a Private Key for a System fails

---

src/app/pages/dashboard/components/dashboard/dashboard.component.ts

Testing:
Create a new Pool or more
Go to Dashboard -> Click Configure
Please confirm if displays all the pools

NAS-115243 / 22.02.1 / Dashboard Pool Widget not seeing new pool

---

src/app/helptext/system/advanced.ts
src/app/pages/system/advanced/advanced.component.ts

see https://github.com/truenas/webui/pull/6304

NAS-114241 / 13.0 / Replication configuration (13.0-stable)

---

src/app/interfaces/api-directory.interface.ts
src/app/pages/system/advanced/advanced-settings.component.ts
src/app/pages/system/advanced/sed-form/sed-form.component.spec.ts
src/app/pages/system/advanced/sed-form/sed-form.component.ts

Testing:
System -> Advanced -> SED widget & configure form
Related ticket [NAS-114915](https://jira.ixsystems.com/browse/NAS-114915), PR [6454](https://github.com/truenas/webui/pull/6454)

NAS-115057 / 22.02.1 / Provide indication that SED password was set

---

.github/workflows/docker_internal.yml
jest.config.js
package.json
src/app/core/classes/theme-utils/theme-utils.spec.ts
src/app/core/classes/theme-utils/theme-utils.ts

This is mostly an experiment to check if coverage reporting works correctly.

NAS-114658 / 22.12 / NAS-114658: Improving coverage reporting

---

src/app/core/testing/classes/mock-websocket.service.ts
src/app/modules/ix-forms/components/ix-input/ix-input.component.spec.ts
src/app/modules/ix-forms/components/ix-select/ix-select.harness.ts
src/app/modules/truecommand/truecommand-button.component.spec.ts
src/app/pages/storage/volumes/volume-import-wizard/volume-import-wizard.component.html
src/app/pages/storage/volumes/volume-import-wizard/volume-import-wizard.component.spec.ts
src/app/pages/system/general-settings/gui-form/gui-form.component.spec.ts

Some errors in tests are reported in console, but do not prevent tests from passing. This fixes those errors.

NAS-115393 / 22.12 / NAS-115393: Fixes console errors in tests

---

src/app/pages/dashboard/components/dashboard/dashboard.component.ts

Re-targeted for Angelfish from [6521](https://github.com/truenas/webui/pull/6521)

NAS-115256 / 22.02.1 / Dashboard widget is broken after pool is removed

---

src/app/pages/credentials/certificates-dash/forms/ca-add.component.ts

Testing:
Credentials -> Certificates -> Add Certificate Authorities -> Type: Intermadiate CA
Removed default null option to enable step validation.

NAS-115364 / 22.12 / SCALE: Field Validation failure on add CA forum

---

src/app/modules/ix-forms/components/ix-checkbox-list/ix-checkbox-list.harness.ts
src/app/pages/account/users/user-form/user-form.component.spec.ts

NAS-115183 / 22.12 / NAS-115183: Refactoring User Form Fixes

---

src/app/modules/ix-forms/components/ix-permissions/ix-permissions.harness.ts
src/app/pages/services/components/service-tftp/service-tftp.component.html
src/app/pages/services/components/service-tftp/service-tftp.component.scss
src/app/pages/services/components/service-tftp/service-tftp.component.spec.ts
src/app/pages/services/components/service-tftp/service-tftp.component.ts

Testing: System Settings -> Services -> TFTP.

NAS-115453 / 22.12 / NAS-115453: Refactoring TFTP service form

---

src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.ts

Added some lacking `else` conditions that might have caused this

NAS-115420 / 22.02.1 / NAS-115420: Added protections

---

src/app/pages/account/users/user-form/user-form.component.spec.ts
src/app/pages/account/users/user-form/user-form.component.ts

Related middleware PR - https://github.com/truenas/middleware/pull/8639

NAS-115470 / 22.12 / NAS-115470: Disable ms account field for builtin users

---

src/app/modules/terminal/components/terminal/terminal.component.scss

NAS-115360 / 22.12 / SCALE WebUI Shell page issues

---

src/app/pages/system/advanced/advanced-settings.component.html
src/app/pages/system/advanced/advanced-settings.component.ts

Removes a block in Advanced Settings.

NAS-115361 / 22.02.1 / NAS-115361: Hiding advanced kernel settings

---

src/app/helptext/system/ca.ts
src/app/pages/credentials/certificates-dash/certificates-dash.component.ts
src/app/pages/credentials/certificates-dash/forms/ca-edit.component.ts
src/app/pages/credentials/certificates-dash/sign-csr-dialog/sign-csr-dialog.component.html
src/app/pages/credentials/certificates-dash/sign-csr-dialog/sign-csr-dialog.component.scss
src/app/pages/credentials/certificates-dash/sign-csr-dialog/sign-csr-dialog.component.spec.ts
src/app/pages/credentials/certificates-dash/sign-csr-dialog/sign-csr-dialog.component.ts
src/app/pages/credentials/credentials.module.ts

Go to Certificates and create a CSR.
Then create a Certificate Authority.
Then use Certificate Authority to sign a CSR. This can be done in the table and by clicking on a CA.

NAS-115551 / 22.12 / NAS-115551: Extract sign CSR into a separate component

---

.github/CODEOWNERS

Manual backport from `origin/master` branch

NAS-115705 / 22.02.1 / Update codeowners

---

src/app/modules/common/topbar/topbar.component.ts

Sentry Issue ID `WEBUI-SCALE-2HN`

NAS-115694 / 22.12 / Fix error and remove one any

---

tests/bdd/conftest.py
tests/bdd/core/test_NAS_T0987.py
tests/bdd/core/test_NAS_T0988.py
tests/bdd/core/test_NAS_T0989.py
tests/bdd/core/test_NAS_T0990.py
tests/bdd/core/test_NAS_T0991.py
tests/bdd/core/test_NAS_T0992.py
tests/bdd/core/test_NAS_T0993.py
tests/bdd/core/test_NAS_T0994.py
tests/bdd/core/test_NAS_T0995.py
tests/bdd/core/test_NAS_T0996.py
tests/bdd/core/test_NAS_T0997.py
tests/bdd/core/test_NAS_T0998.py
tests/bdd/core/test_NAS_T0999.py
tests/bdd/core/test_NAS_T1132.py
tests/bdd/core/test_NAS_T1141.py

Last test results: https://builds.ixsystems.com/job/Test%20development/job/TrueNAS%2013.0%20Nightlies%20CORE%20UI%20Tests%20from%20Branch/112/

DOCS-3483 / 13.0 / Fixed some test issue and improved some testing flow

---

src/app/modules/entity/entity-job/entity-job.component.html
src/app/modules/entity/entity-job/entity-job.component.scss
src/app/modules/entity/entity-job/entity-job.component.ts
src/app/pages/data-protection/cloudsync/cloudsync-list/cloudsync-list.component.ts
src/app/pages/data-protection/components/data-protection-dashboard/data-protection-dashboard.component.ts
src/app/pages/data-protection/replication/replication-list/replication-list.component.ts
src/assets/styles/other/_tn-styles.scss

To test, go to the Data Protection dashboard and run cloud sync or replication tasks from there. After starting the task, click on the state button and the dialog should come up with the loading bar. The dialog should also have logs of the task as it progresses. Real time logs. Then, click on the title and go to the cloud sync and replication tasks dedicated pages. Test the same thing there too.

NAS-115357 / 22.12 / Added logs for replication tasks and cloud sync tasks

---

src/app/pages/reportsdashboard/components/report/report.component.css
src/app/pages/reportsdashboard/components/report/report.component.html
src/app/pages/reportsdashboard/components/report/report.component.ts

NAS-115633 / 13.0 / Network graph: incorrect legend units

---

src/app/modules/common/app-common.module.ts
src/app/modules/common/breadcrumb/breadcrumb.component.ts
src/app/modules/common/layouts/admin-layout/admin-layout.component.html
src/app/modules/common/layouts/admin-layout/admin-layout.component.ts
src/app/modules/common/page-title/page-title.component.html
src/app/modules/common/page-title/page-title.component.ts
src/app/pages/account/users/user-list/user-list.component.html
src/app/pages/account/users/user-list/user-list.component.scss
src/app/pages/account/users/user-list/user-list.component.ts
src/app/pages/account/users/users.module.ts
src/app/services/layout.service.ts
src/app/services/page-title.service.ts
src/app/services/route-parts/route-parts.service.ts

Test the page header for UserListComponent in comparison to the typical headers

NAS-115376 / 22.12 / NAS-115376: Added portals

---

src/app/components/common/dialog/about/about-dialog.component.html
src/app/components/common/dialog/about/about-dialog.component.ts
src/app/components/common/topbar/topbar.component.ts
src/app/core/components/corecomponents.module.ts
src/app/core/components/widgets/widget-help/widget-help.component.html
src/app/core/components/widgets/widget-help/widget-help.component.scss
src/app/core/components/widgets/widget-help/widget-help.component.ts
src/app/core/services/preferences.service.ts
src/app/helptext/about.ts
src/app/pages/dashboard/dashboard.component.ts
src/app/pages/dashboard/dashboard.html
tsconfig.json

This ports dashboard help widget from Scale and removes code that would show About dialog

NAS-115502 / 13.0 / NAS-115502: Help widget

---

src/app/pages/system/advanced/advanced-settings.component.html
src/app/pages/system/advanced/advanced-settings.component.ts

Testing:
System Settings -> Advanced

NAS-115887 / 22.02.1 / No System Dataset Option

---

src/app/pages/account/users/user-form/user-form.component.ts

Testing:
Credentials -> Users -> Edit User

NAS-115665 / 22.02.2 / 13.0 Nightly and Angelfish build in the User Edit UI sometimes the primary group is missing

---

src/app/pages/account/users/user-form/user-form.component.ts

Testing:
Accounts -> Users -> Edit User

NAS-115665 / 13.0 / 13.0 Nightly and Angelfish build in the User Edit UI sometimes the primary group is missing

---

src/app/pages/system/advanced/advanced-settings.component.html
src/app/pages/system/advanced/advanced-settings.component.ts

Testing:
System Settings -> Advanced
Original PR: https://github.com/truenas/webui/pull/6627
Jira URL: https://jira.ixsystems.com/browse/NAS-115887

NAS-115887 / 22.02.1 / No System Dataset Option (by AlexKarpov98)

---

src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
src/app/pages/storage/volumes/zvol/zvol-form/zvol-form.component.ts
src/app/services/storage.service.ts

Similar to previous PR: dataset form and zvol form need testing for record/block size field.

NAS-115713 / 13.0 / NAS-115713: Replacing static recordsizes with api call

---

src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts

Testing:
Storage -> Edit Dataset -> Advanced Options -> Quota critical/warning

NAS-115902 / 22.02.2 / [SCALE] Quota critical/warning alert cannot be 0

---

src/app/pages/common/select-dialog/select-dialog.component.html

Testing: connect to machine in ticket, go to Network -> IPMI, use Identify Light and check that network request is being sent.

NAS-116057 / 13.0 / NAS-116057: Fix IPMI light

---

src/app/views/sessions/signin/signin.component.html
src/app/views/sessions/signin/signin.component.scss

NAS-115421 / 22.12 / NAS-115421: fixed offline page icon

---

src/app/modules/alerts/components/alerts-panel/alerts-panel.component.spec.ts
src/app/modules/alerts/store/alert.reducer.ts

Updated `sortComparer` function by sorting by level, klass, datetime in `alert.reducer.ts`.

NAS-116175 / 22.12 / Show most important alerts first

---

src/app/pages/system/general-settings/support/support.component.ts

Testing: 
System Settings ->  General -> Add License ->  Update License
Fixed object extensible error

NAS-116302 / 22.12 / Broken Update License button

---

src/app/pages/system/certificates/certificate-add/certificate-add.component.ts

NAS-114924 / 13.0 / NAS-114924: Import CSR errors out on passphrase

---

src/app/pages/credentials/certificates-dash/forms/certificate-add.component.ts

git cherry-pick -x 190cdd5899984e44248edd55292cfec6770e0803
Testing - see ticket.
Original PR: https://github.com/truenas/webui/pull/6725
Jira URL: https://jira.ixsystems.com/browse/NAS-114924

NAS-114924 / 22.02.2 / NAS-114924: Import CSR errors out on passphrase (by undsoft)

---

src/app/helptext/system/cloudcredentials.ts
src/app/pages/system/CloudCredentials/cloudcredentials-form/cloudcredentials-form.component.ts

Check that Cloud Credentials form under System has Endpoint field for Microsoft Azure provider and it gets correctly saved.

NAS-115740 / 13.0 / NAS-115740: Azure Custom Endpoint

---

src/app/pages/system/view-enclosure/components/enclosure-disks-mini/enclosure-disks-mini.component.ts

Cherry-picked from https://github.com/truenas/webui/pull/6756

NAS-116609 / 22.12 / add proper strings so enclosure mapping works

---

src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts

Testing:
Storage -> Pool -> Upgrade Pool

NAS-116623 / 13.0 / Pool upgrade error is not displayed

---

src/app/services/locale.service.ts
src/app/services/storage.service.ts

Testing:
Storage -> Snapshots -> Sort by `Date Created`
Changes:
Updated format as matched locale service.

NAS-116585 / 13.0 / Incorrect Sort by Date

---

src/app/interfaces/api-directory.interface.ts
src/app/pages/applications/dialogs/manage-catalog-summary/manage-catalog-summary-dialog.component.html
src/app/pages/applications/dialogs/manage-catalog-summary/manage-catalog-summary-dialog.component.ts

git cherry-pick -x 9f306eed8ab93ef35d35888c7ce50e22e2b5bb45
Go to Apps -> Manage Catalogs. Click on one of the table rows and you should get a pop up that has replaced the `Version` column with `Status` column and shows app status now.
Original PR: https://github.com/truenas/webui/pull/6776
Jira URL: https://jira.ixsystems.com/browse/NAS-116661

NAS-116661 / 22.12 / NAS-116661: Replaced column (by RehanY147)

---

src/app/pages/system/general-settings/support/support.component.ts

Testing: go to the system in the ticket, Settings -> General and observe two serial numbers.
Original PR: https://github.com/truenas/webui/pull/6796
Jira URL: https://jira.ixsystems.com/browse/NAS-116707

NAS-116707 / 22.02.3 / NAS-116707: Showing HA license number (by undsoft)

---

tests/bdd/scale/test_NAS_T1066.py
tests/bdd/scale/test_NAS_T1091.py
tests/bdd/scale/test_NAS_T1237.py
tests/bdd/scale/test_NAS_T1243.py
tests/bdd/scale/test_NAS_T1249.py
tests/bdd/scale/test_NAS_T1256.py

wait_on_element will report true if the element is still in the UI.

DOCS-3832 / 22.02.2 / Replaced wait_on_element to be false with wait_on_element_disappear.

---

src/app/pages/system/general-settings/support/support.component.ts

Testing: Find yourself an R series machine (see comment in ticket) and make sure that Support widget in General Settings also shows a system image.

NAS-116708 / 22.02.3 / NAS-116708: Adding R series images

---

src/app/interfaces/chart-release.interface.ts
src/app/pages/applications/forms/chart-form.component.ts
src/app/pages/applications/forms/chart-wizard.component.ts
src/app/pages/common/entity/entity-form/components/form-explorer/form-explorer.component.html
src/app/pages/common/entity/entity-form/components/form-explorer/form-explorer.component.ts
src/app/pages/common/entity/utils.ts

Let me know if you need info on how to test

NAS-115759 / 22.02.3 / NAS-115759: Handled immutable

---

src/app/modules/ix-tree/directives/ix-tree-node-toggle.directive.ts
src/app/pages/datasets/components/dataset-management/dataset-management.component.html

Like in Chrome Devtools.
For testing open the new Datasets page and try to toggle tree nodes with Alt(Option) key pressed

NAS-116871 / 22.12 / Toggle tree nodes recursively on alt+click

---

tests/bdd/ha-bhyve02/test_NAS_T0945.py
tests/bdd/ha-bhyve02/test_NAS_T0946.py
tests/bdd/ha-bhyve02/test_NAS_T0948.py
tests/bdd/ha-bhyve02/test_NAS_T0949.py
tests/bdd/ha-bhyve02/test_NAS_T0950.py
tests/bdd/ha-bhyve02/test_NAS_T0951.py
tests/bdd/ha-bhyve02/test_NAS_T0952.py
tests/bdd/ha-bhyve02/test_NAS_T0953.py
tests/bdd/ha-bhyve02/test_NAS_T0954.py
tests/bdd/ha-bhyve02/test_NAS_T0955.py
tests/bdd/ha-bhyve02/test_NAS_T0956.py
tests/bdd/ha-bhyve02/test_NAS_T0957.py
tests/bdd/ha-bhyve02/test_NAS_T0958.py
tests/bdd/ha-bhyve02/test_NAS_T0959.py
tests/bdd/ha-bhyve02/test_NAS_T0960.py
tests/bdd/ha-bhyve02/test_NAS_T0961.py
tests/bdd/ha-bhyve02/test_NAS_T0962.py

* Removed wait_on_element mat-spinner progressbar
* Fixed the test changing a the system pool on HA
* Fixed bad xpath in test_NAS_T0961.py
* Changed the wait on progress bar to disappear to 15 seconds
* Change wait mat-progress-bar to disappear to 20 seconds
* added 5 second sleep after HA enable in NAS-T961
* Fixed SSH General Options xpath in test_NAS_T0945.py
* Fixed License save button xpath in test_NAS_T0946.py
* Fixed SSH service xpaths in test_NAS_T0945.py
* Remove looking for badge to go away in test_NAS_T0962.py
* Update the expending user xpath in all the HA test that edit a user
* Updated the User Edit button xpath
* Fixed user drop down verification in some user test.
* Fixed root user drop down
* Fixed "Permit Sudo" xpath
* Added condition to skip greeting if missing
* …

DOCS-3067 / 22.02 / Add HA test changes and fixes

---

src/app/pages/datasets/components/dataset-capacity-management-card/dataset-capacity-management-card.component.html
src/app/pages/datasets/components/dataset-capacity-management-card/dataset-capacity-management-card.component.scss
src/app/pages/datasets/components/dataset-details-card/dataset-details-card.component.html
src/app/pages/datasets/components/dataset-details-card/dataset-details-card.component.scss
src/app/pages/datasets/components/dataset-details-panel/dataset-details-panel.component.scss
src/app/pages/datasets/modules/encryption/components/zfs-encryption-card/zfs-encryption-card.component.html
src/app/pages/datasets/modules/encryption/components/zfs-encryption-card/zfs-encryption-card.component.scss
src/app/pages/datasets/modules/permissions/containers/permissions-card/permissions-card.component.html
src/app/pages/datasets/modules/permissions/containers/permissions-card/permissions-card.component.scss
src/app/pages/datasets/modules/permissions/containers/permissions-card/permissions-card.component.spec.ts
src/app/pages/storage2/components/dashboard-pool/dashboard-pool.component.scss
src/app/pages/storage2/components/zfs-health-card/zfs-health-card.component.html
src/app/pages/storage2/components/zfs-health-card/zfs-health-card.component.scss
src/app/pages/storage2/components/zfs-health-card/zfs-health-card.component.spec.ts
src/app/pages/storage2/modules/devices/components/disk-details-panel/disk-details-panel.component.html
src/app/pages/storage2/modules/devices/components/disk-details-panel/disk-details-panel.component.scss
src/app/pages/storage2/modules/devices/components/disk-info-card/disk-info-card.component.html
src/app/pages/storage2/modules/devices/components/disk-info-card/disk-info-card.component.scss
src/app/pages/storage2/modules/devices/components/hardware-disk-encryption/hardware-disk-encryption.component.html
src/app/pages/storage2/modules/devices/components/hardware-disk-encryption/hardware-disk-encryption.component.scss
src/assets/styles/mixins/buttons.scss
src/assets/styles/mixins/cards.scss

Created `details-cards` and updated `details-card` mixin

NAS-116801 / 22.12 / Standardize the details card styles

---

src/app/pages/applications/applications.component.html
src/app/pages/applications/applications.component.ts

Testing: 
Make sure the **Launch Docker Image** button shows up "launch docker image" UI form, when the **Available Applications** tab is selected, and also when any of the **Installed Applications**, **Manage Catalogs**, or **Manage Docker** Images tabs are selected.

NAS-116837 / 22.02.2.1 / NAS-116837: Fix Launch Docker Image Button disabled and other UI bugs

---

src/app/pages/storage/volumes/volumes-list/volumes-list-table-config.ts
src/app/pages/storage/volumes/volumes-list/volumes-list.component.ts

Testing:
`zpool create -o compatibility=legacy tank /dev/sdx`
where sdx is one of the unused disks.
`zpool export tank`
Import pool via UI, go to cog icon on a pool and select Upgrade pool.

NAS-117038 / 22.02.3 / NAS-117038: Fixing Upgrade Pool menu item

---

src/app/pages/storage/volumes/manager/manager.component.html
src/app/pages/storage/volumes/manager/manager.component.scss
src/app/pages/storage/volumes/manager/manager.component.ts
src/app/pages/storage2/components/manager/manager.component.html
src/app/pages/storage2/components/manager/manager.component.scss
src/app/pages/storage2/components/manager/manager.component.ts

The text is aligned.
Added value total raw data.
Go to Storage -> Create Pool
Check  text "Estimated total raw data capacity:"

NAS-114866 / 22.12 / NAS-114866: Fix text alignment

---

src/app/pages/applications/forms/chart-form/chart-form.component.spec.ts
src/app/pages/applications/forms/chart-form/chart-form.component.ts

Test the PR on the team cloud scale vm. The `home` app on there has the issue mentioned on the ticket. Before the app name wasn't filled in when the app was being edited. That should be fixed.

NAS-116799 / 22.12 / NAS-116799: Fixed release_name

---

src/app/modules/common/app-common.module.ts
src/app/modules/common/dialog/update-dialog/update-dialog.component.html
src/app/modules/common/dialog/update-dialog/update-dialog.component.scss
src/app/modules/common/dialog/update-dialog/update-dialog.component.ts
src/app/modules/common/topbar/topbar.component.ts
src/app/modules/jobs/store/job.selectors.ts

Test the new component UpdateDialogComponent.
During the update, a popup has been added instead of a modal window to display the status of the job.

NAS-116247 / 22.12 / NAS-116247: added update-dialog component

---

src/app/pages/datasets/modules/permissions/components/permissions-item/permissions-item.component.scss
src/app/pages/datasets/modules/permissions/components/view-nfs-permissions/view-nfs-permissions.component.scss
src/app/pages/datasets/modules/permissions/components/view-posix-permissions/view-posix-permissions.component.scss
src/app/pages/datasets/modules/permissions/components/view-trivial-permissions/view-trivial-permissions.component.scss

Datasets (WIP) -> Add datasets
Create Datasets and match the designs for permission cards (NFS, POSIX,)  (see attached screenshots in Jira task
https://ixsystems.atlassian.net/browse/NAS-117016)
Check rows from cards that used in other places.

NAS-117016 / 22.12 / NAS-117016: Match the designs for the Permissions card 

---

src/app/pages/api-keys/components/api-key-list/api-key-list.component.ts
src/app/pages/api-keys/store/api-key.store.ts

Testing: Topbar -> Api Keys -> test table.

NAS-117114 / 22.12 / NAS-117114: Fix loadApiKeys in ApiKeyComponentStore

---

src/app/pages/common/entity/entity-form/models/field-config.interface.ts
src/app/pages/storage/volumes/permissions/containers/dataset-acl-editor/dataset-acl-editor.component.html
src/app/pages/storage/volumes/permissions/containers/dataset-acl-editor/dataset-acl-editor.component.scss
src/app/pages/storage/volumes/permissions/containers/dataset-acl-editor/dataset-acl-editor.component.spec.ts
src/app/pages/storage/volumes/permissions/containers/dataset-acl-editor/dataset-acl-editor.component.ts
src/app/pages/storage/volumes/permissions/interfaces/dataset-acl-editor-state.interface.ts
src/app/pages/storage/volumes/permissions/stores/dataset-acl-editor.store.ts

Testing: create a dataset, go to View Permissions, Set ACL, observe new Apply User and Apply Group checkboxes.
Check that they work.

NAS-112618 / 22.02.3 / NAS-112618: Adds Apply User/Group checkboxes to ACL editor

---

src/app/pages/storage2/components/disk-health-card/disk-health-card.component.ts

**Testing** 
Emulate error response for "disk.temperatures" (by hard-coding)

NAS-117423 / 22.12 / NAS-117423: Catching error when calling "disk.temperatures" fails

---

tests/bdd/scale/test_NAS_T1134.py
tests/bdd/scale/test_NAS_T1241.py

https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Stable/job/Test%20development/job/UI%20Tests%20-%20TrueNAS%20SCALE%20Angelfish%20from%20branch/83/

DOCS-4081 / 22.02.4 / Added Apply to User and Group checkbox click in test_NAS_T1134.py

---

src/app/pages/sharing/iscsi/target/target-form/target-form.component.html
src/app/pages/sharing/iscsi/target/target-form/target-form.component.spec.ts
src/app/pages/sharing/iscsi/target/target-form/target-form.component.ts

**Testing**
Sharing > iSCSI targets > Create iSCSI target. 
Please see bug report in the ticket

NAS-117259 / 22.12 / NAS-117259: Fix iscsi target package creation

---

src/app/pages/data-protection/replication/replication-wizard/replication-wizard.component.ts
src/app/pages/storage2/modules/devices/components/devices/devices.component.ts

Testing: go to Data Protection, try to create a replication task, but make request fail (for example by changing something in code).
Check that there are no unexpected errors in the console and that there are no new periodic snapshot tasks.

NAS-117249 / 22.12 / NAS-117249: Fixing errors in replication tasks

---

src/app/pages/storage2/components/pools-dashboard/pool-usage-card/pool-usage-card.component.html

**Testing**
On **Storage** (/storage2), click **Manage Datasets**. URL previously was changing to http://localhost:4200/datasets/ . 
I've changed the code, so that URL would contain the name of the pool:
http://localhost:4200/datasets/[pool name]

NAS-117540 / 22.12 / NAS-117540: Select the correct pool on datasets page

---

src/app/pages/datasets/components/dataset-management/dataset-management.component.scss
src/app/pages/storage2/modules/devices/components/devices/devices.component.scss

Brings bar loading progress bar to new storage pages.

NAS-117558 / 22.12 / NAS-117558: Restores loading indicator on storage pages

---

src/app/pages/datasets/modules/permissions/containers/permissions-card/permissions-card.component.html
src/app/pages/datasets/modules/permissions/containers/permissions-card/permissions-card.component.scss
src/app/pages/datasets/modules/permissions/containers/permissions-card/permissions-card.component.ts
src/app/pages/datasets/modules/permissions/permissions.module.ts
src/app/pages/storage2/components/dashboard-pool/dashboard-pool.component.html

Check the skeleton-loader in Permissions card (in storage2 module).

NAS-117119 / 22.12 / NAS-117119: Change loading animation in permissions card

---

package.json
proxy.config.json.skel
src/app/helptext/system/support.ts
src/app/pages/common/entity/entity-form/components/dynamic-field/dynamic-field.directive.ts
src/app/pages/common/entity/entity-form/components/form-oauth-login/form-oauth-login.component.html
src/app/pages/common/entity/entity-form/components/form-oauth-login/form-oauth-login.component.scss
src/app/pages/common/entity/entity-form/components/form-oauth-login/form-oauth-login.component.ts
src/app/pages/common/entity/entity.module.ts
src/app/pages/system/support/fn-support/fn-support.component.ts
src/app/pages/system/support/support.component.ts

Testing: Go to System -> Support and use form to submit a ticket.

NAS-117433 / 13.0 / NAS-117433: Jira Oauth support

---

src/app/pages/storage2/components/pools-dashboard/pool-usage-card/pool-usage-card.component.html
src/app/pages/storage2/components/pools-dashboard/pool-usage-card/pool-usage-card.component.spec.ts
src/app/pages/storage2/components/pools-dashboard/pool-usage-card/pool-usage-card.component.ts

For testing, go to Storage and click on `View Disk Space Reports` link on the `Pool Usage` card

NAS-117596 / 22.12 / Redirect to Disks Reports with pre-selected disks

---

src/app/pages/datasets/components/dataset-management/dataset-management.component.ts

NAS-117539 / 22.12 / NAS-117539: Select first row in Datasets on load

---

src/app/pages/data-protection/cloudsync/cloudsync-list/cloudsync-list.component.ts
src/app/pages/data-protection/data-protection.routing.ts
src/app/pages/data-protection/replication/replication-list/replication-list.component.ts
src/app/pages/data-protection/rsync-task/rsync-task-list/rsync-task-list.component.ts
src/app/pages/data-protection/snapshot/snapshot-list/snapshot-list.component.ts
src/app/pages/datasets/components/data-protection-card/data-protection-card.component.html
src/app/pages/datasets/modules/snapshots/snapshot-list/snapshot-list.component.spec.ts
src/app/pages/datasets/modules/snapshots/snapshot-list/snapshot-list.component.ts
src/app/pages/datasets/modules/snapshots/snapshots.routing.ts

**Testing:**
Datasets => Data Protection Card
- Manage Snapshots
- Manage Snapshot Tasks
- Manage Replication Tasks
- Manage Cloud Sync Tasks
- Manage Rsync Tasks
Check for those 5 links.
The list on the routed page is based on the chosen dataset.

NAS-117573 / 22.12 / NAS-117573: Pre-filter data protection items when clicking on Manage links

---

src/app/pages/storage2/components/manager/vdev/vdev.component.ts

**Testing:**
Go to Storage → Manage Devices → Add Vdev
**Notes:**
This one-liner fixes 1st issue, 2nd issue and 3rd issue as well. Strict check of `undefined` is enough, as `null`s won't break the code.

NAS-117594 / 22.12 / NAS-117594: Fix 'Add VDev' form bug

---

src/app/pages/storage/storage.routing.ts

NAS-117607 / 22.02.4 / NAS-117607: Renaming breadcrumbs

---

src/app/pages/datasets/components/dataset-management/dataset-management.component.html
src/app/pages/datasets/components/dataset-management/dataset-management.component.ts
src/app/pages/datasets/datasets.module.ts
src/app/pages/storage2/components/pools-dashboard/pools-dashboard.component.html
src/app/pages/storage2/components/pools-dashboard/pools-dashboard.component.ts
src/app/pages/storage2/components/unused-resources/unused-resources.component.html

**Testing:**
Go to `Storage` page
See ticket description.

NAS-117718 / 22.12 / NAS-117718: No pools message flashing when switching to Storage

---

src/app/interfaces/api-key.interface.ts
src/app/pages/api-keys/api-keys.component.ts

Testing: See ticket description.

NAS-117713: Specify allowlist explicitly when creating an API key

---

src/app/modules/entity/entity-table/entity-table-add-actions/entity-table-add-actions.component.html
src/app/modules/entity/entity-table/entity-table-add-actions/entity-table-add-actions.component.ts

**Testing:**
See the ticket description

NAS-117768 / 22.12 / NAS-117768: undefined in filter box on some pages

---

src/app/interfaces/api-key.interface.ts
src/app/pages/api-keys/components/api-key-form-dialog/api-key-form-dialog.component.spec.ts
src/app/pages/api-keys/components/api-key-form-dialog/api-key-form-dialog.component.ts

NAS-117713 / 22.12 / NAS-117713: Specify allowlist explicitly when creating an API key

---

src/app/pages/storage2/components/pools-dashboard/pools-dashboard.component.html

NAS-117820: Temporarily hides unused resources card
NAS-117819: Adds Disks button on Storage dashboard

NAS-117820 / 22.12 / NAS-117820: Storage hotfixes

---

src/app/pages/dashboard/components/dashboard/dashboard.component.ts
src/app/store/preferences/preferences.reducer.ts
src/app/store/preferences/preferences.selectors.ts

Testing: 
1. In shell `midclt call user.pop_attribute 1 dashState`
2. Refresh page. 
3. Go to dashboard and test it.

NAS-117803 / 22.12 / NAS-117803: Fixes empty dashboard on first login

---

src/app/interfaces/application.interface.ts
src/app/pages/applications/applications.component.html
src/app/pages/applications/applications.component.ts
src/app/pages/applications/catalog/catalog.component.ts
src/app/pages/applications/chart-releases/chart-releases.component.ts

**Testing**
1. Go to **Apps** page  > **Launch Docker Image**
2. See bug description in the ticket

NAS-117581 / 22.12 / NAS-117581: Fix Launch Docker Image button bugs

---

src/app/modules/ix-icon/ix-icon.component.ts
src/app/pages/datasets/components/dataset-icon/dataset-icon.component.html
src/app/pages/datasets/components/dataset-icon/dataset-icon.component.ts

**Testing**
1. Datasets > choose a dataset. This should result in a change of an icon positioned "Details for" at the details section.
2. Refresh page, and choose another node of datasets tree. This should result in another change of an icon.

NAS-117680 / 22.12 / NAS-117680: update ix-icon for dataset details

---

src/app/pages/vm/vm-form/vm-form.component.ts

**Testing:**
Virtualization => Create VM => Edit
See the ticket description.

NAS-117688 / 22.12 / NAS-117688: Cannot Edit VMs on bluefin

---

src/app/pages/vm/vm-form/vm-form.component.ts

**Testing:**
Virtualization => Create VM => Edit
See the ticket description.

NAS-117688 / 22.02.4 / NAS-117688: Cannot Edit VMs

---

src/app/components/common/notifications/notifications.component.css
src/app/components/common/notifications/notifications.component.html
src/app/components/common/notifications/notifications.component.ts
src/app/services/notifications.service.ts

Testing: 
Find an HA machine in Core Jenkins (for example,  under HA API tests), see that controller is specified in Alerts.
Compare with a normal machine, where controller is not specified.

NAS-117897 / 13.0 / NAS-117897: Showing controller in alerts

---

src/app/modules/alerts/components/alert/alert.component.html
src/app/modules/alerts/components/alert/alert.component.scss
src/app/modules/alerts/components/alert/alert.component.spec.ts
src/app/modules/alerts/components/alert/alert.component.ts
src/app/modules/alerts/components/alert/alert.page-object.ts
src/app/modules/alerts/components/alerts-panel/alerts-panel.component.html
src/app/modules/alerts/components/alerts-panel/alerts-panel.component.spec.ts
src/app/modules/alerts/components/alerts-panel/alerts-panel.component.ts

Testing: check alerts panel on an HA system and not. Observe that HA systems have controller listed.

NAS-117897 / 22.12 / NAS-117897: Showing controller in alerts

---

src/app/modules/ix-forms/services/ix-validators.service.spec.ts
src/app/modules/ix-forms/services/ix-validators.service.ts
src/app/pages/services/components/service-smb/service-smb.component.ts
src/app/pages/system/alert-service/alert-service/alert-services/telegram-service/telegram-service.component.ts
src/app/pages/system/file-ticket/file-ticket-licensed-form/file-ticket-licensed-form.component.ts

Inverts logic for customValidator (felt more natural this way) and adds unit tests.

NAS-117945 / 22.12 / NAS-117945: Inverts customValidator

---

src/app/core/components/directives/details-height/details-height.directive.ts
src/app/pages/datasets/components/dataset-management/dataset-management.component.html
src/app/pages/datasets/components/dataset-management/dataset-management.component.ts
src/app/pages/storage2/modules/devices/components/devices/devices.component.html
src/app/pages/storage2/modules/devices/components/devices/devices.component.ts

Changes:
- Clean up interface of `ixDetailsHeight` directive
- Accept parent container class in `ixDetailsHeight="parent-class"`
- Move `headerHeight`, `footerHeight`, `hasConsoleFooter` inside directive

NAS-117973 / 22.12 / Simplify ixDetailsHeight

---

src/assets/styles/mixins/cards.scss

For testing please check original ticket

NAS-117427 / 22.12 / Fix out of bounds text for the new disks and datasets page

---

.github/workflows/main.yml

NAS-118053 / 22.12 / NAS-118053: Fixing CI in master

---

src/app/interfaces/vm-form-values.interface.ts
src/app/pages/vm/vm-wizard/vm-wizard.component.ts

git cherry-pick -x 70dc0e26bdcbc07725fbfc5dffa2b5315c4fb197
Original PR: https://github.com/truenas/webui/pull/7058
Jira URL: https://ixsystems.atlassian.net/browse/NAS-117853

NAS-117853 / 22.02.4 / NAS-117853: Not adding path when `create_zvol` flag is set to `true` (by RehanY147)

---

src/app/pages/datasets/components/dataset-management/dataset-management.component.scss
src/app/pages/datasets/components/dataset-node/dataset-node.component.scss

NAS-118071 / 22.12 / Fix expand button indentation on datasets tree

---

src/app/modules/common/layouts/admin-layout/admin-layout.component.ts

For testing please check the original ticket

NAS-117959 / 22.12 / Set user selected language for UI after page reloading

---

.browserslistrc
src/app/pages/datasets/components/dataset-details-panel/dataset-details-panel.component.scss
src/assets/styles/other/_egret_overrides.scss

NAS-100748 / 22.12 / NAS-100748: Adding browserslistrc

---

src/app/pages/applications/forms/chart-form/chart-form.component.ts
src/app/services/app-schema.service.spec.ts
src/app/services/app-schema.service.ts

Fix for a bug when user clicks **Edit** and array fields are empty.
For testing, please see example in the ticket

NAS-117953 / 22.12 / NAS-117953: Add 'serializeConfig' method

---

src/app/pages/applications/applications.component.ts
src/app/pages/applications/catalog/catalog.component.ts
src/app/pages/applications/chart-releases/chart-releases.component.ts
src/app/pages/applications/common-apps-toolbar-buttons/common-apps-toolbar-buttons.component.ts

On **Apps** page, for the first time (when pool is not set), 
- Expected Result: user should be sent to the **Available Applications** tab and **Choose a pool for Apps** popup should be displayed

NAS-117875 / 22.12 / NAS-117875: redirect user to Available Applications if pool is not chosen

---

tests/bdd/core/test_NAS_T1128.py
tests/bdd/core/test_NAS_T1132.py
tests/bdd/core/test_NAS_T1135.py
tests/bdd/core/test_NAS_T1136.py
tests/bdd/core/test_NAS_T1140.py
tests/bdd/core/test_NAS_T1141.py
tests/bdd/core/test_NAS_T1143.py

Test results: https://builds.ixsystems.com/job/Test%20development/job/TrueNAS%2013.0%20Internal%20CORE%20UI%20Tests%20from%20Branch%20with%20markers/118/

AUTO-226 / 13.0 / Fixed wait xpath at the Backblaze login

---

src/app/helptext/system/cloudcredentials.ts
src/app/pages/system/CloudCredentials/cloudcredentials-form/cloudcredentials-form.component.ts

git cherry-pick -x 541fac78869a28b8fd09a9bf3c5d6aa5f53e4f13
1. Adds support for storj provider.
2. Defaults cloudsync form to storj
Original PR: https://github.com/truenas/webui/pull/7083
Jira URL: https://ixsystems.atlassian.net/browse/NAS-117827

NAS-117827 / 13.0 / NAS-117827: Adding Storj cloudsync provider (by undsoft)

---

src/app/pages/dashboard/components/widget-network/widget-network.component.ts
src/app/pages/dashboard/components/widget-nic/widget-nic.component.ts

If you use local host with the m40 instance we have, the dashboard crahes. This PR fixes that.

NAS-118167 / 22.12 / NAS-118167: Removed check

---

src/app/pages/applications/select-pool-dialog/select-pool-dialog.component.spec.ts
src/app/pages/applications/select-pool-dialog/select-pool-dialog.component.ts
src/app/pages/dashboard/components/widget-storage/widget-storage.component.html

StorageOldModule -> `/storage-old/manager/`
StorageModule -> `/storage/create`

NAS-118184 / 22.12 / Fix link to create a new pool

---

src/app/modules/charts/components/view-chart-gauge/view-chart-gauge.component.ts
src/app/pages/dashboard/components/widget-cpu/widget-cpu.component.html
src/app/pages/dashboard/components/widget-cpu/widget-cpu.component.ts

**Testing**
Check **CPU Widget**  in Safari. See ticket for details

NAS-117986 / 22.12 / NAS-117986: fix DOM not updated properly in Safari for gauge chart

---

src/app/interfaces/rsync-task.interface.ts
src/app/modules/ix-forms/components/ix-fieldset/ix-fieldset.component.scss
src/app/pages/data-protection/rsync-task/rsync-task-form/rsync-task-form.component.spec.ts
src/app/pages/data-protection/rsync-task/rsync-task-form/rsync-task-form.component.ts

Testing: create and edit rsync task in SSH mode and experiment with `Connect using` dropdown.

NAS-118169 / 22.12 / NAS-118169: Fixes SSH connection field when editing an rsync task form

---

src/app/constants/toggle-menu-duration.ts
src/app/pages/reports-dashboard/components/report/report.component.ts

For testing go to Reporting page and toggle sidebar menu

NAS-118165 / 22.12 / Resize chart on sidebar toggle

---

src/app/pages/system/bootenv/bootenv-list/bootenv-list.component.html
src/app/pages/system/bootenv/bootenv-list/bootenv-list.component.scss
src/app/pages/system/bootenv/bootenv-list/bootenv-list.component.spec.ts

Updated **KEEP** row to look like this:

NAS-118260 / 22.12 / Boot ENV keep table row fix

---

debian/rules

Removes references to removed file.

NAS-118324 / 22.12 / Fix build

---

src/app/modules/common/search-input/search-input.component.html
src/app/modules/common/search-input/search-input.component.scss
src/app/modules/common/search-input/search-input.component.ts
src/app/modules/ix-tree/utils/flattern-tree-with-filter.ts
src/app/pages/datasets/components/dataset-management/dataset-management.component.html
src/app/pages/datasets/components/dataset-management/dataset-management.component.ts
src/app/pages/storage/modules/devices/components/devices/devices.component.html

Fixed:
- Disabled state for dataset input (if no initial data is present)
- Handling initial data correctly (with action if not disabled and has initial value)
- Added debounceTime logic on `(input)` to improve performance
- Fixed dataset search logic to return only needed data
- Small refactoring

NAS-118282: Search input fixes for datasets and generally

---

src/app/modules/entity/entity-empty/entity-empty.component.html
src/app/modules/entity/entity-empty/entity-empty.component.scss
src/app/modules/entity/entity-table/entity-table.component.html
src/app/modules/entity/table/expandable-table/expandable-table.component.scss
src/app/modules/ix-forms/components/ix-radio-group/ix-radio-group.component.scss
src/app/pages/account/groups/group-list/group-list.component.html
src/app/pages/account/users/user-list/user-list.component.html
src/app/pages/dashboard/components/widget-cpu/widget-cpu.component.html
src/app/pages/dashboard/components/widget-memory/widget-memory.component.html
src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.html
src/app/pages/datasets/components/dataset-quotas/dataset-quotas-grouplist/dataset-quotas-grouplist.component.html
src/app/pages/datasets/components/dataset-quotas/dataset-quotas-userlist/dataset-quotas-userlist.component.html
src/app/pages/datasets/modules/snapshots/snapshot-list/snapshot-list.component.html
src/app/pages/services/services.component.html
src/assets/styles/other/_tn-styles.scss

Made spinners smaller (giant ones)
Improved radio group & tooltip icon positioning (centered)
Fixed slide toggle (bar color by default, not primary color, so it is a bit lighter that then circle)

NAS-118335: Improved spinners & some UI elements

---

src/app/pages/datasets/components/dataset-capacity-management-card/space-management-chart/space-management-chart.component.html

Check Dataset Space Management (card). The colour swatches must match the colours on the chart

NAS-118411 / 22.12 / Added style colour for chart swatch

---

src/app/pages/datasets/components/dataset-details-panel/dataset-details-panel.component.html
src/app/pages/datasets/components/dataset-node/dataset-node.component.html
src/app/pages/datasets/components/dataset-node/dataset-node.component.scss
src/assets/styles/other/_fn-styles.scss

https://user-images.githubusercontent.com/22980553/193791390-3ead9c86-7edf-4458-ada1-36c16e28740e.mov

NAS-118349 / 22.12 / Datasets long name fix

---

src/app/pages/storage/modules/disks/components/replace-disk-dialog/replace-disk-dialog.component.spec.ts
src/app/pages/storage/modules/disks/components/replace-disk-dialog/replace-disk-dialog.component.ts

Adding serial size made the string too long. There's the exported pools there too where applicable.

NAS-116537 / 22.12 / Added disk size

---

src/app/modules/entity/entity-empty/entity-empty.component.html
src/app/modules/entity/entity-empty/entity-empty.component.ts
src/app/pages/reports-dashboard/components/line-chart/line-chart.component.ts
src/app/pages/reports-dashboard/components/report/report.component.html
src/app/pages/reports-dashboard/components/report/report.component.ts

Add error handler for Failed Export
For testing, use the host from the ticket description

NAS-118423 / 22.12 / Better error handling for Reports

---

src/app/modules/entity/entity-empty/entity-empty.component.html
src/app/modules/entity/entity-empty/entity-empty.component.ts
src/app/pages/reports-dashboard/components/line-chart/line-chart.component.ts
src/app/pages/reports-dashboard/components/report/report.component.html
src/app/pages/reports-dashboard/components/report/report.component.ts

Add error handler for Failed Export
For testing, use the host from the ticket description
Original PR: https://github.com/truenas/webui/pull/7162
Jira URL: https://ixsystems.atlassian.net/browse/NAS-118423

NAS-118423 / 22.12-BETA.2 / Better error handling for Reports (by denysbutenko)

---

src/app/modules/ix-forms/components/ix-explorer/ix-explorer.component.html
src/app/modules/ix-forms/components/ix-explorer/ix-explorer.component.scss
src/app/modules/ix-forms/components/ix-explorer/ix-explorer.component.spec.ts
src/app/modules/ix-forms/components/ix-explorer/ix-explorer.component.ts
src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.html

backported fixes for `ix-explorer`
Original PR: https://github.com/truenas/webui/pull/7171
Jira URL: https://ixsystems.atlassian.net/browse/NAS-118471

NAS-118471 / 22.12-BETA.2 / delete odd label (by bvasilenko)

---

src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts

Testing:
1. Create AWS S3 credential at **Credentials -> Backup Credentials** make sure you set proper permissions for your credentials to retrieve list of buckets from your S3 
2. **Data Protection -> Cloud Sync Tasks -> Add** , select your S3 credential
3.  Open **Bucket** dropdown
**Expected result:** options of **Bucket** contains list of buckets from your S3

NAS-118472 / 22.12 / Display buckets after S3 credentials are selected

---

src/app/core/services/disk-temperature.service.ts
src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks-mini.component.html
src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.ts

Need  Mini E/X/X+/XL
Go to System -> View Enclosure
Check the Drive Temperatures list display

NAS-117869 / 13.0 / NAS-117869 - Fixed disk temperature display

---

src/app/modules/ix-forms/components/ix-explorer/ix-explorer.component.ts
src/app/modules/layout/components/breadcrumb/breadcrumb.component.html
src/app/modules/layout/components/breadcrumb/breadcrumb.component.ts
src/app/pages/datasets/components/dataset-form/dataset-form.component.ts
src/app/pages/datasets/modules/permissions/components/acl-editor-list/acl-editor-list.component.html
src/app/pages/datasets/modules/permissions/components/acl-editor-list/acl-editor-list.component.ts
src/app/pages/datasets/modules/permissions/components/view-nfs-permissions/view-nfs-permissions.component.ts
src/app/pages/datasets/modules/permissions/containers/dataset-acl-editor/dataset-acl-editor.component.html
src/app/pages/datasets/modules/permissions/containers/dataset-acl-editor/dataset-acl-editor.component.ts
src/app/pages/datasets/modules/permissions/containers/permissions-card/permissions-card.component.ts
src/app/pages/datasets/modules/permissions/stores/dataset-acl-editor.store.ts
src/app/pages/sharing/components/shares-dashboard/shares-dashboard.component.ts
src/app/pages/sharing/smb/smb-acl/smb-acl.component.ts
src/app/pages/sharing/smb/smb-form/smb-form.component.spec.ts
src/app/pages/sharing/smb/smb-form/smb-form.component.ts
src/app/services/route-parts/route-parts.service.ts

Fixed breadcrumbs logic, ACL bugs, Redirects to ACL

NAS-118454 / 22.12-BETA.2 / Go To ACL Manager After Adding SMB Type Dataset of an SMB Dataset Goes to Main Dashboard Not ACL Manager

---

.github/workflows/main-release-engineering.yml

No review is necessary, as I need to merge to make sure it works.

NAS-118542 / 22.12 / Do not require status checks for PRs from RE team

---

src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts

Testing:
1. Create AWS S3 credential at **Credentials -> Backup Credentials** make sure you set proper permissions for your credentials to retrieve list of buckets from your S3 
2. **Data Protection -> Cloud Sync Tasks -> Add** , select your S3 credential
3.  Open **Bucket** dropdown
**Expected result:** options of **Bucket** contains list of buckets from your S3
Original PR: https://github.com/truenas/webui/pull/7183
Jira URL: https://ixsystems.atlassian.net/browse/NAS-118472

NAS-118472 / 22.12-BETA.2 / Display buckets after S3 credentials are selected (by bvasilenko)

---

src/app/interfaces/cloudsync-credential.interface.ts
src/app/interfaces/option.interface.ts
src/app/modules/ix-forms/components/ix-select/ix-select.component.html
src/app/modules/ix-forms/components/ix-select/ix-select.component.spec.ts
src/app/modules/ix-forms/components/ix-select/ix-select.component.ts
src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts
src/assets/styles/other/_tn-styles.scss

1. Add a Storj cloudsync provider.
2. Go to Cloudsync form and select newly created provider.
3. You may need to mock to see that items in select may become disabled based on Enabled property.

NAS-118546 / 22.12 / Allowing some of cloudsync buckets to be disabled

---

src/app/pages/task-calendar/cloudsync/cloudsync-form/cloudsync-form.component.ts

1. Add a Storj cloudsync provider.
2. Go to Cloudsync form and select newly created provider.
3. You may need to mock to see that items in select may become disabled based on `Enabled` property.

NAS-118546 / 13.0 / Disable some cloud sync buckets

---

tests/bdd/conftest.py
tests/bdd/ha-bhyve02/function.py
tests/bdd/ha-bhyve02/test_NAS_T0977.py

This test have been fixed to test iscsi share connection on HA. I fixed Initiators Group step and added code to make sure that se can connect with the proper Initiators setting
I improved the ssh_cmd and added stderr to it.

AUTO-231 / 13.0 / Fixed, improved and expended NAS-T977 to verify that iSCSI works on HA

---

src/app/pages/storage/components/manager/manager.component.html
src/app/pages/storage/components/manager/manager.component.scss
src/app/pages/storage/components/manager/vdev/vdev.component.html
src/app/pages/storage/components/manager/vdev/vdev.component.scss

This PR cleans up some css and markup items on branch NAS-116562

NAS-116562 / None / CSS fixes

---

src/app/pages/system/advanced/advanced-settings.component.ts

go to http://localhost:4200/system/advanced
There you should no longer see duplicated cards.

NAS-118530 / 22.12-RC.1 / Advanced system settings, a few boxes appear twice

---

src/app/core/classes/hardware/r50bm.ts
src/app/core/classes/system-profiler.ts
src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks-mini.component.html
src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.html
src/app/pages/system/viewenclosure/enclosure-disks/enclosure-disks.component.ts

Check out ticket description for testing

NAS-118505 / 13.0 / Added r50bm

---

src/app/pages/applications/forms/chart-form/chart-form.component.ts

**Testing**
Go to **Apps**  page and make sure that apps can be installed and edited without errors:
- pihole

NAS-118662 / 22.12 / refactoring for Chart Form

---

src/app/pages/datasets/components/dataset-details-panel/dataset-details-panel.component.scss
src/app/pages/datasets/components/dataset-management/dataset-management.component.scss
src/app/pages/storage/components/manager/manager.component.scss
src/app/pages/storage/modules/devices/components/devices/devices.component.scss
src/app/pages/storage/modules/devices/components/disk-details-panel/disk-details-panel.component.scss
src/assets/styles/mixins/cards.scss

Test with datasets | devices side columns on any screen size.

NAS-118492 / 22.12 / Datasets detail cards should realign to fill horizontal space first

---

src/app/directives/common/common-directives.module.ts
src/app/directives/common/if-nightly.directive.ts/if-nightly.directive.ts
src/app/pages/dashboard/components/dashboard/dashboard.component.html

Testing: there is a test button on main dashboard that should only be visible on nightlies.

NAS-118768 / 22.12 / Directive to show UI elements on nightlies only

---

src/app/enums/failover-disabled-reason.enum.ts
src/app/helptext/topbar.ts

See https://github.com/truenas/middleware/pull/10052 for details

NAS-118847 / 22.12 / add new failover.disabled.reasons

---

src/app/pages/applications/applications.module.ts
src/app/pages/applications/chart-releases/chart-releases.component.ts
src/app/pages/applications/dialogs/pod-select/pod-select-dialog.component.html
src/app/pages/applications/dialogs/pod-select/pod-select-dialog.component.spec.ts
src/app/pages/applications/dialogs/pod-select/pod-select-dialog.component.ts
src/app/pages/applications/enums/pod-select-dialog.enum.ts

**Testing**
Optionally, you can use mockup response of `chart.release.pod_console_choices`:
```
{
"storj2-68bf795df7-fb56g": [
"storj"
]
}
```

NAS-118669 / 22.12 / Extract dialogs from ChartReleasesComponent

---

tests/bdd/conftest.py
tests/bdd/ha-bhyve02/function.py
tests/bdd/ha-bhyve02/test_NAS_T0965.py
tests/bdd/ha-bhyve02/test_NAS_T1117.py
tests/bdd/ha-bhyve02/xpaths.py

This is a clean up the original work I did last week the other branch was messy so I cherry pick only the relevant changes to this new branch.
here is test results for this branch https://builds.ixsystems.com/job/Test%20development/job/TrueNAS%2013.0%20Internal%20HA%20UI%20Tests%20from%20branch/147/

Auto-290 / Adding NIS test case to verify it still work after failover

---

tests/bdd/bluefin/t_001_12_change_permissions_on_user_home_dir.py
tests/bdd/bluefin/t_001_13_user_ssh_key.py
tests/bdd/bluefin/t_001_2_change_user_shell.py
tests/bdd/bluefin/t_001_3_enable_permit_sudo.py
tests/bdd/bluefin/t_001_4_add_email.py
tests/bdd/bluefin/t_001_5_add_root_group.py
tests/bdd/bluefin/t_001_6_add_home_dir.py
tests/bdd/bluefin/t_001_7_disable_pass.py
tests/bdd/bluefin/t_001_8_enable_pass.py
tests/bdd/bluefin/t_002_4_enabling_sudo_for_group.py
tests/bdd/bluefin/t_004_12_create_second_user_for_smb_share.py
tests/bdd/bluefin/t_004_13_create_wheel_dataset.py
tests/bdd/bluefin/t_004_15_create_ericbsd_dataset.py
tests/bdd/bluefin/t_004_16_create_ericbsd_smb_share.py
tests/bdd/bluefin/t_004_17_create_zvol_for_iscsi.py
tests/bdd/bluefin/t_004_18_kerberos_keytab.py
tests/bdd/bluefin/t_004_19_recursive_and_transverse_acls.py
tests/bdd/bluefin/t_004_3_setup_ad.py
tests/bdd/bluefin/t_004_9_setup_ldap.py
tests/bdd/bluefin/t_006_1_apps_page_validation.py
tests/bdd/bluefin/test_004_0_storage_tests.py

Tests Passing: https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/Test%20development/job/UI%20Tests%20-JT-%20TrueNAS%20Bluefin%20Nightly%20from%20a%20dev%20branch/91

Auto-129  WebUI Test Updates

---

src/app/helptext/storage/volumes/manager/manager.ts
src/app/pages/datasets/components/dataset-details-panel/dataset-details-panel.component.scss
src/app/pages/datasets/modules/permissions/containers/dataset-acl-editor/dataset-acl-editor.component.html
src/app/pages/storage/components/manager/manager.component.html
src/app/pages/storage/components/manager/manager.component.ts
src/app/pages/storage/components/manager/repeat-vdev-dialog/repeat-vdev-dialog.component.html
src/app/pages/storage/components/manager/repeat-vdev-dialog/repeat-vdev-dialog.component.scss
src/app/pages/storage/components/manager/repeat-vdev-dialog/repeat-vdev-dialog.component.ts
src/app/pages/storage/modules/devices/components/disk-details-panel/disk-details-panel.component.scss
src/app/pages/storage/storage.module.ts

Also fixes URL in ACL editor.
Testing: test dialog that appears after Repeat button in pressed when creating a pool.

NAS-119027 / 22.12 / Extracting dialog in Pool Manager

---

src/app/pages/dashboard/components/widget-network/widget-network.component.ts

NAS-119052 / 22.12 / Fix Network Card Statistics

---

tests/install.exp

Also made sure that it is still compatible with the previous version of SCALE.
Replaced FreeNAS with TrueNAS and removed CORE code from the install script

Adding changes for root less in install expect script.

---

src/app/pages/datasets/modules/permissions/containers/permissions-card/permissions-card.component.html
src/app/pages/datasets/modules/permissions/containers/permissions-card/permissions-card.component.scss

Fixed:
https://user-images.githubusercontent.com/22980553/203523917-1b6945fb-4d07-442a-acf2-eb25271da06e.mov

NAS-119099 / 22.12 / Loading indicator in permissions card appears outside of the card

---

src/app/modules/entity/entity-form/components/form-chip/form-chip.component.ts
src/app/modules/entity/entity-form/validators/ip-validation.ts
src/app/modules/ix-forms/components/ix-combobox/ix-combobox.component.ts
src/app/modules/ix-forms/components/ix-file-input/ix-file-input.component.ts
src/app/modules/ix-forms/components/ix-input/ix-input.component.ts
src/app/modules/ix-forms/components/ix-select/ix-select.component.ts
src/app/modules/ix-forms/components/ix-textarea/ix-textarea.component.ts
src/app/pages/applications/forms/chart-form/chart-form.component.spec.ts
src/app/pages/applications/forms/chart-form/chart-form.component.ts
src/app/pages/datasets/components/dataset-form/name-length-validation.ts
src/app/views/sessions/signin/signin.component.ts

When new app form is opened, name now defaults to chart name.
Other minor code fixes.

NAS-113376 / 22.12 / Default app name to chart name

---

src/app/interfaces/api-directory.interface.ts
src/app/interfaces/tunable.interface.ts
src/app/pages/system/tunable/tunable-form/tunable-form.component.spec.ts
src/app/pages/system/tunable/tunable-form/tunable-form.component.ts

Go to System Settings -> Advanced and add an item to sysctl.
You can use `vm.laptop_mode` for variable name.
Then edit the entry that was created.

NAS-119022 / 22.12 / Fix sysctl editing

---

src/app/modules/entity/entity-table/entity-table-row-details/entity-table-row-details.component.ts

NAS-119116 / 22.12 / VM CPU info is N/A

---

.github/workflows/main.yml
src/app/pages/sharing/iscsi/initiator/initiator-form/initiator-form.component.ts

No review necessary, will merge after build completes.

NAS-119168 / 22.12 / Switch codecov to use token

---

src/app/app.module.ts

Enables this https://angular.io/guide/lazy-loading-ngmodules#preloading-modules for better UX after login.

NAS-119167 / 23.10 / Module preloading

---

src/app/modules/layout/components/admin-layout/admin-layout.component.scss
src/app/pages/datasets/modules/permissions/containers/dataset-trivial-permissions/dataset-trivial-permissions.component.html
src/app/pages/datasets/modules/permissions/containers/dataset-trivial-permissions/dataset-trivial-permissions.component.scss
src/app/pages/datasets/modules/permissions/containers/dataset-trivial-permissions/dataset-trivial-permissions.component.ts
src/app/pages/datasets/modules/permissions/permissions.module.ts

NAS-119185 / 22.12.1 / Adding loading indicator to permissions editor

---

src/app/modules/entity/entity-table/entity-table-add-actions/entity-table-add-actions.component.scss
src/app/modules/entity/entity-table/entity-table.component.ts

Reopening this PR on a different branch with https://github.com/truenas/webui/pull/7400

NAS-119205 / 23.10 / VM UI not accessible after VM creation

---

src/app/modules/entity/entity-table/entity-table-add-actions/entity-table-add-actions.component.scss
src/app/modules/entity/entity-table/entity-table.component.ts

Reopening this PR on a different branch with https://github.com/truenas/webui/pull/7400
Original PR: https://github.com/truenas/webui/pull/7415
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119205

NAS-119205 / 22.12 / VM UI not accessible after VM creation (by undsoft)

---

src/app/modules/entity/entity-table/entity-table-add-actions/entity-table-add-actions.component.scss
src/app/modules/entity/entity-table/entity-table.component.ts

Reopening this PR on a different branch with https://github.com/truenas/webui/pull/7400
Original PR: https://github.com/truenas/webui/pull/7415
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119205

NAS-119205 / 22.12.1 / VM UI not accessible after VM creation (by undsoft)

---

src/app/pages/datasets/components/dataset-icon/dataset-icon.component.scss
src/app/pages/storage/modules/devices/components/topology-item-icon/topology-item-icon.component.scss

NAS-119263 / 23.10 / Preserve space for topology and dataset icons

---

src/app/pages/sharing/smb/smb-form/smb-form.component.ts

Backported https://github.com/truenas/webui/pull/7389

NAS-118870 / 23.10 / Update `Name` field after first folder click

---

src/app/pages/applications/catalog/catalog.component.ts

No testing is necessary. Small guard.
Original PR: https://github.com/truenas/webui/pull/7440
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119252

NAS-119252 / 22.12.1 / Available Applications not loading (by undsoft)

---

src/app/pages/applications/catalog/catalog.component.ts

No testing is necessary. Small guard.
Original PR: https://github.com/truenas/webui/pull/7440
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119252

NAS-119252 / 23.10 / Available Applications not loading (by undsoft)

---

src/app/modules/ix-forms/components/ix-select/ix-select.component.scss
src/app/pages/datasets/components/dataset-details-panel/dataset-details-panel.component.html
src/app/pages/datasets/components/dataset-details-panel/dataset-details-panel.component.scss
src/assets/styles/other/_fn-styles.scss

As well fixed title here:
Before:
After:

NAS-119245 / 23.10 / Adjust ix-select width if chosen element has long name

---

src/app/pages/system/general-settings/localization-form/localization-form.component.ts
src/app/services/language.service.ts
src/app/store/system-config/system-config.effects.ts

Now selected language correctly appears on all pages!

NAS-119262 / 23.10 / Update setLanguageFromBrowser logic to get data from LocalStorage if set WS is not connected.

---

tests/bdd/bluefin/t_002_1_create_a_group.py
tests/bdd/bluefin/t_002_3_change_a_group_name.py
tests/bdd/bluefin/t_002_4_enabling_sudo_for_group.py
tests/bdd/bluefin/t_002_5_groups_can_have_duplicate_gids.py

"Please wait"  does not pop up anymore. It is replaced by mat-progress-bar.

AUTO-324 / 22.12.0 /  Replace '//h6[contains(.,"Please wait")]' by '//mat-progress-bar'

---

tests/bdd/bluefin/t_002_1_create_a_group.py
tests/bdd/bluefin/t_002_3_change_a_group_name.py
tests/bdd/bluefin/t_002_4_enabling_sudo_for_group.py
tests/bdd/bluefin/t_002_5_groups_can_have_duplicate_gids.py

"Please wait" does not pop up anymore. It is replaced by mat-progress-bar.

AUTO-324 / 23.10 / Replace '//h6[contains(.,"Please wait")]' by '//mat-progress-bar'

---

tests/bdd/bluefin/t_002_1_create_a_group.py
tests/bdd/bluefin/t_002_3_change_a_group_name.py
tests/bdd/bluefin/t_002_4_enabling_sudo_for_group.py
tests/bdd/bluefin/t_002_5_groups_can_have_duplicate_gids.py

"Please wait" does not pop up anymore. It is replaced by mat-progress-bar.

AUTO-324 / 22.12.1 / Replace '//h6[contains(.,"Please wait")]' by '//mat-progress-bar'

---

src/app/modules/ix-drop-grid/ix-drag.directive.ts
src/app/modules/ix-drop-grid/ix-drop-grid.directive.ts

**Testing**
Please see bug description in the ticket

NAS-119305 / 23.10 / Fix drag and drop on dashboard

---

src/app/pages/datasets/modules/permissions/containers/dataset-trivial-permissions/dataset-trivial-permissions.component.html
src/app/pages/datasets/modules/permissions/containers/dataset-trivial-permissions/dataset-trivial-permissions.component.scss
src/app/pages/datasets/modules/permissions/containers/dataset-trivial-permissions/dataset-trivial-permissions.component.spec.ts

NAS-119370 / 23.10 / Edit permissions - long dataset name problem

---

src/app/pages/credentials/certificates-dash/certificate-acme-add/certificate-acme-add.component.spec.ts
src/app/pages/credentials/certificates-dash/certificate-acme-add/certificate-acme-add.component.ts
src/app/pages/credentials/certificates-dash/certificates-dash.component.ts

Go to Credentials -> Certificates 
In the "Certificate Signing Requests" table, select an existing certificate with DNS:honcharov.cyou and create an ACME certificate (use the wrench button).
Check the update of the tables with certificates.

NAS-119236 / 22.12.1 / Fixed create ACME certificate

---

src/app/pages/credentials/certificates-dash/certificate-acme-add/certificate-acme-add.component.spec.ts
src/app/pages/credentials/certificates-dash/certificate-acme-add/certificate-acme-add.component.ts
src/app/pages/credentials/certificates-dash/certificates-dash.component.ts

git cherry-pick -x 68071b6bf35957d3a098d89f9f213bbaf602dd14
Go to Credentials -> Certificates 
In the "Certificate Signing Requests" table, select an existing certificate with DNS:honcharov.cyou and create an ACME certificate (use the wrench button).
Check the update of the tables with certificates.
Original PR: https://github.com/truenas/webui/pull/7476
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119236

NAS-119236 / 23.10 / Fixed create ACME certificate (by Raz-Dva)

---

src/app/pages/dashboard/components/widget-network/widget-network.component.ts

NAS-119368 / 23.10 / Invert In/Out on Network widget

---

.eslintrc.js
src/app/modules/entity/utils.ts
src/app/pages/data-protection/replication/replication-wizard/replication-wizard-data.interface.ts
src/app/pages/data-protection/replication/replication-wizard/replication-wizard.component.ts
src/app/pages/datasets/components/zvol-form/zvol-form.component.ts

Validation: test affected forms.

NAS-119475 / 23.10 / Reduce max cognitive complexity to 60

---

src/app/pages/storage/components/unused-resources/unused-resources.component.ts

NAS-117027 / 23.10 / Update unused resources card in realtime

---

src/app/pages/dashboard/components/widget-network/widget-network.component.ts

**Testing**
See ticket
Original PR: https://github.com/truenas/webui/pull/7472
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119368

NAS-119368 / 22.12.1 / Invert In/Out on Network widget (by bvasilenko)

---

src/app/pages/datasets/components/dataset-details-panel/dataset-details-panel.component.scss

it's backport, we only need to merge it :)

NAS-119579 / 22.12.1 / Unnecessary scrollbar in dataset header (by AlexKarpov98)

---

src/app/modules/ix-forms/components/ix-slide-in/ix-slide-in.component.ts

Go to Credentials ->  Configure Active Directory 
Original PR: https://github.com/truenas/webui/pull/7483
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119049

NAS-119049 / 23.10 / Nas-119049 - Fixed LDAP slide-in is sometimes blank (by Raz-Dva)

---

.eslintrc.js
src/app/helpers/sentry-custom-extractor.helper.ts
src/app/interfaces/app-schema.interface.ts
src/app/modules/entity/entity-table/entity-table.component.ts
src/app/modules/entity/entity-table/entity-table.interface.ts
src/app/modules/entity/entity-wizard/entity-wizard.component.ts
src/app/modules/entity/utils.ts
src/app/pages/credentials/certificates-dash/forms/ca-add.component.ts
src/app/pages/credentials/certificates-dash/forms/certificate-add.component.ts
src/app/pages/data-protection/replication/replication-form/replication-form.component.ts
src/app/pages/data-protection/replication/replication-wizard/replication-wizard.component.ts
src/app/pages/datasets/components/dataset-form/dataset-form.component.ts
src/app/pages/sharing/iscsi/iscsi-wizard/iscsi-wizard.component.ts
src/app/pages/vm/vm-wizard/vm-wizard.component.ts
src/app/services/ws.service.ts

Remaining places are hard to fix without refactoring whole things, so I've mostly just added exceptions.

NAS-119589 / 23.10 / Enable no-explicit-any rule

---

src/app/modules/entity/entity-table/entity-table.component.html
src/app/modules/entity/entity-table/entity-table.component.ts

Go to disks and check that once you open details for one disk, it's only opened for one disk.
As well check other expandable table rows, like `S.M.A.R.T. Test Results..`

NAS-119607 / 23.10 / Storage -> Disks if one disk details toggled, all the disks are toggled as well

---

src/app/views/sessions/signin/signin-form/signin-form.component.html
src/app/views/sessions/signin/signin-form/signin-form.component.spec.ts
src/app/views/sessions/signin/signin-form/signin-form.component.ts

NAS-119669 / 23.10 / Log In button is disabled when form values are autofilled

---

.eslintrc.js
src/app/interfaces/api-directory.interface.ts
src/app/modules/entity/entity-table/entity-table.component.ts
src/app/modules/entity/table/expandable-table/expandable-table.component.scss
src/app/modules/ix-forms/components/ix-input/ix-input.component.ts
src/app/pages/applications/forms/chart-form/chart-form.component.ts
src/app/services/entity-table.service.ts
src/app/services/locale.service.ts
src/app/services/ws2.service.ts

A bunch of smaller improvements. Code review is enough.

NAS-119652 / 23.10 / Api changes, fixes tooltips and enables a linter rule

---

src/app/pages/network/network.component.ts

IPMI should be available now on page reload:

NAS-119670 / 23.10 / IPMI is missing when page is reloaded

---

src/app/interfaces/dataset.interface.ts
src/app/pages/datasets/components/dataset-capacity-management-card/dataset-capacity-management-card.component.ts

Needs to be merged after https://github.com/truenas/middleware/pull/10370

NAS-119330 / 23.10 / Add check for the readonly property

---

src/app/interfaces/dataset.interface.ts
src/app/pages/datasets/components/dataset-capacity-management-card/dataset-capacity-management-card.component.ts

Needs to be merged after ~https://github.com/truenas/middleware/pull/10370~ https://github.com/truenas/middleware/pull/10371
Original PR: https://github.com/truenas/webui/pull/7555
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119330

NAS-119330 / 22.12.1 / Add readonly property to dataset details (by denysbutenko)

---

src/app/modules/layout/components/admin-layout/admin-layout.component.html

Menu should be closed only by clicking the hamburger menu.

NAS-119793 / 23.10 / Sidebar menu closes if I hit ESC button

---

src/app/modules/layout/components/admin-layout/admin-layout.component.html

Menu should be closed only by clicking the hamburger menu.
Original PR: https://github.com/truenas/webui/pull/7559
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119793

NAS-119793 / 22.12.1 / Sidebar menu closes if I hit ESC button (by AlexKarpov98)

---

src/app/pages/system/general-settings/support/support.component.ts

How it works now:
https://user-images.githubusercontent.com/22980553/211558909-6489a766-6de9-4d87-8014-634d13ec0d77.mov
Previously if we cancelled, checkbox was marked as checked and didn't get back to default state (unchecked)
Like that:
https://user-images.githubusercontent.com/22980553/211559206-f94aeb14-8137-4067-b302-5b1b1189b61d.mov
Original PR: https://github.com/truenas/webui/pull/7558
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119743

NAS-119743 / 22.12.1 / System -> General -> Support -> Production system checkbox and modal bug (by AlexKarpov98)

---

src/app/pages/datasets/components/dataset-quotas/dataset-quota-edit-form/dataset-quota-edit-form.component.ts
src/app/pages/datasets/components/dataset-quotas/dataset-quotas-grouplist/dataset-quotas-grouplist.component.spec.ts
src/app/pages/datasets/components/dataset-quotas/dataset-quotas-grouplist/dataset-quotas-grouplist.component.ts
src/app/pages/datasets/components/dataset-quotas/dataset-quotas-userlist/dataset-quotas-userlist.component.spec.ts
src/app/pages/datasets/components/dataset-quotas/dataset-quotas-userlist/dataset-quotas-userlist.component.ts

**Summary**
The change relies on the PR https://github.com/truenas/middleware/pull/10073 . Make sure you have latest nightly build installed on your box before testing.
**Testing**
1. Go to **Datasets > Choose a dataset > Manage Quota**
2. For each quota in the list, make sure that
- usage percentage is calculated and displayed correctly
- N/A is displayed when quota has undefined amount
Original PR: https://github.com/truenas/webui/pull/7378
Jira URL: https://ixsystems.atlassian.net/browse/NAS-118993

NAS-118993 / 22.12.1 / Update WebUI for quota API changes (by bvasilenko)

---

src/app/interfaces/acl.interface.ts
src/app/interfaces/api-directory.interface.ts
src/app/pages/datasets/modules/permissions/components/save-as-preset-modal/save-as-preset-modal.component.spec.ts
src/app/pages/datasets/modules/permissions/components/save-as-preset-modal/save-as-preset-modal.component.ts

Additional fix for partially merged PR  https://github.com/truenas/webui/pull/7430

NAS-119180 / 23.10 / Designs for allowing users to manage ACL presets + Improvements

---

tests/bdd/conftest.py
tests/bdd/ha-bhyve02/test_NAS_T0961.py
tests/bdd/ha-bhyve02/test_NAS_T0962.py
tests/bdd/scale/test_NAS_T1102.py
tests/bdd/scale/test_NAS_T1104.py
tests/bdd/scale/test_NAS_T1249.py
tests/bdd/xpaths.py

Test results at https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Bluefin/job/UI%20Tests%20-%20TrueNAS%20SCALE%20Bluefin%20-%20Nightly/57/

TE-153 / 22.12.1 / Fixing AD netbios, system dataset and deleting dataset test issues 

---

src/app/pages/storage/modules/disks/components/disk-list/disk-list.component.ts

Revert "NAS-116966 / 23.10 / Hide `togglesmart` and `smartoptions` for unsupported SMART"

---

tests/bdd/conftest.py
tests/bdd/ha-bhyve02/test_NAS_T0961.py
tests/bdd/ha-bhyve02/test_NAS_T0962.py
tests/bdd/scale/test_NAS_T1102.py
tests/bdd/scale/test_NAS_T1104.py
tests/bdd/scale/test_NAS_T1249.py
tests/bdd/xpaths.py

It Fixing AD netbios and deleting dataset test issues

TE-153 / 23.10 / backport Bluefin UI fixes from #7578

---

src/app/interfaces/acl.interface.ts
src/app/interfaces/api-directory.interface.ts
src/app/pages/datasets/modules/permissions/components/save-as-preset-modal/save-as-preset-modal.component.html
src/app/pages/datasets/modules/permissions/components/save-as-preset-modal/save-as-preset-modal.component.scss
src/app/pages/datasets/modules/permissions/components/save-as-preset-modal/save-as-preset-modal.component.spec.ts
src/app/pages/datasets/modules/permissions/components/save-as-preset-modal/save-as-preset-modal.component.ts

Test by creating an acl preset and removing it.

NAS-119879 / 23.10 / Unable to set or delete an ACL preset

---

src/app/views/sessions/signin/signin-form/signin-form.component.ts

Testing instructions are in the ticket.

NAS-119884 / 23.10 / Authentication failures are incorrectly handled

---

src/app/interfaces/dynamic-form-schema.interface.ts
src/app/modules/ix-forms/components/ix-dynamic-form/ix-dynamic-form-item/ix-dynamic-form-item.component.html
src/app/modules/ix-forms/components/ix-dynamic-form/ix-dynamic-form-item/ix-dynamic-form-item.component.scss
src/app/services/app-schema.service.spec.ts
src/app/services/app-schema.service.ts

Instructions for testing are in the ticket

NAS-119632 / 22.12.1 / Nas 119632 Fixed tooltip

---

src/app/modules/entity/utils.ts
src/app/modules/ix-forms/components/ix-checkbox-list/ix-checkbox-list.component.html
src/app/modules/ix-forms/components/ix-checkbox/ix-checkbox.component.html
src/app/modules/ix-forms/components/ix-combobox/ix-combobox.component.html
src/app/modules/ix-forms/components/ix-input/ix-input.component.html
src/app/modules/ix-forms/components/ix-radio-group/ix-radio-group.component.html
src/app/modules/ix-forms/components/ix-select/ix-select.component.html
src/app/modules/ix-forms/components/ix-slide-toggle/ix-slide-toggle.component.html
src/app/modules/ix-forms/components/ix-textarea/ix-textarea.component.html
src/app/modules/ix-forms/ix-forms.module.ts
src/app/modules/test/test.module.ts
src/app/modules/test/test/test.directive.ts
src/app/pages/apps-old/chart-releases/chart-releases.component.ts
src/app/pages/services/services.component.html
src/app/pages/services/services.module.ts

This is a temporary experiment to see if this is something release engineering can use.
Code review is enough. Accepting comments and suggestions on how to make this better/easier to use.

NAS-119303 / 23.10 / Experimenting with test id attributes

---

src/app/interfaces/dynamic-form-schema.interface.ts
src/app/modules/ix-dynamic-form/components/ix-dynamic-form/ix-dynamic-form-item/ix-dynamic-form-item.component.html
src/app/modules/ix-dynamic-form/components/ix-dynamic-form/ix-dynamic-form-item/ix-dynamic-form-item.component.scss
src/app/modules/ix-dynamic-form/ix-dynamic-form.module.ts
src/app/pages/storage/modules/disks/components/disk-form/disk-form.component.ts
src/app/services/schema/app-schema.service.spec.ts
src/app/services/schema/app-shema.transformer.ts

git cherry-pick -x e7c21ee771d7816ad0490d4595970e8c96f40bbd
git cherry-pick -x 3f02a4dac8a11c3fb75980ee760fdacd5818248e
git cherry-pick -x 6c7d77e921b5c2383b4de97955e1b8bedf654e29
git cherry-pick -x 9f6eb7e1cc04735340b2d0147c2099baac8e3da3
git cherry-pick -x 68823092d46faac63a9bcbaa5b2db753e5a701b8
Instructions for testing are in the ticket
Original PR: https://github.com/truenas/webui/pull/7554
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119632

NAS-119632 / 23.10 / Nas 119632 Fixed tooltip (by RehanY147)

---

src/app/interfaces/api-directory.interface.ts
src/app/interfaces/ds-cache.interface.ts
src/app/modules/layout/components/change-password-dialog/change-password-dialog.component.spec.ts
src/app/modules/layout/components/change-password-dialog/change-password-dialog.component.ts
src/app/modules/layout/components/topbar/user-menu/user-menu.component.html
src/app/modules/layout/components/topbar/user-menu/user-menu.component.spec.ts
src/app/modules/layout/components/topbar/user-menu/user-menu.component.ts
src/app/services/ws.service.ts

git cherry-pick -x 3c24e72f6adb3e95e6a5a481b872f45898405bce
git cherry-pick -x 0b05715bf5d5fbb62d6de0a0914ec46a599577ee
git cherry-pick -x dee662fa68fa07d134417ac4d4f0766a6b8b4659
git cherry-pick -x e4b1cfc6304590ccc388174a0e2dfd270e628299
git cherry-pick -x 1491c8fdd83d7d06170cdf2d7207a63bb5ecd6df
git cherry-pick -x 3dab7760480751d4476bcc4126aa34c81dcce27f
git cherry-pick -x bb9576ef2b03bc240b8efdc20c839ac8c30bb1cd
git cherry-pick -x 2f3c7f7c9ae56fd78277d55db7f3a0e8fb88b711
git cherry-pick -x 13dad7e6309fb735db09f72b013e3cf3ff8e22ed
Change password should be visible if user has `{ local: true }` prop.
Original PR: https://github.com/truenas/webui/pull/7592
Jira URL: …

NAS-119792 / 22.12.1 / Changing user password doesn't work on non-root users (by AlexKarpov98)

---

src/app/pages/apps-old/docker-images/docker-images-list/docker-images-list.component.html
src/app/pages/apps-old/docker-images/docker-images-list/docker-images-list.component.spec.ts
src/app/pages/apps-old/docker-images/docker-images-list/docker-images-list.component.ts

Testing: see that docker images tab in Apps works.

NAS-119968 / 23.10 / Docker images page doesn't work

---

src/app/pages/api-keys/components/key-created-dialog/key-created-dialog.component.html
src/app/pages/api-keys/components/key-created-dialog/key-created-dialog.component.scss
src/app/pages/datasets/modules/encryption/components/export-all-keys-dialog/export-all-keys-dialog.component.html
src/app/pages/datasets/modules/encryption/components/export-dataset-key-dialog/export-dataset-key-dialog.component.html

Testing: check affected dialogs.
Before:

NAS-119917 / 23.10 / Margins on some dialogs is incorrect

---

src/app/views/sessions/signin/store/signin.store.ts

Testing. Do something in code to make one of the token generation requests fail.

NAS-119973 / 23.10 / Clear loading indicator in signin form on error

---

src/app/modules/layout/components/topbar/topbar.component.ts
src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.html
src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.ts
src/app/store/system-info/system-info.actions.ts
src/app/store/system-info/system-info.effects.ts
src/app/store/system-info/system-info.reducer.ts
src/app/store/system-info/system-info.selectors.ts

git cherry-pick -x 9d500051382f9fa0f1849841e6307db56639c84b
git cherry-pick -x 464f533fdaf5cfddc06973c7b85876b994df5cae
git cherry-pick -x 1dbbae9e5763b90423084ac57f0b6c14debb41ad
git cherry-pick -x 473842c65102f17c3e0f9415ffcf6c21daa245b9
git cherry-pick -x 878172b804940860311f3783e79df7603898a043
git cherry-pick -x eca95615110039ec8ca7ab01e8f30389b6f3f285
git cherry-pick -x d55780ae45d52a43de40b11324821eecf21a2753
git cherry-pick -x 76b42f1f144e98e432f932c5d81b19b257513514
git cherry-pick -x d50084a292c51cd329c01d604a102a8e165812d2
git cherry-pick -x d1c57afc0f03f1dfeb83fc10c98b40677ffef92a
Original PR: https://github.com/truenas/webui/pull/7356
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119081

NAS-119081 / 22.12.1 / Do not disallow failover when system versions mismatch (by AlexKarpov98)

---

src/app/modules/ix-forms/services/ix-formatter.service.ts

**Testing**
At the **Capacity Settings** block,
Test using a decimal in the **Quota** and **Reserved** fields

NAS-119945 / 23.10 / Save input decimals

---

src/app/views/sessions/signin/signin.component.html
src/app/views/sessions/signin/signin.component.scss
src/assets/styles/other/_material-reduction.scss

on MASTER, it works fine, problem is only on 22.12 (Bluefin) version.

NAS-120047 / 22.12-BETA.2 / UI issue on login window with 2FA enabled

---

src/app/views/sessions/signin/signin.component.html
src/app/views/sessions/signin/signin.component.scss
src/assets/styles/other/_material-reduction.scss

on MASTER, it works fine, problem is only on 22.12 (Bluefin) version.
Original PR: https://github.com/truenas/webui/pull/7657
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120047

NAS-120047 / 22.12.1 / UI issue on login window with 2FA enabled (by AlexKarpov98)

---

src/app/modules/entity/entity-form/components/form-slider/form-slider.component.html
src/app/modules/entity/entity-form/components/form-slider/form-slider.component.ts
src/app/modules/entity/entity-toolbar/components/toolbar-slider/toolbar-slider.component.html
src/app/modules/entity/entity-toolbar/components/toolbar-slider/toolbar-slider.component.ts
src/app/modules/entity/entity.module.ts

NAS-120059 / 23.10 / Legacy slider -> MatLegacySliderModule to MatSliderModule

---

src/app/pages/apps-old/forms/chart-form/chart-form.component.ts
src/app/pages/apps/components/chart-form/chart-form.component.ts
src/app/services/schema/app-schema.service.ts

There was a problem where for some reason **checkIsValidSchedule** received `undefined` or so and caused error.

NAS-120076 / 23.10 / Unable to edit an App

---

src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.html
src/app/pages/reports-dashboard/reports-dashboard.component.html

Just hiding some functionality due to bugs.
Code review should be enough.

NAS-120121 / 22.12.1 / Hiding time diff warning

---

src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.html
src/app/pages/reports-dashboard/reports-dashboard.component.html

Just hiding some functionality due to bugs.
Code review should be enough.
Original PR: https://github.com/truenas/webui/pull/7700
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120121

NAS-120121 / 22.12.2 / Hiding time diff warning (by undsoft)

---

src/app/app.module.ts
src/app/helpers/window.helper.ts
src/app/pages/system/update/manualupdate/manualupdate.component.ts
src/app/pages/system/update/update.component.ts
src/app/services/update.service.ts
src/app/views/sessions/signin/signin.component.ts
yarn.lock

Testing is complicated and not fully possible. I would just suggest inspecting code.

NAS-120213 / 13.0 / Refresh UI after an update

---

src/app/pages/system/update/manual-update-form/manual-update-form.component.ts
src/app/pages/system/update/update.component.ts
src/app/services/update.service.ts
src/app/views/sessions/signin/signin.component.ts

git cherry-pick -x 2576f53573c72e8d5d33358b3f798f12efd34a63
Testing is complicated and not fully possible. I would just suggest inspecting code.
Original PR: https://github.com/truenas/webui/pull/7709
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120213

NAS-120213 / 22.12.1 / Refresh UI after an update (by undsoft)

---

src/app/pages/system/update/manual-update-form/manual-update-form.component.ts
src/app/pages/system/update/update.component.ts
src/app/services/update.service.ts
src/app/views/sessions/signin/store/signin.store.spec.ts
src/app/views/sessions/signin/store/signin.store.ts

git cherry-pick -x f10016e852cb8e76c2496c49ade30ef9ba54a4d3
git cherry-pick -x 015d296f23a0c7318930154953e23c00ab696957
Original PR: https://github.com/truenas/webui/pull/7711
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120213

NAS-120213 / 23.10 / Refresh UI after an update (by undsoft) (by bugclerk)

---

src/app/pages/system/general-settings/manage-configuration-menu/manage-configuration-menu.component.spec.ts
src/app/pages/system/general-settings/manage-configuration-menu/manage-configuration-menu.component.ts
src/app/services/ws.service.ts
src/app/views/sessions/signin/signin.component.ts

git cherry-pick -x 47ddfeabbaf1695654d10cfa0d269fe90ae74863
git cherry-pick -x 559e7ce7b559d72680295615747729e6100dc713
git cherry-pick -x 6734ae54060503a47301722a6149cc2d5a2bfe8b
**Testing**
Please see ticket
Note: fix for Bluefin is coming soon in a separate PR
Original PR: https://github.com/truenas/webui/pull/7695
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120126

NAS-120126 / 22.12.1 / Reinit SigninComponent after connect (by bvasilenko)

---

src/app/interfaces/kubernetes-config.interface.ts
src/app/pages/applications/kubernetes-settings/kubernetes-settings.component.html
src/app/pages/applications/kubernetes-settings/kubernetes-settings.component.spec.ts
src/app/pages/applications/kubernetes-settings/kubernetes-settings.component.ts

Testing: observe new checkbox in Apps -> Advanced settings

NAS-119687 / 22.12.2 / Adding force flags in Kubernetes settings

---

src/app/interfaces/kubernetes-config.interface.ts
src/app/pages/apps-old/kubernetes-settings/kubernetes-settings.component.html
src/app/pages/apps-old/kubernetes-settings/kubernetes-settings.component.spec.ts
src/app/pages/apps-old/kubernetes-settings/kubernetes-settings.component.ts

Testing: observe new checkbox in Apps -> Advanced settings
Original PR: https://github.com/truenas/webui/pull/7729
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119687

NAS-119687 / 23.10 / Adding force flags in Kubernetes settings (by undsoft)

---

src/app/pages/apps/apps.module.ts
src/app/pages/apps/components/app-detail-view/app-detail-view.component.html
src/app/pages/apps/components/app-detail-view/app-detail-view.component.scss
src/app/pages/apps/components/app-detail-view/app-detail-view.component.ts
src/app/pages/apps/components/app-info-card/app-info-card.component.html
src/app/pages/apps/components/app-info-card/app-info-card.component.scss
src/app/pages/apps/components/app-info-card/app-info-card.component.ts
src/app/pages/apps/components/available-apps/available-apps.component.ts
src/app/pages/apps/utils/catalog-to-apps-transform.ts

Shows the first four catalog apps as `Similar Apps` to fulfill the emptiness in the layout.
For testing, you can open the `Apps (WIP) -> Available -> Choose Any App` and check the similar apps on the app detail view.

NAS-120107 / 23.10 / Similar Apps on App Detail View

---

src/app/modules/common/dialog/update-dialog/update-dialog.component.html
src/app/modules/common/dialog/update-dialog/update-dialog.component.scss
src/app/modules/layout/components/topbar/topbar.component.html

Start an update process and click the icon in top bar or update the `*ngIf="updateIsRunning"` condition in `topbar.component.html`.

NAS-120064 / 23.10 / Fixing styles in update popover

---

src/app/pages/sharing/smb/smb-form/smb-form.component.ts

Testing instructions are in the ticket + general testing of SMB form.

NAS-120137 / 22.12.2 / Fixing Enable ACL warning in SMB share form

---

src/app/pages/system/view-enclosure/classes/chassis-view.ts
src/app/pages/system/view-enclosure/classes/system-profiler.ts
src/app/pages/system/view-enclosure/components/enclosure-disks-mini/enclosure-disks-mini.component.html
src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.ts

Make sure enclosure UI shows visualization on supported MINI platforms. Also check JS console is clear of "could not find NativeElement" related errors
You can find the relevant lab machine ip in the ticket comments.

NAS-120298 / 22.12.2 / NAS-120298

---

src/app/services/schema/app-schema.service.ts

Backported
Original PR https://github.com/truenas/webui/pull/7746

NAS-120136 / 23.10 / Clarification of the `checkIsValidCronTab` method

---

src/app/services/gpu/isolated-gpu-validator.service.spec.ts
src/app/services/gpu/isolated-gpu-validator.service.ts

my mommy's gonna be so psyched i authored this important PR

Fixing very minor spelling mistake in GPU isolation service validator message

---

src/app/pages/system/advanced/cron/cron-form/cron-form.component.html

A small fix. Code review should be enough.

NAS-120349 / 23.10 / Fix stdout tooltip in cron form

---

src/app/modules/entity/entity-job/entity-job.component.ts
src/app/services/ws.service.ts

Same as https://github.com/truenas/webui/pull/7774, but for bluefin.

NAS-120217 / 22.12.2 / Getting job status for fast failing jobs

---

src/app/modules/entity/entity-job/entity-job.component.ts
src/app/services/ws2.service.ts

NAS-120217 / 23.10 / Getting job status for fast failing jobs

---

src/app/pages/system/advanced/cron/cron-form/cron-form.component.html

A small fix. Code review should be enough.
Original PR: https://github.com/truenas/webui/pull/7779
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120349

NAS-120349 / 22.12.2 / Fix stdout tooltip in cron form (by denysbutenko)

---

src/app/pages/sharing/smb/smb-form/smb-form.component.ts

Testing instructions are in the ticket + general testing of SMB form.
Original PR: https://github.com/truenas/webui/pull/7732
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120137

NAS-120137 / 22.12.1 / Fixing Enable ACL warning in SMB share form (by undsoft)

---

src/app/pages/system/view-enclosure/classes/chassis-view.ts
src/app/pages/system/view-enclosure/classes/system-profiler.ts
src/app/pages/system/view-enclosure/components/enclosure-disks-mini/enclosure-disks-mini.component.html
src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.ts

git cherry-pick -x 6388c2fad7d153c45241c278162492cd90edddf9
git cherry-pick -x 0e86128f0901e9a0e1aca58e381ef54f82844e72
git cherry-pick -x 249234290c3ece8830de8ea46a39be708f4c6f84
Make sure enclosure UI shows visualization on supported MINI platforms. Also check JS console is clear of "could not find NativeElement" related errors
You can find the relevant lab machine ip in the ticket comments.
Original PR: https://github.com/truenas/webui/pull/7753
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120298

NAS-120298 / 23.10 / NAS-120298 (by dszidi)

---

src/app/modules/jobs/components/job-item/job-item.component.html
src/app/modules/jobs/components/job-item/job-item.component.scss
src/app/modules/jobs/components/job-item/job-item.component.spec.ts
src/app/modules/jobs/components/jobs-panel/jobs-panel.component.scss
src/assets/styles/other/_tn-styles.scss

Examples of how it must look:
For testing, please check the jobs panel.

NAS-120310 / 23.10 / Fix long description on jobs panel

---

src/app/modules/jobs/components/job-item/job-item.component.scss

git cherry-pick -x 71bcf4542b1b3e9d4c5f0866b42a5a2e4270a117
git cherry-pick -x 0b3238146757509fb3d4d95d0dfade391ac15448
Examples of how it must look:
For testing, please check the jobs panel.
Original PR: https://github.com/truenas/webui/pull/7747
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120310

NAS-120310 / 22.12.2 / Fix long description on jobs panel (by denysbutenko)

---

src/app/helptext/directory-service/active-directory.ts
src/app/pages/directory-service/components/active-directory/active-directory.component.html

For testing instructions, please check [the ticket](https://ixsystems.atlassian.net/browse/NAS-120422).

NAS-120422 / 23.10 / Fix tooltip in active directory form

---

src/app/helptext/directory-service/active-directory.ts
src/app/pages/directory-service/components/active-directory/active-directory.component.html

For testing instructions, please check [the ticket](https://ixsystems.atlassian.net/browse/NAS-120422).
Original PR: https://github.com/truenas/webui/pull/7801
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120422

NAS-120422 / 22.12.2 / Fix tooltip in active directory form (by denysbutenko)

---

src/app/pages/data-protection/replication/replication-form/replication-form.component.ts

NAS-120432 / 22.12.2 / Replication tasks cannot be edited

---

src/app/pages/data-protection/replication/replication-form/replication-form.component.ts

See ticket.
Original PR: https://github.com/truenas/webui/pull/7808
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120432

NAS-120432 / 23.10 / Replication tasks cannot be edited (by undsoft)

---

src/app/pages/data-protection/components/data-protection-dashboard/data-protection-dashboard.component.ts

**Testing**
On **Data Protection** page at **Replication Tasks** block,
1. Create and run replication task, watch how it's status displayed
2. Use mockup in code to simulate `WAITING` status (see ticket how)

NAS-120101 / 23.10 / Replace `job status` with `replication task status`

---

src/app/pages/task-calendar/replication/replication-form/replication-form.component.ts

Revert "NAS-119783 / 13.0 / NAS-119783 - Fixed error "[schedule] A dict was expected" for create a replication task"

---

src/app/modules/page-header/page-title-header/page-title-header.component.scss

Test: Check to make sure bottom border of page header element lines up with content below

NAS-120494 / 23.10 / Make page header match width of content below

---

src/app/pages/storage/modules/devices/components/zfs-info-card/zfs-info-card.component.html
src/app/pages/storage/modules/devices/components/zfs-info-card/zfs-info-card.component.ts

git cherry-pick -x eac4c701ce36329d7c6711a4ce44bc37c916e19a
git cherry-pick -x 0ecfe44b1d335b910197885937ae227eda48d6fe
git cherry-pick -x 957fca06e90efd1423f898768597ca0d73fbcdc1
Original PR: https://github.com/truenas/webui/pull/7833
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120376

NAS-120376 / 22.12.2 / Storage - Manage Devices incorrectly presents the "EXTEND button for member disks in RAIDZ VDEVs" (by AlexKarpov98)

---

src/app/interfaces/api-directory.interface.ts
src/app/pages/datasets/components/dataset-management/dataset-management.component.html
src/app/pages/datasets/components/dataset-management/dataset-management.component.ts
src/app/store/system-info/system-info.actions.ts
src/app/store/system-info/system-info.effects.ts
src/app/store/system-info/system-info.reducer.ts
src/app/store/system-info/system-info.selectors.ts

git cherry-pick -x 763d8e4c61c8351e20d2ef9f25c47221632969b4
git cherry-pick -x 7663c3c01dab4b78116071271a43fa3603d6e99e
git cherry-pick -x e8161b74216315be3ead62ebac70bf89758e4132
git cherry-pick -x 10a7348f96b23f05b4a18d868ed7b50debd47847
Original PR: https://github.com/truenas/webui/pull/7834
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119831

NAS-119831 / 22.12.2 / Hide import disk functionality on enterprise systems (by AlexKarpov98)

---

src/app/modules/entity/entity-table/entity-table-add-actions/entity-table-add-actions.component.ts
src/app/modules/layout/components/admin-layout/admin-layout.component.ts
src/app/modules/layout/components/navigation/navigation.component.html
src/app/modules/layout/components/navigation/navigation.component.ts
src/app/pages/directory-service/components/kerberos-realms/kerberos-realms-list.component.ts
src/app/services/navigation/navigation.service.ts

Go to `credentials/directory-services`  then `directoryservice/kerberosrealms`
In header there should be only one `Add` button

NAS-120469 / 23.10 / Kerberos Realms Screen Action Dropdown has Two Add Options

---

src/app/core/classes/system-profiler.ts

To test: Go to any non rackmount server from MINI series and make sure enclosure UI shows up.
You can DM me in slack for a test machine url

NAS-120570 / 13.0 / NAS-120570 - Fix rackmount detection strings

---

src/app/pages/common/entity/entity-form/validators/at-least-one-validation.ts
src/app/pages/common/entity/entity-form/validators/compare-validation.ts
src/app/pages/common/entity/entity-form/validators/password-validation.ts
src/app/services/validation.service.ts

Testing: see ticket + test some of affected validators.

NAS-120444 / 13.0 / Passwords don't match error when they do

---

src/app/modules/ix-dynamic-form/components/ix-dynamic-form/ix-dynamic-form-item/ix-dynamic-form-item.component.ts
src/app/services/app-schema.helpers.ts
src/app/services/app-schema.service.spec.ts
src/app/services/app-schema.service.ts
src/app/services/app-shema.transformer.ts

git cherry-pick -x 35dd891ac2aea4eab42f3cc930c14040ce8ba708
git cherry-pick -x cda1340c694c9b0850a98ea2bf01d3cba405645b
git cherry-pick -x 2d75ea6a9124ba0d1ef69edef3b94d8b14371ae4
git cherry-pick -x 24565f2ce0b2af9b0171467f930bf26b45cf8ccc
Original PR: https://github.com/truenas/webui/pull/7849
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120510

NAS-120510 / 22.12.2 / Nextcloud cron settings were not recognized during installation. (by AlexKarpov98)

---

src/app/modules/entity/entity-table/entity-table-add-actions/entity-table-add-actions.component.ts
src/app/modules/layout/components/admin-layout/admin-layout.component.ts
src/app/modules/layout/components/navigation/navigation.component.html
src/app/modules/layout/components/navigation/navigation.component.ts
src/app/pages/directory-service/components/kerberos-realms/kerberos-realms-list.component.ts
src/app/services/navigation/navigation.service.ts

git cherry-pick -x e92cab6cf5e6400d7f76e5174d5c6e08e57f946d
git cherry-pick -x 0a1f7b07ed5e8dbfc75ef547d3f164d9d3b356ca
Go to `credentials/directory-services`  then `directoryservice/kerberosrealms`
In header there should be only one `Add` button
Original PR: https://github.com/truenas/webui/pull/7847
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120469

NAS-120469 / 22.12.2 / Kerberos Realms Screen Action Dropdown has Two Add Options (by AlexKarpov98)

---

src/app/services/gpu/isolated-gpu-validator.service.spec.ts
src/app/services/gpu/isolated-gpu-validator.service.ts

git cherry-pick -x bd38498e99a72a974832d03a974e751c8ed413ce
git cherry-pick -x a81b73859ea4e72a469d819b1badd68965db466b
git cherry-pick -x 5c9abae9e0075764adfba992e32ae5beb29f0828
Original PR: https://github.com/truenas/webui/pull/7832
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120403

NAS-120403 / 23.10 / Fixed validator (by RehanY147)

---

src/app/services/schema/app-schema.service.ts

For testing you can use: 
10.238.238.100 (machine)
creds: **root / testing** 
Go to apps -> Available Apps -> search for **minio**
click **Install** 
Under **Minio Configuration** configuration there is:
TEST SUBQ checkbox - check it.
Fill required fields and see that form is now valid and you can submit.
Try switching `Type` select and check that form is correctly valid or invalid.
Or contact @stavros-k (he knows how to setup on any machine)

NAS-120493 / 23.10 / [SCALE/Apps]: Weird behaviour with show_if under subquestions

---

src/app/services/app-schema.service.ts

For testing you can use: 
10.238.238.100 (machine)
creds: **root / testing** 
Go to apps -> Available Apps -> search for **minio**
click **Install** 
Under **Minio Configuration** configuration there is:
TEST SUBQ checkbox - check it.
Fill required fields and see that form is now valid and you can submit.
Try switching `Type` select and check that form is correctly valid or invalid.
Or contact @stavros-k (he knows how to setup on any machine)
Original PR: https://github.com/truenas/webui/pull/7855
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120493

NAS-120493 / 22.12.2 / [SCALE/Apps]: Weird behaviour with show_if under subquestions (by AlexKarpov98)

---

src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.html
src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.ts

See ticket, use machine http://minir-101.dc1.ixsystems.net

NAS-120361 / 22.12.2 / Mini R Enclosure View should not have Identify Drive button

---

src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.html
src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.ts

See ticket, use machine http://minir-101.dc1.ixsystems.net
Original PR: https://github.com/truenas/webui/pull/7875
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120361

NAS-120361 / 23.10 / Mini R Enclosure View should not have Identify Drive button (by bvasilenko)

---

src/app/store/system-info/system-info.effects.ts

This just fixes a console error, but probably does nothing to fix error in the ticket. Code review is enough, will continue testing.

NAS-120669 / 22.12.2 / Fixing an error with HA status

---

src/app/interfaces/option.interface.ts
src/app/interfaces/vm-device.interface.ts
src/app/modules/ix-forms/classes/simple-async-combobox-provider.ts
src/app/modules/ix-forms/components/ix-combobox/ix-combobox-provider.ts
src/app/modules/ix-forms/components/ix-combobox/ix-combobox.component.html
src/app/modules/ix-forms/components/ix-combobox/ix-combobox.component.scss
src/app/modules/ix-forms/components/ix-combobox/ix-combobox.component.ts
src/app/pages/vm/devices/device-form/device-form.component.ts

Go to Virtualization -> choose virtual machine -> Devices -> Add -> choose  Type PCI Passthrough Device - >PCI Passthrough Device

NAS-120268 / 23.10 / Show description for PCI passthrough devices choices

---

src/app/pages/vm/utils/vm-gpu.service.ts
src/app/pages/vm/vm-edit-form/vm-edit-form.component.ts
src/app/services/gpu/gpu-service.spec.ts
src/app/services/gpu/gpu.service.ts

See ticket for testing instructions and machine.

NAS-120971 / 22.12.2 / Cannot save gpus in VM edit form

---

src/app/modules/common/dialog/info-dialog/info-dialog.component.scss
src/app/pages/storage/components/manager/manager.component.html
src/app/pages/storage/modules/devices/components/devices/devices.component.html
src/app/pages/storage/modules/devices/components/devices/devices.component.ts
src/app/pages/storage/modules/devices/components/disk-details-panel/disk-details-panel.component.html
src/app/pages/storage/modules/devices/components/disk-details-panel/disk-details-panel.component.ts
src/app/pages/storage/modules/devices/components/zfs-info-card/zfs-info-card.component.html
src/app/pages/storage/modules/devices/components/zfs-info-card/zfs-info-card.component.ts
src/app/pages/storage/modules/devices/stores/devices-store.service.ts

We checked the logic together with **Chris Peredun**.
I think code review is enough.

NAS-120533 / 23.10 / UI does not allow for EXTEND operations on single-device special VDEVs

---

tests/bdd/ha-bhyve02/test_NAS_T0952.py
tests/bdd/scale/test_NAS_T1070.py
tests/bdd/scale/test_NAS_T1089.py
tests/bdd/scale/test_NAS_T1091.py
tests/bdd/scale/test_NAS_T1253.py
tests/bdd/xpaths.py

also removed unnecessary code in T1070

TE-327 / 22.12.2 / Updated the Home Directory steps and code in T952, T1091 and T1253

---

tests/bdd/ha-bhyve02/test_NAS_T0952.py
tests/bdd/scale/test_NAS_T1070.py
tests/bdd/scale/test_NAS_T1089.py
tests/bdd/scale/test_NAS_T1091.py
tests/bdd/scale/test_NAS_T1253.py
tests/bdd/xpaths.py

also removed unnecessary code in T1070
(cherry picked from commit d0c7d18dc8d72005b6a950b5f8accac5e8550068)

TE-327 / 22.12.3 / Updated the Home Directory steps and code in T952, T1091 and T1253

---

tests/bdd/ha-bhyve02/test_NAS_T0952.py
tests/bdd/scale/test_NAS_T1070.py
tests/bdd/scale/test_NAS_T1091.py
tests/bdd/scale/test_NAS_T1253.py
tests/bdd/xpaths.py

also removed unnecessary code in T1070
(cherry picked from commit d0c7d18dc8d72005b6a950b5f8accac5e8550068)

TE-327 / 23.10 / Updated the Home Directory steps and code in T952, T1091 and T1253

---

src/app/modules/layout/components/navigation/navigation.component.scss
src/assets/styles/other/_fn-styles.scss

Test the scrollbar on different themes and browsers.

NAS-120410 / 23.10 / Styles for scrollbar

---

tests/bdd/scale/test_NAS_T1129.py

(cherry picked from commit 21c65911b3d50a42114e6d5af92864503ccd6973)

TE-274 / 22.12.3 / Adding missing pytest import in T1129

---

src/app/pages/network/components/forms/ipmi-form.component.ts
src/app/pages/network/network.component.ts

`http` replaced with `https`
Original PR: https://github.com/truenas/webui/pull/7916
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121056

NAS-121056 / 22.12.2 / Manage IPMI Button Does Not Work Correctly (by AlexKarpov98)

---

src/app/pages/network/components/forms/ipmi-form.component.ts
src/app/pages/network/network.component.ts

`http` replaced with `https`
Original PR: https://github.com/truenas/webui/pull/7916
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121056

NAS-121056 / 22.12.3 / Manage IPMI Button Does Not Work Correctly (by AlexKarpov98)

---

src/app/modules/common/dialog/info-dialog/info-dialog.component.scss
src/app/pages/storage/modules/devices/components/devices/devices.component.html
src/app/pages/storage/modules/devices/components/devices/devices.component.ts
src/app/pages/storage/modules/devices/components/disk-details-panel/disk-details-panel.component.html
src/app/pages/storage/modules/devices/components/disk-details-panel/disk-details-panel.component.ts
src/app/pages/storage/modules/devices/components/zfs-info-card/zfs-info-card.component.html
src/app/pages/storage/modules/devices/components/zfs-info-card/zfs-info-card.component.ts

git cherry-pick -x 4f6780f097d32c96cb19c4d7a47251461b2bd941
git cherry-pick -x 0d536a130ad4befa2decf6c5e9e5eaebfb239b0f
git cherry-pick -x f279c03bc0d18072c1b4e1c2517947c700c8615f
git cherry-pick -x fb98b43700cba68492bcfa6eafa1deb52fd476f8
git cherry-pick -x 04aef7afc9835e56f92a6d0d07cd28ede78c8de0
git cherry-pick -x 558bd239cd09660590dcb871f9f64a8cc6ec5efe
git cherry-pick -x 87a39c7f1b1f114ce66d12b16cd2fd4b6ef08dae
We checked the logic together with **Chris Peredun**.
I think code review is enough.
Original PR: https://github.com/truenas/webui/pull/7883
Jira URL: …

NAS-120533 / 22.12.3 / UI does not allow for EXTEND operations on single-device special VDEVs (by AlexKarpov98)

---

src/app/pages/vm/vm-edit-form/vm-edit-form.component.html
src/app/pages/vm/vm-edit-form/vm-edit-form.component.ts
src/app/pages/vm/vm-list/vm-list.component.ts

git cherry-pick -x 9d5eecc19333b7147529c7da16c721a0d28b90c4
git cherry-pick -x 38d8012ac21bbf4d8b518561113359717caf84e6
For testing you can use any machine where you can set up VM.
I used this one:
**mini3xlp-101.dc1.ixsystems.net**
Original PR: https://github.com/truenas/webui/pull/7930
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119754

NAS-119754 / 22.12.3 / CPU Mode Displays on Edit VM Form for All CPU Mode Options (by AlexKarpov98)

---

src/app/pages/data-protection/replication/replication-list/replication-list.component.ts

Follow steps in ticket for testing.

NAS-121116 / 23.10 / Advanced Options on Replication Page dumps user back to Replication Page

---

src/app/pages/data-protection/replication/replication-list/replication-list.component.ts

git cherry-pick -x 41af54f52e8edd282d71bd749594d204200baa3a
git cherry-pick -x d390d01c00059f458b02c71c7ba5e71a9022fb64
Follow steps in ticket for testing.
Original PR: https://github.com/truenas/webui/pull/7960
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121116

NAS-121116 / 22.12.3 / Advanced Options on Replication Page dumps user back to Replication Page (by AlexKarpov98)

---

src/app/pages/account/users/user-form/user-form.component.ts

for testing please check ticket description.
Original PR: https://github.com/truenas/webui/pull/7977
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121105

NAS-121105 / 22.12.3 / Load state not working on the User create/edit form (by AlexKarpov98)

---

src/app/pages/dashboard/components/widget-network/widget-network.component.ts

**Testing**
On the **Dashboard** page, at **Network** widget, check "time" axis on the chart. Try changing time zone in **System Settings > General**
Expected result: **Network** widget should show same time, as displayed in **Localization** and **Reports**.

NAS-121014 / 23.10 / Fix timezone in network widget

---

src/app/pages/apps/components/available-apps/available-apps-header/available-apps-header.component.scss
src/app/pages/apps/components/catalogs/catalogs.component.html

NAS-121140 / 23.10 / The "Add Catalog" button missing on the new apps design

---

src/app/modules/loader/app-loader.module.ts
src/app/modules/loader/directives/with-loading-state/with-loading-state-error/with-loading-state-error.component.html
src/app/modules/loader/directives/with-loading-state/with-loading-state-error/with-loading-state-error.component.ts
src/app/modules/loader/directives/with-loading-state/with-loading-state-loader/with-loading-state-loader.component.html
src/app/modules/loader/directives/with-loading-state/with-loading-state-loader/with-loading-state-loader.component.scss
src/app/modules/loader/directives/with-loading-state/with-loading-state-loader/with-loading-state-loader.component.ts
src/app/modules/loader/directives/with-loading-state/with-loading-state.directive.spec.ts
src/app/modules/loader/directives/with-loading-state/with-loading-state.directive.ts
src/app/pages/storage/components/dashboard-pool/zfs-health-card/zfs-health-card.component.html
src/app/pages/storage/modules/devices/components/hardware-disk-encryption/hardware-disk-encryption.component.html
src/app/pages/storage/modules/devices/components/smart-info-card/smart-info-card.component.html
src/app/pages/storage/modules/devices/components/smart-info-card/smart-info-card.component.ts
src/app/pages/storage/storage.module.ts

NAS-121143 / 23.10 / Adds *withLoadingState directive

---

src/app/services/websocket-connection.service.ts

Two timers were simultaneously running to reconnect at `onClose`. I added an additional check for the existence of a reconnect attempt. The unnecessary connection via WebSocket does not occur now. Reloading the page every minute is now resolved

NAS-120550 / 23.10 / Exclude unnecessary connection via WebSocket

---

src/app/pages/data-protection/replication/replication-wizard/replication-wizard.component.ts
src/app/pages/datasets/modules/snapshots/snapshot-details-row/snapshot-details-row.component.ts
src/app/pages/datasets/modules/snapshots/store/snapshot.effects.ts

**Testing**
Please go through steps listed in the ticket

NAS-121188 / 23.10 / Snapshot created even though Validation error message displayed

---

src/app/views/sessions/signin/signin-form/signin-form.component.html
src/app/views/sessions/signin/signin-form/signin-form.component.spec.ts
src/app/views/sessions/signin/signin-form/signin-form.component.ts

See that you can login again on latest nightlies.

NAS-121248 / 23.10 / Hotfixes login form

---

src/app/core/testing/utils/mock-storage-generator.utils.ts
src/app/pages/storage/components/dashboard-pool/topology-card/topology-card.component.spec.ts
src/app/pages/storage/components/dashboard-pool/topology-card/topology-card.component.ts
src/app/services/storage.service.spec.ts
src/app/services/storage.service.ts

code review is enough.
Checked together with Chris Peredun.

NAS-120508 / 23.10 / WebUI validation of VDEV redundancy across VDEV types

---

src/app/core/testing/utils/mock-storage-generator.utils.ts
src/app/pages/storage/components/dashboard-pool/topology-card/topology-card.component.spec.ts
src/app/pages/storage/components/dashboard-pool/topology-card/topology-card.component.ts
src/app/services/storage.service.spec.ts
src/app/services/storage.service.ts

code review is enough.
Checked together with Chris Peredun.
Original PR: https://github.com/truenas/webui/pull/7990
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120508

NAS-120508 / 22.12.3 / WebUI validation of VDEV redundancy across VDEV types (by AlexKarpov98)

---

src/app/pages/data-protection/replication/replication-wizard/replication-wizard.component.ts
src/app/pages/datasets/modules/snapshots/snapshot-details-row/snapshot-details-row.component.ts
src/app/pages/datasets/modules/snapshots/store/snapshot.effects.ts

**Testing**
Please go through steps listed in the ticket
Original PR: https://github.com/truenas/webui/pull/8006
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121188

NAS-121188 / 22.12.3 / Snapshot created even though Validation error message displayed (by bvasilenko)

---

src/app/pages/apps/components/chart-wizard/chart-wizard.component.ts

**Testing**
1. Go to Apps -> Available 
1. Choose an app, for example **plex**  as mentioned in the ticket
1. Click the install button
**Expected result:** the install form should appear

NAS-121319 / 23.10 / Restore install app from

---

src/app/pages/storage/modules/disks/components/disk-wipe-dialog/disk-wipe-dialog.component.html
src/app/pages/storage/modules/disks/components/disk-wipe-dialog/disk-wipe-dialog.component.ts

Prevent users from submitting an empty value in the Wipe Disk dialog.
For context, please check the ticket.

NAS-121274 / 23.10 / Prevent empty value in Wipe Disk dialog

---

src/app/enums/middleware-error.enum.ts
src/app/pages/data-protection/replication/replication-wizard/replication-wizard.component.ts

Please check the ticket for details.

NAS-121266 / 22.12.3 / Ignore EEXIST error while creating snapshots

---

src/app/pages/storage/modules/disks/components/disk-wipe-dialog/disk-wipe-dialog.component.html
src/app/pages/storage/modules/disks/components/disk-wipe-dialog/disk-wipe-dialog.component.ts

Prevent users from submitting an empty value in the Wipe Disk dialog.
For context, please check the ticket.
Original PR: https://github.com/truenas/webui/pull/8051
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121274

NAS-121274 / 22.12.3 / Prevent empty value in Wipe Disk dialog (by denysbutenko)

---

src/app/enums/middleware-error.enum.ts
src/app/pages/data-protection/replication/replication-wizard/replication-wizard.component.ts

Please check the ticket for details.

NAS-121266 / 23.10 / Ignore EEXIST error while creating snapshots

---

README.md
src/app/helpers/track-by.utils.ts
src/app/interfaces/websocket-error.interface.ts
src/app/modules/jobs/components/jobs-panel/jobs-panel.component.ts
src/app/pages/apps-old/dialogs/chart-bulk-upgrade/chart-bulk-upgrade.component.html
src/app/pages/apps-old/dialogs/chart-bulk-upgrade/chart-bulk-upgrade.component.ts
src/app/pages/apps-old/docker-images/docker-image-delete-dialog/docker-image-delete-dialog.component.html
src/app/pages/apps-old/docker-images/docker-image-delete-dialog/docker-image-delete-dialog.component.ts
src/app/pages/apps-old/docker-images/docker-image-update-dialog/docker-image-update-dialog.component.html
src/app/pages/apps-old/docker-images/docker-image-update-dialog/docker-image-update-dialog.component.ts
src/app/pages/jobs/jobs-list/jobs-list.component.ts
src/app/pages/system/alert-config-form/alert-config-form.component.html
src/app/pages/system/alert-config-form/alert-config-form.component.ts
src/app/pages/system/bootenv/boot-pool-delete-dialog/boot-pool-delete-dialog.component.html
src/app/pages/system/bootenv/boot-pool-delete-dialog/boot-pool-delete-dialog.component.ts
src/app/pages/vm/vm-list/vm-list.component.ts
src/app/pages/vm/vm-wizard/steps/1-os-step/os-step.component.spec.ts
src/app/pages/vm/vm-wizard/steps/1-os-step/os-step.component.ts
src/app/pages/vm/vm-wizard/vm-wizard.component.spec.ts

NAS-121395 / 23.10 / Minor fixes

---

src/app/core/pipes/format-datetime.pipe.ts
src/app/pages/system/general-settings/localization-form/localization-form.component.ts
src/app/services/locale.service.ts

git cherry-pick -x 36d7087655e4dfe1ec0cb9f0415e445011e9be5b
git cherry-pick -x 4ecead0d2c53223425e38f592417597ed611b1d7
git cherry-pick -x ce7c6ae71ba4b1d3e0a6f6243069a5ba1fea5a37
git cherry-pick -x 893a56ad956a2f51a94db631c1a132b6e01ba8b0
git cherry-pick -x 1457bb24c2643dd0f8e454039d760174a68fe570
git cherry-pick -x d902212d2d88dd3a91bf174cf43ea690ed7bb4b7
git cherry-pick -x 2f83e312fe9c0cfd533d88241e84df84c8243241
git cherry-pick -x dde11b0bb05eef0947b6ad0b5d6ece8e9e1f2293
git cherry-pick -x e658fe53fffc03c6f0b1d0086cf7d3a622936dd3
Original PR: …

NAS-121247 / 22.12.3 / TrueNAS SCALE - RangeError: Invalid time value on UI (by AlexKarpov98)

---

.github/actions/prepare/action.yml
Dockerfile

NAS-121402 / 23.10 / Upgrade node to hydrogen (18 LTS)

---

src/app/modules/jobs/components/jobs-panel/jobs-panel.component.spec.ts
src/app/modules/jobs/components/jobs-panel/jobs-panel.component.ts
src/app/modules/jobs/store/job.selectors.ts

Goal is to filter out `transient: true` jobs.
Original PR: https://github.com/truenas/webui/pull/8072
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121445

NAS-121445 / 22.12.3 / Trivial: Waiting to renew Kerberos ticket. Current ticketexpires (by AlexKarpov98)

---

src/app/modules/common/search-input/search-input.component.ts
src/app/pages/apps/apps-routing.module.ts
src/app/pages/apps/components/installed-apps/app-containers-card/app-containers-card.component.scss
src/app/pages/apps/components/installed-apps/app-details-panel/app-details-panel.component.html
src/app/pages/apps/components/installed-apps/app-details-panel/app-details-panel.component.scss
src/app/pages/apps/components/installed-apps/app-history-card/app-history-card.component.scss
src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.scss
src/app/pages/apps/components/installed-apps/app-notes-card/app-notes-card.component.scss
src/app/pages/apps/components/installed-apps/app-row/app-row.component.html
src/app/pages/apps/components/installed-apps/app-row/app-row.component.scss
src/app/pages/apps/components/installed-apps/app-status-cell/app-status-cell.component.ts
src/app/pages/apps/components/installed-apps/installed-apps.component.html
src/app/pages/apps/components/installed-apps/installed-apps.component.scss
src/app/pages/apps/components/installed-apps/installed-apps.component.ts

- The styles for the app-header-row and app-row were consolidated into a single file.
- The spacing between cards in the details panel was modified.
- The breadcrumbs were corrected.
- The page title was fixed.
- The status column no longer overlaps with other columns and updates properly, addressing issues such as the green deploying status.
- Fixed TypeError in the search input component

NAS-121435 / 23.10 / Fixes for Installed app page

---

src/app/services/ws.service.ts

**Summary**
Need to clear the eventSubscriptions object in the `WebsocketService` after closing the WebSocket connection. It was not possible to directly access the `WebsocketService` from the `onClose` handler due to a circular reference error. Therefore, I solved the problem in a slightly different way.
**Testing**
Make sure this bug no longer happens: 
- NAS-121447
- NAS-121488 (duplicate)
Repro steps:
1. Wait for about 15-20 minutes having the WebUI opened
2. Every 60 seconds, the following issue observed:
- "Connecting..." splash screen appears
- 2 x CloseErrors appear in the console, see screenshot below
- when this happens first time, then one additional websocket connection starts, keeping the old one open, without any message from server indicating that it's closed, which makes …

NAS-121447 / 23.10 / Clear subscriptions after websocket close

---

src/app/pages/dashboard/components/dashboard/dashboard.component.ts

Don't judge. Don't try to understand.
The issue:
https://user-images.githubusercontent.com/351613/234235191-2ed4c0e4-bea9-4d30-86a4-bbe21909f9d5.mp4
The fix:
https://user-images.githubusercontent.com/351613/234235737-c9f2c673-c4f3-4822-b269-4db64bfedf5c.mp4

NAS-121547 / 23.10 / Fix Pool named "Storage" toggles Storage widget

---

src/app/pages/dashboard/components/dashboard/dashboard.component.ts

git cherry-pick -x ec688d0716f629cabb369e72f59d56c10cc170da
git cherry-pick -x 68fb3a1310ba0a2c5d9c532be08b05df7aecf9fb
Don't judge. Don't try to understand.
The issue:
https://user-images.githubusercontent.com/351613/234235191-2ed4c0e4-bea9-4d30-86a4-bbe21909f9d5.mp4
The fix:
https://user-images.githubusercontent.com/351613/234235737-c9f2c673-c4f3-4822-b269-4db64bfedf5c.mp4
Original PR: https://github.com/truenas/webui/pull/8107
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121547

NAS-121547 / 22.12.3 / Fix Pool named "Storage" toggles Storage widget (by denysbutenko)

---

.markuplintrc
src/app/modules/common/dialog/multi-error-dialog/error-template/error-template.component.html
src/app/modules/ix-icon/ix-icon.module.ts

NAS-121650 / 23.10 / Disallow mat-icon

---

src/app/pages/apps/components/installed-apps/app-history-card/app-history-card.component.html
src/app/pages/apps/components/installed-apps/app-history-card/app-history-card.component.scss
src/app/pages/apps/components/installed-apps/app-history-card/app-history-card.component.spec.ts
src/app/pages/apps/components/installed-apps/app-history-card/app-history-card.component.ts

- The newest events appear on top
- Add the `Refresh Events` button to the card
- Add more test cases

NAS-121616 / 23.10 / Improvements to AppHistoryCardComponent

---

scripts/ui/models.json
src/app/core/testing/utils/enclosure-templates/mock-r20.ts
src/app/core/testing/utils/enclosure-templates/mock-r40.ts
src/app/core/testing/utils/enclosure-templates/mock-r50.ts
src/app/core/testing/utils/mock-storage-generator.utils.ts

To test, enable mock utility and set controller model to R20/R40/R50
```
yarn ui -e -m <r20 | r40 | r50>
```

NAS-121704 / 23.10 / Add R20,R40,R50 to mock utility

---

src/app/pages/apps/components/installed-apps/installed-apps.component.scss
src/app/pages/apps/components/installed-apps/installed-apps.component.ts

result:
https://user-images.githubusercontent.com/22980553/235116984-cc9cc613-8aa3-49ed-8278-606368acefc2.mov

NAS-121713 / 23.10 / More fixes for Installed apps page

---

.github/workflows/main.yml

Code review only. Can test this only after this is merged.

NAS-121324 / 23.10 / Test plan fails for contributor PRs

---

src/app/interfaces/api-directory.interface.ts
src/app/pages/account/users/user-form/user-form.component.ts

Go to **Credentials** -> **Users** 
Create a new user. Check the availability of fields that a new user can change.

NAS-121596 / 22.12.3 / Fixed creating a new user fails

---

src/app/services/redirect.service.ts

NAS-121371 / 23.10 / Web Portal for Apps launches after logout - login

---

src/app/interfaces/api-directory.interface.ts
src/app/pages/dashboard/components/dashboard-form/dashboard-form.component.ts
src/app/pages/dashboard/components/dashboard/dashboard.component.ts

Observe that console error is gone.

NAS-121772 / 23.10 / Console error - Unable to save Dashboard State

---

src/app/services/redirect.service.ts

Original PR: https://github.com/truenas/webui/pull/8131
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121371

NAS-121371 / 22.12.3 / Web Portal for Apps launches after logout - login (by undsoft)

---

src/app/modules/alerts/components/alert/alert.component.spec.ts
src/app/modules/jobs/components/job-item/job-item.component.spec.ts
src/app/modules/jobs/components/jobs-panel/jobs-panel.component.spec.ts
src/app/pages/api-keys/components/api-key-list/api-key-list.component.spec.ts
src/app/pages/apps-old/docker-images/docker-image-delete-dialog/docker-image-delete-dialog.component.spec.ts
src/app/pages/apps-old/docker-images/docker-image-update-dialog/docker-image-update-dialog.component.spec.ts
src/app/pages/apps-old/docker-images/docker-images-list/docker-images-list.component.spec.ts
src/app/pages/datasets/modules/snapshots/snapshot-batch-delete-dialog/snapshot-batch-delete-dialog.component.spec.ts
src/app/pages/datasets/modules/snapshots/snapshot-details-row/snapshot-details-row.component.spec.ts
src/app/pages/datasets/modules/snapshots/snapshot-list/snapshot-list.component.spec.ts
src/app/pages/datasets/modules/snapshots/snapshot-rollback-dialog/snapshot-rollback-dialog.component.spec.ts
src/app/pages/datasets/modules/snapshots/testing/snapshot-fake-datasource.ts
src/app/pages/jobs/jobs-list/jobs-list.component.spec.ts
src/app/pages/storage/modules/disks/components/manual-test-dialog/manual-test-dialog.component.spec.ts
src/app/pages/system/bootenv/boot-pool-delete-dialog/boot-pool-delete-dialog.component.spec.ts
src/app/pages/system/bootenv/bootenv-stats-dialog/bootenv-stats-dialog.component.spec.ts
src/app/pages/system/bootenv/bootenv-status/bootenv-status.component.spec.ts

Small change, just need code review.

NAS-121729 / 23.10 / Increase usage of FakeFormatDateTime in unit tests

---

src/app/pages/datasets/components/dataset-management/dataset-management.component.ts

git cherry-pick -x 29c6714b7048a0794614e7fad753eaffd58162ae
git cherry-pick -x 04fbca547b620a42b89c6ab279b731f8c3e544cc
git cherry-pick -x 38d76b7502ef734803294fb2b585e8f110e64cb1
git cherry-pick -x 1f28f20bbf4ed48db8857c46eae46e5dd19c8c5c
git cherry-pick -x b99c34e4aa5967ee51fa5740c741c42815854d5c
Original PR: https://github.com/truenas/webui/pull/8102
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121612

NAS-121612 / 22.12.3 / Import Data Button Appears on Data Protection Header (by AlexKarpov98)

---

src/app/pages/storage/modules/pool-manager/components/inventory/inventory.component.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/create-data-wizard-step/create-data-wizard-step.component.ts
src/app/pages/storage/modules/pool-manager/store/manual-disk-selection-store.service.ts
src/app/pages/storage/modules/pool-manager/store/pools-manager-store.service.ts

NAS-121686 / 23.10 / Add usableUnusedDisks stream

---

package.json
src/app/pages/apps/apps.module.ts
src/app/pages/apps/components/app-detail-view/app-detail-view.component.html
src/app/pages/apps/components/app-detail-view/app-detail-view.component.scss
src/app/pages/apps/components/app-detail-view/app-detail-view.component.ts
yarn.lock

NAS-121750 / 23.10 / Add lightbox for snapshots

---

src/app/modules/layout/components/topbar/power-menu/power-menu.component.spec.ts
src/app/modules/layout/components/topbar/power-menu/power-menu.component.ts
src/app/modules/layout/components/topbar/topbar.component.ts
src/app/pages/system/general-settings/upload-config-dialog/upload-config-dialog.component.spec.ts
src/app/pages/system/general-settings/upload-config-dialog/upload-config-dialog.component.ts
src/app/pages/system/update/manual-update-form/manual-update-form.component.ts
src/app/pages/system/update/update.component.ts
src/app/views/others/reboot/reboot.component.ts

Same as https://github.com/truenas/webui/pull/8170

NAS-120602 / 23.10 / Uncommanded reboot from logging into the web interface

---

src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.html
src/app/pages/system/general-settings/support/support.component.ts

NAS-121721 / 22.12.3 / Dashboard doesn't show actual serial numbers; uses license serials instead

---

src/app/pages/apps/components/installed-apps/app-details-panel/app-details-panel.component.spec.ts
src/app/pages/apps/services/applications.service.spec.ts
src/app/pages/apps/services/applications.service.ts

**Testing** 
Code review should be enough

NAS-121952 / 23.10 / Add tests to ApplicationsService and AppDetailsPanelComponent

---

src/app/pages/common/entity/entity-form/validators/at-least-one-validation.ts
src/app/pages/common/entity/entity-form/validators/compare-validation.ts
src/app/pages/common/entity/entity-form/validators/password-validation.ts
src/app/services/validation.service.ts

**Testing**
Please follow repro steps mentioned in the ticket

NAS-121885 / 13.0 / Sharing > iSCSI > Authorized Access > Add UI is acting weird with secret fields

---

src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.ts
src/app/pages/apps/components/installed-apps/installed-apps.component.ts
src/app/pages/apps/store/available-apps-store.service.ts

Check that the apps table is updated correctly after deleting or updating an apps.

NAS-121320 / 23.10 / Apps table is updated when applications are updated or removed

---

src/app/modules/page-header/page-title-header/page-title-header.component.html
src/app/pages/datasets/modules/snapshots/snapshot-list/snapshot-list.component.html

NAS-119699 / 23.10 / Make active filters in tables more prominent

---

src/app/pages/dashboard/components/dashboard/dashboard.component.html
src/app/pages/dashboard/components/dashboard/dashboard.component.ts
src/app/store/preferences/preferences.actions.ts
src/app/store/preferences/preferences.reducer.ts

For testing please follow the ticket details.

NAS-121123 / 23.10 / Reordered dashboard reversts to initial order

---

.eslintrc.js
src/app/modules/common/summary/summary.component.html
src/app/modules/entity/entity-table/entity-table.component.html
src/app/modules/entity/table/table.component.html
src/app/modules/ix-forms/components/ix-permissions/ix-permissions.component.html
src/app/modules/test-id/test/test.directive.ts
src/app/pages/account/groups/group-list/group-list.component.html
src/app/pages/account/users/user-list/user-list.component.html
src/app/pages/api-keys/components/api-key-list/api-key-list.component.html
src/app/pages/apps-old/docker-images/docker-images-list/docker-images-list.component.html
src/app/pages/datasets/components/dataset-quotas/dataset-quotas-grouplist/dataset-quotas-grouplist.component.html
src/app/pages/datasets/components/dataset-quotas/dataset-quotas-userlist/dataset-quotas-userlist.component.html
src/app/pages/datasets/modules/snapshots/snapshot-list/snapshot-list.component.html
src/app/pages/jobs/jobs-list/jobs-list.component.html
src/app/pages/reports-dashboard/components/report/report.component.html
src/app/pages/services/services.component.html
src/app/pages/system/bootenv/bootenv-list/bootenv-list.component.html
src/app/pages/system/general-settings/ntp-server/ntp-server-card/ntp-server-card.component.html
src/app/pages/system/update/update.component.html
src/app/pages/system/view-enclosure/components/tab-content/tab-content.component.html

NAS-122026 / 23.10 / Enforcing test id attributes for `<table>`

---

src/app/pages/apps/components/chart-wizard/chart-wizard.component.scss
src/app/pages/apps/components/chart-wizard/chart-wizard.component.ts
src/assets/styles/other/_material-reduction.scss

Result:
video: https://github.com/truenas/webui/assets/22980553/8af38001-5309-4547-8d11-aa3aefa464f5
image: <img width="1149" alt="Screenshot 2023-05-18 at 13 47 55" src="https://github.com/truenas/webui/assets/22980553/95082840-8af6-4e13-9304-99d74cdd6f87">

NAS-122020 / 23.10 / Install app form -> Search input fields -> Focus on the selected field

---

tests/bdd/function.py
tests/bdd/ha-bhyve02/test_NAS_T0905.py
tests/bdd/ha-bhyve02/test_NAS_T1073.py

Added refresh before verifying Two-Factor Authentication

TE-658 / 13.0 / Added code to wait that the passive controller is ready

---

src/app/pages/storage/modules/disks/components/manual-test-dialog/manual-test-dialog.component.html
src/app/pages/storage/modules/disks/components/manual-test-dialog/manual-test-dialog.component.scss

NAS-122267 / 23.10 / Manual s.m.a.r.t test modal UI

---

src/app/pages/dashboard/components/dashboard/dashboard.component.html
src/app/pages/dashboard/components/dashboard/dashboard.component.ts
src/app/store/preferences/preferences.actions.ts
src/app/store/preferences/preferences.reducer.ts

git cherry-pick -x 1b5091db038d093e5cc4ca16bf9841ab889e16ef
git cherry-pick -x 07909278f4cdc8308d6395b81582bad9228e3ef7
git cherry-pick -x 993614738c9d1fead70fb192f9d09a5850d86ca7
git reset --hard HEAD~2
git cherry-pick -x f6cef1c9ba66f7150da2ada1c962bf2edb26b0ea
For testing please follow the ticket details.
Original PR: https://github.com/truenas/webui/pull/8169
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121123

NAS-121123 / 22.12.3 / Reordered dashboard reversts to initial order (by AlexKarpov98)

---

src/app/pages/sharing/components/start-service-dialog/start-service-dialog.component.html
src/app/pages/sharing/components/start-service-dialog/start-service-dialog.component.spec.ts
src/app/pages/sharing/smb/smb-form/smb-form.component.ts

**Testing**
Please see repro steps described in the ticket

NAS-122082 / 23.10 / Not starting SMB service when adding a share results in broken form

---

src/app/services/app-schema.service.spec.ts
src/app/services/app-schema.service.ts
src/app/services/app-shema.transformer.ts

Testing: see comment in ticket for url.
Install various apps.
Previous problem occurred when installing apps with lists in them.

NAS-122272 / 22.12.3 / Unable to install apps with lists in schema

---

src/app/services/app-schema.service.spec.ts
src/app/services/app-schema.service.ts
src/app/services/app-shema.transformer.ts

Testing: see comment in ticket for url.
Install various apps.
Previous problem occurred when installing apps with lists in them.
Original PR: https://github.com/truenas/webui/pull/8270
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122272

NAS-122272 / 22.12.4 / Unable to install apps with lists in schema (by undsoft)

---

src/app/services/schema/app-schema.service.spec.ts
src/app/services/schema/app-schema.service.ts

Testing: see comment in ticket for url.
Install various apps.
Previous problem occurred when installing apps with lists in them.
Original PR: https://github.com/truenas/webui/pull/8270
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122272

NAS-122272 / 23.10 / Unable to install apps with lists in schema (by undsoft)

---

src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/pool-manager-wizard.component.html
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/pool-manager-wizard.component.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/1-general-wizard-step/general-wizard-step.component.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/2-enclosure-wizard-step/enclosure-wizard-step.component.html
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/2-enclosure-wizard-step/enclosure-wizard-step.component.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/3-data-wizard-step/data-wizard-step.component.html
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/3-data-wizard-step/data-wizard-step.component.ts

Steps, Next, Back -> are disabled once step is invalid.

NAS-122315 / 23.10 / It's possble to skip steps with validation errors by clicking the next step title - Pool Creation Manager

---

src/app/modules/alerts/components/alert/alert.component.scss

Testing: see that alerts look good.

NAS-122403 / 23.10 / Styles fixes in alerts

---

src/app/modules/entity/table/table.component.html

NAS-122407 / 23.10 / Impossible to terminate other specific sessions

---

src/app/pages/apps/components/app-detail-view/app-available-info-card/app-available-info-card.component.html
src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.html
src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.scss
src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.spec.ts
src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.ts

Sync sources between two places.
For testing, you can check the `AppInfoCard` and `AppAvailableInfoCard`

NAS-122351 / 23.10 / Apply getCleanLink to sources on the AppInfoCard

---

src/app/pages/apps/apps.module.ts
src/app/pages/apps/components/app-detail-view/app-detail-view.component.ts
src/app/pages/apps/components/app-detail-view/app-details-header/app-details-header.component.spec.ts
src/app/pages/apps/components/app-detail-view/app-details-header/app-details-header.component.ts
src/app/pages/apps/components/app-detail-view/app-resources-card/app-resources-card.component.spec.ts
src/app/pages/apps/components/app-detail-view/app-resources-card/app-resources-card.component.ts
src/app/pages/apps/components/available-apps/app-card/app-card.component.spec.ts
src/app/pages/apps/components/available-apps/app-card/app-card.component.ts
src/app/pages/apps/components/available-apps/available-apps-header/available-apps-header.component.spec.ts
src/app/pages/apps/components/available-apps/available-apps-header/available-apps-header.component.ts
src/app/pages/apps/components/available-apps/available-apps.component.ts
src/app/pages/apps/components/installed-apps/app-settings-button/app-settings-button.component.spec.ts
src/app/pages/apps/components/installed-apps/app-settings-button/app-settings-button.component.ts
src/app/pages/apps/components/installed-apps/installed-apps.component.ts
src/app/pages/apps/store/apps-store.service.spec.ts
src/app/pages/apps/store/apps-store.service.ts

Just renaming. CI should pass. Code review is enough.

NAS-122350 / 23.10 / Rename AvailableAppsStore to AppsStore

---

src/app/modules/terminal/components/terminal/terminal.component.ts

Testing: open shell and wait 5 minutes. Previously terminal would reconnect.

NAS-122229 / 23.10 / Fixing shell reconnects

---

src/app/pages/apps/components/app-detail-view/app-available-info-card/app-available-info-card.component.html
src/app/pages/apps/components/app-detail-view/app-available-info-card/app-available-info-card.component.scss
src/app/pages/apps/components/app-detail-view/app-available-info-card/app-available-info-card.component.spec.ts
src/app/pages/apps/components/app-detail-view/app-details-header/app-details-header.component.html
src/app/pages/apps/components/app-detail-view/app-details-header/app-details-header.component.scss
src/app/pages/apps/components/app-detail-view/app-details-header/app-details-header.component.spec.ts
src/app/pages/apps/components/app-detail-view/app-helm-chart-card/app-helm-chart-card.component.html
src/app/pages/apps/components/app-detail-view/app-helm-chart-card/app-helm-chart-card.component.scss
src/app/pages/apps/components/app-detail-view/app-helm-chart-card/app-helm-chart-card.component.spec.ts
src/app/pages/apps/components/app-detail-view/app-resources-card/app-resources-card.component.html
src/app/pages/apps/components/app-detail-view/app-resources-card/app-resources-card.component.scss
src/app/pages/apps/components/app-detail-view/app-resources-card/app-resources-card.component.spec.ts

Minor adjustments to improve loading state.
As it now:
How it will look like:

NAS-122352 / 23.10 / Improve loading state on detail view page

---

src/app/pages/apps/components/chart-wizard/chart-wizard.component.spec.ts
src/app/pages/apps/components/chart-wizard/chart-wizard.component.ts

For testing, try to use the installed app's name when installing a new one

NAS-122623 / 23.10 / Use forbiddenAsyncValues validator for app name

---

src/app/pages/apps/components/chart-wizard/chart-wizard.component.spec.ts
src/app/pages/apps/components/chart-wizard/chart-wizard.component.ts

Testing:
Go to New Apps, Unset Pool.
Go to install page (manually for example http://localhost:4200/apps/available/TRUENAS/charts/minio/install)
You should be navigated to App detail page
http://localhost:4200/apps/available/TRUENAS/charts/minio

NAS-122661 / 23.10 / App Install form is available if pool is not set

---

src/app/pages/apps/components/available-apps/available-apps.component.html
src/app/pages/apps/components/available-apps/available-apps.component.ts
src/app/pages/apps/store/apps-filter-store.service.ts

Testing -> do what is described in ticket:

NAS-122600 / 23.10 / Different number of apps shown based on sorting

---

src/app/modules/ix-feedback/feedback-dialog/feedback-dialog.component.spec.ts
src/app/modules/ix-feedback/feedback-dialog/feedback-dialog.component.ts

For testing, try to submit a review

NAS-122687 / 23.10 / Fix payload to feedback service

---

src/app/modules/page-header/is-new-indicator/new-page-badge.component.scss
src/app/pages/apps/components/installed-apps/app-history-card/app-history-card.component.scss

End result is:
https://github.com/truenas/webui/assets/22980553/1551b6b2-9c55-43ec-ace1-9b4be63975d1

NAS-122613 / 23.10 / Installed Apps: Wrap text on the mini card on the History card

---

src/app/interfaces/api-message.interface.ts
src/app/modules/jobs/store/job.effects.ts
src/app/pages/account/groups/store/group.effects.ts
src/app/pages/account/users/store/user.effects.ts
src/app/pages/apps/services/applications.service.ts
src/app/pages/apps/store/apps-store.service.spec.ts
src/app/pages/apps/store/installed-apps-store.service.spec.ts
src/app/pages/apps/store/installed-apps-store.service.ts

Check that after installing an app, the installed apps table is shown and the app recently installed is shown on the table. Also check that the app has the installed badge on the apps dashboard.
Check the opposite when deleting an app. The table should update and the badge should be removed in apps dashboard.

NAS-121778 / 23.10 / Fixing installed apps updates

---

src/app/pages/system/general-settings/gui/gui-form/gui-form.component.spec.ts
src/app/services/websocket-connection.service.ts
src/app/views/sessions/signin/signin.component.ts

I was able to reproduce original issue by logging in, closing laptop and waiting for ~10 minutes.
You may be able to put system to sleep or do something similar.

NAS-122757 / 23.10 / Maximum number of concurrent calls (20) has exceeded

---

src/app/pages/system/advanced/sessions/sessions-card/sessions-card.component.html
src/app/pages/system/advanced/sessions/sessions-card/sessions-card.component.spec.ts
src/app/pages/system/advanced/sessions/sessions-card/sessions-card.component.ts
src/app/pages/system/advanced/sessions/token-settings/token-settings.component.ts

NAS-122755 / 23.10 / High token settings values

---

src/assets/styles/other/_root-variables.scss

NAS-122799 / 23.10 / Select see-through issue

---

src/app/modules/jobs/components/job-item/job-item.component.html
src/app/modules/jobs/components/job-item/job-item.component.scss
src/app/modules/jobs/components/jobs-panel/jobs-panel.component.html
src/app/modules/jobs/components/jobs-panel/jobs-panel.component.scss
src/app/modules/layout/components/admin-layout/admin-layout.component.ts
src/app/modules/layout/components/topbar/user-menu/user-menu.component.spec.ts
src/app/modules/page-header/page-title-header/page-title-header.component.html
src/app/modules/page-header/page-title-header/page-title-header.component.scss
src/app/pages/account/users/user-form/user-form.component.html
src/app/pages/account/users/user-form/user-form.component.scss
src/app/pages/credentials/certificates-dash/certificate-edit/certificate-edit.component.spec.ts
src/app/pages/datasets/components/dataset-details-panel/dataset-details-panel.component.spec.ts
src/app/pages/datasets/components/dataset-quotas/dataset-quotas-userlist/dataset-quotas-userlist.component.spec.ts
src/app/pages/jobs/jobs-list/jobs-list.component.spec.ts
src/app/pages/reports-dashboard/reports-dashboard.component.html
src/app/pages/reports-dashboard/reports-dashboard.component.scss
src/app/pages/system/advanced/sessions/sessions-card/sessions-card.component.html
src/app/pages/system/advanced/sessions/sessions-card/sessions-card.component.scss
src/app/pages/system/general-settings/ntp-server/ntp-server-card/ntp-server-card.component.spec.ts

NAS-122547 / 23.10 / Reducing warnings and other cleanup

---

src/app/pages/apps/components/installed-apps/app-row/app-row.component.ts
src/app/pages/apps/components/installed-apps/installed-apps.component.html

NAS-122853 / 23.10 / Installed apps -> select all is not working

---

src/app/app.component.ts
src/index.html

Check ticket description:
https://github.com/truenas/webui/assets/22980553/2586d959-2712-486a-99b4-5edd1b19105a

NAS-121496 / 23.10 / Favicons unreadable with dark mode browsers

---

src/app/modules/jobs/components/job-item/job-item.component.scss
src/app/pages/jobs/job-logs-row/job-logs-row.component.scss

Check this message: (description)

NAS-122877 / 23.10 / Job progress description newlines in task manager

---

src/app/pages/apps/components/available-apps/available-apps-header/available-apps-header.component.scss
src/app/pages/apps/components/available-apps/available-apps-header/available-apps-header.component.ts

NAS-122856 / 23.10 / Discover apps -> filters -> fast switching bug

---

src/app/pages/apps/components/chart-wizard/chart-wizard.component.ts

See ticket for more details:
https://github.com/truenas/webui/assets/22980553/c027b486-151d-4b95-a3cf-ae59cd7e3209

NAS-122695 / 23.10 / Cobia: WG-Easy App - updating storage does not take user to applications page

---

src/app/pages/applications/forms/chart-form/chart-form.component.spec.ts
src/app/services/app-schema.helpers.ts
src/app/services/app-schema.service.spec.ts
src/app/services/app-schema.service.ts

Backported 2 PR's from master:
- https://github.com/truenas/webui/pull/8423
- https://github.com/truenas/webui/pull/8417

NAS-122794 / 22.12.4 / show_subquestions_if and show_if nested wrong initial state. 

---

src/app/pages/apps/components/installed-apps/app-containers-card/app-containers-card.component.html
src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.html
src/app/pages/apps/components/installed-apps/app-metadata-card/app-metadata-card.component.html
src/app/pages/datasets/components/dataset-capacity-management-card/dataset-capacity-management-card.component.html
src/app/pages/datasets/components/dataset-details-card/dataset-details-card.component.html
src/app/pages/storage/modules/devices/components/disk-info-card/disk-info-card.component.html
src/app/pages/storage/modules/devices/components/hardware-disk-encryption/hardware-disk-encryption.component.html
src/app/pages/storage/modules/devices/components/smart-info-card/smart-info-card.component.html
src/app/pages/storage/modules/devices/components/zfs-info-card/zfs-info-card.component.html
src/app/pages/storage/modules/pool-manager/components/configuration-preview/configuration-preview.component.html
src/app/pages/storage/modules/pool-manager/components/inventory/inventory.component.html

NAS-122907 / 23.10 / Request consistent rendering of label and value

---

src/app/pages/datasets/components/dataset-capacity-management-card/dataset-capacity-management-card.component.ts

See ticket for testing instructions.

NAS-122973 / 23.10 / Refreshing dataset details after quota updates

---

src/app/pages/account/users/user-form/user-form.component.ts

**Testing**
See ticket for repro steps

NAS-122953 / 23.10 / Fix `home_mode` issue

---

src/app/pages/storage/components/unused-resources/unused-resources.component.ts

NAS-122967 / 23.10 / Maximum number of concurrent calls (20) has exceeded when exporting a pool

---

src/app/modules/ix-forms/components/ix-label/ix-label.component.scss
src/app/pages/storage/modules/pool-manager/components/manual-disk-selection/components/manual-selection-vdev/manual-selection-vdev.component.html
src/app/pages/storage/modules/pool-manager/components/manual-disk-selection/components/manual-selection-vdev/manual-selection-vdev.component.scss

NAS-122964 / 23.10 / Font for errors on New Pool Manual selection is too small to be readable

---

src/app/services/schema/app-schema.service.ts

Testing: 
See ticket and this image.

NAS-123150 / 23.10 / [Scale/Apps/UI] Whole Section is not editable on App Edit

---

src/app/pages/credentials/certificates-dash/forms/acmedns-form/acmedns-form.component.spec.ts
src/app/pages/credentials/certificates-dash/forms/acmedns-form/acmedns-form.component.ts

Check ticket description for testing instructions

NAS-122998 / 23.10 / Setting that hidden flag correctly so form control is hidden as well as disabled

---

src/app/modules/ix-table2/components/ix-table-expandable-row/ix-table-expandable-row.component.html
src/app/modules/ix-table2/components/ix-table-expandable-row/ix-table-expandable-row.component.scss
src/app/modules/ix-table2/components/ix-table-expandable-row/ix-table-expandable-row.component.ts
src/app/modules/ix-table2/directives/ix-table-empty.directive.ts
src/app/modules/ix-table2/ix-table2.module.ts
src/app/modules/ix-tables/ix-table.module.ts
src/app/pages/account/users/user-list/user-list.component.html
src/app/pages/account/users/user-list/user-list.component.spec.ts
src/app/pages/account/users/users.module.ts
src/app/pages/apps/components/catalogs/catalogs.component.html
src/app/pages/data-protection/vmware-snapshot/vmware-snapshot-list/vmware-snapshot-list.component.html
src/app/pages/network/components/static-routes-card/static-routes-card.component.html
src/app/pages/network/components/static-routes-card/static-routes-card.component.scss
src/app/pages/system/bootenv/bootenv-list/bootenv-list.component.html
src/app/pages/system/bootenv/bootenv-list/bootenv-list.component.ts

NAS-123115 / 23.10 / Minor fixes for tables

---

src/app/pages/dashboard/store/dashboard-storage-store.service.ts

Test that the dashboard loads with 0 pools and with >= 1 pools in storage.

NAS-123306 / 23.10 / Returning observable instead of array

---

src/app/pages/dashboard/store/dashboard-storage-store.service.ts

Test that the dashboard loads with 0 pools and with >= 1 pools in storage.
Original PR: https://github.com/truenas/webui/pull/8523
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123306

NAS-123306 / 23.10-BETA.1 / Returning observable instead of array (by RehanY147)

---

src/app/pages/dashboard/store/dashboard-storage-store.service.ts

Test that the dashboard loads with 0 pools and with >= 1 pools in storage.
Original PR: https://github.com/truenas/webui/pull/8523
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123306

NAS-123306 / 24.04 / Returning observable instead of array (by RehanY147)

---

src/assets/styles/other/_root-variables.scss

Testing:
Check that checkboxes have visual feedback on hover, focus

NAS-123055 / 24.04 / Missing focus states for checkboxes

---

src/app/pages/data-protection/replication/replication-wizard/replication-wizard.component.ts

For testing, make sure you can create a local replication task with a `Run Once` schedule.

NAS-123196 / 24.04 / Fix payload for Replication Wizard

---

src/assets/styles/other/_root-variables.scss

Testing:
Check that checkboxes have visual feedback on hover, focus
Original PR: https://github.com/truenas/webui/pull/8533
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123055

NAS-123055 / 23.10 / Missing focus states for checkboxes (by AlexKarpov98)

---

src/app/pages/reports-dashboard/components/line-chart/line-chart.component.ts
src/app/pages/reports-dashboard/components/report/report.component.html
src/app/pages/reports-dashboard/components/report/report.component.ts
src/app/pages/reports-dashboard/reports-dashboard.module.ts

For testing, go to reporting and select range using a cursor on any chart, then check the `Start/End` dates below the chart. Also, try to mouse over the x-axis to see the exact date and time above the legend.

NAS-122296 / 24.04 / Update time interval when manual zoom on Reports

---

src/app/pages/sharing/smb/smb-form/smb-form.component.ts

NAS-123432 / 24.04 / Link to learn more about Host Allow in SMB, points to 404

---

scripts/run_related_tests.js
src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.html
src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.spec.ts

NAS-123460 / 24.04 / Show App Version and Chart Version on two lines

---

src/app/pages/sharing/smb/smb-form/smb-form.component.ts

Check ticket description
Original PR: https://github.com/truenas/webui/pull/8548
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123432

NAS-123432 / 23.10-BETA.1 / Link to learn more about Host Allow in SMB, points to 404 (by AlexKarpov98)

---

src/app/pages/data-protection/data-protection-dashboard.component.ts

git cherry-pick -x 5eb1be8461a83e9cdbf983f87ef267323cc0736a
git cherry-pick -x 9492da9e0db366c73cd0aa05755a2fb9a1dbf11d
Original PR: https://github.com/truenas/webui/pull/8507
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122920

NAS-122920 / 23.10 / Don't refresh table until the job has concluded (by RehanY147)

---

src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/2-enclosure-wizard-step/enclosure-wizard-step.component.ts

NAS-123450 / 24.04 / New Pool Creation wizard - multiple enclosures button states incorrect

---

src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/2-enclosure-wizard-step/enclosure-wizard-step.component.ts

Original PR: https://github.com/truenas/webui/pull/8566
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123450

NAS-123450 / 23.10 / New Pool Creation wizard - multiple enclosures button states incorrect (by AlexKarpov98)

---

src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/2-enclosure-wizard-step/enclosure-wizard-step.component.ts

Original PR: https://github.com/truenas/webui/pull/8566
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123450

NAS-123450 / 23.10-BETA.1 / New Pool Creation wizard - multiple enclosures button states incorrect (by AlexKarpov98)

---

src/app/modules/ix-dynamic-form/components/ix-dynamic-form/ix-dynamic-form-item/ix-dynamic-form-item.component.ts
src/assets/i18n/fr.json

Make sure that Shares are working on `Install WebDAV` page.

NAS-123480 / 24.04 / WebDAV Install missing "Add Share" button. produces error unable to resolve

---

src/app/modules/ix-dynamic-form/components/ix-dynamic-form/ix-dynamic-form-item/ix-dynamic-form-item.component.ts
src/assets/i18n/fr.json

Make sure that Shares are working on `Install WebDAV` page.
Original PR: https://github.com/truenas/webui/pull/8574
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123480

NAS-123480 / 23.10-BETA.1 / WebDAV Install missing "Add Share" button. produces error unable to resolve (by AlexKarpov98)

---

src/app/helptext/directoryservice/activedirectory.ts
src/app/helptext/sharing/afp/afp.ts
src/app/helptext/sharing/iscsi/iscsi.ts
src/app/helptext/sharing/smb/smb.ts
src/app/helptext/task-calendar/initshutdown/initshutdown.ts
src/app/helptext/task-calendar/replication/replication.ts
src/app/helptext/vm/devices/device-add-edit.ts
src/app/pages/system/ssh-connections/ssh-connections-form/ssh-connections-form.component.ts

NAS-115410 / 13.0 / Minor text changes

---

src/app/interfaces/events/index.ts
src/app/interfaces/events/network-interfaces-changed-event.interface.ts
src/app/modules/layout/components/topbar/topbar.component.ts
src/app/pages/network/components/interface-form/interface-form.component.spec.ts
src/app/pages/network/components/interface-form/interface-form.component.ts
src/app/pages/network/components/interfaces-card/interfaces-card.component.ts
src/app/pages/network/components/network-configuration-card/network-configuration-card.component.ts
src/app/pages/network/network.component.ts
src/app/store/admin-panel/admin.actions.ts

Testing: 
Check ticket and work of `Network Interfaces`.

NAS-123499 / 24.04 / Replace usages of NetworkInterfacesChanged with something else

---

src/assets/styles/components/_charts.scss

git cherry-pick -x 43ffece493f41bb4fe83ad8635d2a74c4a8dc7c5
git cherry-pick -x b9ea7853984a601b4ca61a6bd36f4562e5994e0e
For testing, go to reporting and check the cursor on legend items.
Original PR: https://github.com/truenas/webui/pull/8592
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123328

NAS-123328 / 23.10 / Update cursor for legend items on Reporting (by denysbutenko)

---

src/app/pages/dashboard/components/widget-network/widget-network.component.ts

git cherry-pick -x ff59d313f4ef462db81ba9d2961dc1701af132d7
git cherry-pick -x 5f0d49fdc5d6db3714074b258200fdbdea9b54cf
Original PR: https://github.com/truenas/webui/pull/8584
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123362

NAS-123362 / 24.04 / Removed calls interval when component has closed (by RehanY147)

---

src/app/modules/alerts/components/alerts-panel/alerts-panel.component.spec.ts
src/app/modules/alerts/store/alert.actions.ts
src/app/modules/alerts/store/alert.effects.ts
src/app/modules/alerts/store/alert.reducer.ts

Testing:
Check that alerts are working and new one comes on the list.
The end solution came up after talking to V. Vinogradenko.

NAS-123151 / 24.04 / HA: Alert is duplicated

---

src/app/pages/data-protection/data-protection.module.ts

Testing: see Add button on Data Protection -> VMware Snapshots Integration.
Original PR: https://github.com/truenas/webui/pull/8603
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123562

NAS-123562 / 23.10 / Restoring Add button on VMware Snapshots (by undsoft)

---

src/app/modules/ix-table2/components/ix-table-body/ix-table-body.component.html
src/app/modules/ix-table2/components/ix-table-body/ix-table-body.component.ts
src/app/modules/ix-table2/interfaces/table-column.interface.ts
src/app/pages/account/users/user-list/user-list.component.ts

NAS-123014 / 24.04 / Add identifier field

---

src/app/pages/reports-dashboard/components/line-chart/line-chart.component.ts
src/app/pages/reports-dashboard/utils/report.utils.ts

NAS-116079 / 24.04 / dashboard network bandwidth issues

---

src/app/pages/storage/components/dashboard-pool/topology-card/topology-card.component.html
src/app/pages/storage/components/dashboard-pool/topology-card/topology-card.component.spec.ts
src/app/pages/storage/components/dashboard-pool/topology-card/topology-card.component.ts

Testing: see ticket:
**Before:**
**After:**

NAS-121466 / 24.04 / Topology overview hides VDEV information if there is a warning for redundancy mismatch

---

src/app/pages/data-protection/replication/replication-form/properties-override-validator/properties-override-validator.service.ts
src/app/pages/data-protection/replication/replication-form/replication-form.component.html
src/app/pages/data-protection/replication/replication-form/replication-form.component.ts

Testing:
Check Replication Task Advanced form SAVE button.
It should be disabled if form is invalid. (previously it was always active)

NAS-123647 / 24.04 / Add Replication Task Advanced Form [SAVE] button - is always active

---

src/app/pages/storage/components/dashboard-pool/topology-card/topology-card.component.html
src/app/pages/storage/components/dashboard-pool/topology-card/topology-card.component.spec.ts
src/app/pages/storage/components/dashboard-pool/topology-card/topology-card.component.ts

git cherry-pick -x e6591f5f6f414c4b45ccbe8887af3db1e38e5024
git cherry-pick -x 86be9b376acecf200fd9dd1ee54c1f7256d10090
git cherry-pick -x 3c77a0a32fa5eff8976338ff0dea907b8b7d0fbb
Testing: see ticket:
**Before:**
**After:**
Original PR: https://github.com/truenas/webui/pull/8647
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121466

NAS-121466 / 22.12.4 / Topology overview hides VDEV information if there is a warning for redundancy mismatch (by AlexKarpov98)

---

src/app/pages/reports-dashboard/components/report/report.component.html
src/app/pages/reports-dashboard/components/report/report.component.ts

git cherry-pick -x 765f15e5b0f2790361804952358e66d785207445
git reset --hard HEAD~4
git cherry-pick -x 7c1e2589f4369b7b2a6a98472341c9b2959a14d9
Original PR: https://github.com/truenas/webui/pull/8604
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122287

NAS-122287 / 23.10 / Reporting:  Graph resets from a past date/time to current date/time when change the zoom increment (by AlexKarpov98)

---

src/app/pages/data-protection/data-protection-dashboard.component.ts
src/app/pages/data-protection/replication/replication-list/replication-list.component.ts

git cherry-pick -x bcb49f85cb3128e1f224eb33224e3862768118dc
git cherry-pick -x 6e4140547f45a0d08ef1f80b9df04897eb64697b
git cherry-pick -x b7de29bb3c527d13905919da469bf1316ee16b61
Testing:
Check that Replication Task - STATE error modal message is readable.
**Before:**
**After:**
Original PR: https://github.com/truenas/webui/pull/8645
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122321

NAS-122321 / 23.10 / Text field unreadable (by AlexKarpov98)

---

src/app/modules/alerts/components/alerts-panel/alerts-panel.component.spec.ts
src/app/modules/alerts/store/alert.actions.ts
src/app/modules/alerts/store/alert.effects.ts
src/app/modules/alerts/store/alert.reducer.ts

Testing:
Check that alerts are working and new one comes on the list.
The end solution came up after talking to V. Vinogradenko.
Original PR: https://github.com/truenas/webui/pull/8582
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123151

NAS-123151 / 23.10 / HA: Alert is duplicated (by AlexKarpov98)

---

src/app/pages/data-protection/components/data-protection-dashboard/data-protection-dashboard.component.ts
src/app/pages/data-protection/replication/replication-list/replication-list.component.ts

git cherry-pick -x da11af71226dde5dd55f03ac267d7e4252190a6c
git cherry-pick -x 2af6b8ae3fb8dbceca9352805b08704ce65faad5
git cherry-pick -x 0434e136193c42a36df03ad745ecdeeab3599923
Original PR: https://github.com/truenas/webui/pull/8653
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122321

NAS-122321 / 22.12.4 / Text field unreadable (by AlexKarpov98) (by bugclerk)

---

src/app/pages/apps/components/installed-apps/app-containers-card/app-containers-card.component.html

NAS-123634 / 24.04 / Logs/Shell button is missing for apps that are in "Deploying" state

---

src/app/pages/apps/components/installed-apps/app-containers-card/app-containers-card.component.html

Original PR: https://github.com/truenas/webui/pull/8643
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123634

NAS-123634 / 23.10 / Logs/Shell button is missing for apps that are in "Deploying" state (by AlexKarpov98)

---

src/app/pages/apps/components/installed-apps/installed-apps.component.spec.ts

Backported
Code review should be enough
Original PR: https://github.com/truenas/webui/pull/8611

NAS-123494 / 23.10 / Add integration test for apps

---

src/app/pages/apps/components/app-detail-view/app-detail-view.component.html
src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.html
src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.ts
src/app/pages/apps/components/installed-apps/app-row/app-row.component.html
src/app/pages/apps/components/installed-apps/app-row/app-row.component.ts
src/app/pages/apps/components/installed-apps/app-upgrade-dialog/app-upgrade-dialog.component.html

git cherry-pick -x 6ac72d1f76e8525f9a8fb4c1ce53091492c2d365
git cherry-pick -x 41fd379d0b2c3376d59633f6fb87c288f30b6eb3
git cherry-pick -x 41f7faff37b7f21db7f7117b38880ca90b94fe5a
Original PR: https://github.com/truenas/webui/pull/8660
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123666

NAS-123666 / 23.10-BETA.1 / Add placeholder when image failed to load on Apps (by denysbutenko)

---

src/app/pages/dashboard/components/dashboard/dashboard.component.html
src/app/pages/dashboard/components/widget-nic/widget-nic.component.scss
src/app/pages/dashboard/components/widget-pool-wrapper/widget-pool-wrapper.component.html
src/app/pages/dashboard/components/widget-pool/widget-pool.component.scss
src/app/pages/dashboard/store/dashboard-store.service.ts

**Testing**
Please see ticket for replication steps

NAS-123642 / 24.04 / Fix reordering on dashboard

---

src/app/pages/dashboard/components/dashboard/dashboard.component.html
src/app/pages/dashboard/components/widget-nic/widget-nic.component.scss
src/app/pages/dashboard/components/widget-pool-wrapper/widget-pool-wrapper.component.html
src/app/pages/dashboard/components/widget-pool/widget-pool.component.scss
src/app/pages/dashboard/store/dashboard-store.service.ts

**Testing**
Please see ticket for replication steps
Original PR: https://github.com/truenas/webui/pull/8661
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123642

NAS-123642 / 23.10 / Fix reordering on dashboard (by bvasilenko)

---

src/app/core/components/directives/html-tooltip/html-tooltip.directive.ts
src/app/core/components/directives/text-limiter/text-limiter.directive.ts

git cherry-pick -x c806cae52c047ad049636502fdb1da02371dd938
git cherry-pick -x 6f26414180a5a8155cc7be5ce279494913fdffb1
See ticket please
Original PR: https://github.com/truenas/webui/pull/8684
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120309

NAS-120309 / 23.10 / cdk-overlay-pane class HTML divs build up in the DOM and cause the UI to become sluggish (by bvasilenko)

---

src/app/modules/ix-forms/components/ix-chips/ix-chips.component.html
src/app/modules/ix-forms/components/ix-chips/ix-chips.component.spec.ts
src/app/modules/ix-forms/components/ix-chips/ix-chips.component.ts
src/assets/styles/other/_tn-styles.scss

git cherry-pick -x 7b63804671b7ebdbb3ffd06add638fd63ee0ad24
git cherry-pick -x 4966d1cd91b689d83eff3fa25d1473f921b02bd5
Original PR: https://github.com/truenas/webui/pull/8679
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123699

NAS-123699 / 23.10 / Cobia BETA.1: Sudo Commands fields on Edit User are not saving (by AlexKarpov98)

---

src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/pool-manager-wizard.component.spec.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/pool-manager-wizard.component.ts
src/app/pages/storage/modules/pool-manager/enums/pool-creation-wizard-step.enum.ts

NAS-123695 / 24.04 / Bug – fast clicking user can click on Data, but end up on Enclosure Options

---

src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/pool-manager-wizard.component.spec.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/pool-manager-wizard.component.ts
src/app/pages/storage/modules/pool-manager/enums/pool-creation-wizard-step.enum.ts

Original PR: https://github.com/truenas/webui/pull/8690
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123695

NAS-123695 / 23.10 / Bug – fast clicking user can click on Data, but end up on Enclosure Options (by AlexKarpov98)

---

src/app/modules/loader/components/fake-progress-bar/fake-progress-bar.component.scss
src/app/pages/apps/components/installed-apps/app-containers-card/app-containers-card.component.scss
src/app/pages/apps/components/installed-apps/app-row/app-row.component.html
src/app/pages/apps/components/installed-apps/app-row/app-row.component.spec.ts
src/app/pages/apps/components/installed-apps/app-row/app-row.component.ts
src/app/pages/apps/components/installed-apps/installed-apps.component.html
src/app/pages/apps/components/installed-apps/installed-apps.component.ts
src/app/pages/apps/services/applications.service.ts
src/app/pages/apps/store/installed-apps-store.service.spec.ts
src/app/pages/apps/store/installed-apps-store.service.ts

- Removed 4px preserved for scrollbar in fake-progress-bar.
- Enable text wrapping for values
- Sync app status across tabs
Original PR: https://github.com/truenas/webui/pull/8689
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123633

NAS-123633 / 23.10 / Sync app status across tabs and other fixes to Apps (by denysbutenko)

---

src/app/modules/layout/components/topbar/topbar.component.scss
src/app/pages/dashboard/components/widget-controller/widget-controller.component.html
src/app/pages/dashboard/components/widget-controller/widget-controller.component.ts

For testing, ensure the main dashboard looks good in mobile browsers.

NAS-123812 / 24.04 / Fix logo mobile safari and removed duplicate Pool word

---

src/app/modules/ix-forms/components/ix-fieldset/ix-fieldset.harness.ts
src/app/modules/ix-forms/components/ix-select/ix-select.harness.ts
src/app/modules/ix-forms/testing/control-harnesses.helpers.ts
src/app/modules/ix-forms/testing/ix-form.harness.ts
src/app/pages/storage/modules/pool-manager/components/configuration-preview/configuration-preview.component.spec.ts
src/app/pages/storage/modules/pool-manager/components/configuration-preview/configuration-preview.harness.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/pool-warnings/pool-warnings.component.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager/tests/common.utils.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager/tests/pool-manager.harness.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager/tests/unsetting-on-fewer-disks.spec.ts
src/app/pages/storage/modules/pool-manager/store/pool-manager.store.ts
src/app/pages/storage/modules/pool-manager/utils/generate-vdevs/generate-vdevs.service.ts

Testing: test in scenarios where something was selected in steps, but then due to changes in enclosure settings or exported pools, there are no longer enough disks to satisfy the form.

NAS-123438 / 24.04 / Add integration tests to pool manager

---

src/app/pages/system/view-enclosure/components/view-enclosure/view-enclosure.component.html

NAS-123813 / 24.04 / Enclosure page A symbol

---

src/app/modules/ix-table2/components/ix-table-body/ix-table-body.component.html

NAS-123711 / 24.04 / ix-table2 toggle collapse UI issue

---

src/app/modules/ix-table2/components/ix-table-body/ix-table-body.component.html

Result:
Original PR: https://github.com/truenas/webui/pull/8711
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123711

NAS-123711 / 23.10 / ix-table2 toggle collapse UI issue (by AlexKarpov98)

---

src/app/pages/system/view-enclosure/components/view-enclosure/view-enclosure.component.html

Original PR: https://github.com/truenas/webui/pull/8701
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123813

NAS-123813 / 23.10 / Enclosure page A symbol (by AlexKarpov98)

---

src/app/pages/storage/components/dashboard-pool/topology-card/topology-card.component.html
src/app/pages/storage/components/dashboard-pool/topology-card/topology-card.component.ts

Testing: see ticket and comments

NAS-123742 / 24.04 / Spares not properly identified on Storage Dashboard for dRAID pools

---

src/app/pages/datasets/components/dataset-management/dataset-management.component.ts

Backported
Original PR: https://github.com/truenas/webui/pull/8721

NAS-123802 / 23.10 / Fix position of children in dataset tree

---

src/app/core/components/directives/details-height/details-height.directive.ts
src/app/modules/layout/components/admin-layout/admin-layout.component.scss
src/app/pages/apps/components/installed-apps/installed-apps.component.html
src/app/pages/apps/components/installed-apps/installed-apps.component.scss
src/app/pages/datasets/components/dataset-details-card/dataset-details-card.component.html
src/app/pages/datasets/components/dataset-details-panel/dataset-details-panel.component.scss
src/assets/styles/mixins/cards.scss

git cherry-pick -x b0eb3b7eb01e11e27a689de55c9f986f2d19dcf9
git reset --hard HEAD~3
git cherry-pick -x 614e6e77e59eda9003f3b500072cbc892f7aaac6
The height for both columns should be equal.
Original PR: https://github.com/truenas/webui/pull/8703
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123811

NAS-123811 / 23.10 / Layout fixes for Datasets and Apps (by denysbutenko)

---

src/app/pages/datasets/components/dataset-management/dataset-management.component.ts

Backported
Original PR: https://github.com/truenas/webui/pull/8721
Original PR: https://github.com/truenas/webui/pull/8732
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123802

NAS-123802 / 23.10-BETA.1 / Fix position of children in dataset tree (by bvasilenko)

---

src/app/pages/system/file-ticket/file-ticket-form/components/jira-oauth/jira-oauth.component.ts
src/app/pages/system/file-ticket/file-ticket-form/file-ticket-form.component.spec.ts

For testing see details in the ticket

NAS-123762 / 24.04 / Fix JIRA token in File Ticket form

---

src/app/pages/system/file-ticket/file-ticket-form/components/jira-oauth/jira-oauth.component.ts
src/app/pages/system/file-ticket/file-ticket-form/file-ticket-form.component.spec.ts

For testing see details in the ticket
Original PR: https://github.com/truenas/webui/pull/8718
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123762

NAS-123762 / 23.10 / Fix JIRA token in File Ticket form (by denysbutenko)

---

src/app/pages/reports-dashboard/reports-dashboard.component.ts

Original PR: https://github.com/truenas/webui/pull/8691
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123563

NAS-123563 / 23.10 / duplicate "ZFS ARC Result" graphs in reporting section of webUI (by AlexKarpov98)

---

src/app/views/sessions/signin/set-admin-password-form/set-admin-password-form.component.html

NAS-123834 / 24.04 / Fix disabling `Sign In` button

---

src/app/pages/apps/components/chart-wizard/chart-wizard.component.ts

**Summary**
Removed the line which was hiding the error modal window after it was already shown, which makes bad UX - "blinking" of error modal window
**Testing**
See ticket please

NAS-123902 / 24.04 / Show error message

---

src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/layout-step/automated-disk-selection/normal-selection/normal-selection.component.html
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/layout-step/automated-disk-selection/normal-selection/normal-selection.component.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/layout-step/layout-step.component.ts

git cherry-pick -x 5f3a0a03930afe2731af1023036bea29cff0560a
git cherry-pick -x 8cc806145913d644ce3d0a99d1c681304fa674f8
git cherry-pick -x ce5af5e8fc6bff2729a36300873e65dfd3710848
git cherry-pick -x 6c8abf9ff8fa44612c1f41c6f1b14f6f1ca26e9a
Original PR: https://github.com/truenas/webui/pull/8752
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123911

NAS-123911 / 23.10 / Remove Number of VDEVs dropdown for cache and log (by AlexKarpov98)

---

src/app/pages/datasets/modules/snapshots/store/snapshot.effects.ts
src/app/pages/datasets/modules/snapshots/store/snapshot.reducer.ts

NAS-122756 / 22.12.4 / Snapshots dont automatically refresh [Bluefin]

---

src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.html
src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.ts

Testing: see that Descriptor field on Enclosure page is no longer there for Cobia & Bluefin:

NAS-123723 / 23.10 / View Enclosure Elements contain empty Descriptor column

---

src/app/views/sessions/signin/set-admin-password-form/set-admin-password-form.component.html

**Testing**
See ticket please
Original PR: https://github.com/truenas/webui/pull/8747
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123834

NAS-123834 / 23.10 / Fix disabling `Sign In` button (by bvasilenko)

---

src/app/pages/datasets/components/dataset-management/dataset-management.component.ts

Backported
Original PR: https://github.com/truenas/webui/pull/8721
Original PR: https://github.com/truenas/webui/pull/8732
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123802
Original PR: https://github.com/truenas/webui/pull/8740
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123802

NAS-123802 / 23.10-RC.1 / Fix position of children in dataset tree (by bvasilenko) (by bugclerk)

---

src/app/helpers/storage.helper.ts
src/app/pages/storage/modules/pool-manager/components/configuration-preview/configuration-preview.component.html
src/app/pages/storage/modules/pool-manager/components/configuration-preview/configuration-preview.component.spec.ts
src/app/pages/storage/modules/pool-manager/components/configuration-preview/configuration-preview.component.ts
src/app/pages/storage/modules/pool-manager/components/existing-configuration-preview/existing-configuration-preview.component.html
src/app/pages/storage/modules/pool-manager/components/existing-configuration-preview/existing-configuration-preview.component.ts
src/app/pages/storage/modules/pool-manager/components/new-devices/new-devices-preview.component.html
src/app/pages/storage/modules/pool-manager/components/new-devices/new-devices-preview.component.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/9-review-wizard-step/review-wizard-step.component.html
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/9-review-wizard-step/review-wizard-step.component.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager/tests/wizard-reset-step.spec.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager/tests/wizard-start-over.spec.ts
src/app/pages/storage/modules/pool-manager/pipes/topology-category-description.pipe.spec.ts
src/app/pages/storage/modules/pool-manager/pipes/topology-category-description.pipe.ts

NAS-123932 / 24.04 / Pool creation shows type for spares

---

scripts/ui/models.json
src/app/core/testing/utils/enclosure-templates/mock-r10.ts
src/app/core/testing/utils/enclosure-templates/mock-r30.ts
src/app/core/testing/utils/mock-storage-generator.utils.ts

Testing:
Check to see if mock utility can emulate R10 and R30 machines

NAS-123781 / 24.04 / Mock Utility: Complete R series support

---

src/app/pages/storage/modules/pool-manager/components/pool-manager/tests/draid-pool-creation.spec.ts

NAS-XXXXXX: Master fix

---

src/app/pages/sharing/iscsi/extent/extent-form/extent-form.component.ts

Testing: when editing an extent that was created with type = Device, Device dropdown should be filled in.
Original PR: https://github.com/truenas/webui/pull/8804
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122258

NAS-122258 / 23.10 / Showing extent disk on edit (by undsoft)

---

src/app/views/sessions/sessions.module.ts
src/app/views/sessions/signin/failover-status/failover-status.component.html
src/app/views/sessions/signin/failover-status/failover-status.component.scss
src/app/views/sessions/signin/store/signin.store.ts

Testing: 
Check ticket & Sign In form
Result:
https://github.com/truenas/webui/assets/22980553/93e15939-73fe-4d84-8d61-3a57f254e052

NAS-123987 / 24.04 / Do not wait for `failover.get_ips` and `failover.disabled reasons` before enabling signin form

---

src/app/views/sessions/sessions.module.ts
src/app/views/sessions/signin/failover-status/failover-status.component.html
src/app/views/sessions/signin/failover-status/failover-status.component.scss
src/app/views/sessions/signin/store/signin.store.ts

Testing: 
Check ticket & Sign In form
Result:
https://github.com/truenas/webui/assets/22980553/93e15939-73fe-4d84-8d61-3a57f254e052
Original PR: https://github.com/truenas/webui/pull/8813
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123987

NAS-123987 / 23.10 / Do not wait for `failover.get_ips` and `failover.disabled reasons` before enabling signin form (by AlexKarpov98)

---

src/app/modules/ix-forms/components/ix-combobox/ix-combobox.component.ts

Testing: 
see ticket 
Result:
https://github.com/truenas/webui/assets/22980553/0780c142-f910-4675-abd6-0ccd7023d8ba

NAS-123994 / 24.04 / Investigate delay on comboboxes

---

src/app/modules/ix-forms/components/ix-combobox/ix-combobox.component.ts

Testing: 
see ticket 
Result:
https://github.com/truenas/webui/assets/22980553/0780c142-f910-4675-abd6-0ccd7023d8ba
Original PR: https://github.com/truenas/webui/pull/8820
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123994

NAS-123994 / 22.12.4 / Investigate delay on comboboxes (by AlexKarpov98)

---

src/app/pages/system/advanced/allowed-addresses/allowed-addresses-card/allowed-addresses-card.component.html
src/app/pages/system/advanced/allowed-addresses/allowed-addresses-card/allowed-addresses-card.component.scss
src/app/pages/system/advanced/allowed-addresses/allowed-addresses-card/allowed-addresses-card.component.spec.ts
src/app/pages/system/advanced/allowed-addresses/allowed-addresses-card/allowed-addresses-card.component.ts

NAS-124013 / 24.04 / Refactor table in AllowedAddressesCardComponent

---

src/app/modules/ix-forms/components/ix-combobox/ix-combobox.component.ts

Testing: 
see ticket 
Result:
https://github.com/truenas/webui/assets/22980553/0780c142-f910-4675-abd6-0ccd7023d8ba
Original PR: https://github.com/truenas/webui/pull/8820
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123994

NAS-123994 / 23.10 / Investigate delay on comboboxes (by AlexKarpov98)

---

src/app/app.routes.ts
src/app/core/guards/websocket-connection.guard.ts
src/app/helpers/websocket.helper.ts
src/app/modules/layout/components/topbar/power-menu/power-menu.component.ts
src/app/services/websocket-connection.service.spec.ts
src/app/services/websocket-connection.service.ts

NAS-123915 / 24.04 /  Add unit tests to WebsocketConnectionService

---

src/app/modules/ix-feedback/feedback-dialog/feedback-dialog.component.ts

git cherry-pick -x eb1b474fff8be092854d622797a33b32ffd0d6c4
git cherry-pick -x e2baeabe0408275cefdfb056878af11831f45ee9
Original PR: https://github.com/truenas/webui/pull/8842
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124085

NAS-124085 / 23.10 / Fix feedback dialog when attachment upload is failed (by denysbutenko)

---

src/app/modules/ix-feedback/feedback-dialog/feedback-dialog.component.ts

git cherry-pick -x eb1b474fff8be092854d622797a33b32ffd0d6c4
git cherry-pick -x e2baeabe0408275cefdfb056878af11831f45ee9
Original PR: https://github.com/truenas/webui/pull/8842
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124085

NAS-124085 / 23.10-RC.1 / Fix feedback dialog when attachment upload is failed (by denysbutenko)

---

scripts/ui/models.json
src/app/core/testing/utils/enclosure-templates/mock-mini-3.0-e+.ts
src/app/core/testing/utils/enclosure-templates/mock-mini-3.0-x+.ts
src/app/core/testing/utils/enclosure-templates/mock-mini-3.0-x.ts
src/app/core/testing/utils/enclosure-templates/mock-r10.ts
src/app/core/testing/utils/enclosure-templates/mock-r30.ts
src/app/core/testing/utils/mock-storage-generator.utils.ts

Combined backport PR for NAS-123778 and NAS-123781
Testing:
Try to use mock utility to emulate  MINI E+ X+ X and R10/R30

NAS-123778 / 23.10 / Mock utility support for mini models E+ X+ X and R10/R30

---

src/app/pages/datasets/components/dataset-management/dataset-management.component.ts
src/app/pages/datasets/utils/dataset.utils.spec.ts
src/app/pages/datasets/utils/dataset.utils.ts

NAS-124098 / 23.10-RC.1 / Fixes dataset order

---

src/app/pages/datasets/components/dataset-management/dataset-management.component.ts
src/app/pages/datasets/utils/dataset.utils.spec.ts
src/app/pages/datasets/utils/dataset.utils.ts

Original PR: https://github.com/truenas/webui/pull/8849
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124098

NAS-124098 / 24.04 / Fixes dataset order (by undsoft)

---

src/app/pages/datasets/components/dataset-management/dataset-management.component.ts
src/app/pages/datasets/utils/dataset.utils.spec.ts
src/app/pages/datasets/utils/dataset.utils.ts

Original PR: https://github.com/truenas/webui/pull/8849
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124098

NAS-124098 / 23.10 / Fixes dataset order (by undsoft)

---

src/app/pages/datasets/components/dataset-management/dataset-management.component.ts
src/app/pages/datasets/utils/dataset.utils.spec.ts
src/app/pages/datasets/utils/dataset.utils.ts

git cherry-pick -x 2c909b50346a0d5ff8c2e2c076eee6f0b06b86f2
git cherry-pick -x ed7081f034f11487b89e6cd1d1456c3da14f9293
Original PR: https://github.com/truenas/webui/pull/8849
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124098

NAS-124098 / 22.12.4 / Fixes dataset order (by undsoft)

---

src/app/pages/system/file-ticket/file-ticket-form/components/jira-oauth/jira-oauth.component.ts
src/app/pages/system/file-ticket/file-ticket-form/file-ticket-form.component.spec.ts

For testing see details in the ticket
Original PR: https://github.com/truenas/webui/pull/8718
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123762

NAS-123762 / 23.10-RC.1 / Fix JIRA token in File Ticket form (by denysbutenko)

---

src/app/modules/ix-table2/components/ix-table2/ix-table2.harness.ts
src/app/modules/ix-table2/components/ix-table2/row.harness.ts
src/app/pages/network/components/interfaces-card/interfaces-card.component.spec.ts
src/app/pages/system/advanced/cron/cron-card/cron-card.component.spec.ts
src/app/pages/system/advanced/init-shutdown/init-shutdown-card/init-shutdown-card.component.spec.ts

NAS-123696 / 24.04 / Improve ix-table2 harnesses to allow clicking on buttons within a row

---

src/app/pages/storage/modules/pool-manager/components/add-vdevs/add-vdevs.component.html
src/app/pages/storage/modules/pool-manager/components/add-vdevs/add-vdevs.component.scss
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/pool-manager-wizard.component.scss
src/app/pages/storage/modules/pool-manager/components/pool-manager/pool-manager.component.html
src/app/pages/storage/modules/pool-manager/components/pool-manager/pool-manager.component.scss

NAS-123996 / 24.04 / Columns in pool creation are glued together

---

src/app/pages/dashboard/components/widget-network/widget-network.component.html
src/app/pages/dashboard/components/widget-network/widget-network.component.ts
src/app/pages/dashboard/components/widget-nic/widget-nic.component.ts

For testing, check that the values for 'In' and 'Out' values on the widgets for interfaces on the dashboard are accurate in units and values.

NAS-123651 / 23.10 / Fixing units conversion

---

src/app/pages/dashboard/components/widget-network/widget-network.component.html
src/app/pages/dashboard/components/widget-network/widget-network.component.ts
src/app/pages/dashboard/components/widget-nic/widget-nic.component.ts

Backport of https://github.com/truenas/webui/pull/8861

NAS-123651 / 24.04 / Fixing units conversion

---

src/app/modules/ix-table2/components/ix-table-body/cells/ix-cell-date/ix-cell-date.component.html
src/app/modules/ix-table2/components/ix-table-body/cells/ix-cell-date/ix-cell-date.component.ts
src/app/modules/ix-table2/components/ix-table-body/cells/ix-cell-schedule/ix-cell-schedule.component.html
src/app/modules/ix-table2/components/ix-table-body/cells/ix-cell-schedule/ix-cell-schedule.component.ts
src/app/modules/ix-table2/components/ix-table-body/cells/ix-cell-size/ix-cell-size.component.ts
src/app/modules/ix-table2/components/ix-table-body/cells/ix-cell-text/ix-cell-text.component.ts
src/app/modules/ix-table2/components/ix-table-body/cells/ix-cell-toggle/ix-cell-toggle.component.ts
src/app/modules/ix-table2/components/ix-table-body/cells/ix-cell-yesno/ix-cell-yesno.component.html
src/app/modules/ix-table2/interfaces/table-column.interface.ts

**Testing**
On pages where `ix-table2` is used, test the table displaying and sorting and execution of row actions

NAS-124045 / 24.04 / Add support for value transformations in ix-table2

---

src/app/views/sessions/signin/signin.component.ts
src/app/views/sessions/signin/store/signin.store.spec.ts
src/app/views/sessions/signin/store/signin.store.ts

Check the [ticket](https://ixsystems.atlassian.net/browse/NAS-124080) for context and details on how to test it.

NAS-124080 / 23.10 / Fix max number of concurrent calls and empty ws connection

---

tests/bdd/ha-bhyve02/test_NAS_T1659_middleware_log_on_failover.py

(cherry picked from commit bb6a62894dfe61f1f3a531d37932f5b160d475ef) (cherry picked from commit 4f9c1dba1e42b4329224e34f59a907dc74930fb9)

TE-981 / 23.10.0 / Changed NAS-T1659 to only look for the log

---

tests/bdd/ha-bhyve02/test_NAS_T1659_middleware_log_on_failover.py

(cherry picked from commit bb6a62894dfe61f1f3a531d37932f5b160d475ef) (cherry picked from commit 4f9c1dba1e42b4329224e34f59a907dc74930fb9) (cherry picked from commit 80e23c70caa9ddf3392951e4ffb7f648709e97f5)

TE-981 / 24.04 / Changed NAS-T1659 to only look for the log

---

src/app/services/dialog.service.ts
src/app/views/sessions/signin/signin.component.ts
src/app/views/sessions/signin/store/signin.store.spec.ts
src/app/views/sessions/signin/store/signin.store.ts

Check the [ticket](https://ixsystems.atlassian.net/browse/NAS-124080) for context and details on how to test it.
Original PR: https://github.com/truenas/webui/pull/8858
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124080

NAS-124080 / 24.04 / Fix max number of concurrent calls and empty ws connection (by denysbutenko)

---

src/app/core/testing/utils/mock-entity-job-component-ref.utils.ts
src/app/modules/common/dialog/resilver-progress/resilver-progress.component.scss
src/app/modules/layout/components/topbar/failover-upgrade-indicator/failover-upgrade-indicator.component.html
src/app/modules/layout/components/topbar/failover-upgrade-indicator/failover-upgrade-indicator.component.spec.ts
src/app/modules/layout/components/topbar/failover-upgrade-indicator/failover-upgrade-indicator.component.ts
src/app/modules/layout/components/topbar/resilvering-indicator/resilvering-indicator.component.html
src/app/modules/layout/components/topbar/resilvering-indicator/resilvering-indicator.component.scss
src/app/modules/layout/components/topbar/resilvering-indicator/resilvering-indicator.component.spec.ts
src/app/modules/layout/components/topbar/resilvering-indicator/resilvering-indicator.component.ts
src/app/modules/layout/components/topbar/topbar.component.html
src/app/modules/layout/components/topbar/topbar.component.scss
src/app/modules/layout/components/topbar/topbar.component.ts
src/app/modules/layout/layout.module.ts
src/app/store/eula/eula.effects.spec.ts
src/app/store/eula/eula.effects.ts
src/app/store/ha-info/ha-info.actions.ts
src/app/store/ha-info/ha-info.effects.ts
src/app/store/ha-info/ha-info.reducer.ts
src/app/store/ha-upgrade/ha-upgrade.actions.ts
src/app/store/ha-upgrade/ha-upgrade.effects.spec.ts
src/app/store/ha-upgrade/ha-upgrade.effects.ts
src/app/store/index.ts

Testing: the easiest way to test new code is by altering `if` conditions locally.

NAS-124150 / 24.04 / Extracting more components from topbar

---

src/app/pages/storage/modules/pool-manager/components/add-vdevs/add-vdevs.component.html
src/app/pages/storage/modules/pool-manager/components/add-vdevs/add-vdevs.component.scss
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/pool-manager-wizard.component.scss
src/app/pages/storage/modules/pool-manager/components/pool-manager/pool-manager.component.html
src/app/pages/storage/modules/pool-manager/components/pool-manager/pool-manager.component.scss

Testing: 
see these 2 places:
Original PR: https://github.com/truenas/webui/pull/8838
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123996

NAS-123996 / 23.10 / Columns in pool creation are glued together (by AlexKarpov98)

---

src/app/interfaces/iscsi.interface.ts
src/app/pages/sharing/iscsi/iscsi-wizard/iscsi-wizard.component.spec.ts
src/app/pages/sharing/iscsi/iscsi-wizard/iscsi-wizard.component.ts

For testing, go to Shares dashboard and create iSCSI share with empty initiators field. Ensure Initiator Group is created.

NAS-124133 / 24.04 / Ensure iSCSI Wizard creates Initiator Group

---

src/app/modules/entity/table/table.component.html
src/app/modules/entity/table/table.component.ts
src/app/modules/entity/table/table.service.ts

Backported
**Testing**
1. Original bug fixed - please see video in the ticket
2. In addition, while working, I've discovered another bug related to the “View more” and “Collapse” display buttons when adding (removing) a row. I fixed it as well
Original PR: https://github.com/truenas/webui/pull/8857
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124024

NAS-124024 / 23.10 / Fix `ix-conf-table` (by bvasilenko)

---

src/app/services/ix-file-upload.service.ts

Check the [ticket](https://ixsystems.atlassian.net/browse/NAS-124075) for context.

NAS-124075 / 23.10 / Fix uploading screenshots multiple times

---

src/app/pages/apps/store/apps-filter-store.service.ts
src/app/pages/apps/store/apps-store.service.ts
src/app/pages/apps/store/installed-apps-store.service.ts
src/app/pages/apps/store/kubernetes-store.service.ts
src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/base-provider-form.ts
src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/sftp-provider-form/sftp-provider-form.component.ts
src/app/pages/datasets/components/dataset-form/utils/dataset-form.service.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/pool-manager-wizard.component.ts
src/app/pages/system/file-ticket/file-ticket-form/file-ticket-form.component.ts
src/app/pages/system/file-ticket/file-ticket-licensed-form/file-ticket-licensed-form.component.ts
src/app/pages/system/update/update.component.ts
src/app/pages/vm/utils/vm-gpu.service.ts
src/app/services/gpu/gpu-service.spec.ts
src/app/services/gpu/gpu.service.ts
src/app/services/ws.service.ts

There is no concrete way to test this. I've removed instances where undefined is thrown. Also, in the websocket service job method, we were throwing the job object. Instead, we are now throwing the job error.

NAS-123945 / 24.04 / NAS-124077: Removing of(undefined)

---

src/app/modules/common/dialog/directory-services-monitor/directory-services-monitor.component.scss

NAS-124164 / 24.04 / Fix layout for directory services dialog

---

src/app/modules/common/dialog/directory-services-monitor/directory-services-monitor.component.scss

Result:
Original PR: https://github.com/truenas/webui/pull/8896
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124164

NAS-124164 / 23.10 / Fix layout for directory services dialog (by AlexKarpov98)
