truenas/webui

src/app/pages/reports-dashboard/components/reports-global-controls/reports-global-controls.component.html
src/app/pages/reports-dashboard/components/reports-global-controls/reports-global-controls.component.ts
src/app/pages/reports-dashboard/reports-dashboard.component.ts

git cherry-pick -x 2c65f59223cb939c2978d3d1cb57238e9d3eddce
git cherry-pick -x 9dce31810b1ff421d672ab9a5f5360dfae66492f
git cherry-pick -x 7a92aa09a22d9f0e788b7944a6f32a0a36e83386
git cherry-pick -x f37076989e9dc15d101923d88beec106958ec744
The issue is missing menu items in the dropdown menu, such as UPS and Target, when reports are available.
For testing, find a system with UPS or mock it in the `reports.service.ts`.
```
this.ws.call('reporting.graphs').subscribe((reportingGraphs) => {
reportingGraphs.push({
name: 'ups',
title: 'UPS',
vertical_label: 'Requests',
identifiers: [ …
```

NAS-122137 / 22.12.3 / Fix reporting dropdown menu (by denysbutenko)

---

src/app/services/error-handler.service.ts

For current fix it's okay to show modal, but in future we need to fix this TODO:
// TODO: Need to update error handler to open step with an error.
**src/app/pages/credentials/certificates-dash/csr-add/csr-add.component.ts**

NAS-122116 / 23.10 / No Error/notification of duplicate CSR when trying to save

---

src/app/modules/ix-forms/components/ix-input/ix-input.component.ts
src/app/modules/ix-forms/services/ix-formatter.service.ts
src/app/pages/services/components/service-ftp/service-ftp.component.html
src/app/pages/services/components/service-ftp/service-ftp.component.spec.ts

For testing use http://localhost:4200/services/ftp
Advanced options (input now defaults to KiB instead of MiB if no unit specified manually)

NAS-122219 / 23.10 / Update FTP form options

---

src/app/modules/entity/table/table.component.html
src/app/modules/entity/table/table.component.scss
src/app/modules/entity/table/table.component.ts
src/app/pages/data-protection/data-protection-dashboard.component.ts

Added more tooltips for easier reading of data.
Running button colour updated (instead of orange):

NAS-118894 / 23.10 / WebUI changes in Data Protection Section

---

src/app/modules/ix-feedback/feedback-dialog/feedback-dialog.component.scss
src/app/modules/ix-feedback/feedback-dialog/feedback-dialog.component.ts
src/app/modules/ix-feedback/interfaces/feedback.interface.ts

Making `extra` as required param. Fixes dialog width on narrow screens.
There is a known issue with CORS - it will be solved at https://github.com/truenas/feedback-service/pull/8. Until that, for testing, you'll need to set up `feedback-service` locally and expose it to some domain, using `ngrok` for example. Update `hostname` in `ix-feedback.service.ts` using the exposed domain, and test form submission in the dialog.

NAS-121985 / 23.10 / Add Feedback Module

---

src/app/pages/reports-dashboard/components/report/report.component.html
src/app/pages/reports-dashboard/components/report/report.component.ts

Testing: 
Go to reports page and try to rewind to 2000 year.
You should not be able to rewind further - this fixes the bug.
http://localhost:4200/reportsdashboard/network

NAS-122282 / 23.10 / "Failed to export RRD data: ERROR" appear when navigate to the furthest position/time, left, in Reporting graphs

---

src/app/pages/network/components/interface-form/interface-form.component.html
src/app/pages/network/components/interface-form/interface-form.component.scss

NAS-120187 / 23.10 / Unable to set static IP address on secondary interface

---

src/app/pages/network/components/interface-form/interface-form.component.html
src/app/pages/network/components/interface-form/interface-form.component.scss

error is shown now:
Original PR: https://github.com/truenas/webui/pull/8253
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120187

NAS-120187 / 22.12.4 / Unable to set static IP address on secondary interface (by AlexKarpov98)

---

src/app/pages/sharing/iscsi/associated-target/associated-target-list/associated-target-list.component.ts
src/app/pages/sharing/iscsi/authorized-access/authorized-access-list/authorized-access-list.component.ts

Issue appears only for Bluefin.
Testing: 
Go to `Shares` --> `Associated Target` tab http://10.234.27.211/ui/sharing/iscsi/associatedtarget
Try to edit on of the items and it should be updated instantly on the list.

NAS-122262 / 22.12.4 / iSCSI "Associated Targets" UI does not refresh after saving "Edits".  User must change UI focus for updates to appear

---

src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.spec.ts
src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.ts
src/app/pages/apps/components/installed-apps/installed-apps.component.ts

For testing, delete the last app and check if the URL was changed and the details panel is closed. When multiple apps are installed, it should keep the existing behavior - redirect to the first app in the list and the details panel is there.

NAS-122503 / 23.10 / Redirect to installed apps after deletion

---

src/app/services/websocket-connection.service.ts

**Testing**
1. Login in one browser and open inspector.
1. Login in another browser and go to Advanced. Click Terminate Other Sessions.
1. Ensure that in first browser now has only 1 websocket connection with Pending status. (Previously it was 2 connections)
1. Wait for ~2 minutes.  You should not see "Trying to reconnect" message.

NAS-121488 / 23.10 / Close unnecessary connection

---

src/app/pages/storage/modules/devices/components/zfs-info-card/zfs-info-card.component.ts

Added logic in canRemoveDisk and canRemoveVDEV to allow removal of VdevType.Cache and .Log when hasTopLevelRaidz is TRUE - these vdev types are still removable even when a top-level RAIDZ vdev exists so the REMOVE button should be presented for the appropriate disk/vdevs

NAS-122781 / UI does not present "Remove" options for L2ARC or SLOG when pool contains RAIDZ data vdevs

---

src/app/pages/storage/modules/devices/components/zfs-info-card/zfs-info-card.component.ts

Added logic in canRemoveDisk and canRemoveVDEV to allow removal of VdevType.Cache and .Log when hasTopLevelRaidz is TRUE - these vdev types are still removable even when a top-level RAIDZ vdev exists so the REMOVE button should be presented for the appropriate disk/vdevs
Original PR: https://github.com/truenas/webui/pull/8399
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122781

NAS-122781 / 22.12.4 / NAS-122781 / UI does not present "Remove" options for L2ARC or SLOG when pool contains RAIDZ data vdevs (by chrisperedun)

---

src/app/pages/apps/components/app-detail-view/app-details-header/app-details-header.component.scss

Before: <img width="1728" alt="Screenshot 2023-07-07 at 15 08 32" src="https://github.com/truenas/webui/assets/22980553/49e8a56e-7d5c-4cf3-a8b0-fbba16abc5e2">
After:

NAS-122857 / 23.10 / App description → home page prop overlaps

---

src/app/pages/account/users/user-form/user-form.component.spec.ts
src/app/pages/account/users/user-form/user-form.component.ts

**Testing**
On the **Credentials > Local Users > Add User** form, 
1. By default, the checkboxes in **Home Directory Permissions**:
- should be set to `700` by default (User: Read+Write+Execute, Group: -, Other: -)
- should be disabled
1. Enabled/Disabled state of the checkboxes in **Home Directory Permissions** should depend on whether the **Home Directory** is equals `/nonexistent`
1. If user changes **Create Home Directory** from `unchecked` to `checked`:
the checkboxes in **Home Directory Permissions** should **reset to `700`**

NAS-122480 / 23.10 / Fix Home Directory Permissions

---

src/app/pages/dashboard/components/dashboard/dashboard.component.ts

Previously, if the requests to fetch data for the dashboard took long, you would see nothing on the dashboard for a while. This regression was caused by a recent effort to refactor data loading on the dashboard. This PR fixes the regression.

NAS-123178 / 23.10 / Added default config for loading

---

src/app/pages/reports-dashboard/components/report/report.component.ts
src/app/pages/reports-dashboard/enums/report-zoom-level.enum.ts

For testing, go to reporting and zoom out to 6 months, ensuring the time interval is accurate and should match ~180+- days.

NAS-122283 / 23.10 / Fix reporting zoom level for 6 months

---

src/app/modules/ix-forms/classes/group-combobox-provider.ts
src/app/modules/ix-forms/classes/user-combobox-provider.ts
src/app/modules/ix-forms/components/ix-combobox/ix-combobox.component.ts
src/app/pages/sharing/smb/smb-acl/smb-acl.component.html
src/app/pages/sharing/smb/smb-acl/smb-acl.component.spec.ts
src/app/pages/sharing/smb/smb-acl/smb-acl.component.ts
src/app/services/user.service.ts

Testing:
- Go to https://nas-url/sharing/smb and trigger "Edit Share ACL" row action from table row
- In slide in form Who field, select User.
- If there is a current value for the User field, ensure it shows name and not id
- Combobox options for User field should show `builtin` users being shown last
- Saving the form should now work without traceback
- Repeat this process with groups
Original PR: https://github.com/truenas/webui/pull/8499
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123154

NAS-123154 / 23.10 / Fix Edit SMB ACL Share tracebacks (by dszidi)

---

src/app/modules/entity/table/table.component.html

Testing:
check that there are tooltips right now on the table icons:

NAS-122993 / 24.04 / No tooltip appeared when hovering the mouse on the icons on tables

---

src/app/modules/entity/table/table.component.html

Testing:
check that there are tooltips right now on the table icons:
Original PR: https://github.com/truenas/webui/pull/8532
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122993

NAS-122993 / 23.10 / No tooltip appeared when hovering the mouse on the icons on tables (by AlexKarpov98)

---

src/app/pages/storage/modules/pool-manager/components/add-vdevs/store/add-vdevs-store.service.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/pool-manager-wizard.component.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/9-review-wizard-step/review-wizard-step.component.spec.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/9-review-wizard-step/review-wizard-step.component.ts
src/app/pages/storage/modules/pool-manager/store/pool-manager-validation.service.ts
src/app/pages/storage/modules/pool-manager/store/pool-manager.store.spec.ts
src/app/pages/storage/modules/pool-manager/store/pool-manager.store.ts

Testing:
How it was reproducing before:
- Create new Pool with RaidZ1 `Data` Layout step.
- Add Vdev for newly created Pool
- Create new pool with any Layout in `Data` step.
--- Here error showed up 
You can try on latest nightly to reproduce the bug; (you can as well check ticket description video)
On localhost:
Try to go ahead with above steps -> you should no longer see that error.

NAS-123415 / 24.04 / "Mixing vdev layouts not allowed" error appears when creating a new pool

---

src/app/pages/storage/modules/pool-manager/components/add-vdevs/store/add-vdevs-store.service.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/pool-manager-wizard.component.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/9-review-wizard-step/review-wizard-step.component.spec.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/9-review-wizard-step/review-wizard-step.component.ts
src/app/pages/storage/modules/pool-manager/store/pool-manager-validation.service.ts
src/app/pages/storage/modules/pool-manager/store/pool-manager.store.spec.ts
src/app/pages/storage/modules/pool-manager/store/pool-manager.store.ts

Testing:
How it was reproducing before:
- Create new Pool with RaidZ1 `Data` Layout step.
- Add Vdev for newly created Pool
- Create new pool with any Layout in `Data` step.
--- Here error showed up 
You can try on latest nightly to reproduce the bug; (you can as well check ticket description video)
On localhost:
Try to go ahead with above steps -> you should no longer see that error.
Original PR: https://github.com/truenas/webui/pull/8560
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123415

NAS-123415 / 23.10-BETA.1 / "Mixing vdev layouts not allowed" error appears when creating a new pool (by AlexKarpov98)

---

src/app/pages/storage/modules/pool-manager/components/add-vdevs/store/add-vdevs-store.service.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/pool-manager-wizard.component.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/9-review-wizard-step/review-wizard-step.component.spec.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/9-review-wizard-step/review-wizard-step.component.ts
src/app/pages/storage/modules/pool-manager/store/pool-manager-validation.service.ts
src/app/pages/storage/modules/pool-manager/store/pool-manager.store.spec.ts
src/app/pages/storage/modules/pool-manager/store/pool-manager.store.ts

Testing:
How it was reproducing before:
- Create new Pool with RaidZ1 `Data` Layout step.
- Add Vdev for newly created Pool
- Create new pool with any Layout in `Data` step.
--- Here error showed up 
You can try on latest nightly to reproduce the bug; (you can as well check ticket description video)
On localhost:
Try to go ahead with above steps -> you should no longer see that error.
Original PR: https://github.com/truenas/webui/pull/8560
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123415

NAS-123415 / 23.10 / "Mixing vdev layouts not allowed" error appears when creating a new pool (by AlexKarpov98)

---

src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/layout-step/automated-disk-selection/automated-disk-selection.component.html
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/layout-step/automated-disk-selection/automated-disk-selection.component.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/pool-manager-wizard.component.html
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/pool-manager-wizard.component.ts

Test that the Spare vdev step doesn't have the Vdevs Count field. It should only be allowed to have 1 vdev. Also, test that if there is already a spare vdev in the pool, you are not allowed to add a new spare vdev.

NAS-123402 / 23.10 / Hiding vdevs count field for spare vdev step

---

src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.ts
src/app/services/error-handler.service.spec.ts
src/app/services/error-handler.service.ts

**Summary**
After refactoring, the `checkForUpdate` was moved to a place in code, which was out of reach of `untilDestroy` pipe.
Moveover, the call `checkForUpdate` was waiting for the sys info to be fetched, without need to do so.
**Testing**
1. Tweak the code to simulate delayed error in `checkForUpdate`
2. Drop update-related keys from your `sessionStorage`
3. Go to Dashboard, not stay too long
4. Quickly navigate from Dashboard to any other page (/system/services, /storage/, ...)
Once you left Dashboard page, you should never see an pop-up with an error from Pt "1"

NAS-123351 / 24.04 / Takeout `checkForUpdate`

---

src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.ts
src/app/services/error-handler.service.spec.ts
src/app/services/error-handler.service.ts

**Summary**
After refactoring, the `checkForUpdate` was moved to a place in code, which was out of reach of `untilDestroy` pipe.
Moveover, the call `checkForUpdate` was waiting for the sys info to be fetched, without need to do so.
**Testing**
1. Tweak the code to simulate delayed error in `checkForUpdate`
2. Drop update-related keys from your `sessionStorage`
3. Go to Dashboard, not stay too long
4. Quickly navigate from Dashboard to any other page (/system/services, /storage/, ...)
Once you left Dashboard page, you should never see an pop-up with an error from Pt "1"
Original PR: https://github.com/truenas/webui/pull/8537
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123351

NAS-123351 / 23.10 / Takeout `checkForUpdate` (by bvasilenko)

---

src/app/interfaces/events/disk-events.interface.ts
src/app/pages/system/view-enclosure/components/enclosure-disks-mini/enclosure-disks-mini.component.ts
src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.ts
src/app/services/disk-temperature.service.ts

**Testing**
Emulating "Enclosure":
1. run `yarn ui mock -e`
2. run `yarn ui mock-enclosure -e`
3. navigate to **System Settings > Enclosure**
**Expected result:** Disk temperatures should still be fetched every N seconds, according to the new approach. So please test the closure page to make sure that temperatures are still updated properly. `

NAS-123274 / 23.10 / Remove usages of CoreService for getting disk temperatures

---

src/app/app.module.ts
src/app/modules/ix-forms/components/ix-slide-in/ix-slide-in.component.ts
src/assets/styles/other/_material-reduction.scss
src/assets/styles/other/_root-variables.scss

git cherry-pick -x 3937ce5924bcbcc4fb09a4e7aa0304645c209c97
git cherry-pick -x 0f98346863c06c5e49cd312a2ea1d1151c731b7b
git cherry-pick -x b04b69305e1348f1ecf1deda325023da90005d50
git cherry-pick -x 65c8fbe791d07f0b16f5d8e20864e5b6ffce7bcb
git cherry-pick -x cc8a6f0817d681c08a8b5066dc0a972acf4b5eb5
git cherry-pick -x 7af1be307094a79188afdf8faebad0ad46010d80
Testing: 
See ticket description (I tested on Bluefin as well, problem occurs there as well, it's browser update problem)
and 👇
Check help tooltips
(as well added hide on scroll feature, I think it's useful)
Original PR: …

NAS-123336 / 22.12.4 / WebUI tooltips are malfunctioning in chrome (by AlexKarpov98)

---

src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/layout-step/automated-disk-selection/automated-disk-selection.component.ts

Please check the context of the ticket first. 
Note that on the step 4 (Spare) it's impossible to choose a layout (Stripe/Mirror/...). WebUI by design provides no ability to do so by not rendering **Layout** dropdown on this step.
The root cause of the bug is that the **Layout** have no selection, this prevents user from interacting with dependant fields (Treat disk..., Width, Number...) 
This fix ensures that these fields become enabled, by pre-selecting the correct item in the  **Layout** dropdown. The correct item is being chosen automatically based on the logic from `add-vdevs-legacy`.
1. Have an existing pool and at least 2 unassigned disks
2. Go to **Storage** -> **Unassigned Disks** -> **Add To Pool** 
4. In the **Add To Pool** pop-up, select **Existing Pool** option, pick any pool …

NAS-123284 / 24.04 / Unable to add spares in new Pool Creation Wizard

---

src/app/services/token-lifetime.service.ts

Testing: 
Check that you are logged out even tho there is no ws connection and user is logged in.
Extend session modal will appear as usual and closes the session, before once there was no connection - it stuck.
example: 
11:55:19 on screenshot
but now 12:03:59 and session still is not closed

NAS-123526 / 24.04 / Extend session may appear when there is no active connection

---

src/app/services/token-lifetime.service.ts

Testing: 
Check that you are logged out even tho there is no ws connection and user is logged in.
Extend session modal will appear as usual and closes the session, before once there was no connection - it stuck.
example: 
11:55:19 on screenshot
but now 12:03:59 and session still is not closed
Original PR: https://github.com/truenas/webui/pull/8593
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123526

NAS-123526 / 23.10 / Extend session may appear when there is no active connection (by AlexKarpov98)

---

scripts/ui/ui.ts

For testing, make sure the global mock is disabled after `yarn ui remote -i ...` execution.

NAS-123270 / 24.04 / Disable global mock when remote is changed

---

src/app/pages/apps/apps-routing.module.ts
src/app/pages/apps/apps.module.ts
src/app/pages/apps/guards/apps-navigate-away.guard.ts

git cherry-pick -x c8542f5bcad7e96354ffacd03b093b1a79a6ff06
git cherry-pick -x 0016584d13a21aaa954a038ecfb97808dd470767
Testing:
See ticket.
Final result:
https://github.com/truenas/webui/assets/22980553/b30770f6-4a85-489b-b90c-b705bd9c5926
Original PR: https://github.com/truenas/webui/pull/8597
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122599

NAS-122599 / 23.10 / Apps filter should reset when the user navigates away from the apps dashboard page (by AlexKarpov98)

---

src/app/helptext/storage/volumes/volume-list.ts

Hello! 
This is a simple PR to fix a typo that's been present in SCALE for a while, in the auto-trim settings. It fixes the "day block" typo, and rewrites the sentence slightly to be easier to understand.

Correct typo and clarify auto-trim setting text

---

package.json
yarn.lock

Testing:
see that critters version is now > 0.0.19
yarn.lock is updated

NAS-123577 / 24.04 / CVE-2023-3481 identified against component critters in Wambui repo

---

package.json
yarn.lock

Testing:
see that critters version is now > 0.0.19
yarn.lock is updated
Original PR: https://github.com/truenas/webui/pull/8623
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123577

NAS-123577 / 23.10 / CVE-2023-3481 identified against component critters in Wambui repo (by AlexKarpov98)

---

src/app/pages/dashboard/store/dashboard-storage-store.service.ts
src/app/pages/dashboard/store/dashboard-store.service.ts

Try creating/exporting the pool.
See the updates on the dashboard page with latest pools data. 
Original PR: https://github.com/truenas/webui/pull/8617
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123536

NAS-123536 / 23.10 / The Storage Widget Continues to Display After a Pool has Been Exported On The Dashboard (by AlexKarpov98)

---

src/app/pages/storage/components/dashboard-pool/topology-card/topology-card.component.html
src/app/pages/storage/components/dashboard-pool/topology-card/topology-card.component.spec.ts
src/app/pages/storage/components/dashboard-pool/topology-card/topology-card.component.ts

Testing: see ticket:
**Before:**
**After:**
Original PR: https://github.com/truenas/webui/pull/8647
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121466

NAS-121466 / 23.10 / Topology overview hides VDEV information if there is a warning for redundancy mismatch (by AlexKarpov98)

---

src/app/pages/data-protection/replication/replication-form/properties-override-validator/properties-override-validator.service.ts
src/app/pages/data-protection/replication/replication-form/replication-form.component.html
src/app/pages/data-protection/replication/replication-form/replication-form.component.ts

Testing:
Check Replication Task Advanced form SAVE button.
It should be disabled if form is invalid. (previously it was always active)
Original PR: https://github.com/truenas/webui/pull/8646
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123647

NAS-123647 / 23.10 / Add Replication Task Advanced Form [SAVE] button - is always active (by AlexKarpov98)

---

src/app/pages/account/users/user-form/user-form.component.spec.ts
src/app/pages/account/users/user-form/user-form.component.ts

**Testing**
1. **Datasets > Add Dataset** Add a dataset named e.g. `home`
2. **Shares > Windows (SMB) Shares > Add**
- Path - this dataset (`home`)
- Purpose - **No presets**
- Use as Home Share - `true`
3. **Credentials \> Local Users \> Add**
- Full name - for example, `newUser`
- Password - for example, `qwerty`
- Create Home Directoty - `true`
**Expected Behavior:** A user should be added, with a Home Directory similar to `mnt/my pool/home/newUser`

NAS-123426 / 24.04 / Fix default home path

---

src/app/pages/directory-service/components/active-directory/active-directory.component.html
src/app/pages/directory-service/components/active-directory/active-directory.component.spec.ts

NAS-123405 / 24.04 / Basic Options Cannot Save Due to Hidden Advanced Options Error On The Active Directory Setup Screen

---

src/app/pages/directory-service/components/active-directory/active-directory.component.html
src/app/pages/directory-service/components/active-directory/active-directory.component.spec.ts

Original PR: https://github.com/truenas/webui/pull/8644
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123405

NAS-123405 / 23.10 / Basic Options Cannot Save Due to Hidden Advanced Options Error On The Active Directory Setup Screen (by AlexKarpov98)

---

src/app/pages/storage/modules/disks/components/replace-disk-dialog/replace-disk-dialog.component.ts

git cherry-pick -x 63f931decbfed9223eb1a550d9c7119d4b5b220e
git cherry-pick -x 0f5aa8986a20a5d8a81af7d9ce5f51170779b5f5
git cherry-pick -x 82f240754180c1d317c3d82cc3ca9190e5b0b70f
Original PR: https://github.com/truenas/webui/pull/8633
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123358

NAS-123358 / 22.12.3 / Don't initialize observable so loading is shown on select (by RehanY147)

---

src/app/pages/reports-dashboard/components/line-chart/line-chart.component.ts
src/app/pages/reports-dashboard/utils/report.utils.ts

**Summary**
The use of the `convertAggregations` method has not yet been implemented in **stable/cobia**. Therefore rounding in the table wasn't backported.
**Testing**
Please see original ticket
Original PR: https://github.com/truenas/webui/pull/8631
Jira URL: https://ixsystems.atlassian.net/browse/NAS-116079

NAS-116079 / 23.10 / dashboard network bandwidth issues (by bvasilenko)

---

src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/layout-step/automated-disk-selection/automated-disk-selection.component.html
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/layout-step/automated-disk-selection/automated-disk-selection.component.ts

This PR exposes preselected layout field for data vdevs when adding vdevs to existing pool
To test:
- go to add vdevs page
- On Data step check to see that layout field is visible as a read only input field
- Check that the read only field has tooltip text

NAS-123521 / 24.04 / Show readonly layout field for Data VDEVs when adding disks to existing pool

---

src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/layout-step/automated-disk-selection/automated-disk-selection.component.html
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/layout-step/automated-disk-selection/automated-disk-selection.component.ts

This PR exposes preselected layout field for data vdevs when adding vdevs to existing pool
To test:
- go to add vdevs page
- On Data step check to see that layout field is visible as a read only input field
- Check that the read only field has tooltip text 
Original PR: https://github.com/truenas/webui/pull/8676
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123521

NAS-123521 / 23.10 / Show readonly layout field for Data VDEVs when adding disks to existing pool (by dszidi)

---

src/app/modules/scheduler/components/scheduler-modal/scheduler-modal.component.scss

Backported
**Testing**
On the **Data Protection** page,
At Add/edit form for **Periodic Snapshot Task,**
When **Custom** option is picked from the **Schedule** dropdown,
In the **Days of Week** section of the **Custom Scheduler**, the "Sat" checkbox label should be seen.
Original PR: https://github.com/truenas/webui/pull/8670

NAS-123648 / 23.10 / Fix styles

---

src/app/pages/account/users/user-form/user-form.component.spec.ts
src/app/pages/account/users/user-form/user-form.component.ts

**Testing**
1. **Datasets > Add Dataset** Add a dataset named e.g. `home`
2. **Shares > Windows (SMB) Shares > Add**
- Path - this dataset (`home`)
- Purpose - **No presets**
- Use as Home Share - `true`
3. **Credentials \> Local Users \> Add**
- Full name - for example, `newUser`
- Password - for example, `qwerty`
- Create Home Directoty - `true`
**Expected Behavior:** A user should be added, with a Home Directory similar to `mnt/my pool/home/newUser`
Original PR: https://github.com/truenas/webui/pull/8621
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123426

NAS-123426 / 23.10 / Fix default home path (by bvasilenko)

---

src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.html
src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.spec.ts
src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.ts

App Info Card should display:
- application name specified by the user and not the chart name.
- docker image tag as the app version for custom apps
BETA-1:
Changes:

NAS-123675 / 24.04 / Fixes for app info card

---

src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.html
src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.spec.ts
src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.ts

git cherry-pick -x f595321717962e6168ddfa4e6281a9a89ba55d63
git cherry-pick -x 69e407af66c1a73c4ed1292ce66c50286d984d43
App Info Card should display:
- application name specified by the user and not the chart name.
- docker image tag as the app version for custom apps
BETA-1:
Changes:
Original PR: https://github.com/truenas/webui/pull/8681
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123675

NAS-123675 / 23.10 / Fixes for app info card (by denysbutenko)

---

src/app/pages/datasets/components/dataset-node/dataset-node.component.html
src/app/pages/datasets/components/dataset-node/dataset-node.component.scss

**Testing**
On **Datasets** page, the accurate volume should be displayed for a dataset. 
For example, for a dataset with 1.43 terabyte,  the "1\.43TiB" should be reported in the dataset level. You should compare the value displayed to the volume displayed on **Data Protection** page, when adding a replication task
Original PR: https://github.com/truenas/webui/pull/8696
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123650

NAS-123650 / 23.10 / Dataset storage use could be finer graded (by bvasilenko)

---

src/app/pages/datasets/components/dataset-management/dataset-management.component.ts

**Testing**
On **Datasets** page,
1. Create 2 datasets, with identical names, but the second one containing `-` character and some arbitrary postfix in it's name. For example:
1. **pool/data**
2. **pool/data-system**
2. Select one of these datasets, and create a child dataset. For example, **media**
* **Expected result:** media is displayed under "pool/data"

NAS-123802 / 24.04 / Fix position of children in dataset tree

---

src/app/modules/entity/entity-job/entity-job.component.scss

For testing, ensure no horizontal scrollbar on entity job dialog when page width < 768px.

NAS-123852 / 24.04 / Remove horizontal scroll from entity job dialogs

---

src/app/modules/entity/entity-job/entity-job.component.scss

For testing, ensure no horizontal scrollbar on entity job dialog when page width < 768px.
Original PR: https://github.com/truenas/webui/pull/8719
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123852

NAS-123852 / 23.10 / Remove horizontal scroll from entity job dialogs (by denysbutenko)

---

src/app/core/components/directives/details-height/details-height.directive.ts

For testing, go to Apps and check that the extra scrollbar does not appear. Ensure other places that use `ixDetailsHeight` are still functional after switching between pages (e.g., from Datasets to Apps pages).

NAS-123810 / 24.04 / Fix initialization on ixDetailsHeight directive

---

src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.html
src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.ts

git cherry-pick -x 1ba92e27a10e3375c7caaae70125b5df3cd2e494
git cherry-pick -x 42108f438a61a7de196a8a540767f0b27a38e87b
git cherry-pick -x e56a5f24e52f4a3ff6dabae2d64eddfde4974b43
Testing: see that Descriptor field on Enclosure page is no longer there for Cobia & Bluefin:
Original PR: https://github.com/truenas/webui/pull/8764
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123723

NAS-123723 / 22.12.4 / View Enclosure Elements contain empty Descriptor column (by AlexKarpov98)

---

src/app/pages/datasets/components/data-protection-card/data-protection-card.component.ts

For testing, go to datasets, and on the details panel, press the `Create Snapshot` button and close it, ensuring no `Snapshot added successfully` toast appears. Try to submit the form to ensure that the message appears.

NAS-124004 / 24.04 / Do not show success message when snapshot form is closed

---

src/app/helpers/storage.helper.ts
src/app/pages/storage/modules/pool-manager/components/configuration-preview/configuration-preview.component.html
src/app/pages/storage/modules/pool-manager/components/configuration-preview/configuration-preview.component.spec.ts
src/app/pages/storage/modules/pool-manager/components/configuration-preview/configuration-preview.component.ts
src/app/pages/storage/modules/pool-manager/components/existing-configuration-preview/existing-configuration-preview.component.html
src/app/pages/storage/modules/pool-manager/components/existing-configuration-preview/existing-configuration-preview.component.ts
src/app/pages/storage/modules/pool-manager/components/new-devices/new-devices-preview.component.html
src/app/pages/storage/modules/pool-manager/components/new-devices/new-devices-preview.component.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/9-review-wizard-step/review-wizard-step.component.html
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/9-review-wizard-step/review-wizard-step.component.ts
src/app/pages/storage/modules/pool-manager/pipes/topology-category-description.pipe.spec.ts
src/app/pages/storage/modules/pool-manager/pipes/topology-category-description.pipe.ts

git cherry-pick -x 1029572282fc7d511a0de3a9ed5e66992ca29f3a
git cherry-pick -x dd6ced2ca6afdf1a88fdddff6e6b43346396625f
git cherry-pick -x d105be277b087d5077b900bc69dc6d2d2085f61c
Original PR: https://github.com/truenas/webui/pull/8782
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123932

NAS-123932 / 23.10 / Pool creation shows type for spares (by AlexKarpov98)

---

src/app/helpers/storage.helper.ts
src/app/pages/storage/modules/pool-manager/components/configuration-preview/configuration-preview.component.html
src/app/pages/storage/modules/pool-manager/components/configuration-preview/configuration-preview.component.spec.ts
src/app/pages/storage/modules/pool-manager/components/configuration-preview/configuration-preview.component.ts
src/app/pages/storage/modules/pool-manager/components/existing-configuration-preview/existing-configuration-preview.component.html
src/app/pages/storage/modules/pool-manager/components/existing-configuration-preview/existing-configuration-preview.component.ts
src/app/pages/storage/modules/pool-manager/components/new-devices/new-devices-preview.component.html
src/app/pages/storage/modules/pool-manager/components/new-devices/new-devices-preview.component.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/9-review-wizard-step/review-wizard-step.component.html
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/9-review-wizard-step/review-wizard-step.component.ts
src/app/pages/storage/modules/pool-manager/pipes/topology-category-description.pipe.spec.ts
src/app/pages/storage/modules/pool-manager/pipes/topology-category-description.pipe.ts

git cherry-pick -x 1029572282fc7d511a0de3a9ed5e66992ca29f3a
git cherry-pick -x dd6ced2ca6afdf1a88fdddff6e6b43346396625f
git cherry-pick -x d105be277b087d5077b900bc69dc6d2d2085f61c
Original PR: https://github.com/truenas/webui/pull/8782
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123932

NAS-123932 / 23.10-RC.1 / Pool creation shows type for spares (by AlexKarpov98)

---

src/app/pages/storage/modules/pool-manager/components/configuration-preview/configuration-preview.component.ts
src/app/pages/storage/modules/pool-manager/store/pool-manager.store.ts

git cherry-pick -x f5c03f81adaa36db7769d910fd2389ede1025b4b
git cherry-pick -x b6a4891b46bf638130e82164d8281d941747a770
git cherry-pick -x 5660c556a4d504838238ff070adc099f44cc916f
git cherry-pick -x 966a9573c21e0ee250b800840b4dcef0bfc48758
git cherry-pick -x 52a2f35753c5294c17c720f8792827a604b61885
git cherry-pick -x 631083f4ebee8f5dccaeed1a945aece56963be3a
git cherry-pick -x f53a66f87676fa251494a74f9a34d4ead155e788
Original PR: https://github.com/truenas/webui/pull/8707
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123749

NAS-123749 / 23.10 /  "Spares" category from pool creation "Configuration Preview" inaccurate/unneeded (by AlexKarpov98)

---

src/app/pages/storage/modules/pool-manager/components/configuration-preview/configuration-preview.component.ts
src/app/pages/storage/modules/pool-manager/store/pool-manager.store.ts

git cherry-pick -x f5c03f81adaa36db7769d910fd2389ede1025b4b
git cherry-pick -x b6a4891b46bf638130e82164d8281d941747a770
git cherry-pick -x 5660c556a4d504838238ff070adc099f44cc916f
git cherry-pick -x 966a9573c21e0ee250b800840b4dcef0bfc48758
git cherry-pick -x 52a2f35753c5294c17c720f8792827a604b61885
git cherry-pick -x 631083f4ebee8f5dccaeed1a945aece56963be3a
git cherry-pick -x f53a66f87676fa251494a74f9a34d4ead155e788
Original PR: https://github.com/truenas/webui/pull/8707
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123749

NAS-123749 / 23.10-RC.1 /  "Spares" category from pool creation "Configuration Preview" inaccurate/unneeded (by AlexKarpov98)

---

src/app/pages/datasets/components/data-protection-card/data-protection-card.component.ts

For testing, go to datasets, and on the details panel, press the `Create Snapshot` button and close it, ensuring no `Snapshot added successfully` toast appears. Try to submit the form to ensure that the message appears.
Original PR: https://github.com/truenas/webui/pull/8790
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124004

NAS-124004 / 23.10 / Do not show success message when snapshot form is closed (by denysbutenko)

---

src/app/pages/datasets/components/data-protection-card/data-protection-card.component.ts

For testing, go to datasets, and on the details panel, press the `Create Snapshot` button and close it, ensuring no `Snapshot added successfully` toast appears. Try to submit the form to ensure that the message appears.
Original PR: https://github.com/truenas/webui/pull/8790
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124004

NAS-124004 / 23.10-RC.1 / Do not show success message when snapshot form is closed (by denysbutenko)

---

src/app/pages/sharing/iscsi/extent/extent-form/extent-form.component.ts

git cherry-pick -x 528d15b150d62494f5b01882dbca1d4a7913bf2f
git cherry-pick -x d0605c119892a74c557b249851a2a6a939434e78
git cherry-pick -x 88ec05c88a0028048ef80aef38fd3c8f8e7ddffd
Testing: when editing an extent that was created with type = Device, Device dropdown should be filled in.
Original PR: https://github.com/truenas/webui/pull/8804
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122258

NAS-122258 / 22.12.4 / Showing extent disk on edit (by undsoft)

---

src/app/pages/reports-dashboard/components/line-chart/line-chart.component.ts

Testing: See ticket.
Go to reports and try to zoom chart by hands, you will be stopped at some point (max 5 minutes)
If you try to zoom in greater (shorter distance) than 5 minutes (like 2 minutes)
You should be not able to do it and reset to previous valid time range.

NAS-123931 / 24.04 / Time axis on the reporting charts values incorrect on zooms

---

src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.scss

NAS-123985 / 24.04 / Misaligned warning icon in standby card

---

src/app/pages/reports-dashboard/components/line-chart/line-chart.component.ts

Testing: See ticket.
Go to reports and try to zoom chart by hands, you will be stopped at some point (max 5 minutes)
If you try to zoom in greater (shorter distance) than 5 minutes (like 2 minutes)
You should be not able to do it and reset to previous valid time range.
Original PR: https://github.com/truenas/webui/pull/8788
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123931

NAS-123931 / 23.10 / Time axis on the reporting charts values incorrect on zooms (by AlexKarpov98)

---

src/app/pages/reports-dashboard/components/line-chart/line-chart.component.ts

Testing: See ticket.
Go to reports and try to zoom chart by hands, you will be stopped at some point (max 5 minutes)
If you try to zoom in greater (shorter distance) than 5 minutes (like 2 minutes)
You should be not able to do it and reset to previous valid time range.
Original PR: https://github.com/truenas/webui/pull/8788
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123931

NAS-123931 / 23.10-RC.1 / Time axis on the reporting charts values incorrect on zooms (by AlexKarpov98)

---

src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.scss

Result:
Original PR: https://github.com/truenas/webui/pull/8819
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123985

NAS-123985 / 23.10 / Misaligned warning icon in standby card (by AlexKarpov98)

---

src/app/pages/apps/components/chart-wizard/chart-wizard.component.ts

**Summary**
Removed the line which was hiding the error modal window after it was already shown, which makes bad UX - "blinking" of error modal window
**Testing**
See ticket please
Original PR: https://github.com/truenas/webui/pull/8766
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123902

NAS-123902 / 23.10 / Show error message (by bvasilenko)

---

src/app/modules/common/dialog/error-dialog/error-dialog.component.html
src/app/modules/common/dialog/error-dialog/error-dialog.component.scss

For testing, go to backup credentials and open Cloud Credentials form, fill required data with random strings and press the "Verify Credentials" button to see the Error dialog. To have long string error you can replace the following line:
https://github.com/truenas/webui/blob/c82d0f048d474d0262cedd4e52291e4835a2656c/src/app/pages/credentials/backup-credentials/cloud-credentials-form/cloud-credentials-form.component.ts#L206
```diff
- message: response.excerpt,
+ message: Array.from({ length: 1000 }, () => String.fromCharCode(Math.floor(Math.random() * 26) + 97)).join('')
```
Original PR: https://github.com/truenas/webui/pull/8893
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124179

NAS-124179 / 23.10 / Fix long text in Error dialog (by denysbutenko)

---

src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.html
src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.ts
src/app/pages/dashboard/dashboard.module.ts

Changes:
- When product image returns 404 not found error - show fallback image instead of broken one
- Ensure there is single slash in the path: `/assets/images//servers/F100.png`
For testing, use system from the ticket.

NAS-124152 / 24.04 / Show fallback image when product image loading has failure

---

src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.html
src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.ts
src/app/pages/dashboard/dashboard.module.ts

Changes:
- When product image returns 404 not found error - show fallback image instead of broken one
- Ensure there is single slash in the path: `/assets/images//servers/F100.png`
For testing, use system from the ticket.
Original PR: https://github.com/truenas/webui/pull/8892
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124152

NAS-124152 / 23.10 / Show fallback image when product image loading has failure (by denysbutenko)

---

src/app/modules/ix-forms/components/ix-input/ix-input.component.scss

Check password field on sign-in page, ensure icon is aligned well.

NAS-124237 / 24.04 / Fix password icon in ix-input

---

src/app/pages/apps/store/apps-filter-store.service.ts
src/app/pages/apps/store/apps-store.service.ts
src/app/pages/apps/store/installed-apps-store.service.ts
src/app/pages/apps/store/kubernetes-store.service.ts
src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/base-provider-form.ts
src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/sftp-provider-form/sftp-provider-form.component.ts
src/app/pages/datasets/components/dataset-form/utils/dataset-form.service.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/pool-manager-wizard.component.ts
src/app/pages/system/file-ticket/file-ticket-form/file-ticket-form.component.ts
src/app/pages/system/file-ticket/file-ticket-licensed-form/file-ticket-licensed-form.component.ts
src/app/pages/system/update/update.component.ts
src/app/pages/vm/utils/vm-gpu.service.ts
src/app/services/gpu/gpu-service.spec.ts
src/app/services/gpu/gpu.service.ts
src/app/services/ws.service.ts

There is no concrete way to test this. I've removed instances where undefined is thrown. Also, in the websocket service job method, we were throwing the job object. Instead, we are now throwing the job error.
Original PR: https://github.com/truenas/webui/pull/8886
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123945

NAS-123945 / 23.10 / NAS-124077: Removing of(undefined) (by RehanY147)

---

src/app/pages/account/users/user-form/user-form.component.spec.ts
src/app/pages/account/users/user-form/user-form.component.ts

git cherry-pick -x bbbbd915cf5fee4af636b7a3b7fb4f98459cd7a6
git cherry-pick -x d6b83a08ba55b0fc86b78880a6a7d9eaff79007a
**Testing**
1. **Datasets > Add Dataset** Add a dataset named e.g. `home`
2. **Shares > Windows (SMB) Shares > Add**
- Path - this dataset (`home`)
- Purpose - **No presets**
- Use as Home Share - `true`
3. **Credentials \> Local Users \> Add**
- Full name - for example, `newUser`
- Password - for example, `qwerty`
- Create Home Directoty - `true`
**Expected Behavior:** A user should be added, with a Home Directory similar to `mnt/my pool/home/newUser`
Original PR: …

NAS-123426 / 22.12.4 / Fix default home path (by bvasilenko) (by bugclerk)

---

src/app/pages/account/users/user-form/user-form.component.spec.ts
src/app/pages/account/users/user-form/user-form.component.ts

git cherry-pick -x bbbbd915cf5fee4af636b7a3b7fb4f98459cd7a6
git cherry-pick -x d6b83a08ba55b0fc86b78880a6a7d9eaff79007a
**Testing**
1. **Datasets > Add Dataset** Add a dataset named e.g. `home`
2. **Shares > Windows (SMB) Shares > Add**
- Path - this dataset (`home`)
- Purpose - **No presets**
- Use as Home Share - `true`
3. **Credentials \> Local Users \> Add**
- Full name - for example, `newUser`
- Password - for example, `qwerty`
- Create Home Directoty - `true`
**Expected Behavior:** A user should be added, with a Home Directory similar to `mnt/my pool/home/newUser`
Original PR: …

NAS-123426 / 22.12.5 / Fix default home path (by bvasilenko) (by bugclerk)

---

src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/pool-manager-wizard.component.html

git cherry-pick -x 653b2e57a0dd6659b92e6ceecfd947aa208c8c5b
git cherry-pick -x 6302aa85aabc0d2f08eec1367a6a317723196a33
git cherry-pick -x 26c4b8e4749a4440f935b10f5936b30d3a35a6bc
git cherry-pick -x 279f977de3a752afef77bf2608ba026216020ecf
Testing:
see ticket, there should be no errors in console as well.
Original PR: https://github.com/truenas/webui/pull/8925
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124161

NAS-124161 / 23.10 / During pool creation on Cobia nightlies, if dRAID is selected as a layout other options are not available (by AlexKarpov98)

---

src/app/pages/apps/components/installed-apps/app-row/app-row.component.html
src/app/pages/apps/components/installed-apps/app-row/app-row.component.scss
src/app/pages/apps/components/installed-apps/app-status-cell/app-status-cell.component.html
src/app/pages/apps/components/installed-apps/app-status-cell/app-status-cell.component.spec.ts
src/app/pages/apps/components/installed-apps/installed-apps.component.html
src/app/pages/apps/components/installed-apps/installed-apps.component.scss
src/app/pages/apps/components/installed-apps/installed-apps.component.ts
src/app/pages/system/bootenv/bootenv-status/bootenv-status.component.scss

git cherry-pick -x caeb0c72e66e084f8f335fca3282df0e18608898
git cherry-pick -x 0c9f405d7c0ff4d35e7d6a053b8c33f5ed8951ab
git cherry-pick -x ad7195a486f6e9d01c65967a616be3e03fb3302b
git cherry-pick -x 10af49452ffa0e3d25772839c090280b5d13e7ab
git cherry-pick -x bd14cfe0c04671481487fd68d1c9ad0d73f9d8c5
Testing:
Check installed apps page, you should be able to sort by APPLICATION, STATUS, UPDATE AVAILABLE (if there are some apps with update available)
Original PR: https://github.com/truenas/webui/pull/8958
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124339

NAS-124339 / 23.10 / Sorting on installed applications screen (by AlexKarpov98)

---

src/app/pages/apps/store/apps-filter-store.service.ts

Testing:
Go to Available Apps section --> Search for any app and see that `New & Updated Apps`  section is not there while searching.
Original PR: https://github.com/truenas/webui/pull/8969
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123907

NAS-123907 / 23.10 / Do not show New & Updated in search results (by AlexKarpov98)

---

scripts/ui/models.json

To test run `yarn ui me -S` and make sure ES60G2 is listed in the output
NOTE: This does not need any backports. Reported problem only affects `stable/cobia` branch

NAS-124389 / 23.10 / Add es60g2 to models.json

---

src/app/pages/apps/components/installed-apps/app-notes-card/app-notes-card.component.scss

Testing: use inspector to put a long unbreakable string in App -> Notes.

NAS-124397 / 24.04 / Notes card in apps UI does not show full text

---

src/app/views/sessions/signin/signin-form/signin-form.component.html
src/app/views/sessions/signin/signin-form/signin-form.component.ts

Testing: 
See that on login page you don't see `Validators.required` error if **username** or **password** field is empty.
Form shall stay disabled if value is empty tho.

NAS-124222 / 24.04 / Login page error mesage Username is required

---

src/app/pages/apps/components/installed-apps/app-notes-card/app-notes-card.component.scss

Testing: use inspector to put a long unbreakable string in App -> Notes.
Original PR: https://github.com/truenas/webui/pull/8976
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124397

NAS-124397 / 23.10 / Notes card in apps UI does not show full text (by undsoft)

---

src/app/views/sessions/signin/signin-form/signin-form.component.html
src/app/views/sessions/signin/signin-form/signin-form.component.ts

Testing: 
See that on login page you don't see `Validators.required` error if **username** or **password** field is empty.
Form shall stay disabled if value is empty tho.
Original PR: https://github.com/truenas/webui/pull/8970
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124222

NAS-124222 / 23.10 / Login page error mesage Username is required (by AlexKarpov98)

---

src/app/pages/dashboard/components/widget-cpu/widget-cpu.component.html
src/app/pages/dashboard/components/widget-cpu/widget-cpu.component.ts

If temp values are 0, that means temperature values are not available for the CPU and we should show the user `'N/A'`
Original PR: https://github.com/truenas/webui/pull/8950
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124044

NAS-124044 / 24.04 / Adapt to 0 values (by RehanY147)

---

src/app/interfaces/virtual-machine.interface.ts
src/app/pages/vm/vm-list/vm-list.component.ts

Wait for https://github.com/truenas/middleware/pull/12200 to be ported to `cobia` before testing. This removes the need for UI to make decisions about whether or not to show the display button for running vms. Now, middleware will tell us if a display is available or not.

NAS-124232 / 23.10 / Added query param to fetch `display_available` attribute

---

src/app/interfaces/virtual-machine.interface.ts
src/app/pages/vm/vm-list/vm-list.component.ts

Wait for https://github.com/truenas/middleware/pull/12200 to be ported to `cobia` before testing. This removes the need for UI to make decisions about whether or not to show the display button for running vms. Now, middleware will tell us if a display is available or not.
Original PR: https://github.com/truenas/webui/pull/8956
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124232

NAS-124232 / 24.04 / Added query param to fetch `display_available` attribute (by RehanY147)

---

src/app/pages/sharing/smb/smb-form/smb-form.component.ts

Original PR: https://github.com/truenas/webui/pull/9039
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124606

NAS-124606 / 23.10.0 / Duplicate name error is not shown in SMB shares (by AlexKarpov98)

---

src/app/pages/network/components/interface-form/interface-form.component.ts

git cherry-pick -x 7729a1f88e2d5c3831fc6e58e05c4195ad1557f7
git cherry-pick -x e00164511e5d82d560aeca175c9923cc7a755f0e
Testing: check ticket I think code review is enough.
Original PR: https://github.com/truenas/webui/pull/9065
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124681

NAS-124681 / 23.10.0 / Race condition in interface form (by AlexKarpov98)

---

src/app/pages/network/components/interface-form/interface-form.component.ts

git cherry-pick -x 7729a1f88e2d5c3831fc6e58e05c4195ad1557f7
git cherry-pick -x e00164511e5d82d560aeca175c9923cc7a755f0e
Testing: check ticket I think code review is enough.
Original PR: https://github.com/truenas/webui/pull/9065
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124681

NAS-124681 / 23.10.1 / Race condition in interface form (by AlexKarpov98)

---

src/app/modules/ix-table2/components/ix-table-body/cells/ix-cell-actions/ix-cell-actions.component.ts
src/app/modules/ix-table2/components/ix-table-body/cells/ix-cell-checkbox/ix-cell-checkbox.component.ts
src/app/modules/ix-table2/components/ix-table-body/cells/ix-cell-date/ix-cell-date.component.ts
src/app/modules/ix-table2/components/ix-table-body/cells/ix-cell-relative-date/ix-cell-relative-date.component.ts
src/app/modules/ix-table2/components/ix-table-body/cells/ix-cell-schedule/ix-cell-schedule.component.ts
src/app/modules/ix-table2/components/ix-table-body/cells/ix-cell-size/ix-cell-size.component.ts
src/app/modules/ix-table2/components/ix-table-body/cells/ix-cell-state-button/ix-cell-state-button.component.ts
src/app/modules/ix-table2/components/ix-table-body/cells/ix-cell-template/ix-cell-template.component.ts
src/app/modules/ix-table2/components/ix-table-body/cells/ix-cell-text/ix-cell-text.component.ts
src/app/modules/ix-table2/components/ix-table-body/cells/ix-cell-toggle/ix-cell-toggle.component.ts
src/app/modules/ix-table2/components/ix-table-body/cells/ix-cell-yesno/ix-cell-yesno.component.spec.ts
src/app/modules/ix-table2/components/ix-table-body/cells/ix-cell-yesno/ix-cell-yesno.component.ts
src/app/modules/ix-table2/components/ix-table-head/head-cells/ix-header-cell-checkbox/ix-header-cell-checkbox.component.ts
src/app/modules/ix-table2/components/ix-table-head/head-cells/ix-header-cell-text/ix-header-cell-text.component.ts
src/app/pages/dashboard/components/dashboard/dashboard.component.ts
src/app/pages/dashboard/components/widget-controller/widget-controller.component.ts
src/app/pages/dashboard/components/widget-help/widget-help.component.ts
src/app/pages/dashboard/components/widget-network/widget-network.component.ts
src/app/pages/dashboard/components/widget-pool-wrapper/widget-pool-wrapper.component.ts
src/app/pages/dashboard/components/widget-pool/widget-pool.component.ts
src/app/pages/dashboard/components/widget-storage/widget-storage.component.ts
src/app/pages/dashboard/components/widget-sys-info/simple-failover-btn.component.ts
src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.ts
src/app/pages/dashboard/components/widget/widget.component.ts
src/app/pages/network/components/interfaces-card/interfaces-card.component.ts

**Summary** 
This is an optimization of redundant UI updates at 2 different places:
1. OnPush at ix-table2
2. OnPush at `pages/dashboard`
**Testing**
1. Test that pages/dashboard displaying up-to-date information:
- from the hardware reporting streams
- when pool gets added or removed (exported) 
- when 2nd network adapter gets connected and disconnected
2. Test that UI stays up-to-date during interactions on the pages where ix-table2 is used.

NAS-124724 / 24.04 / Update to `ChangeDetection.OnPush` in ix-table2 and pages/dashboard

---

src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts

**Testing**
On **Credentials \> Backup Credentials \> Cloud Credentials** connect to any Dropbox account for debugging.
On **Data Protection** page,
Set up a Dropbox cloud sync task. Under **Remote**, in the **Folder** section, click the triangle to expand the / folder; it will show all of the first-level subfolders.
* **Expected:** every subfolder to have a clickable "triangle" icon , and when clicked it displays deeper subfolders

NAS-124703 / 24.04 / Fix `bucketNodeProvider`

---

src/app/pages/system/view-enclosure/stores/enclosure-store.service.ts

**Testing**
1. Connect to `remote:`
2. Go to **System Settings > Enclosure** page
- **Expected Result:** DRAID pools and related disks should be shown in the Enclosure UI.

NAS-124727 / 24.04 / Show disks assigned to configured DRAID

---

src/app/pages/system/view-enclosure/stores/enclosure-store.service.ts

**Testing**
1. Connect to `remote:`
2. Go to **System Settings > Enclosure** page
- **Expected Result:** DRAID pools and related disks should be shown in the Enclosure UI.
Original PR: https://github.com/truenas/webui/pull/9109
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124727

NAS-124727 / 23.10.1 / Show disks assigned to configured DRAID (by bvasilenko)

---

src/app/modules/ix-tree/components/nested-tree-node/nested-tree-node.component.scss
src/app/modules/ix-tree/components/tree-view/tree-view.component.scss
src/app/modules/ix-tree/components/tree-virtual-scroll-view/tree-virtual-scroll-view.component.scss

git cherry-pick -x c1eefa4108e9043f8fbd26ddbdb35eb8925fcdcf
git cherry-pick -x 928c173382f09caa2ba8ad378939ffe4d9b7a10d
Testing: 
check that rows are aligned correctly now:
Before it was like:
Original PR: https://github.com/truenas/webui/pull/9104
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124763

NAS-124763 / 23.10.0 / Incorrect indentation in dataset tree (by AlexKarpov98)

---

src/app/modules/ix-tree/components/nested-tree-node/nested-tree-node.component.scss
src/app/modules/ix-tree/components/tree-view/tree-view.component.scss
src/app/modules/ix-tree/components/tree-virtual-scroll-view/tree-virtual-scroll-view.component.scss

git cherry-pick -x c1eefa4108e9043f8fbd26ddbdb35eb8925fcdcf
git cherry-pick -x 928c173382f09caa2ba8ad378939ffe4d9b7a10d
Testing: 
check that rows are aligned correctly now:
Before it was like:
Original PR: https://github.com/truenas/webui/pull/9104
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124763

NAS-124763 / 23.10.1 / Incorrect indentation in dataset tree (by AlexKarpov98)

---

src/app/modules/ix-forms/components/ix-select/ix-select.component.html
src/app/modules/ix-forms/components/ix-select/ix-select.component.scss
src/app/modules/ix-forms/components/ix-select/ix-select.component.spec.ts
src/app/modules/ix-forms/components/ix-select/ix-select.component.ts
src/app/pages/credentials/backup-credentials/cloud-credentials-card/cloud-credentials-card.component.html
src/app/pages/reports-dashboard/components/reports-global-controls/reports-global-controls.component.html
src/app/pages/reports-dashboard/components/reports-global-controls/reports-global-controls.component.ts
src/assets/styles/other/_tn-styles.scss

Testing: See updated select component with "Select All" option.

NAS-124670 / 24.04 / Reporting disks view improvements for large disk systems

---

src/app/pages/storage/modules/devices/components/zfs-info-card/extend-dialog/extend-dialog.component.html
src/app/pages/storage/modules/devices/components/zfs-info-card/extend-dialog/extend-dialog.component.spec.ts
src/app/pages/storage/modules/devices/components/zfs-info-card/extend-dialog/extend-dialog.component.ts
src/app/pages/storage/modules/disks/components/replace-disk-dialog/replace-disk-dialog.component.html
src/app/pages/storage/modules/disks/components/replace-disk-dialog/replace-disk-dialog.component.ts
src/assets/styles/other/_tn-styles.scss

Testing: Go to Devices and click Replace
Disks input shall appear and now they are sorted alphabetically and filtering is available.
As well selected item is highlighted (fixed this issue - before it was not)

NAS-124732 / 24.04 / Request:  Improve sorting for Replace Disk Search for DRAIDs 

---

src/app/pages/storage/modules/devices/components/zfs-info-card/extend-dialog/extend-dialog.component.html
src/app/pages/storage/modules/devices/components/zfs-info-card/extend-dialog/extend-dialog.component.spec.ts
src/app/pages/storage/modules/devices/components/zfs-info-card/extend-dialog/extend-dialog.component.ts
src/app/pages/storage/modules/disks/components/replace-disk-dialog/replace-disk-dialog.component.html
src/app/pages/storage/modules/disks/components/replace-disk-dialog/replace-disk-dialog.component.ts
src/assets/styles/other/_tn-styles.scss

git cherry-pick -x 3e5bc6b2203ce78e69e1a7c00e0d745fe9fedbeb
git cherry-pick -x 853d6dc73e5938eda6f4622b72ddbac41f66fd1b
git cherry-pick -x 3f04673a206aeb62a60e1ac6b799c81b98e0d8c6
git cherry-pick -x 92cc911d734d0e1222a8cdb54ba6b542c057beed
Testing: Go to Devices and click Replace
Disks input shall appear and now they are sorted alphabetically and filtering is available.
As well selected item is highlighted (fixed this issue - before it was not)
Original PR: https://github.com/truenas/webui/pull/9111
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124732

NAS-124732 / 23.10.1 / Request:  Improve sorting for Replace Disk Search for DRAIDs  (by AlexKarpov98)

---

src/app/services/websocket-connection.service.ts

**Summary**
The bug, which is reported in the ticket, appeared due to the code in line 21 in file **src/app/store/system-info/system-info.effects.ts** ( 83c73779fbbe1fc43877524a0d791d05bfb8164c). The middleware returns a response with error code `207` and `ws$.complete()` is called.
After the fix, the the connection will be closed and reopened only once.

NAS-124756 / 24.04 / Return ws data after auth error

---

src/app/pages/storage/modules/devices/components/zfs-info-card/zfs-info-card.component.ts

Backported
**Testing**
1. Connect to `remote: '10.220.16.10', // m60-100.dc1.ixsystems.net`
2. On Storage > (Pool block) > Manage Devices page,
- **Expected Result:** When actions “Extend” and “Remove” are not applicable (see ticket), the respective buttons should not be displayed in WebUI in the aforementioned conditions.
Original PR: https://github.com/truenas/webui/pull/9114
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124731

NAS-124731 / 23.10.1 / Remove the "Remove" and "Extend" buttons for the DRAID pool (by bvasilenko)

---

src/app/pages/dashboard/components/dashboard/dashboard.component.html
src/app/pages/dashboard/components/dashboard/dashboard.component.ts

Testing: see ticket and result.
I think we can just show loaders with static 6 items, we don't need more or less. After some updates we got empty page and then widgets.
Result:

NAS-125003 / 24.04 / Dashboard is missing Loading State (only blank screen)

---

src/app/pages/apps/components/chart-wizard/chart-wizard.component.ts
src/app/services/schema/app-schema.transformer.ts

git cherry-pick -x a5c777e2ce2f1e9fadb1ba76c39b2986e59a4a0d
git cherry-pick -x bf3ee7a062ce3f41064b9b01cbe3aa0bd1ac1906
Testing: see ticket, on m40 I tested with `komga` app:
http://localhost:4200/apps/installed/TRUENAS/community/komga-krpv/edit
Newly added items in edit mode shall be editable:
Correct logic: 
IMMUTABLE field - is only for EDIT mode, but it should not spread on the ADD NEW ITEM ON THE LIST in EDIT mode.
We made a bug where we spread IMMUTABLE field for new item on the list in edit mode.
Original PR: https://github.com/truenas/webui/pull/9172
Jira URL: …

NAS-124947 / 23.10.1 / [Apps/UI]: Immutable fields in an item, leaks in other items too (by AlexKarpov98)

---

src/app/modules/ix-table2/components/ix-table-body/ix-table-body.component.html
src/app/modules/ix-table2/components/ix-table-body/ix-table-body.component.scss
src/app/pages/apps/components/available-apps/available-apps.component.scss
src/app/pages/apps/components/installed-apps/installed-apps.component.html
src/app/pages/apps/components/installed-apps/installed-apps.component.scss
src/app/pages/apps/components/installed-apps/installed-apps.component.ts
src/app/pages/audit/audit.module.ts
src/app/pages/audit/components/audit/audit.component.html
src/app/pages/audit/components/audit/audit.component.scss
src/app/pages/datasets/components/dataset-management/dataset-management.component.html
src/app/pages/datasets/components/dataset-management/dataset-management.component.scss
src/app/pages/storage/modules/devices/components/devices/devices.component.html
src/app/pages/storage/modules/devices/components/devices/devices.component.scss
src/app/pages/storage/modules/devices/components/disk-details-panel/disk-details-panel.component.scss
src/assets/styles/mixins/cards.scss
src/assets/styles/mixins/layout.scss

Testing:
Check ticket and all related pages with similar layout:
- Datasets
- Devices
- Apps
- Audit
Upon scroll you should see search & table header sticked to the top while scrolling.
There should be less scrollbars or only one (to control the page scroll)

NAS-124962 / 24.04 / Fix scrolling on pane-details layout

---

src/app/pages/storage/modules/pool-manager/components/configuration-preview/configuration-preview.component.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/layout-step/automated-disk-selection/automated-disk-selection.component.spec.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/layout-step/automated-disk-selection/automated-disk-selection.component.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/pool-manager-wizard.component.html
src/app/pages/storage/modules/pool-manager/components/pool-manager/tests/draid-pool-creation.spec.ts
src/app/pages/storage/modules/pool-manager/store/pool-manager.store.ts

Check ticket description for issue details. This PR also fixes an additional bug where when creating a new pool, adding the spare vdev although seems to be successful, doesn't show up on the review step.
Original PR: https://github.com/truenas/webui/pull/9167
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124985

NAS-124985 / 23.10.1 / Removing mutability of state object (by RehanY147)

---

src/app/pages/system/general-settings/save-config-dialog/save-config-dialog.component.scss

Result:
Button are wrapped if text is not fitting for 1 row, as well added UI improvement with margin top for the buttons wrapper 
before margin:

NAS-124968 / 24.04 / Display problem with the French translation

---

src/app/pages/datasets/components/dataset-form/sections/other-options-section/other-options-section.component.spec.ts
src/app/pages/datasets/components/dataset-form/sections/other-options-section/other-options-section.component.ts

When editing a dataset, set value for the `Metadata (Special) Small Block Size` field in the `Advanced Fields`. Save the form successfully and then edit it again. The field should be populated with the last saved value.

NAS-124826 / 23.10.1 / Using rawvalue instead of value

---

src/app/pages/datasets/components/dataset-form/sections/other-options-section/other-options-section.component.spec.ts
src/app/pages/datasets/components/dataset-form/sections/other-options-section/other-options-section.component.ts

When editing a dataset, set value for the `Metadata (Special) Small Block Size` field in the `Advanced Fields`. Save the form successfully and then edit it again. The field should be populated with the last saved value.
Original PR: https://github.com/truenas/webui/pull/9195
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124826

NAS-124826 / 24.04 / Using rawvalue instead of value (by RehanY147)

---

src/app/pages/reports-dashboard/reports-dashboard.component.html
src/app/pages/reports-dashboard/reports-dashboard.component.scss

Similar to https://github.com/truenas/webui/pull/9162
We are getting blank screen on reports page for a fraction of a second. 
Test that you see loaders and no empty screen.

NAS-125124 / 24.04 / Reports page is not showing preloader on initial load if I reload the page, I see empty page

---

src/app/pages/vm/devices/device-form/device-form.component.ts

Go to the team VM with this PR, edit an NIC device on one of the VMs which has a mac address configured. When editing such a device, the mac adress field should show the previous value instead of a randomly generated value.
Original PR: https://github.com/truenas/webui/pull/9197
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124741

NAS-124741 / 24.04 / Wait for existing values before subscribing to type (by RehanY147)

---

src/app/interfaces/api/api-call-directory.interface.ts
src/app/pages/vm/vm-edit-form/vm-edit-form.component.spec.ts
src/app/pages/vm/vm-edit-form/vm-edit-form.component.ts
src/app/pages/vm/vm-wizard/vm-wizard.component.spec.ts
src/app/pages/vm/vm-wizard/vm-wizard.component.ts

**Testing**
Mock response for `device.get_gpus`
```
❯ midclt call device.get_gpus | jq .
[
{
"addr": {
"pci_slot": "0000:01:00.0",
"domain": "0000",
"bus": "01",
"slot": "00"
},
"description": "NVIDIA Corporation GM206 [GeForce GTX 960]",
"devices": [
{
"pci_id": "10DE:1401",
"pci_slot": "0000:01:00.0",
"vm_pci_slot": "pci_0000_01_00_0"
},
{
"pci_id": "10DE:0FBA",
"pci_slot": "0000:01:00.1",
"vm_pci_slot": "pci_0000_01_00_1"
}
],
"vendor": "NVIDIA",
"uses_system_critical_devices": false,
"available_to_host": true
}
]
```

NAS-125161 / 24.04 / Get PCI ids for GPU isolation

---

src/app/services/storage.service.spec.ts
src/app/services/storage.service.ts

**Testing**
1. Go to **System > Advanced > Storage**, reset **Swap Size** to 2Gb (default value)
2. Create pool with 1 VDEV
2. Adjust **Swap Size** to a different value, for example 1Gb
4. Add another VDEV to your pool
**Expected:** No warnings next to "mixed capacity" at **Storage > Topology**

NAS-125192 / 24.04 / Hide "Mixed Capacity Vdevs" alert for vdevs with ≤2GiB difference eg: vdevs created with different SWAP settings

---

src/app/modules/ix-forms/components/ix-input/ix-input.component.ts
src/app/pages/apps/components/chart-wizard/chart-wizard.component.spec.ts
src/app/services/schema/app-schema.service.ts

Testing: 
See tests updated, the order of the schema items changed but still it should work as expected.
Currently it was not working - because if there were no control yet, we created new one (hidden by default) [what is wrong]
Please use m40 device and go here:
Go to Apps -> Discover -> Minio 👇 
http://localhost:4200/apps/available/TRUENAS/charts/minio/install
or Ask @stavros-k for an app if the one I provided is not there anymore.
Before: (we didn't see `Minio Certificate` even tho it has no **show_if** logic)
Now: (we see `Minio Certificate` and don't see `Minio Domain Name` because it depends on the Minio Certificate value and by default it's null, so we don't want to show Minio Domain Name in this case)

NAS-125008 / 24.04 / Apps: When a `show_if` tries to evaluate a field that is defined after it, results in both fields being hidden in the UI

---

src/app/interfaces/api-directory.interface.ts
src/app/pages/vm/vm-edit-form/vm-edit-form.component.spec.ts
src/app/pages/vm/vm-edit-form/vm-edit-form.component.ts
src/app/pages/vm/vm-wizard/vm-wizard.component.spec.ts
src/app/pages/vm/vm-wizard/vm-wizard.component.ts

**Testing**
Mock response for `device.get_gpus`
```
❯ midclt call device.get_gpus | jq .
[
{
"addr": {
"pci_slot": "0000:01:00.0",
"domain": "0000",
"bus": "01",
"slot": "00"
},
"description": "NVIDIA Corporation GM206 [GeForce GTX 960]",
"devices": [
{
"pci_id": "10DE:1401",
"pci_slot": "0000:01:00.0",
"vm_pci_slot": "pci_0000_01_00_0"
},
{
"pci_id": "10DE:0FBA",
"pci_slot": "0000:01:00.1",
"vm_pci_slot": "pci_0000_01_00_1"
}
],
"vendor": "NVIDIA",
"uses_system_critical_devices": false,
"available_to_host": true
}
]
```
Original PR: https://github.com/truenas/webui/pull/9203
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125161

NAS-125161 / 23.10.1 / Get PCI ids for GPU isolation (by bvasilenko)

---

src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/7-metadata-wizard-step/metadata-wizard-step.component.spec.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/7-metadata-wizard-step/metadata-wizard-step.component.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/8-dedup-wizard-step/dedup-wizard-step.component.html
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/8-dedup-wizard-step/dedup-wizard-step.component.spec.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/8-dedup-wizard-step/dedup-wizard-step.component.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager/tests/add-vdev-to-pool.spec.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager/tests/create-pool.spec.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager/tests/wizard-start-over.spec.ts

Backported
**Testing**
Have at least 12 disks. Ensure it's possible to create a pool specified in the ticket. 
I. **Layout** UI element and **Width,** **VDEVs** options under **Metadata** or **Dedup** sections
1. On **Storage** \> **Create Pool**, at **Data** expandable section, select these options:
1. Layout: **RAIDZ1**
2. Width: **5**
3. VDEVs: **2**
2. At **Metadata** expandable section, try to select these options:
1. Layout: **Mirror**
2. Width: **2**
3. VDEVs: **1**
* **Expected:**
* **Layout:** this UI element is shown,
* **Width:** list of available options should contain the proper options
* **VDEVs:** list of available options should contain the proper options
* The submission of the whole **Create Pool** form: does not require force-creation, and is correctly recognized after …

NAS-124802 / 23.10.1 / Add Metadata or Dedup VDEV types (by bvasilenko)

---

src/app/pages/credentials/backup-credentials/cloud-credentials-form/cloud-credentials-form.component.spec.ts
src/app/pages/credentials/backup-credentials/cloud-credentials-form/cloud-credentials-form.component.ts
src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/base-provider-form.ts
src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/sftp-provider-form/sftp-provider-form.component.ts

For testing, go to Backup Credentials, edit SFTP credentials, and ensure that `cloudsync.credentials.verify` is sent to middleware when you press on the `Verify Credentials` button.

NAS-124897 / 24.04 / Fix verify credentials in Cloud Credentials form

---

src/app/pages/credentials/backup-credentials/cloud-credentials-form/cloud-credentials-form.component.spec.ts
src/app/pages/credentials/backup-credentials/cloud-credentials-form/cloud-credentials-form.component.ts
src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/base-provider-form.ts
src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/sftp-provider-form/sftp-provider-form.component.ts

For testing, go to Backup Credentials, edit SFTP credentials, and ensure that `cloudsync.credentials.verify` is sent to middleware when you press on the `Verify Credentials` button.
Original PR: https://github.com/truenas/webui/pull/9218
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124897

NAS-124897 / 23.10.1 / Fix verify credentials in Cloud Credentials form (by denysbutenko)

---

src/app/pages/data-protection/replication/replication-form/sections/source-section/source-section.component.html
src/app/pages/data-protection/replication/replication-form/sections/transport-section/transport-section.component.ts

**Summary**
1. Ticket's video contains a mandatory field `periodic_snapshot_tasks` which was not filled. This field is not mandatory in the middleware, so I made `periodic_snapshot_tasks` not mandatory in WebUI as well
2. Ticket's screenshots depict expectation of the required ssh credentials field, for LOCAL, where obviously this should not be there. This is fixed in a 2nd commit
**Testing**
Data Protection > Replication Tasks > Add > Advanced Replication Creation

NAS-124951 / 23.10.1 / Remove required for periodic_snapshot_tasks, Disable ssh_credentials when transport is local

---

src/app/interfaces/reporting.interface.ts
src/app/modules/common/interface-status-icon/interface-status-icon.component.spec.ts
src/app/modules/common/interface-status-icon/interface-status-icon.component.ts
src/app/pages/dashboard/components/widget-network/widget-network.component.ts

For testing, use the latest nightly, check the dashboard and ensure no console errors are emitted.
send_bytes/received_bytes keys were removed in https://github.com/truenas/middleware/pull/12502

NAS-125343 / 24.04 / Fix network send/receive rate

---

src/app/pages/system/update/manualupdate/manualupdate.component.ts
src/app/pages/system/update/update.component.ts
src/app/services/update.service.ts

git cherry-pick -x 49f0ce51a9c205931beb27dae556708f6d49dd17
git cherry-pick -x 78accace50af295d739c8ba877575ab7c9fefd1d
git cherry-pick -x d7536b82ed1b1b76ca6715d5514dee82302ba256
git cherry-pick -x abe7ac845e0aea9607c67d9167f614a2d38dab8f
Testing: update a system and see that UI reloads after update is complete.
Background tabs and tabs in other browser should also reload.
Original PR: https://github.com/truenas/webui/pull/9236
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124602

NAS-124602 / 13.0 / Reload UI during updates (by undsoft)

---

src/app/interfaces/reporting.interface.ts
src/app/pages/dashboard/components/widget-network/widget-network.component.ts
src/app/pages/network/components/interfaces-card/interface-status-icon/interface-status-icon.component.spec.ts
src/app/pages/network/components/interfaces-card/interface-status-icon/interface-status-icon.component.ts

git cherry-pick -x 8bc2be324b29dda799ba99285e072b8fb1709c99
git cherry-pick -x e34c6a28864739421bf796c9951a76cf6a5d5ac4
git cherry-pick -x 3ea80b4b1a510f0bba28dc0d3e5f501f662d6ccb
For testing, use the latest nightly, check the dashboard and ensure no console errors are emitted.
send_bytes/received_bytes keys were removed in https://github.com/truenas/middleware/pull/12502
Original PR: https://github.com/truenas/webui/pull/9238
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125343

NAS-125343 / 23.10.1 / Fix network send/receive rate (by denysbutenko)

---

src/app/modules/ix-table2/classes/api-data-provider/api-data-provider.ts
src/app/modules/ix-table2/classes/api-data-provider/pagination-client-side.ts
src/app/modules/ix-table2/classes/api-data-provider/pagination-server-side.class.ts
src/app/modules/ix-table2/classes/api-data-provider/sorting-client-side.class.ts
src/app/modules/ix-table2/classes/api-data-provider/sorting-server-side.class.ts
src/app/modules/ix-table2/classes/async-data-provider/async-data-provider.spec.ts
src/app/modules/ix-table2/classes/async-data-provider/async-data-provider.ts
src/app/modules/ix-table2/interfaces/table-pagination.interface.ts
src/app/modules/ix-table2/interfaces/table-sort.interface.ts

Separate `ApiDataProvider` from `AsyncDataProvider`
This PR separates responsibilities of `ApiDataProvider` from `AsyncDataProvider`. `AsyncDataProvider` will be responsible for handling the pagination, sorting and filtering on the front-end.
`ApiDataProvider` will be responsible for handling the pagination, sorting and filtering on the back-end. `AsyncDataProvider` already has default sorting and pagination from `BaseDataProvider`

NAS-124964 / 24.04 / Only server side pagination/sorting in ApiDataProvider

---

src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/7-metadata-wizard-step/metadata-wizard-step.component.ts

Check the correct step for existing pools
Create a new pool with a metadata vdev.
Go to edit the pool devices and see if the metadata step has the correct vdev type that was assigned when creating the pool originally.
Original PR: https://github.com/truenas/webui/pull/9273
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125438

NAS-125438 / 23.10.1 / Fix step checking (by RehanY147)

---

src/app/pages/datasets/modules/permissions/containers/permissions-card/permissions-card.component.spec.ts
src/app/pages/datasets/modules/permissions/stores/permissions-card.store.ts

Testing: 
see ticket, example (use m40), go to http://localhost:4200/datasets/APPS%2Fa%2Fsmbtest
see permissions card:
And edit state:
They shall be identical.

NAS-125444 / 24.04 / Incorrect acl description in Permissions card

---

src/app/modules/scheduler/utils/schedule-to-crontab.spec.ts
src/app/modules/scheduler/utils/schedule-to-crontab.utils.ts
src/app/pages/data-protection/snapshot/snapshot-list/snapshot-list.component.ts

git cherry-pick -x b75a00037e80ac00d34adc49063a1441bb7bbb6c
git cherry-pick -x 5c38d6f036532bbbb774df27e738c927c7cc2e7c
git cherry-pick -x f1547cfac9253d612245c0aa53e13c6ffa621eba
Testing: 
See ticket and result and test case: 👇 
Original PR: https://github.com/truenas/webui/pull/9294
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125484

NAS-125484 / 23.10.2 / Incorrect When time displayed on periodic snapshot tasks screen (by AlexKarpov98)

---

src/app/modules/ix-feedback/feedback-dialog/feedback-dialog.component.ts
src/app/modules/ix-feedback/file-ticket-form/file-ticket-form.component.ts
src/app/pages/system/general-settings/support/support-card/support-card.component.ts

- Allow to pass default feedback type.
- Revert `choicesToOptions` usage due to regression.
For testing check the ticket.

NAS-125653 / 24.04 / Default to Report a bug when clicking File Ticket

---

src/assets/styles/other/_root-variables.scss

Testing: 👇 
Before: _(notice Readonly Administrators background)_
After:

NAS-125696 / 24.04 / ix-chips options are transparent at some point

---

src/assets/styles/other/_root-variables.scss

Testing: 👇 
Before: _(notice Readonly Administrators background)_
After:
Original PR: https://github.com/truenas/webui/pull/9319
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125696

NAS-125696 / 23.10.2 / ix-chips options are transparent at some point (by AlexKarpov98)

---

src/app/pages/account/groups/group-form/group-form.component.ts

Contains fix for correct work.
There's incorrect check added
`if (this.editingGroup?.id) {}`
But we call method on init for both edit & create mode. `getPrivilegesList`

NAS-125570 / 24.04 / Allow privilege to be attached in group form (fix)

---

src/app/pages/credentials/certificates-dash/certificate-authority-list/certificate-authority-list.component.ts
src/app/pages/credentials/certificates-dash/certificate-list/certificate-list.component.ts
src/app/pages/credentials/certificates-dash/certificates-dash.component.html
src/app/pages/credentials/certificates-dash/sign-csr-dialog/sign-csr-dialog.component.ts

Testing: see ticket (there is video)
Additional:
I tried to update tests to include checks of API calls and value `emit`, but was not able to find `DELETE` button after I open modal, and can't find any working test with same conditions.
```    
expect(spectator.inject(MatDialog).open).toHaveBeenCalledWith(ConfirmForceDeleteCertificateComponent, {
data: certificates[0],
});
```
```
ailed to find element matching one of the following queries:
(_MatButtonHarness with host element matching selector: "[mat-button], [mat-raised-button], [mat-flat-button],
[mat-icon-button], [mat-stroked-button], [mat-fab], [mat-mini-fab]" satisfying the constraints: text = "Delete")
```

NAS-125616 / 24.04 / An Internally Signed Certificate Requires a Page Reload To Display After Creation On The Certificates Page

---

src/app/modules/entity/entity-table/entity-table-row-details/entity-table-row-details.component.scss

Currently, if the text in the right column of `entity-table-row-details` is too long and doesn't contain enouch characters that usually allow line breaks (like spaces and hyphens) the text will overflow. Because the text is in a table this also messes with the layout of the columns of the `entity-table`:
This PR fixes this by adding the `word-break: break-word` CSS property to the `p`-element:

Prevent text overflow in entity-table-row-details

---

src/app/helptext/vm/vm-wizard/vm-wizard.ts

Ideally, the New VM wizard UI should also be updated to show that the Bind and Password fields are related to the VNC display device. I'm not sure what the best way to do that is.
- Group the fields visually
- Rename the fields to "Display bind" and "Display password" and update all of the translations

Clarify what the VM password field is for

---

src/app/interfaces/api/api-call-directory.interface.ts
src/app/interfaces/system-info.interface.ts
src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.html
src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.ts

Testing: See ticket.
See that Dashboard Widget works for `HA systems` as well for the non-iX hardware system
I used: 
- Latest nightly (machine) for non-iX hardware system
- f60-146... (machine) for HA systems
These ones should have latest API on it.
As well the idea is not use `'failover.call_remote'` endpoint.

NAS-125870 / 24.04 / New endpoint for system info card on main dashboard

---

src/app/pages/dashboard/components/widget-network/widget-network.component.ts

This PR reverts changes mistakenly made. The values returned by `reporting.netdata_get_data` are in Kbps so they need to be converted to bytes before UI can use it. Meaning, this multiplication was needed.

NAS-125832 / 23.10.2 / Reverting changes

---

src/app/pages/dashboard/components/widget-network/widget-network.component.ts

This PR reverts changes mistakenly made. The values returned by `reporting.netdata_get_data` are in Kbps so they need to be converted to bytes before UI can use it. Meaning, this multiplication was needed.

NAS-125832 / 24.04 / Reverting changes from `NAS-125832-DF` branch

---

src/app/pages/dashboard/components/widget-network/widget-network.component.ts

This PR reverts changes mistakenly made. The values returned by `reporting.netdata_get_data` are in Kbps so they need to be converted to bytes before UI can use it. Meaning, this multiplication was needed.
Original PR: https://github.com/truenas/webui/pull/9395
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125832

NAS-125832 / 23.10.1.1 / Reverting changes (by RehanY147)

---

src/app/pages/datasets/components/dataset-capacity-management-card/space-management-chart/space-management-chart.component.html

Testing: see ticket and result 👇 :

NAS-125488 / 24.04 / Datasets: Dataset space management does not show the exact number, it shows the number as a rounded number.

---

src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.scss

NAS-125495 / 24.04 / Enclosure management - list of drives off the screen and not scrollable

---

src/app/pages/storage/components/pools-dashboard/pools-dashboard.component.ts

Handling case where missing disks for a specific pool make the topology card fail on the Storage page for pools.

NAS-124814 / 23.10.2 / Handling case for no disks for a specific pool

---

src/assets/i18n/de.json

See for example https://de.wikipedia.org/wiki/Algorithmus
I can remove the trailing newline if it bothers you – just tell me.

Fix typo in German translation: "Algorythmus"

---

src/app/pages/storage/components/pools-dashboard/pools-dashboard.component.ts

Handling case where missing disks for a specific pool make the topology card fail on the Storage page for pools.
Original PR: https://github.com/truenas/webui/pull/9396
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124814

NAS-124814 / 24.04 / Handling case for no disks for a specific pool (by RehanY147)

---

src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts
src/app/pages/data-protection/cloudsync/cloudsync-wizard/steps/cloudsync-what-and-when/cloudsync-what-and-when.component.ts

Testing:
See ticket, use m40 and go to `Cloudsync Task Wizard`
Try selecting folders, there should not be any limits to folder nesting and you should see full path once you selected folder.

NAS-126036 / 24.04 / Folder selector for cloud sync task works incorrectly

---

src/app/pages/system/CloudCredentials/cloudcredentials-form/cloudcredentials-form.component.ts

`cloudsync.onedrive_list_drives` was called for pCloud credential. I suppose, the component was previously used to perform a OneDrive authorization and OneDrive event listener did not remove itself due to an unhandled exception.

NAS-125131 / 13.1 / Always remove OAuth window event listener

---

src/app/modules/ix-forms/components/ix-explorer/ix-explorer.component.ts
src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts
src/app/pages/data-protection/replication/replication-form/replication-form.component.ts
src/app/pages/data-protection/replication/replication-wizard/steps/replication-what-and-where/replication-what-and-where.component.html
src/app/pages/data-protection/replication/replication-wizard/steps/replication-what-and-where/replication-what-and-where.component.ts

git cherry-pick -x e6501003c99f776a1fb547c6301f8986b4a269d1
git cherry-pick -x 418068c8cdd30c5540ec975d50a5f520f41e8ab8
git cherry-pick -x b3e02d759019e6ac7aa5f17d3d8f1948ae7eee08
git cherry-pick -x c4063896c0edd0542afc1d1a9a98cea57f288100
Testing: see ticket, you should be able to see `<ix-explorer>` values updated once trigger is called.
Test for any regressions.
Example:
`Cloud Sync Tasks` - Credential -> Folder (as well I reset folder value once Credential is changed)
see:
https://github.com/truenas/webui/assets/22980553/982fe4ee-205a-4aad-bdba-21685c5a5242
as well check how it …

NAS-126077 / 23.10.2 / The directories don't reset when credentials are changed on the Cloudsync Task Form (by AlexKarpov98)

---

.github/workflows/main.yml
src/assets/i18n/uk.json

For testing -- see this PR, which is based on this branch in order to test pipeline:
https://github.com/truenas/webui/pull/9433
You should see that if only translation files were updated - we skip some of the steps and run only `Resort Strings and Commit if only translations were added` Step.
As well you can go ahead and update some other non i18n file, to see that the pipeline will now skip `Resort Strings and Commit if only translations were added` Step and will only run previous steps we had.

NAS-126685 / 24.04 / NAS-126685: Do not do full build when only translation files were changed

---

src/app/pages/storage/modules/devices/components/zfs-info-card/zfs-info-card.component.ts

Adds EXTEND button for single-device LOG vdevs and removes misleading EXTEND on RAIDZ vdev member disks
isRaidzParent function updated (was checking the passed item itself, intention is to check if the parent item is RAIDZ type) - ref #7883 
canExtendDisk function updated to add match on VdevType.Log as a single-disk LOG should still be extended

NAS-126701 / UI errors on Manage Devices page - Add EXTEND for single-device LOG and remove EXTEND on RAIDZ vdev member disks

---

src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.html
src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.ts

For testing, ensure no `HA Enabled/HA Disabled` text appears while the sys-info widget is loading. Check the non-HA system (e.g., nightly) and check on the HA system (e.g., m40).

NAS-126711 / 24.04 / Fix HA enabled message when loading widget info

---

src/app/modules/ix-forms/components/ix-explorer/ix-explorer.component.ts
src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts

git cherry-pick -x 5cf73f50ddf02a4f1f451349fbfd382ab170be56
git cherry-pick -x 4218f7f6b08f3d9dc8011674cb605514163af4a1
git cherry-pick -x 0ff1e9cc59baa37bda1eda632f10fc27b4d8e6bb
As well I did a small refactoring to remove code duplication for CloudSync form.
Original PR: https://github.com/truenas/webui/pull/9428
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126723

NAS-126723 / 23.10.2 / ix-explorer bug with comma once I clear input and select something  (by AlexKarpov98)

---

src/app/pages/datasets/components/dataset-management/dataset-management.component.ts

**Testing**
On the **Datasets** page, prepare a top-level dataset with a sub-dataset. 
1. Expand top-level dataset
2. Select sub-dataset
3. Reload the page
- **Expected result:** expansion and selection is persisted

NAS-126744 / 24.04 / Dataset tree collapses after new dataset is created

---

src/app/pages/system/advanced/access/access-card/access-card.component.spec.ts
src/app/pages/system/advanced/access/access-card/access-card.component.ts
src/app/pages/system/advanced/access/access-form/access-form.component.ts

Testing: 
Go to `Advanced Settings -> Access` card
http://localhost:4200/system/advanced
Try to update `Token Lifetime`
Make sure that it works if seconds in total are greater then 24 hours:
Example:

NAS-126753 / 24.04 / Wrong seconds calculation in WebUI Sessions Settings Widget

---

src/app/pages/apps/components/installed-apps/installed-apps.component.ts

git cherry-pick -x a598f74e956de96b74ea31e0252f1d54798eb049
git cherry-pick -x 7ca70f0a8f562a0ab0386487b622a2868b5311b3
git cherry-pick -x d79921ea43f12a0f4c0ded1ac825af85f0a459fa
Testing: see ticket, try start / stop apps and keep sorted by Status.
Result (sorted realtime):
https://github.com/truenas/webui/assets/22980553/58fc01f2-758b-463a-aa3f-51fb12dd8549
Original PR: https://github.com/truenas/webui/pull/9449
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125762

NAS-125762 / 24.04 / Installed apps sorting unsorts itself (by AlexKarpov98)

---

src/app/pages/system/advanced/sessions/sessions-card/sessions-card.component.ts

git cherry-pick -x ce87d453d1361adc2c1da9b90d8c2f1113a01622
git cherry-pick -x 149716f614590c90831ab628b1a056691656427a
Testing: 
Go to `Advanced Settings -> Access` card
http://localhost:4200/system/advanced
Try to update `Token Lifetime`
Make sure that it works if seconds in total are greater then 24 hours:
Example:
Original PR: https://github.com/truenas/webui/pull/9459
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126753

NAS-126753 / 23.10.2 / Wrong seconds calculation in WebUI Sessions Settings Widget (by AlexKarpov98)

---

src/app/pages/reports-dashboard/reports-dashboard.component.ts
src/app/pages/reports-dashboard/reports.service.ts

Testing: 
go to Disk Reporting
http://localhost:4200/reportsdashboard/disk
See that Disks are sorted in alphabetical order in the `Select` and In `Cards`
Example:

NAS-125547 / 24.04 / The Disks Are Displayed In A Random Order On The Disk I/O Reporting Page

---

.github/workflows/main.yml
package.json
src/assets/i18n/ar.json
yarn.lock

Testing:
Create new temporary PR based on this branch (like I did here https://github.com/truenas/webui/pull/9488) and make sure that if translation files were changed together with any other files, we should NOT skip build, test and other workflow steps.
If only translation files were changed - then we skip build, test and so on.

NAS-126909 / 24.10 / Bug in the Workflows - If I created PR with translation files and with other files - it skips required steps

---

src/app/modules/test-id/test-override/test-override.directive.ts
src/app/modules/test-id/test/test.directive.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/layout-step/automated-disk-selection/automated-disk-selection.component.html
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/layout-step/automated-disk-selection/automated-disk-selection.component.spec.ts

Testing: 
See ticket, go to http://localhost:4200/storage/create
And see that data-test for `Layout` is now as expected, example:
**data-test="option-layout-RAIDZ1"**
So the Idea here is to append original data-test last part value to overwritten data-test attribute value.
Because for select->option - we can't get option.value from the parent component and append it dynamically via `ixTestOverride`
But with this update, we can override it:
before: **option-RAIDZ1**
with ixTestOverride: **option-layout**
with ixTestOverride && keepLastPart: **option-layout-RAIDZ1**

NAS-126826 / 24.10 / On the latest Dragonfish nightly build Pool Wizard all mat-option data-test  are missing the option text.

---

src/app/modules/test-id/test-override/test-override.directive.ts
src/app/modules/test-id/test/test.directive.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/layout-step/automated-disk-selection/automated-disk-selection.component.html
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/layout-step/automated-disk-selection/automated-disk-selection.component.spec.ts

Testing: 
See ticket, go to http://localhost:4200/storage/create
And see that data-test for `Layout` is now as expected, example:
**data-test="option-layout-RAIDZ1"**
So the Idea here is to append original data-test last part value to overwritten data-test attribute value.
Because for select->option - we can't get option.value from the parent component and append it dynamically via `ixTestOverride`
But with this update, we can override it:
before: **option-RAIDZ1**
with ixTestOverride: **option-layout**
with ixTestOverride && keepLastPart: **option-layout-RAIDZ1**
Original PR: https://github.com/truenas/webui/pull/9509
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126826

NAS-126826 / 24.04-RC.1 / On the latest Dragonfish nightly build Pool Wizard all mat-option data-test  are missing the option text. (by AlexKarpov98)

---

src/app/views/sessions/signin/signin-form/signin-form.component.ts

**Summary**
Until login request request is finished, I've disabled sign-in form
**Testing**
On **Login** page,
1. Enter login and password (try both correct and incorrect)
2. Press **Enter** key multiple times
3. After \~20 quick subsequent presses of **Enter** key, it displays
- **Expected result:** it should not be possible to submit a new attempt to login, until there's unfinished login request .
Original PR: https://github.com/truenas/webui/pull/9483
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126843

NAS-126843 / 24.04-RC.1 / Fix max concurrent calls bug (by bvasilenko)

---

src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.html
src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.ts

git cherry-pick -x 0c0dfe9760181bd1c16c063ea01db8ee36588d37
git cherry-pick -x 72e77b3766e65057d63ae407299a2336cb42b631
git cherry-pick -x d1d78872a292769512a313d7aa60e22924806772
git cherry-pick -x 12cfa7be90e9e9009a6daaca3a85560eb2a5e532
git cherry-pick -x 7ceac3b4f922dc216ba332358e97f714e743c05e
Testing:
you may need to mock **isIxHardware** to be **true** (see `loadIsIxHardware`)
Only in this case you will be able to see image.
Original PR: https://github.com/truenas/webui/pull/9538
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126992

NAS-126992 / 24.04-RC.1 / Mini-R image missing from dashboard widget (by AlexKarpov98)

---

src/app/pages/storage/volumes/volume-status/volume-status.component.ts

**Testing**
1. On a machine with Core, 
2. Go to **Storage -> Pools -> Pool status**
- Option A. have a pool of type Mirror (2 disks)
- Option B. mock `pool.query` and `disk.query` with the [ticket's JSON files](https://ixsystems.atlassian.net/browse/NAS-125844?focusedCommentId=236615) 
3. Choose **/dev/xxx > (Tri-Dot Menu) > Edit**  (see image below)
**Expected result:**  **Edit** action takes the user to **Edit form**, and console has no error
4. Try other actions 
- Offline
- Replace 
- Detach
- Remove
**Expected result:**  user is taken to the corresponding form.

NAS-125844 / 13.0 / Javascript error trying to edit disk in web UI

---

src/app/pages/sharing/smb/smb-acl/smb-acl.component.html
src/app/pages/sharing/smb/smb-acl/smb-acl.component.spec.ts
src/app/pages/sharing/smb/smb-acl/smb-acl.component.ts

Testing:
You should see  👇  for the `readonly` user:

NAS-127051 / 24.10 / Read only user : SMB Share > Edit Share ACL > Save button enabled

---

src/app/pages/sharing/smb/smb-acl/smb-acl.component.html
src/app/pages/sharing/smb/smb-acl/smb-acl.component.spec.ts
src/app/pages/sharing/smb/smb-acl/smb-acl.component.ts

git cherry-pick -x 43fe86e81aa08d6a9e3c080c510e59de1ed8719c
git cherry-pick -x 484c4ce285839aa53c2016a8a2fca25d11a11627
Testing:
You should see  👇  for the `readonly` user:
Original PR: https://github.com/truenas/webui/pull/9568
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127051

NAS-127051 / 24.04-RC.1 / Read only user : SMB Share > Edit Share ACL > Save button enabled (by AlexKarpov98)

---

src/app/modules/entity/entity-table/entity-table.component.scss
src/app/pages/credentials/backup-credentials/backup-credentials.component.scss
src/app/pages/data-protection/data-protection-dashboard.component.scss
src/app/pages/directory-service/directory-services.component.scss
src/app/pages/network/components/network-configuration-card/network-configuration-card.component.scss
src/app/pages/sharing/components/shares-dashboard/iscsi-card/iscsi-card.component.html
src/app/pages/sharing/components/shares-dashboard/nfs-card/nfs-card.component.html
src/app/pages/sharing/components/shares-dashboard/service-state-button/service-state-button.component.scss
src/app/pages/sharing/components/shares-dashboard/smb-card/smb-card.component.html
src/assets/styles/other/_material-reduction.scss
src/assets/styles/other/_root-variables.scss

Testing:
See Shares page on smaller screens and test other cards with toolbar headers.
As well some colouring fixes were made, I switched theme and detected them.
**Result:**
**Before, it was like 👇 :**

NAS-126983 / 24.10 / Share Page: iSCSI Service Status Label and Configure button UI overlap in different browser window sizes

---

src/app/app.module.ts
src/app/modules/ix-forms/components/ix-slide-in/components/ix-modal-header/ix-modal-header.component.ts
src/app/modules/ix-forms/components/ix-slide-in/components/ix-slide-in2/ix-slide-in2.component.ts
src/app/services/focus.service.ts
src/app/services/ix-chained-slide-in.service.ts
src/app/services/ix-slide-in.service.ts

Result: Focus is restored once slide in is closed.
https://github.com/truenas/webui/assets/22980553/06a44b5b-e046-4383-90ee-e7cffe41cbe6

NAS-126976 / 24.10 / Slide In When Closed Is Not Setting Focus On The Button Which Triggered Slide In To Open

---

src/app/modules/entity/entity-table/entity-table.component.scss
src/app/pages/credentials/backup-credentials/backup-credentials.component.scss
src/app/pages/data-protection/data-protection-dashboard.component.scss
src/app/pages/directory-service/directory-services.component.scss
src/app/pages/network/components/network-configuration-card/network-configuration-card.component.scss
src/app/pages/sharing/components/shares-dashboard/iscsi-card/iscsi-card.component.html
src/app/pages/sharing/components/shares-dashboard/nfs-card/nfs-card.component.html
src/app/pages/sharing/components/shares-dashboard/service-state-button/service-state-button.component.scss
src/app/pages/sharing/components/shares-dashboard/smb-card/smb-card.component.html
src/assets/styles/other/_material-reduction.scss
src/assets/styles/other/_root-variables.scss

Testing:
See Shares page on smaller screens and test other cards with toolbar headers.
As well some colouring fixes were made, I switched theme and detected them.
**Result:**
**Before, it was like 👇 :**
Original PR: https://github.com/truenas/webui/pull/9557
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126983

NAS-126983 / 24.04-RC.1 / Share Page: iSCSI Service Status Label and Configure button UI overlap in different browser window sizes (by AlexKarpov98)

---

src/app/app.module.ts
src/app/modules/ix-forms/components/ix-slide-in/components/ix-modal-header/ix-modal-header.component.ts
src/app/modules/ix-forms/components/ix-slide-in/components/ix-slide-in2/ix-slide-in2.component.ts
src/app/services/focus.service.ts
src/app/services/ix-chained-slide-in.service.ts
src/app/services/ix-slide-in.service.ts

Result: Focus is restored once slide in is closed.
https://github.com/truenas/webui/assets/22980553/06a44b5b-e046-4383-90ee-e7cffe41cbe6
Original PR: https://github.com/truenas/webui/pull/9576
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126976

NAS-126976 / 24.04-RC.1 / Slide In When Closed Is Not Setting Focus On The Button Which Triggered Slide In To Open (by AlexKarpov98)

---

src/app/pages/directory-service/components/idmap-form/idmap-form.component.ts
src/app/pages/directory-service/components/idmap-list/idmap-list.component.ts
src/app/pages/directory-service/components/kerberos-settings/kerberos-settings.component.ts
src/app/pages/directory-service/directory-services.component.ts
src/app/pages/sharing/smb/smb-list/smb-list.component.ts
src/app/services/focus.service.ts
src/app/services/ix-slide-in.service.ts

Testing:
I noticed that focus is lost if we update form and return to the table (html element is rerendered and it's reference is lost, I got an Idea to depend on data-test attribute, since it's unchanging)
As well did some fixes for Directory Services.

NAS-126976 / 24.10 / Focus service updates to correctly handle table reloading and loosing html ref & other improvements

---

src/app/modules/ix-table2/classes/async-data-provider/async-data-provider.ts

git cherry-pick -x 608a2815a88dfa7670b0415f6f6290299baedfcf
git cherry-pick -x 65d3398f33a5923479bfb4d13c4824cb10298523
Testing: 
See ticket
Result:
https://github.com/truenas/webui/assets/22980553/363a1f5a-4639-414e-bd4a-ff569adb86e2
Original PR: https://github.com/truenas/webui/pull/9598
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127170

NAS-127170 / 24.04-RC.1 / ix-table2 jumps when something is updated because of data hiding and spinner (by AlexKarpov98)

---

src/app/modules/ix-forms/components/ix-slide-in/components/ix-chained-slide-in/ix-chained-slide-in.component.ts
src/app/modules/ix-forms/components/ix-slide-in/components/ix-slide-in2/ix-slide-in2.component.ts

To test, go to the `Data Protection` dashboard and click the `Add` button for `Cloud Sync Tasks`. Leave the form open and let the web session expire so UI goes to the sign in page automatically. Once that happens, you should be able to interact with the sign in page and continue using the UI. On `master` that was not possible.

NAS-127201 / 24.10 / Removing element when component gets destroyed

---

src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.html
src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.scss
src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.ts

**Testing**
For testing machine - see ticket
**Expected result:** Enclosure page to identify sanity as the degraded pool with triangle "!"  icon in the legend on the right side

NAS-127062 / 24.04-RC.1 / Dragonfish: Fix Enclosure pool/disk UI info incorrect when disk is pulled

---

src/app/pages/storage/modules/disks/components/disk-bulk-edit/disk-bulk-edit.component.html
src/app/pages/storage/modules/disks/components/disk-bulk-edit/disk-bulk-edit.component.spec.ts
src/app/pages/storage/modules/disks/components/disk-bulk-edit/disk-bulk-edit.component.ts

For testing
- Login as Readonly Administator
- Open Storage Dashboard
- Find the Manage Disks button on the screen
- Choose two disks at least to bulk actions appear
- Press the Edit Disks
- Check the Save button is disabled

NAS-127009 / 24.10 / Add role support for Bulk Edit Disks form

---

src/app/modules/ix-forms/components/ix-slide-in/components/ix-chained-slide-in/ix-chained-slide-in.component.ts
src/app/modules/ix-forms/components/ix-slide-in/components/ix-slide-in2/ix-slide-in2.component.ts

To test, go to the `Data Protection` dashboard and click the `Add` button for `Cloud Sync Tasks`. Leave the form open and let the web session expire so UI goes to the sign in page automatically. Once that happens, you should be able to interact with the sign in page and continue using the UI. On `master` that was not possible.
Original PR: https://github.com/truenas/webui/pull/9606
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127201

NAS-127201 / 24.04-RC.1 / Removing element when component gets destroyed (by RehanY147)

---

src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.html
src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.scss
src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.ts

**Testing**
For testing machine - see ticket
**Expected result:** Enclosure page to identify sanity as the degraded pool with triangle "!"  icon in the legend on the right side
Original PR: https://github.com/truenas/webui/pull/9580
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127062

NAS-127062 / 24.10 / Dragonfish: Fix Enclosure pool/disk UI info incorrect when disk is pulled (by bvasilenko)

---

src/app/modules/layout/components/topbar/power-menu/power-menu.component.html
src/app/modules/layout/components/topbar/power-menu/power-menu.component.spec.ts
src/app/modules/layout/components/topbar/power-menu/power-menu.component.ts

git cherry-pick -x a522835ac27a991b300a2587909cebc2db25c481
git cherry-pick -x 80fd084598d2df7620379aa7df7f2bc60cc55d58
git cherry-pick -x afaad5220b43c1c853c76e2727ed74895d0a9657
See ticket.
Original PR: https://github.com/truenas/webui/pull/9624
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127221

NAS-127221 / 24.04-RC.1 / Missing Reboot UI Option on non-root Admin (by undsoft)

---

src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.html
src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.scss
src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.ts

Tested on different systems.
M60 HA is enabled:
M40 HA is disabled:
non-HA nightly instance:
For testing, try to find edge cases where it can be broken.

NAS-127105 / 24.10 / Update SysInfo Widget

---

package.json
src/app/modules/ix-table2/components/ix-table-columns-selector/ix-table-columns-selector.component.html
src/app/modules/ix-table2/components/ix-table-columns-selector/ix-table-columns-selector.component.spec.ts
src/app/modules/ix-table2/components/ix-table-columns-selector/ix-table-columns-selector.component.ts

Testing: (see ticket & videos inside the ticket - for the bugs I've found)
See results 👇 
https://github.com/truenas/webui/assets/22980553/a8512a23-5d4c-4c5c-ad0d-88791e88517b

NAS-127110 / 24.10 / ix-table-columns-selector columns -> reset to default hides all columns/rows values & Select/Unselect all works with glitches

---

src/app/modules/ix-table2/components/ix-table-body/cells/ix-cell-relative-date/ix-cell-relative-date.component.ts
src/app/pages/data-protection/cloudsync/cloudsync-list/cloudsync-list.component.spec.ts
src/app/pages/data-protection/cloudsync/cloudsync-list/cloudsync-list.component.ts
src/app/pages/data-protection/cloudsync/cloudsync-task-card/cloudsync-task-card.component.spec.ts
src/app/pages/data-protection/cloudsync/cloudsync-task-card/cloudsync-task-card.component.ts
src/app/pages/data-protection/rsync-task/rsync-task-card/rsync-task-card.component.spec.ts
src/app/pages/data-protection/rsync-task/rsync-task-card/rsync-task-card.component.ts
src/app/pages/data-protection/rsync-task/rsync-task-list/rsync-task-list.component.spec.ts
src/app/pages/data-protection/rsync-task/rsync-task-list/rsync-task-list.component.ts
src/app/pages/data-protection/scrub-task/scrub-list/scrub-list.component.spec.ts
src/app/pages/data-protection/scrub-task/scrub-list/scrub-list.component.ts
src/app/pages/data-protection/scrub-task/scrub-task-card/scrub-task-card.component.spec.ts
src/app/pages/data-protection/scrub-task/scrub-task-card/scrub-task-card.component.ts
src/app/pages/data-protection/snapshot-task/snapshot-task-card/snapshot-task-card.component.spec.ts
src/app/pages/data-protection/snapshot-task/snapshot-task-card/snapshot-task-card.component.ts
src/app/pages/system/advanced/cron/cron-card/cron-card.component.ts
src/app/pages/system/advanced/cron/cron-list/cron-list.component.html
src/app/pages/system/advanced/cron/cron-list/cron-list.component.spec.ts
src/app/pages/system/advanced/cron/cron-list/cron-list.component.ts
src/assets/styles/other/_tn-styles.scss

git cherry-pick -x 3af9bc02657045d337aa2ab428ad6d5bd4eaa763
git cherry-pick -x d74faa30bac4e52ee135599ecfe5ada836bb3028
git cherry-pick -x 7f2fea9f77722c89c094198cf17f1bb24950657a
Main idea is to make SAME behaviour across `Enabled & Next Run` - to show `Disabled` for Next Run if task is NOT Enabled.
As well in this ticket I fixed some issues with LIST components in Data Protection & Cron, to show same value for table's column and expandable details.
More fixes on listing & expandable rows issue will be done here: https://ixsystems.atlassian.net/browse/NAS-127279 …

NAS-127273 / 24.04-RC.1 / Data Protection → Next Run shows value for disabled tasks miss-match between card and list (by AlexKarpov98)

---

tests/bdd/ha-bhyve02/test_NAS_T0962.py

This sleep is to let the system catch up. In a real-world scenario, a system does not get on a failover after a few seconds of setting AD.

TE-1399 Adding a 10 second before the trigger of Failover

---

src/app/core/components/copy-btn/copy-btn.component.ts

Problem was with the `copyViaDeprecatedExecCommand` - it always received plain text instead of desired value.
https://github.com/truenas/webui/assets/22980553/3c5bab73-fedf-4ebd-809d-1fa14c7bf64b

NAS-127177 / 24.10 / System Audit > Event Data, "Copy JSON" option is not in JSON format

---

src/app/directives/common/common-directives.module.ts
src/app/directives/common/requires-roles/requires-roles-wrapper.component.html
src/app/directives/common/requires-roles/requires-roles-wrapper.component.scss
src/app/directives/common/requires-roles/requires-roles-wrapper.component.ts
src/app/modules/ix-forms/components/ix-slide-in/components/ix-modal-header/ix-modal-header.component.html
src/app/modules/ix-forms/components/ix-slide-in/components/ix-modal-header/ix-modal-header.component.scss
src/app/modules/layout/components/topbar/power-menu/power-menu.component.html
src/app/pages/datasets/components/dataset-details-card/dataset-details-card.component.html
src/app/pages/datasets/modules/encryption/components/zfs-encryption-card/zfs-encryption-card.component.html
src/app/pages/datasets/modules/snapshots/snapshot-details-row/snapshot-details-row.component.html
src/app/pages/services/components/service-ftp/service-ftp.component.html
src/app/pages/services/components/service-ftp/service-ftp.component.scss
src/app/pages/services/components/service-nfs/service-nfs.component.html
src/app/pages/services/components/service-nfs/service-nfs.component.scss
src/app/pages/services/components/service-smart/service-smart.component.html
src/app/pages/services/components/service-smb/service-smb.component.html
src/app/pages/services/components/service-smb/service-smb.component.scss
src/app/pages/services/components/service-snmp/service-snmp.component.html
src/app/pages/services/components/service-snmp/service-snmp.component.scss
src/app/pages/services/components/service-ssh/service-ssh.component.html
src/app/pages/services/components/service-ups/service-ups.component.html
src/app/pages/services/services.component.html
src/app/pages/services/services.component.scss
src/app/pages/storage/components/dashboard-pool/zfs-health-card/zfs-health-card.component.scss
src/app/pages/storage/modules/devices/components/zfs-info-card/zfs-info-card.component.html
src/app/pages/system/update/update.component.scss

Strike-through on restricted elements was replaced with a lock icon as per feedback we received.
Testing: check if lock icon is not looking nice somewhere.
Original PR: https://github.com/truenas/webui/pull/9708
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127417

NAS-127417 / 24.10 / Lock icon for restricted elements (by undsoft)

---

src/app/modules/ix-forms/components/ix-slide-in/components/ix-chained-slide-in/ix-chained-slide-in.component.scss
src/app/modules/ix-forms/components/ix-slide-in/components/ix-slide-in2/ix-slide-in2.component.scss
src/app/modules/ix-forms/components/ix-slide-in/ix-slide-in.component.scss

For testing, check UI on screen width < 600px.
Example:

NAS-127435 / 24.10 / Fix layout width on mobile screens

---

src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.ts

**Summary**
Implemented as per request https://github.com/truenas/webui/pull/9630#pullrequestreview-1866069657 , which references https://ixsystems.atlassian.net/browse/NAS-127022?focusedCommentId=241103
**Testing**
Go to **Enclosure** page, when connected to the box specified in the ticket
Check visibility of **Identity Drive** button , it should not be visible on this box

NAS-127022 / 24.04-RC.1 / Fix `Identify Drive` visible for Dragonfish

---

src/app/interfaces/enclosure.interface.ts
src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.ts
src/app/pages/system/view-enclosure/stores/enclosure-store.service.ts

**Testing**
On **Enclosure** page, when connected to the box specified in the ticket,
The visibility of **Identify Drive** button should depend on the `has_slot_status` property of the response from **enclosure.query** endpoint. `false` - hidden, `true` - visible.

NAS-127022 / 24.10 / Fix `Identify Drive` visible

---

src/app/services/auth/auth.service.ts

An error dialog with `Cannot read properties of undefined (reading 'webui_access')` prompt when login successful but without privilege field:
The correct implementation should respond users with `User is lacking permissions to access WebUI.` when have no permissions or failed to authenticate:
1. I am not quite sure why the field `privilege` is `undefined` when the authentication process has been done. Did I missed something about environment configurations?
2. I have also checked the unit test spec files that located at `src/app/services/auth/auth.service.spec.ts`, and found that there are no current possibilities to add unit tests for such case since the `processLoginResult` method is private, how do you folks usually do with it when it comes to black box testing?

NAS-127276 / 24.10 / guard user.privilege access when processing login results to prevent undefined property read

---

src/app/pages/dashboard/components/dashboard-form/dashboard-form.component.ts
src/app/pages/dashboard/components/dashboard/dashboard.component.ts
src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.scss

Fixed visibility of the system info standby widget. It relies on the visibility of the active widget now. Also, this PR has a fix for icon regression on the standby widget when HA is disabled.

NAS-127503 / 24.10 / Fix Standby card cannot be hidden on main dashboard

---

src/app/enums/codename.enum.ts
src/app/interfaces/system-info.interface.ts
src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.html
src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.scss
src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.ts

git cherry-pick -x 0a518a8ea600e97a092dee05e49bc98ad7f42e5d
git cherry-pick -x c227346e7a3b3714fc2575f64b09740dfa0dfac9
git cherry-pick -x c15c57c8b62015ea2a0e77ad540c5fa09cd4233b
Changes
- Replace `TrueNAS-SCALE` with release codename (when available)
- Fix regression on standby widget when HA is disabled
- Added tooltip to see full version (no need to copy anymore)
Original PR: https://github.com/truenas/webui/pull/9736
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127515

NAS-127515 / 24.04-RC.1 / Add codename to system info widget (by denysbutenko)

---

README.md

Currently the `README.md` documentation stated `truenas/webui` depends on
- yarn >= 1.12
- Node.js >= 14
However, according to the actual building `Dockerfile`, `truenas/webui` uses `node@16`, `yarn@1.22`.
And with `yarn@1.12`, the command execution to `yarn install` will never success since the existing `.yarnrc` isn't compatible to `yarn@1.12` where it complains about
```
error An unexpected error occurred: "Invalid value type 1:16 in <path/to/yarnrc>"
```
This issue suggests updating the `README.md` to align the `node@16`, `yarn@1.22` with Dockerfile.

NAS-127275 / 24.10 / Update Development requirements section of README.md along with formatting

---

src/app/modules/oauth-button/components/oauth-button/oauth-button.component.ts
src/app/pages/system/general-settings/support/support-card/support-card.component.ts
src/app/services/error-handler.service.spec.ts
src/app/services/error-handler.service.ts

Previously, oauth subscriptions were incorrectly cleared, which lead to possible duplicate ticket submittions.
Also, filters out websocket close events from Sentry.
Testing:
1. Update `addTicket` in `FeedbackService` to not create actual tickets:
```
return of(ticket).pipe(
map(() => {
console.log('creating ticket');
return { } as NewTicketResponse;
}),
);
```
2. Open feedback form on an non-enterprise system and fill in a bug report.
3. Click Login To Jira.
4. Close the window.
5. Click Login to Jira again and submit the ticket.
You should only see one `create ticket` message in console.

NAS-127505 / 24.04-RC.1 / UI submitting duplicate issue reports

---

src/app/modules/oauth-button/components/oauth-button/oauth-button.component.ts
src/app/pages/system/general-settings/support/support-card/support-card.component.ts
src/app/services/error-handler.service.spec.ts
src/app/services/error-handler.service.ts

Previously, oauth subscriptions were incorrectly cleared, which lead to possible duplicate ticket submittions.
Also, filters out websocket close events from Sentry.
Testing:
1. Update `addTicket` in `FeedbackService` to not create actual tickets:
```
return of(ticket).pipe(
map(() => {
console.log('creating ticket');
return { } as NewTicketResponse;
}),
);
```
2. Open feedback form on an non-enterprise system and fill in a bug report.
3. Click Login To Jira.
4. Close the window.
5. Click Login to Jira again and submit the ticket.
You should only see one `create ticket` message in console.
Original PR: https://github.com/truenas/webui/pull/9737
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127505

NAS-127505 / 24.10 / UI submitting duplicate issue reports (by undsoft)

---

src/app/modules/ix-table2/classes/api-data-provider/api-data-provider.ts
src/app/pages/account/groups/privilege/privilege-list/privilege-list.component.ts
src/app/pages/audit/components/audit/audit.component.ts

Testing: 
See that load() is not called multiple times (upon initial load request)
inside of the `load(): void {` 
you can alert `alert(this.method);` to make sure it's only called once.
Before it was called twice because of the `setSorting` and `setPagination` logic.

NAS-127582 / 24.10 / Performing advanced query in webui audit form appears to submit query payload twice

---

src/app/modules/ix-table2/classes/api-data-provider/api-data-provider.ts
src/app/pages/account/groups/privilege/privilege-list/privilege-list.component.ts
src/app/pages/audit/components/audit/audit.component.ts

Testing: 
See that load() is not called multiple times (upon initial load request)
inside of the `load(): void {` 
you can alert `alert(this.method);` to make sure it's only called once.
Before it was called twice because of the `setSorting` and `setPagination` logic.
Original PR: https://github.com/truenas/webui/pull/9757
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127582

NAS-127582 / 24.04.0 / Performing advanced query in webui audit form appears to submit query payload twice (by AlexKarpov98)

---

src/app/helpers/operators/filter-async.operator.ts
src/app/modules/dialog/components/start-service-dialog/start-service-dialog.component.html
src/app/modules/dialog/components/start-service-dialog/start-service-dialog.component.ts
src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.ts
src/app/pages/services/services.component.html
src/app/pages/services/services.component.ts
src/app/pages/system/update/components/train-card/train-card.component.ts
src/app/services/services.service.ts
src/app/store/eula/eula.effects.ts
src/app/store/network-interfaces/network-interfaces.effects.ts
src/app/store/services/services.effects.spec.ts
src/app/store/services/services.effects.ts

git cherry-pick -x e5c4678c50fb2dc190585a7cbd1ca9234c61f1a1
git cherry-pick -x 6b9a941c59e5fa0848fee89e3916f09ab5d641cb
git cherry-pick -x 592ac0353211ea17ed0d42467a57fb10020fdb92
git cherry-pick -x cedfa1c09f7d0a559aac92d2d3ccc876b5c50495
git cherry-pick -x 40859e19b6a7e3074eea2b7cec44604bcc6f3827
Testing: see ticket. Start service dialog will no longer be shown is user won't be able to do anything in it.
Original PR: https://github.com/truenas/webui/pull/9793
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127719

NAS-127719 / 24.10 / Do not offer service dialogs if user does not have access (by undsoft)

---

src/app/modules/search-input/services/query-to-api/query-to-api.service.ts

column names are now case-insensitive (see ticket's comment)
`"event" != "Authentication"` will work same as `"Event" != "Authentication"` or `"EvEnT" = "Authentication"`
Testing:
Original PR: https://github.com/truenas/webui/pull/9809
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127787

NAS-127787 / 24.04.0 / Audit advanced search syntax not filtering query (by AlexKarpov98)

---

src/app/modules/layout/components/console-footer/console-messages.store.ts
src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.ts
src/app/services/auth/auth.service.ts
src/app/services/ws.service.spec.ts
src/app/services/ws.service.ts

The easiest way to test changes is to create a fresh nightly instance with API Tests in CI. While tests are running, multiple jobs and events are created. Then, log in and reduce session duration to lowest value (30 seconds). Navigate to different pages and check when session has ended.
Ensure websocket messages have no active subscriptions (except ping). 
Check if active websocket connection can be reused.
Test for any regressions.

NAS-127141 / 24.10 / Unsubscribe from API events subscriptions on logout

---

package.json
yarn.lock

Updated package can parse more timezones returned from middleware without causing errors.

NAS-126795 / 24.04.0 / Updated package to handle more timezones

---

src/app/modules/search-input/services/query-to-api/query-to-api.service.ts

column names are now case-insensitive (see ticket's comment)
`"event" != "Authentication"` will work same as `"Event" != "Authentication"` or `"EvEnT" = "Authentication"`
Testing:
Original PR: https://github.com/truenas/webui/pull/9809
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127787

NAS-127787 / 24.04-RC.1 / Audit advanced search syntax not filtering query (by AlexKarpov98)

---

src/app/pages/vm/vm-list/vm-list.component.ts

git cherry-pick -x 2dc8285440330eaccf52897de51a5f36d06f3225
git cherry-pick -x b3d4263a601d584e5c28efe5d2c6b3c2b84bce62
git cherry-pick -x 71afcf53edce248e9df1ad106fdf84f874068c65
git cherry-pick -x 5f3fc941f1e9b22007af4f92ec99f65c71b3f31a
git cherry-pick -x 8423bade9dec6b6c052a4315e70e3c775f5b0b1d
M40 is ready for testing this PR. Try to download logs on the VM page.
Original PR: https://github.com/truenas/webui/pull/9773
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127589

NAS-127589 / 24.04.0 / Use new download VM logs endpoint in WebUI (by denysbutenko)

---

src/app/services/storage.service.spec.ts
src/app/services/storage.service.ts

Mixed Vdev Capacities warning should only be shown if the difference is greater than 2 Gib and the percentage difference between the highest and lowest vdev capacities is more than 5%.

NAS-125411 / 24.10 / Added check for vdev capacties difference

---

src/app/pages/datasets/components/dataset-form/dataset-form.component.html
src/app/pages/datasets/components/dataset-form/dataset-form.component.ts
src/app/pages/datasets/components/dataset-form/sections/encryption-section/encryption-section.component.ts
src/app/pages/datasets/components/dataset-form/sections/name-and-options-section/name-and-options-section.component.spec.ts
src/app/pages/datasets/components/dataset-form/sections/name-and-options-section/name-and-options-section.component.ts
src/app/pages/datasets/components/dataset-form/sections/other-options-section/other-options-section.component.ts
src/app/pages/datasets/components/dataset-form/sections/quotas-section/quotas-section.component.ts
src/app/pages/sharing/smb/smb-form/smb-validator.service.ts

git cherry-pick -x c9e63b226d26df4b07cda50280006deffdbd4259
git cherry-pick -x 940727476b5c0c2eb5aff46bd27afffb30ca0434
git reset --hard HEAD~2
git cherry-pick -x 54b6031f4d84a863c679533c6b8cda45aae3be9f
Testing:
See ticket, try to create dataset.
You should not be able to submit with invalid name or empty name now.
Original PR: https://github.com/truenas/webui/pull/9808
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127720

NAS-127720 / 24.04.0 / Webui does not handle validation errors properly when creating SMB shares via "Add Dataset" (by AlexKarpov98)

---

src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.html
src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.spec.ts
src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.ts

git cherry-pick -x a09dc4aacef6cdfaa8a7b65319b18535277dc5ae
git cherry-pick -x 8fd97558c9e009039514fd0e0e858fa761e2341a
git cherry-pick -x bbcb24f8bfaafe573109463a4f616306006009fc
git cherry-pick -x f18081f276f254b4c72f31f4dba798ab677bcfea
git cherry-pick -x aadf819cbc43adf615a4cb22035c9a693e646874
Changes:
- Fixed condition for `Unsupported Hardware`
- Added listener for failover reconnect to update system info data.
- ~Cleaned up unused code.~
For testing, it is best to use the HA system from CI. Check the ticket for bug details.
Original PR: https://github.com/truenas/webui/pull/9819 …

NAS-127701 / 24.04.0 / Fix SysInfo widget on failover reconnect (by denysbutenko)

---

src/app/pages/storage/modules/devices/components/zfs-info-card/zfs-info-card.component.ts

Create a RaidZ pool with disks alocated for spare vdevs. You should be able to see the "Remove" button for the Spare disks.

NAS-127603 / 24.04.0 / Added remove button for Spares for RaidZ pool

---

src/app/pages/reports-dashboard/reports-dashboard.component.ts
src/app/pages/reports-dashboard/reports.service.ts

Sorting is now in alphabetical order:

NAS-127829 / 24.04.0 / Disks are displayed in a random order on the Disk I/O Reporting Page

---

src/app/pages/storage/modules/devices/components/devices/devices.component.html
src/app/pages/system/bootenv/bootenv-status/bootenv-status.component.html

To test, open the Devices and Boot Status pages. Ensure tree node takes full width.
Expected no left offset outside of tree node.
Actual:

NAS-127920 / 24.10 / Fix tree node padding on Devices & Boot Status pages

---

src/app/pages/storage/modules/devices/components/zfs-info-card/zfs-info-card.component.spec.ts
src/app/pages/storage/modules/devices/components/zfs-info-card/zfs-info-card.component.ts

Create a RaidZ pool with disks alocated for spare vdevs. You should be able to see the "Remove" button for the Spare disks.
Original PR: https://github.com/truenas/webui/pull/9854
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127603

NAS-127603 / 24.10 / Added remove button for Spares for RaidZ pool (by RehanY147)

---

src/app/modules/feedback/services/feedback.service.spec.ts
src/app/modules/feedback/services/feedback.service.ts

Solution: I increased timing so now user will be able to click the link successfully. (10 sec now)
Original PR: https://github.com/truenas/webui/pull/9873
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127844

NAS-127844 / 24.10 / HA Support ticket: Open Ticket windows closes before I can click the button (by AlexKarpov98)

---

src/app/pages/storage/modules/disks/components/disk-list/disk-list.component.ts

Only exists on dragonfish, I assume it was somehow accidentally backported to dragonfish. 
(on Dragonfish table details row - we show true/false for all of the tables instead of Yes/No as on Electric Eel)

NAS-127798 / 24.04.0 / Unable to save "Enable S.M.A.R.T." settings in Storage > Edit Disk page

---

src/app/helptext/system/advanced.ts
src/app/pages/storage/volumes/volume-status/volume-status.component.ts
src/app/pages/system/advanced/advanced.component.ts

**Testing**
Connect to 13.0 machine
On the **System > Advanced** page, in the **Syslog** block
1. In the **Syslog Transport** dropdown choose **TLS**
2.  Select a certificate
3. Click **Save**
1. There should be a "Certificate Authority" dropdown field
2. This dropdown field should be filled with selectable options from **System > CAs**.

NAS-127717 / 13.0 / Add `syslog_tls_certificate_authority` field

---

src/app/interfaces/api/api-event-directory.interface.ts
src/app/views/sessions/signin/store/signin.store.spec.ts
src/app/views/sessions/signin/store/signin.store.ts

git cherry-pick -x f8c0e082e617701ed25044e393e9cac8cfb50f55
git cherry-pick -x a44d5578afea2f2dc8d61b4a664e8fa260e44339
For testing, ensure the `username` and `password` fields appear after failover is completed. Use m40 and try to initiate failover.
Examples of how it was and what to expect:
Original PR: https://github.com/truenas/webui/pull/9882
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127423

NAS-127423 / 24.04.0 / Fix login prompt after failover processed (by denysbutenko)

---

src/app/interfaces/advanced-config.interface.ts

**Summary**
The middleware team have just updated the API endpoints, as described below
> Removed ability to update isolated GPU config from system.advanced.update
>
> Additionally, a separate endpoint system.advanced.update_gpu_pci_ids already exists to configure and validate isolated GPUs.
**Testing**
No functional changes, code review should be enough.
_Explanation:_ All existing calls to `system.advanced.update` in the project do not attempt to change the `isolated_gpu_pci_ids` field

NAS-127882 / 24.10 / Fix GPU endpoint usage

---

src/app/modules/entity/entity-empty/entity-empty.component.scss
src/app/pages/datasets/components/dataset-management/dataset-management.component.html
src/app/pages/datasets/components/dataset-management/dataset-management.component.ts
src/app/pages/storage/components/pools-dashboard/pools-dashboard.component.html

NAS-128052 / 24.04.0 / Dragonfish Empty Datasets & Empty Pools - `Create Pool` button is not disabled for Readonly User

---

src/app/pages/datasets/components/dataset-management/dataset-management.component.ts

Testing: see ticket. When we do some update - opened datasets shall not collapse.
Result: 
https://github.com/truenas/webui/assets/22980553/e927c232-510e-491d-9a7d-d465bfa28e39

NAS-127966 / 24.10 / Doing actions colapses the Dataset Tree

---

src/app/pages/datasets/components/dataset-management/dataset-management.component.ts

Testing: see ticket. When we do some update - opened datasets shall not collapse.
Result: 
https://github.com/truenas/webui/assets/22980553/e927c232-510e-491d-9a7d-d465bfa28e39
Original PR: https://github.com/truenas/webui/pull/9893
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127966

NAS-127966 / 24.04.0 / Doing actions colapses the Dataset Tree (by AlexKarpov98)

---

src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.spec.ts
src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts

**Testing**
On **Data Protection** page, at **Cloud Sync Tasks** block
User views existing task, then makes a change, save, and then open again
User should be able to edit source and save changes

NAS-128046 / 24.10 / Fix `include` field

---

src/assets/styles/other/_material-reduction.scss
src/assets/styles/other/_tn-styles.scss

While adding some German translations (#9899) I noticed that the labels on all the buttons in the WebUI have the first letter of every single word capitalized due to the use of the CSS filter `text-transform: capitalize`. 
This isn't really grammatically correct, and having every single word on a button capitalized looks weird, in my opinion. At least in German, maybe it's different in english. I'm not sure why the capitalization is even there in the first place (in the CSS) when it might as well be solved by capitalizing these words in the translation files. 
Looking at the english translation file, nearly every button label is already included in the translation file with all words capitalized
With this PR, the CSS for the buttons is changed to remove that auto-capitalization. For the …

Don't force-capitalize every word on button labels

---

src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.spec.ts
src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts

**Testing**
On **Data Protection** page, at **Cloud Sync Tasks** block
User views existing task, then makes a change, save, and then open again
User should be able to edit source and save changes
Original PR: https://github.com/truenas/webui/pull/9895
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128046

NAS-128046 / 24.04.0 / Fix `include` field (by bvasilenko)

---

src/app/pages/datasets/modules/snapshots/snapshot-rollback-dialog/snapshot-rollback-dialog.component.html

NAS-127948 / 24.10 / Dragonfish: Restore Snapshot dialog rendering not consistent with other dialogs

---

src/app/pages/datasets/modules/snapshots/snapshot-rollback-dialog/snapshot-rollback-dialog.component.html

Testing: see result 👇 
Original PR: https://github.com/truenas/webui/pull/9909
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127948

NAS-127948 / 24.04.0 / Dragonfish: Restore Snapshot dialog rendering not consistent with other dialogs (by AlexKarpov98)

---

src/app/pages/datasets/modules/snapshots/snapshot-list/snapshot-list.component.html

Go to /ui/datasets/snapshots
**Expected result:** user can see the page without any errors, especially with no `Maximum number of concurrent calls (20) has exceeded.` error, which was mentioned in the ticket

NAS-128054 / 24.10 / Add `detailsRowIdentifier` for the snapshot list

---

src/app/helptext/storage/disks/disks.ts
src/app/helptext/system/advanced.ts
src/app/helptext/system/kmip.ts

There is no concrete way to stop password manager extensions like Bitwarden from forcefully filling in a field that has any mention of a "password". Setting autocomplete off or other solutions from scale don't work. On scale this problem doesn't exist because we handle forms completely differently from core (slide-ins instead of full-page forms).

NAS-126760 / 13.3 / Replace 'SED Password' with 'SED Key'

---

src/app/pages/storage/modules/pool-manager/components/pool-manager/tests/create-pool.spec.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager/tests/draid-pool-creation.spec.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager/tests/unsetting-on-fewer-disks.spec.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager/tests/wizard-reset-step.spec.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager/tests/wizard-start-over.spec.ts
src/app/pages/storage/modules/pool-manager/store/pool-manager.store.spec.ts
src/app/pages/storage/modules/pool-manager/store/pool-manager.store.ts

**Testing**
Use the machine from the ticket, or setup mocks from the data provided in the attachments of this ticket.
On the **Storage > Create Pool** page,
When user fills **Name** and clicks **Next**
- **Expected result:** it should not display **Enclosure Options** , and this step should never appear at pool creation wizard

NAS-127893 / 24.10 / Fix `hasMultipleEnclosuresAfterFirstStep$` selector

---

src/app/pages/storage/modules/pool-manager/components/pool-manager/tests/create-pool.spec.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager/tests/draid-pool-creation.spec.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager/tests/unsetting-on-fewer-disks.spec.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager/tests/wizard-reset-step.spec.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager/tests/wizard-start-over.spec.ts
src/app/pages/storage/modules/pool-manager/store/pool-manager.store.spec.ts
src/app/pages/storage/modules/pool-manager/store/pool-manager.store.ts

**Testing**
Use the machine from the ticket, or setup mocks from the data provided in the attachments of this ticket.
On the **Storage > Create Pool** page,
When user fills **Name** and clicks **Next**
- **Expected result:** it should not display **Enclosure Options** , and this step should never appear at pool creation wizard
Original PR: https://github.com/truenas/webui/pull/9952
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127893

NAS-127893 / 24.04.1 / Fix `hasMultipleEnclosuresAfterFirstStep$` selector (by bvasilenko)

---

src/app/helpers/file-size.utils.spec.ts
src/app/helpers/file-size.utils.ts

git cherry-pick -x 926c5a833a7a6af03393308786294e55465c32a2
git reset --hard HEAD~2
git cherry-pick -x ec59c4bc8c088a5713aa2ee9b9f6936d1cb0abda
**Testing**
Setup mocks to emulate total pool capacity > 999TiB
At Create Pool wizard, At the review stage of the wizard,
Display correct units of measurement (PiB) for **Est. Usable Raw Capacity** field at **Topology Summary** block
Original PR: https://github.com/truenas/webui/pull/9969
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128344

NAS-128344 / 24.04.1 / Calculation for estimated storage capacity is incorrect in pool manager and dashboard when capacity is > 999TiB (by bvasilenko)

---

src/app/modules/ix-dynamic-form/components/ix-dynamic-wizard/ix-dynamic-wizard.component.html
src/app/modules/ix-dynamic-form/components/ix-dynamic-wizard/ix-dynamic-wizard.component.scss
src/assets/styles/other/_material-reduction.scss

Currently we cannot write multi-line section-help for the App install/edit GUI.
As those get removed, leading to one big blob of text.
This fix, ensures that multiline descriptions get respected accordingly.
Fixes the following issue:
To render as:
Thanks for your attention!

Ensure multiline App "Section help" can be rendered

---

src/app/modules/ix-dynamic-form/components/ix-dynamic-wizard/ix-dynamic-wizard.component.html
src/app/modules/ix-dynamic-form/components/ix-dynamic-wizard/ix-dynamic-wizard.component.scss
src/assets/styles/other/_material-reduction.scss

Currently we cannot write multi-line section-help for the App install/edit GUI.
As those get removed, leading to one big blob of text.
This fix, ensures that multiline descriptions get respected accordingly.
Fixes the following issue:
To render as:
Thanks for your attention!
Original PR: https://github.com/truenas/webui/pull/9987
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128452

NAS-128452 / 24.04.1 / Ensure multiline App "Section help" can be rendered (by StevenMcElligott)

---

src/app/pages/dashboard/widgets/common/widget-datapoint/widget-datapoint.component.scss
src/app/pages/dashboard/widgets/common/widget-datapoint/widget-datapoint.component.ts

Testing: see ticket & result 👇 
Before:
After:

NAS-128481 / 24.10 / Datapoint widget quarters incorrectly renders widget size

---

scripts/ui/ui.ts

Now, this command should work.
`yarn ui remote -i "[2400:adc7:125:4800:a00:27ff:fef2:c326]" -f`
This flag removes preprocessing with the assumption that the ip address is ipv4.

NAS-126973 / 24.10 / Add force flag to `ui.ts` 

---

src/app/modules/global-search/components/global-search/global-search.component.spec.ts
src/app/modules/global-search/components/global-search/global-search.component.ts
src/app/modules/global-search/services/global-search-sections.service.spec.ts
src/app/modules/global-search/services/global-search-sections.service.ts

Testing: see ticket, try to update local storage`recentSearches`, add unexisting search result. (update hierarchy item)
You should only see items which are available in `ui-searchable-elements.json`.

NAS-128625 / 24.10 / Recent searches in global search shows unusual results

---

src/app/pages/dashboard/services/dashboard.store.ts
src/app/pages/dashboard/types/widget.interface.ts
src/app/services/auth/auth.service.ts

Testing: see ticket & result 👇 
https://github.com/truenas/webui/assets/22980553/320be838-d39c-40f3-af45-f1e7d6543fab

NAS-128688 / 24.10 / Dashboard state is reverted once I saved, switched page and returned

---

src/app/pages/dashboard/services/dashboard.store.spec.ts
src/app/pages/dashboard/services/dashboard.store.ts

For testing
- create a fresh VM
- check dashboard using builtin webui - expected: `Dashboard is Empty!`
- check dashboard using this branch - expected: demo widgets are loaded

NAS-128761 / 24.10 / Use demoWidgets as initial state for new dashboard

---

src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.ts

Testing: just review the code.

NAS-128660 / 24.04.1 / ES24n should not have identify buttons for drives

---

src/app/modules/feedback/components/feedback-dialog/feedback-dialog.component.spec.ts
src/app/modules/feedback/components/feedback-dialog/feedback-dialog.component.ts

You can see that Suggestion option is no longer there in Feedback dialog on non-enterprise systems.
Original PR: https://github.com/truenas/webui/pull/10053
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128881

NAS-128881 / 24.04.2 / Removes suggestions from feedback form (by undsoft)

---

src/app/modules/feedback/components/feedback-dialog/feedback-dialog.component.spec.ts
src/app/modules/feedback/components/feedback-dialog/feedback-dialog.component.ts

You can see that Suggestion option is no longer there in Feedback dialog on non-enterprise systems.
Original PR: https://github.com/truenas/webui/pull/10053
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128881

NAS-128881 / 24.10 / Removes suggestions from feedback form (by undsoft)

---

src/app/store/ha-info/ha-info.selectors.ts

Original issue can be reproduced by adding a delay to network code in `loadHaStatus` in `HaInfoEffects`.

NAS-129063 / 24.04.1 / Initiate Failover button is inactive but HA is up

---

src/app/store/ha-info/ha-info.selectors.ts

Original issue can be reproduced by adding a delay to network code in `loadHaStatus` in `HaInfoEffects`.
Original PR: https://github.com/truenas/webui/pull/10081
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129063

NAS-129063 / 24.04.2 / Initiate Failover button is inactive but HA is up (by undsoft)

---

src/app/store/ha-info/ha-info.selectors.ts

Original issue can be reproduced by adding a delay to network code in `loadHaStatus` in `HaInfoEffects`.
Original PR: https://github.com/truenas/webui/pull/10081
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129063

NAS-129063 / 24.10 / Initiate Failover button is inactive but HA is up (by undsoft)

---

src/app/modules/global-search/components/global-search-trigger/global-search-trigger.component.spec.ts
src/app/modules/global-search/components/global-search-trigger/global-search-trigger.component.ts
src/app/modules/global-search/components/global-search/global-search.component.ts

Closes search when escape is pressed instead of just removing the value.

NAS-129183 / 24.10 / Close search on escape

---

src/app/core/classes/system-profiler.ts

I'll attach in the ticket the patch to mock request.
Looks like original issue happened because condition changed it's meaning over time.

NAS-128468 / 13.3 / Enclosure reports all disks as not attached to any pool

---

debian/fetch_node.sh

This commit adds a simple script to download the specified pre-built nodejs binary. The intention for this script is to be called from within scale-build while chrooted during the package build and so hammering the into /usr/bin and /usr/lib is okay, but probably shouldn't be done on developer systems.

NAS-129253 / 24.10 / Add script to fetch prebuilt nodejs

---

src/app/helptext/topbar.ts

I've reworded the verbiage for `FailoverDisabledReason.MismatchNics` to match what was decided on in the [middleware PR](https://github.com/truenas/middleware/pull/13820)

NAS-129397 / 24.10 / Reworded MismatchNics

---

src/app/modules/global-search/components/global-search-results/global-search-results.component.scss
src/app/modules/global-search/components/global-search-trigger/global-search-trigger.component.ts
src/app/modules/global-search/components/global-search/global-search.component.ts
src/app/services/focus.service.ts

Testing: see ticket, now we are focusing on the first element in the sidenav content, it's needed to not loose focus.
As well search element in global search is fixed to focus from first to second if search input is focused (previously we had to double tab to move to second element)

NAS-129438 / 24.10 / White Box surrounds iXsystems Logo in UI after Clicking enter in the Search UI

---

src/app/modules/global-search/components/global-search/global-search.component.ts

It's a missing fix, when I worked on the https://github.com/truenas/webui/pull/10169.

NAS-129580 / 24.10 / Global Search Tab + Arrow navigation fix when input is focused

---

src/app/pages/sharing/iscsi/target/target-form/target-form.component.html
src/app/pages/sharing/iscsi/target/target-form/target-form.component.ts
src/app/pages/sharing/smb/smb-form/smb-form.component.html
src/app/pages/sharing/smb/smb-form/smb-form.component.ts

Try to edit some field on a iSCSI Target except name, it should not block 
Original PR: https://github.com/truenas/webui/pull/10205
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129391

NAS-129391 / 24.10 / Can't edit iSCSI Target on SCALE (by AlexKarpov98)

---

src/app/core/testing/mock-enclosure/enclosure-templates/utils/disk.utils.ts
src/app/core/testing/mock-enclosure/enclosure-templates/utils/pool.utils.ts
src/app/core/testing/mock-enclosure/enclosure-templates/utils/slots.utils.ts

Update your env config, 
or run `yarn ui mock-enclosure` and configure it to have `FillSomeSlots` and with `expansionModels`
Result:
Right now it correctly occupies slots.
https://github.com/truenas/webui/assets/22980553/b27005a8-f1aa-4a6c-ab0b-edca905af1c0

NAS-129644 / 24.10 / Fix MockStorageScenario.FillSomeSlots for multiple enclosures

---

src/app/helpers/operators/accumulate-loading-state.helper.ts
src/app/pages/sharing/components/shares-dashboard/smb-card/smb-card.component.ts

Restored as a backport. 
Original PR: https://github.com/truenas/webui/pull/10218
**Testing**
**Steps to Reproduce**
1. Navigate to Shares page
2. toggle share 'enabled' slider to 'disabled'
3. At this share click 'pencil' icon
**Expected Result**
right panel displays and 'enabled' checkbox is disabled

NAS-129198 / 24.04.2 / Share "enabled" checkbox on edit right panel not matched share page

---

src/assets/styles/other/_fn-styles.scss

NAS-128364 / 24.10 / Truncated translation on Backup Credentials panel

---

src/app/enums/nfs-acl.enum.ts
src/app/interfaces/smb-share.interface.ts
src/app/modules/ix-forms/classes/smb-both-combobox-provider.ts
src/app/pages/sharing/smb/smb-acl/smb-acl.component.html
src/app/pages/sharing/smb/smb-acl/smb-acl.component.spec.ts
src/app/pages/sharing/smb/smb-acl/smb-acl.component.ts

git cherry-pick -x 594ce987a9f58c7fd0927bbe79a47c39048961fd
git cherry-pick -x df35b0190c725640c742c5fd4bbd6f3029e4cdce
git cherry-pick -x b8609ae68bc07c83acd1468f3b80c8e7d8d644f9
git reset --hard HEAD~3
git cherry-pick -x 324fa0f9a287f5d9d742e132d275ec5061a58177
**Summary**
1. when AD cache is empty (see ticket), when **Group** combobox does not contain any suitable values to choose from,
I've changed to code to add the ability to type in a custom value from keyboard . When user presses **Save**, every value is validated for being a valid existing entry in the Active Directory 
2. Middleware returns special type of AD entry `BOTH` , …

NAS-129686 / 24.04.2 / Fix SMB ACL form (by bvasilenko)

---

src/app/modules/forms/ix-forms/components/ix-slide-in/components/ix-chained-slide-in/ix-chained-slide-in.component.html

**Changes:**
Using old `*ngFor` instead of `@for` - maybe we need to wait a bit for Angular Team updates and try it later again, pretty weird issue though.
**Testing:**
See ticket

NAS-130076 / 24.10 / EE - Replication advanced option button returns to Data Protection page

---

src/app/pages/system/general-settings/support/proactive/proactive.component.spec.ts
src/app/pages/system/general-settings/support/proactive/proactive.component.ts

Testing: see ticket. Now once you open the form - you should not see errors if you didn't touch anything.

NAS-130123 / 24.10 / Proactive Support Fixes

---

src/app/pages/sharing/components/shares-dashboard/smb-card/smb-card.component.spec.ts
src/app/pages/sharing/components/shares-dashboard/smb-card/smb-card.component.ts
src/app/pages/sharing/smb/smb-list/smb-list.component.spec.ts
src/app/pages/sharing/smb/smb-list/smb-list.component.ts
src/app/pages/sharing/utils/smb.utils.spec.ts
src/app/pages/sharing/utils/smb.utils.ts
src/app/services/dataset-service/dataset.service.ts

**Changes:**
Add Audit Logging column to SMB tables.
**Testing:**
See new column.
|Documentation   | New column added to SMB tables.

NAS-127581 / 24.10 / Add indicator in SMB that auditing is enabled

---

src/app/pages/dashboard/widgets/network/widget-interface-ip/widget-interface-ip.component.spec.ts
src/app/pages/dashboard/widgets/network/widget-interface-ip/widget-interface-ip.component.ts

**Changes:**
Look at aliases in the network interface state. Updated tests. Added case for IPv6.
**Testing:**
Check the ticket

NAS-130130 / 24.10 / Fix IPv4 card does not display IP

---

src/assets/styles/other/_material-reduction.scss

**Changes:**
Styling changes
**Testing:**
See ticket, see result:
https://github.com/user-attachments/assets/ba8f44bf-e0a8-40e6-90d6-9805af365866

NAS-128558 / 24.10 / Context menu for user/power options are showing in the wrong place

---

src/app/modules/scheduler/components/scheduler-modal/scheduler-modal.component.spec.ts
src/app/modules/scheduler/components/scheduler-modal/scheduler-modal.component.ts
src/app/modules/scheduler/components/scheduler/scheduler.component.spec.ts
src/app/modules/scheduler/utils/get-default-crontab-presets.utils.ts
src/app/pages/data-protection/cloud-backup/cloud-backup-form/cloud-backup-form.component.spec.ts

**Changes:**
In scheduler modal, when selecting Custom, Preset dropdown in the modal will now react to changes in other fields.
**Testing:**
Detailed instructions are in the ticket.

NAS-129950 / 24.10 / Preset in scheduler does not update with the rest of the form

---

src/app/pages/system/enclosure/components/enclosure-side/enclosure-svg/enclosure-svg.component.scss
src/app/pages/system/enclosure/components/enclosure-side/enclosure-svg/enclosure-svg.component.ts

**Changes:**
Added a new class to the `overlay-rect` that adds the same highlight styles as the selected slot but with a white border color to all other disks in the same vdev as the currently selected slot.
**Testing:**
Mock some enclosures and test by selecting different slots. Other slots that are also part of the same vdev should also get the highlight styles but with a white border.

NAS-130050 / 24.10 / Adds higlight styles for vdev disks

---

src/app/pages/dashboard/services/dashboard.store.ts

**Changes:**
Minor type fix.
**Testing:**
Code review only.
To test that it actually works:
go to `src/app/pages/dashboard/services/dashboard.store.ts`
line 76: `groups: this.getDashboardGroups(dashState || demoWidgets),`
replace it with a config from dragonfish
```          
groups: this.getDashboardGroups([
{
name: 'System Information',
rendered: true,
id: '0',
},
{
id: '1',
name: 'System Information(Standby)',
identifier: 'passive,true',
rendered: true,
},
{
id: '8',
name: 'Pool',
identifier: 'name,Pool:dozer',
rendered: false,
},
{
id: '9',
name: 'Interface',
identifier: 'name,ens1',
rendered: true,
},
] as any)
```
Go ahead and see that it actually renders the widget.

NAS-130073 / 24.10 / Fix `"IPv4 Address"` widget upon migration

---

src/app/pages/reports-dashboard/components/line-chart/line-chart.component.ts

**Testing:**
1. Run a network transfer with rate ~1Gb/s
_Alternatively, make a temporary adjustment of the reporting dashboard code, so that all the metrics are multiplied by 100*1024_
2. Go to **Reports** page,
3. Choose **Network** from the dropdown at the right top corner,
**Expected result:** vertical axis of network bandwidth charts display the following values in Gb/s
```
1
0.5
0
```

NAS-128526 / 24.10 / Fix network axis labels

---

src/app/modules/global-search/components/global-search-trigger/global-search-trigger.component.ts
src/app/modules/global-search/components/global-search/global-search.component.html
src/app/modules/global-search/components/global-search/global-search.component.ts
src/app/services/focus.service.ts

**Changes:** 
Now when voice over is **ON** and we focus out from the search results to some other focusable element - `Global Search Results` panel is closed.
As well `Global Search Section` is no longer trapped and we can focus out from the search results once we tabbed fully.
**Testing:** 
See ticket & result 👇 :
https://github.com/user-attachments/assets/5dc81267-3036-41be-b524-e290a28135a4

NAS-130305 / 24.10 / Check global search with voice over

---

src/app/pages/system/enclosure/components/enclosure-side/enclosure-side.component.spec.ts
src/app/pages/system/enclosure/components/enclosure-side/enclosure-side.component.ts

**Changes:**
Reverts changes in https://github.com/truenas/webui/pull/10386 because they break functionality in https://ixsystems.atlassian.net/browse/NAS-129928.
**Testing:**
Testing can be done by adding a fake model via `yarn ui mock-enclosure`.

NAS-130451 / 24.10 / Fix missing enclosures support

---

src/app/helptext/sharing/nfs/nfs.ts
src/app/helptext/sharing/smb/smb.ts
src/app/modules/ix-table/components/ix-table-pager-show-more/ix-table-pager-show-more.component.html
src/app/modules/ix-table/components/ix-table-pager-show-more/ix-table-pager-show-more.component.scss
src/app/modules/ix-table/components/ix-table-pager-show-more/ix-table-pager-show-more.component.spec.ts
src/app/modules/ix-table/components/ix-table-pager-show-more/ix-table-pager-show-more.component.ts
src/app/modules/ix-table/interfaces/table-sort.interface.ts
src/app/pages/sharing/components/shares-dashboard/iscsi-card/iscsi-card.component.html
src/app/pages/sharing/components/shares-dashboard/iscsi-card/iscsi-card.component.scss
src/app/pages/sharing/components/shares-dashboard/iscsi-card/iscsi-card.component.ts
src/app/pages/sharing/components/shares-dashboard/nfs-card/nfs-card.component.html
src/app/pages/sharing/components/shares-dashboard/nfs-card/nfs-card.component.scss
src/app/pages/sharing/components/shares-dashboard/nfs-card/nfs-card.component.ts
src/app/pages/sharing/components/shares-dashboard/smb-card/smb-card.component.html
src/app/pages/sharing/components/shares-dashboard/smb-card/smb-card.component.scss
src/app/pages/sharing/components/shares-dashboard/smb-card/smb-card.component.ts
src/app/pages/sharing/iscsi/target/target-list/target-list.component.ts
src/app/pages/sharing/nfs/nfs-list/nfs-list.component.ts
src/app/pages/sharing/smb/smb-list/smb-list.component.ts

**Changes:**
1. Fix sort on `SMB`, `NFS` and `iSCSI` cards
2. Sync behavior between mentioned cards
3. Use `ix-table-pager-show-more` component for `View All` button
4. Update `ix-table-pager-show-more` to use signals
5. Add router support in `ix-table-pager-show-more`
6. Minor cleanup
**Testing:**
Go to the Sharing dashboard. Create 5 or more shares for each card.
|Documentation   | Minor UI changes for `View All` button

NAS-130259 / 24.10 / Ensure alphabetical order of shares on Shares dashboard

---

src/app/interfaces/api/api-job-directory.interface.ts
src/app/interfaces/app.interface.ts
src/app/pages/apps/components/app-wizard/app-wizard.component.ts
src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.html
src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.spec.ts
src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.ts
src/app/pages/apps/components/installed-apps/app-rollback-modal/app-rollback-modal.component.ts

**Changes:**
Fixes proper button hidden/unhidden status for update and rollback buttons. Fixes rollback operation.
**Testing:**
Test by adding `test` train to catalog and install `nginx` version `1.0.5`. Then update to latest version and rollback to version `1.0.5`. You should be able to do this without refreshing the page or navigating away.

NAS-130503 / 24.10 / Fix rollback and upgrade, as well updates for relevant buttons

---

src/app/pages/dashboard/services/widget-resources.service.ts

**Changes:**
The main dashboard still works when `update.check_available` has failed
**Testing:**
Create a fresh VM and try to open main dashboard, ensure it works

NAS-130419 / 25.04 / Fix dashboard crashing when update.check failed

---

src/app/pages/dashboard/services/widget-resources.service.ts

**Changes:**
The main dashboard still works when `update.check_available` has failed
**Testing:**
Create a fresh VM and try to open main dashboard, ensure it works
Original PR: https://github.com/truenas/webui/pull/10456
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130419

NAS-130419 / 24.10-RC.1 / Fix dashboard crashing when update.check failed (by denysbutenko)

---

src/app/modules/layout/components/topbar/topbar.component.html

**Changes:**
Icon visual change.
**Testing:**
|Documentation   | Icon visual change.

NAS-130049 / 25.04 / Consider removing blue plus overlay from feedback icon.

---

src/app/modules/layout/components/topbar/topbar.component.html

**Changes:**
Icon visual change.
**Testing:**
|Documentation   | Icon visual change.
Original PR: https://github.com/truenas/webui/pull/10459
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130049

NAS-130049 / 24.10-RC.1 / Consider removing blue plus overlay from feedback icon. (by AlexKarpov98)

---

src/app/pages/dashboard/widgets/system/widget-sys-info-active/widget-sys-info-active.component.spec.ts
src/app/pages/dashboard/widgets/system/widget-sys-info-active/widget-sys-info-active.component.ts
src/app/pages/dashboard/widgets/system/widget-sys-info-passive/widget-sys-info-passive.component.spec.ts
src/app/pages/dashboard/widgets/system/widget-sys-info-passive/widget-sys-info-passive.component.ts
src/app/pages/dashboard/widgets/system/widget-system-uptime/widget-system-uptime.component.spec.ts
src/app/pages/dashboard/widgets/system/widget-system-uptime/widget-system-uptime.component.ts
src/app/pages/reports-dashboard/components/report/report.component.ts
src/app/services/locale.service.spec.ts
src/app/services/locale.service.ts

**Changes:**
Added locale service tests & added new method to correctly convert string date to Date() object.
**Testing:**
See ticket.
Try affected files. (As well fixed dashboard widgets)
**new Date() Bug logic:**
It's because the Date constructor in JavaScript expects the date string to be in a format that it can parse correctly. The format DD/MM/YYYY HH:MM:SS is not natively supported by the Date constructor, leading to an “Invalid Date” error.

NAS-130254 / 25.04 / Setting UK/GB date results in error in Reporting graphs

---

src/app/pages/dashboard/widgets/system/widget-sys-info-active/widget-sys-info-active.component.spec.ts
src/app/pages/dashboard/widgets/system/widget-sys-info-active/widget-sys-info-active.component.ts
src/app/pages/dashboard/widgets/system/widget-sys-info-passive/widget-sys-info-passive.component.spec.ts
src/app/pages/dashboard/widgets/system/widget-sys-info-passive/widget-sys-info-passive.component.ts
src/app/pages/dashboard/widgets/system/widget-system-uptime/widget-system-uptime.component.spec.ts
src/app/pages/dashboard/widgets/system/widget-system-uptime/widget-system-uptime.component.ts
src/app/pages/reports-dashboard/components/report/report.component.ts
src/app/services/locale.service.spec.ts
src/app/services/locale.service.ts

**Changes:**
Added locale service tests & added new method to correctly convert string date to Date() object.
**Testing:**
See ticket.
Try affected files. (As well fixed dashboard widgets)
**new Date() Bug logic:**
It's because the Date constructor in JavaScript expects the date string to be in a format that it can parse correctly. The format DD/MM/YYYY HH:MM:SS is not natively supported by the Date constructor, leading to an “Invalid Date” error.
Original PR: https://github.com/truenas/webui/pull/10465
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130254

NAS-130254 / 24.10-RC.1 / Setting UK/GB date results in error in Reporting graphs (by AlexKarpov98)

---

src/app/pages/apps/components/app-card-logo/app-card-logo.component.html
src/app/pages/apps/components/app-card-logo/app-card-logo.component.spec.ts
src/app/pages/apps/components/app-card-logo/app-card-logo.component.ts
src/app/pages/apps/components/available-apps/available-apps.component.spec.ts

**Changes:**
Adds a custom observable to lazy-image-load process. Solves the problem where scrolling of the container element wasn't triggered so image wasn't loading.
**Testing:**
Go to apps page, discover apps and search for different apps. The image icon should load properly and should show without any scrolling or clicking on the page automatically.

NAS-130636 / 25.04 / Fix lazy image loading

---

src/app/pages/apps/components/app-card-logo/app-card-logo.component.html
src/app/pages/apps/components/app-card-logo/app-card-logo.component.spec.ts
src/app/pages/apps/components/app-card-logo/app-card-logo.component.ts
src/app/pages/apps/components/available-apps/available-apps.component.spec.ts

**Changes:**
Adds a custom observable to lazy-image-load process. Solves the problem where scrolling of the container element wasn't triggered so image wasn't loading.
**Testing:**
Go to apps page, discover apps and search for different apps. The image icon should load properly and should show without any scrolling or clicking on the page automatically.
Original PR: https://github.com/truenas/webui/pull/10487
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130636

NAS-130636 / 24.10-RC.1 / Fix lazy image loading (by RehanY147)

---

src/app/pages/sharing/iscsi/target/target-form/target-form.component.spec.ts
src/app/pages/sharing/iscsi/target/target-form/target-form.component.ts

git cherry-pick -x a9c3d6b4fdbe99c9edd3f9337f95d6bf84f5c6e8
git cherry-pick -x 45c1c8e73f7a20f60e2018da4fa5b368ba8af6c1
Testing: see ticket. We used different identifiers - that's the issue.
Original PR: https://github.com/truenas/webui/pull/10512
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130656

NAS-130656 / 24.10-RC.1 / Portal group IDs on iSCSI target are shown as incorrect (by AlexKarpov98)

---

src/app/modules/global-search/components/global-search-results/global-search-results.component.scss
src/app/modules/ix-table/components/ix-table/ix-table.component.scss
src/app/modules/layout/components/topbar/user-menu/user-menu.component.scss
src/app/pages/apps/components/available-apps/app-card/app-card.component.scss
src/app/pages/dashboard/components/dashboard/dashboard.component.scss
src/app/pages/dashboard/components/widget-group-form/widget-group-slot-form/widget-group-slot-form.component.scss
src/app/pages/dashboard/components/widget-group-form/widget-group-slot-form/widget-group-slot-form.component.ts
src/app/pages/dashboard/widgets/apps/widget-app-settings/widget-app-settings.component.scss
src/app/pages/dashboard/widgets/backup/widget-backup/backup-task-empty/backup-task-empty.component.scss
src/app/pages/dashboard/widgets/common/widget-datapoint/widget-datapoint.component.scss
src/app/pages/dashboard/widgets/custom/arbitrary-text/widget-arbitrary-text-settings/widget-arbitrary-text-settings.component.scss
src/app/pages/dashboard/widgets/help/widget-help/widget-help.component.scss
src/app/pages/dashboard/widgets/memory/widget-memory/widget-memory.component.scss
src/app/pages/dashboard/widgets/network/widget-interface-ip/widget-interface-ip-settings/widget-interface-ip-settings.component.scss
src/app/pages/dashboard/widgets/network/widget-interface/widget-interface.component.html
src/app/pages/dashboard/widgets/network/widget-interface/widget-interface.component.scss
src/app/pages/dashboard/widgets/storage/widget-pool-disks-with-zfs-errors/widget-pool-disks-with-zfs-errors.component.scss
src/app/pages/dashboard/widgets/storage/widget-pool-last-scan-errors/widget-pool-last-scan-errors.component.scss
src/app/pages/dashboard/widgets/storage/widget-pool-status/widget-pool-status.component.scss
src/app/pages/dashboard/widgets/storage/widget-pool-usage-gauge/widget-pool-usage-gauge.component.scss
src/app/pages/dashboard/widgets/storage/widget-pool/common/pool-stats.scss
src/app/pages/dashboard/widgets/storage/widget-pool/common/pool-usage-gauge/pool-usage-gauge.component.html
src/app/pages/dashboard/widgets/storage/widget-pool/common/pool-usage-gauge/pool-usage-gauge.component.scss
src/app/pages/dashboard/widgets/storage/widget-pool/common/pool-usage-gauge/pool-usage-gauge.component.spec.ts
src/app/pages/dashboard/widgets/storage/widget-pool/widget-pool-settings/widget-pool-settings.component.scss
src/app/pages/dashboard/widgets/storage/widget-pool/widget-pool.component.scss
src/app/pages/dashboard/widgets/storage/widget-storage/widget-storage.component.html
src/app/pages/dashboard/widgets/storage/widget-storage/widget-storage.component.scss
src/app/pages/dashboard/widgets/system/common/widget-sys-info.scss
src/assets/styles/other/_material-reduction.scss

git cherry-pick -x 238af6c20307ac8079939a6c43a26110fd4864a2
git cherry-pick -x 550f74cd18a7f3e78bae812a20de7cfca0009d9e
git cherry-pick -x 7060a2d2a0781110c8b5daa5d1473f0d30d1f59b
git cherry-pick -x 63041fdcef046d4ca1ee755e19abe176388ddde7
git cherry-pick -x 7c8ce1b9001f80222025349ecdcce52479bea119
git cherry-pick -x ede88ac073dac1408193ed757b3156e79e767a6a
git cherry-pick -x 16098573d7aee3a41f8290bac9678d1783da359c
git cherry-pick -x bc17d740a3676a71c0ec9d9d4d8f85c6c3a262dd
git cherry-pick -x b0d75a1e208fe99a2728ebe97eb984dd181305db
**Changes:**
Adjustments for widgets (mobile view) …

NAS-130607 / 24.10-RC.1 / Mobile adjustments for dashboard widgets (by AlexKarpov98)

---

src/app/modules/forms/ix-forms/components/ix-select/ix-select.component.html

**Changes:**
Fixes translation issue.
**Testing:**
Check translation issue as described in the ticket.

NAS-130692 / 24.10-RC.1 / Some text is not translated in Pool creation

---

src/app/pages/dashboard/widgets/storage/interfaces/pool-info.interface.ts
src/app/pages/dashboard/widgets/storage/widget-storage/widget-storage.component.ts

git cherry-pick -x 8f813fbfb7f21bf7f679ae2f56b075a81e2561d8
git cherry-pick -x 4b31f8e63e29dbfcb71ab5e444b7e1de92f633e9
**Changes:**
Update icon and color when `Last Resilver` is `Never`
**Testing:**
Check the Storage widget
Original PR: https://github.com/truenas/webui/pull/10515
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130665

NAS-130665 / 24.10-RC.1 / Update Last Resilver Never as neutral (by denysbutenko)

---

src/app/modules/ix-tree/components/tree-virtual-scroll-view/tree-virtual-scroll-view.component.ts

**Changes:**
Instead of recreating the instance to disconnect from event listener on component destroy event, use the same instance that is used to register the callback method.
**Testing:**
Have some datasets setup on a pool. Navigate quickly between different pages and come back to the datasets dashboard and try scrolling. If you do it quickly, you can see lots of instances of the same error on the console. This fix resolves that issue.

NAS-130759 / 25.04 / Use same instance on destroy and on init for `tree-vritual-scroll-view`

---

src/app/modules/ix-tree/components/tree-virtual-scroll-view/tree-virtual-scroll-view.component.ts

**Changes:**
Instead of recreating the instance to disconnect from event listener on component destroy event, use the same instance that is used to register the callback method.
**Testing:**
Have some datasets setup on a pool. Navigate quickly between different pages and come back to the datasets dashboard and try scrolling. If you do it quickly, you can see lots of instances of the same error on the console. This fix resolves that issue.
Original PR: https://github.com/truenas/webui/pull/10532
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130759

NAS-130759 / 24.10-RC.1 / Use same instance on destroy and on init for `tree-vritual-scroll-view` (by RehanY147)

---

src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/layout-step/automated-disk-selection/draid-selection/draid-selection.component.spec.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/layout-step/automated-disk-selection/draid-selection/draid-selection.component.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager/tests/draid-pool-creation.spec.ts

**Changes:**
Previously in the code the comparison operator was not strict and was including the value `p+d+s`. But as per the ticket requirements, the comparison operator is now strict
**Testing:**
Please see ticket for replication steps and expected results

NAS-130678 / 25.04 / Fix dRAID logic for number of children when creating a pool

---

src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts

Add Glacier Instant Retrieval storage class for AWS S3 Cloud Sync
**Changes:**
Adds `Glacier Instant Retrieval` to the storage class option for AWS S3 Cloud Sync task.  `GLACIER_IR` was added to Rclone in v1.58.0: https://rclone.org/changelog/#v1-58-0-2022-03-18
**Testing:**
https://ixsystems.atlassian.net/browse/NAS-130168
|Documentation   | None found
|midddleware | Added to middleware in truenas/middleware#14094

NAS-130168 / 24.10 / NAS-130168

---

src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/layout-step/automated-disk-selection/draid-selection/draid-selection.component.spec.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/layout-step/automated-disk-selection/draid-selection/draid-selection.component.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager/tests/draid-pool-creation.spec.ts

**Changes:**
Previously in the code the comparison operator was not strict and was including the value `p+d+s`. But as per the ticket requirements, the comparison operator is now strict
**Testing:**
Please see ticket for replication steps and expected results
Original PR: https://github.com/truenas/webui/pull/10510
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130678

NAS-130678 / 24.10-RC.1 / Fix dRAID logic for number of children when creating a pool (by bvasilenko)

---

src/app/directives/disable-focusable-elements/disable-focusable-elements.directive.ts

git cherry-pick -x 546ad08f16bd266d4d038e605398fc6535fc01ff
git cherry-pick -x a5e774f51df90ab8470516d508664f3c5388510e
**Changes:**
Fix `Initiate Failover` button on main dashboard (and other buttons too).
**Testing:**
On HA system. Disable Failover. Open main dashboard-ensure the `Initiate Failover` button is disabled. Click `Configure` button to edit mode. Save changes. Ensure `Initiate Failover` button still disabled.
Original PR: https://github.com/truenas/webui/pull/10523
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129013

NAS-129013 / 24.10-RC.1 / Skip disabled buttons for changes by directive (by denysbutenko)

---

src/app/interfaces/api/api-call-directory.interface.ts
src/app/pages/api-keys/components/api-key-list/api-key-list.component.spec.ts
src/app/pages/api-keys/components/api-key-list/api-key-list.component.ts

API Keys - can be removed now.

NAS-130838 / 25.04 / API Keys deletion is not working

---

src/app/interfaces/api/api-call-directory.interface.ts
src/app/pages/api-keys/components/api-key-list/api-key-list.component.spec.ts
src/app/pages/api-keys/components/api-key-list/api-key-list.component.ts

API Keys - can be removed now.
Original PR: https://github.com/truenas/webui/pull/10573
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130838

NAS-130838 / 24.10-RC.1 / API Keys deletion is not working (by AlexKarpov98)

---

src/app/pages/sharing/components/shares-dashboard/smb-card/smb-card.component.spec.ts
src/app/pages/sharing/components/shares-dashboard/smb-card/smb-card.component.ts
src/app/pages/sharing/smb/smb-list/smb-list.component.spec.ts
src/app/pages/sharing/smb/smb-list/smb-list.component.ts

Result 👇 
Original PR: https://github.com/truenas/webui/pull/10582
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130830

NAS-130830 / 24.10-RC.1 / Audit Logging status on SMB share tables is always Yes (by AlexKarpov98)

---

src/app/modules/global-search/components/global-search/global-search.component.ts
src/app/modules/global-search/helpers/extract-version.spec.ts
src/app/modules/global-search/helpers/extract-version.ts
src/app/modules/global-search/services/global-search-sections.service.spec.ts
src/app/modules/global-search/services/global-search-sections.service.ts

git cherry-pick -x dc595392f0c139178d6f177b78225f7f845c3883
git cherry-pick -x 27bd75f2ba4f8d7a1a5ef1333d36f4eebf03949d
git cherry-pick -x 2bd2ed0ed0dcc25da9e7ee48bb7ae45fbe24f0c2
git cherry-pick -x f6a5d1978948cc7808239b1c8b4fb695f7256e51
git cherry-pick -x 27b50c0dd793c550ae61b1d4bc47b9130b72caf2
git cherry-pick -x 974607f856a7a4af249f38b68f7265549c955728
**Testing:** see ticket.
If no version found - we redirect user to global docs, not version specific.
Original PR: https://github.com/truenas/webui/pull/10533
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130719

NAS-130719 / 24.10-RC.1 / UI Global Search passes "undefined" url path to Docs Hub (by AlexKarpov98)

---

src/app/pages/dashboard/widgets/network/widget-interface/widget-interface.component.ts

**Testing:**
On the **Dashboard** page,
When User adds 2 stacked small widgets, one of them is **Network \> Interface**
**Expected result:** no empty `[]` at the chart's legend, see ticket

NAS-130994 / 25.04 / Fix interface name in the widget

---

src/app/pages/dashboard/widgets/network/widget-interface/widget-interface.component.ts

**Testing:**
On the **Dashboard** page,
When User adds 2 stacked small widgets, one of them is **Network \> Interface**
**Expected result:** no empty `[]` at the chart's legend, see ticket
Original PR: https://github.com/truenas/webui/pull/10625
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130994

NAS-130994 / 24.10-RC.1 / Fix interface name in the widget (by bvasilenko)

---

src/app/pages/datasets/components/dataset-form/sections/other-options-section/other-options-section.component.spec.ts
src/app/pages/datasets/components/dataset-form/sections/other-options-section/other-options-section.component.ts
src/assets/styles/mixins/cards.scss

Testing: 
If ACL Mode is somehow incorrectly set, in edit mode - user should be able to see it and be able change it, or update ACL Type and then we should see revalidation. 
Shortly, validation is turned off in edit mode if user has incorrect ACL Mode related to ACL Type.
Example:
`Posix -> passthrough`  is incorrect 
`Posix -> Discard` is correct
So if we entered edit mode and user has incorrect setup - he should be able to change it.
If user opened form with correct setup, like `Posix -> Discard` - Discard option shall remain disabled.
Result:
https://github.com/user-attachments/assets/3f3ee674-9f27-4a0a-a7e1-7b148ead9405

NAS-130859 / 25.04 / UI provides incorrect information about dataset ACL mode and does not provide a mechanism to fix it when incorrect

---

src/app/pages/storage/modules/pool-manager/components/pool-manager/tests/create-pool.spec.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager/tests/step-changing.spec.ts
src/app/pages/storage/modules/pool-manager/store/pool-manager.store.spec.ts
src/app/pages/storage/modules/pool-manager/store/pool-manager.store.ts
src/app/pages/storage/modules/pool-manager/utils/generate-vdevs/generate-vdevs-maximize-dispersal.spec.ts
src/app/pages/storage/modules/pool-manager/utils/generate-vdevs/generate-vdevs-normal.spec.ts
src/app/pages/storage/modules/pool-manager/utils/generate-vdevs/generate-vdevs-treat-as-minimum.spec.ts
src/app/pages/storage/modules/pool-manager/utils/generate-vdevs/generate-vdevs.service.ts
src/app/pages/storage/modules/pool-manager/utils/generate-vdevs/test-utils.ts

Summary:
The problem was that the `findSuitableDisks` method was returning more suitable disks for the checked `treatDiskSizeAsMinimum` than there actually were. This occurs because `removeUsedDisks` for **Metadata** was called later than `findSuitableDisks` for **Dedup**, and the disks occupied by **Metadata** were available for selection.
Testing:
For replication steps, please follow the video attached to the ticket
Original PR: https://github.com/truenas/webui/pull/10559
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130645

NAS-130645 / 24.10-RC.1 / Exclude used disks from automated disk selection (by bvasilenko)

---

src/app/interfaces/api/api-call-and-subscribe-directory.interface.ts
src/app/pages/apps/components/app-detail-view/app-resources-card/app-resources-card.component.spec.ts
src/app/pages/apps/components/app-detail-view/app-resources-card/app-resources-card.component.ts
src/app/pages/apps/services/applications.service.ts
src/app/pages/apps/store/installed-apps-store.service.spec.ts
src/app/pages/apps/store/installed-apps-store.service.ts

git cherry-pick -x 6baf69935d7e569dbf892d08fb1a517214e9baf2
git cherry-pick -x 7145acbbbefc03723e093066570849702054fd6c
git cherry-pick -x 9baf8724b722800ec335972cdf38485f0ef2fb51
git cherry-pick -x 2a9b772f16dfe6ceac393e0c7efe5234e08bab78
git cherry-pick -x 4c128b3338cd8cc06ce264de3230da396f520a08
git reset --hard HEAD~2
git cherry-pick -x 4598a0c26ee95531e5cf055e2afaae6e9b8bc99c
**Changes:**
- Reduce usage `app.query` endpoint
- Use `app.available_space` for retrieving available space in ix-apps dataset 
**Testing:**
See ticket for details
Original PR: https://github.com/truenas/webui/pull/10569
Jira URL: …

NAS-130767 / 24.10-RC.1 / Optimize app.query calls (by denysbutenko)

---

src/app/pages/dashboard/widgets/system/widget-sys-info-active/widget-sys-info-active.component.html
src/app/pages/dashboard/widgets/system/widget-sys-info-active/widget-sys-info-active.component.spec.ts
src/app/pages/dashboard/widgets/system/widget-sys-info-active/widget-sys-info-active.component.ts
src/app/pages/dashboard/widgets/system/widget-sys-info-passive/widget-sys-info-passive.component.html
src/app/pages/dashboard/widgets/system/widget-sys-info-passive/widget-sys-info-passive.component.spec.ts
src/app/pages/dashboard/widgets/system/widget-sys-info-passive/widget-sys-info-passive.component.ts
src/app/pages/dashboard/widgets/system/widget-system-uptime/widget-system-uptime.component.html
src/app/pages/dashboard/widgets/system/widget-system-uptime/widget-system-uptime.component.spec.ts
src/app/pages/dashboard/widgets/system/widget-system-uptime/widget-system-uptime.component.ts

Testing: 
Go to dashboard, switch tab or open another app. 
Wait 2-3 minutes, return to the WEB UI tab and check that time is not ahead.
_As well - I tried `visibilitychange` listener and `requestAnimationFrame` - but no luck._

NAS-131016 / 25.04 / Uptime on Dashboard runs too fast

---

src/app/pages/dashboard/components/dashboard/dashboard.component.spec.ts
src/app/pages/dashboard/components/dashboard/dashboard.component.ts
src/app/pages/dashboard/services/dashboard.store.spec.ts
src/app/pages/dashboard/services/dashboard.store.ts
src/app/pages/dashboard/services/get-default-widgets.spec.ts
src/app/pages/dashboard/services/get-default-widgets.ts

git cherry-pick -x 7d6616a8d9afaf3e86a8330a75978ba9819364f6
git cherry-pick -x 827e60c86bac207acfaf4f7e803c9523196035db
git cherry-pick -x 4efc5ea9d1d72a1beffffee2196a36d0088d9120
**Changes:**
Updated logic of default widgets generation.
**Testing:**
See ticket, try with HA system & on non HA system as well.
Original PR: https://github.com/truenas/webui/pull/10640
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130980

NAS-130980 / 24.10-RC.1 / ElectricEel HA Dashboard is missing the Standby System Information card. (by AlexKarpov98)

---

src/app/interfaces/cloud-backup.interface.ts
src/app/pages/data-protection/cloud-backup/cloud-backup-details/cloud-backup-restore-form-snapshot-form/cloud-backup-restore-from-snapshot-form.component.html
src/app/pages/data-protection/cloud-backup/cloud-backup-details/cloud-backup-restore-form-snapshot-form/cloud-backup-restore-from-snapshot-form.component.spec.ts
src/app/pages/data-protection/cloud-backup/cloud-backup-details/cloud-backup-restore-form-snapshot-form/cloud-backup-restore-from-snapshot-form.component.ts

git cherry-pick -x 230ad4d68c98b933680f4f92b894eaa0b6a46ec8
git cherry-pick -x 362aa54513240399c0cbc2e303bebb0e5ab8d199
git cherry-pick -x f270c0b192923a03a045212062b4ce6269f2ff13
git cherry-pick -x 6cc233ecb64a89eaa46e34f1719fd48cbc0f956a
git cherry-pick -x fd6c5a5cfcd5c5503e8e3fad0954bd99dc440b4e
git cherry-pick -x ca586bacd30b2aa377f641dd40163480ef00c9e3
git cherry-pick -x b44bf5bab0683a8076170d105674585185c4528f
git cherry-pick -x ce7678279bb2136a4da87d4437ee1c40ef1e64a0
git cherry-pick -x 25da2b42caf62ae14295c0ca5fc368fabcaec821
**Changes:**
Fix Cloud Backup Restore Include From …

NAS-130794 / 24.10-RC.1 / Fix Cloud Backup Restore Include From Subfolder (by denysbutenko)

---

src/app/pages/apps/apps.module.ts
src/app/pages/apps/components/app-detail-view/app-detail-view.component.html
src/app/pages/apps/components/app-detail-view/app-detail-view.component.spec.ts
src/app/pages/apps/components/app-detail-view/app-json-details-card/app-json-details-card.component.html
src/app/pages/apps/components/app-detail-view/app-json-details-card/app-json-details-card.component.scss
src/app/pages/apps/components/app-detail-view/app-json-details-card/app-json-details-card.component.spec.ts
src/app/pages/apps/components/app-detail-view/app-json-details-card/app-json-details-card.component.ts
src/assets/styles/other/_fn-styles.scss

**Changes:**
Added 2 new cards to the App Details page.
Created a generic component which will render JSON data we need.
**Testing:**
See ticket. Currently middleware is not returning that metadata, the ticket is blocked.
But you can test using mocks & update code a bit to return mocked data.
in `app-detail-view.component.ts`
line 86 
update code to be:
```
if (app) {
this.app = {
...app,
app_metadata: {
...app?.app_metadata,
capabilities: app.app_metadata?.capabilities || [
{
description: 'AdGuard Home is able to bind to a privileged port.',
name: 'NET_BIND_SERVICE',
},
{
description: 'AdGuard Home is able to chown files.',
name: 'CHOWN',
},
{
description: "AdGuard Home is able to bypass permission checks for it's sub-processes.",
name: 'FOWNER',
},
{
description: 'AdGuard Home is able …
```

NAS-130884 / 24.10.0 / Apps | App metadata like `Run As Context` and `Capabilities` should be visible before installation (by AlexKarpov98)

---

src/app/modules/forms/ix-forms/components/ix-checkbox/ix-checkbox.component.scss

git cherry-pick -x 881dd27fc4a9c4a8fd5844c664e62ce688f81793
git cherry-pick -x ec515577953148b9cab2b02aafb5e12cbdc59488
git cherry-pick -x c026cd8a1b88e45222adb89cf6a420bcd0884962
Result: 
Original PR: https://github.com/truenas/webui/pull/10685
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131101

NAS-131101 / 24.10.0 / Help button in the Active Directory menu is not clickable if the translation is too long. (by AlexKarpov98)

---

src/app/pages/system/update/components/update-actions-card/update-actions-card.component.scss

git cherry-pick -x 5c70e43e99a053085f9d1159845ba0be31874c9a
git cherry-pick -x f59fbc2bfd2674feda3fb67bd4b9b57612d6694b
git cherry-pick -x f2bd4a58105af5165950e9f5f8171bc73f84ae20
Result:
Original PR: https://github.com/truenas/webui/pull/10684
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131123

NAS-131123 / 24.10.0 / Buttons overlap on upgrade page / mobile (by AlexKarpov98)

---

src/app/modules/forms/ix-forms/components/form-actions/form-actions.component.scss

git cherry-pick -x 82d89d5776de4e69fce7c3e298baadcef0914bd4
git cherry-pick -x c7065417f8ca3123f20193ef4fe3f7e459ffde6f
git cherry-pick -x d6612ff725d5e7c5ee6fd9a2119c8ded08eeeca5
Result:
Original PR: https://github.com/truenas/webui/pull/10686
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131218

NAS-131218 / 24.10.0 / Form Buttons overlap (by AlexKarpov98)

---

src/app/pages/signin/store/signin.store.ts
src/app/pages/system/update/components/train-card/train-card.component.ts

**Changes:**
Before:
After:
**Testing:**
1. Build a machine with 24.04.0.
2. Comment out in `SigninStore`
```
switchMap(() => forkJoin([
this.checkIfAdminPasswordSet(),
// this.checkForLoginBanner(),
this.loadFailoverStatus(),
// this.updateService.hardRefreshIfNeeded(),
])),
```
3. See Update page.

NAS-131214 / 25.04 / Do not show keys from `update.get_trains`

---

src/app/pages/system/update/components/train-card/train-card.component.ts
src/app/views/sessions/signin/store/signin.store.ts

git cherry-pick -x 36566e3f2484d525ab7650d698d3f9c862c21436
git cherry-pick -x 119af35a4d64256f22b4e5641e2e65ac82277f3a
**Changes:**
Before:
After:
**Testing:**
1. Build a machine with 24.04.0.
2. Comment out in `SigninStore`
```
switchMap(() => forkJoin([
this.checkIfAdminPasswordSet(),
// this.checkForLoginBanner(),
this.loadFailoverStatus(),
// this.updateService.hardRefreshIfNeeded(),
])),
```
3. See Update page.
Original PR: https://github.com/truenas/webui/pull/10690
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131214

NAS-131214 / 24.10-RC.1 / Do not show keys from `update.get_trains` (by undsoft)

---

src/app/pages/system/update/components/train-card/train-card.component.ts
src/app/views/sessions/signin/store/signin.store.ts

git cherry-pick -x 36566e3f2484d525ab7650d698d3f9c862c21436
git cherry-pick -x 119af35a4d64256f22b4e5641e2e65ac82277f3a
**Changes:**
Before:
After:
**Testing:**
1. Build a machine with 24.04.0.
2. Comment out in `SigninStore`
```
switchMap(() => forkJoin([
this.checkIfAdminPasswordSet(),
// this.checkForLoginBanner(),
this.loadFailoverStatus(),
// this.updateService.hardRefreshIfNeeded(),
])),
```
3. See Update page.
Original PR: https://github.com/truenas/webui/pull/10690
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131214

NAS-131214 / 24.10.0 / Do not show keys from `update.get_trains` (by undsoft)

---

src/app/modules/dialog/components/full-screen-dialog/full-screen-dialog.component.scss
src/app/views/sessions/signin/signin.component.ts

git cherry-pick -x 5e8d72d0e2ee0d23dda570c9d2486a66231a6710
git cherry-pick -x 42f0d70a35ed54a3d8911ade3cb8bd1a55238569
**Changes:**
Adjust styles to display long text better.
**Testing:**
Setup login banner and check how it renders. Check the ticket for details.
**Preview:**
https://github.com/user-attachments/assets/53c52025-2595-4719-9d42-68ba8742bab8
Original PR: https://github.com/truenas/webui/pull/10709
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131276

NAS-131276 / 24.10.0 / Wrap long text on the login banner (by denysbutenko)

---

src/app/pages/apps/components/installed-apps/app-row/app-row.component.html
src/app/pages/apps/components/installed-apps/installed-apps.component.ts

**Changes:**
Now we are able to stop the app with `Deploying` status.
– The retry of deploying is done by docker.
Only allow stop from the UI is the option to fix this bug.
I've discussed it with @stavros-k .
**Testing:**
See ticket, comments, the only way for now is to allow stopping an app which is in `Deploying` phase.
|Documentation   | We can stop app with `Deploying` status.

NAS-131231 / 25.04 / if you enter an invalid AUTH key, tailscale goes into a tight restart loop

---

src/app/pages/apps/components/installed-apps/app-row/app-row.component.html
src/app/pages/apps/components/installed-apps/installed-apps.component.ts

git cherry-pick -x dadc83e8342870ee844087f567bad12c48914dfd
git cherry-pick -x 73295b24bdc6c3432d791862dd0da80d745df4dc
git cherry-pick -x b6969a51b0fab9a798dce24eff910b6cb203530b
**Changes:**
Now we are able to stop the app with `Deploying` status.
– The retry of deploying is done by docker.
Only allow stop from the UI is the option to fix this bug.
I've discussed it with @stavros-k .
**Testing:**
See ticket, comments, the only way for now is to allow stopping an app which is in `Deploying` phase. …

NAS-131231 / 24.10.0 / if you enter an invalid AUTH key, tailscale goes into a tight restart loop (by AlexKarpov98)

---

src/app/pages/system/enclosure/services/enclosure.store.spec.ts
src/app/pages/system/enclosure/services/enclosure.store.ts

**Changes:**
Adds `debounceTime` operator to `enclosure.store.ts` `disk.query` subscription pipe. The method is set to be called every time `disk.query` event emits an event. Sometimes, when enclosure state changes, `disk.query` can emit for all the disks at once. Meaning, you can get dozens of events fired in milliseconds. So, the update method was calling `webui.enclosure.dashboard` method as many times very quickly, causing the `Maximum concurrent calls` error. The `debounceTIme` operator will ensure that any surge of event updates from `disk.query` only cause one eventual `webui.enclosure.dashboard` call.
**Testing:**
Test using the steps in the ticket.

NAS-131290 / 25.04 / Add `debounceTime` to `disk.query` subscription update in `enclosure.store.ts`

---

src/app/pages/system/enclosure/services/enclosure.store.spec.ts
src/app/pages/system/enclosure/services/enclosure.store.ts

**Changes:**
Adds `debounceTime` operator to `enclosure.store.ts` `disk.query` subscription pipe. The method is set to be called every time `disk.query` event emits an event. Sometimes, when enclosure state changes, `disk.query` can emit for all the disks at once. Meaning, you can get dozens of events fired in milliseconds. So, the update method was calling `webui.enclosure.dashboard` method as many times very quickly, causing the `Maximum concurrent calls` error. The `debounceTIme` operator will ensure that any surge of event updates from `disk.query` only cause one eventual `webui.enclosure.dashboard` call.
**Testing:**
Test using the steps in the ticket.
Original PR: https://github.com/truenas/webui/pull/10717
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131290

NAS-131290 / 24.10.0 / Add `debounceTime` to `disk.query` subscription update in `enclosure.store.ts` (by RehanY147)

---

src/app/pages/account/groups/group-form/group-form.component.html

NAS-131222 / 25.04 / FT: Local Groups create new GID errors with red text: Input should be a valid integer

---

src/app/pages/account/groups/group-form/group-form.component.html

Original PR: https://github.com/truenas/webui/pull/10703
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131222

NAS-131222 / 24.10.0 / FT: Local Groups create new GID errors with red text: Input should be a valid integer (by AlexKarpov98)

---

src/app/pages/system/update/components/train-card/train-card.component.spec.ts
src/app/pages/system/update/components/train-card/train-card.component.ts
src/app/pages/system/update/services/train.service.ts

_Problem was that we always updated value to initial one or existing one._ 
Original PR: https://github.com/truenas/webui/pull/10720
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131271

NAS-131271 / 24.10.0 / Check for updates daily-button not working (by AlexKarpov98)

---

src/app/pages/dashboard/services/get-default-widgets.spec.ts
src/app/pages/dashboard/services/get-default-widgets.ts

NAS-130993 / 25.04 / Make use of a 1/4 size widget in defaults, if possible.

---

src/app/pages/account/groups/group-form/group-form.component.ts
src/app/pages/account/users/user-form/user-form.component.ts

**Changes**
Remove function was called incorrectly.
**Testing:**
Previous issue was reproducible by creating a user with `link` username and then trying to edit it.

NAS-131372 / 25.04 / Cannot edit `link` user

---

src/app/interfaces/app.interface.ts
src/app/interfaces/available-app.interface.ts
src/app/pages/apps/components/app-detail-view/app-detail-view.component.html
src/app/pages/apps/components/app-detail-view/app-json-details-card/app-json-details-card.component.html

git cherry-pick -x 114c677c1f8bd53d1d713924e12ccc9e1314db8e
git cherry-pick -x 1f46a9c111b4eb5b22337c6525568f68ed90d94c
git cherry-pick -x a3c1ec9b1f96524581b887d661849a7e0031d8c2
git cherry-pick -x d2f61c109fcdd118ad23351346ca13a02e68ae3a
**Changes:**
➡️ Feel free to take over and do any changes as you see fit!
Fixing the data-source of the 2 fields, the payload now should include the actual data
Original PR https://github.com/truenas/webui/pull/10673
Example Payload
```json
{
"id": "9342af35-5bf4-8aba-fd45-793026e5359a",
"msg": "result",
"result": [
{
"catalog": "TRUENAS",
"installed": …
```

NAS-130884 / 24.10.0 / Fix data-source (by stavros-k)

---

src/app/pages/account/groups/group-form/group-form.component.ts
src/app/pages/account/users/user-form/user-form.component.ts

git cherry-pick -x 2274cd9d9cbda3f701dc03a505d79b777f575c80
git cherry-pick -x f6d82ca3148780fdd488b7142dd4741c3bf8c619
**Changes**
Remove function was called incorrectly.
**Testing:**
Previous issue was reproducible by creating a user with `link` username and then trying to edit it.
Original PR: https://github.com/truenas/webui/pull/10738
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131372

NAS-131372 / 24.10.0 / Cannot edit `link` user (by undsoft)

---

src/app/pages/dashboard/services/get-default-widgets.spec.ts
src/app/pages/dashboard/services/get-default-widgets.ts

Testing: 
Result:
Original PR: https://github.com/truenas/webui/pull/10718
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130993

NAS-130993 / 24.10.0 / Make use of a 1/4 size widget in defaults, if possible. (by AlexKarpov98)

---

src/app/pages/apps/services/applications.service.ts
src/app/pages/apps/store/installed-apps-store.service.ts

**Changes:**
Reload installed apps on first app install
**Testing:**
On fresh nightly system when docker service is not configured and you try to install an app for first time. Ensure apps tree shows newly installed app.

NAS-131100 / 25.04 / Fix installed apps is empty on app install

---

src/app/pages/apps/services/applications.service.ts
src/app/pages/apps/store/installed-apps-store.service.ts

**Changes:**
Reload installed apps on first app install
**Testing:**
On fresh nightly system when docker service is not configured and you try to install an app for first time. Ensure apps tree shows newly installed app.
Original PR: https://github.com/truenas/webui/pull/10745
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131100

NAS-131100 / 24.10.0 / Fix installed apps is empty on app install (by denysbutenko)

---

src/app/pages/dashboard/services/widget-resources.service.spec.ts
src/app/pages/dashboard/services/widget-resources.service.ts
src/app/pages/dashboard/widgets/apps/widget-app-cpu/widget-app-cpu.component.scss
src/app/pages/dashboard/widgets/apps/widget-app-info/widget-app-info.component.scss
src/app/pages/dashboard/widgets/apps/widget-app-memory/widget-app-memory.component.scss
src/app/pages/dashboard/widgets/apps/widget-app-settings/widget-app-settings.component.spec.ts
src/app/pages/dashboard/widgets/apps/widget-app-settings/widget-app-settings.component.ts

**Changes:**
Optimize calls when many different app widgets are added to the dashboard.
**Testing:**
Add every app's widget for two apps.

NAS-131390 / 25.04 / Optimize apps widgets on dashboard

---

src/app/modules/global-search/components/global-search-results/global-search-results.component.scss
src/app/modules/ix-table/components/ix-table/ix-table.component.scss
src/app/modules/layout/topbar/user-menu/user-menu.component.scss
src/app/pages/apps/components/available-apps/app-card/app-card.component.scss
src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.html
src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.scss
src/app/pages/apps/components/installed-apps/app-row/app-row.component.scss
src/app/pages/dashboard/components/dashboard/dashboard.component.scss
src/assets/styles/mixins/text.scss
src/assets/styles/other/_material-reduction.scss

I've added new mixin for line-clamp handling.

NAS-131272 / 25.04 / App name issue in UI

---

src/app/pages/dashboard/widgets/network/widget-interface/widget-interface.component.scss

git cherry-pick -x 6bf2079d2a3cae36558e8ab6b795fb322fd37f10
git cherry-pick -x 2afce47e22a34742b02f389acd312894a9880945
Testing: See ticket
Before:
After:
Original PR: https://github.com/truenas/webui/pull/10751
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131307

NAS-131307 / 24.10.0 / Text does not fit in network widget (by AlexKarpov98)

---

src/app/pages/apps/store/installed-apps-store.service.ts

NAS-131130 / 25.04 / Refactor `subscribeToInstalledAppsUpdates` in `installed-apps-store.service`

---

src/app/modules/ix-table/utils.ts
src/app/pages/services/components/service-state-column/service-state-column.component.html
src/app/pages/services/components/service-state-column/service-state-column.component.ts

NAS-131378 / 25.04 / Fangtooth iSCSI service data-test tag of the Running toggle is inconsistent with the other iSCSI toggle.

---

src/app/pages/dashboard/widgets/system/common/widget-sys-info.scss

Result:
Original PR: https://github.com/truenas/webui/pull/10761
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131392

NAS-131392 / 24.10.0 / Dashboard - Initiate Failover button - text overlapping issue (by AlexKarpov98)

---

src/app/pages/apps/components/app-wizard/app-wizard.component.spec.ts
src/app/services/schema/app-schema.service.ts

Testing: 
See comments from Stavros Kois in the ticket.
_Side note: we discussed with @stavros-k that it's not possible to use `hidden: true` all together with `show_if` logic._
1. Install app via Shell:
```
midclt call -job app.create '{"train":"stable","catalog_app":"plex","values":{"storage":{"data":{"type":"ix_volume","ix_volume_config":{"dataset_name":"ix-custom-data"}},"config":{"type":"ix_volume","ix_volume_config":{"dataset_name":"ix-custom-config"}},"logs":{"type":"temporary"},"transcode":{"type":"temporary"}}},"app_name":"plex"}'
```
2. Go to the app edit page, hit submit.
3. You should see something like below as a data payload for `app.update`:
```
{
"config": {
"storage": {
"additional_storage": [],
"config": {
"ix_volume_config": {
"acl_enable": false,
"dataset_name": …
```

NAS-131437 / 25.04 / Restarting Plex container breaks migration mounts

---

src/app/pages/apps/components/app-wizard/app-wizard.component.spec.ts
src/app/services/schema/app-schema.service.ts

Testing: 
See comments from Stavros Kois in the ticket.
_Side note: we discussed with @stavros-k that it's not possible to use `hidden: true` all together with `show_if` logic._
1. Install app via Shell:
```
midclt call -job app.create '{"train":"stable","catalog_app":"plex","values":{"storage":{"data":{"type":"ix_volume","ix_volume_config":{"dataset_name":"ix-custom-data"}},"config":{"type":"ix_volume","ix_volume_config":{"dataset_name":"ix-custom-config"}},"logs":{"type":"temporary"},"transcode":{"type":"temporary"}}},"app_name":"plex"}'
```
2. Go to the app edit page, hit submit.
3. You should see something like below as a data payload for `app.update`:
```
{
"config": {
"storage": {
"additional_storage": [],
"config": {
"ix_volume_config": {
"acl_enable": false,
"dataset_name": …
```

NAS-131437 / 24.10.0 / Restarting Plex container breaks migration mounts (by AlexKarpov98)

---

src/app/pages/apps/components/app-wizard/app-wizard.component.spec.ts
src/app/services/schema/app-schema.service.ts

Testing: 
See comments from Stavros Kois in the ticket.
_Side note: we discussed with @stavros-k that it's not possible to use `hidden: true` all together with `show_if` logic._
1. Install app via Shell:
```
midclt call -job app.create '{"train":"stable","catalog_app":"plex","values":{"storage":{"data":{"type":"ix_volume","ix_volume_config":{"dataset_name":"ix-custom-data"}},"config":{"type":"ix_volume","ix_volume_config":{"dataset_name":"ix-custom-config"}},"logs":{"type":"temporary"},"transcode":{"type":"temporary"}}},"app_name":"plex"}'
```
2. Go to the app edit page, hit submit.
3. You should see something like below as a data payload for `app.update`:
```
{
"config": {
"storage": {
"additional_storage": [],
"config": {
"ix_volume_config": {
"acl_enable": false,
"dataset_name": …
```

NAS-131437 / 24.10-RC.1 / Restarting Plex container breaks migration mounts (by AlexKarpov98)

---

src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.html
src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.spec.ts
src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.ts

git cherry-pick -x b2e59647cd4caa2024b32b818a26dbaa63ee5dea
git cherry-pick -x 6b4d9606328c94b61a188b1d4064985f6bb75a47
git cherry-pick -x 05ac839f77955423fc7c9b1532de39fc951178a8
git cherry-pick -x 1e907b8b8e402ddb01884a70f1521b3e9d69b323
git cherry-pick -x 924743a42d5a67b4b4af6c5b8a6d65ee72537d19
I updated it for `App Info` card and `Workloads` card (I see there is as well 0.0.0.0 host ip)
Result (instead of 0.0.0.0 we have localhost locally):
https://github.com/user-attachments/assets/7d55932c-ab01-49dc-8dc5-296d51da2335
Original PR: …

NAS-131308 / 24.10.0 / First time accessing a Minio deployment the webui button launches portal is 0.0.0.0:30001 (by AlexKarpov98)

---

Dockerfile

No testing necessary, the job will either fail or not.

NAS-131552 / 25.04 / Fixing docker build

---

src/app/pages/apps/components/app-detail-view/app-available-info-card/app-available-info-card.component.html
src/app/pages/apps/components/app-detail-view/app-available-info-card/app-available-info-card.component.spec.ts
src/app/pages/apps/components/app-detail-view/app-details-header/app-details-header.component.html
src/app/pages/apps/components/app-detail-view/app-details-header/app-details-header.component.spec.ts
src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.html
src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.spec.ts

I talked with @stavros-k about this and we agreed to have `App Version` and `Version` in some places together and in some places - only Version.
So, we should mainly show the version (which is our packaged app version).
The `app_version` should show as additional information in:
- the application info card
- the upgrade dialog
- the main app page (where you can see the "install button"

NAS-130834 / 25.04 / App version vs Version is confusing

---

src/app/pages/apps/components/app-detail-view/app-available-info-card/app-available-info-card.component.html
src/app/pages/apps/components/app-detail-view/app-available-info-card/app-available-info-card.component.spec.ts
src/app/pages/apps/components/app-detail-view/app-details-header/app-details-header.component.html
src/app/pages/apps/components/app-detail-view/app-details-header/app-details-header.component.spec.ts
src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.html
src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.spec.ts

I talked with @stavros-k about this and we agreed to have `App Version` and `Version` in some places together and in some places - only Version.
So, we should mainly show the version (which is our packaged app version).
The `app_version` should show as additional information in:
- the application info card
- the upgrade dialog
- the main app page (where you can see the "install button"
Original PR: https://github.com/truenas/webui/pull/10793
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130834

NAS-130834 / 24.10.0 / App version vs Version is confusing (by AlexKarpov98)

---

src/app/pages/apps/store/installed-apps-store.service.ts

**Changes:**
Listen for apps stats only when have installed apps
**Testing:**
Check websocket messages

NAS-131461 / 25.04 / Listen for apps stats only when have installed apps

---

src/app/pages/dashboard/widgets/network/widget-interface-ip/widget-interface-ip.component.spec.ts
src/app/pages/dashboard/widgets/network/widget-interface-ip/widget-interface-ip.component.ts

Testing: 
See ticket & comments.
Comment from @yocalebo: 👇 
UI is using incorrect logic. The aliases key is the addresses that have been assigned statically via our API and exist in our database. The state.aliases key are the addresses that actually are assigned to the network interface according to the OS.
For a network widget you should only use state.aliases key.
---
Based on that I've updated UI logic.
We should rely on `networkInterface?.state?.aliases` but not on `networkInterface?.aliases`

NAS-131020 / 25.04 / Network Widget doesn't show autoconfigured IPv6 address

---

src/app/pages/dashboard/widgets/network/widget-interface-ip/widget-interface-ip.component.spec.ts
src/app/pages/dashboard/widgets/network/widget-interface-ip/widget-interface-ip.component.ts

Testing: 
See ticket & comments.
Comment from @yocalebo: 👇 
UI is using incorrect logic. The aliases key is the addresses that have been assigned statically via our API and exist in our database. The state.aliases key are the addresses that actually are assigned to the network interface according to the OS.
For a network widget you should only use state.aliases key.
---
Based on that I've updated UI logic.
We should rely on `networkInterface?.state?.aliases` but not on `networkInterface?.aliases`
Original PR: https://github.com/truenas/webui/pull/10794
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131020

NAS-131020 / 24.10.0 / Network Widget doesn't show autoconfigured IPv6 address (by AlexKarpov98)

---

package.json
scripts/icon-sprite/make-sprite.ts
src/app/modules/ix-icon/ix-icon-registry.service.ts
src/assets/icons/sprite-config.json
yarn.lock

Testing:
See new `sprite-config.json` which holds latest sprite version's url.
The idea here is to update hash if there are any changes to the sprite itself. 
If nothing changed - hash will remain the same.
To see updated hashed url - try to add new/non-used icon somewhere in .html, like `<ix-icon name="mdi-rocket"></ix-icon>`
You will see that `sprite.svg` will be changed as well as hash (`sprite-config.json`).

NAS-131550 / 25.04 / Add cache busting to icon sprite

---

src/app/pages/apps/components/installed-apps/app-row/app-row.component.ts
src/app/pages/apps/components/installed-apps/installed-apps.component.ts
src/assets/i18n/es-ar.json
src/assets/i18n/ga.json

git cherry-pick -x 0d16e59303e50bd74216f5655c0b4817a901c729
git cherry-pick -x f838c9c53f95873291f2d32a3049a1ccd9514b94
When I created an app with the following yaml:
```
version: '3.8'
services:
nginx:
image: nginx:1-alpine
ports:
- 8089:80
volumes:
- ./html5up-stellar/:/usr/share/nginx/html
```
I couldn't afterwards stop it and loader won't disappear.
If this yaml doens't work for you, you can just add throws manually.
Known issue: starting an app may flash Crashed status. This will be fixed by middleware.
Original PR: https://github.com/truenas/webui/pull/10816
Jira URL: …

NAS-131636 / 24.10.0 / Loader is not closed when there are errors when stopping … (by undsoft)

---

src/app/pages/apps/components/installed-apps/container-logs/container-logs.component.spec.ts
src/app/pages/apps/components/installed-apps/container-logs/container-logs.component.ts
src/app/pages/apps/components/logs-details-dialog/logs-details-dialog.component.html

**Changes:**
When view button for container logs for an app is clicked, user is taken to show container logs. The cancel button previously didn't take them back to the apps page. Now it does.
**Testing:**
See ticket description for testing.

NAS-131266 / 25.04 / Cancel button takes back to apps page

---

src/app/pages/apps/components/installed-apps/container-logs/container-logs.component.spec.ts
src/app/pages/apps/components/installed-apps/container-logs/container-logs.component.ts
src/app/pages/apps/components/logs-details-dialog/logs-details-dialog.component.html

git cherry-pick -x b0245879aff71644c50ace0a1a140471c84646b4
git cherry-pick -x 83fab9993c5280c29ee9b88de1a068c86b5fef44
git reset --hard HEAD~3
git cherry-pick -x 3c418ee48844ebe5c4237e0366ebde0e83fef341
**Changes:**
When view button for container logs for an app is clicked, user is taken to show container logs. The cancel button previously didn't take them back to the apps page. Now it does.
**Testing:**
See ticket description for testing.
Original PR: https://github.com/truenas/webui/pull/10802
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131266

NAS-131266 / 24.10.0 / Cancel button takes back to apps page (by RehanY147)

---

src/app/enums/dataset.enum.ts
src/app/interfaces/dataset.interface.ts
src/app/interfaces/storage.interface.ts

NAS-131693 / 25.04 / Make any required UI repo changes to account for removing option from pool.dataset endpoint

---

src/app/helpers/operators/options.operators.ts
src/app/interfaces/api/api-call-directory.interface.ts
src/app/pages/system/advanced/isolated-gpus/isolated-gpus-form/isolated-gpus-form.component.spec.ts
src/app/pages/system/advanced/isolated-gpus/isolated-gpus-form/isolated-gpus-form.component.ts
src/app/pages/vm/vm-edit-form/vm-edit-form.component.spec.ts
src/app/pages/vm/vm-edit-form/vm-edit-form.component.ts
src/app/pages/vm/vm-wizard/steps/6-gpu-step/gpu-step.component.spec.ts
src/app/pages/vm/vm-wizard/steps/6-gpu-step/gpu-step.component.ts
src/app/pages/vm/vm-wizard/vm-wizard.component.spec.ts
src/app/pages/vm/vm-wizard/vm-wizard.component.ts
src/app/services/gpu/gpu-service.spec.ts
src/app/services/gpu/gpu.service.ts

**Changes:**
Uses new API end points and filtering process to get the right data to be passed to the middleware endpoints
**Testing:**
Create a VM with one or more GPUs.
Edit a VM by removing GPUs and changing them.
Test on the system mentioned in the ticket comments.

NAS-128601 / 25.04 / Fixes the process to assign GPUs to VMs when creating or editing

---

src/app/pages/apps/components/installed-apps/app-workloads-card/app-workloads-card.component.spec.ts
src/app/pages/apps/components/installed-apps/app-workloads-card/app-workloads-card.component.ts
src/app/pages/apps/components/installed-apps/app-workloads-card/volume-mounts-dialog/volume-mounts-dialog.component.scss

Tested dialog width setup, it's possible to set width from `matDialog.open()`
I set
```
volumeButtonPressed(containerDetails: AppContainerDetails): void {
this.matDialog.open(VolumeMountsDialogComponent, {
maxWidth: '80vw',
minWidth: '50vw',
data: containerDetails,
});
}
```
And width is set and it’s working,
we currently have Global Styling to limit modal width to  max-width: 700px;
So I updated `VolumeMountsDialogComponent` view.
Testing:
See ticket.
Result:
Before:
After:

NAS-130571 / 25.04 / Impossible to set dialog width

---

src/app/pages/data-protection/cloud-backup/cloud-backup-form/cloud-backup-form.component.html
src/app/pages/data-protection/cloud-backup/cloud-backup-form/cloud-backup-form.component.ts

Testing: 
See ticket.
The idea is to show text input and not list directories when the bucket is known to not exist.

NAS-131332 / 25.04 / TrueCloud Backup Folder field with new bucket errors

---

src/app/pages/data-protection/cloud-backup/cloud-backup-form/cloud-backup-form.component.html
src/app/pages/data-protection/cloud-backup/cloud-backup-form/cloud-backup-form.component.ts

Testing: 
See ticket.
The idea is to show text input and not list directories when the bucket is known to not exist.
Original PR: https://github.com/truenas/webui/pull/10848
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131332

NAS-131332 / 24.10.1 / TrueCloud Backup Folder field with new bucket errors (by AlexKarpov98)

---

src/app/pages/storage/modules/devices/components/zfs-info-card/extend-dialog/extend-dialog.component.ts

NAS-131746 / 25.04 / RAIDZ Expansion Dialog cannot be minimized or "backgrounded" preventing further UI operations

---

src/app/pages/apps/components/installed-apps/app-workloads-card/app-workloads-card.component.html

git cherry-pick -x bebf231138e12a8830eb8635aa581cdc92fe849c
git cherry-pick -x 009012d9e944feb5f6c619492b38cf20857a76f7
Testing: 
Original PR: https://github.com/truenas/webui/pull/10855
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131712

NAS-131712 / 24.10.1 / Apps | shell button is missing when application "Starting" (by AlexKarpov98)

---

src/app/pages/apps/components/installed-apps/app-workloads-card/app-workloads-card.component.html

NAS-131713 / 25.04 / Apps | when an app is in crashed state all buttons for the container is missing

---

src/app/pages/apps/components/installed-apps/container-logs/container-logs.component.scss

**Changes:**
The text here is unreadable in the white theme:
It was due to `color: #fff` being on parent `.logs-wrapper` instead of actual child `.logs` element where it's needed to counteract the black background of terminal window.
**Testing:**
Use light theme and ensure text after header is readable and not white. The logs output should still be white on black.
nothing?

Fix logs header in light theme in Container Logs

---

src/app/pages/apps/components/installed-apps/app-workloads-card/app-workloads-card.component.html

Testing: 
Original PR: https://github.com/truenas/webui/pull/10860
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131713

NAS-131713 / 24.10.1 / Apps | when an app is in crashed state all buttons for the container is missing (by AlexKarpov98)

---

src/app/pages/storage/modules/devices/components/zfs-info-card/extend-dialog/extend-dialog.component.ts

Testing: see ticket, result:
Original PR: https://github.com/truenas/webui/pull/10863
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131746

NAS-131746 / 24.10.1 / RAIDZ Expansion Dialog cannot be minimized or "backgrounded" preventing further UI operations (by AlexKarpov98)

---

src/app/pages/data-protection/cloud-backup/cloud-backup-form/cloud-backup-form.component.html
src/app/pages/data-protection/cloud-backup/cloud-backup-form/cloud-backup-form.component.ts

Testing: 
See ticket.
The idea is to show text input and not list directories when the bucket is known to not exist.
Original PR: https://github.com/truenas/webui/pull/10848
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131332
Original PR: https://github.com/truenas/webui/pull/10856
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131332

NAS-131332 / 24.10.0 / TrueCloud Backup Folder field with new bucket errors (by AlexKarpov98) (by bugclerk)

---

src/app/pages/apps/components/installed-apps/app-workloads-card/app-workloads-card.component.html

Testing: 
Original PR: https://github.com/truenas/webui/pull/10860
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131713
Original PR: https://github.com/truenas/webui/pull/10867
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131713

NAS-131713 / 24.10.0 / Apps | when an app is in crashed state all buttons for the container is missing (by AlexKarpov98) (by bugclerk)

---

src/app/pages/vm/vm-edit-form/vm-edit-form.component.ts
src/app/services/gpu/gpu-service.spec.ts
src/app/services/gpu/gpu.service.ts

**Changes:**
Minor code improvement
**Testing:**
Code review is enough

NAS-128601 / 25.04 / Use `undefined` instead of `EMPTY`

---

src/assets/styles/mixins/cards.scss

NAS-131800 / 25.04 / App details page does not scale / cropped on mobile

---

src/assets/styles/mixins/cards.scss

Testing: see ticket, 
Result:
Original PR: https://github.com/truenas/webui/pull/10903
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131800

NAS-131800 / 24.10.1 / App details page does not scale / cropped on mobile (by AlexKarpov98)

---

src/app/pages/dashboard/widgets/cpu/widget-cpu-model/widget-cpu-model.component.scss
src/app/pages/dashboard/widgets/network/widget-interface/widget-interface.component.html
src/app/pages/dashboard/widgets/network/widget-interface/widget-interface.component.scss

**Changes:**
Fix loading state for cpu-model and interface widgets
**Testing:**
You can tweak `toLoadingState` helper to see loading state.

NAS-131844 / 25.04 / Fix loading state for cpu-model and interface widgets

---

src/app/modules/layout/topbar/change-password-dialog/change-password-dialog.component.html
src/app/modules/layout/topbar/change-password-dialog/change-password-dialog.component.spec.ts
src/app/modules/layout/topbar/change-password-dialog/change-password-dialog.component.ts

**Changes:**
**Testing:**
See ticket.
Result:
|Documentation   | Removed the "current password" field from UI for FULL_ADMIN

NAS-131848 / 25.04 / Remove the "current password" field from UI for FULL_ADMIN

---

src/app/modules/layout/components/topbar/change-password-dialog/change-password-dialog.component.html
src/app/modules/layout/components/topbar/change-password-dialog/change-password-dialog.component.spec.ts
src/app/modules/layout/components/topbar/change-password-dialog/change-password-dialog.component.ts

git cherry-pick -x 0330deafb5c4358cbc4698c770aa4e432b6e0b63
git cherry-pick -x eeb1d5d63b6845c2ab3a6724cf2ab9e4821d7be7
**Changes:**
**Testing:**
See ticket.
Result:
|Documentation   | Removed the "current password" field from UI for FULL_ADMIN
Original PR: https://github.com/truenas/webui/pull/10920
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131848

NAS-131848 / 24.10.0 / Remove the "current password" field from UI for FULL_ADMIN (by AlexKarpov98)

---

src/app/modules/forms/ix-forms/components/ix-checkbox/ix-checkbox.component.scss
src/app/modules/forms/ix-forms/components/ix-slide-toggle/ix-slide-toggle.component.scss

Testing: 
Code review.
As well noticed same issue for `ix-slide-toggle.component.scss`
Result:

NAS-131968 / 25.04 / Minor-est of issues.  There should be a space between Confirm and *

---

src/app/pages/data-protection/cloud-backup/cloud-backup-form/cloud-backup-form.component.spec.ts
src/app/pages/data-protection/cloud-backup/cloud-backup-form/cloud-backup-form.component.ts

Testing: see ticket & comments.
Now middleware handles new bucket creation if it was provided by UI.
So the idea on UI side is to remove the bucket creation calls for TrueCloud Backup Form.

NAS-131722 / 25.04 / Storj Bucket is created before `Add TrueCloud Backup Task` form successful submit

---

src/app/pages/apps/store/docker.store.ts
src/app/pages/apps/store/installed-apps-store.service.ts

**Changes:**
We were subscribing to only docker store loading boolean. Should also be listening to docker store state update observable to know when to update installed apps store again.
**Testing:**
Testing system and method described in the ticket

NAS-131913 / 24.10.1 / Fix the sequence of state updates

---

src/app/pages/apps/store/docker.store.ts
src/app/pages/apps/store/installed-apps-store.service.ts

**Changes:**
We were subscribing to only docker store loading boolean. Should also be listening to docker store state update observable to know when to update installed apps store again.
**Testing:**
Testing system and method described in the ticket

NAS-131913 / 25.04 / Fix the sequence of state updates

---

src/app/interfaces/dialog.interface.ts
src/app/modules/dialog/components/confirm-dialog/confirm-dialog.component.spec.ts
src/app/modules/dialog/components/confirm-dialog/confirm-dialog.component.ts

git cherry-pick -x 98bc80e3bcb9acc23906abe77bb145e4cd0bd077
git cherry-pick -x 5c24f6c356a1a123fad36bc525c7b7918538ef23
git cherry-pick -x f2f8d9a96f2bea50c12bf0d1e1830be337226e1a
git cherry-pick -x 7f7405c8f75610c98d06c896338bbfdaef52b7af
**Changes:**
1. Install nginx from test train.
2. Try to remove it.
AR: Nothing happens after confirmation dialog.
There has been a mismatch between types and actual return value in `confirm` when `secondaryCheckbox` key was false.
**Testing:**
You may need to replace implementation of getLacksNvidiaDrivers() with of(false) in DockerStore due to an …

NAS-132245 / 24.10.1 / Apps without ixVolumes cannot be removed (by undsoft)

---

src/app/pages/apps/components/installed-apps/app-row/app-row.component.scss
src/app/pages/apps/components/installed-apps/app-state-cell/app-state-cell.component.scss
src/app/pages/apps/components/installed-apps/installed-apps.component.scss

Testing: 
See ticket.
Before:
After:
Result:
https://github.com/user-attachments/assets/91a263f0-d553-4294-9f55-4f18b9b13c18

NAS-132076 / 25.04 / Interface to start / stop a container/app is hidden at default zoom level

---

src/app/interfaces/app.interface.ts
src/app/pages/apps/components/installed-apps/app-update-cell/app-update-cell.component.html

git cherry-pick -x d5ac62cbc4d57b1c0d3d57f65f31406be4bd88cb
git cherry-pick -x 4099ac75421bdd41e3de29b323eee846c57600a5
**Testing:**
See ticket. 
Middleware updated us with `latest_version` field, so we used it.
Original PR: https://github.com/truenas/webui/pull/10966
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131747

NAS-131747 / 24.10.1 / "Update available" tooltip for Apps shows wrong version (by AlexKarpov98)

---

src/app/pages/apps/store/installed-apps-store.service.ts

**Changes:**
- https://ixsystems.atlassian.net/browse/NAS-131885 has been fixed.
- Removed workaround to update installed apps when custom app installs.
- 
**Testing:**
Check installed apps list after custom app is installed. Expected are no changes in behavior.

NAS-132159 / 25.04 / Remove workaround for custom_app

---

src/app/pages/apps/store/installed-apps-store.service.ts

git cherry-pick -x 85ba6784d0a6acf0fcdc47449653394047b63156
git cherry-pick -x b7c8c324d28e14c40f4d731461b021e1188fa906
**Changes:**
- https://ixsystems.atlassian.net/browse/NAS-131885 has been fixed.
- Removed workaround to update installed apps when custom app installs.
- 
**Testing:**
Check installed apps list after custom app is installed. Expected are no changes in behavior.
Original PR: https://github.com/truenas/webui/pull/10995
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132159

NAS-132159 / 24.10.1 / Remove workaround for custom_app (by denysbutenko)

---

src/app/pages/dashboard/widgets/network/common/network-chart/network-chart.component.scss

On **Dashboard** page,
When the **Network widget** renders, but the chart does not scale correctly.
Access the dashboard (containing the default Network Interface widget) from the Firefox browser.
The widget should be displayed correctly (see below)

NAS-132074 / 25.04 / Fix network chart styles

---

src/app/pages/dashboard/widgets/network/common/network-chart/network-chart.component.scss

On **Dashboard** page,
When the **Network widget** renders, but the chart does not scale correctly.
Access the dashboard (containing the default Network Interface widget) from the Firefox browser.
The widget should be displayed correctly (see below)
Original PR: https://github.com/truenas/webui/pull/11020
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132074

NAS-132074 / 24.10.1 / Fix network chart styles (by bvasilenko)

---

src/app/pages/sharing/smb/smb-list/smb-list.component.spec.ts
src/app/pages/sharing/smb/smb-list/smb-list.component.ts

**Testing:**
On the **Shares** page
At the **SMB** block, 
1. User sets a share to **Disabled** state.
1. User clicked **View all** to navigate to the distinguished **SMB** page.
2. User sets this share to **Enabled** state.
2. User goes back to **Shares** page, and observes the **SMB** block (and optionally refreshes the page).
- **Expected result:** share is in **Enabled** state
Original PR: https://github.com/truenas/webui/pull/11001
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132227

NAS-132227 / 24.10.1 / Fix enable change in SMB table (by bvasilenko)

---

src/assets/i18n/fr.json

Fix error translation with NTP Burst. This word doesn't need to translate.

Fix error translation in fr.json

---

src/app/pages/data-protection/cloudsync/cloudsync-provider-description/cloudsync-provider-description.component.html
src/app/pages/data-protection/cloudsync/cloudsync-provider-description/cloudsync-provider-description.component.spec.ts

NAS-132517 / 25.04 / Cloud credentials storJ text does not render link correctly

---

src/app/interfaces/api/api-call-directory.interface.ts
src/app/interfaces/virtualization.interface.ts
src/app/pages/virtualization/components/all-instances/instance-details/instance-devices/add-device-menu/add-device-menu.component.html
src/app/pages/virtualization/components/all-instances/instance-details/instance-devices/add-device-menu/add-device-menu.component.spec.ts
src/app/pages/virtualization/components/all-instances/instance-details/instance-devices/add-device-menu/add-device-menu.component.ts
src/app/pages/virtualization/components/instance-wizard/instance-wizard.component.spec.ts
src/app/pages/virtualization/components/instance-wizard/instance-wizard.component.ts

**Changes:**
`virt.device.gpu_choices` returns an object where keys are pci addresses that should be used to add gpus to a container.
**Testing:**
I am not aware of a system that we can use for testing for now, but for now you can inspect code and tests.

NAS-132593 / 25.04 / Fix how GPU devices are added to containers

---

src/app/pages/dashboard/services/widget-resources.service.ts
src/app/pages/dashboard/widgets/storage/widget-pool/widget-pool.component.spec.ts
src/app/pages/dashboard/widgets/storage/widget-pool/widget-pool.component.ts
src/app/pages/dashboard/widgets/storage/widget-pool/widget-pool.definition.ts

**Changes:**
Adds support for the new pool widget to get pool by name from old widgets.
**Testing:**
Install 24.04 and add a pool widget on the dashboard. Then upgrade to 24.10 via an update file. Go back to the dashboard and you should see the pool widget still working and showing the pool data correctly.

NAS-132108 / 24.10.1 / Add support for name selection from old pool widgets

---

src/app/app.component.ts
src/app/interfaces/api/api-call-directory.interface.ts
src/app/modules/layout/components/topbar/user-menu/user-menu.component.spec.ts
src/app/modules/layout/components/topbar/user-menu/user-menu.component.ts
src/app/services/ping.service.spec.ts
src/app/services/ping.service.ts
src/app/services/websocket-connection.service.spec.ts
src/app/services/websocket-connection.service.ts

**Testing:**
Enter login page, authenticate, and then logout. Watch messages sent over websocket in browser's network log
**Expected results:**
1. **ping** should be sent only when user is authenticated. In other words, **ping** should not be sent on "public" pages, such as login screen
2. call `core.ping` should be done instead of sending `{ msg: 'ping' }`

NAS-132643 / 24.10.2 / Rework `ping` logic

---

src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.ts

User configures an app to use IPv6 Address for it's web interface. 
**Steps to replicate**
1. When logging into the front-end by entering IPv4 address ( 127.0.0.1:4200 ) into the address bar, 
2. User configures some app to use IPv6 Address for it's web interface
3. User logs out. And then logs in again, but by entering IPv6 address of the server into the address bar
4. Go to **Apps**, choose this App, and click button to access app's web interface.
Please also see video attachment in the ticket.
**Expected Result**
- The Apps can be accessed using both Ipv4 and IPv6 URL's

NAS-131595 / 25.04 / Prepare redirect URL for IPv6

---

src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/layout-step/automated-disk-selection/draid-selection/draid-selection.component.spec.ts
src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/layout-step/automated-disk-selection/draid-selection/draid-selection.component.ts

**Changes:**
Adjusts min allowed child count when creating dRaid pools
**Testing:**
The children select's minimum value when creating a draid pool should be calculated based on this formula
```
max = Math.min(maxAvailableDisks, 255)
parity = 1 if dRaid1, 2 if dRaid2, 3 if dRaid3
min = (data vdev disks) + (hot spares count) + parity
```

NAS-128390 / 25.04 / Adjust min child count when creating draid pools

---

src/app/pages/credentials/backup-credentials/cloud-credentials-card/cloud-credentials-card.component.ts

Testing: 
See custom error as an example:
https://github.com/user-attachments/assets/4b8e9bdb-7885-4989-9db3-80f43a01525c

NAS-132751 / 25.04 / Cloud Credentials: It is not possible to delete cloud credentials

---

src/app/pages/data-protection/cloud-backup/cloud-backup-form/cloud-backup-form.component.html
src/app/pages/data-protection/cloud-backup/cloud-backup-form/cloud-backup-form.component.spec.ts
src/app/pages/data-protection/cloud-backup/cloud-backup-form/cloud-backup-form.component.ts

**Changes:**
Hides "Take Snapshot" option from the UI as requested in the ticket.
|Documentation   | Removes an option from Truecloud Backup form.

NAS-132805 / 24.10.1 / Hide "take snapshot" for TrueCloud backup

---

src/app/core/guards/websocket-connection.guard.ts
src/app/core/testing/utils/empty-auth.service.ts
src/app/pages/signin/store/signin.store.spec.ts
src/app/pages/signin/store/signin.store.ts
src/app/services/auth/auth-guard.service.spec.ts
src/app/services/auth/auth-guard.service.ts
src/app/services/auth/auth.service.spec.ts
src/app/services/auth/auth.service.ts
src/app/services/websocket/websocket-handler.service.ts
src/main.ts

**Changes:**
**Testing:**
One method:
* clear `localStorage`
* you'll have to comment out the `https:` check in `AuthService.setQueryToken`
* `midclt call auth.generate_token`
* append the token to an app route: `localhost:4200/storage/disks?token=<token>`

NAS-132648 / 25.04 / query param handling for auth tokens

---

src/app/modules/layout/copyright-line/copyright-line.component.html
src/app/modules/layout/copyright-line/copyright-line.component.spec.ts
src/app/modules/layout/copyright-line/copyright-line.component.ts

**Changes:**
Update link in copyright line
**Testing:**
Check affected places

NAS-131248 / 25.04 / Update copyright line component to use dynamic links

---

src/app/pages/dashboard/widgets/apps/widget-app/widget-app.component.html
src/app/pages/dashboard/widgets/apps/widget-app/widget-app.component.spec.ts
src/app/pages/dashboard/widgets/apps/widget-app/widget-app.component.ts

**Changes:**
Changes how we get the subscription observable in the component
**Testing:**
Install two apps. plex and photoprism. Go to the dashboard. Add a widget for photoprism. Large widget for the app overview. Then without saving, open the add widget form again and add another widget for the same app. 
Problem:
The stats data doesn't load the second time
Fix:
The stats load every time

NAS-131558 / 25.04 / Change observable subscription for apps widget

---

src/app/pages/credentials/certificates-dash/certificate-authority-add/steps/ca-identifier-and-type/ca-identifier-and-type.component.html
src/app/pages/credentials/certificates-dash/certificate-edit/certificate-edit.component.html
src/app/pages/credentials/certificates-dash/certificate-edit/certificate-edit.component.spec.ts
src/app/pages/credentials/certificates-dash/certificate-edit/certificate-edit.component.ts
src/app/pages/credentials/certificates-dash/forms/certificate-add/steps/certificate-identifier-and-type/certificate-identifier-and-type.component.html

I talked with Waqar, he told me that we should remove `Add to Trusted Store` for `CSR` in edit form and not add it for creation form.

NAS-132967 / 25.04 / Trusted Store option not present on CSR creation but is on edit

---

src/app/pages/apps/components/installed-apps/app-details-panel/app-details-panel.component.html
src/app/pages/apps/components/installed-apps/app-details-panel/app-details-panel.component.spec.ts

git cherry-pick -x 2f84efe7391fd52fbeb4df62c3ca27e68e8c5494
git cherry-pick -x 7864ad7a4f521f7a9ce5749496bead63a620287f
git cherry-pick -x a0878977874337ff65586e3183f5150a72f26fc3
git cherry-pick -x 38a0f8bddbe296a0d3cafbb95d98778752e0704e
Testing: 
before:
after:
Original PR: https://github.com/truenas/webui/pull/11194
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131851

NAS-131851 / 24.10.2 / Custom Apps: Empty info cards (App Metadata) are visible (by AlexKarpov98)

---

scripts/test_changed.js

**Changes:**
Fixes an incorrect "Some tests failed" message that was shown when using `yarn test:changed`.
**Testing:**
1. Make change in some component that has tests.
2. `yarn test:changed`.

NAS-133096 / 25.04 / Fix Some tests failed message

---

src/app/modules/layout/topbar/user-menu/user-menu.component.html
src/app/modules/layout/topbar/user-menu/user-menu.elements.ts
src/app/pages/credentials/users/user-api-keys/user-api-keys.elements.ts
src/assets/ui-searchable-elements.json

NAS-133237 / 25.04 / Add search elements for API keys

---

src/app/pages/storage/components/unused-resources/unused-resources.component.html
src/app/pages/storage/components/unused-resources/unused-resources.component.spec.ts
src/app/pages/storage/components/unused-resources/unused-resources.component.ts

git cherry-pick -x ee2da2e7e1bfff679104373555e73d84eba485f6
git cherry-pick -x eac8c1d7479087176994a3615e8bc021416ea843
git cherry-pick -x 11f1665f74df5ce7f51bbe877bb9eca6b32af9b5
git cherry-pick -x 8d90712eb4219aafcf54c3fc4d70a8217d376436
Unused disks now appear/update instantly (without page refresh).
Result:
https://github.com/user-attachments/assets/e3042b4b-6b8d-4680-a61b-819dfaa4d021
Original PR: https://github.com/truenas/webui/pull/11209
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131994

NAS-131994 / 24.10.2 / Storage: Number of available disks doesn't update after a disconnect/destroy data until screen refresh (by AlexKarpov98)

---

src/app/directives/navigate-and-interact/navigate-and-interact.service.ts

Result:
https://github.com/user-attachments/assets/0376ef43-8388-40ad-8162-e8227384a0cc

NAS-133239 / 25.04 / Remove highlighting when user interacts with a page

---

src/app/pages/apps/components/installed-apps/installed-apps.component.html

Testing: 
This is the proposed solution. Similar issue is appearing for all other similar scenarios, like Datasets, Instances.
Result:
https://github.com/user-attachments/assets/93884a3a-82ea-458d-9ade-97e11596acf4
Let's see if we like this solution first.

NAS-133107 / 25.04 / Apps UI, when apps are filtered continues to show prior selection details, even when not shown in the list

---

src/app/admin.routes.ts
src/app/pages/reports-dashboard/reports-dashboard.component.spec.ts
src/app/pages/reports-dashboard/reports-dashboard.component.ts
src/app/pages/reports-dashboard/reports.service.spec.ts
src/app/pages/reports-dashboard/reports.service.ts

**Testing:**
Go to **Reporting > Disk** and ensure that the stats are displayed correctly

NAS-131912 / 25.04 / Adapt to back-end changes in disk stats

---

src/assets/styles/other/_material-overrides.scss

Testing: see ticket. Check another places where `<ix-chip` used.
Result:

NAS-133330 / 25.04 / Misaligned input/placeholder

---

src/app/pages/dashboard/widgets/cpu/common/cpu-core-bar/cpu-core-bar.component.spec.ts
src/app/pages/dashboard/widgets/cpu/common/cpu-core-bar/cpu-core-bar.component.ts
src/app/pages/dashboard/widgets/network/widget-interface/widget-interface.component.ts

**Changes:**
Previous UI code assumes that if hyperthreading is enabled, than there must be 2 threads per core. 
This is not the case for newer CPUs that have performance and efficiency cores. In Intel processors efficiency cores are single-threaded.
This PR simplifies the logic to just showing what middleware sends us.
**Testing:**
Test CPU widgets for regressions.
You can also use mock data from the ticket in `WidgetResourcesService`.

NAS-133128 / 24.10.2 / Simplify CPU widget logic

---

src/app/pages/storage/modules/devices/components/disk-details-panel/disk-details-panel.component.ts
src/app/pages/storage/modules/devices/components/zfs-info-card/raidz-extend-dialog/raidz-extend-dialog.component.ts

**Testing:**
1. Replace `ws.service.ts` with attached file.
[ws.service.ts.txt](https://github.com/user-attachments/files/18339620/ws.service.ts.txt)
2. Navigate to `/storage/3/devices/` and test that cards open. Functionality will be limited because of the mock
, but there should not be console errors.

NAS-133299 / 24.10.2 / Extend window not showing up for spares

---

src/app/pages/storage/modules/disks/components/smart-test-result-list/smart-test-result-list.component.spec.ts
src/app/pages/storage/modules/disks/components/smart-test-result-list/smart-test-result-list.component.ts

**Changes:**
Added factor 100 to "Remaining" column
**Testing:**
Use the following mockup response for  `smart.test.results` call:
```
[{"tests": [{"num": 1, "description": "Short offline", "status_verbose": "Completed without error", "remaining": 0.0, "lifetime": 1677, "lba_of_first_error": null, "status": "SUCCESS"}, {"num": 2, "description": "Extended offline", "status_verbose": "Completed without error", "remaining": 0.0, "lifetime": 1656, "lba_of_first_error": null, "status": "SUCCESS"}, {"num": 3, "description": "Extended offline", "status_verbose": "Aborted by host", "remaining": 0.9, "lifetime": 1627, "lba_of_first_error": null, "status": "ABORTED"}, {"num": 4, "description": "Short offline", "status_verbose": "Aborted by host", "remaining": 0.9, "lifetime": 37, …
```

NAS-133373 / 25.04 / Storage > Disks > Fix remaining display

---

src/app/modules/layout/topbar/directory-services-indicator/directory-services-indicator.component.spec.ts
src/app/modules/layout/topbar/directory-services-indicator/directory-services-indicator.component.ts
src/app/pages/sharing/iscsi/iscsi-wizard/iscsi-wizard.component.html
src/app/pages/sharing/iscsi/iscsi-wizard/iscsi-wizard.component.spec.ts
src/app/pages/sharing/iscsi/iscsi-wizard/iscsi-wizard.component.ts
src/app/pages/sharing/iscsi/iscsi.component.ts
src/app/pages/sharing/iscsi/target/all-targets/all-targets.component.html
src/app/pages/sharing/iscsi/target/all-targets/target-details/connections-card/connections-card.component.ts
src/app/pages/sharing/iscsi/target/all-targets/target-details/fibre-channel-connections-card/fibre-channel-connections-card.component.html
src/app/pages/sharing/iscsi/target/all-targets/target-details/fibre-channel-connections-card/fibre-channel-connections-card.component.spec.ts
src/app/pages/sharing/iscsi/target/all-targets/target-details/fibre-channel-connections-card/fibre-channel-connections-card.component.ts
src/app/services/iscsi.service.ts

**Changes:**
Minor fixes and improvements.
**Testing:**
Check ticket details.

NAS-133354 / 25.04 / QA iSCSI pages

---

package.json
src/app/enums/explorer-type.enum.ts
src/app/modules/forms/ix-forms/components/ix-explorer/ix-explorer.component.html
src/app/pages/data-protection/cloud-backup/cloud-backup-form/cloud-backup-form.component.html
src/app/pages/data-protection/cloud-backup/cloud-backup-form/cloud-backup-form.component.ts
src/app/services/filesystem.service.spec.ts
src/app/services/filesystem.service.ts
yarn.lock

**Changes:**
Adds option to load zvols alongside datasets by providing two root paths. `/dev/zvol` alongside `/mnt` when calling `filesystem.listdir` endpoint. `ix-explorer` `root` property should be set to `/` for this. Default `root` for `ix-explorer` is `/mnt`
**Testing:**
Test on the TrueCloud Task Form. The path explorer should show `'/'` as it's root. When expanded, it should show two children paths. `'/mnt'` and `'/dev/zvol'`. When expanded, `'/mnt'` should show the normal datasets and `'/dev/zvol'` should show the zvols.
Original PR: https://github.com/truenas/webui/pull/11332
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132372

NAS-132372 / 24.10.2 / Add `/dev/zvol` root for explorer (by RehanY147)

---

src/app/pages/apps/components/installed-apps/installed-apps-list/installed-apps-list.component.scss

Testing: see ticket & comments.
Results:
No scrollbar anymore & aligned Controls.

NAS-131818 / 25.04 / Apps: The horizontal scroll bar makes columns unaligned with the column header

---

src/app/helpers/file-size.utils.spec.ts
src/app/helpers/file-size.utils.ts
src/app/modules/ix-table/classes/async-data-provider/async-data-provider.spec.ts
src/app/modules/ix-table/utils.ts
src/app/pages/storage/modules/disks/components/disk-list/disk-list.component.html
src/app/pages/storage/modules/disks/components/disk-list/disk-list.component.ts

Result:
https://github.com/user-attachments/assets/54b5b0d7-f1fa-4075-a352-76ff312b066e

NAS-133540 / 25.04 / Allow disk list to be filtered by size

---

src/app/pages/system/general-settings/email/email-form/email-form.component.html
src/app/pages/system/general-settings/email/email-form/email-form.component.spec.ts
src/app/pages/system/general-settings/email/email-form/email-form.component.ts

**Testing:**
See ticket.
Result:
|Documentation   | From Email option is now required for Outlook provider

NAS-133538 / 25.04 / `fromemail` must be specified when setting up OAuth for Outlook Mail

---

src/app/pages/credentials/groups/privilege/privilege-form/privilege-form.component.html
src/app/pages/credentials/groups/privilege/privilege-form/privilege-form.component.ts

**Changes:**
Added ability of manual entry into the groups dropdown
**Testing:**
1. Prosivion a new machine with HA and Active Directory
2. Please see ticket for replication steps and expected results

NAS-133477 / 25.04 / Allow adding directory services groups manually

---

package.json
src/app/enums/explorer-type.enum.ts
src/app/modules/forms/ix-forms/components/ix-explorer/ix-explorer.component.html
src/app/pages/data-protection/cloud-backup/cloud-backup-form/cloud-backup-form.component.html
src/app/pages/data-protection/cloud-backup/cloud-backup-form/cloud-backup-form.component.ts
src/app/services/filesystem.service.spec.ts
src/app/services/filesystem.service.ts
yarn.lock

**Changes:**
Adds option to load zvols alongside datasets by providing two root paths. `/dev/zvol` alongside `/mnt` when calling `filesystem.listdir` endpoint. `ix-explorer` `root` property should be set to `/` for this. Default `root` for `ix-explorer` is `/mnt`
**Testing:**
Test on the TrueCloud Task Form. The path explorer should show `'/'` as it's root. When expanded, it should show two children paths. `'/mnt'` and `'/dev/zvol'`. When expanded, `'/mnt'` should show the normal datasets and `'/dev/zvol'` should show the zvols.

NAS-132372 / 24.10.3 / Add `/dev/zvol` root for explorer

---

src/app/services/filesystem.service.spec.ts
src/app/services/filesystem.service.ts

**Testing:**
Use machine, where the issue was discovered: `r40-1.dc1.ixsystems.net`
Please see video attached to the ticket

NAS-133622 / 24.10.2.1 / Add `is_ctldir` to `filesystem.listdir` response

---

src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.ts

**Testing:**
Check that `force_remove_ix_volumes` is being correctly sent when you delete an app.
Original PR: https://github.com/truenas/webui/pull/11374
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133582

NAS-133582 / 24.10.2.1 / Fix force_remove_ix_volumes (by undsoft)

---

src/app/pages/sharing/smb/smb-form/smb-form.component.ts

See Comment:
Original PR: https://github.com/truenas/webui/pull/11384
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133736

NAS-133736 / 25.04-RC.1 / UI always submits a zero-sized time machine quota for SMB shares (by AlexKarpov98)

---

src/app/pages/sharing/smb/smb-form/smb-form.component.ts

See Comment:
Original PR: https://github.com/truenas/webui/pull/11384
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133736

NAS-133736 / 25.04-BETA.1 / UI always submits a zero-sized time machine quota for SMB shares (by AlexKarpov98)

---

src/app/pages/services/services.component.ts
src/app/pages/sharing/iscsi/iscsi.component.html
src/app/pages/sharing/iscsi/iscsi.component.ts
src/app/pages/sharing/iscsi/target/all-targets/target-details/associated-extents-card/associated-extents-card.component.html
src/assets/ui-searchable-elements.json

**Changes:**
* [NAS-133776: Adds checks for remove association in ISCSI targets.](https://ixsystems.atlassian.net/browse/NAS-133776)
* [NAS-133775: Removes checks for Global Target Configuration button.](https://ixsystems.atlassian.net/browse/NAS-133775)
* [NAS-133740: Removes checks for edit button on the service list.](https://ixsystems.atlassian.net/browse/NAS-133740)

NAS-133740 / 25.10 / Permission checks

---

src/app/pages/services/services.component.ts
src/app/pages/sharing/iscsi/iscsi.component.html
src/app/pages/sharing/iscsi/iscsi.component.ts
src/app/pages/sharing/iscsi/target/all-targets/target-details/associated-extents-card/associated-extents-card.component.html
src/assets/ui-searchable-elements.json

**Changes:**
* [NAS-133776: Adds checks for remove association in ISCSI targets.](https://ixsystems.atlassian.net/browse/NAS-133776)
* [NAS-133775: Removes checks for Global Target Configuration button.](https://ixsystems.atlassian.net/browse/NAS-133775)
* [NAS-133740: Removes checks for edit button on the service list.](https://ixsystems.atlassian.net/browse/NAS-133740)
Original PR: https://github.com/truenas/webui/pull/11386
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133740

NAS-133740 / 25.04-RC.1 / Permission checks (by undsoft)

---

src/app/pages/apps/components/custom-app-form/custom-app-form.component.html
src/app/pages/apps/components/custom-app-form/custom-app-form.component.spec.ts
src/app/pages/apps/components/custom-app-form/custom-app-form.component.ts

Result:
https://github.com/user-attachments/assets/9eaf1b20-7d90-4157-824d-b4464e9cde11

NAS-133816 / 25.10 / YAML is not available during edit when app is created

---

src/app/helptext/data-protection/cloud-backup/cloud-backup.ts
src/app/pages/data-protection/cloud-backup/cloud-backup-form/cloud-backup-form.component.spec.ts
src/assets/i18n/es-ar.json

**Changes:**
Renames checkbox "Take Snapshot" to "Use Snapshot". See ticket for instructions
**Testing:**
See that checkbox is renamed
|Documentation   | Renames checkbox "Take Snapshot" to "Use Snapshot" on the TrueCloud Backup Tasks form

NAS-133830 / 25.10 / Renames checkbox "Take Snapshot" to "Use Snapshot"

---

src/app/modules/forms/ix-forms/components/ix-code-editor/ix-code-editor.component.ts
src/app/modules/forms/ix-forms/components/ix-code-editor/ix-code-editor.spec.ts

Result:
https://github.com/user-attachments/assets/e38f74e3-1f5a-48f3-bf99-2eb3d86be275
Original PR: https://github.com/truenas/webui/pull/11437
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133815

NAS-133815 / 25.04-RC.1 / Code editor gets marked dirty incorrectly (by AlexKarpov98)

---

src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts

It shows as expected now, on form start:
Original PR: https://github.com/truenas/webui/pull/11418
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133130

NAS-133130 / 25.04-RC.1 / Advanced Cloud Sync Task: "Use Snapshot" checked box does not disappear correctly when direction is pull (by AlexKarpov98)

---

src/app/pages/apps/services/applications.service.ts

**Changes:**
Pass location.hostname to the `host_ip` argument to `app.query` API calls. This makes it so that portals use a URL based on the hostname used to access the TrueNAS web UI, rather than a URL based on the IP address which is the default when not passing a `host_ip`.
I believe that this was the intention of the existing code, since https://github.com/truenas/webui/blob/master/src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.ts#L116-L126 already replaces `0.0.0.0` with `window.location.hostname`. However, after https://github.com/truenas/middleware/pull/14057, the portal URI which we get from the back-end is already transformed to replace `0.0.0.0` with the value passed from `host_ip`, so that code doesn't have an effect anymore.
**Testing:** …

Pass location.hostname as host_ip to app.query

---

src/app/pages/virtualization/components/instance-wizard/instance-wizard.component.spec.ts
src/app/pages/virtualization/components/instance-wizard/instance-wizard.component.ts

git cherry-pick -x 75d4a4bdaf0dbc768729a68318cba86067fcab60
git cherry-pick -x f706d0df52e76d0b04d19496ea5278325739dbaf
git cherry-pick -x c79c45e4de9fce44060f9586886f7e65c8df0e18
git cherry-pick -x 4d874471319814c5d0a79f863aa55a060f0e509d
Added missing `gpu_type` field for GPU devices.
Currently only `PHYSICAL` is acceptable.
Same applies for the GPU devices list:
```
gpuDevices$ = this.api.call(
'virt.device.gpu_choices',
[VirtualizationGpuType.Physical],
)
``` 
Original PR: https://github.com/truenas/webui/pull/11462
Jira URL: …

NAS-133861 / 25.04-RC.1 / Cannot create VM with GPU selected (by AlexKarpov98)

---

src/app/pages/virtualization/components/instance-wizard/instance-wizard.component.spec.ts
src/app/pages/virtualization/components/instance-wizard/instance-wizard.component.ts

git cherry-pick -x 75d4a4bdaf0dbc768729a68318cba86067fcab60
git cherry-pick -x f706d0df52e76d0b04d19496ea5278325739dbaf
git cherry-pick -x c79c45e4de9fce44060f9586886f7e65c8df0e18
git cherry-pick -x 4d874471319814c5d0a79f863aa55a060f0e509d
Added missing `gpu_type` field for GPU devices.
Currently only `PHYSICAL` is acceptable.
Same applies for the GPU devices list:
```
gpuDevices$ = this.api.call(
'virt.device.gpu_choices',
[VirtualizationGpuType.Physical],
)
``` 
Original PR: https://github.com/truenas/webui/pull/11462
Jira URL: …

NAS-133861 / 25.04-BETA.1 / Cannot create VM with GPU selected (by AlexKarpov98)

---

src/app/pages/sharing/iscsi/target/all-targets/target-details/associated-extents-card/associated-extents-card.component.ts

```
Updated
I understand the issue when I connected the target through the initiator, it was not possible to remove it. This is a valid reason. But it would be good if there were warning texts about that.
```
https://github.com/user-attachments/assets/a39acc2c-28f8-4a77-8b43-27213d8b4ac0

NAS-133970 / 25.10 / Add error handling for removal the extent association from the iSCSI Targets page

---

src/app/pages/sharing/iscsi/target/all-targets/target-details/associated-extents-card/associated-extents-card.component.ts

```
Updated
I understand the issue when I connected the target through the initiator, it was not possible to remove it. This is a valid reason. But it would be good if there were warning texts about that.
```
https://github.com/user-attachments/assets/a39acc2c-28f8-4a77-8b43-27213d8b4ac0
Original PR: https://github.com/truenas/webui/pull/11477
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133970

NAS-133970 / 25.04-RC.1 / Add error handling for removal the extent association from the iSCSI Targets page (by AlexKarpov98)

---

src/app/pages/virtualization/components/instance-wizard/instance-wizard.component.html
src/app/pages/virtualization/components/instance-wizard/instance-wizard.component.spec.ts
src/app/pages/virtualization/components/instance-wizard/instance-wizard.component.ts

Result:
https://github.com/user-attachments/assets/0a8153a3-f2ee-4123-a5e0-57e13f948925

NAS-133998 / 25.10 / Do not show root disk size field when importing a zvol

---

src/app/pages/credentials/users/user-api-keys/user-api-keys.component.spec.ts
src/app/pages/virtualization/components/instance-wizard/instance-wizard.component.html
src/app/pages/virtualization/components/instance-wizard/instance-wizard.component.spec.ts
src/app/pages/virtualization/components/instance-wizard/instance-wizard.component.ts

git cherry-pick -x 34347528ab58f189c954831abdfe604f60defb16
git cherry-pick -x 7f930817eb4480df83e5f75c6ee0515378525731
Result:
https://github.com/user-attachments/assets/0a8153a3-f2ee-4123-a5e0-57e13f948925
Original PR: https://github.com/truenas/webui/pull/11489
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133998

NAS-133998 / 25.04-RC.1 / Do not show root disk size field when importing a zvol (by AlexKarpov98)

---

src/app/modules/layout/topbar/topbar.component.scss
src/assets/styles/other/_material-overrides.scss

git cherry-pick -x f6d21d9f66056551932c252486cd18870c79fcab
git cherry-pick -x bae4577c6f7d294c97ebee3d6ceb7fe0d337530e
git cherry-pick -x b808ccab524e91642a6be740d1d21f96e561360e
git cherry-pick -x 14743758bbc59118661a7b97290baff6de97cc20
git cherry-pick -x 5111e7706e622748a85bed8a15494d8701d400a7
git cherry-pick -x aa8b6b51247f31d487a25fa54198cbacac2d2981
Result:
https://github.com/user-attachments/assets/917c75e8-aca0-48b0-b892-6c0031014cf1
Original PR: https://github.com/truenas/webui/pull/11461
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133853

NAS-133853 / 25.04-RC.1 / ix-blue theme wrong icon colors (by AlexKarpov98)

---

src/app/modules/layout/topbar/power-menu/power-menu.component.spec.ts
src/app/modules/layout/topbar/power-menu/power-menu.component.ts
src/app/modules/layout/topbar/reboot-or-shutdown-dialog/reboot-or-shutdown-dialog.component.html

NAS-134050 / 25.10 / Restart dialog layout shifts because of validation message

---

src/app/pages/dashboard/widgets/cpu/widget-cpu-usage-bar/widget-cpu-usage-bar.component.scss
src/app/pages/datasets/modules/encryption/components/export-dataset-key-dialog/export-dataset-key-dialog.component.spec.ts
src/app/pages/datasets/modules/encryption/components/export-dataset-key-dialog/export-dataset-key-dialog.component.ts

git cherry-pick -x 8edfb86108554a9fceffda9166dac64c8d45d9ba
git cherry-pick -x 6066f1cda13dd70c81e29b5bbbb6edec4e3446b9
git cherry-pick -x 84095d400815e55e27b868e9688641e9e470c209
Original issue:
> 1. Create a dataset with Key encryption.
> 2. Simulate pool.dataset.export_key failing in loadKey in ExportDatasetKeyDialogComponent.
> 3. Click Export Key.
> ER: I see error dialog and I am not prompted to download the key.
> AR: I see error dialog and then I am prompted to download the key.
Original PR: https://github.com/truenas/webui/pull/11505
Jira URL: …

NAS-134046 / 25.04-RC.1 / Auth error in Export Key is not properly handled (by undsoft)

---

src/app/pages/audit/audit.component.scss
src/app/pages/data-protection/cloud-backup/all-cloud-backups/all-cloud-backups.component.html
src/app/pages/data-protection/cloud-backup/all-cloud-backups/all-cloud-backups.component.spec.ts
src/app/pages/data-protection/cloud-backup/all-cloud-backups/all-cloud-backups.component.ts
src/app/pages/data-protection/cloud-backup/cloud-backup-details/cloud-backup-details.component.html
src/app/pages/data-protection/cloud-backup/cloud-backup-details/cloud-backup-details.component.ts
src/app/pages/data-protection/cloud-backup/cloud-backup-list/cloud-backup-list.component.html
src/app/pages/data-protection/cloud-backup/cloud-backup-list/cloud-backup-list.component.scss
src/app/pages/data-protection/cloud-backup/cloud-backup-list/cloud-backup-list.component.ts
src/app/pages/data-protection/data-protection.routes.ts
src/assets/ui-searchable-elements.json

git cherry-pick -x 0930eb80c5266aee3f6ba688a0e72f5a2fa9d69f
git cherry-pick -x d742b0e7c0995f25627d7cbbc6267456c6a3958f
git cherry-pick -x 716dafce47db132b7bc9772d8c19ef7e6440eae8
git cherry-pick -x db1ed7bcd30cfe1dcc485687bd057b7a95327e68
git cherry-pick -x 4b3acb8bbec3aad2538f7163eaccff334927d2e8
git cherry-pick -x b8494cc62ec0c521f6624f02e35636cf3a103992
git cherry-pick -x 94303d12c1f96036825823fcd520f588a6e5836a
git cherry-pick -x 1fbdc9fef73402a4cc98d455ef2f9349168f5ca3
git cherry-pick -x 2bd276f58af8847e9e35d030841ef4fc4098f583
git cherry-pick -x a37df00ec8515e830f594fc91589a94a9fc8caa7
git cherry-pick -x b72879839ab8824431e990d024ec32bf6f7935b7
git cherry-pick -x …

NAS-133675 / 25.04-RC.1 / Refactor CloudBackupListComponent to master-detail-view (by denysbutenko)

---

src/app/store/preferences/preferences.effects.spec.ts
src/app/store/preferences/preferences.effects.ts

**Testing:**
Steps to reproduce:
1. Go to **Advanced Settings \> Access widget**
2. Click **Configure** and change the value of **Session Timeout**. Save.
3. Refresh the window
4. **Session Timeout** reverts to it's previous value, `300`
**Expected result:** proper value is saved and then loaded
Original PR: https://github.com/truenas/webui/pull/11404
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133598

NAS-133598 / 25.04-RC.1 / Fix `saveUpdatedPreferences` effect (by bvasilenko)

---

src/app/modules/layout/topbar/user-menu/user-menu.component.scss

git cherry-pick -x fc30f4835b646307f6b8cdcb78cd7b780d45755c
git cherry-pick -x 433583e781ffa82f01fe005447e92298edbd2d31
git cherry-pick -x f431c845b0b0f91f6ce3d7c76be6df2d8b82c3be
git cherry-pick -x c8b9cc25b937048668e40941e9a1aa2aeeeecb95
Result:
Original PR: https://github.com/truenas/webui/pull/11509
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134022

NAS-134022 / 25.04-RC.1 / Long admin names do not fit on the screen (by AlexKarpov98)

---

src/app/modules/forms/ix-forms/components/ix-explorer/ix-explorer.component.html
src/app/modules/forms/ix-forms/components/ix-explorer/ix-explorer.component.ts
src/app/pages/datasets/components/dataset-details-panel/dataset-details-panel.component.ts
src/app/pages/datasets/components/dataset-form/dataset-form.component.spec.ts
src/app/pages/datasets/components/dataset-form/dataset-form.component.ts
src/app/pages/datasets/components/zvol-form/zvol-form.component.spec.ts
src/app/pages/datasets/components/zvol-form/zvol-form.component.ts
src/app/pages/instances/components/instance-wizard/instance-wizard.component.html
src/app/pages/instances/components/instance-wizard/instance-wizard.component.ts
src/app/services/filesystem.service.spec.ts

git cherry-pick -x 644082303a78a74bc4e67ab4bc188711c7aac78f
git cherry-pick -x d72d33acbe429dbe96386660c3543911c1d2b8da
git cherry-pick -x 553356aacb9f12dc011e6c47f98bd0fd69ba39ce
git cherry-pick -x 9bb480b6117b93d5268678677fbbc9046c2f6c03
git cherry-pick -x 862a7870b70f7ebc645700927d14dd67cf7f109b
git cherry-pick -x 9e39dc8ecc35a34e7c185b8c5798690a13ec7485
git cherry-pick -x 39582aeff4782b2641f197175c1e9ca49d9a9247
git cherry-pick -x fa8238843452499b49b4f269a95549cb98401a5b
**Changes:**
**IxExplorer**: Reload node children on toggle
**Testing:**
Check any page with `ix-explorer` and …

NAS-133774 / 25.04-BETA.1 / Reload node children on toggle in ix-explorer (by denysbutenko)

---

src/app/modules/forms/ix-forms/components/ix-explorer/ix-explorer.component.html
src/app/modules/forms/ix-forms/components/ix-explorer/ix-explorer.component.ts
src/app/pages/datasets/components/dataset-details-panel/dataset-details-panel.component.ts
src/app/pages/datasets/components/dataset-form/dataset-form.component.spec.ts
src/app/pages/datasets/components/dataset-form/dataset-form.component.ts
src/app/pages/datasets/components/zvol-form/zvol-form.component.spec.ts
src/app/pages/datasets/components/zvol-form/zvol-form.component.ts
src/app/pages/instances/components/instance-wizard/instance-wizard.component.html
src/app/pages/instances/components/instance-wizard/instance-wizard.component.ts
src/app/services/filesystem.service.spec.ts

git cherry-pick -x 644082303a78a74bc4e67ab4bc188711c7aac78f
git cherry-pick -x d72d33acbe429dbe96386660c3543911c1d2b8da
git cherry-pick -x 553356aacb9f12dc011e6c47f98bd0fd69ba39ce
git cherry-pick -x 9bb480b6117b93d5268678677fbbc9046c2f6c03
git cherry-pick -x 862a7870b70f7ebc645700927d14dd67cf7f109b
git cherry-pick -x 9e39dc8ecc35a34e7c185b8c5798690a13ec7485
git cherry-pick -x 39582aeff4782b2641f197175c1e9ca49d9a9247
git cherry-pick -x fa8238843452499b49b4f269a95549cb98401a5b
**Changes:**
**IxExplorer**: Reload node children on toggle
**Testing:**
Check any page with `ix-explorer` and …

NAS-133774 / 25.04-RC.1 / Reload node children on toggle in ix-explorer (by denysbutenko)

---

src/app/modules/auth/auth.service.ts

**Changes:**
Changes login status first before clearing subscriptions so the decision to not make `core.unsubscribe` calls can be made based on updated state
**Testing:**
Test login and then logout and check browser console for errors.

NAS-134064 / 25.10 / Changes login status before clearing subscriptions

---

src/app/modules/forms/ix-forms/validators/url-validation.service.spec.ts
src/app/modules/forms/ix-forms/validators/url-validation.service.ts

Result, no validation error:
Original PR: https://github.com/truenas/webui/pull/11530
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134061

NAS-134061 / 25.04-RC.1 / Apps - UI validates `uri` type more strictly than middleware (by AlexKarpov98)

---

src/app/modules/layout/topbar/truenas-logo/truenas-logo.component.scss

Testing:
Original PR: https://github.com/truenas/webui/pull/11558
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134165

NAS-134165 / 25.04-RC.1 / New TrueNAS logo does not sit well in mobile (by AlexKarpov98)

---

src/app/pages/reports-dashboard/reports-dashboard.component.ts

**Testing:**
At the **Reporting > Disks** screen,
**Expected result:** the disk temperature data displayed correctly

NAS-133897 / 25.10 / Add disk reporting temps

---

src/app/services/user.service.ts

**Summary**
In the middleware API the only suitable operator is `~`, which resolved into a Python's `re.match`, which has baked-in logic to find a substring exactly at the beginning of the string. 
So the regular expression pattern consists of:
- `.*` - to workaround limitation of `re.match`, and find a substring at arbitrary index within the string
- `(?i)` - for case insensivity
**Testing:**
1. User ensures that **Disable AD cache** is **checked** at **Credentials > Directory Services > Settings > Advanced Options.** _Note:_ you'll need to spin up a new AD connected machine
3. User types in from a keyboard `Domain Users` or `Domain Admins` into **Datasets > (Choose a dataset)  Permissions** at sidebar **> Edit  > Edit ACL > Owner Group** field
**Expected result:** user is able to set …

NAS-132203 / 25.10 / Changing the owner group of a dataset with an AD group does not work if the AD cache is disabled.

---

src/app/services/user.service.ts

**Summary**
In the middleware API the only suitable operator is `~`, which resolved into a Python's `re.match`, which has baked-in logic to find a substring exactly at the beginning of the string. 
So the regular expression pattern consists of:
- `.*` - to workaround limitation of `re.match`, and find a substring at arbitrary index within the string
- `(?i)` - for case insensivity
**Testing:**
1. User ensures that **Disable AD cache** is **checked** at **Credentials > Directory Services > Settings > Advanced Options.** _Note:_ you'll need to spin up a new AD connected machine
3. User types in from a keyboard `Domain Users` or `Domain Admins` into **Datasets > (Choose a dataset)  Permissions** at sidebar **> Edit  > Edit ACL > Owner Group** field
**Expected result:** user is able to set …

NAS-132203 / 25.04-RC.1 / Changing the owner group of a dataset with an AD group does not work if the AD cache is disabled. (by bvasilenko)

---

src/app/pages/dashboard/services/widget-resources.service.ts
src/app/pages/dashboard/widgets/cpu/widget-cpu-usage-recent/widget-cpu-usage-recent.component.spec.ts
src/app/pages/dashboard/widgets/cpu/widget-cpu-usage-recent/widget-cpu-usage-recent.component.ts

git cherry-pick -x b15a63e5dbf4210a61f470f1c9cce1f6ba69d3b3
git cherry-pick -x 8cf15382e26bd99649f87fe2bd8471d41de961d8
**Changes:**
Remove call to `netdata` endpoint from CPU Recent Usage widget.
**Testing:**
Ensure no regressions. 
Original PR: https://github.com/truenas/webui/pull/11569
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134072

NAS-134072 / 25.04-RC.1 / Remove CPU netdata call from main dashboard (by denysbutenko)

---

src/app/pages/credentials/users/user-api-keys/components/api-key-form/api-key-form.component.spec.ts
src/app/pages/credentials/users/user-api-keys/components/api-key-form/api-key-form.component.ts

**Changes:**
Disables Username field in API keys on edit since it cannot be changed.
Original PR: https://github.com/truenas/webui/pull/11589
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134213

NAS-134213 / 25.04-RC.1 / Disable username in API keys on edit (by undsoft)

---

src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.html
src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.spec.ts
src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.ts

**Testing:**
Install an app (custom or not) and give it a different name.

NAS-134405 / 25.10 / Incorrect name hyperlink in apps

---

src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.html
src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.spec.ts
src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.ts
src/assets/i18n/it.json

git cherry-pick -x 2b1c89cc9ab9f0e73a3bc528f223b65df44a3669
git cherry-pick -x 2b9b106848c8747a68ab8d109885b9e751976838
**Testing:**
Install an app (custom or not) and give it a different name. 
Original PR: https://github.com/truenas/webui/pull/11631
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134405

NAS-134405 / 25.04.0 / Incorrect name hyperlink in apps (by undsoft)

---

src/app/interfaces/bind-ip.interface.ts
src/app/interfaces/smb-config.interface.ts
src/app/pages/services/components/service-smb/service-smb.component.html
src/app/pages/services/components/service-smb/service-smb.component.spec.ts
src/app/pages/services/components/service-smb/service-smb.component.ts

**Changes:**
Adjusts UI to the response schema from middleware. Removes addition to bind_ip choices.
**Testing:**
Test normal function. Set, unset bind_ip for smb config under System -> Services -> Edit Config (SMB)

NAS-134556 / 25.10 / Fix bind_ip for smb service config

---

src/app/interfaces/bind-ip.interface.ts
src/app/interfaces/smb-config.interface.ts
src/app/pages/services/components/service-smb/service-smb.component.html
src/app/pages/services/components/service-smb/service-smb.component.spec.ts
src/app/pages/services/components/service-smb/service-smb.component.ts

git cherry-pick -x c01d3faddf0d662e1ff164d9826780efb6b6f452
git cherry-pick -x 14c81f244ecae7eba8244adb57925e373a8e6446
git cherry-pick -x efb6ef317dca378dd920817ff971c7c3b9dfc2b4
**Changes:**
Adjusts UI to the response schema from middleware. Removes addition to bind_ip choices.
**Testing:**
Test normal function. Set, unset bind_ip for smb config under System -> Services -> Edit Config (SMB)
Original PR: https://github.com/truenas/webui/pull/11663
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134556

NAS-134556 / 25.04.0 / Fix bind_ip for smb service config (by RehanY147)

---

src/app/modules/forms/ix-forms/components/ix-form-glossary/ix-form-glossary.component.ts

Disabled input should not count as invalid.
Result:
https://github.com/user-attachments/assets/f778ea2b-8128-47ac-b3fe-98fd3f401e47

NAS-134566 / 25.10 / Unexpected warning next to Security in Instances

---

src/app/modules/forms/ix-forms/components/ix-form-glossary/ix-form-glossary.component.ts

Disabled input should not count as invalid.
Result:
https://github.com/user-attachments/assets/f778ea2b-8128-47ac-b3fe-98fd3f401e47
Original PR: https://github.com/truenas/webui/pull/11670
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134566

NAS-134566 / 25.04.0 / Unexpected warning next to Security in Instances (by AlexKarpov98)

---

src/app/interfaces/bind-ip.interface.ts
src/app/interfaces/smb-config.interface.ts
src/app/pages/services/components/service-smb/service-smb.component.html
src/app/pages/services/components/service-smb/service-smb.component.spec.ts
src/app/pages/services/components/service-smb/service-smb.component.ts

git cherry-pick -x c01d3faddf0d662e1ff164d9826780efb6b6f452
git cherry-pick -x 14c81f244ecae7eba8244adb57925e373a8e6446
git cherry-pick -x efb6ef317dca378dd920817ff971c7c3b9dfc2b4
**Changes:**
Adjusts UI to the response schema from middleware. Removes addition to bind_ip choices.
**Testing:**
Test normal function. Set, unset bind_ip for smb config under System -> Services -> Edit Config (SMB)
Original PR: https://github.com/truenas/webui/pull/11663
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134556

NAS-134556 / 25.04-RC.1 / Fix bind_ip for smb service config (by RehanY147)

---

src/app/pages/dashboard/services/widget-resources.service.spec.ts
src/app/pages/dashboard/services/widget-resources.service.ts
src/app/pages/dashboard/widgets/apps/widget-app-cpu/widget-app-cpu.component.spec.ts
src/app/pages/dashboard/widgets/apps/widget-app-info/widget-app-info.component.spec.ts
src/app/pages/dashboard/widgets/apps/widget-app-memory/widget-app-memory.component.spec.ts
src/app/pages/dashboard/widgets/apps/widget-app-network/widget-app-network.component.spec.ts
src/app/pages/dashboard/widgets/apps/widget-app/widget-app.component.spec.ts
src/app/pages/dashboard/widgets/system/widget-hostname-active/widget-hostname-active.component.spec.ts
src/app/pages/dashboard/widgets/system/widget-hostname-active/widget-hostname-active.component.ts
src/app/pages/dashboard/widgets/system/widget-hostname-passive/widget-hostname-passive.component.spec.ts
src/app/pages/dashboard/widgets/system/widget-hostname-passive/widget-hostname-passive.component.ts
src/app/pages/dashboard/widgets/system/widget-os-version/widget-os-version.component.spec.ts
src/app/pages/dashboard/widgets/system/widget-os-version/widget-os-version.component.ts
src/app/pages/dashboard/widgets/system/widget-serial-active/widget-serial-active.component.spec.ts
src/app/pages/dashboard/widgets/system/widget-serial-active/widget-serial-active.component.ts
src/app/pages/dashboard/widgets/system/widget-serial-passive/widget-serial-passive.component.spec.ts
src/app/pages/dashboard/widgets/system/widget-serial-passive/widget-serial-passive.component.ts
src/app/pages/dashboard/widgets/system/widget-sys-info-active/widget-sys-info-active.component.spec.ts
src/app/pages/dashboard/widgets/system/widget-sys-info-active/widget-sys-info-active.component.ts
src/app/pages/dashboard/widgets/system/widget-sys-info-passive/widget-sys-info-passive.component.spec.ts
src/app/pages/dashboard/widgets/system/widget-sys-info-passive/widget-sys-info-passive.component.ts
src/app/pages/dashboard/widgets/system/widget-system-image/widget-system-image.component.spec.ts
src/app/pages/dashboard/widgets/system/widget-system-image/widget-system-image.component.ts
src/app/pages/dashboard/widgets/system/widget-system-uptime/widget-system-uptime.component.spec.ts
src/app/pages/dashboard/widgets/system/widget-system-uptime/widget-system-uptime.component.ts
src/app/pages/data-protection/rsync-task/rsync-task-card/rsync-task-card.component.ts

**Summary** 
This is a fix for a network widget chart.
Apart from the main issue with the chart, this PR contains a fix for an additional issue, mentioned in the last line of "Testing" section below ("...status should properly refresh and display **Success**")
**Testing:**
In this scenario user will copy the files from 1st `m40g3-137` machine to 2nd `m50-143a` machine.
1. (Skip first, do later) On 2nd server clean the destination directory in **System \> Shell**
```
rm /mnt/z/iso/*.iso
```
2. On 1st server open and watch the chart at **Dashboard** \> **widget** "**Interface** `eno1np0` **"**
2. On 1st server click **Data Protection \> Rsync Tasks \> `mnt/pewl/iso` item \> "Run job" icon**
3. At the tab opened in pt "2"
1. ensure you can see a traffic peak displayed on 00:13 second of the …

NAS-133011 / 25.10 / Network interface graph on Dashboard does not appear to retain network traffic as seen on Reporting page

---

src/app/modules/forms/ix-forms/components/ix-explorer/ix-explorer.component.ts

**Changes:**
The endpoint we have to load datasets hierarchy only needs to be called once and all datasets are loaded. A recent PR made it so that when loading zvols we reload children when a node is collapsed and expanded again. However, this approach only works for zvols. Doesn't work for datasets and datasets just get loaded again from the root. This will fix that issue so reloading children only happens for zvols and not for datasets.
**Testing:**
See ticket description. Also see the ticket description of https://ixsystems.atlassian.net/browse/NAS-133774 to test that the issue there is still resolved.

NAS-134428 / 25.10 / Only reload explorer node children if going through zvols

---

src/app/modules/forms/ix-forms/components/ix-explorer/ix-explorer.component.ts

**Changes:**
The endpoint we have to load datasets hierarchy only needs to be called once and all datasets are loaded. A recent PR made it so that when loading zvols we reload children when a node is collapsed and expanded again. However, this approach only works for zvols. Doesn't work for datasets and datasets just get loaded again from the root. This will fix that issue so reloading children only happens for zvols and not for datasets.
**Testing:**
See ticket description. Also see the ticket description of https://ixsystems.atlassian.net/browse/NAS-133774 to test that the issue there is still resolved.
Original PR: https://github.com/truenas/webui/pull/11677
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134428

NAS-134428 / 25.04.0 / Only reload explorer node children if going through zvols (by RehanY147)

---

src/app/pages/network/components/configuration/configuration.component.ts

git cherry-pick -x 1ae7c3e34395924a5257cc386a2551764aaa177f
git cherry-pick -x e132f0d8720bf5faae25cbcd18565115cf12445c
You may `.log()` the hostname directly in `private saveDebug(): Observable<Blob> {` to see that it uses latest value.
Original PR: https://github.com/truenas/webui/pull/11711
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134638

NAS-134638 / 25.04.0 / If the browser is not refreshed after changing the hostname, the debug file downloads as the old hostname (by AlexKarpov98)

---

src/app/pages/dashboard/widgets/apps/widget-app-settings/widget-app-settings.component.ts
src/app/pages/dashboard/widgets/custom/arbitrary-text/widget-arbitrary-text-settings/widget-arbitrary-text-settings.component.ts
src/app/pages/dashboard/widgets/network/widget-interface-ip/widget-interface-ip-settings/widget-interface-ip-settings.component.ts
src/app/pages/dashboard/widgets/storage/widget-pool/widget-pool-settings/widget-pool-settings.component.ts

**Testing:**
Please see the ticket for replication steps and expected result.
Original PR: https://github.com/truenas/webui/pull/11524
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133904

NAS-133904 / 25.04.0 / Editing the Network Widget saved the values to the other portion of the widget (by bvasilenko)

---

src/app/pages/dashboard/services/widget-resources.service.spec.ts
src/app/pages/dashboard/services/widget-resources.service.ts
src/app/pages/dashboard/widgets/apps/widget-app-cpu/widget-app-cpu.component.spec.ts
src/app/pages/dashboard/widgets/apps/widget-app-info/widget-app-info.component.spec.ts
src/app/pages/dashboard/widgets/apps/widget-app-memory/widget-app-memory.component.spec.ts
src/app/pages/dashboard/widgets/apps/widget-app-network/widget-app-network.component.spec.ts
src/app/pages/dashboard/widgets/apps/widget-app/widget-app.component.spec.ts
src/app/pages/data-protection/rsync-task/rsync-task-card/rsync-task-card.component.ts

**Summary** 
This is a fix for a network widget chart.
Apart from the main issue with the chart, this PR contains a fix for an additional issue, mentioned in the last line of "Testing" section below ("...status should properly refresh and display **Success**")
**Testing:**
In this scenario user will copy the files from 1st `m40g3-137` machine to 2nd `m50-143a` machine.
1. (Skip first, do later) On 2nd server clean the destination directory in **System \> Shell**
```
rm /mnt/z/iso/*.iso
```
2. On 1st server open and watch the chart at **Dashboard** \> **widget** "**Interface** `eno1np0` **"**
2. On 1st server click **Data Protection \> Rsync Tasks \> `mnt/pewl/iso` item \> "Run job" icon**
3. At the tab opened in pt "2"
1. ensure you can see a traffic peak displayed on 00:13 second of the …

NAS-133011 / 25.04.0 / Network interface graph on Dashboard does not appear to retain network traffic as seen on Reporting page (by bvasilenko)

---

src/app/pages/system/general-settings/save-config-dialog/save-config-dialog.component.spec.ts
src/app/pages/system/general-settings/save-config-dialog/save-config-dialog.component.ts

Changes defaults for `Export Password Secret Seed` in `Save Configuration` dialog.

NAS-134729 / 25.10 / Change defaults for Export Password Secret Seed

---

src/app/pages/system/general-settings/save-config-dialog/save-config-dialog.component.spec.ts
src/app/pages/system/general-settings/save-config-dialog/save-config-dialog.component.ts

Changes defaults for `Export Password Secret Seed` in `Save Configuration` dialog.
Original PR: https://github.com/truenas/webui/pull/11725
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134729

NAS-134729 / 25.04.0 / Change defaults for Export Password Secret Seed (by undsoft)

---

src/app/modules/use-enterprise-marketing-link/use-enterprise-marketing-link.component.html
src/app/modules/use-enterprise-marketing-link/use-enterprise-marketing-link.component.scss

NAS-134842 / 25.10 / Explore TrueNAS Enterprise text vanishes

---

eslint/eslint-ts-rules-extra.mjs
src/app/pages/sharing/smb/smb-form/smb-form.component.spec.ts

**Changes:**
Throwing an Error (or a subclass of Error) is better because it properly preserves stack trace.
Most of the code was already updated for it, but here I enable the relevant linter rule.
**Testing:**
Code review.

NAS-134869 / 25.10 / Enable rxjs/throw-error

---

src/app/pages/apps/components/docker-images/docker-image-delete-dialog/docker-image-delete-dialog.component.ts

**Changes:**
Updated the Force Delete Docker Image tooltip to reflect actual usage.
**Testing:**
N/A
None.

NAS-134734 / 25.10 / Update Force Delete Docker Image tooltip

---

src/app/modules/use-enterprise-marketing-link/use-enterprise-marketing-link.component.html
src/app/modules/use-enterprise-marketing-link/use-enterprise-marketing-link.component.scss

Result:
Original PR: https://github.com/truenas/webui/pull/11743
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134842

NAS-134842 / 25.04.0 / Explore TrueNAS Enterprise text vanishes (by AlexKarpov98)

---

src/app/modules/layout/admin-layout/admin-layout.component.html
src/app/pages/dashboard/widgets/system/widget-sys-info-active/widget-sys-info-active.component.html
src/app/pages/dashboard/widgets/system/widget-sys-info-passive/widget-sys-info-passive.component.html

**Changes:**
Adds tooltip to hostname item in sys-info card
**Testing:**
See that tooltip exists
Original PR: https://github.com/truenas/webui/pull/11731
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134719

NAS-134719 / 25.04.0 / Add tooltip to hostname item in sys-info card (by RehanY147)

---

src/assets/styles/other/_material-overrides.scss

Result:
Original PR: https://github.com/truenas/webui/pull/11739
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134755

NAS-134755 / 25.04.1 / Incorrect snackbar colors on blue theme (by AlexKarpov98)

---

src/app/interfaces/apps-filters-values.interface.ts
src/app/pages/apps/components/available-apps/available-apps-header/available-apps-header.component.ts
src/app/pages/apps/store/apps-filter-store.service.spec.ts
src/app/pages/apps/store/apps-filter-store.service.ts

Result:
**2FA is no longer under `T` letter on sorting:**
Original PR: https://github.com/truenas/webui/pull/11791
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134995

NAS-134995 / 25.04.1 / Sort Apps by title, not by an internal key string (by AlexKarpov98)

---

src/app/helpers/storage.helper.spec.ts
src/app/helpers/storage.helper.ts
src/app/pages/datasets/components/dataset-capacity-management-card/dataset-capacity-management-card.component.html
src/app/pages/datasets/components/dataset-capacity-management-card/dataset-capacity-management-card.component.spec.ts
src/app/pages/datasets/components/dataset-capacity-management-card/dataset-capacity-management-card.component.ts
src/app/pages/datasets/components/dataset-quotas/dataset-quotas-list/dataset-quotas-list.component.ts

git cherry-pick -x 145e160afbd3d28ec65f20dc92d88223cd88d232
git cherry-pick -x 290dc5610ffc375b843b601bb68d5f9f4bf2cc28
git cherry-pick -x 6f99d514b9fa5b079e7eccc1577077605298fd0b
git cherry-pick -x 77b58f20cfaec3367869bf11f3f2f5440c39aa60
git cherry-pick -x c7738f7a1ef61462b3495cabed996b516edf184d
git cherry-pick -x 025a1ab7a22013dcbe5e387e65e5ede7c2211c8a
**Changes:**
Previously Dataset Space Management card would report too many quotas.
Original PR: https://github.com/truenas/webui/pull/11812
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135044

NAS-135044 / 25.04.1 / Too many quotas are reported in Dataset Space Management card (by undsoft)

---

src/app/pages/system/general-settings/email/email-card/email-card.component.html
src/app/pages/system/general-settings/email/email-card/email-card.component.spec.ts

Result:
Before:
Original PR: https://github.com/truenas/webui/pull/11814
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135011

NAS-135011 / 25.04.1 / [BUG] email showing wrong SMTP server than what is configured. (by AlexKarpov98)

---

src/app/pages/audit/audit.component.scss
src/app/pages/audit/components/audit-list/audit-list.component.html
src/app/pages/audit/components/audit-list/audit-list.component.scss
src/app/pages/audit/components/audit-list/audit-list.component.ts
src/app/pages/audit/components/event-data-details-card/event-data-details-card.component.html
src/app/pages/audit/components/event-data-details-card/event-data-details-card.component.spec.ts
src/app/pages/audit/components/event-data-details-card/event-data-details-card.component.ts

it's now easy to see successful and failed operations in a non intrusive way.
Result:

NAS-135110 / 25.10 / Audit Event Data widget should include the success value

---

src/app/modules/dialog/components/general-dialog/general-dialog.component.scss
src/app/pages/storage/modules/disks/components/disk-wipe-dialog/disk-wipe-dialog.component.ts

Result:
https://github.com/user-attachments/assets/5cac5cbf-dab9-45ed-92be-6917a7f48242

NAS-134422 / 25.10 / On Goldeye No close button on the Wipe Disk sd* Disk Wiped successfully dialog

---

src/app/pages/audit/audit.component.scss
src/app/pages/audit/components/audit-list/audit-list.component.html
src/app/pages/audit/components/audit-list/audit-list.component.scss
src/app/pages/audit/components/audit-list/audit-list.component.ts
src/app/pages/audit/components/event-data-details-card/event-data-details-card.component.html
src/app/pages/audit/components/event-data-details-card/event-data-details-card.component.spec.ts
src/app/pages/audit/components/event-data-details-card/event-data-details-card.component.ts

it's now easy to see successful and failed operations in a non intrusive way.
Result:
Original PR: https://github.com/truenas/webui/pull/11833
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135110

NAS-135110 / 25.04.1 / Audit Event Data widget should include the success value (by AlexKarpov98)

---

src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/openstack-swift-provider-form/openstack-swift-provider-form.component.ts

**Changes:**
Removed `tenant_id` as required for OpenStack Swift credentials. The [Rclone doc](https://rclone.org/swift/#swift-tenant) says that at least one of `tenant` (i.e. `tenant_name`) or `tenant_id` is required, but not necessarily `tenant_id`.
Related: https://forums.truenas.com/t/cannot-add-cloud-credentials-because-optional-key-is-required-in-ui/38163

tenant_id should not required for Swift credentials

---

src/app/pages/instances/components/all-instances/instance-details/instance-idmap/instance-idmap.component.html

git cherry-pick -x b59538e29163f4e61351681d7271fb4cc067fbfc
git cherry-pick -x c973ad178bd0901b2423436a430f9b1eeaef3b52
git cherry-pick -x 688467c38ecea592cd590b2b8cd0aac88e02ba42
I was not able to somehow reproduce. For testing you may user the data provided by user in the ticket, to see that page is not broken anymore.
```
"userns_idmap": {
"uid": null,
"gid": null
},
```
Original PR: https://github.com/truenas/webui/pull/11842
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135098

NAS-135098 / 25.04.1 / Instances page UI not loading properly (by AlexKarpov98)

---

src/app/pages/sharing/iscsi/fibre-channel-ports/fibre-channel-ports.component.spec.ts
src/app/pages/sharing/iscsi/fibre-channel-ports/fibre-channel-ports.component.ts

Before:
After:
Original PR: https://github.com/truenas/webui/pull/11863
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134938

NAS-134938 / 25.04.1 / Physical ports in Fibre Channel Ports do not display WWPNs unless target is mapped (by AlexKarpov98)

---

src/app/interfaces/preferences.interface.ts
src/app/modules/ix-table/components/ix-table-columns-selector/ix-table-columns-selector.component.html
src/app/modules/ix-table/components/ix-table-columns-selector/ix-table-columns-selector.component.spec.ts
src/app/modules/ix-table/components/ix-table-columns-selector/ix-table-columns-selector.component.ts
src/app/pages/sharing/nfs/nfs-list/nfs-list.component.html
src/app/pages/sharing/nfs/nfs-list/nfs-list.component.spec.ts
src/app/pages/sharing/smb/smb-list/smb-list.component.html
src/app/pages/sharing/smb/smb-list/smb-list.component.spec.ts
src/app/store/preferences/preferences.actions.ts
src/app/store/preferences/preferences.reducer.ts

p.s _I don't see a reason for a separate service for these updates._
Current possible issue: We only know `title` or `propertyName`, but they are not always available.
maybe we can provide additional key for each column, especially to know how we save that column to the API.
Currently I use title. (so the selection changes when we change the language) 
Result:
https://github.com/user-attachments/assets/1dc7d022-4986-4fd2-b255-5a516273c9aa

NAS-135157 / 25.10 / Remember user selected columns in tables

---

src/app/pages/instances/components/instance-wizard/instance-wizard.component.html

Previously root disk size was hidden when using an existing zvol. This appears to be unnecessary.

NAS-135398 / 25.10 / Allow root disk size to be specified when using zvols

---

src/app/pages/instances/components/instance-wizard/instance-wizard.component.html

git cherry-pick -x 0c9d537020b43bc73d58572c456789529dce0911
git cherry-pick -x 68b862bd417584446d82c139323e048a6ec410da
Previously root disk size was hidden when using an existing zvol. This appears to be unnecessary.
Original PR: https://github.com/truenas/webui/pull/11895
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135398

NAS-135398 / 25.04.1 / Allow root disk size to be specified when using zvols (by undsoft)

---

src/app/pages/data-protection/replication/replication-form/sections/transport-section/transport-section.component.spec.ts
src/app/pages/data-protection/replication/replication-form/sections/transport-section/transport-section.component.ts

**Testing:**
1. Create a replication task that uses SSH connection. You can create an SSH connection to the same system.
2. Check that Compression field can be set to disabled.

NAS-135554 / 25.10 / Fix disabled `Compression` in replication tasks

---

src/app/pages/dashboard/services/widget-resources.service.spec.ts
src/app/pages/dashboard/services/widget-resources.service.ts

**Changes:**
`update.check_available` is to reach out to update servers and check if there is an update, so it doesn't make sense to call it on main dashboard.

NAS-135539 / 25.10 / Incorrect endpoint is used to check for updates

---

src/app/pages/data-protection/replication/replication-form/sections/transport-section/transport-section.component.spec.ts
src/app/pages/data-protection/replication/replication-form/sections/transport-section/transport-section.component.ts

**Testing:**
1. Create a replication task that uses SSH connection. You can create an SSH connection to the same system.
2. Check that Compression field can be set to disabled.
Original PR: https://github.com/truenas/webui/pull/11933
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135554

NAS-135554 / 25.04.1 / Fix disabled `Compression` in replication tasks (by undsoft)

---

src/app/pages/dashboard/services/widget-resources.service.spec.ts
src/app/pages/dashboard/services/widget-resources.service.ts

git cherry-pick -x 9157b9ba77972d5b00179562aa5686be34b64e7c
git cherry-pick -x bce424849f3487c7a1a9a8b0fbb3788e72ed55c1
**Changes:**
`update.check_available` is to reach out to update servers and check if there is an update, so it doesn't make sense to call it on main dashboard.
Original PR: https://github.com/truenas/webui/pull/11932
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135539

NAS-135539 / 25.04.1 / Incorrect endpoint is used to check for updates (by undsoft)

---

src/app/pages/signin/signin.component.ts
src/app/pages/signin/store/signin.store.ts

**Testing:**
Original issue was reproducible by setting login banner in Advanced Settings, logging out and breaking websocket connection.
The expectation is that login banner is still shown after WS connection reestablishes.
For connection to break you can just wait for bit on login page.

NAS-135388 / 25.10 / A banner for STIG disappeared if the system rebooted

---

.github/workflows/require-checklist.yml

**Testing:**
One of the jobs should fails because this checklist item is not done:
The intention is to allow developers to add checklist items to their PR so that they don't forget to do something before merging the PR.

NAS-135771 / 25.10 / Require checklist items to be resolved on PRs

---

src/app/pages/signin/signin.component.spec.ts
src/app/pages/signin/signin.component.ts
src/app/pages/system-tasks/failover/failover.component.ts
src/app/services/websocket-status.service.spec.ts
src/app/services/websocket-status.service.ts

**Changes:**
- Do not show reconnect dialog when system restart was initiated using the Failover button
**Testing:**
- Try to restart system using Initiate Failover button

NAS-135651 / 25.10 / Disable reconnect dialog on failover

---

src/app/pages/credentials/backup-credentials/ssh-connection-form/ssh-connection-form.component.html
src/app/pages/credentials/backup-credentials/ssh-connection-form/ssh-connection-form.component.spec.ts

git cherry-pick -x e7c1876d477de6f8be605189a5bd023db8f2e1bd
git cherry-pick -x ec847eca3da30120e8eef249991bebc63a16a140
git cherry-pick -x 449e0d5306e5f7cbba8d736214de4fe92e7fc492
**Testing:**
See ticket.
Original PR: https://github.com/truenas/webui/pull/12025
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135953

NAS-135953 / 25.04.2 / Input is not a valid integer in SSH form (by undsoft)

---

src/app/pages/system/general-settings/gui/gui-form/gui-form.component.ts

**Changes:**
Removes validators from those fields, because they are coming from choices anyway and current validators create a problem.
**Testing:**
See that you can select and save multiple items in `Web Interface IPv4 Address` in `GUI Settings`.
Middleware error when 0.0.0.0 is something else.

NAS-136000 / 25.10 / Remove validators from IP addresses in GUI form

---

eslint/eslint-ts-rules-extra.mjs
src/app/directives/animate-out/animate-out.directive.spec.ts
src/app/directives/animate-out/animate-out.directive.ts
src/app/directives/new-feature-indicator/new-feature-indicator-wrapper.component.html
src/app/directives/new-feature-indicator/new-feature-indicator-wrapper.component.scss
src/app/directives/new-feature-indicator/new-feature-indicator-wrapper.component.ts
src/app/modules/global-search/components/global-search/global-search.component.spec.ts
src/app/modules/loader/components/fake-progress-bar/fake-progress-bar.component.html
src/app/modules/loader/components/fake-progress-bar/fake-progress-bar.component.scss
src/app/modules/loader/components/fake-progress-bar/fake-progress-bar.component.spec.ts
src/app/modules/loader/components/fake-progress-bar/fake-progress-bar.component.ts
src/app/modules/slide-ins/components/slide-in-container/slide-in-container.component.scss
src/app/modules/slide-ins/components/slide-in-container/slide-in-container.component.ts
src/app/modules/slide-ins/slide-in.spec.ts
src/app/modules/slide-ins/slide-in.ts
src/app/pages/dashboard/components/dashboard/dashboard.component.html
src/app/pages/dashboard/components/dashboard/dashboard.component.scss
src/app/pages/dashboard/components/dashboard/dashboard.component.spec.ts
src/app/pages/dashboard/components/dashboard/dashboard.component.ts
src/app/pages/system/enclosure/components/enclosure-side/enclosure-svg/enclosure-svg.component.html
src/app/pages/system/enclosure/components/enclosure-side/enclosure-svg/enclosure-svg.component.scss
src/app/pages/system/enclosure/components/enclosure-side/enclosure-svg/enclosure-svg.component.ts
src/main.ts
yarn.lock

**Changes:**
Removes @angular/animations as this package is now deprecated.
Adds one replacement helper directive.
Forbids package use in linter.
**Testing:**
Test affected places.

NAS-136456 / 25.10 / Remove @angular/animations

---

src/app/pages/credentials/new-users/all-users/user-details/user-access-card/user-access-card.component.html
src/app/pages/credentials/new-users/all-users/user-details/user-access-card/user-access-card.component.spec.ts
src/app/pages/credentials/new-users/all-users/user-details/user-access-card/user-access-card.component.ts
src/app/pages/credentials/new-users/user-form/additional-details-section/additional-details-section.component.html
src/app/pages/credentials/new-users/user-form/additional-details-section/additional-details-section.component.spec.ts
src/app/pages/credentials/new-users/user-form/additional-details-section/additional-details-section.component.ts
src/assets/ui-searchable-elements.json

**Changes:**
- Since UID cannot be edited, don't show it on the form on edit.
- Remove functionality that updates username when Full Name is changed.
- Fix error: user_create.uid: Input should be a valid integer when specifying UID manually
- Prevent builtin users from being locked, except for root.

NAS-136592 / 25.10 / Various fixes to new users form

---

src/app/interfaces/api/api-call-directory.interface.ts
src/app/interfaces/gpu-pci-choice.interface.ts
src/app/pages/system/advanced/isolated-gpus/isolated-gpus-form/isolated-gpus-form.component.spec.ts
src/app/pages/system/advanced/isolated-gpus/isolated-gpus-form/isolated-gpus-form.component.ts
src/app/pages/vm/vm-edit-form/vm-edit-form.component.spec.ts
src/app/pages/vm/vm-edit-form/vm-edit-form.component.ts
src/app/pages/vm/vm-wizard/steps/6-gpu-step/gpu-step.component.spec.ts
src/app/pages/vm/vm-wizard/steps/6-gpu-step/gpu-step.component.ts
src/app/pages/vm/vm-wizard/vm-wizard.component.spec.ts
src/app/services/gpu/critical-gpu-prevention.service.ts
src/app/services/gpu/gpu-service.spec.ts
src/app/services/gpu/gpu.service.ts

**Changes:**
Make GPUs screen show all available but show a error dialog when selection a system critical one, forbidding selection.
**Testing:**
Have two GPUs in the system, once that cannot be isolated and one that can.
Try select system critical and verify error shows up.

NAS-136784 / 25.10 / Always show all GPUs but forbid selection of critical ones

---

src/app/pages/directory-service/components/directory-services-form/directory-services-form.component.ts

**Changes:**
Add missing TestDirective import to ensure ixTest attributes are properly converted to data-test attributes in the rendered DOM. This makes the save button render with data-test="button-save" attribute, matching the behavior of other forms like the SMB form.
**Testing:**
Inspect save element using developer tools and check data-test="save-button" is there.

NAS-136826 / 25.10 / Add TestDirective to directory services form

---

src/app/services/network.service.spec.ts
src/app/services/network.service.ts

**Changes:**
Check for failover license as well for ha enabled check
**Testing:**
Non-HA system shouldn't warn the user about making changes to network interfaces. They should appear on HA systems when HA is enabled

NAS-136845 / 25.10 / Check for failover license as well for ha enabled check

---

src/app/services/failover-validation.service.spec.ts
src/app/services/failover-validation.service.ts

**Changes:**
Handle sign in after license is applied for HA.
**Testing:**
failover.licensed is True and failover.status is SINGLE
Happens on fresh install and after license is applied.
Original PR: https://github.com/truenas/webui/pull/12314

NAS-136863 / 25.04.2 / handle sign in case when failover status is SINGLE (by william-gr)

---

eslint/eslint-ts-rules-overrides.mjs
src/app/pages/apps/components/app-wizard/app-wizard.component.ts
src/app/services/schema/app-schema.service.spec.ts
src/app/services/schema/app-schema.service.ts

**Changes:**
Make UUID for GPUs work when editing apps.
**Testing:**
Edit apps and select nvidia GPU.

NAS-134152 / 25.10 / use the default value from the schema for hidden fields

---

src/app/core/testing/classes/mock-auth.service.ts
src/app/core/testing/utils/mock-auth.utils.ts
src/app/pages/system/advanced/system-security/system-security-form/system-security-form.component.html
src/app/pages/system/advanced/system-security/system-security-form/system-security-form.component.scss
src/app/pages/system/advanced/system-security/system-security-form/system-security-form.component.spec.ts
src/app/pages/system/advanced/system-security/system-security-form/system-security-form.component.ts

**Changes:**
Add a warning if there are users without 2FA configured when enabling STIG.
**Testing:**
Have admin users without 2FA and enable STIG.
|Documentation   |Warn if there are users with roles and without 2FA
|Testing         |Enabling STIG has new potential dialog

NAS-134499 / 25.10 / Update messaging for admin on STIG

---

src/app/modules/slide-ins/slide-in.spec.ts
src/app/modules/slide-ins/slide-in.ts

**Changes:**
Fix regression on slide in with debug disabled.
**Testing:**
Run a production build and try any slide in form.

NAS-136893 / 25.10 / regression on slide in when debug is disabled

---

src/assets/styles/other/_material-overrides.scss

NAS-136842 / 25.10 / The Shares > iSCSI screen tabs for Targets, Extents, etc Cannot be seen in iXDark theme

---

src/app/interfaces/truenas-connect-config.interface.ts
src/app/modules/layout/topbar/topbar.component.spec.ts
src/app/modules/layout/topbar/topbar.component.ts
src/app/modules/truenas-connect/components/truenas-connect-status-modal/truenas-connect-status-modal.component.spec.ts
src/app/modules/truenas-connect/services/truenas-connect.service.spec.ts
src/app/modules/truenas-connect/truenas-connect-button.component.spec.ts

**Changes:**
- Add `interfaces_ips` field to `TruenasConnectConfig` interface
- Update `hasTncConfig` computed property to check both `ips` and
`interfaces_ips` arrays
- Ensures TrueNAS Connect configuration is considered valid when
either IP source is available
**Testing:**
1. Run this in shell 
`
midclt call tn_connect.update '{"enabled": true, "ips": [IP_ADDRESS], "account_service_base_url": "https://account-service.dev.ixsystems.net/", "leca_service_base_url": "https://dns-service.dev.ixsystems.net/", "tnc_base_url": "https://truenas.connect.dev.ixsystems.net/", "heartbeat_url": "https://heartbeat-service.dev.ixsystems.net/"}'
`
2. TNC icon should appear in topbar

NAS-136899 / 25.10 / Allow "ips" or "interface_ips" in checking for TNC configuration

---

src/app/modules/websocket-debug-panel/components/mock-config/mock-config-form/mock-config-form.component.html
src/app/modules/websocket-debug-panel/components/mock-config/mock-config-form/mock-config-form.component.ts

NAS-136928 / 25.10 / Use `ix-code-editor` instead of `ix-textarea` for mockconfig form

---

src/app/pages/sharing/components/shares-dashboard/smb-card/smb-card.component.ts
src/app/pages/sharing/smb/smb-form/smb-form.component.html
src/app/pages/sharing/smb/smb-form/smb-form.component.spec.ts
src/app/pages/sharing/smb/smb-form/smb-form.component.ts
src/app/pages/sharing/smb/smb-list/smb-list.component.ts

We show purpose first.
But still if user types some external path - we switch to `External` Purpose.
Preview:
https://github.com/user-attachments/assets/a1f0800b-89b4-43ce-8b74-eb7be586cd1a

NAS-136988 / 26.04 / Fix and improve External Share for Goldeye

---

src/app/pages/instances/components/all-instances/all-instances.component.ts

Fix missing translation marker in all-instances.component.ts. I think that can fix it.
**Changes:**
**Testing:**

Fix missing translation marker

---

src/app/modules/forms/ix-forms/components/ix-explorer/explorer-create-dataset/explorer-create-dataset.component.spec.ts
src/app/modules/forms/ix-forms/components/ix-explorer/explorer-create-dataset/explorer-create-dataset.component.ts

Now button is disabled when invalid path provided. 
Original PR: https://github.com/truenas/webui/pull/12382

NAS-136903 / 25.10-RC.1 / Validation Inconsistency in Storage Disk Source Field of Container Form (by AlexKarpov98)

---

src/app/helptext/directory-service/dashboard.ts
src/app/pages/directory-service/directory-services.component.html
src/app/pages/directory-service/directory-services.component.spec.ts
src/app/pages/directory-service/directory-services.component.ts
src/app/pages/directory-service/directory-services.elements.ts
src/assets/ui-searchable-elements.json

**Changes:**
Added tests for each card.
Updated LDAP Card content.
Cleanup.
**Testing:**
See ticket.
Preview:
|Documentation   | LDAP Card changes
Original PR: https://github.com/truenas/webui/pull/12369

NAS-136964 / 25.10-RC.1 / Directory Services summary for LDAP always shows BindDN (by AlexKarpov98)

---

src/app/modules/terminal/components/terminal/terminal.component.html
src/app/modules/terminal/components/terminal/terminal.component.scss
src/app/modules/terminal/components/terminal/terminal.component.spec.ts
src/app/modules/terminal/components/terminal/terminal.component.ts

**Changes:**
- Fixed Reconnect logic.
- Added tests.
- Added loading indication for reconnect action.
**Testing:**
See ticket.
Before:
https://github.com/user-attachments/assets/239cf4af-2899-4ac6-bc92-0dec9459ce65
After:
https://github.com/user-attachments/assets/5d8b6ff4-72bb-4957-a48b-eb689b82d4e0
Original PR: https://github.com/truenas/webui/pull/12393

NAS-135923 / 25.10-RC.1 / Instance shell: the "Reconnect" button does not work after an instance reboot (by AlexKarpov98)

---

.github/workflows/main.yml
Dockerfile
debian/rules
package.json
scripts/setup_prod.js
setup-production-env.js
yarn.lock

- Remove unused @inquirer/prompts dependency
- Consolidate build:prod script by removing redundant setup_prod.js
- Move environment.ts creation logic into setup-production-env.js
- Remove build:prod:aot script (merged into build:prod)
- Update Dockerfile and debian/rules to use simplified build:prod
- Fix JIRA URL in package.json (jira.ixsystems.com → ixsystems.atlassian.net)
**Changes:**
**Testing:**

NAS-137161 / 26.04 / Clean up build scripts and remove unused dependencies

---

.github/workflows/main.yml
Dockerfile
debian/rules
package.json
scripts/setup_prod.js
setup-production-env.js
yarn.lock

- Remove unused @inquirer/prompts dependency
- Consolidate build:prod script by removing redundant setup_prod.js
- Move environment.ts creation logic into setup-production-env.js
- Remove build:prod:aot script (merged into build:prod)
- Update Dockerfile and debian/rules to use simplified build:prod
- Fix JIRA URL in package.json (jira.ixsystems.com → ixsystems.atlassian.net)
**Changes:**
**Testing:**
Original PR: https://github.com/truenas/webui/pull/12410

NAS-137161 / 25.10-RC.1 / Clean up build scripts and remove unused dependencies (by william-gr)

---

src/app/enums/vm.enum.ts
src/app/helptext/vm/devices/device-add-edit.ts
src/app/helptext/vm/vm-wizard/vm-wizard.ts
src/app/interfaces/vm-device.interface.ts
src/app/pages/vm/devices/device-form/device-form.component.html
src/app/pages/vm/devices/device-form/device-form.component.scss
src/app/pages/vm/devices/device-form/device-form.component.spec.ts
src/app/pages/vm/devices/device-form/device-form.component.ts
src/app/pages/vm/devices/device-list/device-delete-modal/device-delete-modal.component.html
src/app/pages/vm/devices/device-list/device-delete-modal/device-delete-modal.component.spec.ts
src/app/pages/vm/devices/device-list/device-delete-modal/device-delete-modal.component.ts
src/app/pages/vm/devices/device-list/device-list/device-list.component.ts
src/app/pages/vm/vm-list.component.ts
src/app/pages/vm/vm-wizard/steps/1-os-step/os-step.component.html
src/app/pages/vm/vm-wizard/steps/1-os-step/os-step.component.spec.ts
src/app/pages/vm/vm-wizard/steps/1-os-step/os-step.component.ts
src/app/pages/vm/vm-wizard/vm-wizard.component.spec.ts
src/app/pages/vm/vm-wizard/vm-wizard.component.ts
src/app/services/vm.service.ts

git cherry-pick -x 0cfbcea3120fb66d52e84bc0748269a527c3753d
git cherry-pick -x 9d233ee78eda48a6d7425f9e5ed40929d1d136c1
git cherry-pick -x 0041bdfaeffbf89306fd5f1a591ba0fa25ad7b6f
**Changes:**
* VNC display configuration now available in the VM wizard as well as "Add Device" form.
* SPICE display configuration has been removed from the VM wizard (still available via Add Device form).
* One SPICE display and one VNC display can be configured simultaneously.
**Testing:**
* Create a VM and configure a VNC display. Use your preferred VNC client to connect.
* After VM creation, verify that an …

NAS-137185 / 25.10-BETA.1 / add UI support for VNC to VM feature (by aervin)

---

src/app/modules/theme/theme.constants.ts
src/app/pages/system/general-settings/gui/gui-card/gui-card.component.html
src/app/pages/system/general-settings/gui/gui-card/gui-card.component.spec.ts
src/app/pages/system/general-settings/gui/gui-card/gui-card.component.ts
src/app/pages/system/general-settings/gui/gui-form/gui-form.component.spec.ts

**Changes:**
- removed `iX` in the theme labels
**Testing:**

NAS-137176 / 26.04 / renamed dark and blue theme labels

---

src/app/pages/credentials/certificates-dash/csr-add/steps/csr-import/csr-import.component.spec.ts
src/app/pages/credentials/certificates-dash/csr-add/steps/csr-import/csr-import.component.ts
src/app/pages/credentials/certificates-dash/import-certificate/import-certificate.component.spec.ts
src/app/pages/credentials/certificates-dash/import-certificate/import-certificate.component.ts
src/app/pages/credentials/certificates-dash/utils/normalize-certificate.utils.spec.ts
src/app/pages/credentials/certificates-dash/utils/normalize-certificate.utils.ts

**Testing:** 
see ticket and use CSR and Private key from the Comment here -> https://ixsystems.atlassian.net/browse/NAS-137150?focusedCommentId=317319
The form should be submitted successfully now.
Added more tests + util method.
Original PR: https://github.com/truenas/webui/pull/12423

NAS-137150 / 25.10-RC.1 / Private Key and Passphrase Validation Errors when Importing CSR (by AlexKarpov98)

---

src/app/helptext/storage/volumes/pool-creation/pool-creation.ts
src/app/pages/storage/modules/pool-manager/store/pool-manager-validation.service.spec.ts
src/app/pages/storage/modules/pool-manager/store/pool-manager-validation.service.ts

**Changes:**
During add VDEV workflow, adds warnings about special and dedup VDEVs lacking redundancy.
**Testing:**
* Create a pool
* Navigate to that pool's "Add VDEV" workflow.
* Verify that adding special or dedup VDEVs without redundancy results in a red warning message.

NAS-137241 / 26.04 / warn users about adding special/dedup VDEVs with no redundancy

---

src/app/modules/ix-table/classes/base-data-provider.ts
src/app/pages/vm/vm-list.component.ts

Fixed sorting for all VM fields.
Preview:
https://github.com/user-attachments/assets/9d40d83d-9c03-4dce-95bf-70289b12acea
Original PR: https://github.com/truenas/webui/pull/12454

NAS-137154 / 25.10-RC.1 / Sorting on Display Port not proper (by AlexKarpov98)

---

src/app/helptext/system/advanced.ts

NAS-137230 / 26.04 / Fix misleading help text for Show Text Console without Password Prompt

---

src/app/helptext/system/advanced.ts

Preview:
Original PR: https://github.com/truenas/webui/pull/12462

NAS-137230 / 25.10-RC.1 / Fix misleading help text for Show Text Console without Password Prompt (by AlexKarpov98)

---

src/app/pages/vm/vm-list.component.html
src/app/pages/vm/vm-list.component.spec.ts

Now VM list remembers column state.
https://github.com/user-attachments/assets/70662903-996d-4830-a4e3-a5868dccac5a
Original PR: https://github.com/truenas/webui/pull/12455

NAS-137291 / 25.10-RC.1 / VM list does not remember column state (by AlexKarpov98)

---

src/app/enums/api.enum.ts
src/app/enums/system-update.enum.ts
src/app/pages/system/update/update.component.html
src/app/pages/system/update/update.component.spec.ts
src/app/pages/system/update/update.component.ts

- Add NetworkActivityDisabled to UpdateCode enum for identifying disabled network status
- Add NoNetwork (ENONET) and Fault (EFAULT) to ApiErrorName enum
- Implement handleApiError method to silently handle ENONET errors without showing error dialogs
- Display user-friendly message "Network activity has been administratively disabled for update operation. Please use Manual Update." when network is disabled
- Hide error field when status code is NETWORK_ACTIVITY_DISABLED
- Add comprehensive test coverage for network disabled status and error handling scenarios
**Changes:**
**Testing:**
Disable network activity for update in Network global settings and navigate to update page.
You will need middleware changes committed today.
Websocket debug panel wont work because it cant mock error …

NAS-137088 / 26.04 / Handle network activity disabled status in update page

---

src/app/enums/api.enum.ts
src/app/enums/system-update.enum.ts
src/app/pages/system/update/update.component.html
src/app/pages/system/update/update.component.spec.ts
src/app/pages/system/update/update.component.ts

- Add NetworkActivityDisabled to UpdateCode enum for identifying disabled network status
- Add NoNetwork (ENONET) and Fault (EFAULT) to ApiErrorName enum
- Implement handleApiError method to silently handle ENONET errors without showing error dialogs
- Display user-friendly message "Network activity has been administratively disabled for update operation. Please use Manual Update." when network is disabled
- Hide error field when status code is NETWORK_ACTIVITY_DISABLED
- Add comprehensive test coverage for network disabled status and error handling scenarios
**Changes:**
**Testing:**
Disable network activity for update in Network global settings and navigate to update page.
You will need middleware changes committed today.
Websocket debug panel wont work because it cant mock error …

NAS-137088 / 25.10-RC.1 / Handle network activity disabled status in update page (by william-gr)

---

src/app/enums/virtualization.enum.ts
src/app/pages/instances/components/all-instances/all-instances-header/all-instances-header.component.spec.ts
src/app/pages/instances/components/all-instances/all-instances-header/all-instances-header.component.ts
src/app/pages/instances/components/all-instances/instance-details/instance-disks/instance-disk-form/instance-disk-form.component.ts
src/app/pages/instances/components/common/volumes-dialog/volumes-dialog.component.html
src/app/pages/instances/components/common/volumes-dialog/volumes-dialog.component.spec.ts
src/app/pages/instances/components/common/volumes-dialog/volumes-dialog.component.ts

**Changes:**
- Removed logic related to VM in Volumes dialog if no VMs provided
https://github.com/user-attachments/assets/5261ffd3-316e-40d2-b144-b4ab0a4bc1e9
**Testing:**
Containers -> Manage Volumes should not show the buttons related to ISO management if no VM provided: Upload and Import.
|Documentation   | Removed logic related to VM in Volumes dialog if no VMs provided

NAS-137215 / 26.04 / Clean up Containers screen areas that are specific to the disabled VMs area

---

src/app/modules/websocket-debug-panel/components/mock-config/mock-config-form/mock-config-form.component.html
src/app/modules/websocket-debug-panel/components/mock-config/mock-config-form/mock-config-form.component.spec.ts
src/app/modules/websocket-debug-panel/components/mock-config/mock-config-form/mock-config-form.component.ts
src/app/modules/websocket-debug-panel/components/mock-config/mock-config-list/mock-config-list.component.html
src/app/modules/websocket-debug-panel/components/mock-config/mock-config-list/mock-config-list.component.scss
src/app/modules/websocket-debug-panel/components/mock-config/mock-config-list/mock-config-list.component.spec.ts
src/app/modules/websocket-debug-panel/components/mock-config/mock-config-list/mock-config-list.component.ts
src/app/modules/websocket-debug-panel/interfaces/mock-config.interface.ts
src/app/modules/websocket-debug-panel/services/mock-response.service.spec.ts
src/app/modules/websocket-debug-panel/services/mock-response.service.ts
src/app/modules/websocket-debug-panel/store/websocket-debug.effects.spec.ts
src/app/modules/websocket-debug-panel/store/websocket-debug.effects.ts
src/app/modules/websocket-debug-panel/store/websocket-debug.reducer.spec.ts
src/app/modules/websocket-debug-panel/store/websocket-debug.selectors.spec.ts
src/app/services/enclosure-mock.service.integration.spec.ts
src/app/services/enclosure-mock.service.spec.ts
src/app/services/enclosure-mock.service.ts

Implement support for mocking error responses in addition to successful responses in the WebSocket debug panel, allowing developers to test error handling scenarios.
- Changed `MockResponse` from a simple interface to a discriminated union type with `MockSuccessResponse` and `MockErrorResponse` variants
- Added support for JSON-RPC error structure with code, message, and optional data fields
- Updated `MockResponseService` to generate proper `ErrorResponse` objects when configured with error type
- Added response type selector (Success/Error) in mock configuration form
- Implemented dynamic form fields based on selected response type:
- Success: Shows JSON response data field
- Error: Shows error code, message, and optional data fields
- Added combobox for error code selection with …

NAS-137348 / 26.04 / Add error response mocking support to WebSocket debug panel

---

src/app/pages/credentials/backup-credentials/ssh-connection-form/ssh-connection-form.component.spec.ts
src/app/pages/credentials/backup-credentials/ssh-connection-form/ssh-connection-form.component.ts
src/app/pages/credentials/backup-credentials/ssh-keypair-card/ssh-keypair-card.component.spec.ts
src/app/pages/credentials/backup-credentials/ssh-keypair-card/ssh-keypair-card.component.ts
src/app/services/keychain-credential.service.spec.ts
src/app/services/keychain-credential.service.ts

**Changes:**
- The auto-generated SSH keypair should be displayed immediately after creating a new SSH connection.
https://github.com/user-attachments/assets/afdcba50-ec2a-4879-a898-1d9481fe3565
**Testing:**
1. Navigate to Credentials -> Backup Credentials
2. Click `Add` button in SSH Connection
3. Fill out and submit the form
4. If `Generate New` is selected as Private Key, it will immediately update the list of SSH Keypairs after form submission

NAS-137360 / 26.04 / auto-generated SSH Keypair should be displayed on new SSH Connection creation

---

src/app/pages/sharing/nvme-of/ports/port-form/port-form.component.html
src/app/pages/sharing/nvme-of/ports/port-form/port-form.component.spec.ts
src/app/pages/sharing/nvme-of/ports/port-form/port-form.component.ts

**Changes:**
**Testing:**
Try to add nvme Port with a TCP port.
|Documentation   |Port no longer required
|Testing         |Test without and with port

NAS-137395 / 26.04 / Do not require Port in NVMe-oF and show 4420 as placeholder

---

src/app/interfaces/advanced-config.interface.ts
src/app/pages/system/advanced/syslog/syslog-card/syslog-card.component.html
src/app/pages/system/advanced/syslog/syslog-card/syslog-card.component.spec.ts
src/app/pages/system/advanced/syslog/syslog-card/syslog-card.component.ts
src/app/pages/system/advanced/syslog/syslog-form/syslog-form.component.html
src/app/pages/system/advanced/syslog/syslog-form/syslog-form.component.scss
src/app/pages/system/advanced/syslog/syslog-form/syslog-form.component.spec.ts
src/app/pages/system/advanced/syslog/syslog-form/syslog-form.component.ts
src/assets/ui-searchable-elements.json

- Replace single syslogserver with array of up to 2 syslog servers
- Each server can have its own host, transport, and TLS certificate settings
- Add dynamic form controls for adding/removing syslog servers
- Allow configuration with zero syslog servers (disabled state)
- Convert TLS certificate select values to integers for proper API compatibility
- Add conditional validation requiring TLS certificate when transport is TLS
- Improve UX with server count indicators (1/2, 2/2) and limit messaging
- Add ARIA labels for accessibility on dynamic form elements
- Create helper function for FormArray length testing to work around Jest/ngneat incompatibility
- Add comprehensive test coverage for multi-server scenarios
- Use FormArray.clear() instead of while loop for better performance
- Make …

NAS-137315 / 26.04 / Refactor syslog configuration to support multiple servers

---

src/app/interfaces/advanced-config.interface.ts
src/app/pages/system/advanced/syslog/syslog-card/syslog-card.component.html
src/app/pages/system/advanced/syslog/syslog-card/syslog-card.component.spec.ts
src/app/pages/system/advanced/syslog/syslog-card/syslog-card.component.ts
src/app/pages/system/advanced/syslog/syslog-form/syslog-form.component.html
src/app/pages/system/advanced/syslog/syslog-form/syslog-form.component.scss
src/app/pages/system/advanced/syslog/syslog-form/syslog-form.component.spec.ts
src/app/pages/system/advanced/syslog/syslog-form/syslog-form.component.ts
src/assets/ui-searchable-elements.json

- Replace single syslogserver with array of up to 2 syslog servers
- Each server can have its own host, transport, and TLS certificate settings
- Add dynamic form controls for adding/removing syslog servers
- Allow configuration with zero syslog servers (disabled state)
- Convert TLS certificate select values to integers for proper API compatibility
- Add conditional validation requiring TLS certificate when transport is TLS
- Improve UX with server count indicators (1/2, 2/2) and limit messaging
- Add ARIA labels for accessibility on dynamic form elements
- Create helper function for FormArray length testing to work around Jest/ngneat incompatibility
- Add comprehensive test coverage for multi-server scenarios
- Use FormArray.clear() instead of while loop for better performance
- Make …

NAS-137315 / 25.10-RC.1 / Refactor syslog configuration to support multiple servers (by william-gr)

---

src/app/pages/vm/vm-list.component.spec.ts
src/app/pages/vm/vm-list.component.ts

Code review should be enough.
It's hard to reproduce the bug actually.
The issue described:
`this.vmMap.set(vmId, { ...this.vmMap.get(vmId), ...updatedVm });`
This line is using object spread to merge the existing VM data with the updated data. However, if the
devices array is not included in the updatedVm (which is likely the case for partial updates), the
existing devices array will be lost when the spread operation occurs.
The issue is that when partial VM updates come through (like state changes), the devices property might
not be included, causing the display port information to disappear until a full refresh happens.
Original PR: https://github.com/truenas/webui/pull/12483

NAS-137321 / 25.10-RC.1 / Display Port not displayed when you expand "Name" on Virtual Machines (by AlexKarpov98)

---

src/app/pages/system/advanced/isolated-gpus/isolated-gpus-form/isolated-gpus-form.component.spec.ts
src/app/pages/vm/vm-edit-form/vm-edit-form.component.spec.ts
src/app/pages/vm/vm-edit-form/vm-edit-form.component.ts
src/app/pages/vm/vm-wizard/steps/6-gpu-step/gpu-step.component.spec.ts
src/app/pages/vm/vm-wizard/vm-wizard.component.spec.ts
src/app/services/gpu/critical-gpu-prevention.service.spec.ts
src/app/services/gpu/critical-gpu-prevention.service.ts
src/app/services/gpu/gpu-service.spec.ts
src/app/services/gpu/gpu.service.ts

vm.bootloader_options was being called twice and
system.advanced.get_gpu_pci_choices called three times on VM edit form.
**Changes:**
**Testing:**
Open VM Edit form and verify how many websockets calls are being made.

NAS-137426 / 26.04 / Avoid calling same API calls multiple times

---

src/app/interfaces/api/api-call-directory.interface.ts
src/app/interfaces/api/api-job-directory.interface.ts
src/app/interfaces/vm-device.interface.ts
src/app/pages/vm/devices/device-list/device-list/device-list.component.html
src/app/pages/vm/devices/device-list/device-list/device-list.component.spec.ts
src/app/pages/vm/devices/device-list/device-list/device-list.component.ts
src/app/pages/vm/devices/device-list/export-disk-dialog/export-disk-dialog.component.html
src/app/pages/vm/devices/device-list/export-disk-dialog/export-disk-dialog.component.scss
src/app/pages/vm/devices/device-list/export-disk-dialog/export-disk-dialog.component.spec.ts
src/app/pages/vm/devices/device-list/export-disk-dialog/export-disk-dialog.component.ts
src/app/pages/vm/vm-wizard/steps/3-disk-step/disk-step.component.html
src/app/pages/vm/vm-wizard/steps/3-disk-step/disk-step.component.spec.ts
src/app/pages/vm/vm-wizard/steps/3-disk-step/disk-step.component.ts
src/app/pages/vm/vm-wizard/vm-wizard.component.html
src/app/pages/vm/vm-wizard/vm-wizard.component.ts

Implement disk image import during VM creation with support for qcow2, qed, raw, vdi, vhdx, and vmdk formats. Add server-side file browser, format validation, progress dialogs, and automatic cleanup on failure. Add export functionality to convert VM disks to portable image files with format selection and job tracking. Include comprehensive test coverage (22 tests) and proper error handling for both features.
**Changes:**
https://github.com/user-attachments/assets/8705a7d1-245c-4f6f-8eef-756bd9173e58
https://github.com/user-attachments/assets/11360188-4ecd-4f71-9ee4-0b380c775cf9
**Testing:**
Create a VM importing image and export a disk to image.
|Documentation   |New feature to import/export image
|Testing …

NAS-137335 / 25.10-RC.1 / Add VM disk image import/export functionality (by william-gr)

---

src/app/modules/pipes/network-speed/network-speed.pipe.spec.ts
src/app/modules/pipes/network-speed/network-speed.pipe.ts
src/app/pages/apps/components/installed-apps/app-row/app-row.component.spec.ts
src/app/pages/dashboard/widgets/apps/common/app-network-info/app-network-info.component.spec.ts
src/app/pages/dashboard/widgets/network/widget-interface/widget-interface.component.spec.ts

The idea: more appropriate abbreviation should be capital 'B' (B/s, kB/s, MB/s)

NAS-137428 / 26.04 / Applications Network reporting bytes vs bits

---

src/app/modules/pipes/network-speed/network-speed.pipe.spec.ts
src/app/modules/pipes/network-speed/network-speed.pipe.ts
src/app/pages/apps/components/installed-apps/app-row/app-row.component.spec.ts
src/app/pages/dashboard/widgets/apps/common/app-network-info/app-network-info.component.spec.ts
src/app/pages/dashboard/widgets/network/widget-interface/widget-interface.component.spec.ts

The idea: more appropriate abbreviation should be capital 'B' (B/s, kB/s, MB/s)
Original PR: https://github.com/truenas/webui/pull/12526

NAS-137428 / 25.10-RC.1 / Applications Network reporting bytes vs bits (by AlexKarpov98)

---

src/app/pages/system/enclosure/components/pages/enclosure-page/enclosure-page.component.scss
src/app/pages/system/enclosure/components/pages/enclosure-page/enclosure-selector/enclosure-selector.component.scss

After https://github.com/truenas/webui/pull/12567 is merged - enclosure mock will work.
Result:
Now rendered properly, full size.
https://github.com/user-attachments/assets/faa9d799-acfc-4ff7-a00e-acb180a4f3ca
Original PR: https://github.com/truenas/webui/pull/12566

NAS-137604 / 25.10-RC.1 / Enclosure preview & main view does not fit properly (by AlexKarpov98)

---

src/app/pages/system/enclosure/components/pages/enclosure-page/enclosure-page.component.scss
src/app/pages/system/enclosure/components/pages/enclosure-page/enclosure-selector/enclosure-selector.component.scss

After https://github.com/truenas/webui/pull/12567 is merged - enclosure mock will work.
Result:
Now rendered properly, full size.
https://github.com/user-attachments/assets/faa9d799-acfc-4ff7-a00e-acb180a4f3ca
Original PR: https://github.com/truenas/webui/pull/12566

NAS-137604 / 25.10.0 / Enclosure preview & main view does not fit properly (by AlexKarpov98)

---

src/app/pages/credentials/users/user-form/auth-section/auth-section.component.html
src/app/pages/credentials/users/user-form/auth-section/auth-section.component.scss
src/app/pages/credentials/users/user-form/auth-section/auth-section.component.spec.ts
src/app/pages/credentials/users/user-form/auth-section/auth-section.component.ts

git cherry-pick -x 734153f3456c821c69ef756d042cf45a53bb81f3
git cherry-pick -x 57efaab806aad14136b2ad4d1ac8bb5c039c2b1a
git cherry-pick -x 664c3664665ca6047171f33ab6d7bf56494f8d05
git cherry-pick -x b769964bdab0cdc1845f22f65de0babdc3cbb442
No validation was present for SSH checkbox logic. Now it's added and form works as expected. Tests added.
Preview:
https://github.com/user-attachments/assets/6c3996f5-8797-40c6-a196-d8a4265965ce
Original PR: https://github.com/truenas/webui/pull/12584

NAS-137646 / 25.10.0 / User UI: Enabling SSH access does not save although the text says that the user was updated (by AlexKarpov98)

---

src/app/modules/master-detail-view/master-detail-view.component.html
src/app/pages/datasets/components/dataset-details-panel/dataset-details-panel.component.html

Not sure why there is no lint error for such cases.
`(close)` instead of `(closed)` used

NAS-137661 / 26.04 / User UI: Back button is not working

---

src/app/modules/master-detail-view/master-detail-view.component.html
src/app/pages/datasets/components/dataset-details-panel/dataset-details-panel.component.html

Not sure why there is no lint error for such cases.
`(close)` instead of `(closed)` used 
Original PR: https://github.com/truenas/webui/pull/12585

NAS-137661 / 25.10-RC.1 / User UI: Back button is not working (by AlexKarpov98)

---

src/app/helptext/system/2fa.ts
src/app/modules/auth/auth.service.ts
src/app/modules/auth/blocking-action-guard.service.spec.ts
src/app/modules/auth/blocking-action-guard.service.ts
src/app/pages/credentials/users/all-users/user-details/user-access-card/user-access-card.component.html
src/app/pages/credentials/users/all-users/user-details/user-access-card/user-access-card.component.scss
src/app/pages/credentials/users/all-users/user-details/user-access-card/user-access-card.component.spec.ts
src/app/pages/credentials/users/all-users/user-details/user-access-card/user-access-card.component.ts
src/app/pages/credentials/users/two-factor-setup-dialog/two-factor-setup-dialog.component.html
src/app/pages/credentials/users/two-factor-setup-dialog/two-factor-setup-dialog.component.scss
src/app/pages/credentials/users/two-factor-setup-dialog/two-factor-setup-dialog.component.ts
src/app/pages/system/advanced/global-two-factor-auth/global-two-factor-form/global-two-factor-form.component.ts
src/app/pages/two-factor-auth/two-factor.component.html
src/app/pages/two-factor-auth/two-factor.component.scss
src/app/pages/two-factor-auth/two-factor.component.spec.ts
src/app/pages/two-factor-auth/two-factor.component.ts

- Make 2FA setup optional instead of mandatory
* Add "Skip Setup" button with confirmation dialog to 2FA setup screen
* Users can now choose to skip 2FA setup and proceed without it
* Updated warning messages to reflect that 2FA is recommended, not required
- Add "Unset 2FA Secret" functionality
* Add warning-level button to remove existing 2FA configuration
* Calls user.unset_2fa_secret API with username
* Shows confirmation dialog before removing 2FA
- Fix 2FA dialog showing on every navigation
* Dialog now shows only once per session after login
* Added hasCheckedTwoFactorSetup flag to track if dialog was shown
* Resets properly on logout for next session
- Remove admin bypass for /system/* routes
* Admins now see 2FA setup dialog like all other users
* Ensures consistent security …

NAS-137692 / 26.04 / Make 2FA setup optional and add unset functionality

---

src/app/modules/ix-table/components/ix-table-head/ix-table-head.component.html

**Changes:**
the sorting direction indicator (up or down arrow) was backwards in our sorting menu. when sorting in ascending order, the arrow should point upwards and the items should be ordered low-to-high. when sorting in descending order, the arrow should point downwards and the items should be ordered high-to-low.
**Testing:**
1. navigate to any page with a sortable table view. (the ticket mentions the snapshots view, but the jobs view works just as well)
2. observe that the arrow points upwards when the smallest items are first, and downwards when the largest items are first. 

NAS-137674 / 26.04 / fix: reverse sorting arrow; up means ascending, down means descending

---

src/app/pages/datasets/modules/snapshots/snapshot-batch-delete-dialog/snapshot-batch-delete-dialog.component.html
src/app/pages/datasets/modules/snapshots/snapshot-batch-delete-dialog/snapshot-batch-delete-dialog.component.scss
src/app/pages/datasets/modules/snapshots/snapshot-batch-delete-dialog/snapshot-batch-delete-dialog.component.spec.ts
src/app/pages/datasets/modules/snapshots/snapshot-batch-delete-dialog/snapshot-batch-delete-dialog.component.ts

**Changes:**
- disable the button when deletion starts
- show the loader during the process.
**Testing:**
https://github.com/user-attachments/assets/660aea1b-3d72-41ac-a807-779b21796cb0

NAS-137688 / 26.04 / fix errors in deleting bulk snapshots

---

src/app/modules/ix-tree/components/tree/tree.component.ts
src/app/modules/ix-tree/flat-tree-datasource.ts
src/app/modules/ix-tree/tree-control.factory.spec.ts
src/app/modules/ix-tree/tree-control.factory.ts
src/app/modules/ix-tree/tree-datasource.ts
src/app/modules/ix-tree/tree-expansion.interface.ts
src/app/modules/ix-tree/tree-flattener.ts
src/app/pages/datasets/components/dataset-management/dataset-management.component.ts
src/app/pages/storage/modules/pool-manager/components/manual-disk-selection/components/manual-selection-disks/manual-selection-disks.component.ts
src/app/pages/storage/modules/vdevs/components/vdevs-list/vdevs-list.component.ts
src/app/pages/storage/modules/vdevs/components/zfs-info-card/zfs-info-card.component.ts
src/app/pages/system/bootenv/bootenv-status/bootenv-status.component.html
src/app/pages/system/bootenv/bootenv-status/bootenv-status.component.ts

Address TreeControl deprecation warnings by creating an abstraction layer that centralizes usage of deprecated classes in a single location.
- Create TreeExpansion interface to abstract tree control functionality
- Create factory functions (createFlatTreeControl/createNestedTreeControl) to encapsulate deprecated FlatTreeControl and NestedTreeControl usage
- Update ix-tree module components to use TreeExpansion interface
- Update consuming components (datasets, vdevs, bootenv, pool-manager) to use factory functions instead of direct instantiation
- Add comprehensive test coverage for factory functions (19 tests)
- Fix bootenv-status component rendering tree before dataSource initialized
- Fix zfs-info-card null pointer when topologyParentItem is not provided
Angular CDK deprecated …

NAS-137843 / 26.04 / Isolate deprecated Angular CDK TreeControl usage

---

src/app/pages/system/update/update.component.html

**Changes:**
Do not show summary/release notes url if there is a proper markdown release notes available.
**Testing:**
Try page with and without release notes url and with release notes.

NAS-137781 / 26.04 / Do not show update summary if there is a release notes

---

src/app/pages/credentials/certificates-dash/acmedns-form/acmedns-form.component.html
src/app/pages/credentials/certificates-dash/acmedns-form/acmedns-form.component.scss
src/app/pages/credentials/certificates-dash/acmedns-form/acmedns-form.component.spec.ts
src/app/pages/credentials/certificates-dash/acmedns-form/acmedns-form.component.ts
src/app/pages/credentials/certificates-dash/acmedns-form/cloudflare-auth.validator.spec.ts
src/app/pages/credentials/certificates-dash/acmedns-form/cloudflare-auth.validator.ts

I moved the validator into it's own file [`cloudflare-auth.validator.ts`] with tests, so that the main form is not overloaded.
Preview:
https://github.com/user-attachments/assets/4cfde877-28e2-4117-9bc5-15676dfb6eb9

NAS-137665 / 26.04 / Credentials/ACME DNS-Auth: Validation messages appear as errors after attempting to save the form

---

.claude/settings.local.json
src/app/pages/credentials/groups/group-form/group-form.component.html
src/app/pages/credentials/groups/group-form/group-form.component.spec.ts
src/app/pages/credentials/users/all-users/user-details/user-access-card/user-access-card.component.html
src/app/pages/credentials/users/all-users/user-details/user-access-card/user-access-card.component.spec.ts
src/app/pages/credentials/users/all-users/user-details/user-access-card/user-access-card.component.ts
src/app/pages/credentials/users/user-form/additional-details-section/additional-details-section.component.html
src/app/pages/credentials/users/user-form/additional-details-section/additional-details-section.component.spec.ts
src/app/pages/credentials/users/user-form/additional-details-section/additional-details-section.component.ts
src/assets/styles/other/_material-reduction.scss

We should no longer see mixed cased text for SSH.
As well improved text when `ALL`  sudo commands are allowed to be shown as `All` for users - with translations available.

NAS-137815 / 26.04 / User UI: SSH access field are mixed Cased

---

src/app/interfaces/api/api-event-directory.interface.ts
src/app/pages/data-protection/snapshot-task/snapshot-task-list/snapshot-task-list.component.spec.ts
src/app/pages/data-protection/snapshot-task/snapshot-task-list/snapshot-task-list.component.ts

**Changes:**
* previously, the snapshot tasks page only updated once when first opened or when a UI element was added.
* this fix subscribes to `pool.snapshottask.query` and calls `getSnapshotTasks` when receiving an event.
**Testing:**
here are the testing instructions directly from the ticket, modified to note the expected and observed behavior:
1.  Configure a new Periodic Snapshot Task from Data Protection page  (Note: if edit a previously configured Snapshot that was successfully Finished, it doesn’t always get updated to Pending state so may not see the issue without creating a new task)
* For ease, set the Schedule to “Custom” and enter any time within the next few minutes to execute.  Select any dataset and leave all other parameters at default.  Save.
2. Monitor the Periodic …

NAS-137694 / 26.04 / fix: update on `pool.snapshottask.query`

---

src/app/pages/credentials/users/user-form/auth-section/auth-section.component.ts
src/app/pages/credentials/users/user-form/user-form.component.ts

The Fix
Changed both locations to use getRawValue() instead of .value:
- auth-section.component.ts:87 - Store updates now use getRawValue() to capture password even when field is
disabled
- user-form.component.ts:102-105 - Form submission now uses getRawValue() on all form sections
This ensures the password value is always captured and sent to the API, regardless of the disabled state of
the form controls.
Before:
https://github.com/user-attachments/assets/099bed6f-5527-4b0a-ace2-0641d48c752b
After:
https://github.com/user-attachments/assets/6e27112c-bf49-42f5-a665-bda91de419fa
Original PR: https://github.com/truenas/webui/pull/12651

NAS-137883 / 25.10.0 / Users page: unexpected behavior during account edit that prevents password enable. (by AlexKarpov98)

---

src/app/pages/data-protection/replication/replication-form/sections/transport-section/transport-section.component.spec.ts
src/app/pages/data-protection/replication/replication-form/sections/transport-section/transport-section.component.ts

**Changes:**
previously on the replication page, the speed limit would be submitted as an empty string which would cause an `EINVAL` error from the API when editing a replication task. this PR sends `null` if the speed limit is empty, which is what the API is expecting. this PR also changes a test to expect `speed_limit` to always be on the form's value and adds a test to validate whether or not `null` is actually submitted when the field is empty.
**Testing:**
1. set up a TrueNAS SSH replication task on the `data-protection/replication` page. the best way to do this is just to create two local datasets and SSH replicate one of them to the other. 
2. input the "Limit" field as empty. observe that the task saves correctly.
3. input the "Limit" field as some arbitrary value like "1 GiB" and …

NAS-137813 / 26.04 / fix: send `null` as speed limit when field empty

---

src/app/pages/credentials/users/user-form/allowed-access-section/allowed-access-section.component.html
src/app/pages/credentials/users/user-form/allowed-access-section/allowed-access-section.component.scss
src/app/pages/credentials/users/user-form/allowed-access-section/allowed-access-section.component.spec.ts
src/app/pages/credentials/users/user-form/allowed-access-section/allowed-access-section.component.ts
src/app/pages/credentials/users/user-form/auth-section/auth-section.component.html
src/app/pages/credentials/users/user-form/auth-section/auth-section.component.spec.ts
src/app/pages/credentials/users/user-form/auth-section/auth-section.component.ts
src/app/pages/credentials/users/user-form/user-form.component.html
src/app/pages/credentials/users/user-form/user-form.component.ts

Local validation added to prevent API validation errors for checkboxes. (because for checkboxes we need to tick/untick in order to make the form valid again)
Preview:
https://github.com/user-attachments/assets/dcdb42c2-cbc0-4479-963d-88cdfdcdcb27
Original PR: https://github.com/truenas/webui/pull/12650

NAS-137770 / 25.10.0 / SSH Password login error message does not clear automatically (by AlexKarpov98)

---

src/app/modules/dialog/components/job-progress/job-progress-dialog.component.spec.ts
src/app/modules/dialog/components/job-progress/job-progress-dialog.component.ts
src/app/modules/layout/console-footer/console-messages.store.spec.ts
src/app/modules/layout/console-footer/console-messages.store.ts

Update WebSocket subscriptions to use JSON-encoded parameters instead of colon-separated strings for filesystem.file_tail_follow calls in job progress dialog and console messages store.
**Testing:**
Enable console messages in General Settings -> UI
Original PR: https://github.com/truenas/webui/pull/12654

NAS-137913 / 25.10.0 / Fix filesystem.file_tail_follow WebSocket subscription parameter format (by william-gr)

---

src/app/pages/datasets/components/zvol-form/zvol-form.component.spec.ts
src/app/pages/datasets/components/zvol-form/zvol-form.component.ts

`inherit_encryption` should not be sent to the API on update.
**Testing:**
Add a zvol then try to edit it (e.g. change size)

NAS-137861 / 26.04 / Fix editing a zvol
