- src/app/pages/storage/modules/pool-manager/components/configuration-preview/configuration-preview.component.scss
- src/app/pages/storage/modules/pool-manager/components/pool-manager/pool-manager.component.scss
> NAS-124235 / 24.04 / Fix layout when pool has long name on Pool Creation Wizard

- src/app/modules/ix-forms/testing/control-harnesses.helpers.ts
- src/app/pages/storage/modules/pool-manager/components/configuration-preview/configuration-preview.component.spec.ts
- src/app/pages/storage/modules/pool-manager/components/configuration-preview/configuration-preview.harness.ts
- src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/9-review-wizard-step/review-wizard-step.harness.ts
- src/app/pages/storage/modules/pool-manager/components/pool-manager/tests/common.utils.ts
- src/app/pages/storage/modules/pool-manager/components/pool-manager/tests/create-pool.spec.ts
- src/app/pages/storage/modules/pool-manager/components/pool-manager/tests/draid-pool-creation.spec.ts
- src/app/pages/storage/modules/pool-manager/components/pool-manager/tests/pool-manager.harness.ts
- src/app/pages/storage/modules/pool-manager/components/pool-manager/tests/unsetting-on-fewer-disks.spec.ts
- src/app/pages/storage/modules/pool-manager/components/pool-manager/tests/wizard-reset-step.spec.ts
- src/app/pages/storage/modules/pool-manager/components/pool-manager/tests/wizard-start-over.spec.ts
- src/app/pages/storage/modules/pool-manager/store/pool-manager.store.ts
- src/app/pages/storage/modules/pool-manager/utils/generate-vdevs/generate-vdevs.service.ts
This ports integration tests and some bugfixes from cobia.
Testing: check pool creation for regressions.
> NAS-124176 / 23.10 / Integration tests

- src/app/interfaces/vm-form-values.interface.ts
- src/app/pages/vm/vm-wizard/vm-wizard.component.ts
Testing: check that vm wizard works.
> NAS-122751 / 22.12.5 / VM Display Password

- src/app/pages/storage/modules/pool-manager/components/configuration-preview/configuration-preview.component.scss
- src/app/pages/storage/modules/pool-manager/components/pool-manager/pool-manager.component.scss
Check ticket for details
Original PR: https://github.com/truenas/webui/pull/8905
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124235
> NAS-124235 / 23.10 / Fix layout when pool has long name on Pool Creation Wizard (by denysbutenko)

- tests/bdd/ha-bhyve02/test_NAS_T1664_iSCSI_on_failover.py
- tests/bdd/reusableSeleniumCode.py
- tests/bdd/scale/test_NAS_T1129.py
- tests/bdd/xpaths.py
Also, rename the xpath to restart services.
> TE-1103 / 24.04/ Added iSCSI start service for the iSCSI HA test

- tests/bdd/ha-bhyve02/test_NAS_T1664_iSCSI_on_failover.py
- tests/bdd/reusableSeleniumCode.py
- tests/bdd/scale/test_NAS_T1129.py
- tests/bdd/xpaths.py
Also rename the xpath to restart services.
> TE-1103 / 23.10.0 / Added iSCSI start service for the iSCSI HA test

- src/app/pages/storage/modules/pool-manager/store/pool-manager.store.ts
> NAS-124123 / 24.04 / Removing vdevs from the manual disk selection dialog doesn't update the automated dropdowns

- src/app/core/components/directives/details-height/details-height.directive.ts
- src/app/pages/datasets/components/dataset-management/dataset-management.component.scss
- src/app/pages/datasets/components/dataset-management/dataset-management.component.ts
For testing, go to Datasets page and zoom-in the window to get single column layout. See the video for easy way to check the fix:
Note: Pay attention on the cursor position to get right area of layout to be scrolled.
https://github.com/truenas/webui/assets/351613/17bba1aa-2c9a-4555-8f1a-ee94f3da7b97
> NAS-124048 / 24.04 / Fix dataset layout on mobile devices

- src/app/interfaces/container-image.interface.ts
- src/app/pages/apps/components/docker-images/pull-image-form/pull-image-form.component.spec.ts
- src/app/pages/apps/components/docker-images/pull-image-form/pull-image-form.component.ts
Ticket description for testing
> NAS-124242 / 24.04 / Fixed field name

- src/app/interfaces/container-image.interface.ts
- src/app/pages/apps-old/docker-images/pull-image-form/pull-image-form.component.spec.ts
- src/app/pages/apps-old/docker-images/pull-image-form/pull-image-form.component.ts
- src/app/pages/apps/components/docker-images/pull-image-form/pull-image-form.component.spec.ts
- src/app/pages/apps/components/docker-images/pull-image-form/pull-image-form.component.ts
> NAS-124242 / 23.10 / Fixed field name

- src/app/core/components/directives/details-height/details-height.directive.ts
- src/app/pages/datasets/components/dataset-management/dataset-management.component.scss
- src/app/pages/datasets/components/dataset-management/dataset-management.component.ts
For testing, go to Datasets page and zoom-in the window to get single column layout. See the video for easy way to check the fix:
Note: Pay attention on the cursor position to get right area of layout to be scrolled.
https://github.com/truenas/webui/assets/351613/17bba1aa-2c9a-4555-8f1a-ee94f3da7b97
Original PR: https://github.com/truenas/webui/pull/8941
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124048
> NAS-124048 / 23.10 / Fix dataset layout on mobile devices (by denysbutenko)

- src/app/pages/apps/components/installed-apps/pod-logs/pod-logs.component.scss
Check ticket description for testing
> NAS-124336 / 23.10 / Shortened height

- src/app/pages/dashboard/components/dashboard/dashboard.component.ts
- src/app/pages/dashboard/store/resources-usage-store.service.ts
> NAS-124183 / 23.10 / Unsubscribe from 'reporting.realtime' after leaving the dashboard

- src/app/interfaces/terminal.interface.ts
- src/app/modules/terminal/components/terminal/terminal.component.ts
- src/app/modules/terminal/xterm-attach-addon.ts
- src/app/pages/apps/components/installed-apps/pod-shell/pod-shell.component.ts
- src/app/pages/shell/shell.component.ts
- src/app/pages/vm/vm-serial-shell/vm-serial-shell.component.ts
- src/app/services/shell.service.ts
**Testing**
Terminal UI component should have no regressions
> NAS-124139 / 24.04 / Refactor `ShellService`

- src/app/pages/apps/components/installed-apps/app-row/app-row.component.html
- src/app/pages/apps/components/installed-apps/app-row/app-row.component.scss
- src/app/pages/apps/components/installed-apps/app-status-cell/app-status-cell.component.html
- src/app/pages/apps/components/installed-apps/app-status-cell/app-status-cell.component.spec.ts
- src/app/pages/apps/components/installed-apps/installed-apps.component.html
- src/app/pages/apps/components/installed-apps/installed-apps.component.scss
- src/app/pages/apps/components/installed-apps/installed-apps.component.ts
- src/app/pages/system/bootenv/bootenv-status/bootenv-status.component.scss
Testing:
Check installed apps page, you should be able to sort by APPLICATION, STATUS, UPDATE AVAILABLE (if there are some apps with update available)
> NAS-124339 / 24.04 / Sorting on installed applications screen

- src/app/modules/ix-dynamic-form/components/ix-dynamic-form/ix-dynamic-form-item/ix-dynamic-form-item.component.html
- src/app/modules/ix-forms/components/ix-list/ix-list.component.html
- src/app/modules/ix-forms/components/ix-list/ix-list.component.ts
- src/app/modules/ix-forms/services/form-error-handler.service.ts
- src/app/pages/credentials/certificates-dash/certificate-acme-add/certificate-acme-add.component.html
- src/app/pages/datasets/modules/encryption/components/dataset-unlock/dataset-unlock.component.html
- src/app/pages/network/components/interface-form/interface-form.component.html
- src/app/pages/sharing/iscsi/iscsi-wizard/steps/portal-wizard-step/portal-wizard-step.component.html
- src/app/pages/sharing/iscsi/portal/portal-form/portal-form.component.html
- src/app/pages/sharing/iscsi/portal/portal-form/portal-form.component.ts
- src/app/pages/sharing/iscsi/target/target-form/target-form.component.html
- src/app/pages/sharing/nfs/nfs-form/nfs-form.component.html
- src/app/pages/sharing/smb/smb-acl/smb-acl.component.html
- src/app/pages/system/advanced/allowed-addresses/allowed-addresses-form/allowed-addresses-form.component.html
Check ticket description for details
> NAS-123801 / 24.04 / Fixes error handling for `ix-list`

- src/app/modules/ix-forms/services/form-error-handler.service.ts
Showing error in a dialog. Check out the ticket description for details.
> NAS-123801 / 23.10 / Showing error in dialog if form not found

- src/app/pages/apps/store/apps-filter-store.service.ts
Testing:
Go to Available Apps section --> Search for any app and see that `New & Updated Apps`  section is not there while searching.
> NAS-123907 / 24.04 / Do not show New & Updated in search results

- src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.html
I was not able to reproduce the bug, but I did fix based on an error provided.
> NAS-124250 / 24.04 / Details panel does not always properly populate when clicking apps

- src/app/pages/apps/components/installed-apps/installed-apps.component.ts
- src/app/pages/sharing/iscsi/iscsi-wizard/iscsi-wizard.component.spec.ts
- src/app/pages/sharing/iscsi/iscsi-wizard/steps/portal-wizard-step/portal-wizard-step.component.html
- src/app/pages/sharing/iscsi/iscsi-wizard/steps/portal-wizard-step/portal-wizard-step.component.ts
Testing: 
GO to iSCSI wizard
http://localhost:4200/sharing/iscsi/configuration
Go to Portal  settsings:
IP Address is required and if not added -> form stays disabled
> NAS-124301 / 24.04 / Traceback received When creating New iSCSI Share/Suggested Improvement

- src/app/pages/apps/components/installed-apps/app-details-panel/app-details-panel.component.html
- src/app/pages/apps/components/installed-apps/app-details-panel/app-details-panel.component.ts
- src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.html
- src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.scss
- src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.ts
- src/app/pages/apps/components/installed-apps/app-row/app-row.component.html
- src/app/pages/apps/components/installed-apps/app-row/app-row.component.scss
- src/app/pages/apps/components/installed-apps/installed-apps.component.html
- src/app/pages/apps/components/installed-apps/installed-apps.component.scss
Check out the ticket description for details
> NAS-124335 / 23.10 / Improved styles for movile view for installed apps

- src/app/pages/sharing/iscsi/iscsi-wizard/iscsi-wizard.component.spec.ts
- src/app/pages/sharing/iscsi/iscsi-wizard/steps/portal-wizard-step/portal-wizard-step.component.html
- src/app/pages/sharing/iscsi/iscsi-wizard/steps/portal-wizard-step/portal-wizard-step.component.ts
Testing: 
GO to iSCSI wizard
http://localhost:4200/sharing/iscsi/configuration
Go to Portal  settsings:
IP Address is required and if not added -> form stays disabled
Original PR: https://github.com/truenas/webui/pull/8972
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124301
> NAS-124301 / 23.10 / Traceback received When creating New iSCSI Share/Suggested Improvement (by AlexKarpov98)

- src/app/pages/dashboard/components/widget-cpu/widget-cpu.component.html
- src/app/pages/dashboard/components/widget-cpu/widget-cpu.component.ts
If temp values are 0, that means temperature values are not available for the CPU and we should show the user `'N/A'`
> NAS-124044 / 23.10 / Adapt to 0 values

- src/app/pages/datasets/components/dataset-form/dataset-form.component.spec.ts
- src/app/pages/datasets/components/dataset-form/dataset-form.component.ts
- src/app/pages/datasets/components/dataset-form/utils/dataset-form.service.spec.ts
- src/app/pages/datasets/components/dataset-form/utils/dataset-form.service.ts
> NAS-124360 / 24.04 / Fixed dataset form

- src/app/modules/layout/components/topbar/topbar.component.html
- src/app/modules/layout/components/topbar/topbar.component.ts
- src/app/pages/apps/apps-routing.module.ts
- src/app/pages/storage/modules/pool-manager/pool-manager.routing.ts
> NAS-124421 / 23.10 / MAS-124421: Remove feedback prompts [cobia]

- src/app/pages/apps/apps-routing.module.ts
- src/app/pages/storage/modules/pool-manager/pool-manager.routing.ts
> NAS-124421 / 24.04 / Remove feedback prompts [master]

- src/app/modules/jobs/components/job-item/job-item.component.html
**Testing**
Add mocks (see ticket) and ensure that the tooltip is displayed correctly
> NAS-124340 / 24.04 / NAS-124340 Stopped cron jobs shown as tasks

- src/app/pages/data-protection/replication/replication-form/replication-form.component.spec.ts
- src/app/pages/data-protection/replication/replication-form/replication-form.component.ts
- src/app/pages/data-protection/replication/replication-wizard/steps/replication-what-and-where/replication-what-and-where.component.spec.ts
For testing, check `Sudo Enabled` dialog on `Replication Form` and `Replication Wizard`
> NAS-124298 / 24.04 / Add sudo enabled dialog to replication form and unit tests

- src/app/pages/apps/components/available-apps/app-card/app-card.component.ts
Check ticket description for testing instructions
Original PR: https://github.com/truenas/webui/pull/9000
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124419
> NAS-124419 / 24.04 / Checking for null (by RehanY147)

- src/app/modules/jobs/components/job-item/job-item.component.html
**Testing**
Add mocks (see ticket) and ensure that the tooltip is displayed correctly
Original PR: https://github.com/truenas/webui/pull/8998
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124340
> NAS-124340 / 23.10 / NAS-124340 Stopped cron jobs shown as tasks (by bvasilenko)

- src/app/modules/ix-tree/components/nested-tree-node/nested-tree-node.component.scss
- src/app/modules/ix-tree/components/tree-virtual-scroll-view/tree-virtual-scroll-view.component.scss
- src/app/pages/datasets/modules/permissions/components/save-as-preset-modal/save-as-preset-modal.component.scss
- src/app/pages/system/bootenv/bootenv-status/bootenv-node-item/bootenv-node-item.component.scss
- src/app/pages/system/bootenv/bootenv-status/bootenv-status.component.scss
> NAS-124332 / 24.04 / Icons are misaligned in datasets tree

- src/app/services/schema/app-schema.service.ts
> NAS-124291 / 24.04 / Minio Host Path cannot be selected

- src/app/services/schema/app-schema.service.ts
Original PR: https://github.com/truenas/webui/pull/9004
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124291
> NAS-124291 / 23.10 / Minio Host Path cannot be selected (by AlexKarpov98)

- src/app/services/ws.service.ts
Testing: see ticket description.
Original PR: https://github.com/truenas/webui/pull/9009
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124442
> NAS-124442 / 23.10 / Errors is not shown - Cannot use 'in' operator to search … (by undsoft)

- scripts/ui/models.json
- src/app/core/testing/utils/enclosure-templates/mock-r10.ts
- src/app/core/testing/utils/enclosure-templates/mock-r30.ts
- src/app/core/testing/utils/mock-storage-generator.utils.ts
Testing:
Check to see if mock utility can emulate R10 and R30 machines
Original PR: https://github.com/truenas/webui/pull/8787
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123781
> NAS-123781 / 23.10.0 / Mock Utility: Complete R series support (by dszidi)

- src/app/pages/datasets/components/dataset-details-panel/dataset-details-panel.component.ts
Testing: Create new dataset -> you should be navigated to the newly created dataset now.
`We need to wait for datasets to be load before redirecting to newly created one.`
> NAS-124480 / 24.04 / "Switched to new dataset" does not work anymore

- src/app/pages/system/advanced/allowed-addresses/allowed-addresses-card/allowed-addresses-card.component.html
> NAS-124555 / 24.04 / Unexpected symbol in Allowed IP Addresses Card

- src/app/pages/datasets/components/dataset-details-panel/dataset-details-panel.component.ts
Testing: Create new dataset -> you should be navigated to the newly created dataset now.
`We need to wait for datasets to be load before redirecting to newly created one.`
Original PR: https://github.com/truenas/webui/pull/9022
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124480
> NAS-124480 / 23.10.1 / "Switched to new dataset" does not work anymore (by AlexKarpov98)

- src/app/pages/datasets/components/dataset-details-panel/dataset-details-panel.component.ts
Testing: Create new dataset -> you should be navigated to the newly created dataset now.
`We need to wait for datasets to be load before redirecting to newly created one.`
Original PR: https://github.com/truenas/webui/pull/9022
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124480
> NAS-124480 / 23.10.0 / "Switched to new dataset" does not work anymore (by AlexKarpov98)

- src/app/pages/apps/components/installed-apps/pod-logs/pod-logs.component.scss
Check ticket description for testing
Original PR: https://github.com/truenas/webui/pull/8955
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124336
> NAS-124336 / 24.04 / Shortened height (by RehanY147)

- src/app/services/ws.service.spec.ts
> NAS-124483 / 24.04 / Add unit tests to WebSocketService

- src/app/pages/sharing/smb/smb-form/smb-form.component.ts
> NAS-124606 / 24.04 / Duplicate name error is not shown in SMB shares

- src/app/pages/account/users/user-form/user-form.component.ts
> NAS-124600 / 24.04 / Webui path selector for home dirs presents non-directory files

- src/app/modules/ix-forms/components/ix-input/ix-input.component.ts
> NAS-124481 / 24.04 / undefined in search filter when installing an app

- src/app/pages/account/users/user-form/user-form.component.ts
Original PR: https://github.com/truenas/webui/pull/9038
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124600
> NAS-124600 / 23.10.1 / Webui path selector for home dirs presents non-directory files (by AlexKarpov98)

- src/app/pages/account/users/user-form/user-form.component.ts
Original PR: https://github.com/truenas/webui/pull/9038
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124600
> NAS-124600 / 23.10.0 / Webui path selector for home dirs presents non-directory files (by AlexKarpov98)

- scripts/ui/models.json
- src/app/core/testing/utils/enclosure-templates/mock-es102s.ts
- src/app/core/testing/utils/mock-storage-generator.utils.ts
- src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.ts
git cherry-pick -x e7848ce56bd06ba3bc32a1a527ab372ec0590687
git cherry-pick -x c20a7c63eb80264c28c4764915fd918cd2452a6f
Original PR: https://github.com/truenas/webui/pull/9033
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124569
> NAS-124569 / 23.10.1 / Rename ES102S to ES102G2 (UI) (by AlexKarpov98)

- src/app/pages/apps/components/installed-apps/app-bulk-upgrade/app-bulk-upgrade.component.ts
> NAS-124609 / 24.04 / Do not open Task Manager when using Upgrade All

- src/app/pages/apps/components/installed-apps/app-bulk-upgrade/app-bulk-upgrade.component.ts
Original PR: https://github.com/truenas/webui/pull/9046
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124609
> NAS-124609 / 23.10.1 / Do not open Task Manager when using Upgrade All (by AlexKarpov98)

- src/app/pages/apps/components/installed-apps/app-bulk-upgrade/app-bulk-upgrade.component.ts
Original PR: https://github.com/truenas/webui/pull/9046
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124609
> NAS-124609 / 23.10.0 / Do not open Task Manager when using Upgrade All (by AlexKarpov98)

- scripts/ui/models.json
- src/app/core/testing/utils/enclosure-templates/mock-es102s.ts
- src/app/core/testing/utils/mock-storage-generator.utils.ts
- src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.ts
git cherry-pick -x e7848ce56bd06ba3bc32a1a527ab372ec0590687
git cherry-pick -x c20a7c63eb80264c28c4764915fd918cd2452a6f
Original PR: https://github.com/truenas/webui/pull/9033
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124569
> NAS-124569 / 23.10.0 / Rename ES102S to ES102G2 (UI) (by AlexKarpov98)

- src/app/pages/network/components/interface-form/interface-form.component.ts
Testing: check ticket I think code review is enough.
> NAS-124681 / 24.04 / Race condition in interface form

- src/app/core/testing/interfaces/mock-storage-generator.interface.ts
- src/app/core/testing/utils/mock-enclosure.utils.ts
- src/app/core/testing/utils/mock-storage-generator.utils.ts
- src/app/modules/entity/entity-table/entity-table.component.ts
- src/app/pages/credentials/certificates-dash/certificate-authority-list/certificate-authority-list.component.ts
- src/app/pages/credentials/certificates-dash/certificate-list/certificate-list.component.ts
- src/app/pages/credentials/certificates-dash/csr-list/csr-list.component.ts
- src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts
- src/app/pages/network/components/static-routes-card/static-routes-card.component.ts
- src/app/pages/system/advanced/system-security/system-security-card/system-security-card.component.ts
- src/app/pages/system/alert-config-form/alert-config-form.component.ts
- src/app/pages/system/bootenv/bootenv-list/bootenv-list.component.ts
- src/app/pages/system/general-settings/email/email-card/email-card.component.ts
Testing: test for regressions in some of the affected places.
> NAS-124718 / 24.04 / Various code improvements

- src/app/pages/apps/components/app-section-expand-collapse/app-section-expand-collapse.component.scss
- src/app/pages/apps/components/app-section-expand-collapse/app-section-expand-collapse.component.ts
- src/app/pages/apps/components/installed-apps/app-notes-card/app-notes-card.component.html
- src/app/pages/apps/components/installed-apps/app-notes-card/app-notes-card.component.scss
- src/app/pages/apps/components/installed-apps/app-notes-card/app-notes-card.component.ts
https://github.com/truenas/webui/assets/22980553/da880dcf-905c-42e3-9c29-5d4a71e01785
> NAS-124680 / 24.04 / Notes section on Apps page has issues showing full contents - scrolling/expanding data not always available

- src/app/pages/apps/components/app-section-expand-collapse/app-section-expand-collapse.component.scss
- src/app/pages/apps/components/app-section-expand-collapse/app-section-expand-collapse.component.ts
- src/app/pages/apps/components/installed-apps/app-notes-card/app-notes-card.component.html
- src/app/pages/apps/components/installed-apps/app-notes-card/app-notes-card.component.scss
- src/app/pages/apps/components/installed-apps/app-notes-card/app-notes-card.component.ts
https://github.com/truenas/webui/assets/22980553/da880dcf-905c-42e3-9c29-5d4a71e01785
Original PR: https://github.com/truenas/webui/pull/9064
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124680
> NAS-124680 / 23.10.0 / Notes section on Apps page has issues showing full contents - scrolling/expanding data not always available (by AlexKarpov98)

- src/app/pages/apps/components/app-section-expand-collapse/app-section-expand-collapse.component.scss
- src/app/pages/apps/components/app-section-expand-collapse/app-section-expand-collapse.component.ts
- src/app/pages/apps/components/installed-apps/app-notes-card/app-notes-card.component.html
- src/app/pages/apps/components/installed-apps/app-notes-card/app-notes-card.component.scss
- src/app/pages/apps/components/installed-apps/app-notes-card/app-notes-card.component.ts
https://github.com/truenas/webui/assets/22980553/da880dcf-905c-42e3-9c29-5d4a71e01785
Original PR: https://github.com/truenas/webui/pull/9064
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124680
> NAS-124680 / 23.10.1 / Notes section on Apps page has issues showing full contents - scrolling/expanding data not always available (by AlexKarpov98)

- src/app/pages/reports-dashboard/components/exporters/reporting-exporters-form/reporting-exporters-form.component.ts
- src/app/pages/reports-dashboard/components/exporters/reporting-expoters-list/reporting-exporters-list.component.html
- src/app/pages/reports-dashboard/components/exporters/reporting-expoters-list/reporting-exporters-list.component.scss
- src/app/pages/reports-dashboard/components/exporters/reporting-expoters-list/reporting-exporters-list.component.ts
Testing: see http://localhost:4200/reportsdashboard/exporters
> NAS-124707 / 24.04 / UI Adjustments for Reporting Exporters

- tests/bdd/ha-bhyve02/test_NAS_T0964.py
(cherry picked from commit b75e653f3a6b800b15a5672ecb639015f56a519b)
> TE-1199 / 23.10.1 / Removed extra Login in test_NAS_T0964.py

- src/app/pages/data-protection/cloudsync/cloudsync-list/cloudsync-list.component.html
- src/app/pages/data-protection/cloudsync/cloudsync-list/cloudsync-list.component.ts
- src/app/pages/system/advanced/cron/cron-list/cron-list.component.html
- src/app/pages/system/advanced/cron/cron-list/cron-list.component.ts
Testing: code review is enough.
> NAS-124723 / 24.04 / Use ixPageHeader instead of this.layoutService.pageHeaderUpdater$.next(this.pageHeader);

- src/app/modules/common/search-input/search-input.component.html
- src/app/modules/common/search-input/search-input.component.ts
- src/app/modules/ix-forms/components/ix-input/ix-input.component.html
- src/app/modules/ix-forms/components/ix-input/ix-input.component.ts
- src/app/pages/apps/components/available-apps/available-apps-header/available-apps-header.component.html
- src/app/pages/apps/components/installed-apps/installed-apps.component.html
> NAS-124685 / 24.04 / Apps "Search" text field,  for Installed and Discover pages, do not have a character string limit

- src/app/modules/common/search-input/search-input.component.html
- src/app/modules/common/search-input/search-input.component.ts
- src/app/modules/ix-forms/components/ix-input/ix-input.component.html
- src/app/modules/ix-forms/components/ix-input/ix-input.component.ts
- src/app/pages/apps/components/available-apps/available-apps-header/available-apps-header.component.html
- src/app/pages/apps/components/installed-apps/installed-apps.component.html
Testing: check ticket
Original PR: https://github.com/truenas/webui/pull/9077
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124685
> NAS-124685 / 23.10.1 / Apps "Search" text field,  for Installed and Discover pages, do not have a character string limit (by AlexKarpov98)

- src/app/modules/common/search-input/search-input.component.html
- src/app/modules/common/search-input/search-input.component.ts
- src/app/modules/ix-forms/components/ix-input/ix-input.component.html
- src/app/modules/ix-forms/components/ix-input/ix-input.component.ts
- src/app/pages/apps/components/available-apps/available-apps-header/available-apps-header.component.html
- src/app/pages/apps/components/installed-apps/installed-apps.component.html
Testing: check ticket
Original PR: https://github.com/truenas/webui/pull/9077
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124685
> NAS-124685 / 23.10.0 / Apps "Search" text field,  for Installed and Discover pages, do not have a character string limit (by AlexKarpov98)

- src/app/core/testing/classes/mock-websocket.service.ts
- src/app/core/testing/interfaces/mock-websocket-responses.interface.ts
- src/app/core/testing/utils/mock-websocket.utils.ts
- src/app/modules/ix-forms/components/ix-slide-in/ix-slide-in.component.ts
- src/app/modules/ix-tables/testing/ix-table.harness.ts
- src/app/pages/network/network.component.html
- src/app/pages/network/network.component.ts
- src/app/pages/network/tests/checkin.spec.ts
- src/app/services/ix-slide-in.service.ts
> NAS-124650 / 24.04 / Tests for network checkin

- src/app/pages/dashboard/components/dashboard/dashboard.component.ts
- src/app/pages/dashboard/components/widget-cpu/widget-cpu.component.ts
- src/app/pages/dashboard/components/widget-network/widget-network.component.ts
- src/app/pages/reports-dashboard/components/report/report.component.ts
To avoid memory leaks and save memory usage.
https://developer.mozilla.org/en-US/docs/Web/API/Document/hidden
> NAS-123988 / 24.04 / Skip processing state updates when the document is hidden

- src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.ts
**Testing**
On the m60-111.dc1.ixsystems.net (10.220.16.28) or any other machine with enclosure support,
Follow the replication steps specified in the ticket.
> NAS-124583 / 24.04 / Fix `selectedVdevSlots` getter bug in Enclosure

- src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/layout-step/automated-disk-selection/automated-disk-selection.component.html
- src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/layout-step/automated-disk-selection/automated-disk-selection.component.ts
- src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/7-metadata-wizard-step/metadata-wizard-step.component.html
- src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/7-metadata-wizard-step/metadata-wizard-step.component.spec.ts
- src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/7-metadata-wizard-step/metadata-wizard-step.component.ts
- src/app/pages/storage/modules/pool-manager/components/pool-manager/tests/create-pool.spec.ts
- src/app/pages/storage/modules/pool-manager/components/pool-manager/tests/wizard-start-over.spec.ts
Check ticket description for testing
> NAS-124690 / 23.10.1 / Allow layouts to change for metadata step

- src/app/pages/datasets/modules/permissions/components/save-as-preset-modal/save-as-preset-modal.component.spec.ts
- src/app/pages/datasets/modules/permissions/components/save-as-preset-modal/save-as-preset-modal.component.ts
See ticket description for testing instructions
> NAS-124633 / 24.04 / Fix missing ids when saving modal

- src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.ts
**Testing**
On the m60-111.dc1.ixsystems.net (10.220.16.28) or any other machine with enclosure support,
Follow the replication steps specified in the ticket.
Original PR: https://github.com/truenas/webui/pull/9079
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124583
> NAS-124583 / 23.10.1 / Fix `selectedVdevSlots` getter bug in Enclosure (by bvasilenko)

- src/app/pages/sharing/components/shares-dashboard/service-state-button/service-state-button.component.spec.ts
- src/app/pages/sharing/components/shares-dashboard/service-state-button/service-state-button.component.ts
> NAS-124764 / 24.04 / Mismatched color of service status pill buttons on the Shares Dashboard

- src/app/modules/ix-forms/components/ix-select/ix-select.component.html
- src/app/modules/ix-forms/components/ix-select/ix-select.component.scss
- src/app/modules/ix-forms/components/ix-select/ix-select.component.spec.ts
- src/app/modules/ix-forms/components/ix-select/ix-select.component.ts
- src/app/pages/reports-dashboard/components/reports-global-controls/reports-global-controls.component.html
- src/app/pages/reports-dashboard/components/reports-global-controls/reports-global-controls.component.ts
- src/assets/styles/other/_tn-styles.scss
git cherry-pick -x f05233364cdb2d1204e0be9e336f11b22d77d727
git cherry-pick -x cd804d003b4cc751a7b95c91c199b34ac16f578f
git cherry-pick -x d9f8923732305e0a52bda6fce8edb94379b61701
git cherry-pick -x 025afb18f0d538d2735082d80cd91d629c8cb44c
git cherry-pick -x ff97620ae17ab440ea722489fd4bffc20c9dd7d3
git cherry-pick -x d987d1a9913c57de64f170e2859a202030a519ac
Testing: See updated select component with "Select All" option.
Original PR: https://github.com/truenas/webui/pull/9076
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124670
> NAS-124670 / 23.10.1 / Reporting disks view improvements for large disk systems (by AlexKarpov98)

- src/app/pages/dashboard/components/widget-help/widget-help.component.ts
Help widget on main dashboard will now show a back button when in mobile mode.
> NAS-124818 / 24.04 / Missing back button on dashboard widget

- src/app/interfaces/chart-release.interface.ts
- src/app/pages/apps/components/installed-apps/app-row/app-row.component.html
- src/app/pages/apps/components/installed-apps/app-row/app-row.component.spec.ts
- src/app/pages/apps/components/installed-apps/app-row/app-row.component.ts
- src/app/pages/apps/components/installed-apps/installed-apps.component.html
- src/app/pages/apps/components/installed-apps/installed-apps.component.ts
- src/app/pages/data-protection/cloudsync/cloudsync-task-card/cloudsync-task-card.component.spec.ts
- src/app/pages/data-protection/rsync-task/rsync-task-card/rsync-task-card.component.spec.ts
- src/app/pages/data-protection/scrub-task/scrub-task-card/scrub-task-card.component.spec.ts
- src/app/pages/data-protection/smart-task/smart-task-card/smart-task-card.component.spec.ts
- src/app/pages/data-protection/snapshot-task/snapshot-task-card/snapshot-task-card.component.spec.ts
- src/app/pages/system/advanced/cron/cron-card/cron-card.component.spec.ts
Testing: check that app selection works as before
> NAS-123820 / 24.04 / Remove `selected` property from ChartRelease interface

- src/app/pages/datasets/components/dataset-management/dataset-management.component.ts
fixing previous accidentally merged pr.
> NAS-125044 / 24.04 / Datasets fix

- src/app/pages/apps/components/chart-wizard/chart-wizard.component.spec.ts
- src/app/pages/apps/components/chart-wizard/chart-wizard.component.ts
git cherry-pick -x 58ae6b3f2c668b34312246d3eac19333cbdda513
git cherry-pick -x 49bc75d96a8a1a3bde0c3d9355462b51ce1d8483
Testing: 
Read the ticket
Use m40 (Nextcloud)
http://localhost:4200/apps/available/TRUENAS/charts/nextcloud/install
OR ask @stavros-k for app if you can't find the one with different versions.
Original PR: https://github.com/truenas/webui/pull/9171
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124944
> NAS-124944 / 23.10.1 / [Apps/UI]: Selecting different app version to install does not use questions of the specified version (by AlexKarpov98)

- src/app/pages/storage/modules/pool-manager/components/configuration-preview/configuration-preview.component.ts
- src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/layout-step/automated-disk-selection/automated-disk-selection.component.spec.ts
- src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/layout-step/automated-disk-selection/automated-disk-selection.component.ts
- src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/pool-manager-wizard.component.html
- src/app/pages/storage/modules/pool-manager/components/pool-manager/tests/draid-pool-creation.spec.ts
- src/app/pages/storage/modules/pool-manager/store/pool-manager.store.ts
Check ticket description for issue details. This PR also fixes an additional bug where when creating a new pool, adding the spare vdev although seems to be successful, doesn't show up on the review step.
> NAS-124985 / 24.04 / Removing mutability of state object

- src/app/modules/ix-table2/components/ix-table-head/ix-table-head.component.html
- src/app/modules/ix-table2/components/ix-table2/ix-table2.component.scss
> NAS-125002 / 24.04 / Break table headers to new line in ix-table2

- src/app/pages/audit/components/audit/audit.component.scss
- src/app/pages/audit/components/log-details-panel/log-details-panel.component.scss
Result:
https://github.com/truenas/webui/assets/22980553/525c6cc6-a038-499c-9ca3-84fa6475617e
> NAS-125166 / 24.04 / Audit stickiness fix after updates

- src/app/pages/system/advanced/save-debug-button/save-debug-button.component.ts
Testing: see ticket, code review is enough
> NAS-125147 / 24.04 / Dragonfish: Generate debug dialog triggered multiple times and comes back after canceled

- src/app/pages/system/advanced/save-debug-button/save-debug-button.component.ts
Testing: see ticket, code review is enough 
Original PR: https://github.com/truenas/webui/pull/9199
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125147
> NAS-125147 / 23.10.1 / Dragonfish: Generate debug dialog triggered multiple times and comes back after canceled (by AlexKarpov98)

- src/app/enums/from-wizard-to-advanced.enum.ts
- src/app/modules/ix-icon/ix-icon.component.scss
- src/app/modules/ix-table2/components/ix-table2/ix-table2.component.scss
- src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts
- src/app/pages/data-protection/cloudsync/cloudsync-list/cloudsync-list.component.ts
- src/app/pages/data-protection/cloudsync/cloudsync-task-card/cloudsync-task-card.component.ts
- src/app/pages/data-protection/cloudsync/cloudsync-wizard/steps/cloudsync-provider/cloudsync-provider.component.ts
- src/app/pages/data-protection/cloudsync/cloudsync-wizard/steps/cloudsync-what-and-when/cloudsync-what-and-when.component.ts
- src/app/pages/data-protection/replication/replication-form/replication-form.component.ts
- src/app/pages/data-protection/replication/replication-list/replication-list.component.ts
- src/app/pages/data-protection/replication/replication-task-card/replication-task-card.component.ts
- src/app/pages/data-protection/replication/replication-wizard/steps/replication-what-and-where/replication-what-and-where.component.ts
- src/app/store/admin-panel/admin.actions.ts
> NAS-125213 / 24.04 / From wizard to Advanced options in card/list are not updating on new items creation (switching from wizard to form)

- src/app/pages/storage/components/dashboard-pool/zfs-health-card/zfs-health-card.component.ts
Testing: see ticket. Code review is enough.
> NAS-125209 / 24.04 / Pools missing in GUI after manually initiating scrub tasks on some pools

- src/app/pages/storage/components/dashboard-pool/zfs-health-card/zfs-health-card.component.ts
Testing: see ticket. Code review is enough.
Original PR: https://github.com/truenas/webui/pull/9207
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125209
> NAS-125209 / 23.10.1 / Pools missing in GUI after manually initiating scrub tasks on some pools (by AlexKarpov98)

- src/app/pages/system/viewenclosure/view-enclosure.component.ts
Testing: 
See ticket, use `r50bm` machine from the ticket.
Visit http://localhost:4200/system/viewenclosure 
And see that it's loading. (Disks on TRUENAS-R50BM (0))
> NAS-125259 / 13.0 / ES60G2 fails to be displayed in UI

- src/app/pages/system/update/manual-update-form/manual-update-form.component.ts
- src/app/pages/system/update/update.component.ts
- src/app/services/update.service.ts
- src/app/views/sessions/signin/store/signin.store.spec.ts
- src/app/views/sessions/signin/store/signin.store.ts
Testing: update a system and see that UI reloads after update is complete.
Background tabs and tabs in other browser should also reload.
> NAS-124602 / 23.10.1 / Reload UI during updates

- src/app/pages/system/update/manual-update-form/manual-update-form.component.ts
- src/app/pages/system/update/update.component.ts
- src/app/services/update.service.ts
- src/app/views/sessions/signin/store/signin.store.spec.ts
- src/app/views/sessions/signin/store/signin.store.ts
Testing: update a system and see that UI reloads after update is complete.
Background tabs and tabs in other browser should also reload.
Original PR: https://github.com/truenas/webui/pull/9236
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124602
> NAS-124602 / 24.04 / Reload UI during updates (by undsoft)

- src/app/pages/apps/apps.module.ts
- src/app/pages/network/components/interfaces-card/interface-status-icon/interface-status-icon.component.ts
Testing: see ticket, code review shall be enough.
Original PR: https://github.com/truenas/webui/pull/9241
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125347
> NAS-125347 / 23.10.1 / Bugs detected in console (by AlexKarpov98)

- src/app/interfaces/certificate.interface.ts
- src/app/pages/credentials/certificates-dash/certificate-edit/certificate-edit.component.ts
> NAS-125191 / 24.04 / SCALE Certificates UI does not show saved "Renew Certificate Days Before Expiry" values

- src/app/pages/credentials/backup-credentials/cloud-credentials-form/oauth-provider/oauth-provider.component.spec.ts
- src/app/pages/credentials/backup-credentials/cloud-credentials-form/oauth-provider/oauth-provider.component.ts
- src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/base-provider-form.ts
Go to add a new Cloud Backup Credential. Select Yandex as the provider and click the "Log in to Provider" button. Go through the process that follows and log in to Yandex. Once done successfully, you should be redirected to UI and the token and client id and secret fields should be filled in. You should be able to submit the form.
> NAS-125122 / 23.10.2 / Only accept events with truenas.com origin

- src/app/modules/ix-forms/components/ix-button-group/ix-button-group.component.html
- src/app/modules/ix-forms/components/ix-button-group/ix-button-group.component.scss
- src/app/modules/ix-forms/components/ix-button-group/ix-button-group.component.spec.ts
- src/app/modules/ix-forms/components/ix-button-group/ix-button-group.component.ts
- src/app/modules/ix-forms/components/ix-button-group/ix-button-group.harness.ts
- src/app/modules/ix-forms/ix-forms.module.ts
- src/app/modules/ix-forms/testing/control-harnesses.helpers.ts
- src/app/modules/test-id/test/test.directive.ts
We agreed to split PRs into smaller parts for easier reviews. 
Extracted from PRs #9205 #9256 
There is no actual usage of this component yet. Tests should pass and code review is enough.
> NAS-125399 / 24.04 / Add Button Group Component to IxForms

- src/app/helpers/params-builder/params-builder.class.ts
- src/app/interfaces/group.interface.ts
- src/app/interfaces/property-path.type.ts
- src/app/interfaces/query-api.interface.ts
- src/app/modules/search-input/components/advanced-search/advanced-search.component.spec.ts
- src/app/modules/search-input/components/search-input/search-input.component.spec.ts
- src/app/modules/search-input/services/query-to-api/query-to-api.service.ts
- src/app/pages/audit/components/audit/audit.component.ts
- src/app/pages/audit/components/export-button/export-button.component.ts
- src/app/pages/data-protection/replication/replication-form/replication-form.component.spec.ts
- src/app/pages/datasets/modules/snapshots/constants/snapshot-exclude-boot.constant.ts
- src/app/pages/datasets/modules/snapshots/snapshot-add-form/snapshot-add-form.component.ts
- src/app/pages/datasets/modules/snapshots/store/snapshot.effects.ts
> NAS-125371 / 24.04 / Fix typing for query filters

- src/app/interfaces/certificate.interface.ts
- src/app/pages/credentials/certificates-dash/certificate-edit/certificate-edit.component.ts
Original PR: https://github.com/truenas/webui/pull/9204
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125191
> NAS-125191 / 23.10.2 / SCALE Certificates UI does not show saved "Renew Certificate Days Before Expiry" values (by AlexKarpov98)

- src/app/pages/credentials/backup-credentials/cloud-credentials-form/oauth-provider/oauth-provider.component.spec.ts
- src/app/pages/credentials/backup-credentials/cloud-credentials-form/oauth-provider/oauth-provider.component.ts
- src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/base-provider-form.ts
Go to add a new Cloud Backup Credential. Select Yandex as the provider and click the "Log in to Provider" button. Go through the process that follows and log in to Yandex. Once done successfully, you should be redirected to UI and the token and client id and secret fields should be filled in. You should be able to submit the form.
Original PR: https://github.com/truenas/webui/pull/9259
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125122
> NAS-125122 / 23.10.1 / Only accept events with truenas.com origin (by RehanY147)

- src/app/modules/oauth-button/components/oauth-button/oauth-button.component.ts
- src/app/pages/credentials/backup-credentials/cloud-credentials-form/oauth-provider/oauth-provider.component.spec.ts
git cherry-pick -x 532e532afc8cfed3a454d256eabba882469f4f2b
git cherry-pick -x b8382cf4d06b96eed2d8a2c5a43b41e76e06ea7f
git cherry-pick -x cff987eafb0217cda583d872f4d11c55c3751435
Go to add a new Cloud Backup Credential. Select Yandex as the provider and click the "Log in to Provider" button. Go through the process that follows and log in to Yandex. Once done successfully, you should be redirected to UI and the token and client id and secret fields should be filled in. You should be able to submit the form.
Original PR: https://github.com/truenas/webui/pull/9259
Jira URL: …
> NAS-125122 / 24.04 / Only accept events with truenas.com origin (by RehanY147)

- src/app/modules/layout/components/topbar/user-menu/user-menu.component.html
- src/app/modules/layout/components/topbar/user-menu/user-menu.component.scss
- src/app/modules/layout/components/topbar/user-menu/user-menu.component.spec.ts
- src/app/modules/layout/components/topbar/user-menu/user-menu.component.ts
Testing: see ticket result 👇 :
> NAS-125507 / 24.04 / Show username in top bar

- src/app/modules/scheduler/utils/schedule-to-crontab.spec.ts
- src/app/modules/scheduler/utils/schedule-to-crontab.utils.ts
- src/app/pages/data-protection/snapshot-task/snapshot-task-list/snapshot-task-list.component.ts
Testing: 
See ticket and result and test case: 👇
> NAS-125484 / 24.04 / Incorrect When time displayed on periodic snapshot tasks screen

- src/app/modules/layout/components/topbar/user-menu/user-menu.component.html
- src/app/modules/layout/components/topbar/user-menu/user-menu.component.scss
- src/app/modules/layout/components/topbar/user-menu/user-menu.component.spec.ts
> NAS-125535 / 24.04 / Make username and settings icon in topbar one item

- package.json
- src/app/modules/search-input/components/advanced-search/advanced-search.component.html
- src/app/modules/search-input/components/advanced-search/advanced-search.component.scss
- src/app/modules/search-input/components/advanced-search/advanced-search.component.spec.ts
- src/app/modules/search-input/components/advanced-search/advanced-search.component.ts
- src/app/modules/search-input/components/advanced-search/advanced-search.harness.ts
- src/app/modules/search-input/components/basic-search/basic-search.component.ts
- src/app/modules/search-input/search-input.module.ts
- src/app/modules/search-input/services/query-parser/query-parser.service.ts
- src/app/modules/search-input/services/query-parser/query-parsing-result.interface.ts
- yarn.lock
Testing:
Go to Audit page, switch to advanced query and test out some input, you should see error highlighted with border bottom and see error triangle on the left hand side:
> NAS-125375 / 24.04 / Improve error handling in advanced search

- src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/layout-step/automated-disk-selection/automated-disk-selection.component.html
- src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/layout-step/automated-disk-selection/disk-size-selects/disk-size-selects.component.html
- src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/layout-step/automated-disk-selection/draid-selection/draid-selection.component.html
- src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/layout-step/automated-disk-selection/normal-selection/normal-selection.component.html
- src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/components/layout-step/custom-layout-applied/custom-layout-applied.component.html
- src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/1-general-wizard-step/general-wizard-step.component.html
- src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/2-enclosure-wizard-step/enclosure-wizard-step.component.html
- src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/3-data-wizard-step/data-wizard-step.component.html
- src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/4-log-wizard-step/log-wizard-step.component.html
- src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/5-spare-wizard-step/spare-wizard-step.component.html
- src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/6-cache-wizard-step/cache-wizard-step.component.html
- src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/7-metadata-wizard-step/metadata-wizard-step.component.html
- src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/8-dedup-wizard-step/dedup-wizard-step.component.html
- src/app/pages/storage/modules/pool-manager/components/pool-manager-wizard/steps/9-review-wizard-step/review-wizard-step.component.html
**Testing**
Please double check the pool creation wizard for minor regressions
> NAS-125250 / 24.04 / Dynamic Pool Creation Wizard data-test tags

- src/app/pages/sharing/smb/smb-form/smb-form.component.ts
Testing: see ticket for testing
Result: only 1 error appears & Form is not closed on error.
https://github.com/truenas/webui/assets/22980553/12a0b11a-2bde-42d9-adc0-001a69cf98c7
> NAS-125703 / 24.04 / Double Error message for Sharing SMB creation

- src/app/modules/ix-forms/components/ix-chips/ix-chips.component.spec.ts
- src/app/modules/ix-forms/components/ix-chips/ix-chips.component.ts
For testing:
> Open add user form.
> Fill in details and select builtin_users from the list in Auxiliary Groups.
> Try to save.
> Get error: Item#0 is not valid per list types: [group] Not an integer
> NAS-125706 / 24.04 / Fix mixed values in ix-chips

- src/app/pages/apps/components/app-detail-view/app-details-header/app-details-header.component.spec.ts
- src/app/pages/apps/components/app-detail-view/app-details-header/app-details-header.component.ts
- src/app/pages/apps/components/installed-apps/app-settings-button/app-settings-button.component.spec.ts
- src/app/pages/apps/components/installed-apps/app-settings-button/app-settings-button.component.ts
- yarn.lock
Go to the App details page and click on the Setup Pool button to make the dialog appear.
Expected: The dialog opens
Actual: nothing shows up. The screen goes a bit dark. Errors in the browser console.
> NAS-125754 / 24.04 / Fixed injection of `KubernetesStore` to `SetupPoolDialogComponent`

- src/app/pages/reports-dashboard/reports-dashboard.component.ts
- src/app/pages/reports-dashboard/reports.service.ts
For testing, go to Reporting and check the `System Active Processes` chart on the CPU tab.
- Add a new chart - System Active Processes
- Fix condition for UPS menu item. For charts another ticket - https://ixsystems.atlassian.net/browse/NAS-125159
> NAS-125717 / 24.04 / Add processes charts to Reporting > CPU

- src/app/pages/credentials/backup-credentials/cloud-credentials-form/cloud-credentials-form.component.ts
- src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/base-provider-form.ts
- src/app/pages/data-protection/cloudsync/cloudsync-wizard/steps/cloudsync-provider/cloudsync-provider.component.html
- src/app/pages/data-protection/cloudsync/cloudsync-wizard/steps/cloudsync-provider/cloudsync-provider.component.ts
Testing: see ticket for instructions:
You should not stuck with loader.
> NAS-125768 / 24.04 / Cloud Credential Creation Error is not shown, instead infinite loading

- src/app/core/testing/utils/mock-auth.utils.ts
- src/app/enums/account-attribute.enum.ts
- src/app/interfaces/ds-cache.interface.ts
- src/app/modules/layout/components/topbar/power-menu/power-menu.component.html
- src/app/modules/layout/components/topbar/power-menu/power-menu.component.spec.ts
- src/app/modules/layout/components/topbar/power-menu/power-menu.component.ts
- src/app/modules/layout/components/topbar/user-menu/user-menu.component.html
- src/app/modules/layout/components/topbar/user-menu/user-menu.component.spec.ts
- src/app/modules/layout/components/topbar/user-menu/user-menu.component.ts
- src/app/pages/system/general-settings/manage-configuration-menu/manage-configuration-menu.component.html
- src/app/pages/system/general-settings/manage-configuration-menu/manage-configuration-menu.component.spec.ts
- src/app/pages/system/general-settings/manage-configuration-menu/manage-configuration-menu.component.ts
- src/app/pages/two-factor-auth/components/two-factor/two-factor.component.spec.ts
- src/app/pages/two-factor-auth/components/two-factor/two-factor.component.ts
- src/app/services/auth/auth.service.spec.ts
- src/app/services/auth/auth.service.ts
Testing: create a limited role and observe that Restart, Power Off and Reset to defaults option from General settings are not there.
> NAS-125756 / 24.04 / Hide Restart and other options from limited users

- src/assets/styles/other/_root-variables.scss
> NAS-125709 / 24.04 / Weird colors in VM list

- src/app/interfaces/api/api-call-directory.interface.ts
- src/app/pages/vm/vm-edit-form/vm-edit-form.component.spec.ts
- src/app/pages/vm/vm-edit-form/vm-edit-form.component.ts
- src/app/pages/vm/vm-wizard/vm-wizard.component.spec.ts
- src/app/pages/vm/vm-wizard/vm-wizard.component.ts
> NAS-125803 / 24.04 / Error received when trying to update existing VM

- src/app/modules/layout/components/topbar/user-menu/user-menu.component.html
- src/app/modules/layout/components/topbar/user-menu/user-menu.component.scss
> NAS-125716 / 24.04 / Misaligned icons in menues

- src/app/interfaces/api-directory.interface.ts
- src/app/pages/vm/vm-edit-form/vm-edit-form.component.spec.ts
- src/app/pages/vm/vm-edit-form/vm-edit-form.component.ts
- src/app/pages/vm/vm-wizard/vm-wizard.component.spec.ts
- src/app/pages/vm/vm-wizard/vm-wizard.component.ts
Backported.
**Testing**
See ticket
Original PR: https://github.com/truenas/webui/pull/9361
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125803
> NAS-125803 / 23.10.2 / Error received when trying to update existing VM (by bvasilenko)

- src/app/pages/api-keys/components/api-key-list/api-key-list.component.html
- src/app/pages/datasets/components/dataset-quotas/dataset-quotas-grouplist/dataset-quotas-grouplist.component.html
- src/app/pages/datasets/components/dataset-quotas/dataset-quotas-grouplist/dataset-quotas-grouplist.component.scss
- src/app/pages/datasets/components/dataset-quotas/dataset-quotas-userlist/dataset-quotas-userlist.component.html
- src/app/pages/datasets/components/dataset-quotas/dataset-quotas-userlist/dataset-quotas-userlist.component.scss
Testing: see new edit buttons on User and Group lists.
> NAS-125903 / 24.04 / Add edit icons to Quotas lists

- src/app/interfaces/api/api-call-directory.interface.ts
- src/app/pages/sharing/components/shares-dashboard/smb-card/smb-card.component.spec.ts
- src/app/pages/sharing/components/shares-dashboard/smb-card/smb-card.component.ts
- src/app/pages/sharing/smb/smb-form/smb-form.component.spec.ts
- src/app/pages/sharing/smb/smb-list/smb-list.component.ts
> NAS-125831 / 24.04 / Remove pool.dataset.path_in_locked_datasets

- src/app/pages/system/bootenv/bootenv-list/bootenv-list.component.html
- src/app/pages/system/bootenv/bootenv-list/bootenv-list.component.ts
> NAS-125125 / 24.04 / It is a requirement to specify source bootenv when creating a new bootenv in UI

- src/app/pages/dashboard/store/resources-usage-store.service.ts
Add check for undefined value before using array values
> NAS-125421 / 23.10.2 / Add check for undefined before concatenating values

- src/app/pages/dashboard/store/resources-usage-store.service.ts
Add check for undefined value before using array values
Original PR: https://github.com/truenas/webui/pull/9387
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125421
> NAS-125421 / 24.04 / Add check for undefined before concatenating values (by RehanY147)

- src/app/modules/ix-table2/components/ix-table-body/cells/ix-cell-actions/ix-cell-actions.component.scss
- src/app/modules/ix-table2/components/ix-table-body/ix-table-body.component.scss
- src/app/pages/credentials/backup-credentials/backup-credentials.component.scss
- src/app/pages/credentials/certificates-dash/certificates-dash.component.scss
- src/app/pages/directory-service/directory-services.component.scss
- src/app/pages/network/components/interfaces-card/interfaces-card.component.scss
- src/assets/styles/other/_material-reduction.scss
> NAS-125611 / 24.04 / Truncated display of IPv6 address in Network screen

- src/app/pages/datasets/components/dataset-capacity-management-card/space-management-chart/space-management-chart.component.html
Testing: see ticket and result 👇 :
Original PR: https://github.com/truenas/webui/pull/9400
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125488
> NAS-125488 / 23.10.2 / Datasets: Dataset space management does not show the exact number, it shows the number as a rounded number. (by AlexKarpov98)

- src/app/pages/sharing/smb/smb-form/smb-form.component.ts
See ticket for testing details
> NAS-125984 / 23.10.2 / Removing current name from validated smb share names list when editing

- src/app/services/task.service.ts
git cherry-pick -x 4a49197e9d3e3b7d6100c824ecdf689bde76d79f
git cherry-pick -x ccdd52b76c0003553afee4b73ec644dead7db716
Original PR: https://github.com/truenas/webui/pull/9403
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125777
> NAS-125777 / 24.04 / Added null check (by RehanY147)

- src/app/interfaces/api/api-call-directory.interface.ts
- src/app/pages/credentials/certificates-dash/certificate-acme-add/certificate-acme-add.component.spec.ts
- src/app/pages/credentials/certificates-dash/certificate-acme-add/certificate-acme-add.component.ts
- src/app/pages/credentials/certificates-dash/certificate-authority-add/certificate-authority-add.component.spec.ts
- src/app/pages/credentials/certificates-dash/certificate-authority-add/steps/ca-identifier-and-type/ca-identifier-and-type.component.spec.ts
- src/app/pages/credentials/certificates-dash/certificate-authority-add/steps/ca-identifier-and-type/ca-identifier-and-type.component.ts
- src/app/pages/credentials/certificates-dash/csr-add/csr-add.component.spec.ts
- src/app/pages/credentials/certificates-dash/csr-add/steps/csr-identifier-and-type/csr-identifier-and-type.component.spec.ts
- src/app/pages/credentials/certificates-dash/csr-add/steps/csr-identifier-and-type/csr-identifier-and-type.component.ts
- src/app/pages/credentials/certificates-dash/forms/certificate-add/certificate-add.component.spec.ts
- src/app/pages/credentials/certificates-dash/forms/certificate-add/steps/certificate-identifier-and-type/certificate-identifier-and-type.component.spec.ts
- src/app/pages/credentials/certificates-dash/forms/certificate-add/steps/certificate-identifier-and-type/certificate-identifier-and-type.component.ts
- src/assets/styles/other/_material-reduction.scss
Testing: check certificates for any regressions.
> NAS-126028 / 24.04 / Use new endpoints for certain crypto related endpoints in the UI

- src/app/modules/ix-forms/components/ix-explorer/ix-explorer.component.ts
- src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts
Testing: 
See ticket & use COBIA.
Now you should be able to get child nodes, as well fixed the path which is stored.
https://github.com/truenas/webui/assets/22980553/ed8f1321-61a6-491a-aada-09dcca8e461e
> NAS-125351 / 23.10.2 / In pCloud only directories in root dir can be selected, not lower levels

- src/app/modules/ix-forms/components/ix-slide-in/components/ix-chained-slide-in/ix-chained-slide-in.component.scss
- src/app/modules/ix-forms/components/ix-slide-in/components/ix-slide-in2/ix-slide-in2.component.scss
- src/app/modules/ix-forms/components/ix-slide-in/ix-slide-in.component.scss
- src/app/modules/search-input/components/advanced-search/tests/autocomplete.spec.ts
- src/app/modules/search-input/services/advanced-search-autocomplete.service.ts
- src/app/pages/account/groups/group-list/group-list.component.scss
- src/assets/styles/other/_material-reduction.scss
Result: 👇 
https://github.com/truenas/webui/assets/22980553/80ba457c-1e85-4688-bbd0-af6782df3447
_p.s: this PR is based on my previous one regarding UI fixes (https://github.com/truenas/webui/pull/9425)_
> NAS-126709 / 24.04 / Minor usability improvements for advanced search in audit

- src/app/modules/ix-forms/components/ix-explorer/ix-explorer.component.ts
- src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts
- src/app/pages/data-protection/cloudsync/cloudsync-wizard/steps/cloudsync-what-and-when/cloudsync-what-and-when.component.ts
As well I did a small refactoring to remove code duplication for CloudSync form.
> NAS-126723 / 24.04 / ix-explorer bug with comma once I clear input and select something 

- src/app/modules/search-input/components/search-input/search-input.component.spec.ts
**Testing**
Code review should be enough
> NAS-125707 / 24.04 / Fix unit tests

- src/app/interfaces/api/api-call-directory.interface.ts
- src/app/pages/storage/modules/devices/components/hardware-disk-encryption/hardware-disk-encryption.component.spec.ts
- src/app/pages/storage/modules/devices/components/hardware-disk-encryption/hardware-disk-encryption.component.ts
- src/app/pages/system/advanced/advanced-settings.component.spec.ts
- src/app/pages/system/advanced/advanced-settings.component.ts
**Testing**
1. **Storage** \> **Manage Devices** (Select any disk)
On card **Hardware Disk Encryption**, **Global SED Password** field
- is **Password is set** when `system.advanced.sed_global_password_is_set` returns `true`
- is **Password is not set** when `system.advanced.sed_global_password_is_set` returns `false`
2. **System Settings** \> **Advanced**
- **System Security** card exists when `system.security.info.fips_available` returns `true`
- **System Security** card does not exist when `system.security.info.fips_available` returns `false`
> NAS-126752 / 24.04 / Integrate new endpoints

- src/app/modules/common/dual-list/dual-list.component.scss
> NAS-125082 / 24.04 / Selected item are misaligned in dual list

- src/app/pages/apps/components/installed-apps/app-row/app-row.component.html
- src/app/pages/apps/components/installed-apps/app-row/app-row.component.spec.ts
Testing: see m40 Apps for example.
> NAS-126710 / 24.04 / Memory conversion error in apps

- src/app/pages/account/groups/groups.routing.ts
- src/app/pages/audit/audit.routing.ts
- src/app/pages/sharing/sharing.routing.ts
> NAS-126824 / 24.04 / Add new indication to some pages

- src/app/enums/schema.enum.ts
- src/app/helpers/get-dynamic-form-schema-node.ts
- src/app/helpers/object-keys-to-human-readable.helper.spec.ts
- src/app/helpers/object-keys-to-human-readable.helper.ts
- src/app/pages/audit/components/event-data-details-card/event-data-details-card.component.spec.ts
- src/app/pages/credentials/certificates-dash/forms/acmedns-form/acmedns-form.component.spec.ts
- src/app/pages/credentials/certificates-dash/forms/acmedns-form/acmedns-form.component.ts
- src/app/pages/reports-dashboard/components/exporters/reporting-exporters-form/reporting-exporters-form.component.spec.ts
- src/app/pages/reports-dashboard/components/exporters/reporting-exporters-form/reporting-exporters-form.component.ts
Testing: See ticket + ticket comments.
Check `Reporting Exporter Screen` and abbreviation handling. (like ID, IP, IPs, IDs, API)
As well check that `boolean` type is rendered as checkbox and `integer` type is an input type=number.
I did the same for `acmedns-form` as well.
> NAS-125407 / 24.04 / Polish Add Reporting Exporter Screen

- src/app/pages/apps/components/installed-apps/installed-apps.component.ts
Testing: see ticket, try start / stop apps and keep sorted by Status.
Result (sorted realtime):
https://github.com/truenas/webui/assets/22980553/58fc01f2-758b-463a-aa3f-51fb12dd8549
> NAS-125762 / 23.10.2 / Installed apps sorting unsorts itself

- src/app/pages/system/general-settings/general-settings.component.ts
Testing: see ticket and result: 👇 
https://github.com/truenas/webui/assets/22980553/9bfe6363-425a-4bde-93b8-6d97d0ec2cfd
> NAS-126801 / 24.10 / Accessing the email set up a second time requires a screen refresh when accessed and also the UI reverts to the General page

- scripts/ui/ui.ts
- src/app/modules/feedback/components/file-ticket-licensed/file-ticket-licensed.component.html
- src/app/modules/ix-table2/components/ix-table-body/cells/ix-cell-state-button/ix-cell-state-button.component.ts
- src/app/pages/apps/components/available-apps/available-apps-header/available-apps-header.component.ts
- src/app/pages/apps/components/catalogs/catalog-add-form/catalog-add-form.component.ts
- src/app/pages/apps/components/catalogs/catalogs.component.ts
- src/app/pages/apps/components/catalogs/manage-catalog-summary/manage-catalog-summary-dialog.component.scss
- src/app/pages/apps/components/chart-wizard/chart-wizard.component.ts
- src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.ts
- src/app/pages/apps/components/installed-apps/app-rollback-modal/app-rollback-modal.component.ts
- src/app/pages/apps/components/installed-apps/app-settings-button/app-settings-button.component.ts
- src/app/pages/apps/components/installed-apps/installed-apps.component.ts
- src/app/pages/apps/components/installed-apps/kubernetes-settings/kubernetes-settings.component.ts
- src/app/pages/apps/components/pod-select-logs/pod-select-logs-dialog.component.ts
- src/app/pages/apps/components/select-pool-dialog/select-pool-dialog.component.ts
- src/app/pages/apps/services/applications.service.ts
- src/app/pages/apps/store/apps-filter-store.service.ts
- src/app/pages/apps/store/apps-store.service.ts
- src/app/pages/apps/store/installed-apps-store.service.ts
- src/app/pages/apps/store/kubernetes-store.service.spec.ts
- src/app/pages/apps/store/kubernetes-store.service.ts
- src/app/pages/credentials/backup-credentials/cloud-credentials-card/cloud-credentials-card.component.html
- src/app/services/error-handler.service.ts
Testing: 
See ticket.
for example try changing request to get MiddleWare errors.
You should see improved Error Handling For Apps. 
Check that loaders are stopping on errors.
Example:
https://github.com/truenas/webui/assets/22980553/35826242-0036-4efe-a20f-ec60dd2be4a7
> NAS-125604 / 24.04 / Poor error handling in apps

- scripts/ui/ui.ts
- src/app/modules/feedback/components/file-ticket-licensed/file-ticket-licensed.component.html
- src/app/modules/ix-table2/components/ix-table-body/cells/ix-cell-state-button/ix-cell-state-button.component.ts
- src/app/pages/apps/components/available-apps/available-apps-header/available-apps-header.component.ts
- src/app/pages/apps/components/catalogs/catalog-add-form/catalog-add-form.component.ts
- src/app/pages/apps/components/catalogs/catalogs.component.ts
- src/app/pages/apps/components/catalogs/manage-catalog-summary/manage-catalog-summary-dialog.component.scss
- src/app/pages/apps/components/chart-wizard/chart-wizard.component.ts
- src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.ts
- src/app/pages/apps/components/installed-apps/app-rollback-modal/app-rollback-modal.component.ts
- src/app/pages/apps/components/installed-apps/app-settings-button/app-settings-button.component.ts
- src/app/pages/apps/components/installed-apps/installed-apps.component.ts
- src/app/pages/apps/components/installed-apps/kubernetes-settings/kubernetes-settings.component.ts
- src/app/pages/apps/components/pod-select-logs/pod-select-logs-dialog.component.ts
- src/app/pages/apps/components/select-pool-dialog/select-pool-dialog.component.ts
- src/app/pages/apps/services/applications.service.ts
- src/app/pages/apps/store/apps-filter-store.service.ts
- src/app/pages/apps/store/apps-store.service.ts
- src/app/pages/apps/store/installed-apps-store.service.ts
- src/app/pages/apps/store/kubernetes-store.service.spec.ts
- src/app/pages/apps/store/kubernetes-store.service.ts
- src/app/pages/credentials/backup-credentials/cloud-credentials-card/cloud-credentials-card.component.html
- src/app/services/error-handler.service.ts
Testing: 
See ticket.
for example try changing request to get MiddleWare errors.
You should see improved Error Handling For Apps. 
Check that loaders are stopping on errors.
Example:
https://github.com/truenas/webui/assets/22980553/35826242-0036-4efe-a20f-ec60dd2be4a7
Original PR: https://github.com/truenas/webui/pull/9466
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125604
> NAS-125604 / 24.04-RC.1 / Poor error handling in apps (by AlexKarpov98)

- src/app/services/websocket-connection.service.ts
The original issue is fixed in #9473
Small improvements. Code review is enough.
- Removed unnecessary UntilDestroy from singleton service. 
- Improved code readability.
> NAS-125603 / 24.10 / Rearrange websocket service code

- src/app/pages/apps/components/installed-apps/app-details-panel/app-details-panel.component.ts
- src/app/pages/apps/components/installed-apps/installed-apps.component.html
- src/app/pages/apps/components/installed-apps/installed-apps.component.ts
Testing: 
see ticket for details (2 video)
https://ixsystems.atlassian.net/browse/NAS-126933
> NAS-126933 / 24.10 / Apps sorting breaks after viewing details and closing panel (smaller devices) & selection via Enter is not working

- src/app/pages/credentials/kmip/kmip.component.html
- src/app/pages/credentials/kmip/kmip.component.spec.ts
- src/app/pages/credentials/kmip/kmip.component.ts
Testing: check /credentials/kmip on a readonly role.
> NAS-126920 / 24.10 / Roles for KMIP

- src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.ts
- src/app/store/system-info/system-info.effects.ts
For testing, ensure uptime values are still updating on the system information widgets.
> NAS-125605 / 24.10 / Do not reload system.info every 30 seconds

- src/app/pages/credentials/kmip/kmip.component.html
- src/app/pages/credentials/kmip/kmip.component.spec.ts
- src/app/pages/credentials/kmip/kmip.component.ts
Testing: check /credentials/kmip on a readonly role.
Original PR: https://github.com/truenas/webui/pull/9486
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126920
> NAS-126920 / 24.04-RC.1 / Roles for KMIP (by undsoft)

- src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.ts
- src/app/store/system-info/system-info.effects.ts
For testing, ensure uptime values are still updating on the system information widgets. 
Original PR: https://github.com/truenas/webui/pull/9473
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125605
> NAS-125605 / 24.04-RC.1 / Do not reload system.info every 30 seconds (by denysbutenko)

- src/app/modules/feedback/components/similar-issues/similar-issues.component.html
- src/app/modules/feedback/components/similar-issues/similar-issues.component.scss
- src/app/modules/feedback/components/similar-issues/similar-issues.component.spec.ts
- src/app/modules/feedback/components/similar-issues/similar-issues.component.ts
> NAS-126856 / 24.10 / Improve similar tickets search results

- src/app/pages/audit/components/audit/audit.component.scss
Testing:
see ticket & audit page header on page reload.
> NAS-127050 / 24.10 / Audit header on load time is partially invisible

- src/app/pages/audit/components/audit/audit.component.scss
Testing:
see ticket & audit page header on page reload.
Original PR: https://github.com/truenas/webui/pull/9547
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127050
> NAS-127050 / 24.04-RC.1 / Audit header on load time is partially invisible (by AlexKarpov98)

- src/app/modules/feedback/components/file-review/file-review.component.ts
- src/app/modules/feedback/components/file-ticket-licensed/file-ticket-licensed.component.ts
- src/app/modules/feedback/components/file-ticket/file-ticket.component.ts
> NAS-127037 / 24.10 / Add maxlength validation for feedback and tickets

- src/app/modules/feedback/components/file-review/file-review.component.ts
- src/app/modules/feedback/components/file-ticket-licensed/file-ticket-licensed.component.ts
- src/app/modules/feedback/components/file-ticket/file-ticket.component.ts
Check ticket details
Original PR: https://github.com/truenas/webui/pull/9555
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127037
> NAS-127037 / 24.04-RC.1 / Add maxlength validation for feedback and tickets (by denysbutenko)

- src/app/pages/directory-service/components/idmap-form/idmap-form.component.ts
- src/app/pages/directory-service/components/idmap-list/idmap-list.component.ts
- src/app/pages/directory-service/components/kerberos-settings/kerberos-settings.component.ts
- src/app/pages/directory-service/directory-services.component.ts
- src/app/pages/sharing/smb/smb-list/smb-list.component.ts
- src/app/services/focus.service.ts
- src/app/services/ix-slide-in.service.ts
Testing:
I noticed that focus is lost if we update form and return to the table (html element is rerendered and it's reference is lost, I got an Idea to depend on data-test attribute, since it's unchanging)
As well did some fixes for Directory Services.
Original PR: https://github.com/truenas/webui/pull/9597
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126976
> NAS-126976 / 24.04-RC.1 / Focus service updates to correctly handle table reloading and loosing html ref & other improvements (by AlexKarpov98)

- .github/actions/prepare/action.yml
> NAS-127153 / 24.10 / Upgrade node in CI

- src/app/modules/ix-table2/classes/async-data-provider/async-data-provider.ts
- src/app/pages/system/alert-service/alert-service-list/alert-service-list.component.ts
Testing: 
See ticket
Result:
https://github.com/truenas/webui/assets/22980553/363a1f5a-4639-414e-bd4a-ff569adb86e2
> NAS-127170 / 24.10 / ix-table2 jumps when something is updated because of data hiding and spinner

- src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts
**Testing**
Please see ticket
Original PR: https://github.com/truenas/webui/pull/9550
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126985
> NAS-126985 / 24.04-RC.1 / Fix: Folder does not show up when editing already created cloud sync tasks (Pull/copy) (by bvasilenko)

- src/app/pages/datasets/components/dataset-form/dataset-form.component.spec.ts
- src/app/pages/datasets/components/dataset-form/dataset-form.component.ts
- src/app/pages/datasets/components/dataset-form/sections/name-and-options-section/name-and-options-section.component.html
- src/app/pages/datasets/components/dataset-form/sections/name-and-options-section/name-and-options-section.component.ts
> NAS-127071 / 24.04-RC.1 / Add additional check for dialog display

- src/app/pages/system/general-settings/gui/gui-form/gui-form.component.ts
Testing: 
See ticket
Result:
https://github.com/truenas/webui/assets/22980553/795e6dc9-94b1-4b7e-9113-da0e9d9e4001
Original PR: https://github.com/truenas/webui/pull/9599
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127061
> NAS-127061 / 24.04-RC.1 / Read only user : GUI theme change error but applied (by AlexKarpov98)

- src/app/modules/ix-forms/components/ix-file-input/ix-file-input.component.html
- src/app/modules/ix-forms/components/ix-file-input/ix-file-input.component.scss
Testing: (focus state was added, as well check ENTER clicking to trigger actions)
Original PR: https://github.com/truenas/webui/pull/9616
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127172
> NAS-127172 / 24.04-RC.1 / Add focus state to ix-file-input component (by AlexKarpov98)

- src/app/modules/jobs/store/job.selectors.ts
- src/app/pages/jobs/jobs-list/jobs-list.component.ts
git cherry-pick -x 488cb4b86cd7147517621d9f871d313f36672bdd
git cherry-pick -x 26bdd96c9d78c4c5155f3deecb3a53f991cbc386
Original PR: https://github.com/truenas/webui/pull/9632
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127152
> NAS-127152 / 24.04-RC.1 / Update jobs list to exclude transient jobs (by denysbutenko)

- src/app/interfaces/smart-test.interface.ts
- src/app/pages/storage/modules/disks/components/smart-results/smart-results.component.ts
**Testing**
1. Go to **Storage \> Pool Disk Health card \> View All S.M.A.R.T. tests**
2. Select to expand the view of 1 of the results
**Expected Result** Only selected row expands, regardless of other rows 
Original PR: https://github.com/truenas/webui/pull/9562
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127013
> NAS-127013 / 24.04-RC.1 / Fix smart result table expanding (by bvasilenko)

- src/app/modules/ix-forms/components/ix-explorer/ix-explorer.component.ts
**Testing**
See steps to replicate in the ticket
> NAS-126982 / 24.10 / Fix loading of children for ix-explorer

- src/app/directives/common/requires-roles/requires-roles.directive.ts
- src/app/pages/services/services.component.html
- src/app/pages/services/services.component.ts
Testing: test services page. You may need to create a privilege with READONLY + role to test. Or just mock.
If your new cannot login, you may need to mock `processLoginResult` in `AuthService`.
> NAS-127108 / 24.10 / Add narrower checks for sharing roles

- src/app/pages/account/groups/privilege/privilege-form/privilege-form.component.spec.ts
- src/app/pages/account/groups/privilege/privilege-form/privilege-form.component.ts
backported
**Testing**
See ticket
Original PR: https://github.com/truenas/webui/pull/9641
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127233
> NAS-127233 / 24.04-RC.1 / Do not allow build-in privileges to be edited (by bvasilenko)

- src/app/pages/reports-dashboard/components/exporters/reporting-exporters-list/reporting-exporters-list.component.html
- src/app/pages/reports-dashboard/components/exporters/reporting-exporters-list/reporting-exporters-list.component.spec.ts
- src/app/pages/reports-dashboard/components/exporters/reporting-exporters-list/reporting-exporters-list.component.ts
> NAS-127010 / 24.10 / Readonly user > Reporting exporters enabled/disabled controls active

- src/app/pages/reports-dashboard/components/exporters/reporting-exporters-list/reporting-exporters-list.component.html
- src/app/pages/reports-dashboard/components/exporters/reporting-exporters-list/reporting-exporters-list.component.spec.ts
- src/app/pages/reports-dashboard/components/exporters/reporting-exporters-list/reporting-exporters-list.component.ts
git cherry-pick -x ec4958442a4679fd12c6b225e8db44595bb2d65f
git cherry-pick -x 2dae906a596535e5464f15df5be57e93f7d6c8e3
git cherry-pick -x 923f4b22cd4668cae4b962d207370fb7f8465cc4
Testing: 
See ticket,
Original PR: https://github.com/truenas/webui/pull/9665
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127010
> NAS-127010 / 24.04-RC.1 / Readonly user > Reporting exporters enabled/disabled controls active (by AlexKarpov98)

- src/app/modules/ix-forms/components/ix-explorer/ix-explorer.component.ts
**Testing**
See steps to replicate in the ticket
Original PR: https://github.com/truenas/webui/pull/9649
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126982
> NAS-126982 / 24.04-RC.1 / Fix loading of children for ix-explorer (by bvasilenko)

- src/app/directives/common/requires-roles/requires-roles-wrapper.component.scss
- src/app/pages/storage/components/dashboard-pool/zfs-health-card/zfs-health-card.component.html
- src/app/pages/storage/components/dashboard-pool/zfs-health-card/zfs-health-card.component.scss
- src/app/pages/storage/components/dashboard-pool/zfs-health-card/zfs-health-card.component.ts
> NAS-127011 / 24.10 / Readonly user > Storage > ZFS Health - Edit Auto Trim > Save button enabled

- src/app/directives/common/requires-roles/requires-roles-wrapper.component.scss
- src/app/pages/storage/components/dashboard-pool/zfs-health-card/zfs-health-card.component.html
- src/app/pages/storage/components/dashboard-pool/zfs-health-card/zfs-health-card.component.scss
- src/app/pages/storage/components/dashboard-pool/zfs-health-card/zfs-health-card.component.ts
Testing: 
See ticket,
Original PR: https://github.com/truenas/webui/pull/9666
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127011
> NAS-127011 / 24.04-RC.1 / Readonly user > Storage > ZFS Health - Edit Auto Trim > Save button enabled (by AlexKarpov98)

- src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.html
- src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts
**Testing**
See ticket for replication steps
> NAS-127297 / 23.10.3 / Fix Folder does not show up when editing already created cloud sync tasks (Pull/copy)

- src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.html
- src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts
**Testing**
See ticket for replication steps
Original PR: https://github.com/truenas/webui/pull/9675
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127297
> NAS-127297 / 23.10.2 / Fix Folder does not show up when editing already created cloud sync tasks (Pull/copy) (by bvasilenko)

- src/app/pages/sharing/smb/smb-list/smb-list.component.spec.ts
- src/app/pages/sharing/smb/smb-list/smb-list.component.ts
> NAS-127049 / 24.10 / Read only user > SMB shares table > Delete - confirmationbox Unshare is not disabled

- src/app/core/pipes/uptime.pipe.spec.ts
- src/app/core/pipes/uptime.pipe.ts
Unit tests cover changes. Check for possible regressions.
> NAS-127342 / 24.10 / Hide seconds when uptime exceeds 1 hour

- src/app/pages/apps/components/docker-images/docker-image-update-dialog/docker-image-update-dialog.component.spec.ts
- src/app/pages/apps/components/docker-images/docker-image-update-dialog/docker-image-update-dialog.component.ts
- src/app/pages/apps/components/docker-images/docker-images-list/docker-images-list.component.ts
Fix condition and updated tests.
> NAS-121641 / 24.10 / Fix container image update dialog

- src/app/directives/common/common-directives.module.ts
- src/app/directives/common/requires-roles/requires-roles-wrapper.component.html
- src/app/directives/common/requires-roles/requires-roles-wrapper.component.scss
- src/app/directives/common/requires-roles/requires-roles-wrapper.component.ts
- src/app/modules/ix-forms/components/ix-slide-in/components/ix-modal-header/ix-modal-header.component.html
- src/app/modules/ix-forms/components/ix-slide-in/components/ix-modal-header/ix-modal-header.component.scss
- src/app/modules/layout/components/topbar/power-menu/power-menu.component.html
- src/app/pages/datasets/components/dataset-details-card/dataset-details-card.component.html
- src/app/pages/datasets/modules/encryption/components/zfs-encryption-card/zfs-encryption-card.component.html
- src/app/pages/datasets/modules/snapshots/snapshot-details-row/snapshot-details-row.component.html
- src/app/pages/services/components/service-ftp/service-ftp.component.html
- src/app/pages/services/components/service-ftp/service-ftp.component.scss
- src/app/pages/services/components/service-nfs/service-nfs.component.html
- src/app/pages/services/components/service-nfs/service-nfs.component.scss
- src/app/pages/services/components/service-smart/service-smart.component.html
- src/app/pages/services/components/service-smb/service-smb.component.html
- src/app/pages/services/components/service-smb/service-smb.component.scss
- src/app/pages/services/components/service-snmp/service-snmp.component.html
- src/app/pages/services/components/service-snmp/service-snmp.component.scss
- src/app/pages/services/components/service-ssh/service-ssh.component.html
- src/app/pages/services/components/service-ups/service-ups.component.html
- src/app/pages/services/services.component.html
- src/app/pages/services/services.component.scss
- src/app/pages/storage/components/dashboard-pool/zfs-health-card/zfs-health-card.component.scss
- src/app/pages/storage/modules/devices/components/zfs-info-card/zfs-info-card.component.html
- src/app/pages/system/update/update.component.scss
Strike-through on restricted elements was replaced with a lock icon as per feedback we received.
Testing: check if lock icon is not looking nice somewhere.
> NAS-127417 / 24.04-RC.1 / Lock icon for restricted elements

- src/app/pages/apps/components/docker-images/docker-image-update-dialog/docker-image-update-dialog.component.spec.ts
- src/app/pages/apps/components/docker-images/docker-image-update-dialog/docker-image-update-dialog.component.ts
- src/app/pages/apps/components/docker-images/docker-images-list/docker-images-list.component.ts
Fix condition and updated tests.
Original PR: https://github.com/truenas/webui/pull/9704
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121641
> NAS-121641 / 24.04-RC.1 / Fix container image update dialog (by denysbutenko)

- src/app/modules/ix-forms/components/ix-slide-in/components/ix-chained-slide-in/ix-chained-slide-in.component.scss
- src/app/modules/ix-forms/components/ix-slide-in/components/ix-slide-in2/ix-slide-in2.component.scss
- src/app/modules/ix-forms/components/ix-slide-in/ix-slide-in.component.scss
For testing, check UI on screen width < 600px.
Example:
Original PR: https://github.com/truenas/webui/pull/9712
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127435
> NAS-127435 / 24.04-RC.1 / Fix layout width on mobile screens (by denysbutenko)

- src/app/pages/credentials/certificates-dash/csr-list/csr-list.component.html
Original PR: https://github.com/truenas/webui/pull/9700
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127377
> NAS-127377 / 24.04-RC.1 / The Add button on the Certificates and Certificate Signing Requests has the same data-test tag. (by AlexKarpov98)

- src/app/pages/directory-service/components/idmap-list/idmap-list.component.spec.ts
- src/app/pages/directory-service/components/idmap-list/idmap-list.component.ts
- src/app/pages/directory-service/directory-services.component.html
- src/app/pages/system/advanced/cron/cron-list/cron-list.component.spec.ts
Portion of the code was removed because it wasn't connected to anything. I've check git history, it appears not to be needed anymore.
> NAS-127447 / 24.10 / Adding tests to IdmapListComponent

- src/app/pages/dashboard/components/widget-sys-info/simple-failover-btn.component.html
- src/app/pages/dashboard/components/widget-sys-info/simple-failover-btn.component.ts
- src/app/pages/system/failover-settings/failover-settings.component.html
- src/app/pages/system/failover-settings/failover-settings.component.spec.ts
- src/app/pages/system/failover-settings/failover-settings.component.ts
> NAS-127424 / 24.10 / Add role checks for failover

- src/app/modules/ix-tree/components/tree-virtual-scroll-view/tree-virtual-scroll-view.component.scss
- src/app/modules/ix-tree/components/tree-virtual-scroll-view/tree-virtual-scroll-view.component.ts
- src/app/pages/datasets/components/dataset-management/dataset-management.component.html
- src/app/pages/datasets/components/dataset-management/dataset-management.component.scss
- src/app/pages/datasets/components/dataset-node/dataset-node.component.scss
Testing: 
See ticket, go to the datasets page http://localhost:4200/datasets
See result 👇 :
https://github.com/truenas/webui/assets/22980553/a97cc230-a5d2-48c0-a8d0-c545f62cce13
Original PR: https://github.com/truenas/webui/pull/9711
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127420
> NAS-127420 / 24.04-RC.1 / Some datasets are not visible on the bottom of the Dataset list (by AlexKarpov98)

- src/app/pages/dashboard/components/widget-sys-info/simple-failover-btn.component.html
- src/app/pages/dashboard/components/widget-sys-info/simple-failover-btn.component.ts
- src/app/pages/system/failover-settings/failover-settings.component.html
- src/app/pages/system/failover-settings/failover-settings.component.spec.ts
- src/app/pages/system/failover-settings/failover-settings.component.ts
git cherry-pick -x 24ec1f04b41cfe234d62c4ae66b9e266dd8bb14e
git cherry-pick -x 9dff1702688c39f3e4a9f5d3f282d35073a911e1
Testing:
Original PR: https://github.com/truenas/webui/pull/9720
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127424
> NAS-127424 / 24.04-RC.1 / Add role checks for failover (by AlexKarpov98)

- src/app/pages/data-protection/cloudsync/cloudsync-list/cloudsync-list.component.ts
- src/app/pages/data-protection/cloudsync/cloudsync-task-card/cloudsync-task-card.component.ts
Testing: see ticket & try with CloudSync Tasks
> NAS-127400 / 24.10 / Cloud Sync Tasks: State does not refresh after stopping

- src/app/pages/data-protection/cloudsync/cloudsync-list/cloudsync-list.component.ts
- src/app/pages/data-protection/cloudsync/cloudsync-task-card/cloudsync-task-card.component.ts
Testing: see ticket & try with CloudSync Tasks
Original PR: https://github.com/truenas/webui/pull/9744
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127400
> NAS-127400 / 24.04-RC.1 / Cloud Sync Tasks: State does not refresh after stopping (by AlexKarpov98)

- .github/workflows/main.yml
> NAS-127578 / 24.10 / Fix validate translations CI job

- src/app/pages/account/groups/groups.module.ts
> NAS-XXYYXX: Double IxForms Module import

- src/app/pages/apps/components/catalogs/catalog-add-form/catalog-add-form.component.spec.ts
- src/app/pages/apps/components/catalogs/catalog-add-form/catalog-add-form.component.ts
- src/app/pages/apps/components/catalogs/catalogs.component.spec.ts
- src/app/pages/apps/components/catalogs/catalogs.component.ts
- src/app/pages/apps/components/catalogs/manage-catalog-summary/manage-catalog-summary-dialog.component.html
- src/app/pages/apps/components/catalogs/manage-catalog-summary/manage-catalog-summary-dialog.component.ts
- src/app/pages/apps/components/docker-images/pull-image-form/pull-image-form.component.spec.ts
- src/app/pages/apps/components/docker-images/pull-image-form/pull-image-form.component.ts
- src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.spec.ts
- src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.ts
- src/app/pages/apps/components/installed-apps/app-rollback-modal/app-rollback-modal.component.spec.ts
- src/app/pages/apps/components/installed-apps/app-rollback-modal/app-rollback-modal.component.ts
- src/app/pages/apps/components/installed-apps/app-settings-button/app-settings-button.component.spec.ts
- src/app/pages/apps/components/installed-apps/app-settings-button/app-settings-button.component.ts
- src/app/pages/apps/components/installed-apps/installed-apps.component.ts
- src/app/pages/apps/components/select-pool-dialog/select-pool-dialog.component.spec.ts
- src/app/pages/apps/components/select-pool-dialog/select-pool-dialog.component.ts
Changes are scoped to the Apps section only. Check affected components for regressions.
> NAS-127371 / 24.10 / Refactor Apps module to use new jobDialog

- src/app/modules/dialog/components/error-dialog/error-dialog.component.html
- src/app/modules/dialog/components/error-dialog/error-dialog.component.scss
> NAS-127662 / 24.10 / Add copy button for error traceback

- src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.ts
**Testing**
Connect to machine specified in the ticket's commentaries and verify the **System Settings > Enclosure** page for regressions
> NAS-123838 / 24.04.0 / Add support for legacy model ES24N

- src/app/enums/boot-environment-active.enum.ts
- src/app/interfaces/bootenv.interface.ts
- src/app/pages/storage/modules/disks/components/disk-list/disk-list.component.ts
- src/app/pages/system/bootenv/bootenv-list/bootenv-list.component.html
- src/app/pages/system/bootenv/bootenv-list/bootenv-list.component.scss
- src/app/pages/system/bootenv/bootenv-list/bootenv-list.component.spec.ts
- src/app/pages/system/bootenv/bootenv-list/bootenv-list.component.ts
**Testing**
Go to **System Settings > Boot** and test for regressions
> NAS-127443 / 24.10 / Refactor bootenv-list.component List to ix-table2

- src/app/pages/apps/components/chart-wizard/chart-wizard.component.html
- src/app/pages/apps/components/chart-wizard/chart-wizard.component.scss
- src/app/pages/apps/components/chart-wizard/chart-wizard.component.ts
- src/assets/styles/other/_material-reduction.scss
Testing: see result, as well I improved UX by showing highlighted selected blocks as well.
https://github.com/truenas/webui/assets/22980553/ccf731bd-9aab-433d-b59d-bfcd6411e743
> NAS-127546 / 24.10 / App Install Page Layout is incorrect

- src/app/pages/system/update/components/update-actions-card/update-actions-card.component.ts
**Testing**
Follow the repro steps mentioned in the ticket
> NAS-127668 / 24.10 / Fix `saveConfigurationIfNecessary` method

- src/app/pages/vm/vm-list/vm-list.component.ts
https://ixsystems.atlassian.net/browse/NAS-127628
> NAS-127628 / 24.04.0 / Fix disabled controls on VM page

- src/app/pages/apps/components/chart-wizard/chart-wizard.component.html
- src/app/pages/apps/components/chart-wizard/chart-wizard.component.scss
- src/app/pages/apps/components/chart-wizard/chart-wizard.component.ts
- src/assets/styles/other/_material-reduction.scss
git cherry-pick -x 74c0eafbbf95a8521bb068d121e2e9244b68463c
git cherry-pick -x cbcb1870a35739aa298c7b29e7238f4ea2858cbd
Testing: see result, as well I improved UX by showing highlighted selected blocks as well.
https://github.com/truenas/webui/assets/22980553/ccf731bd-9aab-433d-b59d-bfcd6411e743
Original PR: https://github.com/truenas/webui/pull/9751
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127546
> NAS-127546 / 24.04.0 / App Install Page Layout is incorrect (by AlexKarpov98)

- src/app/pages/system/advanced/save-debug-button/save-debug-button.component.html
- src/app/pages/system/advanced/save-debug-button/save-debug-button.component.ts
`Save Dubug` is allowed operation.
> NAS-127670 / 24.10 / Save debug is disabled but debug can still be downloaded

- src/app/pages/system/advanced/save-debug-button/save-debug-button.component.html
- src/app/pages/system/advanced/save-debug-button/save-debug-button.component.ts
`Save Dubug` is allowed operation.
Original PR: https://github.com/truenas/webui/pull/9788
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127670
> NAS-127670 / 24.04.0 / Save debug is disabled but debug can still be downloaded (by AlexKarpov98)

- src/app/helpers/operators/filter-async.operator.ts
- src/app/modules/common/dialog/start-service-dialog/start-service-dialog.component.html
- src/app/modules/common/dialog/start-service-dialog/start-service-dialog.component.ts
- src/app/pages/dashboard/components/widget-sys-info/widget-sys-info.component.ts
- src/app/pages/services/services.component.html
- src/app/pages/services/services.component.ts
- src/app/pages/system/update/update.component.ts
- src/app/services/services.service.ts
- src/app/store/eula/eula.effects.ts
- src/app/store/network-interfaces/network-interfaces.effects.ts
- src/app/store/services/services.effects.spec.ts
- src/app/store/services/services.effects.ts
Testing: see ticket. Start service dialog will no longer be shown is user won't be able to do anything in it.
Original PR: https://github.com/truenas/webui/pull/9793
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127719
> NAS-127719 / 24.04-RC.1 / Do not offer service dialogs if user does not have access (by undsoft)

- .vscode/launch.json
- src/app/pages/datasets/modules/permissions/containers/dataset-acl-editor/dataset-acl-editor.component.spec.ts
- src/app/pages/sharing/smb/smb-status/components/smb-lock-list/smb-lock-list.component.spec.ts
- src/app/pages/sharing/smb/smb-status/components/smb-notification-list/smb-notification-list.component.spec.ts
- src/app/pages/sharing/smb/smb-status/components/smb-session-list/smb-session-list.component.spec.ts
- src/app/pages/sharing/smb/smb-status/components/smb-share-list/smb-share-list.component.spec.ts
- src/app/pages/storage/modules/disks/components/disk-wipe-dialog/disk-wipe-dialog.component.spec.ts
- src/app/pages/system/advanced/init-shutdown/init-shutdown-card/init-shutdown-card.component.spec.ts
- src/app/pages/system/advanced/sysctl/sysctl-card/sysctl-card.component.spec.ts
- src/app/pages/system/general-settings/ntp-server/ntp-server-card/ntp-server-card.component.html
- src/app/pages/system/general-settings/ntp-server/ntp-server-card/ntp-server-card.component.scss
- src/app/pages/system/general-settings/ntp-server/ntp-server-card/ntp-server-card.component.spec.ts
- src/app/pages/system/general-settings/ntp-server/ntp-server-card/ntp-server-card.component.ts
Testing: 
Go to http://localhost:4200/system/general, see NTP Servers table updated.
> NAS-127765 / 24.10 / Refactor `NTP Servers` to ix-table2

- src/app/pages/dashboard/components/widget-backup/widget-backup.component.scss
- src/app/pages/dashboard/components/widget-backup/widget-backup.component.ts
> NAS-127703 / 24.04.0 / Tick icon and Pop out icon are displayed overlapping on Dashboard Backup Tasks Widget

- src/app/pages/dashboard/components/widget-backup/widget-backup.component.scss
- src/app/pages/dashboard/components/widget-backup/widget-backup.component.ts
Result:
Original PR: https://github.com/truenas/webui/pull/9797
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127703
> NAS-127703 / 24.10 / Tick icon and Pop out icon are displayed overlapping on Dashboard Backup Tasks Widget (by AlexKarpov98)

- src/app/pages/account/groups/groups.routing.ts
- src/app/pages/audit/audit.routing.ts
- src/app/pages/sharing/sharing.routing.ts
Original PR: https://github.com/truenas/webui/pull/9792
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126935
> NAS-126935 / 24.10 / Remove new prompts (by undsoft)

- src/app/pages/dashboard/components/widget-backup/widget-backup.component.scss
- src/app/pages/dashboard/components/widget-backup/widget-backup.component.ts
Result:
Original PR: https://github.com/truenas/webui/pull/9797
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127703
> NAS-127703 / 24.04-RC.1 / Tick icon and Pop out icon are displayed overlapping on Dashboard Backup Tasks Widget (by AlexKarpov98)

- src/app/pages/sharing/iscsi/portal/portal-form/portal-form.component.ts
Backported 
Original PR: https://github.com/truenas/webui/pull/9817
> NAS-127782 / 24.04.0 / Fix WebUI fails to remove IP address from iSCSI portal

- src/app/pages/apps/components/chart-wizard/chart-wizard.component.spec.ts
- src/app/pages/apps/components/installed-apps/installed-apps.component.spec.ts
- src/app/pages/sharing/smb/smb-form/smb-form.component.spec.ts
- src/app/services/schema/app-schema.service.spec.ts
> NAS-127823 / 24.10 / Clean Up Installed Apps .spec file

- src/app/pages/sharing/iscsi/portal/portal-form/portal-form.component.spec.ts
- src/app/pages/sharing/iscsi/portal/portal-form/portal-form.component.ts
**Testing**
See replication steps in the ticket
> NAS-127782 / 24.10 / Fix WebUI fails to remove IP address from iSCSI portal

- src/app/pages/dashboard/components/widget-backup/widget-backup.component.ts
**Testing**
Follow replication steps described in the ticket
> NAS-127736 / 24.04.0 / Fix failed and success states on backup tasks widget

- src/app/services/focus.service.ts
Testing:
Result 👇 
https://github.com/truenas/webui/assets/22980553/f9a6fcc4-f9dd-4277-bdf6-2de72a566937
> NAS-127857 / 24.10 / Focus back to trigger button fails

- src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.ts
Reverts the condition because it turned out to be an incorrect solution.
> NAS-127022: Revert drive identification condition

- src/app/pages/sharing/iscsi/portal/portal-form/portal-form.component.spec.ts
- src/app/pages/sharing/iscsi/portal/portal-form/portal-form.component.ts
**Testing**
See replication steps in the ticket
Original PR: https://github.com/truenas/webui/pull/9817
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127782
> NAS-127782 / 24.04-BETA.1 / Fix WebUI fails to remove IP address from iSCSI portal (by bvasilenko)

- src/app/pages/sharing/iscsi/portal/portal-form/portal-form.component.spec.ts
**Testing**
See replication steps in the ticket
Original PR: https://github.com/truenas/webui/pull/9817
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127782
> NAS-127782 / 24.04.0 / Fix WebUI fails to remove IP address from iSCSI portal (by bvasilenko)

- src/app/pages/dashboard/components/widget-backup/widget-backup.component.ts
**Testing**
Follow replication steps described in the ticket
Original PR: https://github.com/truenas/webui/pull/9805
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127736
> NAS-127736 / 24.10 / Fix failed and success states on backup tasks widget (by bvasilenko)

- src/app/modules/ix-forms/services/form-error-handler.service.ts
- src/app/pages/sharing/smb/smb-form/smb-form.component.ts
This is a quick solution to opening the Advanced Options if there's a validation field for one of the fields hidden in Basic Options mode. Proper solution will be provided by https://ixsystems.atlassian.net/browse/NAS-127892
> NAS-127778 / 24.04.0 / Added check to open Advanced Options on error

- src/app/pages/dashboard/components/dashboard/dashboard.component.ts
- src/app/pages/dashboard/store/dashboard-store.service.ts
> NAS-127796 / 24.04.0 / On Dragonfish nightly and RC.1 the reordering of the dashboard changes when going somewhere else and going to the dashboard.

- src/app/pages/reports-dashboard/components/line-chart/line-chart.component.ts
- src/app/pages/reports-dashboard/components/report/report.component.html
- src/app/pages/reports-dashboard/components/report/report.component.ts
- src/app/pages/reports-dashboard/interfaces/report.interface.ts
> NAS-127854 / 24.04.0 / Show value only for selected report

- src/app/pages/system/advanced/storage/storage-settings-form/storage-settings-form.component.ts
> NAS-127855 / 24.04.0 / Fix dialog multiple showing

- src/app/modules/feedback/services/feedback.service.spec.ts
- src/app/modules/feedback/services/feedback.service.ts
Solution: I increased timing so now user will be able to click the link successfully. (10 sec now)
> NAS-127844 / 24.04.0 / HA Support ticket: Open Ticket windows closes before I can click the button

- src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.ts
> NAS-127923 / 24.04.0 / Enclosure graphics/info are not loading for m60s

- src/app/pages/reports-dashboard/components/line-chart/line-chart.component.spec.ts
- src/app/pages/reports-dashboard/components/line-chart/line-chart.component.ts
- src/app/pages/reports-dashboard/components/report/report.component.html
- src/app/pages/reports-dashboard/components/report/report.component.spec.ts
- src/app/pages/reports-dashboard/components/report/report.component.ts
- src/app/pages/reports-dashboard/interfaces/report.interface.ts
- src/app/pages/reports-dashboard/reports-dashboard.module.ts
- src/app/pages/reports-dashboard/services/plotter.service.ts
- src/app/pages/reports-dashboard/services/smooth-plotter.service.ts
Backported.
**Testing**
See ticket
Original PR: https://github.com/truenas/webui/pull/9846
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127854
> NAS-127854 / 24.10 / Show value only for selected report (by bvasilenko)

- src/app/core/testing/utils/mock-window.utils.ts
- src/app/pages/reports-dashboard/reports.service.spec.ts
- src/app/pages/reports-dashboard/reports.service.ts
> NAS-128057 / 24.10 / Only open netdata once

- src/app/core/testing/utils/mock-window.utils.ts
- src/app/pages/reports-dashboard/reports.service.spec.ts
- src/app/pages/reports-dashboard/reports.service.ts
See ticket.
Original PR: https://github.com/truenas/webui/pull/9891
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128057
> NAS-128057 / 24.04.0 / Only open netdata once (by undsoft)

- src/app/interfaces/advanced-config.interface.ts
Backported
Original PR: https://github.com/truenas/webui/pull/9885
> NAS-127882 / 24.04.0 / Fix GPU endpoint usage

- src/app/pages/dashboard/components/widget-network/widget-network.component.ts
Testing: see ticket, and result:
https://github.com/truenas/webui/assets/22980553/7c24adf7-6cfc-452e-ac9f-409bf76aee06
> NAS-127913 / 24.10 / Network Graph does not update with live results unless refresh browser

- src/app/pages/dashboard/components/widget-network/widget-network.component.ts
Testing: see ticket, and result:
https://github.com/truenas/webui/assets/22980553/7c24adf7-6cfc-452e-ac9f-409bf76aee06
Original PR: https://github.com/truenas/webui/pull/9904
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127913
> NAS-127913 / 24.04.0 / Network Graph does not update with live results unless refresh browser (by AlexKarpov98)

- src/app/helptext/about.ts
> NAS-128148 / 13.3 / Forum link change

- src/app/modules/global-search/services/ui-search.service.spec.ts
- src/app/modules/global-search/services/ui-search.service.ts
https://github.com/truenas/webui/assets/22980553/d5972f1d-df51-4b2a-82ff-c17db3f77a15
> NAS-128073 / 24.10 / Add support for synonyms in global search

- src/app/pages/storage/volumes/datasets/dataset-form/dataset-form.component.ts
- src/app/pages/storage/volumes/zvol/zvol-form/zvol-form.component.ts
> NAS-122461 / 13.3 / Revert encryption value when Cancel button  is pressed

- src/app/helptext/about.ts
- src/app/pages/dashboard-old/components/widget-help/widget-help.component.html
- src/app/pages/dashboard/components/dashboard/dashboard.component.html
- src/app/pages/dashboard/components/dashboard/dashboard.component.scss
- src/app/pages/dashboard/components/widget-group/widget-group.component.html
- src/app/pages/dashboard/components/widget-group/widget-group.component.scss
- src/app/pages/dashboard/components/widget-group/widget-group.component.ts
- src/app/pages/dashboard/dashboard.module.ts
- src/app/pages/dashboard/types/widget-category.enum.ts
- src/app/pages/dashboard/types/widget.interface.ts
- src/app/pages/dashboard/widgets/all-widgets.constant.ts
- src/app/pages/dashboard/widgets/help/widget-help/widget-help.component.html
- src/app/pages/dashboard/widgets/help/widget-help/widget-help.component.scss
- src/app/pages/dashboard/widgets/help/widget-help/widget-help.component.spec.ts
- src/app/pages/dashboard/widgets/help/widget-help/widget-help.component.ts
- src/app/pages/dashboard/widgets/help/widget-help/widget-help.definition.ts
See help widget on new dashboard.
> NAS-128287 / 24.10 / Porting help widget to new dashboard

- src/app/pages/system/view-enclosure/stores/enclosure-store.service.ts
Testing: see machine hostname in the ticket comments. Check that enclosure view doesn't break.
> NAS-128303 / 24.04.0 / Fixing enclosure view for m50 systems

- src/app/pages/system/view-enclosure/stores/enclosure-store.service.ts
Testing: see machine hostname in the ticket comments. Check that enclosure view doesn't break.
Original PR: https://github.com/truenas/webui/pull/9954
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128303
> NAS-128303 / 24.04.1 / Fixing enclosure view for m50 systems (by undsoft)

- src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.ts
**Summary**
Corrected image of the front panel at 2 places on the Enclosure page.
**Testing**
1. Connect to machine with ES24N available at 10.220.16.104 
2. See ticket for replication steps and expected result
> NAS-128334 / 24.04.1 / Fix chassis for ES24N

- src/app/pages/system/old-view-enclosure/components/enclosure-disks/enclosure-disks.component.ts
**Summary**
Corrected image of the front panel at 2 places on the Enclosure page.
**Testing**
1. Connect to machine with ES24N available at 10.220.16.104 
2. See ticket for replication steps and expected result
Original PR: https://github.com/truenas/webui/pull/9956
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128334
> NAS-128334 / 24.10 / Fix chassis for ES24N (by bvasilenko)

- src/app/modules/layout/components/topbar/user-menu/user-menu.component.html
- src/app/modules/layout/components/topbar/user-menu/user-menu.component.ts
Not sure why changing user password was limited to a full admin, but this is incorrect.
> NAS-128397 / 24.04.0 / Restore change password form for limited users

- src/app/modules/layout/components/topbar/user-menu/user-menu.component.html
- src/app/modules/layout/components/topbar/user-menu/user-menu.component.ts
Not sure why changing user password was limited to a full admin, but this is incorrect.
Original PR: https://github.com/truenas/webui/pull/9972
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128397
> NAS-128397 / 24.10 / Restore change password form for limited users (by undsoft)

- src/app/pages/dashboard-old/components/widget-memory/widget-memory.component.scss
- src/app/pages/dashboard/widgets/memory/widget-memory/widget-memory.component.scss
- src/app/pages/dashboard/widgets/memory/widget-memory/widget-memory.component.ts
- src/app/pages/dashboard/widgets/memory/widget-memory/widget-memory.definition.ts
Testing: see result & ticket.
https://github.com/truenas/webui/assets/22980553/9e9a2b7a-1c13-44fe-88bf-4100bb7f5a87
> NAS-128384 / 24.10 / Add support for additional sizes to memory widget

- src/app/pages/account/groups/group-list/group-list.component.spec.ts
- src/app/pages/account/groups/group-list/group-list.component.ts
> NAS-128406 / 24.10 / Groups default "Allow Sudo Commands" incorrectly = Yes

- src/app/pages/system/view-enclosure/components/enclosure-disks/enclosure-disks.component.ts
**Testing**
See ticket for replication steps and expected result
> NAS-128442 / 24.04.1 / Fix enclosure finding bug

- src/app/pages/dashboard/widgets/memory/widget-memory/widget-memory.component.ts
- src/app/services/websocket-connection.service.ts
- src/app/services/ws.service.spec.ts
- src/app/services/ws.service.ts
Testing instructions in the ticket
> NAS-128449 / 24.10 / Fix issues with subscriptions

- src/app/pages/network/components/interface-form/interface-form.component.spec.ts
- src/app/pages/network/components/interface-form/interface-form.component.ts
> NAS-128343 / 24.10 / Checking Autoconfigure IPv6 hides IPv4 Aliases

- src/app/pages/network/components/interface-form/interface-form.component.spec.ts
- src/app/pages/network/components/interface-form/interface-form.component.ts
Original PR: https://github.com/truenas/webui/pull/9999
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128343
> NAS-128343 / 24.04.1 / Checking Autoconfigure IPv6 hides IPv4 Aliases (by AlexKarpov98)

- src/app/pages/dashboard/components/widget-group-form/widget-group-form.component.ts
- src/app/pages/dashboard/components/widget-group/widget-group-mixin.scss
Go to the WidgetGroupForm on the new dashboard and switch between different possible layouts.
on `master`, the preview doesn't update properly. This PR fixes that.
> NAS-128689 / 24.10 / Fix layout preview issues for WidgetGroupFormComponent

- package.json
- src/app/core/testing/classes/mock-websocket.service.ts
- src/app/pages/account/groups/privilege/privilege-form/privilege-form.component.ts
- src/app/pages/apps/components/chart-wizard/chart-wizard.component.ts
- tsconfig.json
- yarn.lock
Just checking where tests will fail.
> NAS-128635 / 24.10 / Experimenting with immutability

- src/app/interfaces/api/api-event-directory.interface.ts
- src/app/interfaces/chart-release.interface.ts
- src/app/pages/apps/components/apps-scope-wrapper.component.ts
- src/app/pages/apps/components/installed-apps/app-row/app-row.component.html
- src/app/pages/apps/components/installed-apps/app-row/app-row.component.spec.ts
- src/app/pages/apps/components/installed-apps/app-row/app-row.component.ts
- src/app/pages/apps/components/installed-apps/installed-apps.component.html
- src/app/pages/apps/components/installed-apps/installed-apps.component.spec.ts
- src/app/pages/apps/components/installed-apps/installed-apps.component.ts
- src/app/pages/apps/services/applications.service.ts
- src/app/pages/apps/store/apps-statistics.service.spec.ts
- src/app/pages/apps/store/apps-statistics.service.ts
- src/app/pages/apps/store/apps-store.service.ts
- src/app/pages/apps/store/installed-apps-store.service.spec.ts
- src/app/pages/apps/store/installed-apps-store.service.ts
Testing: see https://ixsystems.atlassian.net/browse/NAS-128515 and https://ixsystems.atlassian.net/browse/NAS-127859
> NAS-128515 / 24.04.1 / Fixes stats logic on Installed apps page

- src/app/interfaces/api/api-event-directory.interface.ts
- src/app/interfaces/chart-release.interface.ts
- src/app/pages/apps/components/apps-scope-wrapper.component.ts
- src/app/pages/apps/components/installed-apps/app-row/app-row.component.html
- src/app/pages/apps/components/installed-apps/app-row/app-row.component.spec.ts
- src/app/pages/apps/components/installed-apps/app-row/app-row.component.ts
- src/app/pages/apps/components/installed-apps/installed-apps.component.html
- src/app/pages/apps/components/installed-apps/installed-apps.component.spec.ts
- src/app/pages/apps/components/installed-apps/installed-apps.component.ts
- src/app/pages/apps/services/applications.service.ts
- src/app/pages/apps/store/apps-statistics.service.spec.ts
- src/app/pages/apps/store/apps-statistics.service.ts
- src/app/pages/apps/store/apps-store.service.ts
- src/app/pages/apps/store/installed-apps-store.service.spec.ts
- src/app/pages/apps/store/installed-apps-store.service.ts
git cherry-pick -x 6ca8cf30b01e3e3a7eaec3489180e65a16325914
git cherry-pick -x 995904e37ee1b5d065be46d0bb37abb39425c211
git cherry-pick -x 0339900595d1c10ed49eafbdf06230de79cdda86
Testing: see https://ixsystems.atlassian.net/browse/NAS-128515 and https://ixsystems.atlassian.net/browse/NAS-127859
Original PR: https://github.com/truenas/webui/pull/10020
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128515
> NAS-128515 / 24.10 / Fixes stats logic on Installed apps page (by undsoft)

- src/app/pages/system/advanced/system-security/system-security-form/system-security-form.component.ts
> NAS-128395 / 24.04.1 / Rebooting on FIPS changes

- src/app/pages/system/advanced/system-security/system-security-form/system-security-form.component.ts
git cherry-pick -x 92e3105b322457ac2f4990ce310af38b59b3ad16
git cherry-pick -x 9afab09bf60570b61e75d23f23596456ba3e0584
Testing – see ticket.
Original PR: https://github.com/truenas/webui/pull/10033
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128395
> NAS-128395 / 24.10 / Rebooting on FIPS changes (by undsoft)

- src/assets/i18n/de.json
Just a small typo (capitalized).
> German language typo

- src/app/modules/ix-forms/classes/group-combobox-provider.ts
- src/app/modules/ix-forms/classes/smb-group-combobox-provider.ts
- src/app/pages/sharing/smb/smb-acl/smb-acl.component.html
**Testing**
Please see ticket for replication steps and expected result
> NAS-128488 / 24.10 / Cleanup `initialOptions` after adding

- src/app/modules/ix-forms/classes/group-combobox-provider.ts
- src/app/modules/ix-forms/classes/smb-group-combobox-provider.ts
- src/app/pages/sharing/smb/smb-acl/smb-acl.component.html
**Testing**
Please see ticket for replication steps and expected result
Original PR: https://github.com/truenas/webui/pull/10030
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128488
> NAS-128488 / 24.04.2 / Cleanup `initialOptions` after adding (by bvasilenko)

- src/app/modules/feedback/components/feedback-dialog/feedback-dialog.component.spec.ts
- src/app/modules/feedback/components/feedback-dialog/feedback-dialog.component.ts
You can see that Suggestion option is no longer there in Feedback dialog on non-enterprise systems.
> NAS-128881 / 24.04.1 / Removes suggestions from feedback form

- src/app/enums/reporting.enum.ts
- src/app/pages/reports-dashboard/components/report/report.component.ts
- src/app/pages/reports-dashboard/reports-dashboard.component.ts
> NAS-128971 / 24.10 / Remove swap utilization graph in reporting memory section

- src/app/app.component.ts
- src/app/modules/global-search/components/global-search-trigger/global-search-trigger.component.html
- src/app/modules/global-search/components/global-search-trigger/global-search-trigger.component.scss
- src/app/modules/global-search/components/global-search-trigger/global-search-trigger.component.spec.ts
- src/app/modules/global-search/components/global-search-trigger/global-search-trigger.component.ts
- src/app/modules/global-search/global-search.module.ts
- src/app/modules/keyboard-shortcut/keyboard-shortcut.component.scss
- src/app/modules/keyboard-shortcut/keyboard-shortcut.component.spec.ts
- src/app/modules/keyboard-shortcut/keyboard-shortcut.component.ts
- src/app/services/detect-browser.service.spec.ts
- src/app/services/detect-browser.service.ts
See hint and test shortcut for global search.
> NAS-129134 / 24.10 / Add keyboard shortcut to global search

- src/app/modules/custom-selects/cloud-credentials-select/cloud-credentials-select.component.ts
- src/app/modules/custom-selects/ssh-credentials-select/ssh-credentials-select.component.ts
- src/app/pages/dashboard/components/dashboard/dashboard.component.ts
- src/app/services/ix-chained-slide-in.service.ts
> NAS-129162 / 24.10 / Improve type safety for ChainedComponentResponse interface

- src/app/store/ha-info/ha-info.selectors.ts
Blindly fixes Cannot read something of null errors.
> NAS-129226 / 24.04.2 / Fix HA selectors

- src/app/modules/global-search/components/global-search/global-search.component.spec.ts
- src/app/modules/global-search/components/global-search/global-search.component.ts
**Testing**
See ticket for replication steps and expected result
> NAS-129163 / 24.10 / Restore functionality when search input is focused

- src/app/pages/system/general-settings/gui/gui-form/gui-form.component.ts
> NAS-129278 / 24.10 / Fix GUI form failed to load

- src/assets/ui-searchable-elements.json
- src/environments/environment.interface.ts
- src/environments/environment.prod.ts
> NAS-129432 / 24.10 / Fix environment.ts for production builds

- src/app/pages/dashboard/components/widget-network/widget-network.component.scss
- src/app/pages/dashboard/store/resources-usage-store.service.ts
> NAS-129334 / 24.04.2 / Fix Dashboard is not loading

- src/app/core/testing/mock-enclosure/enclosure-templates/utils/disk.utils.ts
- src/app/core/testing/mock-enclosure/enclosure-templates/utils/pool.utils.ts
- src/app/core/testing/mock-enclosure/enums/mock-storage.enum.ts
- src/app/core/testing/mock-enclosure/mock-storage-generator.utils.ts
Testing: use `yarn ui mock-enclosure` and see old enclosure UI.
> NAS-129557 / 24.10 / Add fill all slots mocking scenario

- src/app/pages/sharing/iscsi/target/target-form/target-form.component.html
- src/app/pages/sharing/iscsi/target/target-form/target-form.component.ts
- src/app/pages/sharing/smb/smb-form/smb-form.component.html
- src/app/pages/sharing/smb/smb-form/smb-form.component.ts
Try to edit some field on a iSCSI Target except name, it should not block
> NAS-129391 / 24.04.2 / Can't edit iSCSI Target on SCALE

- src/app/views/sessions/signin/signin.component.html
- src/app/views/sessions/signin/signin.component.scss
- src/app/views/sessions/signin/store/signin.store.ts
"Fixes" login page on recent middleware.
> NAS-129711 / 24.10 / Fix login page due to API changes

- src/app/helpers/operators/accumulate-loading-state.helper.ts
- src/app/pages/sharing/components/shares-dashboard/smb-card/smb-card.component.ts
**Testing**
**Steps to Reproduce**
1. Navigate to Shares page
2. toggle share 'enabled' slider to 'disabled'
3. At this share click 'pencil' icon
**Expected Result**
right panel displays and 'enabled' checkbox is disabled
> NAS-129198 / 24.10 / Update enabled field after change

- src/app/pages/reports-dashboard/reports-dashboard.component.ts
> NAS-129556 / 24.10 / Incorrect URL on reporting section

- src/app/helpers/operators/accumulate-loading-state.helper.ts
- src/app/pages/sharing/components/shares-dashboard/smb-card/smb-card.component.ts
**Testing**
**Steps to Reproduce**
1. Navigate to Shares page
2. toggle share 'enabled' slider to 'disabled'
3. At this share click 'pencil' icon
**Expected Result**
right panel displays and 'enabled' checkbox is disabled
Original PR: https://github.com/truenas/webui/pull/10218
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129198
> NAS-129198 / 24.04.3 / Update enabled field after change (by bvasilenko)

- src/app/pages/reports-dashboard/components/report/report.component.ts
> NAS-128992 / 24.10 / On Electric Eel nightly reporting graph does not load without hovering the mouse on  graphs area.

- src/app/pages/data-protection/snapshot-task/snapshot-task-card/snapshot-task-card.component.scss
> NAS-129010 / 24.10 / Buttons are not aligned in Data Protection

- src/app/modules/scheduler/components/scheduler/scheduler.component.html
> NAS-128701 / 24.10 / ixTest updates in scheduler

- src/app/pages/audit/components/audit/audit.component.html
- src/app/pages/audit/components/audit/audit.component.scss
> NAS-129902 / 24.10 / Audit Layout is missing grid gap

- src/app/pages/sharing/smb/smb-form/smb-validator.service.ts
**Replication steps:**
1. Make sure there are no local or domain users with SMB enabled. (See ticket for details on this step.)
Or as alternative, add mocks to the `SmbValidationService` to simulate "TrueNAS server must be joined to Active Directory or have at least one local SMB user before creating an SMB share" error.
3. Go to Shares > Add SMB
4. Select a Path
**Expected result:** 
A non-intrusive warning pop-up with the text "TrueNAS server must be joined to Active Directory or have at least one local SMB user before creating an SMB share",
which does not block the user from continuing.
> NAS-127520 / 24.10 / SMB validator: do not prevent user from continuing in one particular case

- src/app/modules/feedback/services/feedback.service.spec.ts
- src/app/modules/feedback/services/feedback.service.ts
You can use mocks to test what message is being sent to the server, but changes are pretty self-explanatory.
Original PR: https://github.com/truenas/webui/pull/10302
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129964
> NAS-129964 / 24.04.3 / Remove host id from bug reports (by undsoft)

- src/app/modules/layout/components/admin-layout/admin-layout.component.html
- src/app/modules/layout/components/copyright-line/copyright-line.component.html
- src/app/modules/layout/components/copyright-line/copyright-line.component.spec.ts
- src/app/modules/layout/components/copyright-line/copyright-line.component.ts
- src/app/pages/dashboard/widgets/help/widget-help/widget-help.component.html
- src/app/pages/dashboard/widgets/help/widget-help/widget-help.component.scss
- src/app/pages/dashboard/widgets/help/widget-help/widget-help.component.spec.ts
- src/app/pages/dashboard/widgets/help/widget-help/widget-help.component.ts
- src/app/services/system-general.service.ts
- src/app/store/system-info/system-info.actions.ts
- src/app/store/system-info/system-info.effects.ts
- src/app/store/system-info/system-info.reducer.ts
- src/app/store/system-info/system-info.selectors.ts
1. Updated styles
2. Updated related components
3. Updated unit tests
4. Added systemBuildTime selector
5. Marked systemGeneralService methods as depracated
For testing check help widget for every available size.
> NAS-130026 / 24.10 / Fix styles for Help widget for different sizes

- .github/PULL_REQUEST_TEMPLATE/ix_employee_template.md
There is no way to check this until this is merged, so I'll merge as is.
> NAS-130077: Add PR template

- .github/PULL_REQUEST_TEMPLATE/ix_employee_template.md
- .github/pull_request_template.md
> NAS-130077 / 24.10 / PR template

- .github/pull_request_template.md
For now we only have Documentation.
> Bugclerk template for downstream areas

- src/app/modules/pipes/or-not-available/or-not-available.pipe.spec.ts
- src/app/modules/pipes/or-not-available/or-not-available.pipe.ts
- src/app/pages/apps/apps.module.ts
- src/app/pages/apps/components/app-detail-view/app-available-info-card/app-available-info-card.component.html
- src/app/pages/apps/components/app-detail-view/app-available-info-card/app-available-info-card.component.spec.ts
- src/app/pages/apps/components/app-detail-view/app-details-header/app-details-header.component.html
- src/app/pages/apps/components/app-detail-view/app-details-header/app-details-header.component.spec.ts
- src/app/pages/apps/components/app-detail-view/app-resources-card/app-resources-card.component.html
- src/app/pages/apps/components/available-apps/available-apps.component.spec.ts
- src/app/pages/apps/components/installed-apps/app-containers-card/app-containers-card.component.html
- src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.html
- src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.spec.ts
- src/app/pages/apps/components/installed-apps/app-row/app-row.component.html
- src/app/pages/dashboard/widgets/cpu/widget-cpu/widget-cpu.component.html
- src/app/pages/dashboard/widgets/network/widget-network/widget-network.component.html
- src/app/pages/dashboard/widgets/storage/widget-pool/widget-pool.component.html
- src/app/pages/datasets/components/dataset-details-card/dataset-details-card.component.html
- src/app/pages/datasets/components/dataset-details-card/dataset-details-card.component.spec.ts
- src/app/pages/datasets/datasets.module.ts
- src/app/pages/datasets/modules/permissions/containers/permissions-card/permissions-card.component.html
- src/app/pages/datasets/modules/snapshots/snapshot-details-row/snapshot-details-row.component.html
- src/app/pages/jobs/job-logs-row/job-logs-row.component.html
- src/app/pages/storage/components/dashboard-pool/disk-health-card/disk-health-card.component.html
- src/app/pages/storage/components/dashboard-pool/topology-card/topology-card.component.html
- src/app/pages/storage/modules/devices/components/disk-info-card/disk-info-card.component.html
- src/app/pages/storage/modules/devices/components/disk-info-card/disk-info-card.component.spec.ts
- src/app/pages/storage/modules/devices/devices.module.ts
And additional control flow syntax migration.
Testing: code review should be sufficient.
> NAS-130067 / 24.10 / Introduce OrNotAvailable pipe

- src/app/services/storage.service.ts
> NAS-333333 / 24.10 / Remove Unused Code

- src/app/pages/network/network.component.ts
**Changes:**
Added missing `cdr.markForCheck()`
**Testing:**
See ticket.
> NAS-130024 / 24.10 / On Electric Eel nightly the Interface Test Changes does not appear on freshly open browser.

- src/app/modules/alerts/components/alerts-panel/alerts-panel.component.html
- src/app/modules/alerts/components/alerts-panel/alerts-panel.component.ts
- src/app/pages/account/groups/privilege/privilege-form/privilege-form.component.ts
- src/app/pages/datasets/modules/permissions/components/save-as-preset-modal/save-as-preset-modal.component.html
- src/app/pages/network/components/ipmi-card/ipmi-events-dialog/ipmi-events-dialog.component.html
- src/app/pages/network/components/ipmi-card/ipmi-events-dialog/ipmi-events-dialog.component.ts
- src/app/pages/system/alert-config-form/alert-config-form.component.html
- src/app/pages/system/alert-config-form/alert-config-form.component.ts
- src/app/services/user.service.ts
**Changes:**
See ticket.
**Testing:**
Test some of the affected places.
> NAS-129865 / 24.10 / Simplify user and group queries

- src/app/modules/scheduler/components/scheduler/scheduler.component.html
- src/app/modules/scheduler/components/scheduler/scheduler.component.spec.ts
- src/assets/styles/other/_tn-styles.scss
**Changes:**
see ticket, Visual:
**Testing:**
Try using Schedule input.
> NAS-130167 / 24.10 / Schedule mat option may look better

- src/app/pages/credentials/backup-credentials/cloud-credentials-form/cloud-credentials-form.component.spec.ts
- src/app/pages/credentials/backup-credentials/cloud-credentials-form/cloud-credentials-form.component.ts
- src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/azure-provider-form/azure-provider-form.component.ts
- src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/backblaze-b2-provider-form/backblaze-b2-provider-form.component.ts
- src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/base-provider-form.ts
- src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/ftp-provider-form/ftp-provider-form.component.ts
- src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/google-cloud-provider-form/google-cloud-provider-form.component.ts
- src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/google-drive-provider-form/google-drive-provider-form.component.ts
- src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/google-photos-provider-form/google-photos-provider-form.component.ts
- src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/http-provider-form/http-provider-form.component.ts
- src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/mega-provider-form/mega-provider-form.component.ts
- src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/openstack-swift-provider-form/openstack-swift-provider-form.component.ts
- src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/pcloud-provider-form/pcloud-provider-form.component.ts
- src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/s3-provider-form/s3-provider-form.component.ts
- src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/sftp-provider-form/sftp-provider-form.component.ts
- src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/storj-provider-form/storj-provider-form.component.ts
- src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/token-provider-form/token-provider-form.component.ts
- src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/webdav-provider-form/webdav-provider-form.component.ts
> NAS-130087 / 24.10 / EE: Access Key and Secret Access Key of Cloud Credentials do not display unless clicking the Help icon

- .github/workflows/main.yml
- .github/workflows/resort-translations.yml
**Changes:**
This may fix resort action for our translations.
**Testing:**
Code review only. We'll know if it works once this is merged.
> NAS-127001 / 24.10 / Fix resort translations action for external contributors

- src/app/pages/storage/modules/pool-manager/utils/generate-vdevs/generate-vdevs.service.ts
**Changes:**
Fixes a minor undefined/null JS bug on the pool creation wizard
**Testing:**
On master, when adding a new vdev to an existing pool, you can see the described bug in the console and can't submit the form even though form is valid.
> NAS-130322 / 24.10 / Fix null bug

- src/app/pages/system/enclosure/components/enclosure-side/enclosure-side.component.spec.ts
- src/app/pages/system/enclosure/components/enclosure-side/enclosure-side.component.ts
_We need a unique url for each enclosure._
> NAS-130349 / 24.10 / Animation glitch when switching between enclosures with the same svg

- src/app/interfaces/api/api-call-directory.interface.ts
- src/app/interfaces/disk.interface.ts
- src/app/pages/storage/modules/devices/components/devices/devices.component.html
- src/app/pages/storage/modules/devices/components/devices/devices.component.ts
- src/app/pages/storage/modules/devices/components/disk-details-panel/disk-details-panel.component.html
- src/app/pages/storage/modules/devices/components/disk-details-panel/disk-details-panel.component.ts
- src/app/pages/storage/modules/devices/components/smart-info-card/smart-info-card.component.html
- src/app/pages/storage/modules/devices/components/smart-info-card/smart-info-card.component.spec.ts
- src/app/pages/storage/modules/devices/components/smart-info-card/smart-info-card.component.ts
- src/app/pages/storage/modules/devices/stores/devices-store.service.spec.ts
- src/app/pages/storage/modules/devices/stores/devices-store.service.ts
**Changes:**
Fix TODO. Add check if disk supports smart. Update tests.
**Testing:**
Open Devices page and check if `Run Manual Test` button appears correctly.
> NAS-130412 / 24.10 / Check smart supports before showing Run Manual Test button

- src/app/modules/forms/ix-forms/components/ix-slide-in/ix-slide-in.component.ts
- src/app/pages/apps/components/catalog-settings/catalog-settings.component.html
- src/app/pages/apps/components/catalog-settings/catalog-settings.component.spec.ts
- src/app/pages/apps/components/catalog-settings/catalog-settings.component.ts
- src/app/pages/apps/components/installed-apps/app-settings-button/app-settings-button.component.ts
- src/app/pages/apps/store/apps-store.service.ts
- src/app/services/ix-slide-in.service.ts
**Changes:**
Changing trains in apps under Settings will now reload the list of available apps.
**Testing:**
☝🏼
> NAS-130468 / 24.10 / Changing catalog trains should trigger resync

- src/app/constants/catalog.constants.ts
- src/app/pages/apps/components/app-wizard/app-wizard.component.spec.ts
- src/app/pages/apps/components/app-wizard/app-wizard.component.ts
- src/app/pages/apps/components/available-apps/app-card/app-card.component.spec.ts
- src/app/pages/apps/components/available-apps/available-apps-header/available-apps-header.component.html
- src/app/pages/apps/components/available-apps/available-apps-header/available-apps-header.component.ts
- src/app/pages/apps/components/available-apps/custom-app-button/custom-app-button.component.spec.ts
- src/app/pages/apps/components/available-apps/custom-app-button/custom-app-button.component.ts
- src/app/pages/apps/components/installed-apps/app-bulk-upgrade/app-bulk-upgrade.component.spec.ts
- src/app/pages/apps/components/installed-apps/app-bulk-upgrade/app-bulk-upgrade.component.ts
- src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.html
- src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.spec.ts
- src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.ts
- src/app/pages/apps/components/installed-apps/app-rollback-modal/app-rollback-modal.component.spec.ts
- src/app/pages/apps/components/installed-apps/app-row/app-row.component.spec.ts
- src/app/pages/apps/components/installed-apps/app-row/app-row.component.ts
- src/app/pages/apps/components/installed-apps/app-upgrade-dialog/app-upgrade-dialog.component.ts
- src/app/pages/apps/components/installed-apps/installed-apps.component.spec.ts
- src/app/pages/apps/components/installed-apps/installed-apps.component.ts
- src/app/pages/apps/components/installed-apps/pod-shell/pod-shell.component.ts
- src/app/pages/apps/components/pod-select-logs/pod-select-logs-dialog.component.spec.ts
- src/app/pages/apps/components/pod-select-logs/pod-select-logs-dialog.component.ts
- src/app/pages/apps/services/applications.service.spec.ts
- src/app/pages/apps/services/applications.service.ts
**Changes:**
Fixes incorrect condition for Start/Stop button and renames some references.
**Testing:**
> NAS-130518 / 24.10 / Fix Start/Stop button

- src/app/interfaces/api/api-call-directory.interface.ts
- src/app/pages/apps/components/catalog-settings/catalog-settings.component.html
- src/app/pages/apps/components/catalog-settings/catalog-settings.component.spec.ts
- src/app/pages/apps/components/catalog-settings/catalog-settings.component.ts
**Changes:**
Train settings in apps now shows a list of checkboxes.
> NAS-130524 / 24.10 / Change train selection to checkbox group

- src/app/store/eula/eula.effects.spec.ts
- src/app/store/eula/eula.effects.ts
**Changes:**
Fix condition to show EULA dialog for enterprise users on first loading.
**Testing:**
Ensure you can see EULA dialog on fresh system when first time log-in
> NAS-130572 / 25.04 / Fix EULA condition to display

- src/app/constants/server-series.constant.ts
- src/app/pages/dashboard/widgets/system/common/widget-sys-info.utils.spec.ts
- src/app/pages/dashboard/widgets/system/common/widget-sys-info.utils.ts
**Changes:**
Code cleanup
**Testing:**
No testing is required. Code review only.
> NAS-130419 / 25.04 / Remove unused isRackMount function

- src/app/modules/layout/components/copyright-line/copyright-line.component.ts
**Changes:**
Use default value for copyright-line
**Testing:**
Check ticket
> NAS-130296 / 24.10 / Update copyright-line

- src/app/store/eula/eula.effects.spec.ts
- src/app/store/eula/eula.effects.ts
**Changes:**
Fix condition to show EULA dialog for enterprise users on first loading.
**Testing:**
Ensure you can see EULA dialog on fresh system when first time log-in
Original PR: https://github.com/truenas/webui/pull/10440
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130572
> NAS-130572 / 24.10-RC.1 / Fix EULA condition to display (by denysbutenko)

- src/app/pages/storage/components/dashboard-pool/pool-usage-card/pool-usage-card.component.spec.ts
- src/app/services/theme/theme.service.ts
Original PR: https://github.com/truenas/webui/pull/10443
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130386
> NAS-130386 / 24.10-RC.1 / Theme is too persistent (by AlexKarpov98)

- src/app/pages/apps/components/docker-images/docker-images-list/docker-images-list.component.html
- src/app/pages/apps/components/docker-images/docker-images-list/docker-images-list.component.scss
- src/app/pages/apps/components/docker-images/docker-images-list/docker-images-list.component.spec.ts
- src/app/pages/apps/components/docker-images/docker-images-list/docker-images-list.component.ts
**Changes:**
Added bulk delete operation for docker images list
**Testing:**
Go to **Apps > Images** page, and verify bulk deletion
> NAS-130533 / 25.04 / Add bulk delete operation for docker images list

- src/assets/styles/other/_tn-styles.scss
> NAS-130586 / 25.04 / Unround corners in main menu

- src/assets/styles/other/_tn-styles.scss
Testing:
Original PR: https://github.com/truenas/webui/pull/10464
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130586
> NAS-130586 / 24.10-RC.1 / Unround corners in main menu (by AlexKarpov98)

- src/app/pages/dashboard/services/dashboard.store.spec.ts
- src/app/pages/dashboard/services/dashboard.store.ts
- src/app/pages/dashboard/services/default-widgets.constant.ts
- src/app/pages/dashboard/services/widget-resources.service.ts
- src/app/pages/dashboard/widgets/storage/widget-pool-disks-with-zfs-errors/widget-pool-disks-with-zfs-errors.component.spec.ts
- src/app/pages/dashboard/widgets/storage/widget-pool-disks-with-zfs-errors/widget-pool-disks-with-zfs-errors.component.ts
- src/app/pages/dashboard/widgets/storage/widget-pool-disks-with-zfs-errors/widget-pool-disks-with-zfs-errors.definition.ts
- src/app/pages/dashboard/widgets/storage/widget-pool-last-scan-errors/widget-pool-last-scan-errors.component.spec.ts
- src/app/pages/dashboard/widgets/storage/widget-pool-last-scan-errors/widget-pool-last-scan-errors.definition.ts
- src/app/pages/dashboard/widgets/storage/widget-pool-last-scan-errors/widget-pool-scan-errors.component.ts
- src/app/pages/dashboard/widgets/storage/widget-pool-status/widget-pool-status.component.spec.ts
- src/app/pages/dashboard/widgets/storage/widget-pool-status/widget-pool-status.component.ts
- src/app/pages/dashboard/widgets/storage/widget-pool-status/widget-pool-status.definition.ts
- src/app/pages/dashboard/widgets/storage/widget-pool-usage-gauge/widget-pool-usage-gauge.component.spec.ts
- src/app/pages/dashboard/widgets/storage/widget-pool-usage-gauge/widget-pool-usage-gauge.component.ts
- src/app/pages/dashboard/widgets/storage/widget-pool-usage-gauge/widget-pool-usage-gauge.definition.ts
- src/app/pages/dashboard/widgets/storage/widget-pool/widget-pool-settings/widget-pool-settings.component.spec.ts
- src/app/pages/dashboard/widgets/storage/widget-pool/widget-pool-settings/widget-pool-settings.component.ts
- src/app/pages/dashboard/widgets/storage/widget-pool/widget-pool.component.spec.ts
- src/app/pages/dashboard/widgets/storage/widget-pool/widget-pool.component.ts
- src/app/pages/dashboard/widgets/storage/widget-pool/widget-pool.definition.ts
**Changes:**
Better handle cases for old pool widget preferences.
**Testing:**
Add widgets to the old dashboard and save them. Then, go to the new dashboard and ensure the pool widgets work well.
> NAS-130551 / 25.04 / Improve backward compatibility for pool widget

- src/app/modules/layout/components/copyright-line/copyright-line.component.ts
**Changes:**
Use default value for copyright-line
**Testing:**
Check ticket
Original PR: https://github.com/truenas/webui/pull/10427
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130296
> NAS-130296 / 24.10-RC.1 / Update copyright-line (by denysbutenko)

- src/app/modules/forms/ix-forms/components/ix-textarea/ix-textarea.component.scss
Testing: see ticket, result 👇 
https://github.com/user-attachments/assets/ba4392e3-52f0-4075-86c2-996053123e3e
> NAS-130371 / 25.04 / Resizing a textarea doesn't work correctly

- src/app/modules/forms/ix-forms/components/ix-textarea/ix-textarea.component.scss
Testing: see ticket, result 👇 
https://github.com/user-attachments/assets/ba4392e3-52f0-4075-86c2-996053123e3e
Original PR: https://github.com/truenas/webui/pull/10466
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130371
> NAS-130371 / 24.10-RC.1 / Resizing a textarea doesn't work correctly (by AlexKarpov98)

- src/app/pages/apps/components/docker-images/docker-images-list/docker-images-list.component.html
- src/app/pages/apps/components/docker-images/docker-images-list/docker-images-list.component.scss
- src/app/pages/apps/components/docker-images/docker-images-list/docker-images-list.component.spec.ts
- src/app/pages/apps/components/docker-images/docker-images-list/docker-images-list.component.ts
**Changes:**
Added bulk delete operation for docker images list
**Testing:**
Go to **Apps > Images** page, and verify bulk deletion
Original PR: https://github.com/truenas/webui/pull/10454
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130533
> NAS-130533 / 24.10-RC.1 / Add bulk delete operation for docker images list (by bvasilenko)

- src/app/pages/datasets/modules/encryption/components/dataset-unlock/dataset-unlock.component.html
- src/app/pages/datasets/modules/encryption/components/dataset-unlock/dataset-unlock.component.ts
**Testing:**
Please follow replication steps described in the ticket
> NAS-130138 / 25.04 / Fix manual dataset unlocking

- src/app/pages/datasets/modules/encryption/components/dataset-unlock/dataset-unlock.component.html
- src/app/pages/datasets/modules/encryption/components/dataset-unlock/dataset-unlock.component.ts
**Testing:**
Please follow replication steps described in the ticket
Original PR: https://github.com/truenas/webui/pull/10469
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130138
> NAS-130138 / 24.10-RC.1 / Fix manual dataset unlocking (by bvasilenko)

- src/app/directives/details-height/details-height.directive.ts
- src/app/modules/ix-tree/components/tree-virtual-scroll-view/tree-virtual-scroll-view.component.scss
- src/assets/styles/mixins/layout.scss
git cherry-pick -x e1b80c97a821479a5cacd313e67b00713a4c912c
git cherry-pick -x e587f3e12adc210a4e0f86070e53a9d60304f85a
git cherry-pick -x 3009679ebdd129ae5a69c1186a353d310033570e
git cherry-pick -x 0008a16a19cc119f5e93ce555636e0f4ffbee59b
This is an alternative fix for https://github.com/truenas/webui/pull/10477.
Read comments there.
Original PR: https://github.com/truenas/webui/pull/10519
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129146
> NAS-129146 / 24.10-RC.1 / Slow scroll behaviour on Apps screen (by AlexKarpov98)

- src/app/pages/storage/modules/pool-manager/components/download-key-dialog/download-key-dialog.component.html
- src/app/pages/storage/modules/pool-manager/components/download-key-dialog/download-key-dialog.component.spec.ts
- src/app/pages/storage/modules/pool-manager/components/download-key-dialog/download-key-dialog.component.ts
- src/app/services/error-handler.service.spec.ts
- src/app/services/error-handler.service.ts
git cherry-pick -x d6bc65b0f6e3f9327ad7454ceffc45bd5026811d
git cherry-pick -x 02b8c051116f8c2f45d8dd5f07ab3ba17189e6b9
git cherry-pick -x e2083dbb7f1e665ba06dd2016c912a8a78313353
git cherry-pick -x 15e042645a57c9362b687e1e60fe980afa1c600e
git cherry-pick -x 9ad8523536c28668fd7024b3689a8d7aa51c4a53
git cherry-pick -x e287cea878e7e6835bcd546ed182f05a1a73e0fa
Testing: see ticket, result 👇 
https://github.com/user-attachments/assets/6761fff1-ade9-4370-9c16-2598e0af92ec
Original PR: https://github.com/truenas/webui/pull/10513
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130715
> NAS-130715 / 24.10-RC.1 / Better error handling for Download Encrypted Key (by AlexKarpov98)

- src/app/pages/apps/store/apps-filter-store.service.ts
git cherry-pick -x 7882b479a29f6ba0aefab61182f7eee8fecedbca
git cherry-pick -x de49a9e479e8fbe041befdccb1327b6c9f2fce45
**Changes:**
Sort apps asc by default in categories
**Testing:**
Ensure no regressions are there
Original PR: https://github.com/truenas/webui/pull/10514
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130630
> NAS-130630 / 24.10-RC.1 / Sort apps by name in categories (by denysbutenko)

- src/app/modules/forms/ix-forms/components/ix-select/ix-select.component.html
**Changes:**
Fixes translation issue.
**Testing:**
Check translation issue as described in the ticket.
Original PR: https://github.com/truenas/webui/pull/10536
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130692
> NAS-130692 / 25.04 / Some text is not translated in Pool creation (by undsoft)

- src/app/modules/forms/ix-forms/components/ix-list/ix-list-item/ix-list-item.component.scss
git cherry-pick -x 72ffdf95b1d53920bf6ad9aa7a238480c38d8eed
git cherry-pick -x c3ea9f3177a6e5a9c0a9eeab5f0c7168636da74f
git cherry-pick -x ce6a8227977dc6e56a17ce6e185f599a472e66fe
Original PR: https://github.com/truenas/webui/pull/10534
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130716
> NAS-130716 / 24.10-RC.1 / Margin issue in lists in apps (by AlexKarpov98)

- src/app/modules/charts/components/view-chart-area/view-chart-area.component.ts
git cherry-pick -x 7ed878c4b41b7f11f545ac699c6301a03440edd9
git cherry-pick -x 6872b28c3c57ef7b6704221bea856c62d65d727d
git cherry-pick -x 6908e35941be48651a60ffcc43df9901436b297b
Testing: see ticket. Try to reproduce.
Original PR: https://github.com/truenas/webui/pull/10527
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130717
> NAS-130717 / 24.10-RC.1 / Interface Widget | No chart is rendered (console.errors) (by AlexKarpov98)

- src/app/pages/data-protection/replication/replication-form/sections/target-section/target-section.component.html
- src/app/pages/data-protection/replication/replication-form/sections/target-section/target-section.component.spec.ts
- src/app/pages/data-protection/replication/replication-form/sections/target-section/target-section.component.ts
**Testing:**
Ensure that there's no validation conflict between **Encryption** checkbox and the **Encryption Key Format**  
Original PR: https://github.com/truenas/webui/pull/10521
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130521
> NAS-130521 / 24.10-RC.1 / Fix disabled replication task form submission (by bvasilenko)

- src/app/pages/dashboard/widgets/backup/widget-backup/widget-backup.component.scss
> NAS-130711 / 25.04 / Fix the backup banner position

- src/app/pages/dashboard/widgets/backup/widget-backup/widget-backup.component.scss
**Testing:**
See ticket
Original PR: https://github.com/truenas/webui/pull/10560
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130711
> NAS-130711 / 24.10-RC.1 / Fix the backup banner position (by bvasilenko)

- src/app/pages/system/advanced/cron/cron-list/cron-list.component.html
> NAS-130839 / 25.04 / Code cleanup id="lol"

- src/app/pages/system/advanced/cron/cron-list/cron-list.component.html
Code review only.
Original PR: https://github.com/truenas/webui/pull/10572
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130839
> NAS-130839 / 24.10-RC.1 / Code cleanup id="lol" (by AlexKarpov98)

- src/app/modules/feedback/components/file-review/file-review.component.scss
- src/app/modules/feedback/components/file-ticket-licensed/file-ticket-licensed.component.scss
- src/app/modules/feedback/components/file-ticket/file-ticket.component.scss
**Testing:** see ticket. Visual change only.
> NAS-130837 / 25.04 / Send Feedback modal - buttons spacing is missing

- src/app/pages/data-protection/cloud-backup/cloud-backup-details/cloud-backup-restore-form-snapshot-form/cloud-backup-restore-from-snapshot-form.component.spec.ts
- src/app/pages/data-protection/cloud-backup/cloud-backup-details/cloud-backup-restore-form-snapshot-form/cloud-backup-restore-from-snapshot-form.component.ts
**Changes:**
Fix subfolder path for cloud_backup.restore
**Testing:**
details in ticket
> NAS-130644 / 25.04 / Fix subfolder path for `cloud_backup.restore`

- src/app/modules/feedback/components/file-review/file-review.component.scss
- src/app/modules/feedback/components/file-ticket-licensed/file-ticket-licensed.component.scss
- src/app/modules/feedback/components/file-ticket/file-ticket.component.scss
**Testing:** see ticket. Visual change only.
Original PR: https://github.com/truenas/webui/pull/10571
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130837
> NAS-130837 / 24.10-RC.1 / Send Feedback modal - buttons spacing is missing (by AlexKarpov98)

- src/app/pages/data-protection/cloud-backup/cloud-backup-details/cloud-backup-restore-form-snapshot-form/cloud-backup-restore-from-snapshot-form.component.spec.ts
- src/app/pages/data-protection/cloud-backup/cloud-backup-details/cloud-backup-restore-form-snapshot-form/cloud-backup-restore-from-snapshot-form.component.ts
**Changes:**
Fix subfolder path for cloud_backup.restore
**Testing:**
details in ticket
Original PR: https://github.com/truenas/webui/pull/10537
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130644
> NAS-130644 / 24.10-RC.1 / Fix subfolder path for `cloud_backup.restore` (by denysbutenko)

- src/app/pages/storage/modules/disks/components/disk-list/disk-list.component.spec.ts
- src/app/pages/storage/modules/disks/components/disk-list/disk-list.component.ts
- src/app/pages/storage/modules/disks/components/disk-wipe-dialog/disk-wipe-dialog.component.ts
**Testing:**
Connect to machine 10.220.16.85
See ticket for replication steps.
> NAS-130758 / 25.04 / Update disk list after wipe

- src/app/pages/storage/modules/disks/components/disk-list/disk-list.component.spec.ts
- src/app/pages/storage/modules/disks/components/disk-list/disk-list.component.ts
- src/app/pages/storage/modules/disks/components/disk-wipe-dialog/disk-wipe-dialog.component.ts
**Testing:**
Connect to machine 10.220.16.85
See ticket for replication steps. 
Original PR: https://github.com/truenas/webui/pull/10570
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130758
> NAS-130758 / 24.10-RC.1 / Update disk list after wipe (by bvasilenko)

- src/app/pages/storage/modules/pool-manager/utils/generate-vdevs/generate-vdevs.service.ts
**Testing:**
Please see replication steps in the ticket
Original PR: https://github.com/truenas/webui/pull/10585
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128302
> NAS-128302 / 24.10-RC.1 / Fix filtering in `excludeManualSelectionDisks` (by bvasilenko)

- src/app/pages/audit/components/event-data-details-card/event-data-details-card.component.html
- src/app/pages/audit/components/event-data-details-card/event-data-details-card.component.ts
**Changes:**
See ticket for info.
> NAS-131015 / 25.04 / Sanitize audit logs

- src/app/pages/audit/components/event-data-details-card/event-data-details-card.component.html
- src/app/pages/audit/components/event-data-details-card/event-data-details-card.component.ts
**Changes:**
See ticket for info.
Original PR: https://github.com/truenas/webui/pull/10624
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131015
> NAS-131015 / 24.10-RC.1 / Sanitize audit logs (by undsoft)

- src/app/pages/audit/components/event-data-details-card/event-data-details-card.component.html
git cherry-pick -x 09032941db6d70065a2c6c764c3aacc800847ed8
git cherry-pick -x 257fb8ac1f814410f2f4deb31847b990854d4a2d
**Changes:**
See ticket for info.
Original PR: https://github.com/truenas/webui/pull/10624
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131015
> NAS-131015 / 24.04.2.1 / Sanitize audit logs (by undsoft)

- src/app/pages/apps/components/docker-images/docker-images-list/docker-images-list.component.ts
- src/app/pages/datasets/modules/snapshots/snapshot-list/snapshot-list.component.ts
- src/app/pages/storage/modules/disks/components/disk-list/disk-list.component.ts
- src/app/pages/system/bootenv/bootenv-list/bootenv-list.component.ts
git cherry-pick -x 8dc700154fd519606a4f610976addadc0f5bf412
git cherry-pick -x 01f0d26154948add56903fefe05c79f3a0c47a20
git cherry-pick -x 2f8b5eb885246f4ed1f5a55a71dabf6892d9642c
git cherry-pick -x f9268d054b24b8f6edfbcacaf0fa35395b5a2b29
Result: ⬇️ 
https://github.com/user-attachments/assets/f187e383-bd22-48b0-b369-18fc20c852f3
Original PR: https://github.com/truenas/webui/pull/10602
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130874
> NAS-130874 / 24.10-RC.1 / snapshot batch delete button is deleting ALL snapshots, not just selected (by AlexKarpov98)

- src/app/pages/reports-dashboard/components/reports-global-controls/netdata-dialog/netdata-dialog.component.html
**Testing:**
There is no way to test this until this is merged, so code review only.
> NAS-130879 / 25.04 / Fix netdata URL

- src/app/pages/reports-dashboard/components/reports-global-controls/netdata-dialog/netdata-dialog.component.html
**Testing:**
There is no way to test this until this is merged, so code review only.
Original PR: https://github.com/truenas/webui/pull/10626
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130879
> NAS-130879 / 24.10-RC.1 / Fix netdata URL (by undsoft)

- src/app/pages/dashboard/components/dashboard/dashboard.component.spec.ts
- src/app/pages/dashboard/components/dashboard/dashboard.component.ts
- src/app/pages/dashboard/services/dashboard.store.spec.ts
- src/app/pages/dashboard/services/dashboard.store.ts
- src/app/pages/dashboard/services/get-default-widgets.spec.ts
- src/app/pages/dashboard/services/get-default-widgets.ts
**Changes:**
Updated logic of default widgets generation.
**Testing:**
See ticket, try with HA system & on non HA system as well.
> NAS-130980 / 25.04 / ElectricEel HA Dashboard is missing the Standby System Information card.

- src/app/pages/apps/store/installed-apps-store.service.ts
This one as well fixes the App status and app show up on first install.
Incorrect check was set up.
Result:
https://github.com/user-attachments/assets/80accc89-47cd-4549-b28f-43f8a4791a55
https://github.com/user-attachments/assets/05a9586b-e39b-4bd9-9655-81b4e0d84a9f
> NAS-131098 / 25.04 / Custom App Issue | error modal & close

- src/app/pages/apps/store/installed-apps-store.service.ts
This one as well fixes the App status and app show up on first install.
Incorrect check was set up.
Result:
https://github.com/user-attachments/assets/80accc89-47cd-4549-b28f-43f8a4791a55
https://github.com/user-attachments/assets/05a9586b-e39b-4bd9-9655-81b4e0d84a9f
Original PR: https://github.com/truenas/webui/pull/10652
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131098
> NAS-131098 / 24.10-RC.1 / Custom App Issue | error modal & close (by AlexKarpov98)

- src/app/pages/apps/components/installed-apps/app-details-panel/app-details-panel.component.html
**Testing:**
Please see ticket
> NAS-131004 / 25.04 / Remove empty Metadata Card

- src/app/enums/catalog-app-state.enum.ts
- src/app/pages/apps/components/installed-apps/app-row/app-row.component.ts
- src/app/pages/apps/components/installed-apps/app-status-cell/app-status-cell.component.scss
git cherry-pick -x 44e3bae956db65ce2a7808e30ec36e1d2f4ebc2b
git cherry-pick -x 44a727c9a324d5ef70ad7d2a4fa0459958d0aaa0
Original PR: https://github.com/truenas/webui/pull/10669
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131146
> NAS-131146 / 24.10.0 / Crashed state for apps (by undsoft)

- src/app/pages/apps/store/installed-apps-store.service.ts
Testing: 
See ticket, result ⬇️ 
https://github.com/user-attachments/assets/573ec19b-6a98-4e63-a8bd-27ebe275c77f
Original PR: https://github.com/truenas/webui/pull/10666
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131118
> NAS-131118 / 24.10.0 / All discovery apps get `installed` flag once I start or stop installed application (by AlexKarpov98)

- src/app/pages/reports-dashboard/utils/report.utils.spec.ts
- src/app/pages/reports-dashboard/utils/report.utils.ts
**Changes:**
•	Enhanced code quality by making it more maintainable.
•	Increased test coverage to prevent regressions and ensure reliability.
**Testing:**
Go to the Reporting section and check for regressions.
> NAS-131132 / 25.04 / Refactor code in `report.utils.ts` & Add tests

- src/app/pages/apps/components/installed-apps/app-details-panel/app-details-panel.component.html
**Testing:**
Please see ticket
Original PR: https://github.com/truenas/webui/pull/10672
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131004
> NAS-131004 / 24.10.0 / Remove empty Metadata Card (by bvasilenko)

- src/app/pages/data-protection/cloud-backup/cloud-backup-card/cloud-backup-card.component.ts
- src/app/pages/data-protection/cloud-backup/cloud-backup-list/cloud-backup-list.component.ts
git cherry-pick -x 4cf72d5488af5c7e8f51203b25f1592e710f5f48
git cherry-pick -x 2215d543222f5a25c2b0cd52df1cde173b8b32ef
git cherry-pick -x 1cef68357d7afb9a803e23994edde1fa0e558cef
Original PR: https://github.com/truenas/webui/pull/10688
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131134
> NAS-131134 / 24.10.0 / Multiple Cloud backup has started messages (by AlexKarpov98)

- src/app/modules/dialog/components/full-screen-dialog/full-screen-dialog.component.scss
- src/app/pages/signin/signin.component.ts
**Changes:**
Adjust styles to display long text better.
**Testing:**
Setup login banner and check how it renders. Check the ticket for details.
**Preview:**
https://github.com/user-attachments/assets/53c52025-2595-4719-9d42-68ba8742bab8
> NAS-131276 / 25.04 / Wrap long text on the login banner

- src/app/pages/apps/store/installed-apps-store.service.ts
Result:
https://github.com/user-attachments/assets/79176bbc-c61c-4b18-a236-583c867769e7
Original PR: https://github.com/truenas/webui/pull/10713
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131286
> NAS-131286 / 24.10.0 / No application installed blink before showing installed apps (by AlexKarpov98)

- scripts/validate_translations.js
**Changes:**
Fixes incorrect line reporting.
**Testing:**
You can make a mistake in one of the json files by adding too many `}` and running `yarn validate-translations`.
> NAS-131228 / 25.04 / Fix validate-translations CI job

- src/app/core/testing/mock-enclosure/enclosure-templates/enclosure-mocks.ts
- src/app/core/testing/mock-enclosure/enclosure-templates/mock-expansion-shelves.ts
- src/app/enums/enclosure-model.enum.ts
- src/app/pages/system/enclosure/utils/supported-enclosures.ts
- src/assets/images/new-hardware/es60g3/es60g3-top.svg
**Changes:**
Adds support for ES60G3 (it's visually the same as gen 2).
**Testing:**
See ticket for URL and credentials.
> NAS-130828 / 25.04 / ES60G3 support

- .husky/pre-commit
- src/app/pages/system/update/components/train-card/train-card.component.spec.ts
- src/app/pages/system/update/components/train-card/train-card.component.ts
- src/app/pages/system/update/services/train.service.ts
_Problem was that we always updated value to initial one or existing one._
> NAS-131271 / 25.04 / Check for updates daily-button not working

- src/app/modules/forms/ix-forms/components/ix-combobox/ix-combobox.component.scss
- src/app/modules/forms/ix-forms/components/ix-combobox/ix-combobox.component.ts
Testing: see ticket & comments for steps to reproduce.
Fixes https://github.com/truenas/charts/issues/2824
> NAS-131323 / 25.04 / ddns-updater does not show the IP version value if set to “IPv4 and IPv6” when editing the configuration of the docker

- src/app/core/testing/classes/mock-global-store.service.ts
- src/app/core/testing/interfaces/mock-global-store-responses.interface.ts
- src/app/pages/dashboard/services/widget-resources.service.spec.ts
- src/app/pages/dashboard/services/widget-resources.service.ts
- src/app/services/global-store/global-store.service.spec.ts
- src/app/services/global-store/global-store.service.ts
- src/app/services/global-store/stores.constant.ts
**Changes:**
An attempt to establish a new kind of service, which will resolve the problem described in the ticket.
**Testing:**
1. Double check that the ticket's requirements are met
2. Code review
> NAS-130955 / 25.04 / Alternative for global data stores, part 1

- src/app/pages/apps/store/apps-filter-store.service.ts
Now:
https://github.com/user-attachments/assets/5f1c4ef0-f680-48f4-91f3-5da48eafc2d8
> NAS-131343 / 25.04 / UI is not showing new and updated apps properly

- src/app/pages/apps/store/apps-filter-store.service.ts
Now:
https://github.com/user-attachments/assets/5f1c4ef0-f680-48f4-91f3-5da48eafc2d8
Original PR: https://github.com/truenas/webui/pull/10739
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131343
> NAS-131343 / 24.10.0 / UI is not showing new and updated apps properly (by AlexKarpov98)

- src/app/core/testing/mock-enclosure/enclosure-templates/utils/pool.utils.spec.ts
- src/app/core/testing/mock-enclosure/enclosure-templates/utils/pool.utils.ts
> NAS-131131 / 25.04 / Refactor messy code in `pool.utils.ts`

- src/app/pages/system/general-settings/support/sys-info/sys-info.component.html
- src/app/pages/system/general-settings/support/sys-info/sys-info.component.spec.ts
> NAS-131295 / 25.04 / System Support page is reporting incorrect Model information

- src/app/modules/global-search/components/global-search-results/global-search-results.component.scss
- src/app/modules/ix-table/components/ix-table/ix-table.component.scss
- src/app/modules/layout/components/topbar/user-menu/user-menu.component.scss
- src/app/pages/apps/components/available-apps/app-card/app-card.component.scss
- src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.html
- src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.scss
- src/app/pages/apps/components/installed-apps/app-row/app-row.component.scss
- src/app/pages/dashboard/components/dashboard/dashboard.component.scss
- src/assets/styles/mixins/text.scss
- src/assets/styles/other/_material-reduction.scss
git cherry-pick -x c5028bb8e4e2c0146bb2c9bacdd614ed08fec173
git cherry-pick -x d7e8d0cf384ff688493c519a1df58e9351217871
I've added new mixin for line-clamp handling.
Original PR: https://github.com/truenas/webui/pull/10740
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131272
> NAS-131272 / 24.10.0 / App name issue in UI (by AlexKarpov98)

- src/app/pages/system/general-settings/support/sys-info/sys-info.component.html
- src/app/pages/system/general-settings/support/sys-info/sys-info.component.spec.ts
git cherry-pick -x 5a45fdf5a846d9b4fdb4e641c723d6457ede5a49
git cherry-pick -x fb5e85d1f7c94c3e1c9eb4db238ace042d4e83c0
Original PR: https://github.com/truenas/webui/pull/10750
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131295
> NAS-131295 / 24.10.0 / System Support page is reporting incorrect Model information (by AlexKarpov98)

- src/app/pages/system/enclosure/components/jbof-list/jbof-list.component.html
> NAS-131421 / 25.04 / Improve webui professionalism

- src/app/pages/system/enclosure/components/jbof-list/jbof-list.component.html
**Testing:**
Code review.
Original PR: https://github.com/truenas/webui/pull/10764
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131421
> NAS-131421 / 24.10.0 / Improve webui professionalism (by undsoft)

- src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.html
- src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.scss
> NAS-131443 / 25.04 / App Info Card -> App Version Overlap

- src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.html
- src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.scss
git cherry-pick -x 168347c2ceee66f9fc33e3253486b851291b27d8
git cherry-pick -x e4cf522989e933c6bd6990d9d38c9a317795c887
**Testing:** 
Before:
After:
Original PR: https://github.com/truenas/webui/pull/10771
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131443
> NAS-131443 / 24.10.0 / App Info Card -> App Version Overlap (by AlexKarpov98)

- src/app/pages/storage/modules/pool-manager/utils/generate-vdevs/generate-vdevs-treat-as-minimum.spec.ts
- src/app/pages/storage/modules/pool-manager/utils/generate-vdevs/generate-vdevs.service.ts
**Testing:**
Please see ticket for expected algorithm change, replication steps, and expected result
> NAS-130978 / 25.04 / Sort disks by size when Treat Disk Size As Minimum is selected

- src/app/pages/apps/store/apps-filter-store.service.ts
**Changes:**
Changed order of apps when a search query is applied.
**Testing:**
Go to apps and try to search an app and check ticket for details.
> NAS-131413 / 25.04 / Apps discovery should favor app name on search results

- src/app/modules/forms/ix-forms/components/ix-explorer/ix-explorer.component.html
- src/app/modules/forms/ix-forms/components/ix-explorer/ix-explorer.component.scss
Testing: see ticket, 
Result:
Hitting Space - toggles item (prevents scrolling down)
Hitting Enter - selects item
https://github.com/user-attachments/assets/f1ea6f46-f233-44c7-8e44-33101ce2e047
> NAS-126907 / 25.04 / `ix-explorer` accessibility improvements

- src/app/modules/forms/ix-forms/components/ix-explorer/ix-explorer.component.html
- src/app/modules/forms/ix-forms/components/ix-explorer/ix-explorer.component.scss
Testing: see ticket, 
Result:
Hitting Space - toggles item (prevents scrolling down)
Hitting Enter - selects item
https://github.com/user-attachments/assets/f1ea6f46-f233-44c7-8e44-33101ce2e047
Original PR: https://github.com/truenas/webui/pull/10787
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126907
> NAS-126907 / 24.10.0 / `ix-explorer` accessibility improvements (by AlexKarpov98)

- src/app/services/filesystem.service.spec.ts
- src/app/services/filesystem.service.ts
**Changes:**
Optimization is made by specifying a strict list of fields at the `query-param` argument
**Testing:**
Ensure that directory listing works correctly across the webUI.
> NAS-131060 / 25.04 / Optimize `filesystem.listdir`

- src/app/interfaces/api/api-call-directory.interface.ts
- src/app/pages/credentials/certificates-dash/csr-add/csr-add.component.spec.ts
- src/app/pages/credentials/certificates-dash/csr-add/steps/csr-identifier-and-type/csr-identifier-and-type.component.spec.ts
- src/app/pages/credentials/certificates-dash/csr-add/steps/csr-identifier-and-type/csr-identifier-and-type.component.ts
**Testing:**
Test for regressions.
> NAS-131460 / 25.04 / UI should use `webui.crypto.csr_profiles` endpoint for CSR

- src/app/interfaces/api/api-call-directory.interface.ts
- src/app/pages/credentials/certificates-dash/csr-add/csr-add.component.spec.ts
- src/app/pages/credentials/certificates-dash/csr-add/steps/csr-identifier-and-type/csr-identifier-and-type.component.spec.ts
- src/app/pages/credentials/certificates-dash/csr-add/steps/csr-identifier-and-type/csr-identifier-and-type.component.ts
**Testing:**
Test for regressions.
Original PR: https://github.com/truenas/webui/pull/10797
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131460
> NAS-131460 / 24.10.0 / UI should use `webui.crypto.csr_profiles` endpoint for CSR (by undsoft)

- src/app/pages/directory-service/components/idmap-list/idmap-list.component.html
- src/app/pages/directory-service/components/idmap-list/idmap-list.component.scss
- src/app/pages/directory-service/components/idmap-list/idmap-list.component.ts
- src/app/pages/directory-service/components/kerberos-keytabs/kerberos-keytabs-list/kerberos-keytabs-list.component.html
- src/app/pages/directory-service/components/kerberos-keytabs/kerberos-keytabs-list/kerberos-keytabs-list.component.scss
- src/app/pages/directory-service/components/kerberos-keytabs/kerberos-keytabs-list/kerberos-keytabs-list.component.ts
- src/app/pages/directory-service/components/kerberos-realms/kerberos-realms-list.component.html
- src/app/pages/directory-service/components/kerberos-realms/kerberos-realms-list.component.scss
- src/app/pages/directory-service/components/kerberos-realms/kerberos-realms-list.component.ts
> NAS-131551 / 25.04 / Inconsistent fonts on directory services pages

- .github/actions/prepare/action.yml
- .gitignore
- jest.config.cjs
- src/app/pages/api-keys/api-keys.component.spec.ts
**Changes:**
Maybe this would make tests faster.
**Testing:**
Once this PR builds, I'll push another commit that should and we can look at whether test job takes less time there.
> NAS-131633 / 25.04 / Adding cache to Jest

- src/app/pages/storage/modules/disks/components/disk-list/disk-list.component.ts
**Changes:**
Fix disk size sorting on disk list
**Testing:**
Go to Storage -> Disks and ensure disks are sorted numerically when disk size sort is active
> NAS-131484 / 25.04 / Sort disk size column numerically

- src/app/pages/storage/modules/devices/devices.component.ts
> NAS-129168 / 25.04 / Pool name appears modified on Manage Devices page.  "AppsPool" shows as "Appspool"

- src/app/pages/directory-service/directory-services.component.scss
> NAS-131641 / 25.04 / Directory Services Cards -> Different card for Kerberos Settings

- src/app/pages/directory-service/directory-services.component.scss
Original PR: https://github.com/truenas/webui/pull/10823
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131641
> NAS-131641 / 24.10.0 / Directory Services Cards -> Different card for Kerberos Settings (by AlexKarpov98)

- src/app/pages/apps/components/app-section-expand-collapse/app-section-expand-collapse.component.ts
Testing: 
See ticket.
Now you should correctly see View More if it's needed.
> NAS-131667 / 25.04 / App Notes card does not show View More button until I resize window

- .github/actions/prepare/action.yml
- .github/workflows/docker_internal.yml
- .github/workflows/docker_latest.yml
- .github/workflows/main.yml
- src/app/interfaces/cloud-backup.interface.ts
- src/app/pages/system/update/interfaces/package.interface.ts
- src/app/pages/vm/devices/device-form/device-form.component.ts
**Changes:**
Hopefully this will split tests across multiple machines and should reduce running time.
**Testing:**
See what happens with CI jobs.
> NAS-131643 / 25.04 / Try using shards with Jest

- src/app/pages/apps/components/installed-apps/app-workloads-card/app-workloads-card.component.html
> NAS-131712 / 25.04 / Apps | shell button is missing when application "Starting"

- src/app/pages/system/update/components/update-actions-card/update-actions-card.component.ts
**Testing:**
For replication steps, please see ticket
> NAS-130734 / 25.04 / Fix empty observer

- src/app/pages/directory-service/components/active-directory/active-directory.component.spec.ts
- src/app/pages/directory-service/components/active-directory/active-directory.component.ts
- src/app/pages/directory-service/components/ldap/ldap.component.spec.ts
- src/app/pages/directory-service/components/ldap/ldap.component.ts
Testing: 
See ticket.
Result:
https://github.com/user-attachments/assets/cd5f7b73-b606-48d0-af6e-76ddfbfc42ac
Original PR: https://github.com/truenas/webui/pull/10847
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129891
> NAS-129891 / 24.10.1 / Webui cache refresh should report progress of cache fill job (by AlexKarpov98)

- src/app/pages/dashboard/components/dashboard/dashboard.component.html
**Changes:**
Disable dragging widgets in view mode
**Testing:**
Try to drag any widget in view mode. Ensure no regressions for dragging in edit mode.
> NAS-131770 / 25.04 / Disable dragging widgets in view mode

- src/app/pages/system/update/components/update-actions-card/update-actions-card.component.ts
**Testing:**
For replication steps, please see ticket
Original PR: https://github.com/truenas/webui/pull/10846
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130734
> NAS-130734 / 24.10.1 / Fix empty observer (by bvasilenko)

- src/app/pages/system/enclosure/components/pages/enclosure-page/enclosure-page.component.scss
- src/app/pages/system/enclosure/components/pages/enclosure-page/enclosure-side-switch/enclosure-side-switch.component.spec.ts
- src/app/pages/system/enclosure/components/pages/enclosure-page/enclosure-side-switch/enclosure-side-switch.component.ts
- src/app/pages/system/enclosure/components/pages/enclosure-page/pools-view/pools-view.component.html
- src/app/pages/system/enclosure/components/pages/enclosure-page/pools-view/pools-view.component.spec.ts
- src/app/pages/system/enclosure/components/pages/enclosure-page/pools-view/pools-view.component.ts
- src/app/pages/system/enclosure/components/pages/enclosure-page/status-view/status-view.component.html
- src/app/pages/system/enclosure/components/pages/enclosure-page/status-view/status-view.component.spec.ts
- src/app/pages/system/enclosure/components/pages/enclosure-page/status-view/status-view.component.ts
- src/app/pages/system/enclosure/services/enclosure.store.ts
**Testing:**
Please see ticket.
You can simulate this enclosure on our test servers by providing
```typescript
EnclosureModel.Es60G3
```
at the `mockConfig` section of **environment.ts**
> NAS-131637 / 25.04 / Increase enclosure display size

- src/app/modules/buttons/export-button/export-button.component.scss
- src/app/modules/buttons/mobile-back-button/mobile-back-button.component.html
- src/app/modules/buttons/mobile-back-button/mobile-back-button.component.scss
- src/app/modules/buttons/mobile-back-button/mobile-back-button.component.spec.ts
- src/app/modules/buttons/mobile-back-button/mobile-back-button.component.ts
- src/app/pages/apps/apps.module.ts
- src/app/pages/apps/components/installed-apps/app-details-panel/app-details-panel.component.html
- src/app/pages/apps/components/installed-apps/app-details-panel/app-details-panel.component.scss
- src/app/pages/apps/components/installed-apps/app-details-panel/app-details-panel.component.spec.ts
- src/app/pages/audit/components/log-details-panel/log-details-panel.component.html
- src/app/pages/audit/components/log-details-panel/log-details-panel.component.scss
- src/app/pages/audit/components/log-details-panel/log-details-panel.component.ts
- src/app/pages/data-protection/cloud-backup/cloud-backup-details/cloud-backup-details.component.html
- src/app/pages/data-protection/cloud-backup/cloud-backup-details/cloud-backup-details.component.scss
- src/app/pages/data-protection/cloud-backup/cloud-backup-details/cloud-backup-details.component.ts
- src/app/pages/datasets/components/dataset-details-panel/dataset-details-panel.component.html
- src/app/pages/datasets/components/dataset-details-panel/dataset-details-panel.component.scss
- src/app/pages/datasets/components/dataset-details-panel/dataset-details-panel.component.spec.ts
- src/app/pages/datasets/datasets.module.ts
- src/app/pages/storage/modules/devices/components/disk-details-panel/disk-details-panel.component.html
- src/app/pages/storage/modules/devices/components/disk-details-panel/disk-details-panel.component.scss
- src/app/pages/storage/modules/devices/components/disk-details-panel/disk-details-panel.component.ts
Testing: 
See ticket. Refactoring.
> NAS-131705 / 25.04 / Clean up duplicated code for mobile-back-button

- src/app/pages/storage/modules/devices/components/zfs-info-card/extend-dialog/extend-dialog.component.ts
Testing: see ticket, result:
Original PR: https://github.com/truenas/webui/pull/10863
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131746
Original PR: https://github.com/truenas/webui/pull/10866
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131746
> NAS-131746 / 24.10.0 / RAIDZ Expansion Dialog cannot be minimized or "backgrounded" preventing further UI operations (by AlexKarpov98) (by bugclerk)

- src/app/pages/dashboard/widgets/cpu/widget-cpu-temperature-bar/widget-cpu-temperature-bar.component.scss
- src/app/pages/dashboard/widgets/cpu/widget-cpu-usage-bar/widget-cpu-usage-bar.component.scss
- src/app/pages/dashboard/widgets/cpu/widget-cpu-usage-gauge/widget-cpu-usage-gauge.component.scss
- src/app/pages/dashboard/widgets/cpu/widget-cpu-usage-recent/widget-cpu-usage-recent.component.scss
**Changes:**
Add border to CPU widgets
**Testing:**
Code review only.
**Preview:**
Before:
After:
> NAS-131824 / 25.04 / Add border to CPU widgets

- src/app/pages/dashboard/widgets/cpu/widget-cpu-temperature-bar/widget-cpu-temperature-bar.component.scss
- src/app/pages/dashboard/widgets/cpu/widget-cpu-usage-bar/widget-cpu-usage-bar.component.scss
- src/app/pages/dashboard/widgets/cpu/widget-cpu-usage-gauge/widget-cpu-usage-gauge.component.scss
- src/app/pages/dashboard/widgets/cpu/widget-cpu-usage-recent/widget-cpu-usage-recent.component.scss
**Changes:**
Add border to CPU widgets
**Testing:**
Code review only.
**Preview:**
Before:
After:
Original PR: https://github.com/truenas/webui/pull/10874
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131824
> NAS-131824 / 24.10.1 / Add border to CPU widgets (by denysbutenko)

- src/app/pages/apps/components/installed-apps/docker-status/docker-status.component.html
> NAS-131367 / 25.04 / Tooltip error on Apps service

- src/app/pages/network/components/configuration/configuration.component.ts
**Testing:**
See last comment in the ticket.
> NAS-131787 / 25.04 / Improper payload on re-saving the form

- src/app/pages/network/components/configuration/configuration.component.ts
**Testing:**
See last comment in the ticket.
Original PR: https://github.com/truenas/webui/pull/10888
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131787
> NAS-131787 / 24.10.0 / Improper payload on re-saving the form (by undsoft)

- src/app/pages/network/components/configuration/configuration.component.ts
**Testing:**
See last comment in the ticket.
Original PR: https://github.com/truenas/webui/pull/10888
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131787
> NAS-131787 / 24.10.1 / Improper payload on re-saving the form (by undsoft)

- src/app/modules/loader/app-loader.service.ts
**Testing:**
https://github.com/user-attachments/assets/bdd5840b-f7b5-456e-b482-ee3d38c112e2
> NAS-131270 / 25.04 / Accessibility | Setup pool to install dialog focus

- .eslintrc.cjs
- src/app/core/testing/mock-enclosure/mock-enclosure-websocket.service.ts
- src/app/helpers/assert-unreachable.utils.ts
- src/app/modules/charts/gauge-chart/gauge-chart.component.ts
- src/app/modules/dialog/components/job-progress/job-progress-dialog.component.ts
- src/app/modules/empty/empty.component.ts
- src/app/modules/ix-table/components/ix-empty-row/ix-empty-row.component.ts
- src/app/pages/apps/components/installed-apps/installed-apps.component.ts
- src/app/pages/dashboard/widgets/network/widget-interface/widget-interface.component.ts
- src/app/pages/data-protection/replication/replication-wizard/replication-wizard.component.ts
- src/app/pages/datasets/components/dataset-form/sections/other-options-section/other-options-section.component.ts
- src/app/pages/network/components/interface-form/interface-name-validator.service.ts
- src/app/pages/reports-dashboard/components/line-chart/line-chart.component.spec.ts
- src/app/pages/reports-dashboard/components/line-chart/line-chart.component.ts
- src/app/pages/sharing/smb/smb-acl/smb-acl.component.ts
- src/app/pages/storage/components/dashboard-pool/topology-card/topology-card.component.ts
- src/app/pages/storage/modules/pool-manager/utils/generate-vdevs/generate-vdevs.service.ts
- src/app/pages/system/bootenv/bootenv-form/bootenv-form.component.ts
- src/app/pages/system/update/components/update-actions-card/update-actions-card.component.ts
- src/app/services/schema/app-schema.transformer.ts
> NAS-131866 / 25.04 / Enable some linter rules

- src/app/core/guards/websocket-connection.guard.ts
- src/app/interfaces/dialog.interface.ts
- src/app/modules/dialog/components/full-screen-dialog/full-screen-dialog.component.html
- src/app/modules/dialog/components/full-screen-dialog/full-screen-dialog.component.scss
- src/app/modules/dialog/components/full-screen-dialog/full-screen-dialog.component.ts
- src/app/modules/dialog/dialog.service.ts
- src/app/pages/signin/signin.component.ts
- src/app/services/auth/two-factor-guard.service.spec.ts
- src/app/services/auth/two-factor-guard.service.ts
**Changes:**
Allows new lines in login banner text, cleans up code.
> NAS-131837 / 25.04 / New lines in login banner

- src/app/app.component.ts
Testing: 
https://github.com/user-attachments/assets/8bd1e0f4-a810-4fae-9445-fc73e46016ce
Original PR: https://github.com/truenas/webui/pull/10875
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128726
> NAS-128726 / 24.10.1 / The Scrollbar Position Does Not Reset When Loading New Pages (by AlexKarpov98)

- src/app/directives/warn-about-unsaved-changes/warn-about-unsaved-changes.directive.ts
- src/app/pages/credentials/groups/group-form/group-form.component.ts
- src/app/pages/credentials/users/user-form/user-form.component.ts
- src/app/pages/datasets/components/dataset-capacity-management-card/dataset-capacity-settings/dataset-capacity-settings.component.ts
- src/app/pages/directory-service/components/kerberos-keytabs/kerberos-keytabs-form/kerberos-keytabs-form.component.ts
- src/app/pages/directory-service/components/kerberos-realms-form/kerberos-realms-form.component.ts
- src/app/pages/services/components/service-ftp/service-ftp.component.ts
- src/app/pages/services/components/service-nfs/service-nfs.component.ts
- src/app/pages/services/components/service-smart/service-smart.component.ts
- src/app/pages/services/components/service-smb/service-smb.component.ts
- src/app/pages/services/components/service-snmp/service-snmp.component.ts
- src/app/pages/services/components/service-ssh/service-ssh.component.ts
- src/app/pages/services/components/service-ups/service-ups.component.ts
- src/app/pages/system/enclosure/components/jbof-list/jbof-form/jbof-form.component.ts
- src/app/pages/system/general-settings/localization/localization-form/localization-form.component.ts
- src/app/pages/system/general-settings/support/license/license.component.ts
- src/app/pages/system/general-settings/support/proactive/proactive.component.ts
For some reason previous fix stopped working 🤷‍♂️
On successful close, we should return some value.
We already handle this logic for another forms
> NAS-131838 / 25.04 / "Unsaved changes" warning when saving a form

- src/app/modules/forms/ix-forms/components/ix-explorer/create-dataset-dialog/create-dataset-dialog.component.html
- src/app/modules/forms/ix-forms/components/ix-explorer/create-dataset-dialog/create-dataset-dialog.component.spec.ts
- src/app/modules/forms/ix-forms/components/ix-explorer/create-dataset-dialog/create-dataset-dialog.component.ts
- src/app/pages/storage/modules/disks/components/manual-test-dialog/manual-test-dialog.component.html
**Testing:**
The easier way to reproduce the original issue is to:
1. Go to Shares -> SMB -> Add
2. Select a dataset.
3. Add trailing slash in the input.
4. Click Create Dataset.
> NAS-131802 / 25.04 / Error with some dataset paths in pool creation

- src/app/pages/storage/modules/pool-manager/components/inspect-vdevs-dialog/inspect-vdevs-dialog.component.ts
> NAS-131810 / 25.04 / Fangtooth Pool Creation Wizard Inspect VDEVs is not populated.

- src/app/modules/alerts/components/alert/alert.component.html
- src/app/modules/alerts/components/alert/alert.component.scss
- src/app/modules/alerts/components/alert/alert.component.spec.ts
- src/app/modules/alerts/components/alert/alert.component.ts
- src/app/modules/alerts/components/alerts-panel/alerts-panel.component.html
- src/app/modules/alerts/components/alerts-panel/alerts-panel.component.scss
- src/app/modules/alerts/components/alerts-panel/alerts-panel.component.spec.ts
- src/app/modules/alerts/components/alerts-panel/alerts-panel.component.ts
- src/app/modules/alerts/store/alert.actions.ts
- src/app/modules/alerts/store/alert.effects.ts
- src/app/modules/alerts/store/alert.reducer.ts
Testing: see ticket, 
Error handling added as well.
> NAS-131843 / 25.04 / Incorrect behavior on alert actions with readonly admin

- src/app/interfaces/api/api-call-directory.interface.ts
- src/app/interfaces/dialog.interface.ts
- src/app/modules/dialog/dialog.service.ts
- src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.spec.ts
- src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.ts
- src/app/pages/apps/components/installed-apps/installed-apps.component.spec.ts
- src/app/pages/apps/components/installed-apps/installed-apps.component.ts
- src/app/pages/apps/services/applications.service.ts
Install some apps.
Try to delete them - with single delete button and with Bulk Delete.
We'll see loader (checking if we should show `Remove IxVolumes`) and then the actual confirm dialog.
Did small refactoring to `onBulkDelete` to split code a little more.
Result:
https://github.com/user-attachments/assets/43512063-2333-4506-8978-530efa1a829b
> NAS-131918 / 25.04 / UI should conditionally show ix-volumes deletion button on app deletion

- src/app/pages/datasets/components/dataset-capacity-management-card/space-management-chart/space-management-chart.component.spec.ts
- src/app/pages/datasets/components/dataset-capacity-management-card/space-management-chart/space-management-chart.component.ts
> NAS-117256 / 25.04 / Add unit tests for Space Management Chart

- src/app/pages/apps/components/catalog-settings/apps-settings.component.ts
Result:
https://github.com/user-attachments/assets/72483f13-63a0-4111-90db-0cd48e8c5aae
> NAS-131984 / 25.04 / Apps Settings / Address Pools -> on save extra address pool added

- src/app/pages/apps/components/catalog-settings/apps-settings.component.ts
Result:
https://github.com/user-attachments/assets/72483f13-63a0-4111-90db-0cd48e8c5aae
Original PR: https://github.com/truenas/webui/pull/10930
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131984
> NAS-131984 / 24.10.1 / Apps Settings / Address Pools -> on save extra address pool added (by AlexKarpov98)

- src/app/enums/service-name.enum.ts
- src/app/interfaces/api/api-call-directory.interface.ts
- src/app/pages/services/components/service-nfs/service-nfs.component.spec.ts
- src/app/pages/services/components/service-nfs/service-nfs.component.ts
**Changes:**
Middleware endpoint got renamed.
**Testing:**
Code review.
> NAS-132056 / 25.04 / Replace RDMA endpoint

- src/app/pages/apps/components/apps-scope-wrapper.component.ts
- src/app/pages/apps/store/docker.store.ts
**Changes:**
Listen for docker config changes.
**Testing:**
1. Open two tabs with fresh CI machine in Apps Not Configured state.
2. Install an app in one of the tabs.
> NAS-127607 / 25.04 / Fix out of sync docker config between tabs

- src/app/pages/apps/components/apps-scope-wrapper.component.ts
- src/app/pages/apps/store/docker.store.ts
**Changes:**
Listen for docker config changes.
**Testing:**
1. Open two tabs with fresh CI machine in Apps Not Configured state.
2. Install an app in one of the tabs.
Original PR: https://github.com/truenas/webui/pull/10938
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127607
> NAS-127607 / 24.10.1 / Fix out of sync docker config between tabs (by denysbutenko)

- src/app/pages/apps/components/installed-apps/installed-apps.component.ts
**Testing:**
Please see the ticket for replication steps and ER/AR.
> NAS-132058 / 25.04 / Close details when the last app was deleted

- src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/storj-provider-form/storj-provider-form.component.html
- src/app/pages/data-protection/cloudsync/cloudsync-provider-description/cloudsync-provider-description.ts
**Changes:**
Updated the Storj Wording in cooperation with them and marketing. Updated the signup-links to use truenas.com URLs so we can adjust landing pages as needed without future product updates. 
**Testing:**
Validate the links to signup and landing pages work. 
None
> NAS-132190 / 25.04 / Update wording for Storj Description and links

- src/app/pages/sharing/nfs/nfs-list/nfs-list.component.ts
**Testing:**
See ticket.
Logic is taken from the NFS card.
Result:
https://github.com/user-attachments/assets/084d7cd1-b87b-40ba-b982-ca6ff7f69e70
> NAS-131761 / 25.04 / Enabled toggle in Shares>NFS does not work

- src/app/pages/sharing/nfs/nfs-list/nfs-list.component.ts
**Testing:**
See ticket.
Logic is taken from the NFS card.
Result:
https://github.com/user-attachments/assets/084d7cd1-b87b-40ba-b982-ca6ff7f69e70
Original PR: https://github.com/truenas/webui/pull/10965
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131761
> NAS-131761 / 24.10.1 / Enabled toggle in Shares>NFS does not work (by AlexKarpov98)

- scripts/ui-search/parse-ui-search-elements.ts
- src/app/core/testing/mock-enclosure/enclosure-templates/utils/pool.utils.spec.ts
- src/app/modules/forms/ix-forms/components/ix-explorer/ix-explorer.component.spec.ts
- src/app/modules/forms/ix-forms/components/ix-input/ix-input.harness.ts
- src/app/modules/forms/search-input/components/search-input/search-input.component.spec.ts
- src/app/pages/credentials/certificates-dash/acme-dns-authenticator-list/acme-dns-authenticator-list.component.spec.ts
- src/app/pages/dashboard/widgets/apps/common/app-controls/app-controls.component.spec.ts
- src/app/pages/dashboard/widgets/apps/widget-app-cpu/widget-app-cpu.component.spec.ts
- src/app/pages/dashboard/widgets/apps/widget-app-info/widget-app-info.component.spec.ts
- src/app/pages/dashboard/widgets/apps/widget-app-memory/widget-app-memory.component.spec.ts
- src/app/pages/dashboard/widgets/apps/widget-app-network/widget-app-network.component.spec.ts
- src/app/pages/dashboard/widgets/system/widget-system-uptime/widget-system-uptime.component.spec.ts
- src/app/pages/data-protection/cloud-backup/cloud-backup-card/cloud-backup-card.component.spec.ts
- src/app/pages/data-protection/cloud-backup/cloud-backup-form/cloud-backup-form.component.ts
- src/app/pages/datasets/components/dataset-management/dataset-management.component.ts
- src/app/pages/datasets/modules/snapshots/testing/snapshot-fake-datasource.ts
- src/app/pages/network/components/interfaces-card/ip-addresses-cell/ip-addresses-cell.component.spec.ts
- src/app/pages/reports-dashboard/components/line-chart/line-chart.component.ts
- src/app/pages/reports-dashboard/components/report/report.component.spec.ts
- src/app/pages/reports-dashboard/utils/report.utils.spec.ts
- src/app/pages/storage/modules/pool-manager/store/pool-manager.store.spec.ts
- src/app/pages/virtualization/components/all-instances/instance-details/instance-devices/instance-devices.component.spec.ts
- src/app/pages/virtualization/components/all-instances/instance-details/instance-general-info/instance-general-info.component.spec.ts
- src/app/pages/virtualization/components/instance-wizard/select-image-dialog/select-image-dialog.component.spec.ts
- tsconfig.strictNullChecks.json
**Changes:**
Using `as unknown as Something` while may sometimes be necessary can also hide errors and should be avoided when possible.
> NAS-132466 / 25.04 / Remove some usages of unknown

- docker/nginx.conf
**Testing:**
Once docker job is finished, run
```
docker container run -it -e TNIP=192.168.0.30 -p 8080:80 ixsystems/truenas-webui:11018
```
replace IP with IP of actual system and verify that UI can connect.
> NAS-132468 / 25.04 / Fix UI docker build

- src/app/modules/forms/ix-dynamic-form/components/ix-dynamic-form/ix-dynamic-form-item/ix-dynamic-form-item.component.html
Original PR: https://github.com/truenas/webui/pull/11024
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132328
> NAS-132328 / 24.10.1 / Apps - Lists do not show `description` (tooltip) (by AlexKarpov98)

- src/app/pages/jobs/job-logs-row/job-logs-row.component.scss
> NAS-132526 / 25.04 / Line wrap "Log Excerpt" text on jobs page

- src/app/pages/jobs/job-logs-row/job-logs-row.component.scss
Original PR: https://github.com/truenas/webui/pull/11056
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132526
> NAS-132526 / 24.10.1 / Line wrap "Log Excerpt" text on jobs page (by AlexKarpov98)

- src/app/pages/apps/components/docker-images/docker-images-list/docker-images-list.component.ts
- src/assets/i18n/zh-hans.json
**Testing:**
Please see ticket for repro steps/expected
> NAS-132411 / 25.04 / Sort image size column numerically

- src/app/modules/forms/ix-forms/components/readonly-badge/readonly-badge.component.scss
- src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts
- src/app/pages/data-protection/cloudsync/cloudsync-wizard/steps/cloudsync-provider/cloudsync-provider.component.ts
- src/app/pages/data-protection/cloudsync/cloudsync-wizard/steps/cloudsync-what-and-when/cloudsync-what-and-when.component.ts
> NAS-132581 / 25.04 / NAS-132550: Restricted admin - cloud sync task details not loaded

- src/app/pages/dashboard/widgets/network/widget-interface/widget-interface.component.html
- src/app/pages/dashboard/widgets/network/widget-interface/widget-interface.component.scss
- src/app/pages/dashboard/widgets/network/widget-interface/widget-interface.component.spec.ts
- src/app/pages/dashboard/widgets/network/widget-interface/widget-interface.component.ts
**Changes:**
Fix Missing NICs Can Cause Dashboard to Misbehave
**Testing:**
Add different network widgets and remove nic. Ensure the dashboard and whole UI is still operable.
Expected result:
> NAS-132242 / 25.04 / Fix Missing NICs Can Cause Dashboard to Misbehave

- src/app/modules/forms/ix-forms/components/readonly-badge/readonly-badge.component.scss
- src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts
- src/app/pages/data-protection/cloudsync/cloudsync-wizard/steps/cloudsync-provider/cloudsync-provider.component.ts
- src/app/pages/data-protection/cloudsync/cloudsync-wizard/steps/cloudsync-what-and-when/cloudsync-what-and-when.component.ts
git cherry-pick -x e2051e6af02567e9c39be881681e4a8bab3a7b67
git cherry-pick -x 89f61eacf56c4c65fba22e24b5e587e534e54b49
git cherry-pick -x 776a0e6d9b3e623e3c913d22bf430563e1732afa
Code review may be enough.
Original PR: https://github.com/truenas/webui/pull/11057
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132581
> NAS-132581 / 24.10.1 / NAS-132550: Restricted admin - cloud sync task details not loaded (by AlexKarpov98)

- .github/workflows/main.yml
- jest.config.cjs
- package.json
- yarn.lock
**Changes:**
Uploads additional data to codecov to enable more detailed analytics.
**Testing**
If you have access, see that additional stats are available here: https://app.codecov.io/gh/truenas/webui/tests/NAS-132540
> NAS-132540 / 25.04 / Enable additional codecov test analytics

- src/app/pages/account/groups/group-list/group-list.component.ts
- src/app/pages/account/users/user-list/user-list.component.ts
- src/app/pages/apps/components/docker-images/docker-images-list/docker-images-list.component.ts
- src/app/pages/data-protection/cloud-backup/cloud-backup-list/cloud-backup-list.component.spec.ts
- src/app/pages/data-protection/cloud-backup/cloud-backup-list/cloud-backup-list.component.ts
- src/app/pages/data-protection/cloudsync/cloudsync-list/cloudsync-list.component.ts
- src/app/pages/data-protection/replication/replication-list/replication-list.component.ts
- src/app/pages/data-protection/smart-task/smart-task-list/smart-task-list.component.ts
- src/app/pages/data-protection/vmware-snapshot/vmware-snapshot-list/vmware-snapshot-list.component.ts
- src/app/pages/datasets/components/dataset-quotas/dataset-quotas-list/dataset-quotas-list.component.ts
- src/app/pages/directory-service/components/idmap-list/idmap-list.component.ts
- src/app/pages/directory-service/components/kerberos-keytabs/kerberos-keytabs-list/kerberos-keytabs-list.component.ts
- src/app/pages/directory-service/components/kerberos-realms/kerberos-realms-list.component.ts
- src/app/pages/reports-dashboard/components/exporters/reporting-exporters-list/reporting-exporters-list.component.ts
- src/app/pages/services/services.component.ts
- src/app/pages/sharing/iscsi/associated-target/associated-target-list/associated-target-list.component.ts
- src/app/pages/sharing/iscsi/authorized-access/authorized-access-list/authorized-access-list.component.ts
- src/app/pages/sharing/iscsi/extent/extent-list/extent-list.component.ts
- src/app/pages/sharing/iscsi/initiator/initiator-list/initiator-list.component.ts
- src/app/pages/sharing/iscsi/portal/portal-list/portal-list.component.ts
- src/app/pages/sharing/iscsi/target/target-list/target-list.component.ts
- src/app/pages/sharing/nfs/nfs-list/nfs-list.component.ts
- src/app/pages/sharing/smb/smb-list/smb-list.component.ts
- src/app/pages/storage/modules/disks/components/smart-test-result-list/smart-test-result-list.component.ts
- src/app/pages/system/advanced/cron/cron-list/cron-list.component.ts
- src/app/pages/system/advanced/sysctl/tunable-list/tunable-list.component.ts
- src/app/pages/system/enclosure/components/jbof-list/jbof-list.component.ts
- src/app/pages/vm/devices/device-list/device-list/device-list.component.ts
- src/app/pages/vm/vm-list/vm-list.component.ts
git cherry-pick -x 17d902ed1cf12af5fff8d2de9d479683c20db412
git cherry-pick -x 462e4c71d02766b1f5e5d673d30501d4b6ee8f0f
git cherry-pick -x 6d0d1d73070841debb49be43bf52c93b5320ff20
Testing: see affected pages.
Original PR: https://github.com/truenas/webui/pull/11082
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132485
> NAS-132485 / 24.10.1 / Search is always lowercase on Users page (by AlexKarpov98)

- src/app/pages/apps/components/docker-images/docker-image-delete-dialog/docker-image-delete-dialog.component.html
- src/app/pages/apps/components/docker-images/docker-image-delete-dialog/docker-image-delete-dialog.component.ts
**Changes:**
Implemented [this request](https://ixsystems.atlassian.net/browse/NAS-132660?focusedCommentId=286416).
**Note:**  issue from ticket's description seems to be fixed already, as I could not replicate it.
> NAS-132660 / 25.04 / Disable Delete button while the operation is in progress

- .github/workflows/main.yml
- package.json
- src/app/pages/shell/shell.component.ts
**Testing:**
Observe that codecov/patch fails with an error now. I will remove dummy code before merge.
> NAS-132650 / 25.04 / Fixing codecov coverage reporting

- src/app/modules/master-detail-view/master-detail-view.component.html
- src/app/modules/master-detail-view/master-detail-view.component.scss
- src/app/pages/sharing/iscsi/target/all-targets/all-targets.component.html
- src/app/pages/sharing/iscsi/target/all-targets/all-targets.component.scss
- src/app/pages/sharing/iscsi/target/all-targets/target-list/target-list.component.ts
- src/app/pages/virtualization/components/all-instances/all-instances.component.html
- src/app/pages/virtualization/components/all-instances/instance-list/instance-list.component.html
- src/app/pages/virtualization/components/all-instances/instance-list/instance-list.component.scss
- src/app/pages/virtualization/components/all-instances/instance-list/instance-list.component.ts
- src/assets/styles/mixins/layout.scss
**Testing:**
Please see ticket for the list of expected results
> NAS-132783 / 25.04 / Improve master-detail-view

- src/app/pages/credentials/backup-credentials/cloud-credentials-card/cloud-credentials-card.component.ts
git cherry-pick -x d1ba4d0e4cea1ca1278445ab0b04b164fcab6e2d
git cherry-pick -x 625db124477082031b7fa33770e360c67766e392
Testing: 
See custom error as an example:
https://github.com/user-attachments/assets/4b8e9bdb-7885-4989-9db3-80f43a01525c
Original PR: https://github.com/truenas/webui/pull/11122
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132751
> NAS-132751 / 24.10.2 / Cloud Credentials: It is not possible to delete cloud credentials (by AlexKarpov98)

- src/app/pages/account/users/user-details-row/user-details-row.component.html
- src/app/pages/account/users/user-details-row/user-details-row.component.spec.ts
- src/app/pages/account/users/user-details-row/user-details-row.component.ts
git cherry-pick -x 1e38bff1129e44b206d776b194b2acb689be333f
git cherry-pick -x 948dfef05dee65877188799ed5b00fb92c8e2a3b
git cherry-pick -x 05a0c9df50e01665b20528f83b6940b28bb43fe9
- Create another admin user.
- Login as another admin user and try delete that new user.  (it's impossible now)
Original PR: https://github.com/truenas/webui/pull/11121
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132725
> NAS-132725 / 24.10.2 / UI - Do not allow user to delete themselves (by AlexKarpov98)

- src/app/pages/data-protection/rsync-task/rsync-task-form/rsync-task-form.component.spec.ts
- src/app/pages/data-protection/rsync-task/rsync-task-form/rsync-task-form.component.ts
Code review & passed tests are enough.
> NAS-132928 / 25.04 / rsync task: mode == MODULE, ssh_credentials == null

- src/app/pages/data-protection/rsync-task/rsync-task-form/rsync-task-form.component.spec.ts
- src/app/pages/data-protection/rsync-task/rsync-task-form/rsync-task-form.component.ts
Code review & passed tests are enough.
Original PR: https://github.com/truenas/webui/pull/11156
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132928
> NAS-132928 / 24.10.2 / rsync task: mode == MODULE, ssh_credentials == null (by AlexKarpov98)

- src/app/pages/virtualization/components/all-instances/instance-list/instance-list.component.scss
**Changes:**
Original issue is not reproducible. Fixed instance list header position.
**Testing:**
Create enough instances. Check header position.
> NAS-132873 / 25.04 / Fix styles for instance list header

- src/app/interfaces/cloud-backup.interface.ts
- src/app/interfaces/cloud-sync-task.interface.ts
- src/app/interfaces/cloudsync-credential.interface.ts
- src/app/modules/forms/custom-selects/cloud-credentials-select/cloud-credentials-select.component.spec.ts
- src/app/modules/forms/custom-selects/cloud-credentials-select/cloud-credentials-select.component.ts
- src/app/modules/slide-ins/components/slide-in2/slide-in2.component.spec.ts
- src/app/pages/credentials/backup-credentials/cloud-credentials-card/cloud-credentials-card.component.spec.ts
- src/app/pages/credentials/backup-credentials/cloud-credentials-card/cloud-credentials-card.component.ts
- src/app/pages/credentials/backup-credentials/cloud-credentials-form/cloud-credentials-form.component.html
- src/app/pages/credentials/backup-credentials/cloud-credentials-form/cloud-credentials-form.component.spec.ts
- src/app/pages/credentials/backup-credentials/cloud-credentials-form/cloud-credentials-form.component.ts
- src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/base-provider-form.ts
- src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/google-cloud-provider-form/google-cloud-provider-form.component.ts
- src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/openstack-swift-provider-form/openstack-swift-provider-form.component.ts
- src/app/pages/data-protection/cloud-backup/cloud-backup-form/cloud-backup-form.component.spec.ts
- src/app/pages/data-protection/cloud-backup/cloud-backup-form/cloud-backup-form.component.ts
- src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.spec.ts
- src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts
- src/app/pages/data-protection/cloudsync/cloudsync-list/cloudsync-list.component.spec.ts
- src/app/pages/data-protection/cloudsync/cloudsync-task-card/cloudsync-task-card.component.spec.ts
- src/app/pages/data-protection/cloudsync/cloudsync-wizard/cloudsync-wizard.component.ts
- src/app/pages/data-protection/cloudsync/cloudsync-wizard/cloudsync-wizard.testing.utils.ts
- src/app/pages/data-protection/cloudsync/cloudsync-wizard/steps/cloudsync-provider/cloudsync-provider.component.spec.ts
- src/app/pages/data-protection/cloudsync/cloudsync-wizard/steps/cloudsync-provider/cloudsync-provider.component.ts
- src/app/pages/data-protection/cloudsync/cloudsync-wizard/steps/cloudsync-what-and-when/cloudsync-what-and-when.component.ts
**Testing:**
Check cloud credential form in various places.
> NAS-132927 / 25.04 / Adapt to changes in cloudsync.credentials API

- src/app/pages/virtualization/components/all-instances/instance-details/instance-general-info/instance-edit-form/instance-edit-form.component.html
**Changes:**
Add translate pipe for hints
**Testing:**
Check if hints translated properly in another language.
> NAS-133087 / 25.04 / Add translate pipe for hints

- src/app/core/testing/utils/empty-api.service.ts
- src/app/interfaces/api/api-event-directory.interface.ts
- src/app/interfaces/app.interface.ts
- src/app/modules/dialog/components/job-progress/job-progress-dialog.component.ts
- src/app/modules/layout/console-footer/console-messages.store.spec.ts
- src/app/modules/layout/console-footer/console-messages.store.ts
- src/app/pages/apps/components/installed-apps/container-logs/container-logs.component.spec.ts
- src/app/pages/apps/components/installed-apps/container-logs/container-logs.component.ts
- src/app/services/websocket/api.service.spec.ts
- src/app/services/websocket/api.service.ts
**Changes:**
`subscribeToLogs` wasn't doing anything special, it was just wrapping `subscribe` with less type safety.
**Testing:**
Code review.
> NAS-133097 / 25.04 / Refactor out subscribeToLogs

- src/app/directives/has-access/missing-access-wrapper.component.scss
- src/app/pages/apps/components/installed-apps/app-row/app-row.component.html
- src/assets/styles/other/_material-overrides.scss
> NAS-133032 / 25.04 / Lock icon is misaligned on some resolutions in apps

- src/app/pages/sharing/iscsi/authorized-access/authorized-access-list/authorized-access-list.component.ts
- src/app/pages/sharing/iscsi/extent/extent-list/extent-list.component.ts
- src/app/pages/sharing/iscsi/initiator/initiator-list/initiator-list.component.ts
- src/app/pages/sharing/iscsi/iscsi.component.ts
- src/app/pages/sharing/iscsi/portal/portal-list/portal-list.component.ts
- src/app/pages/sharing/iscsi/target/all-targets/all-targets.component.ts
- src/app/services/iscsi.service.ts
**Changes:**
When new iSCSI share is created, list on active tab will reloaded.
**Testing:**
Create new iSCSI share on each iSCSI tab and check list is reloaded.
> NAS-132877 / 25.04 / Listen for changes on iSCSI tabs

- src/app/interfaces/schema.interface.ts
- src/app/pages/credentials/certificates-dash/forms/acmedns-form/acmedns-form.component.ts
Result:
https://github.com/user-attachments/assets/9045464b-a5d6-40b8-96e0-1ca72cf1d487
> NAS-132965 / 25.04 / Shell authenticator option for ACME DNS produces invalid fields

- src/app/interfaces/api/api-call-directory.interface.ts
- src/app/pages/system/enclosure/components/set-enclosure-label-dialog/set-enclosure-label-dialog.component.spec.ts
- src/app/pages/system/enclosure/components/set-enclosure-label-dialog/set-enclosure-label-dialog.component.ts
> NAS-129926 / 25.04 / `enclosure.label.set`

- src/app/pages/account/groups/group-members/group-members.component.spec.ts
- src/app/pages/account/groups/group-members/group-members.component.ts
Manual backport of https://github.com/truenas/webui/pull/11035
No review necessary.
> NAS-132503 / 24.10.2 / Exclude non-local users from group members selector

- src/app/pages/apps/apps.module.ts
- src/app/pages/apps/components/app-detail-view/app-details-header/app-details-header.component.html
- src/app/pages/apps/components/app-detail-view/app-details-header/app-details-header.component.scss
- src/app/pages/apps/components/app-detail-view/app-details-header/app-details-header.component.spec.ts
- src/app/pages/apps/components/app-detail-view/app-details-header/app-details-header.component.ts
- src/app/pages/apps/components/available-apps/app-card/app-card.component.html
- src/app/pages/apps/components/available-apps/app-card/app-card.component.scss
- src/app/pages/apps/components/available-apps/app-card/app-card.component.spec.ts
- src/app/pages/apps/components/available-apps/app-card/app-card.component.ts
- src/app/pages/apps/components/installed-app-badge/installed-app-badge.component.html
- src/app/pages/apps/components/installed-app-badge/installed-app-badge.component.scss
- src/app/pages/apps/components/installed-app-badge/installed-app-badge.component.spec.ts
- src/app/pages/apps/components/installed-app-badge/installed-app-badge.component.ts
git cherry-pick -x 2fd97cf33a639d2bd6511ab5ca38750f74693ecb
git cherry-pick -x 51095ed335ca4bf4bc3f11617f8cb1c0c501aa7c
git cherry-pick -x 9d4ac705cf3f11e52f9538d4e6f9da87ae7f38a0
git cherry-pick -x 4ee807acb699d7ee0884ecd97a6fa29fd9a694cb
Extracted duplicated logic into it's own component.
Result:
https://github.com/user-attachments/assets/4aaac631-0f3b-473b-8c6b-ebabb0f97134
Original PR: https://github.com/truenas/webui/pull/11230
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133127
> NAS-133127 / 24.10.2 / Incorrect redirect for already installed app (by AlexKarpov98)

- src/app/pages/data-protection/replication/replication-list/replication-list.component.ts
git cherry-pick -x ee8f3d372db4b6fe952ebc486f2343568d142060
git cherry-pick -x 2f67ca3210e94948f40124cca7c8832415cba7cc
git cherry-pick -x f2a2ee71639dedeaf138b816b1099fdd2b8ff8c3
git cherry-pick -x 58271c63e100f4359c9974dd2b48806f171456de
Code review should be enough.
Original PR: https://github.com/truenas/webui/pull/11224
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133139
> NAS-133139 / 24.10.2 / Replication has started spam (by AlexKarpov98)

- src/app/pages/services/components/service-nfs/service-nfs.component.ts
- src/app/pages/services/components/service-smb/service-smb.component.ts
Backported
Original PR: https://github.com/truenas/webui/pull/11225
> NAS-133049 / 24.10.2 / UI does not provide mechanism to remove an invalid NFS bind IP address

- src/app/modules/forms/ix-forms/components/ix-form-glossary/ix-form-glossary.component.scss
- src/app/pages/virtualization/components/all-instances/instance-list/stop-options-dialog/stop-options-dialog.component.scss
- src/app/pages/virtualization/components/instance-wizard/instance-wizard.component.scss
> NAS-133263 / 25.04 / Mobile QA for containers

- src/app/pages/signin/signin-form/signin-form.component.html
**Testing:**
Ensure that the 2fa field has focus when the page loads.
> NAS-132428 / 25.04 / Two-Factor Authentication > Give 2fa field focus

- src/app/pages/system/general-settings/email/email-card/email-card.component.spec.ts
> NAS-133459 / 25.04 / Master Fix

- src/app/pages/storage/modules/devices/components/zfs-info-card/raidz-extend-dialog/raidz-extend-dialog.component.ts
> NAS-133467 / 25.04 / GUI: Extending VDEV progress is blocking

- src/app/pages/system/general-settings/support/license/license.component.spec.ts
- src/app/pages/system/general-settings/support/license/license.component.ts
**Testing:**
Testing steps and example license are in the ticket.
> NAS-133566 / 25.04 / UI is not reloaded after license is applied

- src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.spec.ts
- src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts
- src/app/pages/data-protection/cloudsync/cloudsync-wizard/steps/cloudsync-what-and-when/cloudsync-what-and-when.component.ts
> NAS-133551 / 25.04 / Bucket input fix for cloudsync-form

- src/app/pages/credentials/kmip/kmip.component.html
- src/app/pages/credentials/kmip/kmip.component.spec.ts
- src/app/pages/credentials/kmip/kmip.component.ts
- src/app/pages/storage/modules/devices/components/hardware-disk-encryption/hardware-disk-encryption.component.html
- src/app/pages/storage/modules/devices/components/hardware-disk-encryption/hardware-disk-encryption.component.spec.ts
- src/app/pages/storage/modules/devices/components/hardware-disk-encryption/hardware-disk-encryption.component.ts
- src/app/pages/storage/modules/disks/components/disk-form/disk-form.component.html
- src/app/pages/storage/modules/disks/components/disk-form/disk-form.component.spec.ts
- src/app/pages/storage/modules/disks/components/disk-form/disk-form.component.ts
- src/app/pages/system/advanced/advanced-settings.component.html
- src/app/pages/system/advanced/advanced-settings.component.spec.ts
- src/app/pages/system/advanced/advanced-settings.component.ts
**Changes:**
- hide SED related options in UI
**Testing:**
Check ticket and related components.
|Documentation   | hide SED related options in UI for Community Edition users who haven't configured SED
> NAS-133442 / 25.04 / hide SED related options in UI

- src/app/pages/apps/components/installed-apps/app-info-card/app-info-card.component.ts
**Testing:**
Check that `force_remove_ix_volumes` is being correctly sent when you delete an app.
> NAS-133582 / 24.10.2 / Fix force_remove_ix_volumes

- src/app/pages/virtualization/components/all-instances/instance-details/instance-disks/instance-disk-form/instance-disk-form.component.html
- src/app/pages/virtualization/components/all-instances/instance-details/instance-disks/instance-disk-form/instance-disk-form.component.ts
Code review may be enough.
Result:
> NAS-133748 / 25.04 / Datasets show in VM edit

- src/app/interfaces/cloud-backup.interface.ts
- src/app/pages/data-protection/cloud-backup/cloud-backup-details/cloud-backup-restore-form-snapshot-form/cloud-backup-restore-from-snapshot-form.component.html
- src/app/pages/data-protection/cloud-backup/cloud-backup-details/cloud-backup-restore-form-snapshot-form/cloud-backup-restore-from-snapshot-form.component.spec.ts
- src/app/pages/data-protection/cloud-backup/cloud-backup-details/cloud-backup-restore-form-snapshot-form/cloud-backup-restore-from-snapshot-form.component.ts
**Testing:**
The machine where the issue was discovered: r40-1.dc1.ixsystems.net
Please see replication steps and expected results on the ticket.
> NAS-133634 / 24.10.2.1 / Fix paths when they are not absolute

- src/app/interfaces/cloud-backup.interface.ts
- src/app/pages/data-protection/cloud-backup/cloud-backup-details/cloud-backup-restore-form-snapshot-form/cloud-backup-restore-from-snapshot-form.component.html
- src/app/pages/data-protection/cloud-backup/cloud-backup-details/cloud-backup-restore-form-snapshot-form/cloud-backup-restore-from-snapshot-form.component.spec.ts
- src/app/pages/data-protection/cloud-backup/cloud-backup-details/cloud-backup-restore-form-snapshot-form/cloud-backup-restore-from-snapshot-form.component.ts
**Testing:**
The machine where the issue was discovered: r40-1.dc1.ixsystems.net
Please see replication steps and expected results on the ticket.
Original PR: https://github.com/truenas/webui/pull/11378
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133634
> NAS-133634 / 24.10.2 / Fix paths when they are not absolute (by bvasilenko)

- src/app/pages/credentials/users/user-form/user-form.component.html
- src/app/pages/credentials/users/user-form/user-form.component.ts
- src/app/services/user.service.ts
> NAS-133792 / 25.10 / NAS0-133792: Only allow local groups for groups in user form

- src/app/pages/credentials/users/user-form/user-form.component.html
- src/app/pages/credentials/users/user-form/user-form.component.ts
- src/app/services/user.service.ts
**Changes:**
See ticket.
Original PR: https://github.com/truenas/webui/pull/11388
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133792
> NAS-133792 / 25.04-RC.1 / NAS0-133792: Only allow local groups for groups in user form (by undsoft)

- src/app/pages/account/users/user-form/user-form.component.ts
- src/app/services/user.service.ts
git cherry-pick -x d571c68a54ecc5a0de34cecc4bd52394f0cf8071
git cherry-pick -x fdb0143b4279cff94b29bf6b9cae61559c26b689
git cherry-pick -x 8fdf54bdaf36d44cf037e0e40e6af5649fb40b05
git cherry-pick -x 7ac1d772d5a9f294e6a42dfcd1383a5c00d18495
**Changes:**
See ticket.
Original PR: https://github.com/truenas/webui/pull/11388
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133792
> NAS-133792 / 24.10.3 / NAS0-133792: Only allow local groups for groups in user form (by undsoft)

- src/app/pages/account/users/user-form/user-form.component.ts
- src/app/services/user.service.ts
git cherry-pick -x d571c68a54ecc5a0de34cecc4bd52394f0cf8071
git cherry-pick -x fdb0143b4279cff94b29bf6b9cae61559c26b689
git cherry-pick -x 8fdf54bdaf36d44cf037e0e40e6af5649fb40b05
git cherry-pick -x 7ac1d772d5a9f294e6a42dfcd1383a5c00d18495
**Changes:**
See ticket.
Original PR: https://github.com/truenas/webui/pull/11388
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133792
> NAS-133792 / 24.10.2 / NAS0-133792: Only allow local groups for groups in user form (by undsoft)

- src/app/pages/virtualization/components/all-instances/instance-details/instance-general-info/instance-edit-form/instance-edit-form.component.html
git cherry-pick -x 0d30ccb2ca284aa529b45fec9bf4d61daa6ef31d
git cherry-pick -x 077a3180412c7033eb5003afb8487964a8e6b355
**Changes:**
See ticket.
Original PR: https://github.com/truenas/webui/pull/11402
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133746
> NAS-133746 / 25.04-RC.1 / CPU/memory optional on edit but required on creation (by undsoft)

- src/app/pages/apps/components/custom-app-form/custom-app-form.component.html
- src/app/pages/apps/components/custom-app-form/custom-app-form.component.spec.ts
- src/app/pages/apps/components/custom-app-form/custom-app-form.component.ts
Result:
https://github.com/user-attachments/assets/9eaf1b20-7d90-4157-824d-b4464e9cde11
Original PR: https://github.com/truenas/webui/pull/11428
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133816
> NAS-133816 / 25.04-RC.1 / YAML is not available during edit when app is created (by AlexKarpov98)

- src/app/enums/codename.enum.ts
- src/app/pages/dashboard/widgets/system/common/widget-sys-info.utils.spec.ts
- src/app/pages/dashboard/widgets/system/common/widget-sys-info.utils.ts
- src/app/pages/dashboard/widgets/system/widget-sys-info-active/widget-sys-info-active.component.spec.ts
- src/app/pages/dashboard/widgets/system/widget-sys-info-passive/widget-sys-info-passive.component.spec.ts
**Changes:**
Adapt utils to naming changes in system version.
**Testing:**
Check system info widgets.
Original PR: https://github.com/truenas/webui/pull/11419
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133818
> NAS-133818 / 25.04-RC.1 / Update system version utils for new naming (by denysbutenko)

- src/app/pages/dashboard/components/dashboard/dashboard.component.ts
**Testing:**
for 2 issues please see the replication steps in the 2 videos attached to the ticket
Original PR: https://github.com/truenas/webui/pull/11421
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133773
> NAS-133773 / 25.04-RC.1 / Fix Dashboard issues (by bvasilenko)

- src/app/pages/data-protection/cloud-backup/cloud-backup-card/cloud-backup-card.component.ts
**Testing:**
For replication steps and expected result please see ticket
> NAS-133822 / 25.04-RC.1 / Fix `updateRowJob` at cloud backups

- src/app/pages/apps/components/app-card-logo/app-card-logo.component.ts
Result:
https://github.com/user-attachments/assets/1446481b-e63e-4bfe-84ef-ea1ceaaa77a2
Original PR: https://github.com/truenas/webui/pull/11436
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133707
> NAS-133707 / 25.04-RC.1 / App icons are not initially rendered when searching until screen redraw (by AlexKarpov98)

- src/app/pages/apps/services/applications.service.ts
Backport of https://github.com/truenas/webui/pull/11356
> NAS-133655 / 25.04-RC.1 / Pass location.hostname as host_ip to app.query

- src/app/pages/data-protection/cloud-backup/cloud-backup-card/cloud-backup-card.component.spec.ts
- src/app/pages/data-protection/cloud-backup/cloud-backup-card/cloud-backup-card.component.ts
- src/assets/i18n/es-ar.json
**Testing:**
For replication steps please see ticket
> NAS-133825 / 25.10 / Update backups only once at the end

- src/app/pages/data-protection/cloud-backup/cloud-backup-card/cloud-backup-card.component.spec.ts
- src/app/pages/data-protection/cloud-backup/cloud-backup-card/cloud-backup-card.component.ts
Backported.
Original PR: https://github.com/truenas/webui/pull/11459
> NAS-133825 / 25.04-RC.1 / Update backups only once at the end

- src/app/modules/layout/admin-layout/admin-layout.component.ts
- src/app/modules/layout/topbar/topbar.component.ts
- src/app/pages/credentials/groups/privilege/privilege-form/privilege-form.component.html
- src/app/pages/system/advanced/system-security/system-security-form/system-security-form.component.spec.ts
- src/app/pages/system/advanced/system-security/system-security-form/system-security-form.component.ts
> NAS-134043 / 25.10 / Clear token when STIG is enabled

- src/app/modules/layout/admin-layout/admin-layout.component.ts
- src/app/modules/layout/topbar/topbar.component.ts
- src/app/pages/credentials/groups/privilege/privilege-form/privilege-form.component.html
- src/app/pages/system/advanced/system-security/system-security-form/system-security-form.component.spec.ts
- src/app/pages/system/advanced/system-security/system-security-form/system-security-form.component.ts
**Changes:**
See ticket.
Original PR: https://github.com/truenas/webui/pull/11501
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134043
> NAS-134043 / 25.04-RC.1 / Clear token when STIG is enabled (by undsoft)

- src/app/pages/apps/components/installed-apps/installed-apps.component.html
git cherry-pick -x a49f99d14ce8c1d66ac5e4375098266114b3b004
git cherry-pick -x 19602248a05f119e1630f69a976acfef251350ce
git cherry-pick -x 4a1c5e00ede764a73ad3fa0f3a923dd0604df741
Result:
https://github.com/user-attachments/assets/f653b0bf-d493-44b9-8626-b0f7a15d735f
Original PR: https://github.com/truenas/webui/pull/11526
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134024
> NAS-134024 / 25.04-RC.1 / Show details for header in apps (by AlexKarpov98)

- src/app/modules/layout/topbar/topbar.component.spec.ts
- src/app/modules/layout/topbar/topbar.component.ts
**Testing:**
You can fail an upgrade job by uploading an ISO for the old version.
> NAS-134021 / 25.10 / Update in progress icon sticks around after job fails

- src/app/modules/layout/topbar/topbar.component.spec.ts
- src/app/modules/layout/topbar/topbar.component.ts
**Testing:**
You can fail an upgrade job by uploading an ISO for the old version.
Original PR: https://github.com/truenas/webui/pull/11520
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134021
> NAS-134021 / 25.04-RC.1 / Update in progress icon sticks around after job fails (by undsoft)

- src/app/pages/dashboard/widgets/backup/widget-backup/backup-task-empty/backup-task-empty.component.html
- src/app/pages/dashboard/widgets/cpu/widget-cpu-temperature-bar/widget-cpu-temperature-bar.component.scss
- src/app/pages/dashboard/widgets/cpu/widget-cpu-usage-bar/widget-cpu-usage-bar.component.scss
- src/app/pages/dashboard/widgets/cpu/widget-cpu-usage-gauge/widget-cpu-usage-gauge.component.scss
- src/app/pages/dashboard/widgets/cpu/widget-cpu-usage-recent/widget-cpu-usage-recent.component.scss
- src/app/pages/dashboard/widgets/help/widget-help/widget-help.component.scss
- src/app/pages/dashboard/widgets/system/common/widget-sys-info.scss
> NAS-134145 / 25.10 / Help widget has scrollbar & other widgets checkup

- src/app/pages/instances/components/all-instances/all-instances.component.spec.ts
- src/app/pages/instances/components/all-instances/all-instances.component.ts
git cherry-pick -x e627ff4a3202edae14265872d5b4862cb06aff3f
git cherry-pick -x 8e2a7988790af092e2d902197592304b7ee043ec
git cherry-pick -x 7b3b73ce2083068dec045d573c2e40583747c2f4
git cherry-pick -x baec1d09ebb37e41c34531c3590f09730a840d2d
git cherry-pick -x 4aaa7cc126698bfb804763783dc1b94bf4d325dd
git cherry-pick -x fa3c7fe0a4bd031b21243e984b86bb167c3ca422
Testing: 
See ticket.
Result:
https://github.com/user-attachments/assets/b18b78c9-2386-4746-ba02-0c318f89a763
Original PR: https://github.com/truenas/webui/pull/11536
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133841
> NAS-133841 / 25.04-RC.1 / Warning on new Virtualization feature (by AlexKarpov98)

- src/app/pages/dashboard/widgets/backup/widget-backup/backup-task-empty/backup-task-empty.component.html
- src/app/pages/dashboard/widgets/cpu/widget-cpu-temperature-bar/widget-cpu-temperature-bar.component.scss
- src/app/pages/dashboard/widgets/cpu/widget-cpu-usage-bar/widget-cpu-usage-bar.component.scss
- src/app/pages/dashboard/widgets/cpu/widget-cpu-usage-gauge/widget-cpu-usage-gauge.component.scss
- src/app/pages/dashboard/widgets/cpu/widget-cpu-usage-recent/widget-cpu-usage-recent.component.scss
- src/app/pages/dashboard/widgets/help/widget-help/widget-help.component.scss
- src/app/pages/dashboard/widgets/system/common/widget-sys-info.scss
Result:
Original PR: https://github.com/truenas/webui/pull/11537
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134145
> NAS-134145 / 25.04-RC.1 / Help widget has scrollbar & other widgets checkup (by AlexKarpov98)

- src/app/modules/ix-table/components/ix-table-body/cells/ix-cell-state-button/ix-cell-state-button.component.ts
- src/app/pages/data-protection/cloudsync/cloudsync-task-card/cloudsync-task-card.component.ts
**Testing:**
Please see the ticket for replication steps and expected result
> NAS-134036 / 25.10 / Add logs to Cloud Sync Task card

- src/app/modules/forms/search-input/components/advanced-search/advanced-search.component.scss
- src/app/modules/forms/search-input/components/basic-search/basic-search.component.scss
- src/app/modules/ix-table/components/ix-table-head/head-cells/ix-header-cell-text/ix-header-cell-text.component.scss
- src/app/modules/ix-table/components/ix-table-head/head-cells/ix-header-cell-text/ix-header-cell-text.component.ts
- src/app/modules/layout/admin-layout/admin-layout.component.scss
- src/app/pages/audit/components/audit-list/audit-list.component.ts
- src/app/pages/audit/components/audit-search/audit-search.component.scss
- src/app/pages/dashboard/components/dashboard/dashboard.component.scss
- src/app/pages/datasets/components/dataset-management/dataset-management.component.ts
- src/app/pages/reports-dashboard/components/report/report.component.scss
- src/app/pages/reports-dashboard/reports-dashboard.component.scss
- src/app/pages/storage/modules/pool-manager/components/manual-disk-selection/components/disk-info/disk-info.component.scss
- src/app/pages/storage/modules/pool-manager/components/manual-disk-selection/components/enclosure-wrapper/enclosure-wrapper.component.scss
- src/app/pages/storage/modules/pool-manager/components/manual-disk-selection/components/manual-selection-vdev/manual-selection-vdev.component.scss
- src/app/pages/storage/modules/pool-manager/components/pool-manager/pool-manager.component.scss
- src/app/pages/system-tasks/failover/failover.component.scss
- src/app/pages/system-tasks/restart/restart.component.scss
- src/app/pages/system-tasks/shutdown/shutdown.component.scss
- src/app/pages/system/general-settings/support/support-card/support-card.component.scss
- src/assets/styles/mixins/cards.scss
- src/assets/styles/other/_material-reduction.scss
Check each 12 steps provided in the ticket.
Note my comment:
```
this (9) issue deserves a separate ticket.
Drag and drop selection for manual disk selection is not possible in Mobile mode. No method in place to perform this.
```
Original PR: https://github.com/truenas/webui/pull/11550
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131881
> NAS-131881 / 25.04-RC.1 / GUI restrictions/issues present when accessing TrueNAS in Mobile display size (by AlexKarpov98)

- src/app/pages/reports-dashboard/reports-dashboard.component.ts
**Testing:**
At the **Reporting > Disks** screen,
**Expected result:** the disk temperature data displayed correctly
Original PR: https://github.com/truenas/webui/pull/11542
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133897
> NAS-133897 / 25.04-RC.1 / Add disk reporting temps (by bvasilenko)

- src/app/modules/ix-table/components/ix-table-body/cells/ix-cell-state-button/ix-cell-state-button.component.ts
- src/app/pages/data-protection/cloudsync/cloudsync-task-card/cloudsync-task-card.component.ts
**Testing:**
Please see the ticket for replication steps and expected result
Original PR: https://github.com/truenas/webui/pull/11535
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134036
> NAS-134036 / 25.04-RC.1 / Add logs to Cloud Sync Task card (by bvasilenko)

- src/app/pages/instances/components/instance-wizard/instance-wizard.component.spec.ts
- src/app/pages/instances/components/instance-wizard/instance-wizard.component.ts
Testing: see ticket & updated tests.
Original PR: https://github.com/truenas/webui/pull/11573
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134154
> NAS-134154 / 25.04-RC.1 / Some fields not cleared when changing creation form from container to VM (by AlexKarpov98)

- src/app/modules/auth/auth.service.ts
**Changes:**
Changes login status first before clearing subscriptions so the decision to not make `core.unsubscribe` calls can be made based on updated state
**Testing:**
Test login and then logout and check browser console for errors.
Original PR: https://github.com/truenas/webui/pull/11549
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134064
> NAS-134064 / 25.04-RC.1 / Changes login status before clearing subscriptions (by RehanY147)

- src/app/modules/layout/topbar/topbar.component.html
- src/app/modules/layout/topbar/topbar.component.spec.ts
- src/app/modules/layout/topbar/topbar.component.ts
git cherry-pick -x ff3285e6fe78eb395a231ddc1bd3d406c1381e4b
git cherry-pick -x e94ccbb98e83adc22a4276a886e16a852ecee783
**Changes:**
Removes iXsystems logo from topbar.
**Testing:**
Original PR: https://github.com/truenas/webui/pull/11570
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134223
> NAS-134223 / 25.04-RC.1 / Remove ix-logo from topbar (by denysbutenko)

- src/app/pages/sharing/iscsi/fibre-channel-ports/fibre-channel-ports.component.ts
- src/app/pages/sharing/iscsi/iscsi-wizard/iscsi-wizard.component.ts
- src/app/pages/sharing/iscsi/iscsi.component.ts
- src/app/pages/sharing/iscsi/target/all-targets/all-targets.component.ts
- src/app/services/iscsi.service.ts
Original PR: https://github.com/truenas/webui/pull/11574
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134027
> NAS-134027 / 25.04-RC.1 / Minor fixes for iscsi pages (by AlexKarpov98)

- src/app/pages/credentials/users/user-api-keys/components/api-key-form/api-key-form.component.spec.ts
- src/app/pages/credentials/users/user-api-keys/components/api-key-form/api-key-form.component.ts
**Changes:**
Disables Username field in API keys on edit since it cannot be changed.
> NAS-134213 / 25.10 / Disable username in API keys on edit

- src/app/pages/reports-dashboard/components/report/report.component.ts
**Testing:**
1. At **System > General settings > Localization** change language to **French (fr)**
2. Go to **Reporting** page
**Expected Result**: page should not crash and there should be no errors in the console
Original PR: https://github.com/truenas/webui/pull/11580
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134245
> NAS-134245 / 25.04-RC.1 / FR/UK or any other language except en brings `Invalid date format` errors for Reporting page (by bvasilenko)

- src/app/pages/instances/components/all-instances/instance-details/instance-general-info/instance-edit-form/instance-edit-form.component.ts
- src/app/pages/instances/components/instance-wizard/instance-wizard.component.ts
**Testing:**
For a container, type something in Memory field and then clear it and try to save.
Original PR: https://github.com/truenas/webui/pull/11586
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134210
> NAS-134210 / 25.04-RC.1 / Incus Container Instance won't allow empty memory after c… (by undsoft)

- src/app/helpers/copyright-text.helper.spec.ts
- src/app/helpers/copyright-text.helper.ts
- src/app/modules/layout/admin-layout/admin-layout.component.html
- src/app/modules/layout/admin-layout/admin-layout.component.ts
- src/app/modules/layout/copyright-line/copyright-line.component.html
- src/app/modules/layout/copyright-line/copyright-line.component.spec.ts
- src/app/modules/layout/copyright-line/copyright-line.component.ts
- src/app/store/system-info/system-info.selectors.ts
git cherry-pick -x 4b9c7745e54de4cf9185a49476e7fe70577f6e85
git cherry-pick -x eed97efc3916b39587315cc7fac61b5dfbdd5f6c
git cherry-pick -x f41465b7083bdb8fefe6b848a81b54cf62af5f13
git cherry-pick -x a65cb5d07c125ed00bebf7e3376f32a69b61f7b1
git cherry-pick -x 601f9887f236475165b0851abc2d414d9e132497
Testing: 
See ticket & comments.
|Documentation   | Copyright updated
Original PR: https://github.com/truenas/webui/pull/11596
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134221
> NAS-134221 / 25.04-RC.1 / Adjust Copyright in the UI (by AlexKarpov98)

- src/app/core/testing/utils/empty-auth.service.ts
- src/app/interfaces/api/api-call-directory.interface.ts
- src/app/interfaces/auth.interface.ts
- src/app/modules/auth/auth.service.spec.ts
- src/app/modules/auth/auth.service.ts
- src/app/modules/terminal/components/terminal/terminal.component.ts
- src/app/pages/datasets/modules/encryption/components/dataset-unlock/dataset-unlock.component.ts
- src/app/pages/instances/components/common/volumes-dialog/upload-iso-button/upload-iso-button.component.ts
- src/app/pages/system/advanced/system-security/system-security-form/system-security-form.component.ts
- src/app/pages/system/general-settings/save-config-dialog/save-config-dialog.component.ts
- src/app/pages/system/update/components/manual-update-form/manual-update-form.component.ts
- src/app/pages/system/update/components/train-card/train-card.component.spec.ts
- src/app/pages/system/update/components/train-card/train-card.component.ts
- src/app/services/upload.service.spec.ts
- src/app/services/upload.service.ts
**Changes:**
- Add single-use token supports
- Use it for uploads
**Testing:**
Open General Settings and Try to Export/Import Settings.
> NAS-134047 / 25.10 / Fix File uploads and downloads do not work in STIG mode

- src/app/core/testing/utils/empty-auth.service.ts
- src/app/interfaces/api/api-call-directory.interface.ts
- src/app/interfaces/auth.interface.ts
- src/app/modules/auth/auth.service.spec.ts
- src/app/modules/auth/auth.service.ts
- src/app/modules/terminal/components/terminal/terminal.component.ts
- src/app/pages/datasets/modules/encryption/components/dataset-unlock/dataset-unlock.component.ts
- src/app/pages/instances/components/common/volumes-dialog/upload-iso-button/upload-iso-button.component.ts
- src/app/pages/system/advanced/system-security/system-security-form/system-security-form.component.ts
- src/app/pages/system/general-settings/save-config-dialog/save-config-dialog.component.ts
- src/app/pages/system/update/components/manual-update-form/manual-update-form.component.ts
- src/app/pages/system/update/components/train-card/train-card.component.spec.ts
- src/app/pages/system/update/components/train-card/train-card.component.ts
- src/app/services/upload.service.spec.ts
- src/app/services/upload.service.ts
**Changes:**
- Add single-use token supports
- Use it for uploads
**Testing:**
Open General Settings and Try to Export/Import Settings.
Original PR: https://github.com/truenas/webui/pull/11591
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134047
> NAS-134047 / 25.04-RC.1 / Fix File uploads and downloads do not work in STIG mode (by denysbutenko)

- src/app/pages/dashboard/widgets/help/widget-help/widget-help.component.scss
> NAS-134368 / 25.10 / Help widget has scrollbar again

- src/app/pages/dashboard/widgets/help/widget-help/widget-help.component.scss
Original PR: https://github.com/truenas/webui/pull/11612
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134368
> NAS-134368 / 25.04.0 / Help widget has scrollbar again (by AlexKarpov98)

- package.json
- src/app/pages/apps/components/app-detail-view/app-detail-view.component.ts
- src/app/pages/apps/components/available-apps/category-view/category-view.component.spec.ts
- src/app/pages/apps/components/available-apps/category-view/category-view.component.ts
- src/app/pages/apps/components/installed-apps/installed-apps-list/installed-apps-list.component.spec.ts
- src/app/pages/apps/components/installed-apps/installed-apps-list/installed-apps-list.component.ts
- src/app/pages/apps/components/installed-apps/installed-apps.component.spec.ts
- src/app/pages/system/enclosure/components/pages/elements-page/elements-page.component.ts
- tsconfig.json
- yarn.lock
**Changes:**
- Add [ngxtension](https://ngxtension.netlify.app/getting-started/introduction/)
- Use `injectParams()` 
**Testing:**
Ensure no regressions in updated places.
> NAS-134141 / 25.10 / Use router signals

- src/app/pages/dashboard/widgets/system/common/widget-sys-info.utils.spec.ts
**Changes:**
Fix failed test.
**Testing:**
Code review & CI passed
> NAS-134470 / 25.10 / Fix missing unit tests in master

- src/app/helptext/topbar.ts
- src/app/modules/layout/topbar/topbar.component.ts
git cherry-pick -x c931fc54de0012e15a61949ef0bb4852f12cf3cf
git cherry-pick -x af04b006180ba788b2ba449a497fca7cc05a3d4e
git cherry-pick -x 616db2560b27cb68f3e16b953e8e97175d4c9fe4
git cherry-pick -x 2e04c07bf81801b21f5a513cd134c2ea0c240610
Additional fix: translation for the concatenated string.
Original PR: https://github.com/truenas/webui/pull/11620
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134289
> NAS-134289 / 25.04.0 / Missing space between sentences (by AlexKarpov98)

- src/index.html
> NAS-134424 / 25.10 / Make sure TrueNAS is not being indexed

- src/app/pages/sharing/iscsi/authorized-access/authorized-access-list/authorized-access-list.component.ts
- src/app/pages/sharing/iscsi/extent/extent-list/extent-list.component.ts
- src/app/pages/sharing/iscsi/initiator/initiator-list/initiator-list.component.ts
- src/app/pages/sharing/iscsi/portal/portal-list/portal-list.component.ts
- src/app/pages/sharing/iscsi/target/all-targets/all-targets.component.ts
- src/app/services/iscsi.service.ts
Result:
https://github.com/user-attachments/assets/c9d798cc-c513-4f58-9516-340994c716dd
Original PR: https://github.com/truenas/webui/pull/11627
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134385
> NAS-134385 / 25.04.0 / Cannot retrieve response after adding Authorized access (by AlexKarpov98)

- src/app/pages/instances/components/instance-wizard/instance-wizard.component.spec.ts
- src/app/pages/instances/components/instance-wizard/instance-wizard.component.ts
Original PR: https://github.com/truenas/webui/pull/11651
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134482
> NAS-134482 / 25.04.0 / The webui should tighten up pre-submission validation of incus instance names (by AlexKarpov98)

- src/app/pages/system/general-settings/ntp-server/ntp-server-form/ntp-server-form.component.html
- src/app/pages/system/general-settings/ntp-server/ntp-server-form/ntp-server-form.component.spec.ts
Result:
https://github.com/user-attachments/assets/1e064a2f-6587-4ed0-be6e-a36c4272c381
> NAS-134459 / 25.10 / NTP host addition

- src/app/pages/system/general-settings/ntp-server/ntp-server-form/ntp-server-form.component.html
- src/app/pages/system/general-settings/ntp-server/ntp-server-form/ntp-server-form.component.spec.ts
Result:
https://github.com/user-attachments/assets/1e064a2f-6587-4ed0-be6e-a36c4272c381
Original PR: https://github.com/truenas/webui/pull/11659
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134459
> NAS-134459 / 25.04.0 / NTP host addition (by AlexKarpov98)

- src/app/pages/instances/components/all-instances/instance-details/instance-disks/instance-disk-form/instance-disk-form.component.ts
- src/app/pages/instances/components/instance-wizard/instance-wizard.component.ts
- src/app/services/filesystem.service.ts
Testing: see ticket description.
> NAS-134555 / 25.10 / Remove ability to set zvol as a container disk

- src/app/pages/instances/components/all-instances/instance-details/instance-general-info/instance-edit-form/instance-edit-form.component.html
- src/app/pages/instances/components/all-instances/instance-details/instance-general-info/instance-edit-form/instance-edit-form.component.spec.ts
- src/app/pages/instances/components/all-instances/instance-details/instance-general-info/instance-edit-form/instance-edit-form.component.ts
> NAS-134504 / 25.10 / Edit Instance Screen Shows Environment Variables for VMs

- src/app/pages/instances/components/all-instances/instance-details/instance-disks/instance-disk-form/instance-disk-form.component.ts
- src/app/pages/instances/components/instance-wizard/instance-wizard.component.ts
- src/app/services/filesystem.service.ts
Testing: see ticket description.
Original PR: https://github.com/truenas/webui/pull/11669
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134555
> NAS-134555 / 25.04.0 / Remove ability to set zvol as a container disk (by AlexKarpov98)

- src/app/pages/instances/components/all-instances/instance-details/instance-general-info/instance-edit-form/instance-edit-form.component.html
- src/app/pages/instances/components/all-instances/instance-details/instance-general-info/instance-edit-form/instance-edit-form.component.spec.ts
- src/app/pages/instances/components/all-instances/instance-details/instance-general-info/instance-edit-form/instance-edit-form.component.ts
Result:
Original PR: https://github.com/truenas/webui/pull/11660
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134504
> NAS-134504 / 25.04.0 / Edit Instance Screen Shows Environment Variables for VMs (by AlexKarpov98)

- src/app/pages/instances/components/all-instances/instance-details/instance-details.component.html
- src/app/pages/instances/components/all-instances/instance-details/instance-details.component.spec.ts
- src/app/pages/instances/components/all-instances/instance-details/instance-details.component.ts
- src/app/pages/instances/components/all-instances/instance-details/instance-idmap/instance-idmap.component.ts
- src/app/pages/instances/components/instance-wizard/instance-wizard.component.html
- src/app/pages/instances/components/instance-wizard/instance-wizard.component.spec.ts
- src/app/pages/instances/components/instance-wizard/instance-wizard.component.ts
|Documentation   | Proxies are no longer available for VM instances.
> NAS-134553 / 25.10 / Hide proxies for VMs

- src/app/pages/instances/components/all-instances/instance-details/instance-details.component.html
- src/app/pages/instances/components/all-instances/instance-details/instance-details.component.spec.ts
- src/app/pages/instances/components/all-instances/instance-details/instance-details.component.ts
- src/app/pages/instances/components/all-instances/instance-details/instance-idmap/instance-idmap.component.ts
- src/app/pages/instances/components/instance-wizard/instance-wizard.component.html
- src/app/pages/instances/components/instance-wizard/instance-wizard.component.spec.ts
- src/app/pages/instances/components/instance-wizard/instance-wizard.component.ts
git cherry-pick -x 66389909f1ad2d19cf8036d40e710b157d3f4e3a
git cherry-pick -x a64b78e2e8117b6d481098688f5d73895a4ab6e6
|Documentation   | Proxies are no longer available for VM instances.
Original PR: https://github.com/truenas/webui/pull/11679
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134553
> NAS-134553 / 25.04.0 / Hide proxies for VMs (by undsoft)

- src/app/modules/use-enterprise-marketing-link/use-enterprise-marketing-link.component.scss
- src/app/pages/dashboard/widgets/system/common/widget-sys-info.scss
- src/app/pages/dashboard/widgets/system/widget-sys-info-active/widget-sys-info-active.component.html
- src/app/pages/dashboard/widgets/system/widget-sys-info-active/widget-sys-info-active.component.scss
- src/app/pages/dashboard/widgets/system/widget-sys-info-active/widget-sys-info-active.component.spec.ts
- src/app/pages/dashboard/widgets/system/widget-sys-info-active/widget-sys-info-active.component.ts
- src/app/pages/dashboard/widgets/system/widget-sys-info-passive/widget-sys-info-passive.component.html
- src/app/pages/dashboard/widgets/system/widget-sys-info-passive/widget-sys-info-passive.component.scss
- src/app/pages/dashboard/widgets/system/widget-sys-info-passive/widget-sys-info-passive.component.spec.ts
- src/app/pages/dashboard/widgets/system/widget-sys-info-passive/widget-sys-info-passive.component.ts
Testing: see ticket + comment.
Removed code duplications and used `<ng-container *ngTemplateOutlet="skeletonLoader"></ng-container>` instead.
Result:
> NAS-134605 / 25.10 / TrueNAS hint does not look good when there is a serial number

- src/app/modules/auth/auth-guard.service.spec.ts
- src/app/modules/auth/auth-guard.service.ts
- src/app/pages/signin/store/signin.store.spec.ts
- src/app/pages/signin/store/signin.store.ts
git cherry-pick -x 16770fd1c854d04751adea5352feab796a37c474
git cherry-pick -x 1870bf779f8be448306ee281269137b73b1354a3
git cherry-pick -x 65a602d1bb79e225105da02044a505e0b6c24536
**Testing:**
See ticket.
Original PR: https://github.com/truenas/webui/pull/11689
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134610
> NAS-134610 / 25.04.0 / "Input should be a valid string" when reloading ACL editor (by undsoft)

- src/app/pages/instances/components/all-instances/instance-list/instance-list.component.ts
**Changes:**
Avoids selecting an instance row when it's already the last selected instance
**Testing:**
See ticket
> NAS-134631 / 25.10 / Fixes reselection when instance is already selected

- src/app/pages/instances/components/all-instances/instance-list/instance-list.component.spec.ts
- src/app/pages/instances/components/all-instances/instance-list/instance-list.component.ts
- src/app/pages/instances/stores/virtualization-instances.store.ts
git cherry-pick -x 26100b95c2b595fc9c5e59b66e7775fa629c28d4
git cherry-pick -x 4c3e29c7c696868457562aefedd5b446ddebbea0
git cherry-pick -x 9e8a8f917173e0b1b74c10f935c6e8b0f25aed01
git cherry-pick -x adbd41a8877e9eea1612b77b35487a9018fc947c
**Changes:**
Fix instance is not selected when it is created
**Testing:**
This PR was changed from the original one. Ensure that the instances page redirects:
1. to the given route param (change URL manually)
2. to the first item when no route param
3. to the first item when an invalid route param
4. to the newly created instance
Original PR: …
> NAS-133871 / 25.04.0 / Fix virt instance is not selected when it is created (by denysbutenko)

- src/app/modules/layout/admin-layout/admin-layout.component.html
- src/app/modules/layout/admin-layout/admin-layout.component.scss
- src/app/modules/layout/admin-layout/admin-layout.component.ts
- src/app/modules/layout/topbar/truenas-logo/truenas-logo.component.html
- src/app/modules/layout/topbar/truenas-logo/truenas-logo.component.scss
- src/app/modules/layout/topbar/truenas-logo/truenas-logo.component.spec.ts
- src/app/modules/layout/topbar/truenas-logo/truenas-logo.component.ts
git cherry-pick -x b5bfe481d1859179c88cebf9b9890ac385983723
git cherry-pick -x 57e963458bfcf0f8fb2975ef0092e89efc5046be
git cherry-pick -x 4cd81636ca38e68679cd30f15e77011b47d4391e
git cherry-pick -x a581003758616e16724d317977a9e93a237e43f2
git cherry-pick -x 57e95d60cb3dbb55fc307a4f4fd1d0b304183a45
As well Logo is fixed for different themes.
Result:
https://github.com/user-attachments/assets/062f600f-9337-441b-b791-331db2af676f
Original PR: https://github.com/truenas/webui/pull/11710
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134290
> NAS-134290 / 25.04.0 / Update TrueNAS logo with input from Marketing (by AlexKarpov98)

- src/app/modules/use-enterprise-marketing-link/use-enterprise-marketing-link.component.scss
- src/app/pages/dashboard/widgets/system/common/widget-sys-info.scss
- src/app/pages/dashboard/widgets/system/widget-sys-info-active/widget-sys-info-active.component.html
- src/app/pages/dashboard/widgets/system/widget-sys-info-active/widget-sys-info-active.component.scss
- src/app/pages/dashboard/widgets/system/widget-sys-info-active/widget-sys-info-active.component.spec.ts
- src/app/pages/dashboard/widgets/system/widget-sys-info-active/widget-sys-info-active.component.ts
- src/app/pages/dashboard/widgets/system/widget-sys-info-passive/widget-sys-info-passive.component.html
- src/app/pages/dashboard/widgets/system/widget-sys-info-passive/widget-sys-info-passive.component.scss
- src/app/pages/dashboard/widgets/system/widget-sys-info-passive/widget-sys-info-passive.component.spec.ts
- src/app/pages/dashboard/widgets/system/widget-sys-info-passive/widget-sys-info-passive.component.ts
git cherry-pick -x 3bcdd2cb595986fedf92a3d30dc3c016878febff
git cherry-pick -x f61e19fdf578d7f1e1e00683f11b72e20f70713c
git cherry-pick -x 2f348bef483514c17a4b5c5425f90fe76ae96e15
git cherry-pick -x b84f0edb6a1781d808e543ee425759ced5696e7b
Testing: see ticket + comment.
Removed code duplications and used `<ng-container *ngTemplateOutlet="skeletonLoader"></ng-container>` instead.
Result:
Original PR: https://github.com/truenas/webui/pull/11692
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134605
> NAS-134605 / 25.04.0 / TrueNAS hint does not look good when there is a serial number (by AlexKarpov98)

- src/app/pages/apps/components/docker-registries/docker-registry-form/docker-registry-form.component.html
- src/app/pages/apps/components/docker-registries/docker-registry-form/docker-registry-form.component.ts
Testing: see ticket & comments section.
> NAS-134706 / 25.10 / Improve URI validation in Create Docker Registry screen

- src/app/modules/alerts/components/alerts-panel/alerts-panel.component.spec.ts
- src/app/modules/alerts/store/alert.reducer.ts
Alerts will be sorted by level, then by date, then by class.
More alerts are available on m40.
> NAS-134326 / 25.10 / Change how alerts are sorted

- src/app/pages/apps/components/docker-registries/docker-registry-form/docker-registry-form.component.html
- src/app/pages/apps/components/docker-registries/docker-registry-form/docker-registry-form.component.ts
Testing: see ticket & comments section.
Original PR: https://github.com/truenas/webui/pull/11727
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134706
> NAS-134706 / 25.04.0 / Improve URI validation in Create Docker Registry screen (by AlexKarpov98)

- src/app/pages/apps/components/installed-apps/app-settings-button/app-settings-button.component.spec.ts
- src/app/pages/apps/components/installed-apps/app-settings-button/app-settings-button.component.ts
**Changes:**
[Load apps catalog when pool is updated](https://github.com/truenas/webui/commit/b07f454c31a3b7d6b8cb69e4aaff49e42333b48f)
**Testing:**
Check JIRA for details
Original PR: https://github.com/truenas/webui/pull/11735
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134490
> NAS-134490 / 25.04.0 / Load apps catalog when pool is updated (by denysbutenko)

- src/app/constants/explore-nas-enterprise-link.constant.ts
- src/app/helpers/hash-message.spec.ts
- src/app/helpers/hash-message.ts
- src/app/modules/layout/admin-layout/admin-layout.component.html
- src/app/modules/layout/admin-layout/admin-layout.component.scss
- src/app/modules/layout/admin-layout/admin-layout.component.ts
- src/app/modules/use-enterprise-marketing-link/use-enterprise-marketing-link.component.spec.ts
- src/app/modules/use-enterprise-marketing-link/use-enterprise-marketing-link.component.ts
Original PR: https://github.com/truenas/webui/pull/11736
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134785
> NAS-134785 / 25.04.0 / Hyperlink gray COMMUNITY EDITION box in footer to Community->Enterprise page (by AlexKarpov98)

- README.md
- docs/contributing_code.md
- docs/setup.md
Minor fixes. Code review is enough.
> NAS-134855 / 25.10 / Fixes for docs

- README.md
- docs/contributing_code.md
> NAS-134855 / 25.10 / More docs updates.

- src/app/modules/layout/admin-layout/admin-layout.component.html
- src/app/pages/dashboard/widgets/system/widget-sys-info-active/widget-sys-info-active.component.html
- src/app/pages/dashboard/widgets/system/widget-sys-info-passive/widget-sys-info-passive.component.html
**Changes:**
Adds tooltip to hostname item in sys-info card
**Testing:**
See that tooltip exists
> NAS-134719 / 25.10 / Add tooltip to hostname item in sys-info card

- package.json
- src/app/modules/websocket/websocket-handler.service.ts
- src/app/pages/dashboard/widgets/storage/widget-storage/widget-storage.component.ts
- src/app/services/errors/error-handler.service.ts
- src/main.ts
Minor adjustments to Sentry. Code review is enough.
> NAS-134871 / 25.10 / Fix some Sentry issues

- src/app/pages/sharing/iscsi/portal/portal-form/portal-form.component.html
- src/app/pages/sharing/iscsi/portal/portal-form/portal-form.component.ts
Result:
https://github.com/user-attachments/assets/ff2a499c-cd89-43bb-91eb-50b9c6ae13b2
> NAS-134873 / 25.10 / iSCSI Portal form can be submitted without required `IP Address` field

- src/app/pages/sharing/iscsi/portal/portal-form/portal-form.component.html
- src/app/pages/sharing/iscsi/portal/portal-form/portal-form.component.ts
Result:
https://github.com/user-attachments/assets/ff2a499c-cd89-43bb-91eb-50b9c6ae13b2
Original PR: https://github.com/truenas/webui/pull/11757
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134873
> NAS-134873 / 25.04.0 / iSCSI Portal form can be submitted without required `IP Address` field (by AlexKarpov98)

- src/app/helpers/api.helper.ts
- src/app/interfaces/api-message.interface.ts
- src/app/modules/websocket/subscription-manager.service.spec.ts
- src/app/modules/websocket/subscription-manager.service.ts
**Changes:**
See ticket for explanation.
> NAS-134748 / 25.10 / Properly handle `notify_unsubscribed`

- src/app/pages/apps/components/app-card-logo/app-card-logo.component.spec.ts
- src/app/pages/instances/components/all-instances/all-instances-header/map-user-group-ids-dialog/new-mapping-form/new-mapping-form.component.ts
Result:
https://github.com/user-attachments/assets/599b5711-505b-467b-85f5-af1901ed20b4
Original PR: https://github.com/truenas/webui/pull/11779
Jira URL: https://ixsystems.atlassian.net/browse/NAS-134876
> NAS-134876 / 25.04.1 / Map User And Group IDs does not re-enable Set button (by AlexKarpov98)

- src/app/interfaces/apps-filters-values.interface.ts
- src/app/pages/apps/components/available-apps/available-apps-header/available-apps-header.component.ts
- src/app/pages/apps/store/apps-filter-store.service.spec.ts
- src/app/pages/apps/store/apps-filter-store.service.ts
Result:
**2FA is no longer under `T` letter on sorting:**
> NAS-134995 / 25.10 / Sort Apps by title, not by an internal key string

- docs/contributing_code.md
- docs/contributing_translations.md
- src/app/pages/apps/components/installed-apps/container-logs/container-logs.component.ts
- src/app/pages/dashboard/widgets/storage/widget-storage/widget-storage.component.ts
> NAS-134997 / 25.10 / More Sentry fixes

- src/app/views/sessions/signin/store/signin.store.ts
> NAS-134342: Check for old code earlier

- CLAUDE.md
This may be helpful if you try to use https://docs.anthropic.com/en/docs/agents-and-tools/claude-code/overview
> NAS-135178 / 25.10 / Add claude.md

- src/app/services/download.service.spec.ts
- src/app/services/download.service.ts
**Changes:**
Fix for 401 Unauthorized error.
**Testing:**
See ticket.
> NAS-135036 / 25.10 / Fix http request called twice

- src/app/helptext/topbar.ts
- src/app/modules/dialog/components/update-dialog/update-dialog.component.ts
- src/app/modules/layout/topbar/topbar.component.spec.ts
- src/app/modules/layout/topbar/topbar.component.ts
- src/app/pages/system/update/components/update-actions-card/update-actions-card.component.html
- src/app/pages/system/update/components/update-actions-card/update-actions-card.component.scss
- src/app/pages/system/update/components/update-actions-card/update-actions-card.component.spec.ts
- src/app/pages/system/update/components/update-actions-card/update-actions-card.component.ts
**Changes:**
Minor fix.
**Testing:**
See ticket for details
> NAS-135156 / 25.10 / Fix missing space between sentences

- src/app/pages/storage/components/dashboard-pool/export-disconnect-modal/export-disconnect-modal.component.spec.ts
- src/app/pages/storage/components/dashboard-pool/export-disconnect-modal/export-disconnect-modal.component.ts
> NAS-135313 / 25.10 / Errors are not reported when exporting a pool

- package.json
- src/app/services/errors/error-handler.service.ts
> NAS-135512 / 25.10 / Reduce number of errors logged to Sentry

- src/app/modules/layout/admin-layout/admin-layout.component.html
- src/app/modules/layout/admin-layout/admin-layout.component.scss
- src/app/modules/layout/admin-layout/admin-layout.component.ts
Original PR: https://github.com/truenas/webui/pull/11892
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135322
> NAS-135322 / 25.04.1 / Enterprise banner in menu footer should not link to community upsell site (by AlexKarpov98)

- src/app/pages/signin/signin.component.ts
- src/app/pages/signin/store/signin.store.ts
Manual backport of https://github.com/truenas/webui/pull/11937
> NAS-135388 / 25.04.1 / A banner for STIG disappeared if the system rebooted

- src/app/pages/system/advanced/storage/storage-settings-form/storage-settings-form.component.spec.ts
- src/app/pages/system/advanced/storage/storage-settings-form/storage-settings-form.component.ts
> NAS-135845 / 25.10 / Advanced System Settings Storage 'save' button unresponsive

- src/app/pages/credentials/users/user-api-keys/user-api-keys.component.spec.ts
- src/app/pages/system-tasks/config-reset/config-reset.component.ts
- src/app/pages/system-tasks/failover/failover.component.ts
- src/app/pages/system-tasks/restart/restart.component.ts
- src/app/pages/system-tasks/shutdown/shutdown.component.ts
**Changes:**
Updates login banner to show on failover and other system events.
**Testing:**
You don't have to enable STIG to test it, just add login banner.
> NAS-135938 / 25.04.1 / Show login banner more often

- src/app/pages/system/advanced/ntp-servers/ntp-servers-card/ntp-servers-card.elements.ts
- src/assets/ui-searchable-elements.json
> NAS-135934 / 25.10 / Fix search elements for NTP servers

- src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/storj-provider-form/storj-provider-form.component.html
- src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/storj-provider-form/storj-provider-form.component.spec.ts
- src/app/pages/credentials/backup-credentials/cloud-credentials-form/provider-forms/storj-provider-form/storj-provider-form.component.ts
Original PR: https://github.com/truenas/webui/pull/12015
Jira URL: https://ixsystems.atlassian.net/browse/NAS-135837
> NAS-135837 / 25.04.2 / Allow passing endpoint to Storj credential in UI (by AlexKarpov98)

- src/app/modules/auth/auth.service.spec.ts
- src/app/modules/auth/auth.service.ts
- src/app/pages/credentials/users/first-login-dialog/first-login-dialog.component.html
- src/app/pages/credentials/users/first-login-dialog/first-login-dialog.component.spec.ts
- src/app/pages/credentials/users/first-login-dialog/first-login-dialog.component.ts
**Changes:**
Don't show option to set password for non-local users right after login.
**Testing:**
See ticket
> NAS-135972 / 25.10 / Don't show option to set password for non-local users

- src/app/modules/auth/two-factor-guard.service.spec.ts
- src/app/modules/auth/two-factor-guard.service.ts
git cherry-pick -x b31fc4c4193bf86e47f16f68dab5c31f0cf0e4ec
git cherry-pick -x 8c6cf1d540682743e5ef2dd749f489845c093dd7
git cherry-pick -x b74c469f420302974f9ed5d1fae0470cf65231f6
git cherry-pick -x 852d618025fe1b7aa0b5cead63a917e1eef7ab3a
Preview:
https://github.com/user-attachments/assets/cc19f396-809b-4d53-8a08-7326a39651a1
Original PR: https://github.com/truenas/webui/pull/12076
Jira URL: https://ixsystems.atlassian.net/browse/NAS-136002
> NAS-136002 / 25.04.2 / Second 'Set New Password' dialog appears on STIG OTP users upon login (by AlexKarpov98)

- src/app/modules/slide-ins/components/modal-header/modal-header.component.scss
> NAS-136317 / 25.10 / Form in a Sidenav -> loading bar is not fully visibly

- src/app/pages/data-protection/cloud-backup/cloud-backup-form/cloud-backup-form.component.html
- src/app/pages/data-protection/cloud-backup/cloud-backup-form/cloud-backup-form.component.ts
- src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.html
- src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.ts
- src/app/pages/data-protection/replication/replication-form/sections/source-section/source-section.component.html
- src/app/pages/data-protection/replication/replication-form/sections/source-section/source-section.component.ts
- src/app/pages/data-protection/replication/replication-form/sections/target-section/target-section.component.html
- src/app/pages/data-protection/replication/replication-form/sections/target-section/target-section.component.ts
- src/app/pages/data-protection/replication/replication-wizard/steps/replication-what-and-where/replication-what-and-where.component.ts
- src/app/pages/instances/components/all-instances/instance-details/instance-disks/instance-disk-form/instance-disk-form.component.html
- src/app/pages/instances/components/all-instances/instance-details/instance-disks/instance-disk-form/instance-disk-form.component.ts
- src/app/pages/instances/components/instance-wizard/instance-wizard.component.html
- src/app/pages/instances/components/instance-wizard/instance-wizard.component.ts
> NAS-136260 / 25.10 / Can't create Replication task using the wizard

- .claude/commands/make-pr.md
- .claude/settings.json
**Changes:**
Probably not super useful, but it's somewhat entertaining.
You can use `claude` and  `/make-pr NAS-136373: Automate PR creation` to create a PR.
> NAS-136373: Automate PR creation

- src/app/modules/ix-table/classes/api-data-provider/api-data-provider.ts
- src/app/pages/credentials/new-users/all-users/all-users-header/all-users-header.component.ts
- src/app/pages/credentials/new-users/all-users/all-users.component.html
- src/app/pages/credentials/new-users/all-users/all-users.component.spec.ts
- src/app/pages/credentials/new-users/all-users/all-users.component.ts
- src/app/pages/credentials/new-users/all-users/testing/mock-user-api-data-provider.ts
- src/app/pages/credentials/new-users/all-users/user-list/user-list.component.ts
- src/app/pages/credentials/new-users/all-users/users-data-provider.ts
- src/app/pages/credentials/new-users/all-users/users-search/users-search.component.ts
- src/app/pages/credentials/new-users/router-utils.ts
**Changes:**
Adds a new users-data-provider and uses query-params to select a user and remember them in the url
**Testing:**
Test selecting users and reloading page to see they are still selected
> NAS-135333 / 25.10 / Enable linking to a user via query params

- package.json
- yarn.lock
https://github.com/angular/angular-cli/commit/732639d5df00f2c01fe80c1a28690e749351718f
**Changes:**
Simply updating to latest dot release which includes a number of fixes.
**Testing:**
Building multiple times in a row.
> NAS-136688 / 25.10 / Update angular to fix a race condition into the build:

- .dockerignore
- Dockerfile
**Changes:**
Use stable image from debian and add docker ignore file.
**Testing:**
Docker build
> NAS-136693 / 25.10 / Update and fix docker build

- src/app/pages/credentials/new-users/all-users/all-users.component.spec.ts
- src/app/pages/credentials/new-users/all-users/user-details/user-access-card/user-access-card.component.html
- src/app/pages/credentials/new-users/all-users/user-details/user-access-card/user-access-card.component.spec.ts
- src/app/pages/credentials/new-users/all-users/user-details/user-access-card/user-access-card.component.ts
- src/app/pages/credentials/new-users/all-users/user-details/user-password-card/user-password-card.component.html
- src/app/pages/credentials/users/user-details-row/user-details-row.component.html
**Changes:**
Small fixes
**Testing:**
See ticket
> NAS-136589 / 25.10 / Fixes for users page

- src/app/modules/forms/ix-forms/components/ix-explorer/ix-explorer.component.spec.ts
- src/app/modules/forms/ix-forms/components/ix-explorer/ix-explorer.component.ts
**Changes:**
Makes `ix-explorer` select the node with the path entered in the text field
**Testing:**
See ticket for testing
> NAS-136587 / 25.10 / Makes `ix-explorer` select the node with the path entered in the text field

- src/app/modules/forms/editable/editable.component.scss
- src/app/modules/forms/ix-forms/components/ix-checkbox-list/ix-checkbox-list.component.scss
- src/app/modules/forms/ix-forms/components/ix-checkbox/ix-checkbox.component.scss
- src/app/pages/apps/components/catalog-settings/apps-settings.component.scss
- src/app/pages/system/advanced/global-two-factor-auth/global-two-factor-form/global-two-factor-form.component.html
- src/assets/styles/other/_material-overrides.scss
- src/assets/styles/other/_material-reduction.scss
> NAS-136506 / 25.10 / Minor visual glitches

- src/assets/styles/other/_material-overrides.scss
- src/assets/styles/other/_tn-styles.scss
Preview:
https://github.com/user-attachments/assets/8aff4ac5-6580-4133-9970-14b8e229aba1
> NAS-135519 / 25.10 / Using Paper theme, many dropdowns are barely visible

- src/app/pages/datasets/components/dataset-details-card/dataset-details-card.component.html
- src/app/pages/datasets/components/dataset-details-card/dataset-details-card.component.spec.ts
- src/assets/i18n/uk.json
> NAS-136649 / 25.10 / On Goldeye creating a zvol makes the datasets UI act weird.

- src/app/enums/login-result.enum.ts
- src/app/interfaces/auth.interface.ts
- src/app/modules/auth/auth.service.spec.ts
- src/app/modules/auth/auth.service.ts
- src/app/pages/signin/set-admin-password-form/set-admin-password-form.component.spec.ts
- src/app/pages/signin/set-admin-password-form/set-admin-password-form.component.ts
- src/app/pages/signin/signin-form/signin-form.component.html
- src/app/pages/signin/signin-form/signin-form.component.scss
- src/app/pages/signin/signin-form/signin-form.component.spec.ts
- src/app/pages/signin/signin-form/signin-form.component.ts
**Changes:**
Support redirect
**Testing:**
Try to login on the standby node.
> NAS-136843 / 25.04.2 / NAS-134384: Handle REDIRECT login error (#12118)

- src/app/pages/directory-service/components/directory-services-form/directory-services-form.component.html
- src/app/pages/directory-service/components/directory-services-form/directory-services-form.component.spec.ts
- src/app/pages/directory-service/components/directory-services-form/directory-services-form.component.ts
- src/app/pages/directory-service/directory-services.component.html
- src/app/pages/directory-service/directory-services.component.spec.ts
**Changes:**
Disable Leave and Saving DS form for roles without directory service write.
**Testing:**
Try to save without being a full admin.
> NAS-136839 / 25.10 / Roles support in directory services

- src/app/helptext/directory-service/kerberos-realms-form-list.ts
- src/app/interfaces/kerberos-realm.interface.ts
- src/app/pages/directory-service/components/kerberos-realms-form/kerberos-realms-form.component.html
- src/app/pages/directory-service/components/kerberos-realms-form/kerberos-realms-form.component.spec.ts
- src/app/pages/directory-service/components/kerberos-realms-form/kerberos-realms-form.component.ts
**Changes:**
Adds the `primary_kdc` field to Kerberos Realms form
**Testing:**
Check that the field is saved on create and on edit
> NAS-136760 / 25.10 / Adds the `primary_kdc` field to Kerberos Realms form

- CLAUDE.md
- src/app/constants/stig-password-requirements.constants.ts
- src/app/pages/system/advanced/system-security/system-security-form/system-security-form.component.html
- src/app/pages/system/advanced/system-security/system-security-form/system-security-form.component.scss
- src/app/pages/system/advanced/system-security/system-security-form/system-security-form.component.spec.ts
- src/app/pages/system/advanced/system-security/system-security-form/system-security-form.component.ts
**Changes:**
Fix password policy STIG requirements
**Testing:**
See ticket.
**Preview:**
https://github.com/user-attachments/assets/abfa5c09-ba33-45d1-89e2-ebc730d43700
> NAS-135600 / 25.10 / Fix password policy STIG requirements

- src/app/interfaces/system-update.interface.ts
- src/app/pages/system/update/components/dynamic-markdown/dynamic-markdown.component.html
- src/app/pages/system/update/components/dynamic-markdown/dynamic-markdown.component.scss
- src/app/pages/system/update/components/dynamic-markdown/dynamic-markdown.component.spec.ts
- src/app/pages/system/update/components/dynamic-markdown/dynamic-markdown.component.ts
- src/app/pages/system/update/update.component.html
- src/app/pages/system/update/update.component.scss
- src/app/pages/system/update/update.component.ts
**Changes:**
Show release notes
**Testing:**
Try to update to a version that has a release notes file.
> NAS-136858 / 25.10 / Add releases notes support to update page

- package.json
- src/app/modules/charts/view-chart-gauge/view-chart-gauge.component.ts
- src/app/modules/interface-status-icon/interface-status-icon.component.ts
- src/app/modules/slide-ins/slide-in.ts
- src/app/modules/websocket-debug-panel/services/websocket-debug.service.ts
- src/app/modules/websocket/api.service.spec.ts
- src/app/modules/websocket/api.service.ts
- src/app/modules/websocket/ping.service.ts
- src/app/modules/websocket/subscription-manager.service.spec.ts
- src/app/modules/websocket/subscription-manager.service.ts
- src/app/modules/websocket/websocket-handler.service.ts
- src/app/pages/reports-dashboard/components/line-chart/line-chart.component.ts
- src/app/pages/reports-dashboard/components/report/report.component.spec.ts
- src/app/pages/reports-dashboard/components/report/report.component.ts
- src/app/pages/storage/modules/pool-manager/components/manual-disk-selection/manual-disk-selection.component.spec.ts
- src/app/pages/storage/modules/pool-manager/components/manual-disk-selection/store/manual-disk-selection.store.spec.ts
- src/app/pages/storage/modules/pool-manager/components/manual-disk-selection/store/manual-disk-selection.store.ts
- src/app/pages/storage/modules/pool-manager/components/manual-disk-selection/utils/vdevs-to-manual-selection-vdevs.utils.ts
- src/app/services/errors/sentry-configuration.service.ts
- yarn.lock
> NAS-136933 / 25.10 / Replace 9 year old angular2-uuid with already installed uuid package

- src/app/core/testing/mock-enclosure/mock-enclosure-generator.utils.ts
- src/app/helptext/system/support.ts
- src/app/helptext/topbar.ts
- src/app/modules/layout/copyright-line/copyright-line.component.spec.ts
- src/app/modules/truecommand/components/truecommand-signup-modal/truecommand-signup-modal.component.spec.ts
- src/app/modules/truecommand/components/truecommand-signup-modal/truecommand-signup-modal.component.ts
- src/app/pages/apps/components/install-app-button/install-app-button.component.ts
- src/app/pages/system/general-settings/support/proactive/proactive.component.html
- src/app/pages/system/general-settings/support/proactive/proactive.component.spec.ts
- src/app/pages/system/general-settings/support/sys-info/sys-info.component.spec.ts
- src/app/pages/two-factor-auth/two-factor.component.spec.ts
- src/environments/environment.prod.ts
UPD:
Tests will be fixed. Locally all tests are failing for me. trying to figure it out..
> NAS-136909 / 25.10 / The Proactive Support Screen mentions iXsystems

- src/app/modules/charts/view-chart-gauge/view-chart-gauge.component.ts
- src/app/modules/slide-ins/slide-in.ts
- src/app/modules/websocket/api.service.ts
- src/app/modules/websocket/subscription-manager.service.ts
- src/app/pages/sharing/iscsi/target/all-targets/target-details/iscsi-groups-card/iscsi-groups-card.component.ts
> NAS-136950 / 25.10 / Lint fixes

- src/app/pages/dashboard/widgets/network/widget-interface/widget-interface.utils.ts
> NAS-136954 / 25.10 / Fix interface dashboard widgets

- src/app/interfaces/api/api-call-directory.interface.ts
- src/app/modules/layout/topbar/topbar.component.html
- src/app/modules/layout/topbar/topbar.component.scss
- src/app/modules/layout/topbar/topbar.component.spec.ts
- src/app/modules/layout/topbar/topbar.component.ts
> NAS-136799 / 26.04 / To block feedback/bugs on experimental builds, gray out button.

- src/app/modules/websocket-debug-panel/components/mock-config/mock-config-list/mock-config-list.component.spec.ts
- src/app/modules/websocket-debug-panel/components/mock-config/mock-config-list/mock-config-list.component.ts
**Changes:**
**Testing:**
Configure some mock config with different payloads.
> NAS-137028 / 26.04 / Improve description for mock config item

- src/app/helptext/directory-service/dashboard.ts
- src/app/pages/directory-service/directory-services.component.html
- src/app/pages/directory-service/directory-services.component.spec.ts
- src/app/pages/directory-service/directory-services.component.ts
- src/app/pages/directory-service/directory-services.elements.ts
- src/assets/ui-searchable-elements.json
**Changes:**
Added tests for each card.
Updated LDAP Card content.
Cleanup.
**Testing:**
See ticket.
Preview:
|Documentation   | LDAP Card changes
> NAS-136964 / 26.04 / Directory Services summary for LDAP always shows BindDN

- src/app/helptext/storage/volumes/datasets/dataset-acl.ts
- src/app/pages/datasets/modules/permissions/containers/dataset-acl-editor/acl-editor-save-controls/acl-editor-save-controls.component.html
- src/app/pages/datasets/modules/permissions/containers/dataset-acl-editor/acl-editor-save-controls/acl-editor-save-controls.component.spec.ts
- src/app/pages/datasets/modules/permissions/containers/dataset-acl-editor/acl-editor-save-controls/acl-editor-save-controls.component.ts
- src/app/pages/datasets/modules/permissions/interfaces/dataset-acl-editor-state.interface.ts
- src/app/pages/datasets/modules/permissions/stores/dataset-acl-editor.store.ts
> NAS-135444 / 26.04 / remove Validate effective ACL checkbox

- src/app/modules/forms/ix-forms/components/ix-input/ix-input.component.html
- src/app/modules/forms/ix-forms/components/ix-input/ix-input.component.spec.ts
- src/app/modules/forms/ix-forms/components/ix-input/ix-input.component.ts
- src/app/pages/signin/signin-form/signin-form.component.html
- src/app/pages/signin/signin-form/signin-form.component.spec.ts
- src/app/pages/signin/signin-form/signin-form.component.ts
Testing: 
Just added some suggestions provided by Claude.
I was not able to reproduce in any web browser.
> NAS-136335 / 26.04 / Password managers intermittent recognition of user/pass fields in WebUI login

- src/app/modules/forms/ix-forms/components/ix-input/ix-input.component.html
- src/app/modules/forms/ix-forms/components/ix-input/ix-input.component.spec.ts
- src/app/modules/forms/ix-forms/components/ix-input/ix-input.component.ts
- src/app/pages/signin/signin-form/signin-form.component.html
- src/app/pages/signin/signin-form/signin-form.component.spec.ts
- src/app/pages/signin/signin-form/signin-form.component.ts
Testing: 
Just added some suggestions provided by Claude.
I was not able to reproduce in any web browser.
Original PR: https://github.com/truenas/webui/pull/12395
> NAS-136335 / 25.10-RC.1 / Password managers intermittent recognition of user/pass fields in WebUI login (by AlexKarpov98)

- src/app/pages/datasets/components/zvol-form/zvol-form.component.spec.ts
- src/app/pages/datasets/components/zvol-form/zvol-form.component.ts
**Changes:**
**Testing:**
Create an encrypted dataset
Create an encrypted zvol with different encryption options.
> NAS-137085 / 26.04 / NAS-137084: fix creating non-inherited encrypted zvols

- src/app/pages/datasets/components/zvol-form/zvol-form.component.spec.ts
- src/app/pages/datasets/components/zvol-form/zvol-form.component.ts
**Changes:**
**Testing:**
Create an encrypted dataset
Create an encrypted zvol with different encryption options.
Original PR: https://github.com/truenas/webui/pull/12400
> NAS-137085 / 25.10-RC.1 / NAS-137084: fix creating non-inherited encrypted zvols (by william-gr)

- src/app/interfaces/cloud-sync-task.interface.ts
- src/app/modules/terminal/components/terminal/terminal.component.html
- src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.spec.ts
- src/app/pages/data-protection/cloudsync/cloudsync-list/cloudsync-list.component.ts
- src/app/pages/data-protection/cloudsync/cloudsync-task-card/cloudsync-task-card.component.spec.ts
- src/app/pages/data-protection/cloudsync/cloudsync-task-card/cloudsync-task-card.component.ts
- src/app/pages/data-protection/cloudsync/utils/cloudsync-data-transformer.ts
Sorting should work now.
Preview:
https://github.com/user-attachments/assets/e3b83eb8-2da5-4435-b32a-bcad02b7505e
> NAS-137096 / 26.04 / Time sort for frequency is incorrect

- src/app/interfaces/cloud-sync-task.interface.ts
- src/app/pages/data-protection/cloudsync/cloudsync-form/cloudsync-form.component.spec.ts
- src/app/pages/data-protection/cloudsync/cloudsync-list/cloudsync-list.component.ts
- src/app/pages/data-protection/cloudsync/cloudsync-task-card/cloudsync-task-card.component.spec.ts
- src/app/pages/data-protection/cloudsync/cloudsync-task-card/cloudsync-task-card.component.ts
- src/app/pages/data-protection/cloudsync/utils/cloudsync-data-transformer.ts
Sorting should work now.
Preview:
https://github.com/user-attachments/assets/e3b83eb8-2da5-4435-b32a-bcad02b7505e
Original PR: https://github.com/truenas/webui/pull/12409
> NAS-137096 / 25.10-RC.1 / Time sort for frequency is incorrect (by AlexKarpov98)

- .github/actions/prepare/action.yml
- .github/workflows/main.yml
- package.json
> NAS-137177 / 26.04 / self hosted tests for ux team

- src/app/interfaces/dynamic-form-schema.interface.ts
- src/app/modules/forms/ix-dynamic-form/components/ix-dynamic-form/ix-dynamic-form-item/ix-dynamic-form-item.component.html
- src/app/modules/forms/ix-dynamic-form/components/ix-dynamic-form/ix-dynamic-form-item/ix-dynamic-form-item.component.ts
- src/app/modules/forms/ix-forms/components/ix-code-editor/ix-code-editor.component.ts
see notes ix-code-editor
Preview:
> NAS-137233 / 26.04 / Custom App -> Notes is not rendering any input

- src/app/pages/credentials/new-users/all-users/users-search/users-search.component.spec.ts
- src/app/pages/credentials/new-users/all-users/users-search/users-search.component.ts
**Changes:**
Clears query filters and reverts to default filtering when switching between Basic and Advanced search.
**Testing:**
See ticket
Original PR: https://github.com/truenas/webui/pull/12440
> NAS-137239 / 25.10-RC.1 / reset user search state when toggling between Basic and Advanced (by aervin)

- src/app/helptext/sharing/nvme-of/nvme-of.ts
- src/app/pages/sharing/nvme-of/nvme-of-configuration/nvme-of-configuration.component.spec.ts
- src/app/pages/sharing/nvme-of/nvme-of-configuration/nvme-of-configuration.component.ts
**Changes:**
**Testing:**
Make sure ANA is disabled for non HA systems.
> NAS-137263 / 26.04 / disable ANA for non-HA

- package.json
**Changes:**
Goes with https://github.com/truenas/scale-build/pull/911
**Testing:**
> NAS-137345 / 26.04 / Fix WebUI Debian build

- src/app/modules/master-detail-view/master-detail-view.component.scss
- src/app/pages/apps/components/installed-apps/installed-apps-list/installed-apps-list.component.spec.ts
- src/app/pages/apps/components/installed-apps/installed-apps-list/installed-apps-list.component.ts
- src/app/pages/apps/components/installed-apps/installed-apps.component.html
- src/app/pages/instances/components/all-instances/all-instances.component.html
- src/app/pages/instances/components/all-instances/instance-list/instance-list.component.html
- src/app/pages/instances/components/all-instances/instance-list/instance-list.component.ts
**Changes:**
- Grayed out details when a table row is checked
https://github.com/user-attachments/assets/4545766f-9112-48d5-ae5e-28a7cf6b90f7
**Testing:**
> NAS-133883 / 26.04 / grayed out the details when a row is checked

- scripts/lint.ts
**Changes:**
**Testing:**
yarn lint src/app/some/dicrectory/
> NAS-137349 / 26.04 / Fix scripts/lint.ts to support directory parameters and recursive file discovery

- src/app/interfaces/truenas-connect-config.interface.ts
- src/app/modules/layout/topbar/topbar.component.spec.ts
- src/app/modules/layout/topbar/topbar.component.ts
- src/app/modules/truenas-connect/components/truenas-connect-status-modal/truenas-connect-status-modal.component.spec.ts
- src/app/modules/truenas-connect/components/truenas-connect-status-modal/truenas-connect-status-modal.component.ts
- src/app/modules/truenas-connect/services/truenas-connect.service.spec.ts
- src/app/modules/truenas-connect/services/truenas-connect.service.ts
> NAS-136321 / 26.04 / show TNC header icon by default

- src/app/pages/datasets/modules/permissions/stores/dataset-acl-editor.store.spec.ts
- src/app/pages/datasets/modules/permissions/stores/dataset-acl-editor.store.ts
**Changes:**
**Testing:**
Try to set ACL with boxes checked and unchecked. Verify dataset permissions changes via shell.
Original PR: https://github.com/truenas/webui/pull/12497
> NAS-137378 / 25.04.2.4 / do not pass user/group unless box is checked (by william-gr)

- src/app/modules/slide-ins/slide-in.spec.ts
- src/app/modules/slide-ins/slide-in.ts
When closing a child slide-in (e.g., namespace form in NVMe-oF), the parent slide-in was not becoming visible again, leaving only the overlay backdrop blocking interaction.
The fix ensures the parent container's host element has correct visibility classes when animating back in after a child slide-in closes.
**Changes:**
**Testing:**
Add a namespace when adding a new NVMe oF entry.
> NAS-137417 / 26.04 / Fix parent slide-in not reappearing after closing child slide-in

- src/app/modules/slide-ins/slide-in.spec.ts
- src/app/modules/slide-ins/slide-in.ts
When closing a child slide-in (e.g., namespace form in NVMe-oF), the parent slide-in was not becoming visible again, leaving only the overlay backdrop blocking interaction.
The fix ensures the parent container's host element has correct visibility classes when animating back in after a child slide-in closes.
**Changes:**
**Testing:**
Add a namespace when adding a new NVMe oF entry.
Original PR: https://github.com/truenas/webui/pull/12502
> NAS-137417 / 25.10-RC.1 / Fix parent slide-in not reappearing after closing child slide-in (by william-gr)

- src/app/services/services.service.spec.ts
- src/app/services/services.service.ts
> NAS-137432 / 26.04 / NVMe-of-service is locked for sharing admin (UI)

- src/app/services/services.service.spec.ts
- src/app/services/services.service.ts
Preview:
Original PR: https://github.com/truenas/webui/pull/12511
> NAS-137432 / 25.10-RC.1 / NVMe-of-service is locked for sharing admin (UI) (by AlexKarpov98)

- src/app/pages/reports-dashboard/components/line-chart/line-chart.component.spec.ts
- src/app/pages/reports-dashboard/components/line-chart/line-chart.component.ts
- src/app/pages/reports-dashboard/components/report/report.component.scss
- src/app/pages/reports-dashboard/components/report/report.component.spec.ts
- src/app/pages/reports-dashboard/components/report/report.component.ts
Reporting Charts improvements. (resize issues)
See before:
https://github.com/user-attachments/assets/56cb0531-1c72-4ef7-b07a-e5b819d5a78d
See after:
https://github.com/user-attachments/assets/772b0bf7-c82d-4a84-946d-64e523a2d4ef
> NAS-137272 / 26.04 / Horizontal Scrolling and Key table placement Improvement request

- src/app/interfaces/api/api-call-directory.interface.ts
- src/app/modules/layout/topbar/topbar.component.html
- src/app/modules/layout/topbar/topbar.component.spec.ts
- src/app/modules/layout/topbar/topbar.component.ts
> NAS-137504 / 26.04 / Remove system.experimental

- src/app/modules/forms/editable/editable.component.spec.ts
- src/app/modules/forms/ix-forms/components/ix-input/ix-input.component.html
- src/app/modules/forms/ix-forms/components/ix-input/ix-input.component.spec.ts
- src/app/modules/forms/ix-forms/components/ix-input/ix-input.component.ts
Preview:
Original PR: https://github.com/truenas/webui/pull/12543
> NAS-136335 / 25.10.0 / Password managers intermittent recognition of user/pass fields in WebUI login (by AlexKarpov98)

- src/app/pages/system/network/components/ipmi-card/ipmi-form/ipmi-form.component.spec.ts
- src/app/pages/system/network/components/ipmi-card/ipmi-form/ipmi-form.component.ts
Manage button should be Enabled as long as valid `IPv4 Address` provided. (to **Manage**)
Original PR: https://github.com/truenas/webui/pull/12555
> NAS-137591 / 25.10-RC.1 / System/IPMI/Edit - Manage button disables and doesnt re-enable (by AlexKarpov98)

- src/app/pages/system/network/components/ipmi-card/ipmi-form/ipmi-form.component.spec.ts
- src/app/pages/system/network/components/ipmi-card/ipmi-form/ipmi-form.component.ts
Manage button should be Enabled as long as valid `IPv4 Address` provided. (to **Manage**)
Original PR: https://github.com/truenas/webui/pull/12555
> NAS-137591 / 25.10.0 / System/IPMI/Edit - Manage button disables and doesnt re-enable (by AlexKarpov98)

- src/app/modules/websocket-debug-panel/websocket-debug-panel.component.ts
Enclosure mock should work now, see preview:
https://github.com/user-attachments/assets/1b9887cd-c532-4658-9446-797c7c0554e9
> NAS-137585 / 26.04 / Enclosure Mock is not working

- src/app/modules/websocket-debug-panel/websocket-debug-panel.component.ts
Enclosure mock should work now, see preview:
https://github.com/user-attachments/assets/1b9887cd-c532-4658-9446-797c7c0554e9
Original PR: https://github.com/truenas/webui/pull/12567
> NAS-137585 / 25.10.0 / Enclosure Mock is not working (by AlexKarpov98)

- src/app/modules/test-id/test.directive.ts
- src/app/pages/credentials/users/user-form/additional-details-section/additional-details-section.component.html
- src/app/pages/credentials/users/user-form/additional-details-section/additional-details-section.component.spec.ts
- src/app/pages/credentials/users/user-form/additional-details-section/additional-details-section.component.ts
Check comments here: https://ixsystems.atlassian.net/browse/NAS-137611?focusedCommentId=319994
Preview:
https://github.com/user-attachments/assets/377bbc31-cf83-4b51-b60c-34e1a4aab8b3
> NAS-137611 / 26.04 / User Home Default Permissions checkbox remains checked after changing permissions

- src/app/pages/credentials/users/user-form/auth-section/auth-section.component.html
- src/app/pages/credentials/users/user-form/auth-section/auth-section.component.scss
- src/app/pages/credentials/users/user-form/auth-section/auth-section.component.spec.ts
- src/app/pages/credentials/users/user-form/auth-section/auth-section.component.ts
No validation was present for SSH checkbox logic. Now it's added and form works as expected. Tests added.
Preview:
https://github.com/user-attachments/assets/6c3996f5-8797-40c6-a196-d8a4265965ce
> NAS-137646 / 26.04 / User UI: Enabling SSH access does not save although the text says that the user was updated

- src/app/pages/credentials/users/user-form/allowed-access-section/allowed-access-section.component.ts
- src/app/pages/credentials/users/user-form/user-form.component.ts
**Testing:**
See ticket. Add existing group to full admin privilege and edit that user to see role.
Original PR: https://github.com/truenas/webui/pull/12597
> NAS-137673 / 25.10.0 / fix default value for role on user edit (by william-gr)

- src/app/pages/credentials/users/user-form/allowed-access-section/allowed-access-section.component.ts
- src/app/pages/credentials/users/user-form/user-form.component.ts
**Testing:**
See ticket. Add existing group to full admin privilege and edit that user to see role.
Original PR: https://github.com/truenas/webui/pull/12597
> NAS-137673 / 25.10-RC.1 / fix default value for role on user edit (by william-gr)

- src/app/modules/forms/search-input/components/advanced-search/advanced-search.component.scss
> NAS-137656 / 26.04 / Calendar on audit page is not rendered correctly

- src/app/enums/smb-protocol.enum.ts
- src/app/helptext/services/components/service-smb.ts
- src/app/interfaces/smb-config.interface.ts
- src/app/pages/services/components/service-smb/service-smb.component.html
- src/app/pages/services/components/service-smb/service-smb.component.spec.ts
- src/app/pages/services/components/service-smb/service-smb.component.ts
**Changes:**
**Testing:**
https://github.com/user-attachments/assets/5a630863-89fe-48d4-a1f4-ce5c5ea499c8
> NAS-137506 / 26.04 / added search protocols field in smb settings

- .claude/commands/review-branch.md
- .claude/review-prompt.md
- .github/workflows/claude.yml
Prompt is shared between that and github review.
Simply use /review-branch in Claude CLI.
> NAS-137881 / 26.04 / Add review-branch command to Claude CLI

- src/app/pages/data-protection/cloud-backup/cloud-backup-details/cloud-backup-restore-form-snapshot-form/cloud-backup-restore-from-snapshot-form.component.html
- src/app/pages/data-protection/cloud-backup/cloud-backup-details/cloud-backup-restore-form-snapshot-form/cloud-backup-restore-from-snapshot-form.component.spec.ts
- src/app/pages/data-protection/cloud-backup/cloud-backup-details/cloud-backup-restore-form-snapshot-form/cloud-backup-restore-from-snapshot-form.component.ts
Preview:
https://github.com/user-attachments/assets/3839ee5e-b107-4f65-a26a-5c5c62e58597
Original PR: https://github.com/truenas/webui/pull/12628
> NAS-137729 / 25.10.0 / TrueCloud Backup Task > Restore from Snapshot, "Included Paths" field is constantly updating (by AlexKarpov98)
